import { useState } from "react";
import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import { getLoginUrl } from "@/const";
import MarketingLayout from "@/components/MarketingLayout";
import {
  Shield, Lock, Server, Eye, Key, Database, Cpu, Globe,
  CheckCircle2, ChevronDown, ChevronUp, ArrowRight, HardDrive,
  FileCode, Users, AlertCircle, Zap, Menu, X,
} from "lucide-react";

function FAQItem({ question, answer }: { question: string; answer: string }) {
  const [open, setOpen] = useState(false);
  return (
    <div className="border-b border-white/5 last:border-0">
      <button onClick={() => setOpen(!open)} className="w-full flex items-center justify-between py-5 text-left gap-4 group">
        <span className="text-sm sm:text-base font-medium text-white/80 group-hover:text-white transition-colors">{question}</span>
        {open ? <ChevronUp className="h-4 w-4 text-white/40 shrink-0" /> : <ChevronDown className="h-4 w-4 text-white/40 shrink-0" />}
      </button>
      {open && <div className="pb-5"><p className="text-sm text-white/50 leading-relaxed">{answer}</p></div>}
    </div>
  );
}

export default function SecurityPage() {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);

  const pillars = [
    {
      icon: HardDrive,
      title: "Local-first architecture",
      color: "text-blue-400",
      bg: "bg-blue-500/10",
      border: "border-blue-500/20",
      desc: "Titan runs on your machine. Your prompts, credentials, and outputs are processed locally by default. Nothing is sent to external servers unless you explicitly choose to deploy or export.",
      points: ["All AI inference runs in your local environment", "No telemetry or usage data sent to Archibald Titan servers", "Outputs stay on disk until you export or deploy them", "Works fully offline once set up"],
    },
    {
      icon: Lock,
      title: "AES-256 encrypted vault",
      color: "text-emerald-400",
      bg: "bg-emerald-500/10",
      border: "border-emerald-500/20",
      desc: "Every credential stored in Titan is encrypted at rest using AES-256-GCM with a key derived from your master password via PBKDF2. Your master password never leaves your device.",
      points: ["AES-256-GCM encryption at rest", "PBKDF2 key derivation — master password never transmitted", "Zero-knowledge design: Archibald Titan cannot read your vault", "Vault locked automatically on inactivity"],
    },
    {
      icon: Cpu,
      title: "Sandboxed execution",
      color: "text-purple-400",
      bg: "bg-purple-500/10",
      border: "border-purple-500/20",
      desc: "Code generated by Titan Builder runs in an isolated sandbox environment. Scripts cannot access your host filesystem, network, or system resources unless you explicitly grant permission.",
      points: ["Isolated execution environment for all generated code", "No host filesystem access by default", "Network calls blocked unless explicitly enabled", "Sandbox destroyed after each run — no state persistence"],
    },
    {
      icon: Eye,
      title: "Audit trail",
      color: "text-amber-400",
      bg: "bg-amber-500/10",
      border: "border-amber-500/20",
      desc: "Every action in Titan is logged to a tamper-evident local audit trail. Enterprise plans include structured logs exportable to SIEM tools.",
      points: ["Full action log: who did what, when, from which IP", "Tamper-evident log format", "SIEM export (Enterprise+)", "Retention policy configurable per deployment"],
    },
    {
      icon: Key,
      title: "Model and provider controls",
      color: "text-cyan-400",
      bg: "bg-cyan-500/10",
      border: "border-cyan-500/20",
      desc: "You choose which AI models and providers Titan uses. You can restrict to local-only models, block specific providers, or require approval before any external API call is made.",
      points: ["Choose your own model provider (local, OpenAI, Anthropic, etc.)", "Block external providers entirely for air-gapped deployments", "Per-user provider restrictions on team plans", "API key rotation and expiry controls"],
    },
    {
      icon: Users,
      title: "Team governance",
      color: "text-rose-400",
      bg: "bg-rose-500/10",
      border: "border-rose-500/20",
      desc: "Enterprise plans include role-based access control, shared credential vaults with permission scoping, and centralized policy enforcement across your team.",
      points: ["Role-based access control (RBAC)", "Shared vault with per-secret permission scoping", "Admin policy enforcement — restrict features by role", "SSO / SAML integration for enterprise identity providers"],
    },
  ];

  const certifications = [
    { label: "AES-256-GCM", desc: "Vault encryption standard" },
    { label: "PBKDF2", desc: "Key derivation function" },
    { label: "TLS 1.3", desc: "All network transport" },
    { label: "Zero-knowledge", desc: "Vault design" },
    { label: "Local-first", desc: "Default data residency" },
    { label: "RBAC", desc: "Enterprise access control" },
    { label: "SIEM export", desc: "Enterprise audit logs" },
    { label: "Air-gap ready", desc: "Offline deployment" },
  ];

  return (
    <MarketingLayout>
      {/* HERO */}
      <section className="relative pt-32 pb-20 sm:pt-40 sm:pb-28">
        <div className="absolute inset-0 overflow-hidden">
          <div className="absolute top-1/4 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[500px] bg-emerald-600/8 rounded-full blur-[130px]" />
          <div className="absolute bottom-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-emerald-500/20 to-transparent" />
        </div>
        <div className="relative max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full border border-emerald-500/20 bg-emerald-500/5 mb-8">
            <Shield className="h-3.5 w-3.5 text-emerald-400" />
            <span className="text-xs font-medium text-emerald-300">Security & Privacy Architecture</span>
          </div>
          <h1 className="text-4xl sm:text-5xl lg:text-6xl font-black tracking-tight leading-[1.05]">
            <span className="text-white">Built for workflows</span><br />
            <span className="bg-gradient-to-r from-emerald-400 via-teal-400 to-cyan-500 bg-clip-text text-transparent">where data stays yours.</span>
          </h1>
          <p className="mt-6 text-lg sm:text-xl text-white/50 max-w-2xl mx-auto leading-relaxed">
            Titan is designed local-first. Your credentials, prompts, and outputs are processed on your machine by default — not sent to our servers, not stored in the cloud, not shared with anyone.
          </p>
          <div className="mt-8 flex flex-wrap items-center justify-center gap-x-8 gap-y-3">
            {[
              { icon: Lock, label: "AES-256 vault" },
              { icon: HardDrive, label: "Local-first" },
              { icon: Cpu, label: "Sandboxed execution" },
              { icon: Eye, label: "Full audit trail" },
            ].map((item) => (
              <div key={item.label} className="flex items-center gap-2 text-sm text-white/40">
                <item.icon className="h-4 w-4 text-emerald-400/60" />{item.label}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* SECURITY PILLARS */}
      <section className="relative py-20 sm:py-28">
        <div className="relative max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <span className="text-sm font-semibold text-emerald-400 tracking-widest uppercase">Architecture</span>
            <h2 className="mt-3 text-3xl sm:text-4xl font-bold tracking-tight">Six layers of security</h2>
            <p className="mt-4 text-white/50 max-w-2xl mx-auto">Every layer is designed to keep your data under your control, whether you are a solo developer or an enterprise team.</p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {pillars.map((p) => (
              <div key={p.title} className={`p-6 rounded-2xl border ${p.border} bg-white/[0.02] hover:bg-white/[0.04] transition-all duration-300`}>
                <div className={`inline-flex p-2.5 rounded-xl ${p.bg} mb-4`}>
                  <p.icon className={`h-5 w-5 ${p.color}`} />
                </div>
                <h3 className="text-base font-semibold text-white mb-2">{p.title}</h3>
                <p className="text-sm text-white/50 leading-relaxed mb-4">{p.desc}</p>
                <ul className="space-y-1.5">
                  {p.points.map((pt) => (
                    <li key={pt} className="flex items-start gap-2 text-xs text-white/40">
                      <CheckCircle2 className={`h-3.5 w-3.5 ${p.color} shrink-0 mt-0.5`} />{pt}
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* DATA FLOW DIAGRAM (text-based) */}
      <section className="relative py-20 sm:py-24 bg-white/[0.01]">
        <div className="relative max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <span className="text-sm font-semibold text-emerald-400 tracking-widest uppercase">Data Flow</span>
            <h2 className="mt-3 text-3xl sm:text-4xl font-bold tracking-tight">Where your data goes</h2>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            {[
              { step: "01", label: "Your machine", desc: "Prompts written, credentials stored, outputs generated — all locally.", icon: Server, color: "text-blue-400", border: "border-blue-500/20", bg: "bg-blue-500/5" },
              { step: "02", label: "Local AI runtime", desc: "Inference runs in your local environment. No prompt data sent to Archibald Titan.", icon: Cpu, color: "text-purple-400", border: "border-purple-500/20", bg: "bg-purple-500/5" },
              { step: "03", label: "External only if you choose", desc: "Deploy, export, or call external APIs only when you explicitly trigger it.", icon: Globe, color: "text-emerald-400", border: "border-emerald-500/20", bg: "bg-emerald-500/5" },
            ].map((item) => (
              <div key={item.step} className={`p-6 rounded-2xl border ${item.border} ${item.bg}`}>
                <div className="text-xs font-bold text-white/20 mb-3">{item.step}</div>
                <item.icon className={`h-6 w-6 ${item.color} mb-3`} />
                <h3 className="text-sm font-semibold text-white mb-2">{item.label}</h3>
                <p className="text-xs text-white/50 leading-relaxed">{item.desc}</p>
              </div>
            ))}
          </div>
          <div className="mt-8 p-5 rounded-2xl border border-white/5 bg-white/[0.02]">
            <div className="flex items-start gap-3">
              <AlertCircle className="h-5 w-5 text-amber-400 shrink-0 mt-0.5" />
              <div>
                <p className="text-sm font-medium text-white/80 mb-1">What we do collect</p>
                <p className="text-sm text-white/40 leading-relaxed">When you use cloud-connected features (e.g. Titan marketplace, team sync, or cloud backup), we collect only what is necessary to deliver that feature. We never sell data. Full details in our <Link href="/privacy" className="text-blue-400 hover:text-blue-300 underline underline-offset-2">Privacy Policy</Link>.</p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* STANDARDS STRIP */}
      <section className="relative py-16">
        <div className="relative max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-10">
            <span className="text-sm font-semibold text-white/40 tracking-widest uppercase">Standards & Protocols</span>
          </div>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
            {certifications.map((c) => (
              <div key={c.label} className="p-4 rounded-xl border border-white/5 bg-white/[0.02] text-center">
                <div className="text-sm font-bold text-white mb-1">{c.label}</div>
                <div className="text-xs text-white/40">{c.desc}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="relative py-20 sm:py-28">
        <div className="relative max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <span className="text-sm font-semibold text-emerald-400 tracking-widest uppercase">FAQ</span>
            <h2 className="mt-3 text-3xl sm:text-4xl font-bold tracking-tight">Security questions</h2>
          </div>
          <div className="divide-y divide-white/5">
            <FAQItem question="Does Archibald Titan have access to my vault?" answer="No. Your vault is encrypted with a key derived from your master password using PBKDF2. Your master password never leaves your device, and Archibald Titan servers never receive your encryption key. This is a zero-knowledge design — we cannot read your vault even if we wanted to." />
            <FAQItem question="Can I run Titan completely offline?" answer="Yes. Titan is designed to run fully offline once installed. All AI inference, credential management, and build operations run locally. You only need internet access for optional features like marketplace, team sync, or cloud backup." />
            <FAQItem question="What happens to my prompts?" answer="Your prompts are processed locally by the AI runtime on your machine. They are not sent to Archibald Titan servers. If you choose to use a cloud AI provider (e.g. OpenAI), your prompts are sent directly to that provider under their terms — not routed through our servers." />
            <FAQItem question="Is the sandbox truly isolated?" answer="Yes. Generated code runs in a sandboxed environment that cannot access your host filesystem, network, or system resources unless you explicitly grant permission. The sandbox is destroyed after each run." />
            <FAQItem question="What encryption does the vault use?" answer="AES-256-GCM for encryption at rest. Keys are derived using PBKDF2 with a high iteration count. The vault is locked automatically after a configurable inactivity period." />
            <FAQItem question="Do you support enterprise compliance requirements?" answer="Enterprise plans include RBAC, SIEM-compatible audit log export, SSO/SAML integration, and on-premise deployment options. Contact us to discuss specific compliance requirements." />
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="relative py-20 sm:py-28">
        <div className="absolute inset-0 overflow-hidden">
          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[300px] bg-emerald-600/8 rounded-full blur-[120px]" />
        </div>
        <div className="relative max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-3xl sm:text-4xl font-bold tracking-tight">Build with confidence</h2>
          <p className="mt-4 text-white/50 text-lg max-w-xl mx-auto">Titan is designed for teams and individuals who cannot afford to compromise on data security.</p>
          <div className="mt-8 flex flex-col sm:flex-row items-center justify-center gap-4">
            <Button size="lg" onClick={() => { window.location.href = getLoginUrl(); }} className="bg-blue-600 hover:bg-blue-500 text-white border-0 shadow-xl shadow-blue-600/25 h-14 px-10 text-base font-semibold gap-3">
              <Zap className="h-5 w-5" /> Get Started Free
            </Button>
            <Link href="/contact">
              <Button size="lg" variant="outline" className="border-white/10 bg-white/5 hover:bg-white/10 text-white h-12 px-8 text-base">
                Talk to Security Team <ArrowRight className="ml-2 h-4 w-4" />
              </Button>
            </Link>
          </div>
        </div>
      </section>
    </MarketingLayout>
  );
}