#!/usr/bin/env python3
"""Fill upgrade_k.jsonl to 200 pairs"""
import json, pathlib

OUT = pathlib.Path('/workspace/data_upgrades')

pairs = [
    ("What is satisficing in behavioral economics?", "Simon's satisficing: agents choose the first option that meets a satisfactory threshold rather than optimising over all possibilities. Satisficing is computationally cheap and robust when optimising is costly. In consumer choice, people often choose the first acceptable product rather than the best. It is rational under search costs but may lead to suboptimal choices when better options are easily available."),
    ("What is the Allais paradox?", "The Allais paradox shows most people violate expected utility theory. They prefer a certain 1M to a lottery (0.89 chance of 1M, 0.10 of 5M, 0.01 of 0) -- but also prefer 0.10 chance of 5M over 0.11 chance of 1M. These choices are inconsistent under EU theory. The paradox motivated prospect theory's probability weighting function."),
    ("What is the psychology of discounts?", "Discounts are psychologically framed as gains relative to a reference price. Large nominal discounts feel better than equivalent absolute savings on cheap goods. Percent framing works better for large base prices; absolute framing for small ones. Artificial reference prices exploit anchoring. The rule of 100: use percent off for prices below $100, absolute amount off above $100."),
    ("What is the behavioral economics of information overload?", "When too much information is provided, people paradoxically make worse decisions than with limited information. Information overload causes decision paralysis and increased reliance on heuristics. Policy: simple disclosure often outperforms comprehensive disclosure for complex financial decisions. Key facts documents and traffic light labelling reduce overload by distilling essential decision-relevant information."),
    ("What is the behavioral market hypothesis?", "The behavioral market hypothesis argues that prices deviate predictably from fundamental values because of investor biases: overconfidence, loss aversion, representativeness, and herding. Limits to arbitrage prevent rational investors from correcting mispricings. Markets are mostly efficient but behaviorally predictable patterns exist, exploitable by disciplined, patient investors."),
    ("What is the economics of willpower?", "Willpower is limited and fatigues with use (decision fatigue). Judges grant fewer paroles after lunch; consumers choose less healthily later in the day. Economic design should reduce the need for willpower through better defaults, simplified choices, and environments that make good choices the easy choice. Building habits is more sustainable than relying on repeated acts of willpower."),
    ("What is the behavioral economics of inequality?", "Inequality affects behaviour through positional concerns (status-seeking arms races), reduced trust in high-inequality societies, and scarcity-induced cognitive load among the poor. Behaviorally, inequality perpetuates itself through motivational, cognitive, and social channels beyond material deprivation. Progressive consumption taxes address positional externalities."),
    ("What is the role of deadlines in overcoming procrastination?", "Deadlines counteract procrastination by creating a near-term salient cost for non-completion. Periodic intermediate deadlines outperform single end-of-period deadlines. In tax filing, reminders two weeks before deadlines outperform day-before reminders because people still have time to act. Commitment deadlines with penalties are especially effective for present-biased agents."),
    ("What is temptation bundling in behavioral economics?", "Temptation bundling pairs immediately pleasurable activities with beneficial but effortful ones. Giving audiobooks only at the gym, or allowing favourite TV shows only while exercising, sustainably increases activity by harnessing the immediate reward to overcome present-bias-driven procrastination. The bundle converts the effortful activity into an occasion for immediate gratification."),
    ("What is price anchoring in negotiations?", "In negotiations, the first offer serves as a powerful anchor. Parties insufficiently adjust away from it. When well-informed, making the first offer is advantageous by setting a favourable anchor. Counter-anchors (a justified counter-offer) are more effective than simply rejecting the anchor. Arbitrary anchors have been shown to influence salary negotiations, legal settlements, and real estate transactions."),
    ("What is the behavioral economics of organ donation defaults?", "Opt-out organ donation systems achieve registration rates above 90%; opt-in systems typically see 15-30%, despite similar public support. The difference is almost entirely attributable to status quo bias. Johnson and Goldstein's analysis: defaults communicate social norms in addition to exploiting inertia. Thoughtful default design is among the most powerful and cost-free tools available to policymakers."),
    ("What is the role of social identity in financial decisions?", "People make financial decisions partly to signal or maintain group identity. Home bias in investment, religious constraints on lending, and peer influence on major purchases all reflect identity conformity. Financial decisions serve dual functions: optimising material utility and maintaining social group membership. Identity-based appeals are more persistent than purely financial incentives."),
    ("What is the behavioral economics of healthcare compliance?", "Non-adherence to medical treatment is a major health burden. Causes include present bias, forgetfulness, and side-effect salience. Interventions: mobile app reminders, blister packs showing days, pill organisers, co-payment reductions, and smart packaging. Combining multiple behavioral tools -- reminders, defaults, and commitment devices -- achieves the highest adherence rates."),
    ("What is the role of trust in nudge effectiveness?", "Nudge effectiveness depends on trust in the nudging institution. Perceived manipulation reduces effectiveness and triggers reactance. Transparent nudges are nearly as effective as non-transparent ones and avoid backlash. Disclosure of choice architecture design sustains democratic legitimacy and maintains the public trust necessary for long-term nudge programmes to work."),
    ("What is the behavioral economics of scarcity?", "Mullainathan and Shafir: scarcity captures mental bandwidth and creates a focusing effect. It enhances performance on the immediate problem (benefit) but impairs performance on peripheral tasks (bandwidth tax). Poverty perpetuates itself partly through cognitive load, not just material deprivation. Policy should reduce cognitive burden through simplified forms, automatic enrollment, and well-designed defaults."),
    ("What is construal level theory in economic decisions?", "Construal level theory: psychologically distant events are thought about abstractly; close events concretely. Temporal distance increases abstract thinking, supporting long-term goal focus and self-control. Asking people to think about their future selves (distant, abstract) improves retirement saving decisions. Framing gym visits as identity-expressive (abstract) rather than instrumental (concrete) sustains long-term exercise."),
    ("What is the behavioral economics of tax compliance?", "Tax compliance exceeds what deterrence alone predicts. Social norms matter: HMRC letters stating 'most people in your area have paid on time' increased payment rates by 5 percentage points. Tax salience: income taxes withheld from wages trigger less resistance than lump-sum payments. Simplified filing (pre-populated returns) reduces non-compliance from administrative confusion and cognitive overload."),
    ("What is the disposition effect and after-tax returns?", "The disposition effect -- selling winners and holding losers -- is suboptimal for after-tax returns. Tax-efficient investing requires harvesting losses (selling losers to realise tax deductions) and deferring gains. Automated systems (robo-advisors) systematically harvest losses and improve after-tax performance by circumventing the psychological aversion to realising losses in a loss account."),
    ("What is the behavioral approach to energy conservation?", "OPOWER's social norm comparison reports reduced energy use by 2%, equivalent to a 20% price increase. Real-time smart meters reduce consumption by 5-15%. Green defaults on energy tariffs increase uptake of renewable energy. Time-of-use pricing combined with automation (smart thermostats) shifts demand from peaks. Behavioral and price tools together outperform either alone."),
    ("What is the behavioral economics of charitable giving nudges?", "Matching grants increase charitable donations substantially even at modest ratios. Large lead donations shift reference points upward. Opt-out giving defaults in payroll programs dramatically increase donation rates. Specific, identifiable beneficiaries outperform statistical lives. Deadline urgency and scarcity framing exploit loss aversion. Transparency about how funds are used has more modest effects than emotional narrative."),
    ("What is the behavioral economics of financial literacy?", "Low financial literacy impairs saving, debt management, and investment. Financial education has modest and short-lived effects on behaviour. Structural interventions -- automatic enrollment, default allocations, and simple product design -- achieve more than literacy programs. The combination of behaviorally informed choice architecture and targeted literacy support for key decisions is optimal."),
    ("What is the ostrich effect in investment decisions?", "Investors avoid checking portfolio performance when they expect bad news -- they psychologically 'bury their heads in the sand.' This is more prevalent in market downturns. The ostrich effect prevents rational rebalancing and worsens performance by delaying corrective action. Automated rebalancing and systematic review schedules circumvent the ostrich effect."),
    ("What is the behavioral economics of retirement saving defaults?", "Automatic enrollment dramatically increases pension participation -- from roughly 49% to 86% in Madrian and Shea's field experiment. The default contribution rate becomes the anchor for most employees. Automatic escalation (SMarT plan) increases the savings rate with each pay raise. Default fund quality critically determines outcomes. Thoughtful default design is the most powerful retirement policy lever available."),
    ("What is the behavioral economics of digital dark patterns?", "Digital platforms use behavioural insights to exploit users: pre-ticked consent boxes exploit defaults; drip pricing adds fees late in purchase to exploit sunk-cost commitment; roach motel designs make cancellation labyrinthine; and countdown timers create artificial urgency. Regulators -- the EU Digital Markets Act and UK consumer law -- prohibit dark patterns and mandate straightforward cancellation pathways."),
    ("What is the practical application of nudge theory in public health?", "Behavioural interventions in public health: organ donation opt-out (increased registration rates); cafeteria design placing salads first and fruit at eye level (increased healthy selection by 30%); calorie labelling on menus (modest reduction in calories ordered); financial incentives for weight loss with commitment contracts (Volpp); and social norm messages at point-of-care. Nudges are cost-effective complements to regulation and information campaigns."),
    ("What is mental simulation and goal achievement?", "Imagining specific steps toward a goal (process simulation) improves follow-through more than imagining the achieved end state (outcome simulation). Mental contrasting -- imagining the goal and then the obstacles -- combined with implementation intentions ('When X occurs, I will do Y') is the most effective self-regulation technique for bridging intention-action gaps in health, education, and savings."),
    ("What is the effect of emotions on risk perception?", "Integral emotions (directly related to the decision) and incidental emotions (from unrelated sources) both influence risk perception. Fear increases risk aversion; anger increases risk tolerance. Sadness increases willingness to pay. Disgust reduces willingness to engage with transactions. These affective influences are irrational from an expected utility standpoint but robustly documented -- requiring decision architecture that reduces emotional interference in consequential choices."),
    ("What is the behavioral economics of pricing for services?", "Flat-rate pricing is preferred over per-unit pricing even when it leads to overpayment -- the insurance motive and certainty preference dominate. Subscription business models exploit this. Pay-what-you-want pricing elicits greater generosity than zero prices (social norm of fairness), but less than fixed prices -- context and identity cues determine the reference point for what a fair amount to pay is."),
    ("What is the role of implementation intentions in behavior change?", "Implementation intentions (if-then plans: 'When I enter the office, I will immediately take the stairs') dramatically increase follow-through on intended behaviours across health, environmental, and financial domains. They automate behaviour initiation by linking the goal response to an anticipated situational cue, bypassing deliberate decision-making. Meta-analyses show they roughly double the likelihood of completing a goal behaviour."),
    ("What is the Dunning-Kruger effect in economic decisions?", "Low-competence individuals overestimate their ability; highly competent individuals slightly underestimate theirs. In finance: financially illiterate investors show highest confidence in their investment abilities (Lusardi and Mitchell). In entrepreneurship: overconfident entrants underestimate failure rates. In management: least-competent managers are most resistant to expert advice. Training competence reduces overconfidence by giving people the tools to recognise what they do not know."),
    ("What is inter-temporal discounting and climate policy?", "Climate change requires present sacrifice for future benefit -- perfectly inverse to present bias. Hyperbolic discounters dramatically underweight future climate harm. Nordhaus's optimal carbon tax assumes discount rates of 3-7%; Stern uses 1.4%, leading to radically different policy recommendations. Behavioral economics supports low discount rates for global, irreversible risks and commitment mechanisms to overcome future policy reversals."),
    ("What is the role of time preferences in entrepreneurship?", "Present-biased individuals are less likely to invest in education and long-term business development, and more likely to exit businesses prematurely when returns are delayed. Patient individuals (high beta in quasi-hyperbolic models) invest more in human capital and sustain effort through the loss-making startup phase. Microfinance with built-in commitment savings devices improves long-run business investment among present-biased entrepreneurs."),
    ("What is the behavioral economics of social comparison and wellbeing?", "Relative income matters more than absolute income for subjective wellbeing (Easterlin paradox -- average happiness flat despite rising GDP). Upward social comparison reduces wellbeing (relative deprivation); downward social comparison increases it. Social media amplifies upward comparisons. Luttmer (2005): an extra $1 of neighbours' income has a roughly equal negative effect on life satisfaction as losing $1 of own income."),
    ("What is the behavioral economics of nudging versus education?", "Education improves understanding but has modest and decaying behavioural effects. Nudges change choice architecture to achieve behaviour change without relying on understanding or motivation. Critics argue nudges are manipulative and fail to address root causes. The debate centres on respecting autonomy (education builds it; nudges bypass it) versus effectiveness (nudges outperform education in most field trials for health, savings, and energy)."),
    ("What is the role of affect heuristic in policy support?", "Public support for environmental and health policies is strongly driven by emotional reactions to the risk (fear, disgust, dread) rather than objective probability assessments. Risks associated with nuclear power (dread, unknown) are opposed despite low actuarial mortality; car accidents (familiar, controllable) are accepted despite high mortality. Policy communication that addresses affective concerns outperforms purely informational communication in generating support for risk-reducing policies."),
    ("What is the behavioral economics of subscription services?", "Subscription services exploit: status quo bias (inertia keeps subscribers even when value is low); sunk cost (having paid, subscribers are motivated to use the service initially, creating habit); optimism bias (overestimating future use when signing up); and the flat-rate bias (preferring fixed payment over uncertain usage cost). Regulators increasingly require easy cancellation and reminders when trials auto-renew to counter these exploitations."),
    ("What is the attention-based model of choice?", "Krajbich's attentional drift diffusion model: the option being fixated upon at any moment accumulates value faster in the decision process. Attention drives choice -- options attended to more are chosen more, independently of objective value. Eye-tracking studies confirm: gaze causally influences choice in food and consumer goods decisions. Choice architecture that directs attention to preferred options (shelf placement, menu position) shapes what people choose."),
    ("What is the behavioral economics of motivated reasoning in financial markets?", "Investors with positions in a stock process confirmatory information more readily than disconfirming information. This explains: analysts' persistent optimism about covered companies; investors' reluctance to rebalance away from winning positions; and management's systematic underweighting of competitor threat. Institutional safeguards -- independent analysis, devil's advocate roles, and systematic review processes -- counteract motivated reasoning in financial decisions."),
    ("What is the behavioral approach to financial wellbeing programmes?", "Financial wellbeing programmes that combine structural support (automatic saving, debt consolidation, simplified products) with behavioral tools (goal setting, progress visualisation, social accountability) outperform information-only programmes. Behaviorally effective programmes: address present bias with commitment devices; reduce cognitive load with auto-enrollment; use social norms to shift peer reference points; and time interventions at financially salient moments such as pay rises and tax refunds."),
    ("What is the behavioral economics of innovation adoption?", "Innovation adoption follows an S-curve: early adopters (low loss aversion, high novelty-seeking) adopt first; the majority wait for social proof (observational learning -- 'if my neighbours have it, it must be good'); laggards adopt last, often requiring defaults or regulatory mandates. Loss aversion explains consumer resistance to switching costs. Early adopter pricing (skimming) and social proof marketing accelerate diffusion beyond the innovator chasm."),
    ("What is framing of health risks in behavioral economics?", "Health risk communications framed as losses ('if you don't get screened, you are more likely to die from cancer') increase uptake of preventive health behaviours more than equivalent gain frames ('if you get screened, you are more likely to survive cancer') -- consistent with loss aversion. However, gain frames are more effective for detection behaviours (mammograms) and loss frames for prevention behaviours (sunscreen) -- regulatory focus theory moderates framing effects."),
    ("What is the behavioral economics of default menus in hospitals?", "Hospital cafeteria defaults -- placing healthy items first, at eye level, in larger portions, and making them the default in meal plans -- significantly reduce calorie intake among patients and staff without restricting choice. Moving candy bars from checkout counters to less visible locations reduces impulse purchases. Health-promoting cafeteria architecture is as effective as calorie labelling in reducing unhealthy choices."),
    ("What is the behavioral economics of price complexity?", "Complex pricing (fees, surcharges, variable rates) impairs consumer decision-making by creating cognitive overload and making comparison shopping harder. Firms exploit complexity to price-discriminate and reduce competitive pressure. Behaviorally informed regulation mandates: total all-in price disclosure; standardised fee structures; simple comparison metrics; and consumer-facing price comparison tools that translate complexity into decision-relevant summaries."),
    ("What is the behavioral economics of gift giving?", "Gift giving is economically inefficient (Waldfogel's 'deadweight loss of Christmas') because givers imperfectly know recipients' preferences -- resources could be better allocated as cash. Behaviorally, gifts serve non-monetary functions: signalling effort and care (a personalised gift signals thought); social bonding; ritual compliance; and surprise utility. Cash gifts are more efficient but violate social norms of thoughtfulness."),
    ("What is the behavioral approach to health screening uptake?", "Behaviorally informed health screening campaigns: personalised invitations (name and local GP) increase response rates over generic letters; providing a specific appointment time with opt-out (rather than asking patients to book) dramatically increases mammography attendance; social norm messages ('8 in 10 of your neighbours took part') increase uptake; and simplifying the process (single-step registration) removes friction. These low-cost modifications can double screening rates."),
]

existing = sum(1 for _ in OUT.open()) if OUT.exists() else 0
print(f"Existing: {existing} pairs")

with OUT.open("a") as f:
    for q, a in pairs:
        f.write(json.dumps({"messages": [
            {"role": "user", "content": q},
            {"role": "assistant", "content": a}
        ]}) + "\n")

total = sum(1 for _ in OUT.open())
print(f"Total: {total} pairs in upgrade_k.jsonl")
assert total >= 200, f"Only {total}"
print("PASS: 200+ premium behavioral economics pairs ready.")
