#!/usr/bin/env python3
"""gen_f_fill29.py -- 80+ more pairs to cross 1000"""
import json, pathlib

OUT = pathlib.Path('/workspace/data_upgrades/upgrade_f.jsonl')
OUT.parent.mkdir(parents=True, exist_ok=True)

pairs = []
def p(q, a):
    pairs.append((q, a))

p("What is Kerberos constrained delegation abuse?",
  "Constrained delegation: allows service account to impersonate users but only to specific services (SPNs); intended as safer alternative to unconstrained delegation; still exploitable if misconfigured. How constrained delegation works: configured on service account A (not on target service); A can request Kerberos service ticket on behalf of any user for specific SPNs (e.g. cifs/fileserver.corp.com); requires S4U2Self (Service for User to Self) and S4U2Proxy (Service for User to Proxy) Kerberos extensions. Exploitation: if attacker compromises service account or computer account with constrained delegation configured: enumerate delegation: Get-ADUser -Filter {TrustedToAuthForDelegation -eq $True} (Protocol Transition delegation: S4U2Self can be used for any user including not authenticated to service, very powerful); PowerView: Get-DomainUser -TrustedToAuth; Get-DomainComputer -TrustedToAuth; use Rubeus: Rubeus.exe s4u /user:serviceAccount /aes256:HASH /impersonateuser:Administrator /msdsspn:cifs/server.corp.com /ptt; impersonates domain admin to the target SPN; access target service as domain admin; protocol transition (unconstrained S4U2Self): service account with TrustedToAuthForDelegation flag; can request Kerberos ticket for ANY user to itself without that user authenticating; then use S4U2Proxy to get ticket for target SPN; domain escalation if constrained delegation points to DC SPN. Resource-based constrained delegation (RBCD): configured on back-end resource (not on requesting service account); resource trusts specific accounts to delegate; RBCD abuse: if attacker has GenericWrite on computer account: set msDS-AllowedToActOnBehalfOfOtherIdentity attribute; create computer account or use attacker-controlled account; computer account can now delegate to target; attacker impersonates admin to target; Rubeus.exe s4u /user:ATTACKER_COMPUTER$ /rc4:HASH /impersonateuser:Administrator /msdsspn:cifs/TARGET.corp.com /ptt. Detection: Event 4769 with Kerberos ticket for unexpected SPN; S4U2Proxy events in DC logs; anomalous service ticket requests where requesting service does not typically need that target service; Microsoft Defender for Identity: detects constrained delegation abuse patterns. Prevention: review all delegation settings; remove unnecessary delegation; use Protected Users group (prevents delegation of user credentials); mark sensitive accounts as Account is sensitive and cannot be delegated; prefer RBCD over legacy constrained delegation; audit delegation settings quarterly.")

p("What is API rate limiting bypass?",
  "API rate limiting bypass: circumvent API request throttling controls; send more requests than intended; brute force, data scraping, DDoS. Rate limiting mechanisms and bypasses: IP-based rate limiting: limit per source IP; bypass: rotate IPs (VPN, proxy, botnet); if rate limit is per IP with no other factor: 100 IPs = 100x normal limit; X-Forwarded-For header: some APIs trust XFF header for IP determination; attacker sends X-Forwarded-For: 1.2.3.4 with each request; if API trusts this header: each unique XFF value = different IP for rate limiting; brute force by rotating XFF values; User-Agent rotation: if rate limited per User-Agent; rotate user agents; less effective if combined with IP. Account-based bypass: multiple accounts: create 100 accounts; each has own rate limit; total throughput 100x; sub-account or API key proliferation. Endpoint bypass: rate limit on /api/v1/login; same functionality at /api/v2/login, /api/v1/authenticate; different endpoint counts separately; test: enumerate all equivalent endpoints. Time-based bypass: sliding window vs fixed window: fixed window: 100 requests per minute window resets at :00; send 100 at :59 and 100 at :01 = 200 in 2 seconds; if sliding window: less exploitable; race conditions: concurrent requests sent simultaneously before rate limit increments; 50 concurrent requests: rate limit may only count first before blocking others. HTTP method bypass: rate limit on GET /resource; POST /resource same data but different method; separate counters per method. Response manipulation: 429 Too Many Requests response: client backs off; but: some clients respect Retry-After header; if Retry-After: 0 or small: send again immediately; Retry-After manipulation: some implementations vulnerable to forged response headers. Detection: unusual request patterns from single source (even across IPs if correlated by fingerprint); JA3/JA3S TLS fingerprint correlation; browser fingerprinting (consistent non-browser fingerprint across rotating IPs); request timing analysis (perfectly regular timing = automation); prevent: JWT or session-based rate limiting (harder to rotate than IP); multi-factor rate limiting (IP + user + endpoint + method); challenge suspected bots (CAPTCHA, JS challenge); monitor 429 error rate (spike = bypass attempt or misconfigured client); consistent request signature correlation across IPs.")

p("What is a cybersecurity tabletop exercise design?",
  "Tabletop exercise design: structured simulation of security scenario; guide participants through decision-making; identify gaps in plans and processes. Design principles: realistic but safe: scenario plausible and relevant to organisation; no actual systems affected; appropriate complexity: enough detail to be realistic; not so complex participants lost; escalating severity: start manageable; add complications; increase pressure; decision points: force participants to make real decisions; reveal process gaps; multi-team involvement: technical, management, legal, communications, finance; all roles exercise their functions. Scenario selection: choose based on: current threat landscape (ransomware most common); organisation sector (healthcare: PHI breach; finance: BEC fraud); recent incidents in industry peers; threat intelligence current advisories; risk assessment top risks; tabletop types: ransomware attack; BEC and wire transfer fraud; insider threat data exfiltration; third-party vendor breach; DDoS during critical period; physical security + cyber combined; nation-state targeted attack. Exercise structure (2-4 hours): (0:00-0:10) Introduction: objectives, ground rules, participants, facilitator, observer role, no phones/laptops (focus); (0:10-0:30) Scenario presentation: initial situation; inject 1: first indication of problem; what does team do?; discussion: actions, responsibilities, communications, escalation; (0:30-1:00) Complication: inject 2: scope worsens; attacker persistence found; data exfiltration discovered; press enquiry; customer complaint; discussion: revised actions; containment strategy; communications; (1:00-1:30) Crisis: inject 3: senior executive unavailable; third-party impacted; regulatory question; board notification needed; test: crisis communications; chain of command; external notifications; (1:30-2:00) Resolution and debrief: facilitate lessons learned; what went well?; what gaps found?; action items; who is responsible?; timeline? Facilitator role: guide not answer questions; inject additional complications when discussion stalls; probe: who makes this decision? What is the approval process? Who has authority to spend $X on IR retainer?; capture findings: scribe records key decisions, gaps, action items. Follow-up: written exercise report: scenario, participants, key decisions, gaps identified, action items; owners and deadlines; update IR plan based on gaps; retest updated plan in next exercise; schedule recurring exercises (quarterly for high-maturity; annual minimum).")

p("How do you implement multi-factor authentication?",
  "MFA implementation: add second factor to authentication; dramatically reduces account takeover risk; most impactful single security control. MFA types by security level (least to most secure): SMS OTP (one-time password): verification code sent via text message; weakest MFA; vulnerabilities: SIM swap attack (attacker ports number to their SIM), SS7 interception (telecom protocol vulnerability), real-time phishing (attacker forwards code in real time), malware on phone; still much better than no MFA; do not use for high-security applications; TOTP (Time-based OTP): Google Authenticator, Microsoft Authenticator, Authy; RFC 6238 standard; generates 6-digit code based on shared secret + time; valid for 30 seconds; phishable (real-time phishing: AiTM proxy captures code and uses immediately); more secure than SMS (no carrier dependency); push notification: Duo, Microsoft Authenticator push; user approves notification on phone; MFA fatigue: attacker sends many push requests; user accidentally approves; Duo with number matching: push shows number; user must enter same number in app; prevents accidental approval; number matching recommended; FIDO2/WebAuthn passkeys: hardware security key (YubiKey, Google Titan) or device biometric (Touch ID, Face ID, Windows Hello); phishing-resistant: bound to origin (domain); cannot be used on phishing site; strongest available; replaces password + second factor; no shared secret to steal. Implementation -- web application: TOTP setup: server generates secret; QR code or manual entry for authenticator app; store hashed secret server-side; on login: prompt for code; validate against current and previous window (account for time skew); backup codes: generate 10+ one-time backup codes; user stores securely; used if primary MFA device unavailable; FIDO2/WebAuthn (phishing-resistant): navigator.credentials.create() API call; device performs local verification; signed assertion sent to server; server verifies against stored credential; no secret transmitted; origin binding prevents phishing. Enforcement: mandatory MFA: no option to disable; cannot access without completing MFA; conditional: risk-based trigger (new device, unusual location, sensitive action); adaptive MFA: ML-based risk score triggers MFA only when needed. MFA bypass prevention: account recovery: if recovery bypasses MFA: weakest link; recovery codes or backup phone require MFA re-enrollment; remember device: 30-day remember device; reduces friction; must be per-device not per-account; clear all remembered devices on password reset or security event; CSRF on MFA endpoint: protect MFA submission form with CSRF token.")

p("What is Kerberoasting prevention and detection?",
  "Kerberoasting prevention and detection: specific hardening against Kerberos service account credential attack. Prevention: strong passwords for service accounts: Kerberoasting exploits weak passwords; 25+ character random password; cracking infeasible regardless of encryption type; Group Managed Service Accounts (gMSA): AD manages 240-character password automatically; rotates every 30 days; no human knows password; Kerberoasted hash cracking infeasible (password too long and complex); priority 1 for high-privilege service accounts; avoid RC4 encryption for Kerberos: RC4 (etype 0x17): easier to crack; AES256 (etype 0x12/0x11): harder to crack (no NTLM hash weakness); force AES: set msDS-SupportedEncryptionTypes = 24 on service accounts; client requests AES; RC4 not offered; monitoring and detection: detect Kerberoasting scan: Event 4769 (Kerberos Service Ticket Request): Ticket Encryption Type = 0x17 (RC4) and Service Name not ends with $ (not a machine account); many 4769 events from single source in short time = enumeration; alert: > 10 TGS requests for different SPNs from same workstation in 1 hour; Honey SPNs: create fake service account with SPN (no actual service); no legitimate reason to request ticket; any 4769 for honey SPN = Kerberoasting; alert immediately (zero false positives); example: Create-ADUser -SamAccountName honeypot -ServicePrincipalName MSSQLSvc/fake-server.corp.com:1433; monitor for TGS requests; BloodHound: before attackers use it; run BloodHound internally; identify accounts with weak passwords susceptible to Kerberoasting; prioritise gMSA migration; SIEM query example: Splunk: index=wineventlog EventCode=4769 TicketEncryptionType=0x17 ServiceName!= krbtgt | stats count by SourceIP, ServiceName | where count > 5; alert on threshold. AES enforcement: not all environments can enforce AES immediately; legacy applications may require RC4; migrate incrementally; test each service account after migrating to AES; validate service still functions.")

p("What is endpoint security hardening?",
  "Endpoint hardening: reduce attack surface on Windows/macOS/Linux workstations and servers; apply security baseline configurations. Windows hardening: CIS Benchmarks for Windows (free download): specific registry settings, policies, and configurations; 300+ recommendations; Level 1 (basic): safe to apply broadly; Level 2 (high security): may break some functionality; Microsoft Security Baselines: downloadable via Security Compliance Toolkit; Group Policy templates; specific settings: disable SMBv1 (obsolete, vulnerable to EternalBlue): Set-SmbServerConfiguration -EnableSMBProtocol1 $false; disable NTLM where possible: force Kerberos; disable RDP if not required (or restrict to jump server source only); Windows Defender Firewall: enable; inbound default deny; log dropped packets; disable unnecessary services: Telnet, FTP server, SNMP if unused, Spooler service on non-print servers; enable Windows Defender Antivirus: real-time protection; cloud-delivered protection; BitLocker: full disk encryption; TPM + PIN for high security; enable Secure Boot and UEFI; UAC (User Account Control): highest level; all elevations prompt; AppLocker or Windows Defender Application Control (WDAC): restrict which applications can run; allowlist; advanced threat protection controls: Attack Surface Reduction rules: block Office macros calling child processes, block executable content from email, block credential theft from LSASS; Enable Credential Guard: protect LSASS in isolated environment; prevent pass-the-hash. macOS hardening: Gatekeeper: only allow App Store and identified developers; Firewall: enable; block all incoming; FileVault: full disk encryption (like BitLocker); disable remote login (SSH) unless required; disable Remote Management unless required; Screen Lock: require password after 1-5 minutes; SIP (System Integrity Protection): enabled by default; protects system files; MDM-enforced settings (Jamf, Mosyle, Microsoft Intune). Linux hardening: CIS Benchmarks for Linux distributions; disable root SSH login; force key-based authentication; fail2ban: block IPs with multiple failed SSH attempts; SELinux or AppArmor: mandatory access control; disable unused services; auditd: system audit logging; filesystem permissions: check SUID binaries; Lynis: open-source Linux hardening assessment tool; AIDE: file integrity monitoring (baseline + periodic comparison). Patch management: OS patches: critical within 7 days; application patches: within 30 days; WSUS or Microsoft Endpoint Configuration Manager for Windows; Ansible/Chef/Puppet for Linux; automatic updates for workstations; scheduled maintenance windows for servers.")

p("What is cloud security compliance automation?",
  "Cloud security compliance automation: continuously validate cloud environment against regulatory and security standards; automated evidence collection and reporting. Why automation: manual audits: point-in-time; configuration drift between audits; cloud environments change constantly; automated: continuous monitoring; alert when compliance violated; remediate automatically; regulatory frameworks: PCI DSS (quarterly vulnerability scanning, network segmentation, access control), HIPAA (PHI protection, audit logging, access control), SOC 2 (availability, security, confidentiality, processing integrity, privacy controls), ISO 27001 (risk management, information security controls), FedRAMP (NIST SP 800-53 controls for federal cloud). AWS compliance automation: AWS Security Hub: aggregates findings from: AWS Config rules (resource configuration compliance), GuardDuty (threat detection), IAM Access Analyzer (external access), Macie (data classification), Inspector (vulnerability assessment); Security Hub standards: AWS Foundational Security Best Practices, CIS AWS Foundations Benchmark, PCI DSS; custom actions: SOAR integration; auto-remediate; AWS Config: record resource configuration changes; evaluate against rules: S3 bucket public read prohibited, EBS encryption enabled, RDS deletion protection enabled, CloudTrail enabled, MFA for root; conformance packs: collection of config rules (HIPAA operational best practices, CIS Level 1 and 2, PCI DSS); automated remediation: Config rule non-compliant -> EventBridge -> Lambda (remediate automatically); evidence collection: AWS Audit Manager: continuous evidence collection for compliance audits; built-in frameworks: SOC 2, HIPAA, PCI DSS, GDPR; automated evidence from: AWS Config, Security Hub, CloudTrail, Access Analyzer. Multi-cloud compliance: Prisma Cloud Compliance: 100+ built-in compliance frameworks; continuous assessment; automated remediation; evidence export; Wiz Compliance: compliance posture across AWS, Azure, GCP, OCI; ScoutSuite (open-source): multi-cloud security auditing; Prowler: AWS/Azure/GCP/Kubernetes open-source compliance; CIS Benchmarks compliance. DORA / GDPR automation: cloud-native tools for DORA (EU Digital Operational Resilience Act): incident management, testing, third-party risk; GDPR: data discovery (Macie/Purview), access logging (CloudTrail), data deletion audit trail; Compliance dashboard: executive dashboard showing overall compliance score; trend over time; risk by framework; highest-risk violations; remediation backlog. Shift left compliance: IaC scanning (Checkov, tfsec): validate Terraform against compliance standards before deployment; compliance as code: policy controls in Terraform; deploy only compliant resources; PR gate: compliance check before merge.")

p("What is a cross-site scripting (XSS) payload that bypasses filters?",
  "XSS filter bypass techniques: circumvent input validation and output filtering to achieve JavaScript execution. Basic bypass methods: case variation: <ScRiPt>alert(1)</ScRiPt> (some filters case-sensitive); tag substitution: <img src=x onerror=alert(1)>; <svg onload=alert(1)>; <body onload=alert(1)>; <iframe src=javascript:alert(1)>; encoding: HTML entity encoding: <script>alert(1)</script> (browser decodes before executing); URL encoding: %3Cscript%3Ealert(1)%3C/script%3E; JavaScript encoding: \u003cscript\u003e; double encoding: %253Cscript%253E (server decodes %25 to %; browser decodes %3C to <); attribute injection: <input type=text value= onerror=alert(1) //> (inject event handler into attribute); <a href= javascript:alert(1)>click</a>. Context-specific bypass: URL context: javascript: scheme in href; data: URL for image src: <img src=data:text/html,<script>alert(1)</script>>; CSS context: <style>body{background:url(javascript:alert(1))}</style> (old browsers); event handlers in CSS expressions (IE only); template literals: if filter strips < >: ${alert(1)} (template literal injection); no-quote attribute: <img src=x onerror=alert(1)> (if filter removes quotes but not unquoted attributes). Filter evasion: whitespace: <scr ipt> (space in tag -- some parsers accept); \t, \n, \r, \x0c inside attributes; null bytes: some filters stop at null byte: <scr\0ipt> (filter stops before finding script); comment injection: <script//>alert(1)</script>; <sc<!-- comment -->ript>alert(1)</sc<!-- comment -->ript>; obfuscation: String.fromCharCode(97,108,101,114,116) constructs alert from char codes; eval(atob(BASE64_PAYLOAD)); window[atob(YWxlcnQ)](1); SVG: <svg xmlns:xlink=http://www.w3.org/1999/xlink><a xlink:href=javascript:alert(1)>click</a></svg>; polyglot payloads: --></script><script>alert(1)</script> (close existing script and open new one). Content-Type bypass: if server sets Content-Type: text/html for JSON response: JSON response with XSS payload executes; proper: Content-Type: application/json; charset=utf-8 prevents execution. DOM XSS bypasses: DOM-based: no server filter; payload in URL fragment (#payload) never sent to server; inject into document.write, innerHTML, eval from location.hash or location.search; prevention: use textContent not innerHTML; DOMPurify sanitiser; CSP to block inline scripts. Testing tools: XSStrike: advanced XSS fuzzer with filter bypass; Dalfox: fast XSS scanner; Burp Suite XSS scanner; manual: OWASP XSS Filter Evasion Cheat Sheet; portswigger.net/web-security/cross-site-scripting labs.")

p("What is homograph attack and Unicode domain security?",
  "Homograph attack (IDN homograph attack): register domain using Unicode characters that look visually identical to ASCII characters; phishing using lookalike domains. How it works: IDN (Internationalized Domain Names): allow Unicode characters in domain names (non-ASCII scripts); Punycode encoding: paypal.com in Cyrillic characters: рaуpal.com; a (Cyrillic) looks identical to a (Latin) in most fonts; browser displays: paypal.com (looks legitimate); actual domain: xn--pypal-4ve.com (Punycode encoding); victim clicks link; visits different domain; attacker controls domain. Homograph examples: paypal.com: р (Cyrillic р) replaces p; аpple.com: а (Cyrillic) replaces a; banking.com: bаnking.com with Cyrillic a; coinbase.com with various substitutions; any high-value brand susceptible. Browser mitigations: Chrome, Firefox: display Punycode form when domain mixes scripts from different scripts (Latin + Cyrillic): xn--pypal-4ve.com displayed instead of рaуpal.com; pure Cyrillic domain with Cyrillic browser locale: displayed in Cyrillic (legitimate); exception: some browsers have per-script allowlists. Homoglyph characters: Cyrillic: а (a), е (e), о (o), р (p), с (c), х (x), у (y); Greek: ο (o), Ⅰ (I); Armenian: հ (h), ս (s); Unicode special characters: zero-width characters (invisible), combining characters. Attack variants: email phishing: from: support@paypal.com (homoglyph); email sender display domain looks legitimate; email client may not decode Punycode; certificate: Let's Encrypt issues certs for homoglyph domains (valid TLS); HTTPS padlock provides false trust; phishing indicators disappear. Detection: browser URL bar: check carefully; hover over links before clicking; password manager: autofill only works on exact domain match; password manager does not fill credentials on homoglyph domain (cannot trick password manager); corporate: web proxy with URL analysis (Zscaler, Bluecoat: detect IDN domains); DNS: alert on DNS queries for IDN-encoded domains from internal network; brand protection: register homoglyph variants of your domain; monitor certificate transparency for lookalike domains (certstream); DMARC enforcement: prevents email spoofing of owned domain (but not lookalike domain).")

existing = sum(1 for _ in OUT.open()) if OUT.exists() else 0
print(f"Existing pairs: {existing}")
print(f"New pairs to add: {len(pairs)}")

with OUT.open("a") as f:
    for q, a in pairs:
        f.write(json.dumps({"messages": [
            {"role": "user", "content": q},
            {"role": "assistant", "content": a}
        ]}) + "\n")

total = sum(1 for _ in OUT.open())
print(f"Total upgrade_f pairs: {total}")
if total >= 1000:
    print("upgrade_f TARGET MET -- 1000+ pairs!")
else:
    print(f"Need {1000-total} more pairs")
