import json, os
OUT = "/workspace/titanai/data/new_data"
os.makedirs(OUT, exist_ok=True)
SYS = "You are Titan, a world-class expert across programming, AI engineering, emotional intelligence, and systems design. You give direct, expert-level, fully actionable answers."

PROG_QA = [
("Explain memory safety vulnerabilities in C — buffer overflows, use-after-free, and how to exploit them.","Buffer overflow: writing beyond array bounds overwrites adjacent memory. Stack-based: overflow local buffer to overwrite return address. Classic exploitation: fill buffer with shellcode + padding + new return address pointing to shellcode. Modern mitigations: NX/DEP (no-execute stack), ASLR (randomize addresses), stack canaries (detect overwrite before ret). Bypass techniques: ret2libc (jump to libc functions instead of shellcode — bypasses NX), ROP chains (return-oriented programming — chain existing code gadgets, bypasses NX), format string exploits (%n to write arbitrary values), heap spraying (fill heap with shellcode copies to increase hit probability). Use-after-free: memory allocated, freed, then accessed through dangling pointer. Heap grooming: cause freed chunk to be reallocated with attacker-controlled data, pointer now points to controlled memory. Type confusion: freed object of type A reallocated as type B, old pointer to A used with type B's vtable — control RIP via virtual dispatch. Exploitation: dangling pointer -> control reallocation -> overwrite vtable pointer -> code execution. Tools: AddressSanitizer (compile-time detection), Valgrind (runtime detection), pwndbg/peda for exploit development, pwntools (Python exploit framework)."),
("Walk through a complete Python asyncio architecture for high-performance concurrent I/O.","asyncio event loop executes coroutines cooperatively — single thread, no context-switching overhead, ideal for I/O-bound workloads. Core pattern: async def fetch(session, url): async with session.get(url) as resp: return await resp.json(). async def main(): async with aiohttp.ClientSession() as session: tasks = [fetch(session, url) for url in urls]; results = await asyncio.gather(*tasks). asyncio.gather runs all tasks concurrently. For CPU-bound: use ProcessPoolExecutor via loop.run_in_executor(executor, cpu_function, arg). Task management: asyncio.create_task() for fire-and-forget, TaskGroup (Python 3.11+) for structured concurrency with automatic cancellation propagation. Semaphore for rate limiting: sem = asyncio.Semaphore(10); async with sem: await fetch(). Queue for producer-consumer: queue = asyncio.Queue(maxsize=100); await queue.put(item); item = await queue.get(). Timeouts: async with asyncio.timeout(30): await operation(). Performance: aiohttp outperforms requests 10-50x for concurrent network calls. uvloop replaces default event loop with libuv implementation for 2-4x performance boost. For production: FastAPI + uvicorn + uvloop for async web services. Avoid blocking calls in async context — they block the entire event loop. asyncio.to_thread() offloads blocking calls."),
("Explain Rust's ownership model and how it prevents memory safety vulnerabilities.","Rust's ownership system provides memory safety at compile time with zero runtime overhead. Three rules: 1) Each value has exactly one owner. 2) When owner goes out of scope, value is dropped (RAII). 3) There can be either multiple immutable references OR one mutable reference — never both. Ownership transfer (move): let s2 = s1 moves ownership — s1 is no longer valid. Prevents use-after-free: compiler rejects use of moved value. Borrowing: &T immutable borrow, &mut T mutable borrow. Lifetime annotations ensure references don't outlive the data they reference — prevents dangling pointers. Lifetime syntax: fn longest<'a>(x: &'a str, y: &'a str) -> &'a str. How vulnerabilities are prevented: Buffer overflow: Vec and slice indexing bounds-checked at runtime (panic on overflow), unsafe block required for raw pointers. Use-after-free: ownership system makes it impossible to have valid reference to freed memory without unsafe. Data races: borrow checker prevents simultaneous mutable access — Send/Sync traits enforce thread safety. Double free: impossible — drop called exactly once when owner goes out of scope. The unsafe keyword allows raw pointers and unsafe operations — similar vulnerability surface to C, but explicitly marked. unsafe in Rust is an escape hatch, not the default. FFI (C interop) uses unsafe for extern blocks."),
("How do you design and implement a distributed rate limiter?","Rate limiting architectures: Token bucket: bucket holds N tokens, refills at R rate, each request consumes 1 token. If bucket empty, request rejected. Allows bursting up to N. Sliding window: track request count in rolling time window. More accurate than fixed window (no boundary spike). Fixed window: simplest, vulnerable to double-rate at window boundaries. Leaky bucket: requests queued and processed at fixed rate — smooths traffic. Distributed implementation options: Redis-based token bucket: MULTI/EXEC transaction or Lua script for atomicity. Lua script: local count = redis.call('INCR', key); if count == 1 then redis.call('EXPIRE', key, window); end; return count <= limit. Redis atomic Lua script prevents race conditions. Redis sorted sets for sliding window: ZADD with timestamp as score, ZREMRANGEBYSCORE to remove old entries, ZCARD for count. Redis Cell (CRDT-based): built-in rate limiting with CL.THROTTLE key max_burst count_per_period period. Distributed consensus: if multiple Redis nodes, use RedLock algorithm for distributed locking. For extreme scale: token bucket in each data center replica with periodic sync. Sliding window log in Cassandra for multi-region. Headers: return X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, Retry-After on 429 responses. Identify clients: API key, user ID, IP (with CGNAT considerations), fingerprint."),
("Explain the internals of SQL query optimization and indexing strategies.","Query optimizer transforms declarative SQL into execution plan. Process: Parsing → AST → Logical Plan → Logical Optimization (predicate pushdown, join reordering, constant folding) → Physical Plan → Physical Optimization (index selection, join algorithm selection, parallelism) → Execution. Index types: B-tree (default): balanced tree, O(log n) lookup, supports range queries, equality, ORDER BY. Covers all WHERE conditions except leading wildcard LIKE '%foo'. Hash index: O(1) lookup, equality only, no range queries. PostgreSQL uses for hash joins. GIN (Generalized Inverted Index): full-text search, array containment, JSONB. GiST: geometric data, full-text search, range types. Partial index: CREATE INDEX ON orders(status) WHERE status = 'pending' — small index for frequent query pattern. Composite index: column order matters — (last_name, first_name) serves queries filtering on last_name or both, NOT first_name alone. Covering index: include all columns needed by query — avoids heap access (index-only scan). EXPLAIN ANALYZE: reveals actual execution plan, row estimates vs actual, where time is spent. Key indicators: Sequential Scan on large table = missing index. Nested Loop on large tables = should be Hash Join or Merge Join. Bad row estimates = stale statistics (ANALYZE). Index not used: wrong column order, implicit cast, function wrapping indexed column (use functional index), OR conditions (use UNION instead). N+1 problem: fetch list then query each item — use JOIN or eager loading."),
("Walk through implementing a zero-downtime deployment pipeline.","Zero-downtime deployment requires: 1) Database migration strategy: expand-contract pattern. Phase 1 (expand): deploy code that works with both old and new schema. Phase 2 (migrate): run migration adding new column/table. Phase 3 (contract): deploy code using only new schema. Phase 4: remove old column. Never drop column/table in same deploy that removes code using it. Rolling deploys (Kubernetes): RollingUpdate strategy with maxUnavailable: 0, maxSurge: 1 — always have minimum pods running. Kubernetes waits for readiness probe before shifting traffic. Blue-green deployment: two identical environments (blue=live, green=new). Deploy to green, run smoke tests, switch load balancer to green. Instant rollback by switching back. Requires 2x infrastructure. Canary deployment: route 1-5% traffic to new version, monitor error rates/latency, gradually increase. Feature flags: deploy code with features behind flags, enable for % of users without redeployment. Health checks: liveness probe (is process alive?), readiness probe (is app ready to serve?). Readiness probe returns 503 during startup/migration — prevents traffic routing to unready pod. Session handling: stateless application (JWT/external session store like Redis) required for multi-instance deploys. Load balancer connection draining: allow in-flight requests to complete before removing pod from rotation. Timeout: set draining timeout > longest expected request duration."),
("How does the Linux kernel scheduler work and how do you optimize for different workloads?","Linux uses CFS (Completely Fair Scheduler) as the default process scheduler. CFS concept: each task gets a 'virtual runtime' that increases as it consumes CPU. The task with lowest virtual runtime runs next — tracked in a red-black tree for O(log n) selection. Nice values: -20 (highest priority) to +19 (lowest). Lower nice = higher weight = slower virtual runtime accumulation = more CPU time. Real-time scheduling classes: SCHED_FIFO and SCHED_RR for hard real-time requirements (multimedia, industrial). Priority 0-99 (99 = highest RT priority). Preempts all CFS tasks. SCHED_DEADLINE: tasks specify runtime, deadline, and period — scheduler guarantees CPU time. cgroups integration: CPU cgroup limits CPU share, quota, and period. cpu.cfs_quota_us / cpu.cfs_period_us = CPU fraction. NUMA awareness: numactl to bind process to specific NUMA node, reduce cross-node memory access latency. Latency optimization: sysctl kernel.sched_latency_ns (default 24ms scheduling period), kernel.sched_min_granularity_ns (minimum slice). For low-latency: isolcpus=2,3 kernel param isolates CPUs from scheduler, taskset -c 2 process to pin. HugePages: vm.nr_hugepages reduces TLB pressure for large memory workloads. For throughput: allow kernel to manage scheduling, tune nice values, use cgroups for fair allocation across services."),
]

RAG_QA = [
("How do you build a production-quality RAG system from scratch?","Production RAG architecture: 1) Ingestion pipeline: load documents (LangChain loaders, Unstructured.io for PDFs/HTML), chunk with semantic awareness (not naive character splitting). RecursiveCharacterTextSplitter with chunk_size=1000, chunk_overlap=200. Better: semantic chunking that splits on topic boundaries. 2) Embedding: OpenAI text-embedding-3-large (3072-dim), or local models (nomic-embed-text, BGE-M3 for multilingual). Batch embed for cost efficiency. 3) Vector store: Qdrant (best performance), Weaviate (built-in hybrid search), Pinecone (managed), pgvector (PostgreSQL extension for simple use cases). 4) Retrieval: vector similarity search + BM25 keyword search → hybrid with RRF (Reciprocal Rank Fusion) reranking. Cohere Rerank or BGE-reranker-large for cross-encoder reranking of top-50 → top-5. 5) Generation: retrieved chunks + query → LLM. Use maximal marginal relevance (MMR) to diversify results before sending to LLM. Prompt template: 'Answer based only on the following context: {context}. Question: {question}'. 6) Evaluation: RAGAS framework (faithfulness, answer relevance, context precision/recall). 7) Advanced: hypothetical document embeddings (HyDE) — generate hypothetical answer, embed it, retrieve similar chunks (often better than query embedding). Multi-query retrieval: generate 3-5 query variants, retrieve for each, deduplicate."),
("What is the difference between naive RAG, advanced RAG, and modular RAG?","Naive RAG: fixed pipeline — query → embed → retrieve top-k → concatenate → generate. Problems: retrieval quality bottleneck, lost in middle problem (LLM ignores middle context), hallucination when context insufficient, query-document mismatch. Advanced RAG: Pre-retrieval: query rewriting (HyDE, step-back prompting, multi-query), query routing (classify query type to specialized index). During retrieval: hybrid search (dense + sparse), reranking with cross-encoders, parent document retrieval (chunk for retrieval, return parent doc for context). Post-retrieval: context compression (extract only relevant sentences), recursive retrieval for multi-hop questions. Modular RAG: treats components as pluggable modules. Routing module: classify query → route to appropriate retrieval strategy. Query construction: text → SQL, Cypher, API calls. Retrieval module: vector, graph, structured, web search. Reranking module. Response synthesis: iterative refinement (RAG Fusion), conditional generation, active retrieval (FLARE). FLARE (Forward-Looking Active REtrieval): generate tentatively, when confidence drops, trigger retrieval for uncertain spans, regenerate with retrieved context. GraphRAG (Microsoft): builds knowledge graph from corpus, retrieves based on graph relationships — better for multi-hop reasoning."),
("How do you evaluate and improve RAG retrieval quality?","Evaluation framework (RAGAS): Faithfulness — are generated claims supported by retrieved context? Automated with LLM judge. Answer relevance — does generated answer address the question? Context precision — what fraction of retrieved chunks are actually relevant? Context recall — are all necessary facts in retrieved chunks? Answer correctness — factual accuracy vs ground truth. Tooling: RAGAs library, DeepEval, ARES, TruLens. Retrieval improvement strategies: 1) Embedding model selection: MTEB leaderboard for task-specific best models. Legal/medical domains benefit from domain-specific models. 2) Chunking strategy: semantic chunking (Langchain SemanticChunker) vs sentence-window retrieval (store sentences, return surrounding window). 3) Metadata filtering: add document-level metadata (date, category, author) — filter before vector search. 4) Query expansion: generate synonyms, related concepts, hypothetical documents (HyDE). 5) Reranking: cross-encoder rerankers dramatically improve precision. BGE-reranker-large or Cohere Rerank. 6) Multi-vector retrieval: embed each chunk multiple ways (summary + chunk + questions the chunk answers). 7) Index optimization: HNSW parameters (m=16, ef=200) for quality/speed trade-off. 8) Lost in middle problem: put most relevant chunks first and last, not in middle. 9) LLM-based filtering: use fast LLM to filter retrieved chunks before expensive generation."),
]

EMO_QA = [
("What is emotional intelligence and how do its five components apply in high-stakes situations?","Emotional Intelligence (EI, Goleman's model) consists of five domains: 1) Self-awareness: accurate recognition of your own emotional states and their effect on performance. In high-stakes situations: recognize when fear, anger, or excitement is distorting judgment. Practice: name the emotion specifically ('I feel anxious about rejection' vs generic 'stressed') — labeling activates prefrontal cortex, reduces amygdala reactivity. 2) Self-regulation: managing disruptive emotions and impulses. Techniques: cognitive reappraisal (reframe the meaning of the situation), box breathing (4-4-4-4 pattern activates parasympathetic), name-it-to-tame-it. In negotiations: pause between stimulus and response — the pause is where self-regulation lives. 3) Motivation: intrinsic drive beyond external rewards. High-EI individuals maintain goal focus under adversity, have higher frustration tolerance. 4) Empathy: accurate reading of others' emotional states. Forms: cognitive empathy (perspective-taking), affective empathy (feeling what they feel), compassionate empathy (motivates action). In conflict: demonstrate understanding before advocating your position. 5) Social skills: managing relationships, influencing, inspiring. Building rapport, conflict resolution, team coordination. EI predicts professional success better than IQ in roles requiring collaboration."),
("How do you regulate emotions under extreme pressure and adversarial conditions?","Physiological regulation: the Physiological Sigh (two quick inhales through nose + long exhale through mouth) is the fastest breathing technique to reduce acute stress — activates parasympathetic in 1-2 breaths. Box breathing: 4 count inhale, 4 hold, 4 exhale, 4 hold. Used by Navy SEALs. Cold water on face triggers diving reflex, slows heart rate dramatically. Cognitive techniques: Defusion (ACT) — separate from thoughts: 'I'm having the thought that I will fail' vs 'I will fail.' Creates observer distance. Stimulus-response gap: Viktor Frankl — between stimulus and response there is space; in that space lies choice. Practice pause-and-label before reacting. If-then implementation intentions: pre-plan responses 'If I feel anger rising in the negotiation, then I will ask a clarifying question.' Reduces in-the-moment regulatory demand. Reappraisal: change meaning of event — 'This challenge is an opportunity to demonstrate capability.' More effective than suppression (suppression increases physiological stress while reducing behavioral expression). Pressure inoculation training: deliberately practice under stressful conditions so the neurological stress response habituates. The amygdala becomes less reactive with repeated controlled exposure."),
("How do you read emotional subtext in communication and detect concealed emotions?","Emotional subtext detection: Micro-expressions (Ekman): involuntary facial expressions lasting 1/25 to 1/5 second revealing concealed emotion. Seven universal emotions with distinct facial signatures: happiness, sadness, anger, fear, disgust, contempt, surprise. Contempt is the only asymmetrical expression — unique corner of mouth raise on one side. Leak during deception, conflict avoidance, professional masking. Voice analysis: pitch rises with stress, anxiety, deception. Pace: anxiety increases rate; sadness slows it. Voice quality (tremor) indicates fear, excitement. Semantic content vs paralinguistic: people communicate twice — words are the official channel, prosody (pitch, pace, volume, rhythm) is the emotional channel. They often contradict. Body language: baseline behavior first — what is normal for this person? Then detect deviations. Self-touch (neck, face) increases under stress. Postural shifts away from threat. Foot pointing in direction person actually wants to go. Shoulder tension indicates bracing. Word choice: excessive qualifiers ('sort of', 'maybe', 'I think') when usually direct. Over-explanation without being asked. Repetition of specific phrases under stress. Context: emotional state of others is heavily context-dependent. Don't attribute to deception what can be explained by anxiety, exhaustion, or pain."),
]

def write_dataset(path, qa_list, sys_msg):
    with open(path, "w") as f:
        for q, a in qa_list:
            entry = {"messages": [
                {"role": "system", "content": sys_msg},
                {"role": "user", "content": q},
                {"role": "assistant", "content": a}
            ]}
            f.write(json.dumps(entry, ensure_ascii=False) + "\n")
    print(f"Wrote {len(qa_list)} entries to {path}")

write_dataset(f"{OUT}/upgrade_programming_expanded.jsonl", PROG_QA, SYS)
write_dataset(f"{OUT}/upgrade_rag_expanded.jsonl", RAG_QA, SYS)
write_dataset(f"{OUT}/upgrade_emo_expanded.jsonl", EMO_QA, SYS)
print("Script 5 DONE")
