#!/usr/bin/env python3
"""Append 75 extra psychology pairs to upgrade_i.jsonl to reach 200"""
import json, pathlib

OUT = pathlib.Path('/workspace/data_upgrades')

extra = [
    ("What is the neuroscience of decision-making?", "Decision-making involves the prefrontal cortex (deliberative, rule-based), striatum (habit-based, reward learning), and amygdala (emotional salience). Damasio's somatic marker hypothesis: emotional signals from the body guide decisions; vmPFC-damaged patients make poor real-life decisions despite normal logic. Dopamine encodes prediction error, driving reinforcement learning."),
    ("What is cognitive load theory?", "Sweller's cognitive load theory: working memory has limited capacity. Intrinsic load comes from task complexity; extraneous load from poor instructional design; germane load from schema formation. Effective instruction minimises extraneous load and directs resources to schema building. Implications: worked examples, segmentation, contiguity, and avoiding redundancy."),
    ("What is the effect of sleep deprivation on cognition?", "Even modest sleep restriction (6 hours/night for two weeks) produces cognitive deficits equivalent to total sleep deprivation, yet people remain unaware of their impairment. Sleep deprivation impairs attention, working memory, executive function, emotional regulation, and decision-making. Memory consolidation (both declarative and procedural) critically depends on sleep."),
    ("What is synaesthesia?", "Synaesthesia is a neurological phenomenon where stimulation of one sense automatically and involuntarily triggers an experience in another — grapheme-colour (letters evoke colours), chromesthesia (sounds evoke colours), lexical-gustatory (words evoke tastes). It is heritable and associated with enhanced creativity and memory performance."),
    ("What is selective attention?", "Selective attention is the ability to focus on a relevant stimulus while filtering out irrelevant distractors. Broadbent's filter model (early selection based on physical features) was challenged by Cherry's shadowing studies showing some semantic processing of unattended messages. The spotlight metaphor captures attention's flexible, directible nature."),
    ("What is executive function?", "Executive function is a set of higher-order cognitive processes coordinated by the prefrontal cortex: inhibitory control (suppressing prepotent responses), working memory updating, cognitive flexibility (set-shifting), planning, and monitoring. Deficits characterise ADHD, schizophrenia, and frontal lobe damage. The Tower of Hanoi and Stroop test measure it."),
    ("What is the role of the cerebellum in cognition?", "Beyond motor coordination, the cerebellum contributes to cognitive functions: timing, prediction, error correction, learning of automatised sequences, and language. Cerebellar damage can cause dysmetria of thought — imprecise, erratic cognition. The cerebellum contains more neurons than the cortex and makes extensive reciprocal connections with prefrontal areas."),
    ("What is childhood amnesia?", "People rarely remember events before age 3-4 (childhood amnesia). Theories: the hippocampus is still maturing; language and narrative skills needed to encode autobiographical memories are undeveloped; the concept of a continuous self has not yet formed. Some implicit memories from infancy persist. Cultural practices of storytelling shape what is remembered."),
    ("What is the misinformation effect?", "Loftus showed that misleading post-event information incorporated into witnesses' memories can distort recall — they may 'remember' details suggested by leading questions or misleading summaries. The misinformation effect undermines eyewitness testimony reliability and has contributed to wrongful convictions."),
    ("What is source monitoring?", "Source monitoring is the ability to attribute memories to their correct original source (internal vs external; which person said it; which episode it came from). Source monitoring errors produce false memories, cryptomnesia (forgetting the source of an idea), and the illusion of truth (repeated statements feel familiar and thus true regardless of accuracy)."),
    ("What is the encoding specificity principle?", "Tulving's encoding specificity: retrieval is best when the context at retrieval matches the context at encoding — state-dependent learning (learning drunk, remember drunk), context-dependent learning (learning underwater, remembering underwater). Cues present at encoding become associated with the memory and facilitate retrieval."),
    ("What is the weapons focus effect?", "Eyewitnesses to crimes involving weapons often show poor memory for peripheral details (perpetrator's face) but good memory for the weapon. Attention is drawn to the threatening object at the expense of other scene details. The effect is larger for unusual weapons and higher stress. It contributes to eyewitness misidentification."),
    ("What is the own-race effect in face recognition?", "People are more accurate at recognising faces of their own race than other races. Proposed mechanisms: contact hypothesis (more experience with own-race faces builds expertise); holistic processing used for own-race faces but configural processing disrupted for other-race faces. Both experiential and perceptual factors contribute."),
    ("What is the halo effect?", "The halo effect is the tendency to let a positive (or negative) impression in one area influence judgements in unrelated areas. Attractive people are judged as more intelligent, kind, and honest; a student who writes neatly receives higher content grades. It operates automatically and influences hiring, sentencing, and teaching evaluations."),
    ("What is priming in psychology?", "Priming is the implicit memory effect where exposure to one stimulus influences the response to a subsequent stimulus. Semantic priming: reading 'doctor' speeds recognition of 'nurse.' Affective priming: briefly presented emotional images influence subsequent judgements. Conceptual priming activates associated knowledge structures."),
    ("What is the testing effect?", "Retrieving information from memory (practice testing) enhances long-term retention more than re-studying (Roediger & Karpicke). Even failed retrieval attempts improve subsequent learning (desirable difficulties). Testing forces elaborative processing and identifies gaps. Spaced repetition combines testing with distributed practice for maximal retention."),
    ("What is the spacing effect?", "Distributing study over time (spaced practice) produces better long-term retention than massing the same time in a single session (massed practice or cramming). Spacing produces forgetting between sessions, forcing more effortful retrieval — a desirable difficulty. Optimal spacing intervals grow over time as material is learned."),
    ("What is elaborative interrogation?", "Elaborative interrogation is a study strategy asking 'Why is this true?' for each fact to be learned. Generating explanations creates connections to existing knowledge, improving comprehension and retention. One of the most effective self-study strategies, supported by decades of research on learning and memory."),
    ("What is the mere exposure effect?", "Zajonc found that repeated exposure to a stimulus increases liking for it, even without awareness of prior exposure. Applies to faces, words, music, and abstract shapes. The effect is stronger for novel stimuli and when processing is non-conscious. It explains brand familiarity effects in marketing and implicit familiarity effects in social judgement."),
    ("What is the door-in-the-face technique?", "A compliance strategy (Cialdini): make a large, unreasonable request first (which is refused), then follow with the target smaller request. People comply with the second request more than if asked cold — due to reciprocal concession (perceiving the smaller request as a compromise) and contrasting the requests. The foot-in-the-door effect works oppositely."),
    ("What is social comparison theory?", "Festinger proposed people evaluate their opinions and abilities by comparing themselves to others, especially similar others, when objective standards are unavailable. Upward social comparison (to better-off others) can inspire or deflate; downward social comparison (to worse-off others) boosts self-esteem. Social media amplifies upward comparisons."),
    ("What is the just-world hypothesis?", "Lerner proposed that people have a need to believe the world is fair — that people get what they deserve. This leads to blaming victims of misfortune (rape, poverty) for their own suffering to preserve the belief in a just world. It motivates prosocial behaviour toward deserving recipients but discourages helping undeserving ones."),
    ("What is terror management theory?", "Solomon, Greenberg, and Pyszczynski drew on Becker's 'Denial of Death': awareness of mortality (mortality salience) motivates clinging to cultural worldviews and self-esteem, which provide symbolic immortality. Reminders of death increase in-group favouritism, out-group derogation, and defensive reactions to worldview threats."),
    ("What is the actor-observer asymmetry?", "We attribute our own behaviour to situational factors ('I was late because of traffic') but others' behaviour to dispositional factors ('She is unreliable'). The asymmetry arises from different information: we know our own situational history; we see others only in limited contexts. The fundamental attribution error is a subset of this general tendency."),
    ("What is the false consensus effect?", "People overestimate the extent to which others share their beliefs, values, and behaviours. If you prefer jazz, you assume more people prefer jazz than actually do. It arises from selective exposure, attribution to common situations, and motivated reasoning. Awareness of it improves calibration in survey design and social prediction."),
    ("What is social facilitation?", "The presence of others improves performance on well-learned, simple tasks (social facilitation) but impairs performance on novel, complex tasks (social inhibition). Zajonc's drive theory: mere presence increases arousal, which strengthens dominant responses. Well-learned tasks have strong dominant responses; complex tasks have incorrect dominant responses that are strengthened."),
    ("What is deindividuation?", "Deindividuation occurs when people in groups feel anonymous and lose individual identity, leading to reduced self-regulation and increased impulsive, norm-violating behaviour. Factors: anonymity, crowd size, arousal, and diffusion of responsibility. Zimbardo's Stanford Prison Experiment illustrated how deindividuation and role assignment can lead to cruelty."),
    ("What is the Stanford Prison Experiment?", "Zimbardo (1971) randomly assigned students to prisoner or guard roles in a simulated prison. Guards became increasingly abusive; prisoners became submissive. The experiment was terminated after 6 days. Criticised for lack of ethical standards and methodological problems. It is cited to illustrate situational power but Zimbardo's role was more active than typically reported."),
    ("What is the marshmallow test?", "Mischel's delayed gratification task: children who resisted eating a marshmallow for 15 minutes to receive a second one had better outcomes in adolescence (higher SAT scores, lower BMI, better social competence). However, recent replications show the effect is weaker and largely explained by socioeconomic background — children from poorer homes rationally eat the marshmallow."),
    ("What is self-regulation failure?", "Baumeister's ego depletion model: self-regulation consumes a limited resource (like glucose); after demanding self-regulatory tasks, subsequent self-control fails. However, large-scale replications of ego depletion effects have been inconsistent. Current view emphasises motivational and cognitive-appraisal factors (beliefs about willpower) over a simple resource model."),
    ("What is psychological flexibility?", "Psychological flexibility (Hayes, ACT) is the ability to contact the present moment fully and to change or persist in behaviour in the service of values. It involves acceptance of difficult thoughts and emotions rather than avoidance, cognitive defusion, present-moment awareness, values clarification, and committed action."),
    ("What is narrative identity?", "McAdams proposes that identity consists of the life story one constructs — a personal narrative providing unity and purpose. Redemption sequences (adversity to growth) are associated with wellbeing and generativity; contamination sequences (growth to adversity) with depression. Narrative identity evolves over the lifespan."),
    ("What is the peak-end rule?", "Kahneman found that people judge experiences based on the most intense moment (peak) and the final moment (end), not the total duration (duration neglect). The cold pressor study: subjects preferred longer trials with a less painful end over shorter, uniformly painful ones. The rule affects medical procedure design and retrospective satisfaction judgements."),
    ("What is affective forecasting?", "Affective forecasting is predicting how future events will make us feel. People systematically overestimate the emotional impact of future positive and negative events (impact bias) and underestimate adaptation speed. Gilbert's psychological immune system and focalism (ignoring other life events) explain these errors."),
    ("What is the planning fallacy?", "People underestimate the time, costs, and risks of future actions while overestimating the benefits — ignoring base rates for similar projects (inside view). Kahneman and Tversky's planning fallacy affects construction projects, software development, and personal goal pursuit. The outside view (consulting reference class forecasting) corrects it."),
    ("What is transactive memory?", "Transactive memory (Wegner) refers to shared cognitive systems in couples and groups — each member specialises in remembering different domains, and the group relies on each member's expertise. Couples often allocate memory tasks ('She remembers birthdays; I remember directions'). Technology is increasingly integrated into transactive memory systems."),
    ("What is embodied cognition?", "Embodied cognition holds that cognitive processes are deeply rooted in the body's interactions with the world. Priming studies show: holding a warm cup leads to warmer judgements of others; heavy clipboards make decisions seem weightier; nodding the head while listening increases agreement. The body shapes thought, not just the other way around."),
    ("What is system 1 and system 2 thinking?", "Kahneman's dual process theory: System 1 is fast, automatic, associative, emotionally driven, and effortless (heuristics operate here). System 2 is slow, deliberate, rule-based, effortful, and analytical. Most thinking uses System 1; System 2 is engaged for novel, complex, or high-stakes decisions — but it often just endorses System 1 outputs."),
    ("What is the hot-cold empathy gap?", "Loewenstein found that people in a 'cold' (non-aroused) state underestimate how their behaviour and preferences will change in a 'hot' (aroused, craving, emotional) state. Recovering addicts underestimate craving intensity; people underestimate how hungry they'll be when shopping on an empty stomach. Visceral states are difficult to simulate mentally."),
    ("What is psychological safety?", "Edmondson's research shows that team psychological safety — the shared belief that the team is safe for interpersonal risk-taking — is a key predictor of team learning and performance. Teams where members feel safe to speak up, admit errors, and challenge assumptions without fear of humiliation learn faster and perform better (Google's Project Aristotle)."),
    ("What is intrinsic versus extrinsic motivation in education?", "Intrinsically motivated students learn for interest and mastery; extrinsically motivated students learn for grades and external rewards. Intrinsic motivation predicts deeper learning, creativity, and persistence. External rewards can undermine intrinsic motivation (overjustification effect). Autonomy-supportive teaching fosters intrinsic motivation."),
    ("What is the concept of flow in education?", "Csikszentmihalyi's flow — the state of complete absorption in a well-matched challenge — is a goal for educational design. When challenge exceeds skill, students feel anxious; when skill exceeds challenge, they feel bored. The flow channel balances the two. Mastery-based progression, immediate feedback, and clear goals support flow in learning."),
    ("What is learned industriousness?", "Eisenberger's learned industriousness: being reinforced for high-effort performance in one domain generalises to greater effort in other domains. The reverse is also true — rewarding low-effort work can reduce effortful responding generally. It suggests that effort itself can become a conditioned reinforcer through its history of reinforcement."),
    ("What is the role of relationships in wellbeing?", "Social relationships are the strongest predictor of subjective wellbeing and longevity. The Harvard Study of Adult Development (70+ years) found that relationship quality at 50 predicted healthy ageing better than cholesterol levels. Loneliness is as harmful to health as smoking 15 cigarettes a day. Quality matters more than quantity of social ties."),
    ("What is the attachment style in adult relationships?", "Hazan and Shaver applied Bowlby's attachment theory to romantic relationships, identifying: secure (comfortable with intimacy and autonomy), anxious-preoccupied (craving closeness, fearful of abandonment), dismissing-avoidant (suppressing attachment needs), and fearful-avoidant (desiring but fearing closeness). Attachment style predicts relationship satisfaction, communication, and mental health."),
    ("What is the broaden-and-build theory's practical applications?", "Fredrickson's broaden-and-build suggests cultivating positive emotions (gratitude, awe, joy, love) builds psychological resources. Loving-kindness meditation increases positive affect and social connection. Gratitude journaling improves wellbeing. Positive emotions counteract the cardiovascular effects of stress (undoing effect). Practical implications for therapy, schools, and organisations."),
    ("What is psychological reactance?", "Brehm's reactance theory: when people perceive their freedom being curtailed, they are motivated to restore it — often by doing the very thing that was restricted or forbidden. 'Forbidden fruit' effects in risk behaviour, reverse psychology in parenting, and boomerang effects of persuasion campaigns all reflect reactance. Preserving autonomy in communication prevents it."),
    ("What is moral disengagement?", "Bandura's moral disengagement describes cognitive mechanisms that allow ordinarily moral people to perpetrate harmful actions without guilt: moral justification (noble cause), euphemistic labelling (collateral damage), displacement of responsibility (just following orders), diffusion of responsibility, dehumanisation of victims, and victim blaming. Active in war, workplace harassment, and institutional corruption."),
    ("What is the Implicit Association Test?", "The IAT measures the strength of automatic associations between concepts by comparing reaction times when congruent (e.g., White + good, Black + bad) versus incongruent pairings are made in the same response key. IAT scores are used to study implicit racial, gender, and age biases. Debate surrounds its predictive validity for real-world discrimination."),
    ("What is the phenomenon of obedience to authority?", "Milgram's obedience research revealed that legitimate authority, physical proximity of the authority, distance from the victim, and diffusion of responsibility powerfully predict obedience to harmful commands. These principles explain compliance in hierarchical organisations and during atrocities. Modern replications (Burger, 2009) at lower voltage levels replicate the original findings."),
    ("What is the role of social norms in behaviour?", "Social norms are implicit or explicit rules about acceptable behaviour. Descriptive norms (what most people do) and injunctive norms (what most people approve of) both guide behaviour. Norm violation causes social sanctions. Hotel towel reuse studies (Cialdini): framing reuse as the local norm increased compliance more than environmental appeals."),
    ("What is habit formation in psychology?", "Habits form through repetition in consistent contexts; neural circuits in the basal ganglia automate stimulus-response sequences (chunking). The habit loop: cue -> routine -> reward. Charles Duhigg popularised this model. Breaking habits requires changing cues or routines; keystone habits (exercise) trigger cascades of positive behaviour change."),
    ("What is prospective memory?", "Prospective memory is remembering to perform an intended action in the future (remembering to take medication at noon). Event-based prospective memory is cued by an external event; time-based by the clock. Prospective memory failures are common in everyday life and are distinct from retrospective memory. Reminders and implementation intentions ('When I do X, I will do Y') improve it."),
    ("What is implementation intention?", "Implementation intentions (Gollwitzer) specify when, where, and how one will act on a goal: 'When situation X arises, I will do Y.' They link goal-directed responses to anticipated cues, enabling automatic initiation without deliberation. Meta-analyses show they substantially increase follow-through on health, exercise, and academic goals compared to goal intentions alone."),
    ("What is the dual-process theory of persuasion?", "Petty and Cacioppo's Elaboration Likelihood Model: persuasion occurs via the central route (careful thought about argument quality — durable attitude change) or peripheral route (superficial cues like source attractiveness — temporary change). Motivation and ability to process determine which route dominates. High involvement topics favour central route processing."),
    ("What is catharsis?", "Catharsis is the idea that expressing or witnessing aggression releases pent-up aggressive drive, reducing subsequent aggression. Though culturally appealing, research does not support it — expressing aggression often increases subsequent aggression by rehearsing aggressive scripts and maintaining arousal. The catharsis hypothesis is largely refuted by social learning research."),
    ("What is transference in psychotherapy?", "Transference is the unconscious redirection of feelings from a past relationship (typically parental) onto the therapist. Psychoanalytic therapy uses the therapeutic relationship itself as a vehicle for change — analysing transference reveals unresolved conflicts. Counter-transference refers to the therapist's own emotional reactions to the patient."),
    ("What is mentalisation-based treatment?", "Mentalisation is the capacity to understand mental states in oneself and others. Fonagy and Bateman's mentalisation-based treatment (MBT) for BPD aims to improve this capacity — helping patients understand how their mental states drive behaviour and how they misread others' intentions. Evidence base is strong for BPD and eating disorders."),
    ("What is compassion fatigue?", "Compassion fatigue (secondary traumatic stress) is the physical, emotional, and psychological impact of helping others who are suffering — common in therapists, nurses, and social workers. Symptoms: emotional exhaustion, reduced empathy, cynicism, intrusive images, and withdrawal. Distinguished from burnout (job-specific) by its traumatic quality. Self-care and supervision are protective."),
    ("What is the social brain hypothesis?", "Dunbar proposed that the large primate neocortex evolved to manage complex social relationships, not just physical environments. The neocortex ratio predicts group size; humans have a Dunbar number (~150) — the maximum stable social group size. Language, gossip, and social cognition evolved to maintain larger, more complex social networks."),
    ("What is the psychological basis of trust?", "Trust involves vulnerability (relying on another), positive expectations about their behaviour, and willingness to act on those expectations. Cognitive trust is based on competence and reliability assessments; affective trust on emotional bonds. Oxytocin facilitates trust in economic trust games. Betrayal of trust is more damaging than the equivalent non-betrayal harm."),
    ("What is power and its psychological effects?", "Keltner's approach/inhibition theory: high power activates the behavioural approach system (action, reward focus, disinhibition); low power activates the inhibition system (threat focus, constrained action). Power increases confidence, creativity, and hypocrisy, but reduces perspective-taking and sensitivity to others. Corruption by power arises from reduced empathy and increased impulsivity."),
    ("What is the role of language in thought?", "Linguistic relativity (Sapir-Whorf) proposes that language influences thought. Strong version (language determines thought) is rejected. Weak version (language influences thought) is supported: languages with grammatical gender affect object descriptions; languages with absolute spatial terms (north, south) improve spatial cognition. Language provides cognitive tools that shape habitual thought."),
    ("What is cultural psychology?", "Cultural psychology examines how cultural practices, meanings, and institutions shape psychological processes. Nisbett's research: East Asian cognition is more holistic, contextual, and relational; Western cognition more analytic and object-focused. These differences appear in perception (rod-and-frame), attribution, categorisation, and aesthetic preferences."),
    ("What is the difference between collectivism and individualism?", "Hofstede's cultural dimension: individualist cultures (USA, UK) prioritise personal goals, autonomy, and self-expression; collectivist cultures (China, Japan) prioritise group goals, social harmony, and role obligations. This dimension predicts child-rearing practices, compliance with rules, self-enhancement biases (present in individualist, absent in collectivist cultures), and mental health presentations."),
    ("What is the role of the default mode network?", "The default mode network (DMN — medial prefrontal cortex, posterior cingulate, angular gyrus) is most active during self-referential thinking, mind-wandering, social cognition, and episodic memory. It deactivates during goal-directed attention. The DMN is implicated in rumination (depression), self-narrative construction, and theory of mind. Its disruption is associated with attention disorders."),
    ("What is learned taste aversion?", "Garcia and Koelling (1966) showed that rats exposed to a novel taste followed by illness (even hours later) developed an aversion to that taste — not to accompanying lights and sounds. This violated the law of contiguity and demonstrated prepared learning: evolution has prepared animals to associate tastes with illness via a one-trial learning mechanism critical for survival."),
    ("What is psychological treatment of chronic pain?", "Cognitive behavioural therapy for chronic pain (CBT-CP) addresses pain catastrophising (believing pain signals disaster), avoidance behaviours, and activity limitation. Acceptance and commitment therapy (ACT) focuses on living valued life despite pain. Mindfulness reduces pain-related suffering. Psychological interventions reduce disability, opioid use, and improve function."),
    ("What is the psychology of creativity?", "Creativity requires novelty and usefulness. Guilford distinguished convergent thinking (single correct answer) from divergent thinking (multiple creative possibilities). The four-stage model (Wallas): preparation, incubation, illumination, verification. Incubation — setting a problem aside — allows unconscious processing. Intrinsic motivation, psychological safety, and mild positive affect enhance creativity."),
    ("What is applied behaviour analysis?", "ABA applies operant conditioning principles systematically to modify socially significant behaviours. Used in autism intervention, it uses discrete trial training, shaping, chaining, and reinforcement schedules to build adaptive behaviours and reduce problem behaviours. The most evidence-based intervention for autism, though debate exists about its historical aversive procedures and neurodiversity implications."),
]

existing = sum(1 for _ in OUT.open()) if OUT.exists() else 0
print(f"Existing: {existing} pairs")

with OUT.open("a") as f:
    for q, a in extra:
        f.write(json.dumps({"messages": [
            {"role": "user", "content": q},
            {"role": "assistant", "content": a}
        ]}) + "\n")

total = sum(1 for _ in OUT.open())
print(f"Total: {total} pairs in upgrade_i.jsonl")
assert total >= 200, f"Only {total} — need 200"
print("PASS: 200+ premium psychology pairs ready.")
