#!/usr/bin/env python3
"""gen_o_fill.py -- add software architecture pairs to upgrade_o.jsonl"""
import json, pathlib

OUT = pathlib.Path('/workspace/data_upgrades')
OUT.parent.mkdir(parents=True, exist_ok=True)

pairs = []

def p(q, a):
    pairs.append((q, a))

p("What is the difference between monolithic and microservices architecture?",
  "Monolithic: single deployable unit with all functionality; simple to develop and test initially; scales as a unit; one failure can bring down everything; as codebase grows, becomes hard to understand, modify, and deploy. Microservices: independently deployable services with single responsibility; each service has its own database (polyglot persistence); scales independently (scale only the bottleneck service); technology heterogeneity; fault isolation with circuit breakers. Tradeoffs: monolith is simpler for small teams and early stage; microservices pay dividends at scale but add distributed systems complexity. Migration path: Strangler Fig pattern -- gradually extract services from monolith; route traffic through facade; replace monolith piece by piece without big-bang rewrite.")

p("Explain event-driven architecture and when to use it.",
  "Event-driven architecture (EDA): components communicate by producing and consuming events rather than direct synchronous calls. Components: Event Producer (publishes events to message broker); Event Broker (Kafka, RabbitMQ, SQS/SNS -- routes, persists events); Event Consumer (subscribes to events and reacts). Patterns: Event Notification -- producer sends event with minimal data; consumers fetch details if needed; low coupling. Event-Carried State Transfer -- event contains all data consumers need; no callback needed. Event Sourcing -- all state changes recorded as immutable event log; current state derived by replaying events; full audit trail; time travel (replay to any point). CQRS (Command Query Responsibility Segregation) -- separate write model (commands) from read model (queries); often combined with Event Sourcing; optimise reads and writes independently. When to use: loose coupling between services; high throughput (Kafka handles millions of messages/second); audit trail requirements; complex workflows with multiple consumers reacting to same event. Challenges: eventual consistency (consumers may lag); event schema evolution (versioning); debugging is harder (distributed trace); duplicate event handling (idempotent consumers required).")

p("What is the hexagonal architecture (Ports and Adapters) pattern?",
  "Hexagonal architecture (Alistair Cockburn, 2005): core domain logic is isolated from external concerns (UI, databases, external APIs) via Ports (interfaces) and Adapters (implementations). Structure: Domain Core -- pure business logic with no framework or infrastructure dependencies; testable in isolation; Ports -- interfaces defined by the domain for input (driving) and output (driven): IUserRepository, IEmailSender, IOrderService; Input Adapters (driving) -- REST controllers, CLI handlers, message queue consumers -- translate external requests into domain calls; Output Adapters (driven) -- database implementations (PostgresUserRepository), external API clients (StripePaymentAdapter) -- implement domain-defined ports. Benefits: swap databases, message brokers, or external APIs without changing domain logic; test domain with mock adapters; clear dependency direction (domain does not depend on infrastructure). Clean Architecture and Onion Architecture are related concepts with same core idea: dependencies point inward (toward domain). Implementation in Python: domain module has no imports from framework; repository is an abstract class; service receives repository via constructor injection (Dependency Inversion); FastAPI adapter imports domain but domain does not import FastAPI.")

p("Explain the CQRS pattern and when to apply it.",
  "CQRS (Command Query Responsibility Segregation): separate the write side (Commands that change state) from the read side (Queries that return data). In simple CRUD, the same model handles both reads and writes. With CQRS: Command Model -- optimised for consistency and business rules; normalised data model; transactional writes; handles CreateOrder, CancelOrder, UpdateInventory commands; Write Database (relational, strongly consistent). Query Model -- optimised for read performance; denormalised views; pre-joined data ready for display; handles GetOrdersByCustomer, GetDashboardStats queries; Read Database (document store, Elasticsearch, materialised views). Synchronisation: after a command updates the write DB, an event is published; event handlers update the read model (eventually consistent). Benefits: scale reads and writes independently; optimise each model for its purpose (reads need fast queries, writes need transactional safety); complex business domain can express commands as rich domain operations. When to use: read-heavy systems where read and write performance requirements differ greatly; complex domain with many business rules on writes; audit trail needed (combine with Event Sourcing). When NOT to use: simple CRUD applications (massive overengineering); small teams without strong DDD understanding.")

p("What are the SOLID principles for system architecture?",
  "SOLID at architecture level: Single Responsibility: each module or service has one reason to change; the Order Service handles order lifecycle; do not bolt on payment processing or inventory management. Open/Closed: extend system behavior without modifying existing components; add new payment provider by implementing IPaymentGateway interface, not by editing existing payment code. Liskov Substitution: any implementation of an interface can replace another without breaking system; PostgresRepository and MongoRepository both implement IUserRepository and behave identically from caller perspective. Interface Segregation: define narrow interfaces per use case; IOrderReader (read-only queries) separate from IOrderWriter (state-changing commands); services depend only on what they use. Dependency Inversion: high-level modules (business logic) depend on abstractions not concretions; OrderService depends on IPaymentGateway interface, not Stripe SDK directly; Stripe SDK injected at runtime. Applied at architecture level: services expose APIs as contracts (ports); internal implementation hidden; swap implementations (databases, message brokers, payment providers) without changing consumers.")

p("How do you design a system for high availability?",
  "High Availability (HA) design principles: (1) Eliminate single points of failure (SPOF): every component has at least two instances; load balancer distributes traffic; database has primary + replica(s); use managed services with built-in HA (RDS Multi-AZ, ElastiCache cluster mode). (2) Geographic redundancy: deploy across multiple availability zones (AZs) in same region; for highest availability: multi-region active-active or active-passive; traffic routing via latency-based DNS or global load balancers. (3) Health checks and automatic failover: load balancer health checks detect unhealthy instances; auto-scaling group replaces failed instances; database automatic failover (RDS Multi-AZ promotes replica in 60-120s). (4) Circuit breakers: if downstream service is failing, open circuit (stop calling it); prevent cascade failures; retry after timeout. (5) Graceful degradation: if recommendation service is down, show popular products instead; system remains usable with reduced functionality. (6) Zero-downtime deployments: blue-green (run two environments, switch traffic); canary (gradually route traffic to new version); rolling updates (replace instances one by one). Availability math: 99.9% (three nines) = 8.7 hours downtime/year; 99.99% (four nines) = 52 minutes/year; 99.999% (five nines) = 5 minutes/year; two independent 99% systems in parallel = 1 - (0.01 * 0.01) = 99.99%.")

p("Explain database sharding strategies.",
  "Sharding: horizontal partitioning of data across multiple database instances (shards). Why shard: single database cannot handle data volume or query throughput; scale horizontally instead of vertically (bigger machine). Sharding strategies: (1) Range-based: shard by value range (users A-M on shard 1, N-Z on shard 2; orders created Jan-Jun on shard 1, Jul-Dec on shard 2); simple; risk of hot spots if range distribution is uneven (all new orders go to current time shard). (2) Hash-based: shard_id = hash(key) % num_shards; even distribution; no hot spots for uniform key distribution; hard to do range queries (scatter-gather across all shards); resharding when adding shards requires moving data. (3) Directory-based: lookup table maps each key to shard; flexible; lookup table is single point of failure and bottleneck. (4) Geographic: shard by user region; EU users on EU shard for latency and data residency. Challenges: cross-shard joins (application-side join or denormalise); cross-shard transactions (two-phase commit or eventual consistency via saga); rebalancing when adding shards (consistent hashing reduces data movement); increased operational complexity. Consistent hashing: keys and shards placed on a ring; key goes to nearest shard clockwise; adding a shard only moves keys from its neighbors; used in Cassandra, DynamoDB, Redis Cluster.")

p("What is service discovery and how does it work?",
  "Service discovery: mechanism for services to find each other in a dynamic environment where instances come and go (containers, auto-scaling). Problem: microservices cannot use hardcoded IPs because container IPs change on restart; cannot use static DNS because DNS TTL too long for fast failover. Client-side discovery: client queries service registry (Consul, Eureka, etcd); registry returns list of healthy instances; client chooses instance (round-robin, least connections); client-side load balancing; client couples to registry. Server-side discovery: client queries load balancer or API gateway; load balancer queries registry and routes request; client does not know about registry or multiple instances; simpler client. Service registry: central database of service instances with health status; instances register on start, deregister on shutdown (or health check failure marks them unhealthy); Consul uses gossip protocol for distributed state; Eureka used in Spring Cloud; Kubernetes has built-in service discovery via Services (kube-proxy, CoreDNS). Health checks: active (registry pings instance at /health); passive (registry detects failed requests from load balancer). DNS-based: each service has DNS name (orders.internal); DNS returns current healthy IPs with short TTL; simple but TTL caching causes staleness; used by Kubernetes Services (ClusterIP with CoreDNS).")

p("How does a message queue improve system architecture?",
  "Message queues (RabbitMQ, SQS, Kafka) provide asynchronous communication between services. Benefits: (1) Decoupling: producer does not need to know about consumers or wait for them; publish and move on; consumer processes at its own pace. (2) Load leveling: queue absorbs traffic spikes; consumers process at sustainable rate; prevents overwhelming downstream services during bursts. (3) Resilience: if consumer is down, messages wait in queue; when consumer restarts it processes backlog; no message loss (with durable queues). (4) Fan-out: one message goes to multiple consumers simultaneously; OrderPlaced event processed by inventory, email, analytics services in parallel. Common patterns: Work Queue (Task Queue): multiple consumers share a queue; each message processed by exactly one consumer; used for distributing background jobs (send email, resize image, process payment). Pub/Sub: message published to topic; all subscribers receive a copy; used for event notification, cache invalidation. Message types: RabbitMQ: AMQP protocol; exchanges route messages to queues via routing keys; direct, topic, fanout, headers exchange types; strong ordering within queue. SQS: managed AWS service; Standard Queue (at-least-once, best-effort ordering) vs FIFO Queue (exactly-once, ordered within message group). Kafka: distributed log; partitions for parallelism; consumer groups for competing consumers; long retention (replay old messages); extremely high throughput.")

p("Explain API Gateway pattern and its responsibilities.",
  "API Gateway: single entry point for all client requests to a microservices backend. Responsibilities: (1) Request routing: route /api/orders/* to Orders Service; /api/users/* to Users Service; single hostname for client. (2) Authentication and authorization: verify JWT token or API key; extract claims; pass user identity to downstream services (X-User-Id header); backend services trust gateway-validated identity. (3) Rate limiting: per user or per API key limits; prevent abuse; return 429 Too Many Requests. (4) SSL termination: handle HTTPS at gateway; internal communication can be HTTP (simpler certificate management). (5) Request/response transformation: translate between client format and backend format; aggregate multiple backend calls into single response (API composition). (6) Logging and monitoring: log all requests centrally; track latency, errors, usage per endpoint. (7) Load balancing and circuit breaking: distribute traffic across service instances; open circuit if service is unhealthy. Products: AWS API Gateway (managed, integrates with Lambda, IAM auth); Kong (open-source, extensible with plugins); NGINX with Lua; Traefik (Kubernetes-native); Envoy (used in service meshes). BFF (Backend for Frontend) pattern: separate API gateway per client type (mobile BFF, web BFF, third-party API BFF); optimise response format and aggregation for each client; reduces over-fetching.")

p("What is eventual consistency and how do you handle it?",
  "Eventual consistency: in distributed systems, after an update, all nodes will eventually have the same data -- but not immediately. Contrast: strong consistency guarantees every read sees the most recent write; only possible with coordination overhead (locks, two-phase commit) that limits scalability. Why eventual consistency: distributed databases across geographic regions cannot synchronise every write instantly (speed of light); CAP theorem: network partitions require choosing between consistency and availability; most internet-scale systems choose availability + eventual consistency. Handling eventual consistency: (1) Read-your-writes: user always reads from the node they just wrote to (sticky sessions) or from leader (for their own writes); prevents seeing stale data for the user who just updated. (2) Monotonic reads: user never sees older data than what they already saw; route user to same replica consistently. (3) Saga pattern: for distributed transactions (order placement across Order, Inventory, Payment services); sequence of local transactions with compensating transactions on failure (cancel order if payment fails). (4) Idempotent consumers: message queue consumers may process message multiple times; operations must produce same result if applied multiple times (use unique transaction IDs to deduplicate). (5) Conflict resolution: last-write-wins (timestamp-based); vector clocks (track causality); CRDT (Conflict-free Replicated Data Types -- data structures designed to merge automatically, used in distributed counters, sets).")

p("How do you design a caching layer for a web application?",
  "Caching strategy: store expensive computation results or database query results in fast storage (memory) for faster subsequent access. Cache types: (1) Application-level cache: in-process cache (dictionary in memory); no network hop; lost on restart; limited to single instance. (2) Distributed cache: Redis, Memcached; shared across application instances; survives restart (Redis RDB/AOF persistence); supports pub/sub and advanced data types. Cache patterns: Cache-Aside (Lazy Loading): application checks cache first; on miss, load from database and store in cache; cache only stores what is actually requested; cache miss causes double latency. Write-Through: write to cache and database simultaneously on every write; always consistent; extra write latency; cache fills with data not necessarily read. Write-Behind (Write-Back): write to cache; asynchronously write to database; highest write performance; risk of data loss if cache dies before async write. Read-Through: cache handles database reads transparently; application only talks to cache. Cache invalidation strategies: TTL (time-to-live) -- auto-expire after N seconds; simple but stale window exists. Event-based invalidation -- when data changes, publish event; cache subscribers delete/update that key; complex but consistent. Cache-busting: include version or hash in cache key; on update, change key; old key expires naturally. Considerations: cache stampede (many requests miss cache simultaneously and all hit database -- use probabilistic early expiration or locking); hot keys (all traffic hitting same cache key -- shard or replicate).")

p("Explain load balancing algorithms and when to use each.",
  "Load balancing distributes incoming requests across multiple backend instances. Algorithms: (1) Round Robin: requests distributed sequentially to each server in turn; simple; does not account for server load or request duration; good when all requests are similar cost and servers are identical. (2) Weighted Round Robin: some servers get proportionally more traffic (weight=3 gets 3x requests of weight=1); accounts for servers with different capacity. (3) Least Connections: route to server with fewest active connections; better for long-lived connections (WebSockets, file uploads) where request duration varies. (4) Least Response Time: route to server with lowest average response time; requires health check data; best for minimising latency. (5) IP Hash: hash client IP to determine server; same client always goes to same server (session affinity/sticky sessions); useful for stateful applications without shared session store. (6) Random: random server selection; statistically similar to round-robin for high volume. Layer 4 vs Layer 7: L4 (transport layer) -- routes based on IP and port; fast; no TLS termination; limited routing options. L7 (application layer) -- routes based on HTTP headers, URL path, host; can terminate TLS; content-based routing; host-based virtual hosting. Tools: NGINX, HAProxy, AWS ALB (L7); AWS NLB (L4). Health checks: load balancer pings /health endpoint; removes unhealthy instances from rotation; restores when healthy.")

p("What is a distributed transaction and how do you handle it?",
  "Distributed transaction: operation that spans multiple services or databases and must succeed or fail atomically. Traditional two-phase commit (2PC): Coordinator sends Prepare to all participants; participants lock resources and respond Yes/No; if all Yes, Coordinator sends Commit; if any No, sends Rollback. Problems with 2PC: blocking protocol (resources locked during both phases); coordinator failure leaves participants blocked indefinitely; poor scalability; not suitable for microservices across organisational boundaries. Saga pattern (preferred for microservices): sequence of local transactions; each step publishes an event or message triggering next step; compensating transactions undo completed steps on failure. Choreography-based saga: no central coordinator; each service reacts to events and publishes next event; OrderPlaced event triggers InventoryReserved, PaymentCharged; on PaymentFailed event, InventoryReleased event triggered. Orchestration-based saga: central saga orchestrator sends commands to each service; orchestrator tracks state and handles failures; easier to understand and debug but orchestrator becomes central component. Idempotency: each step must be idempotent (safe to retry); use unique transaction IDs to detect and skip duplicate operations. Tradeoffs: saga provides eventual consistency not ACID; intermediate states are visible (order is placed before payment confirmed); compensating transactions can be complex (refund may fail if payment provider is down). Outbox Pattern: prevents lost events -- write event to outbox table in same local transaction as state change; separate process publishes outbox events to message broker.")

p("Explain the difference between synchronous and asynchronous communication in microservices.",
  "Synchronous: caller makes request and waits for response; HTTP/REST, gRPC are synchronous; simple request-response model; caller blocks thread waiting; strong consistency (response confirms action); cascading failures (if Service B is slow, callers of Service A queue up waiting for B, causing A to slow down too). Asynchronous: caller sends message and does not wait; message queue (Kafka, SQS, RabbitMQ); caller continues immediately; decoupled performance; better fault tolerance (queue absorbs load, processes when able); eventual consistency. When synchronous: query operations needing immediate result (return current stock level); real-time user-facing operations where waiting is expected; simple request-reply semantics. When asynchronous: fire-and-forget operations (send email, process image, update analytics); long-running operations (video transcoding); fan-out to multiple consumers; when caller does not need to know if/when action completes; high throughput ingestion. Request-response over async: use correlation ID and reply-to queue; caller publishes request with correlation ID to request queue; consumer processes and publishes response with same correlation ID to reply queue; caller listens on reply queue; adds complexity, prefer sync for simple request-response. Choreography vs Orchestration: choreography uses async events (services react to events); orchestration uses synchronous commands from central orchestrator; both are patterns for coordinating multi-step processes.")

p("What is the saga pattern for distributed transactions?",
  "Saga: sequence of local transactions that together implement a multi-service business operation. Each local transaction updates the service own database and publishes an event or message. On failure, compensating transactions undo completed steps. Example: Create Order Saga -- Step 1: Order Service creates order in PENDING state; publishes OrderCreated event. Step 2: Inventory Service reserves items; publishes InventoryReserved event. Step 3: Payment Service charges card; publishes PaymentCompleted event. Step 4: Order Service updates order to CONFIRMED; saga complete. Failure handling: if Payment fails -- PaymentFailed event triggers Inventory Service to release reservation (compensating transaction); Order Service cancels order. Compensating transactions: must be idempotent; must eventually succeed (payment reversal may take multiple retries); cannot always undo (sending an email cannot be unsent -- use semantic undo: send cancellation email). Choreography (event-driven): no central coordinator; services react to events; simple to implement; hard to track saga state; suitable for simple linear flows. Orchestration: Saga Orchestrator service (or workflow engine like Temporal, AWS Step Functions) sends commands; tracks state machine; handles retries and timeouts; clear visibility into saga progress; orchestrator failure must be handled. State machine: model saga as explicit state machine (PENDING, INVENTORY_RESERVED, PAYMENT_COMPLETED, CONFIRMED, CANCELLED); persist state in database; resume after crash.")

p("Explain the two generals problem and its implications for distributed systems.",
  "Two Generals Problem: two armies (A1 and A2) separated by enemy territory must coordinate simultaneous attack to succeed; they communicate via messengers who may be captured; A1 sends message to A2; A2 cannot know if acknowledgment reached A1; A1 cannot know if original message reached A2; no amount of back-and-forth guarantees both will act simultaneously. This is a formal impossibility proof: you cannot achieve guaranteed consensus over an unreliable network. Implications for distributed systems: no protocol can guarantee that both parties in a distributed transaction commit or rollback simultaneously if network messages can be lost; two-phase commit works if coordinator does not fail but cannot handle coordinator failure during commit phase; Byzantine fault tolerance requires 3f+1 nodes to tolerate f malicious failures; Paxos and Raft achieve consensus in asynchronous networks by requiring a majority quorum (f+1 of 2f+1 nodes) -- can tolerate f failures. FLP Impossibility: in an asynchronous system with even one possibly-crashed process, no deterministic algorithm can guarantee consensus; solved in practice by introducing randomness (timeouts, randomised leader election). Practical implications: design systems to handle partial failures; use idempotent operations and retry; use exactly-once semantics where critical; accept that distributed agreement has fundamental limits and design accordingly.")

p("How do you design for observability in a microservices system?",
  "Observability pillars: Logs, Metrics, Traces. Logs: structured logging in JSON format (not free-form text); include: timestamp, log level, service name, trace ID, span ID, user ID, request ID, message, error details; centralise in ELK (Elasticsearch, Logstash, Kibana) or Splunk; correlation ID propagates through all services (log all related logs with same ID); avoid logging PII. Metrics: quantitative measurements over time; types: counter (requests_total, errors_total -- monotonically increasing), gauge (active_connections, memory_usage -- can go up and down), histogram (request_duration_seconds -- distribution); expose via Prometheus /metrics endpoint; scrape with Prometheus; visualise in Grafana; alert on anomalies (high error rate, p99 latency spike). Distributed tracing: trace follows single request across multiple services; each service creates a span (operation with start/end time, tags); spans linked by trace ID and parent span ID; propagated in HTTP headers (B3 headers for Zipkin, W3C TraceContext); tools: Jaeger, Zipkin, AWS X-Ray, Tempo; identify which service is the bottleneck in a multi-service request. Golden Signals (SRE): Latency (p50, p95, p99 response times); Traffic (requests per second); Errors (error rate percentage); Saturation (resource utilisation -- CPU, memory, queue depth). SLO (Service Level Objective): define acceptable performance (p99 latency below 200ms, error rate below 0.1%); measure against SLO; error budget = allowed error; SLA is contractual commitment based on SLO.")

p("What is chaos engineering and how do you practice it?",
  "Chaos engineering: deliberately inject failures into production (or production-like) systems to discover weaknesses before they cause real incidents. Principle: if a system must tolerate failures, test that it does before learning it does not during an outage. Process: (1) Define steady state: baseline metrics (error rate, latency, throughput) representing healthy system. (2) Hypothesise: predict system will maintain steady state despite specific failure. (3) Introduce failure: terminate random EC2 instances (Netflix Chaos Monkey); inject network latency (500ms added to all calls to Service A); kill database replicas; exhaust connection pools; CPU stress. (4) Observe: did system maintain steady state? Which alerts fired? Was the failure detected? How long to recover? (5) Fix: address discovered weaknesses before chaos experiment reveals them in production. Tools: Netflix Chaos Monkey (terminates EC2 instances); Gremlin (comprehensive fault injection platform: latency, packet loss, disk full, CPU stress, container kills); LitmusChaos (Kubernetes-native chaos); AWS Fault Injection Simulator (FIS). GameDay: scheduled event where team deliberately introduces failures and practices response; measures MTTD, MTTR, validates runbooks. Starting with chaos: run experiments in staging first; start with small blast radius; run during business hours with team ready to respond; never run without monitoring in place; get leadership buy-in. Outcomes: discover missing circuit breakers; find single points of failure; validate auto-scaling works; test backup and failover procedures; build confidence in system resilience.")

p("Explain the strangler fig pattern for legacy system migration.",
  "Strangler Fig: migration pattern for gradually replacing a legacy monolith with microservices without big-bang rewrite. Named after fig trees that grow around host trees and eventually replace them. Process: (1) Create facade: place a routing layer (API gateway, reverse proxy, load balancer) in front of the legacy system; all traffic flows through facade; no client changes needed. (2) Extract first service: identify a bounded context to migrate first; choose a relatively isolated area with clear boundaries; implement new service with modern stack; migrate data if needed. (3) Reroute: update facade to route requests for that domain to the new service instead of legacy; gradually shift traffic (canary release); monitor for errors. (4) Repeat: extract next bounded context; continue until facade routes everything to new services; legacy receives no traffic and is decommissioned. Key principles: never stop business; always have working software; incremental change is safer than big bang; facade decouples routing from implementation. Challenges: shared database (strangler works best with separate databases per service; if sharing database, use data migration patterns like dual writes during transition); integration complexity during transition period (new service and legacy must stay synchronised for overlapping data). Success factors: strong test suite for regression detection; feature flags for rollback; monitoring to compare old vs new service behavior; business stakeholders aware of gradual migration.")

p("How do you design a rate limiting system?",
  "Rate limiting prevents abuse, ensures fair usage, and protects backend systems from overload. Algorithms: (1) Token Bucket: bucket holds N tokens; request consumes one token; tokens added at rate R per second; burst allowed up to bucket capacity; smooth average rate; Redis implementation: INCR key, EXPIRE key 60; or use Redis sorted set with sliding window. (2) Fixed Window: count requests per time window (100 requests per minute); simple; boundary problem -- 200 requests possible if 100 at end of window 1 and 100 at start of window 2. (3) Sliding Window Log: log timestamp of each request; on new request, count requests in last 60 seconds; exact but memory-heavy (store all timestamps). (4) Sliding Window Counter: hybrid of fixed window; estimate sliding window count using weighted average of current and previous window; memory efficient and accurate. (5) Leaky Bucket: queue of fixed size; requests added to queue; processed at fixed rate; drops requests when queue full; enforces constant outflow rate. Implementation: Redis INCR with TTL for fixed window (atomic operations ensure no race); Lua scripts for atomic check-and-increment; Redis SETNX for mutex; Nginx ngx_http_limit_req_module for rate limiting at reverse proxy level. Distributed rate limiting: all API gateway instances share Redis counter; network call overhead for each request; batch updates or local + global quota split. Rate limit response: 429 Too Many Requests; Retry-After header with seconds until reset; X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset headers. Granularity: per user (authenticated), per API key, per IP (for unauthenticated), per endpoint.")

p("What is a circuit breaker pattern and how does it work?",
  "Circuit breaker (Michael Nygard, Release It!): prevents cascade failures when a downstream service is unavailable or slow. States: (1) Closed (normal): requests flow through to service; track failure rate (errors, timeouts); when failure rate exceeds threshold (50% in last 10 requests) for minimum number of calls, open the circuit. (2) Open (tripped): requests immediately fail without calling the service; return fallback or error response; prevents hammering a failing service; allows service to recover. (3) Half-Open: after timeout (e.g., 30 seconds), allow a single probe request through; if succeeds, close circuit and resume normal operation; if fails, reopen circuit and reset timeout. Configuration: failure threshold (percentage or count); success threshold (how many successes to close from half-open); timeout (how long to stay open); call timeout (how long to wait before counting as failure). Fallbacks: return cached data; return default value; call alternative service; return degraded response (show popular items instead of personalised recommendations). Implementation: Resilience4j (Java); Polly (.NET); Hystrix (Netflix, now in maintenance); custom implementation with Redis for distributed state. Bulkhead pattern (complement): isolate thread pools per dependency; if one dependency exhausts its thread pool, other dependencies still have capacity; prevents single slow dependency from exhausting all threads. Circuit breaker + Retry: retry on transient failures (2-3 retries with exponential backoff); circuit breaker trips if retries are insufficient; avoid retrying when circuit is open.")

p("Explain distributed caching with Redis.",
  "Redis (Remote Dictionary Server): in-memory data structure store; used as cache, session store, message broker, real-time leaderboard, pub/sub system. Data structures: String (get, set, incr -- counters); Hash (hget, hset -- object fields); List (lpush, rpush, lpop -- queue, recent items); Set (sadd, smembers -- unique items, tags); Sorted Set (zadd, zrange -- leaderboards, rate limiting); Stream (xadd -- event log). Caching patterns: Cache-Aside: app checks cache; on miss reads DB; stores in cache with TTL; most common pattern. Cache eviction policies: allkeys-lru (evict least recently used when full -- best for caching); volatile-lru (only evict keys with TTL); allkeys-random; noeviction (return error when full -- for queues). Persistence: RDB snapshots (point-in-time snapshots at intervals -- smaller files, faster restart); AOF (Append-Only File -- logs every write operation -- more durable, larger files, slower restart); both together for best durability. Redis Cluster: sharding across multiple nodes; 16384 hash slots assigned to nodes; client routes to correct node; horizontal scaling; each master has replicas for HA. Sentinel: HA without clustering; monitors masters; automatic failover; promoted replica on master failure; suitable for single-shard deployments. Session storage: store user sessions in Redis with TTL; all app instances share sessions; horizontal scaling works; session expires automatically on TTL. Pub/Sub: SUBSCRIBE/PUBLISH for real-time messaging; not durable (messages lost if no subscriber); use Streams for durable messaging.")

p("How do you implement retry logic and exponential backoff?",
  "Retry logic: automatically retry failed operations to handle transient failures (network glitch, temporary overload, brief service restart). Naive retry: immediate retry in loop; if service is overloaded, immediate retries make it worse; never retry on non-transient errors (4xx -- bad request, 404 not found). Exponential backoff: wait = min(base * 2^attempt, max_wait); attempt 1: wait 1s; attempt 2: wait 2s; attempt 3: wait 4s; attempt 4: wait 8s (capped at max); reduces load on recovering service; gives service time to recover. Jitter: add randomness to backoff: wait = random(0, base * 2^attempt); prevents thundering herd (many clients retrying simultaneously after shared failure at exactly same intervals); full jitter vs decorrelated jitter. Retry budget: maximum number of retries (3-5 typical); exponential backoff with cap (cap at 30-60 seconds); total timeout across all retries. Idempotent operations only: only retry idempotent operations (GET, PUT, DELETE are idempotent; POST is not unless designed to be); retrying non-idempotent operations can cause duplicate side effects (double charge). Retryable errors: 429 Too Many Requests (retry after Retry-After header); 503 Service Unavailable; 504 Gateway Timeout; network timeout. Non-retryable: 400 Bad Request; 401 Unauthorized; 403 Forbidden; 404 Not Found; 422 Unprocessable Entity. Libraries: tenacity (Python); Spring Retry (Java); Polly (.NET). Circuit breaker integration: stop retrying when circuit is open.")

p("What is domain-driven design (DDD) and its key concepts?",
  "Domain-Driven Design (Eric Evans, 2003): approach to software development focusing on the core domain and domain logic; collaboration between technical and domain experts. Key concepts: Domain: problem space the software addresses (e-commerce, banking, logistics). Ubiquitous Language: shared vocabulary between developers and domain experts; same terms in code, documentation, conversations; eliminates translation between business language and technical language. Bounded Context: explicit boundary within which a domain model applies; Customer in Sales context (name, address, orders) differs from Customer in Support context (tickets, preferences); each context has its own model and owns its data; map relationships between contexts (Context Map). Entities: objects with distinct identity that persists through state changes; Order has ID; two orders with same items are still different orders. Value Objects: objects defined by attributes, not identity; Address, Money are value objects; immutable; interchangeable if attributes are equal. Aggregates: cluster of entities and value objects treated as single unit for data changes; Order aggregate contains OrderItems; only root entity (Order) accessed from outside; invariants enforced within aggregate. Domain Events: record of something significant that happened in the domain; OrderPlaced, PaymentReceived; past tense; triggers reactions in same or other bounded contexts. Repositories: abstraction for persisting and retrieving aggregates; hides persistence mechanism; IOrderRepository with findById(), save(). Application Services: orchestrate domain objects for use cases; thin layer; no business logic (that belongs in domain). Domain Services: operations that do not naturally belong to any entity (PricingService that applies discount rules across multiple products).")

p("How do you handle schema migrations in a distributed system?",
  "Schema migration challenges in distributed systems: multiple service instances running old and new code simultaneously during deployment; database must support both; zero-downtime requirements. Expand-Contract (Blue-Green schema migration) pattern: (1) Expand: add new column/table while keeping old; new code writes to both old and new; old code ignores new; no downtime. (2) Migrate: backfill existing data to new schema; run in background; may take hours for large tables. (3) Contract: once all instances run new code and all data migrated, remove old column/table. Example: renaming column from user_name to username; Step 1: add username column; deploy code that reads from username but falls back to user_name; writes to both. Step 2: backfill: UPDATE users SET username=user_name WHERE username IS NULL. Step 3: verify no reads of user_name; deploy code that only uses username; Step 4: drop user_name column. Tools: Flyway (Java -- versioned SQL migration scripts, checksummed, idempotent); Liquibase (database-agnostic, XML/YAML/SQL); Alembic (Python SQLAlchemy); Django migrations. Non-blocking index creation: CREATE INDEX CONCURRENTLY in PostgreSQL (does not lock table); MySQL: Online DDL for most operations; avoid long-running schema locks in production. Feature flags: deploy schema change behind feature flag; enable gradually; roll back flag if issues; clean up old code after validation. Testing: test migrations on production-size data copy; measure migration duration; validate rollback procedure.")

p("Explain the twelve-factor app methodology.",
  "Twelve-Factor App (Heroku, 2011): methodology for building modern, cloud-native, scalable SaaS applications. (1) Codebase: one codebase tracked in version control; multiple deploys (staging, prod) of same codebase. (2) Dependencies: explicitly declare and isolate dependencies (requirements.txt, package.json); never rely on system-level packages. (3) Config: configuration in environment variables (not hardcoded, not in version control); app reads from environment. (4) Backing Services: databases, caches, queues treated as attached resources; swap local MySQL for RDS without code change; URL in config. (5) Build, Release, Run: strict separation; build stage compiles code; release stage combines build with config; run stage executes app in environment. (6) Processes: execute app as stateless processes; share nothing; state stored in backing services (database, Redis); enables horizontal scaling. (7) Port Binding: app is self-contained; exports service by binding to port; does not inject into web server; app is the web server (Gunicorn, Uvicorn). (8) Concurrency: scale out via process model; web process, worker process types; horizontal scaling. (9) Disposability: fast startup and graceful shutdown; containers must start quickly; handle SIGTERM gracefully; stop accepting new requests, finish in-flight requests, exit. (10) Dev/Prod Parity: keep development, staging, production as similar as possible; same backing services; Docker eliminates environment differences. (11) Logs: treat logs as event streams; app writes to stdout; orchestrator collects and routes logs. (12) Admin Processes: run admin tasks as one-off processes (database migrations, scripts) in same environment as app.")

existing = sum(1 for _ in OUT.open()) if OUT.exists() else 0
print(f"Existing pairs: {existing}")
print(f"New pairs to add: {len(pairs)}")

with OUT.open("a") as f:
    for q, a in pairs:
        f.write(json.dumps({"messages": [
            {"role": "user", "content": q},
            {"role": "assistant", "content": a}
        ]}) + "\n")

total = sum(1 for _ in OUT.open())
print(f"Total upgrade_o pairs: {total}")
print("upgrade_o DONE")
