#!/usr/bin/env python3
"""gen_f_fill32.py -- final 55 pairs to reach 1000+"""
import json, pathlib

OUT = pathlib.Path('/workspace/data_upgrades/upgrade_f.jsonl')
OUT.parent.mkdir(parents=True, exist_ok=True)

pairs = []
def p(q, a):
    pairs.append((q, a))

p("What is cross-site tracing (XST)?",
  "Cross-Site Tracing (XST): exploit HTTP TRACE method to steal cookies marked HttpOnly; bypasses HttpOnly protection; largely mitigated in modern browsers. How it works: HTTP TRACE: debugging method; server echoes entire request back to client including all headers; exploit: attacker page executes XMLHttpRequest with TRACE method to origin; response includes request headers including Cookie header; attacker JavaScript reads Cookie header from response; bypasses HttpOnly flag (HttpOnly prevents JS document.cookie access but not header echo); result: attacker reads HttpOnly session cookie. Current status: modern browsers block TRACE cross-origin; XMLHttpRequest blocked for TRACE from different origin; all major browsers (Chrome, Firefox, Safari, IE) block XST since 2008; but: legacy applications, custom HTTP clients, non-browser clients still at risk. Mitigation: disable HTTP TRACE on web servers: Nginx: if ($request_method = TRACE) { return 405; }; Apache: TraceEnable Off (in httpd.conf); IIS: disable TRACE in request filtering; test: curl -X TRACE http://target.com/ (should return 405 Method Not Allowed); verify: if TRACE returns 200 with echoed request: vulnerable; additional context: historical significance: OWASP Top 10 2003 and 2004 included XST; now less prominent as browsers mitigated; still relevant for: custom HTTP implementations, API clients, legacy systems, microservices with internal TRACE exposed.")

p("What is the MITRE ATT&CK Navigator?",
  "ATT&CK Navigator: web-based visualisation tool for MITRE ATT&CK framework; create, annotate, and share ATT&CK matrices. Core functionality: visualise ATT&CK matrix (Enterprise, Mobile, ICS); colour-code techniques; layer-based annotation; share and compare layers; use cases: defensive coverage mapping: colour green = controls in place; red = gap; identify coverage gaps visually; threat actor profiling: colour techniques used by specific APT (from ATT&CK group profiles); visualise actors TTPs; red team planning: mark techniques in red team exercise plan; track what was executed; SOC coverage: map SIEM detection rules to techniques; identify detection blind spots; purple team: red team layer (what was tested) + blue team layer (what was detected) = visualise gaps. Layer operations: create layer: import JSON or build manually in UI; export: JSON (shareable, version-controlled), Excel, SVG image; layer operations: multi-layer: overlay multiple layers; score: apply numeric score to technique (coverage level 0-3); comment: document reasoning per technique; filter: filter by tactic, technique, data source; compare: compare two layers (identify differences). Practical workflow: threat intel layer: use ATT&CK group pages; G0016 (APT28) has associated techniques; export layer; visualise in Navigator; defensive layer: map all SIEM rules, EDR controls to ATT&CK techniques; gap analysis: overlay threat intel layer on defensive layer; techniques with threat actor coverage but no defensive coverage = priority gaps; automated: tools generate Navigator layers: Vectr, Tidal Cyber, Picus Security, DeTT&CT; DeTT&CT: Defence Tactics Techniques and CTI; generates data source and detection coverage layers; ATT&CK Workbench: custom ATT&CK knowledge base; add custom techniques; hosted version at attack.mitre.org/versions/v14/; JSON export for integration with SIEM and other tools.")

p("What is cyber deception and honeypot deployment?",
  "Honeypot: decoy system designed to attract attackers; detect intrusion; gather intelligence; waste attacker time. Honeypot types by interaction: low-interaction: simulate services (open ports respond; no full OS); Honeyd: simulate multiple OS on single host; OpenSSH honeypot responds to SSH connection but does not provide real shell; limited attacker actions; easy to deploy; less intelligence; medium-interaction: more realistic service simulation; Dionaea (malware collector): simulates vulnerable services; captures exploit attempts and malware payloads; Conpot (ICS/SCADA honeypot): simulates industrial protocols; high-interaction: real OS with real services; attacker gets genuine shell; maximum intelligence; higher risk (attacker may pivot from honeypot); Cowrie: SSH/Telnet honeypot; full fake shell; logs all attacker commands; credential logging; captures binaries; highly popular; isolated from real network. Honeynet: network of honeypots; simulate entire vulnerable network segment; capture lateral movement behaviour; multi-stage attack observation; Honeynet Project (research organisation): provides tools and research. Deployment considerations: network placement: internet-facing honeypot: observe external attacker techniques; internal honeypot: detect insider threats and lateral movement after perimeter breach; production vs research: production: detect attacks on your organisation (internal; alert-generating); research: study attacker behaviour (internet-facing; not connected to internal network); isolation: honeypot should be isolated from production; if attacker escapes honeypot: should not reach real systems; monitoring: all honeypot traffic logged; alerts on any connection; SIEM integration. Cowrie deployment: pip install cowrie; configure simulated hostname, filesystem; fake credentials (capture what attackers try); listen on port 22 or redirect from port 22; logs: cowrie.json (structured); session logs; downloaded file captures; analyse: what commands do attackers run? What credentials tried? What malware uploaded? Threat intelligence from honeypots: credential brute-force attempts: reveal password spray patterns; attacker tools: malware deposited in honeypot; analyse; C2 infrastructure: malware connects to C2; capture C2 IPs and domains; new exploits: observe novel exploitation attempts; share intelligence: MISP, OTX, FS-ISAC sharing communities. Active defence: legal considerations: honeypots: generally legal (collecting intelligence on own systems); hackbacks: illegal in most jurisdictions; tarpit: slow attacker down (waste attacker time); legal under own network; attribution: honeypot data helps attribute attacks (consistent tooling, infrastructure, TTPs).")

p("What is SAST versus DAST versus IAST?",
  "Application security testing types: SAST (static), DAST (dynamic), IAST (interactive); each finds different vulnerability classes; complement each other. SAST (Static Application Security Testing): analyse source code, bytecode, or binary without executing; finds vulnerabilities in code before runtime; white-box testing; advantages: early in SDLC (shift left; find before deploy); covers all code paths (not just tested paths); developer feedback in IDE; detailed remediation (exact line of code); disadvantages: high false positive rate (code may be fine at runtime); cannot detect runtime issues; language-specific (Java SAST tool does not scan Python); misses configuration issues; tools: commercial: Checkmarx, Veracode, Fortify (Micro Focus), SonarQube (partial), Codacy; open-source: Semgrep (multilanguage, custom rules), CodeQL (GitHub; query-based; powerful), Bandit (Python), SpotBugs (Java), FindSecBugs, Brakeman (Ruby on Rails). DAST (Dynamic Application Security Testing): test running application from outside; black-box testing; sends HTTP requests; observes responses; advantages: finds runtime issues missed by SAST; no source code required; low false positives (issues confirmed executable); finds: XSS, SQL injection, CSRF, auth issues, misconfigurations; disadvantages: cannot test code not reached (low coverage vs SAST); misses logical vulnerabilities; slower (must deploy and test); cannot find most cryptographic issues; requires running environment; tools: OWASP ZAP (open-source; most widely used DAST), Burp Suite (manual + automated scan), Nikto (lightweight; quick), Acunetix, Invicti, HCL AppScan, StackHawk (CI/CD DAST). IAST (Interactive Application Security Testing): instrument application with agent; test dynamically; agent monitors code execution; advantages: runtime context: knows exactly which code executed; lower false positives than SAST; finds vulnerabilities DAST cannot see (code-level); real-time: finds issues as tests run; works with automated test suite (no separate scan needed); disadvantages: agent overhead; language-specific; requires integration with test suite; tools: Contrast Security: strongest IAST; Seeker (Synopsys); Checkmarx CxIAST; Hdiv Security. RASP vs IAST: IAST: security testing (find issues); RASP: security runtime protection (prevent exploitation); both use instrumentation; different purpose. Choosing: use all three for comprehensive coverage; SAST early in CI/CD pipeline on code commit; DAST after deployment to staging; IAST integrated with functional test suite; prioritise SAST + DAST minimum; IAST adds coverage for teams with mature practices.")

p("What is advanced persistent threat (APT) techniques in cloud environments?",
  "APT in cloud: sophisticated threat actors targeting cloud infrastructure; long dwell time; specific techniques for cloud environments. Initial access: phishing targeting cloud credentials (Google Workspace admin, Microsoft 365 admin, AWS console); credential stuffing against cloud portals; supply chain compromise affecting cloud tenant; public exposure: internet-facing S3 buckets, open management ports (EC2 with port 22/3389 open), misconfigured Kubernetes API server; developer credential exposure: AWS access key in public GitHub repository; OAuth token in mobile app; persistence: IAM backdoor: create additional IAM user or access key; survives password changes; conditional: create access key that only activates if primary deleted; Lambda backdoor: modify existing Lambda function; adds persistence code; harder to detect than new Lambda; CloudFormation: add resource to existing stack; CloudTrail disable: DeleteTrail or StopLogging (if IAM permissions allow); resource policy: modify S3, Lambda, or IAM role policy to allow external access; privilege escalation: IAM privilege escalation paths (see AWS pentest entry); cross-account role assumption: if misconfigured cross-account trust; assume external roles; SCP bypass: find child account without tight SCP; pivot via organisation trust. Lateral movement: cross-account access: assume roles in other accounts in AWS Organisation; shared VPC: move between workloads sharing VPC; credentials in SSM Parameter Store or Secrets Manager: retrieve credentials stored for applications; EC2 instance connect: if IAM allows ec2-instance-connect:SendSSHPublicKey: push SSH key to any EC2; connect as any user; Kubernetes lateral movement: service account tokens: high-privilege service accounts allow cross-namespace access; metadata pivot: reach EC2 instance metadata from pod; cloud to on-premises: VPN or Direct Connect from cloud to on-premises; if access to cloud network: reach on-premises segments. Exfiltration in cloud: S3 presigned URLs: generate URL; exfiltrate without authentication trail on victim; Cloudfront distribution: route exfiltration through victim CloudFront (legitimate domain); SQS/SNS: subscribe to victim queue; receive data; data pipeline: Kinesis, Firehose stream exfiltration; slow trickle exfiltration through normal AWS service usage patterns. Detection: CloudTrail: all API calls logged; anomaly detection: unusual API calls, calls from unusual regions, calls at unusual hours, new access key creation, IAM policy changes, CloudTrail disable attempt; GuardDuty: ML-based anomaly detection; alerts: credential exfiltration, anomalous S3 access, unusual API calls, mining activity; Macie: sensitive data in S3 access patterns; UEBA: user behaviour analytics on IAM user actions.")

p("What is security in CI/CD pipelines?",
  "CI/CD pipeline security: integrate security controls throughout continuous integration and deployment; prevent insecure code or infrastructure from reaching production. Pipeline threat model: code injection: attacker-controlled code in pipeline (supply chain attack via dependency, compromised developer account, PR injection); credential theft: secrets stored in environment variables or logs; pipeline configuration tampering: modify .github/workflows or Jenkinsfile; lateral movement: pipeline with broad cloud permissions; attackers compromise pipeline for cloud access; insecure deployment: vulnerable code deployed without security check. Security controls by stage: pre-commit: hooks: detect-secrets, git-leaks, trufflehog (scan for secrets before commit); IDE plugins: SonarLint, Semgrep (real-time feedback); developer workstation: full disk encryption, MFA, EDR. Commit/push: branch protection: protected main branch; require PR review before merge; no force push; signed commits: GPG signing; verify author identity; CODEOWNERS: security team review required for security-sensitive paths (.github/workflows, IAM configs, security configs). Pull request: SAST: Semgrep, CodeQL, Checkmarx (scan code changes); SCA: Snyk, Dependabot (dependency vulnerabilities); IaC scanning: Checkov, tfsec (Terraform security); secret scanning: GitHub Advanced Security, GitLab secret detection; code review: security checklist; OWASP Top 10 per language. Build: signed artifacts: sign build output (Sigstore, in-toto); provenance attestation; SBOM generation (Syft, CycloneDX); container image scanning: Trivy, Snyk Container; scan base image + application layers; dependency hash verification: verify hashes match expected (npm lockfile, pip hash check); ephemeral build environment: fresh environment per build; no persistent secrets. Test: DAST: OWASP ZAP, StackHawk; test running application in staging; infrastructure security testing: AWS Security Hub, Prisma Cloud; compliance checks: ensure deployment meets compliance requirements. Deployment: secrets management: Vault, AWS Secrets Manager, Azure Key Vault; never in environment variables or code; least-privilege deployment credentials: pipeline role has only deploy permissions, not admin; deployment gates: manual approval for production; require sign-off; canary deployment: gradual rollout; detect issues before full deployment. Runtime: CWPP: monitor deployed workloads; CSPM: cloud configuration compliance; production monitoring: anomaly detection, SIEM integration; automated rollback: detect runtime anomaly; trigger rollback. Pipeline hardening: restrict who can modify pipeline config (.github/workflows); audit pipeline changes; no self-hosted runners with broad access (or strictly control self-hosted runners); ephemeral runners (GitHub Actions hosted, AWS CodeBuild): no persistence; rotate credentials: pipeline credentials rotated regularly; principle of least privilege: pipeline role has only what it needs.")

p("What is a security baseline and configuration hardening standard?",
  "Security baseline: minimum security configuration standard; applied consistently across systems; reduces attack surface; measured and enforced. Why baselines: ad hoc hardening: each admin applies different settings; inconsistent; audit failures; security gaps; standardised baseline: repeatable, auditable, consistent; reduces human error; enables automated compliance checking. Baseline sources: CIS Benchmarks: most widely adopted; community-developed; detailed rationale for each setting; available for: Windows Server, Windows 10/11, Ubuntu/Debian/RHEL, macOS, Docker, Kubernetes, cloud (AWS CIS, Azure CIS, GCP CIS); Level 1: baseline; Level 2: higher security (may impact functionality); free download after registration; DISA STIG (Security Technical Implementation Guides): US Department of Defense; stricter than CIS; applicable to government and regulated industries; SCAP-compliant (automated checking); NIST Special Publications: SP 800-70 (National Checklists Program); references vendor-specific checklists; vendor-specific: Microsoft Security Baseline (downloadable); Apple Security Guide; NSA Cybersecurity guidance. Windows baseline key settings: password policy: minimum 14 characters, complexity, 60-day maximum age; lockout: 5 attempts, 30-minute lockout; account policies: disable guest and default admin; rename default admin; audit policy: log success and failure for: logon/logoff, account management, policy change, privilege use, process tracking; network: disable SMBv1, require SMB signing; firewall: enabled all profiles; restrict inbound; protocols: disable weak TLS ciphersuites; services: disable: Telnet, FTP Server, SNMP (if not needed); UAC: highest setting; Defender: real-time protection, cloud-delivered protection. Baseline implementation: CIS-CAT (CIS Configuration Assessment Tool): automated CIS Benchmark assessment; free lite version, Pro version; OpenSCAP: open-source SCAP scanner; SCAP content from NIST NCP; Group Policy (Windows): apply baseline via GPO; Security Compliance Toolkit: Microsoft-provided baseline GPO templates; Ansible/Chef/Puppet: apply baseline configuration at scale; InSpec (Chef): compliance testing as code; Terraform Sentinel: enforce baseline in IaC. Baseline exceptions: formal exception process: business justification, risk acceptance, compensating control, review date; exceptions tracked in GRC tool; periodic review of exceptions. Continuous monitoring: CIS benchmark scanning via: Tenable.sc (Nessus with compliance policies), Qualys Policy Compliance, AWS Security Hub CIS checks, Azure Policy (CIS initiative); drift detection: alert when system deviates from baseline; auto-remediate where safe.")

p("What is malware reverse engineering methodology?",
  "Malware reverse engineering: analyse malicious software to understand behaviour, capabilities, infrastructure, and detect or counter it. Setup: isolated environment: VM (no host-guest clipboard/file sharing); snapshot before analysis; network: host-only adapter + simulated internet (FakeNet-NG or INetSim: simulate DNS, HTTP, SMTP; malware gets responses; researcher observes traffic without real network); Windows VM preferred for Windows malware: Windows 7 or 10; disable Windows Defender before analysis; FlareVM or REMnux: pre-configured RE environments with all tools. Static analysis first: file identification: file (Linux) or PEiD (Windows); identify PE, ELF, Mach-O, APK; hashing: MD5, SHA-256; VirusTotal lookup (35 AV engines; check detection rate); PE analysis (Windows): peframe, pe-sieve, pestudio; check: imports (which Windows APIs called), exports, sections (unusual sections, high entropy = packed), strings (extract ASCII and Unicode strings: file paths, URLs, registry keys, error messages, C2 domains), PE headers (compilation time, linker version); strings analysis: strings malware.exe (Linux); FLOSS (FireEye): extract obfuscated strings; find: IP addresses, URLs, C2 domains, file paths, registry keys, mutex names, error messages; packing detection: high entropy in code section: likely packed; PEiD or Detect-It-Easy (DiE); common packers: UPX (unpack: upx -d malware.exe), custom packers require dynamic analysis. Dynamic analysis: process monitoring: Process Monitor (ProcMon): file system, registry, network, process activity; filter on malware PID; Process Hacker: view processes, threads, handles, memory; monitor process injection; network monitoring: Wireshark: capture all traffic; FakeNet-NG: intercept and respond; log HTTP requests (C2 URLs), DNS queries (C2 domains); registry monitoring: ProcMon filter on Registry; what keys created or modified?; file monitoring: ProcMon filter on File System; what files created/modified/deleted?; persistence: check autoruns before and after execution. Disassembly and decompilation: Ghidra (free, NSA): disassemble and decompile; IDA Pro (commercial, industry standard): professional disassembler; decompiler (Hex-Rays); Binary Ninja: alternative commercial; Cutter: open-source (Rizin backend) with decompiler; analysis: find main function; identify C2 communication function; decrypt strings; understand evasion techniques; x64dbg / OllyDbg: dynamic debugger; step through execution; inspect memory; break on interesting API calls (VirtualAlloc, WriteProcessMemory for injection, CreateRemoteThread). Output: indicators of compromise (IOCs): file hashes, C2 IP/domains, registry keys, file paths, mutex names, network signatures; YARA rules: pattern matching rule to detect malware in files and memory; ATT&CK mapping: which techniques does malware use? (process injection, registry persistence, C2 over HTTP).")

existing = sum(1 for _ in OUT.open()) if OUT.exists() else 0
print(f"Existing pairs: {existing}")
print(f"New pairs to add: {len(pairs)}")

with OUT.open("a") as f:
    for q, a in pairs:
        f.write(json.dumps({"messages": [
            {"role": "user", "content": q},
            {"role": "assistant", "content": a}
        ]}) + "\n")

total = sum(1 for _ in OUT.open())
print(f"Total upgrade_f pairs: {total}")
if total >= 1000:
    print("upgrade_f TARGET MET -- 1000+ pairs!")
else:
    print(f"Need {1000-total} more pairs")
