#!/usr/bin/env python3
"""Append extra neuroscience pairs to upgrade_l.jsonl to reach 200"""
import json, pathlib

OUT = pathlib.Path('/workspace/data_upgrades')

extra = [
    ("What is the anterior insular cortex and agency?", "The anterior insula integrates interoceptive signals with higher cognitive information, generating the subjective sense of 'feeling.' It is active during pain affect, disgust, uncertainty, and the experience of unfairness. Damasio's somatic marker hypothesis attributes decision-making guidance to insular interoceptive signals. The right anterior insula is linked to agency -- the sense of being the author of one's actions -- and disruption contributes to depersonalisation."),
    ("What is neuroethics?", "Neuroethics examines the ethical, legal, and social implications of neuroscience -- particularly brain imaging, neural enhancement, neurotechnology, and neurodiversity. Issues include: mental privacy and brain reading; cognitive enhancement fairness; neurolaw (using brain data in legal decisions); the boundaries of personal identity and responsibility when brain function is altered; and ethical use of brain organoids and chimeric animals in research."),
    ("What is the Allen Brain Atlas?", "The Allen Brain Atlas (Allen Institute) is a comprehensive, publicly available gene expression atlas of the mouse and human brain using in situ hybridisation (ISH) and RNA-seq techniques. It maps the expression of thousands of genes across brain regions at cellular resolution. Tools include the Allen Mouse Brain Atlas, Human Brain Atlas, and Cell Types database, enabling researchers to map molecular heterogeneity and identify cell-type-specific markers."),
    ("What is single-cell RNA sequencing in neuroscience?", "scRNA-seq enables transcriptomic profiling of individual neurons, revealing molecular heterogeneity within brain regions. It has identified dozens of neuronal subtypes in the cortex, hippocampus, and retina based on gene expression -- far more than previously appreciated. Spatial transcriptomics (MERFISH, Slide-seq) combines gene expression with spatial coordinates, mapping cell-type distributions across brain slices with submicrometre resolution."),
    ("What is the BRAIN Initiative?", "The US BRAIN (Brain Research through Advancing Innovative Neurotechnologies) Initiative, launched 2013, aims to develop tools for recording from large numbers of neurons simultaneously, map all cell types in the brain (BRAIN Cell Census Network), and understand neural circuit function. It has funded Neuropixels probes, Clarity tissue clearing, single-cell sequencing pipelines, and the connectomics programme -- producing petabyte-scale datasets of brain structure and function."),
    ("What is the Human Brain Project?", "The Human Brain Project (HBP, EU Flagship, 2013-2023) aimed to develop multi-scale computational models of the human brain, integrate neuroscience data into unified platforms, and develop neuromorphic computing. Key outputs: the EBRAINS research infrastructure (data sharing, simulation), Blue Brain Project multi-compartment neuron and circuit models, neuromorphic chips (Intel Loihi, IBM TrueNorth), and platforms for clinical neuroscience data integration."),
    ("What is the neural basis of consciousness -- specific mechanisms?", "Key proposed mechanisms: (1) thalamo-cortical loops maintain conscious content; (2) gamma synchrony (40 Hz) in cortical networks binds distributed representations; (3) global ignition -- late, widespread cortical activation marks conscious access (Dehaene); (4) posterior cortical hot zone (V1 to TPJ and parietal areas) contains conscious content; (5) disruption of cortico-cortical and cortico-thalamic connections in anaesthesia and vegetative state eliminates consciousness."),
    ("What is locked-in syndrome?", "Locked-in syndrome (LIS) results from pontine damage (basilar artery thrombosis) destroying corticospinal and corticobulbar tracts while sparing consciousness, vertical gaze, and blinking (controlled by the midbrain). Patients are alert and aware but completely paralysed except for vertical eye movements. BCI systems have allowed LIS patients to communicate by modulating cortical signals (P300, SSVEP, motor imagery EEG). Speller BCIs (BrainGate) restore communication at rates of several words per minute."),
    ("What is the vegetative state and disorders of consciousness?", "Vegetative state (VS/UWS -- unresponsive wakefulness syndrome) involves preserved sleep-wake cycles and reflexes but no evidence of awareness. Minimally conscious state (MCS) shows fluctuating signs of awareness. Adrian Owen's EEG/fMRI paradigms ('imagine playing tennis' activates SMA; 'imagine walking through rooms' activates PPA) have detected covert awareness in some clinically vegetative patients. Accurate diagnosis is critical, as many VS patients may be misdiagnosed."),
    ("What is functional connectivity in the brain?", "Functional connectivity (FC) refers to statistical correlations between time-series of activity across brain regions -- measured by resting-state fMRI, EEG coherence, or MEG. Independent component analysis (ICA) and seed-based correlation identify intrinsic brain networks (DMN, sensorimotor, visual, executive control). FC predicts cognitive performance, psychiatric diagnosis, and recovery from stroke. Graph theory metrics (modularity, small-worldness, hub connectivity) characterise network topology."),
    ("What is effective connectivity?", "Effective connectivity refers to the directed causal influence one neural area exerts on another -- beyond statistical correlation. Methods: Granger causality (time-series precedence); dynamic causal modelling (DCM -- compares generative models of causal architectures); structural equation modelling; and transfer entropy. Effective connectivity reveals hierarchical organisation (top-down predictions vs bottom-up prediction errors) and how disease disrupts causal brain dynamics."),
    ("What is the default mode network's role in memory?", "The DMN is critically involved in episodic memory retrieval and future simulation. Hippocampal-neocortical interactions during rest and sleep replay past experiences and preplay future scenarios -- consolidating episodic memories and enabling mental time travel. DMN hubs (posterior cingulate, angular gyrus) support autobiographical memory, scene construction, and theory of mind. Their preferential amyloid accumulation in early Alzheimer's suggests the DMN is a vulnerability hub for neurodegeneration."),
    ("What is the suprachiasmatic nucleus?", "The SCN in the anterior hypothalamus is the master circadian clock. It receives light input via the retinohypothalamic tract (melanopsin-containing ipRGCs) and synchronises peripheral clocks throughout the body. SCN neurons maintain ~24-hour firing rhythms even in isolation. The SCN coordinates sleep timing, hormone release (melatonin from the pineal gland at night; cortisol in the morning), body temperature, and metabolism. Jet lag and shift work disrupt SCN entrainment."),
    ("What is the corticospinal tract?", "The corticospinal tract (CST) is the primary voluntary motor pathway. Upper motor neurons in M1 (and premotor/SMA) descend through the internal capsule, basis pedunculi, and pyramids (medullary decussation -- 85% cross), forming the lateral CST in the contralateral spinal cord, synapsing on lower motor neurons (alpha motor neurons) that innervate muscles. UMN lesions cause contralateral spastic paresis; LMN lesions cause ipsilateral flaccid paralysis with wasting."),
    ("What is the rubrospinal tract?", "The rubrospinal tract originates in the red nucleus of the midbrain (receives input from cerebellum and M1), decussates immediately, and descends in the lateral funiculus to synapse on interneurons and motor neurons controlling limb movements. In humans it is less prominent than in lower mammals (the CST is dominant), but it may contribute to residual motor function after CST damage. Cerebellar tremor partly reflects red nucleus dysfunction."),
    ("What is the spinocerebellar tract?", "The spinocerebellar tracts carry proprioceptive and other sensory information from the body to the cerebellum. Dorsal spinocerebellar tract (ipsilateral, from Clarke's nucleus, L1-C8 level) -- carries information from muscle spindles and Golgi tendon organs in the lower limb. Ventral spinocerebellar tract (bilateral) and cuneocerebellar tract (upper limb) complete the system. This input allows the cerebellum to compare intended vs actual movement for error correction."),
    ("What is spinal cord anatomy and injury?", "The spinal cord contains 31 segments (8 cervical, 12 thoracic, 5 lumbar, 5 sacral, 1 coccygeal). White matter tracts (ascending sensory, descending motor) surround grey matter (dorsal sensory horns, ventral motor horns). SCI classification uses the ASIA Impairment Scale (A-E). Complete SCI eliminates all function below the level; incomplete preserves some. Central cord syndrome (most common -- hand weakness > leg weakness), Brown-Sequard (hemisection), and anterior cord syndromes have distinct patterns."),
    ("What is the dorsal column-medial lemniscal system?", "The dorsal column-medial lemniscal (DCML) system carries fine touch, vibration, and proprioception. Primary afferents (A-beta) enter the dorsal horn and ascend ipsilaterally in the dorsal columns (fasciculus gracilis for leg, cuneatus for arm) to the dorsal column nuclei in the medulla, where second-order neurons decussate and ascend as the medial lemniscus to the VPL thalamus, then to S1. Dorsal column lesions cause ipsilateral loss of fine touch and proprioception."),
    ("What is the anterolateral system?", "The anterolateral system (ALS -- spinothalamic tract plus other components) carries pain, temperature, and crude touch. Primary nociceptive and thermoreceptive afferents (A-delta and C fibres) synapse in the dorsal horn (Rexed laminae I, II, V). Second-order neurons cross in the anterior commissure within 1-2 segments and ascend contralaterally in the anterolateral funiculus to VPL (lateral spinothalamic) and intralaminar thalamic nuclei (anterior spinothalamic). ALS lesions cause contralateral pain and temperature loss."),
    ("What is the cranial nerve examination?", "Cranial nerve testing: CN I (olfaction -- smell each nostril); CN II (visual acuity, visual fields, fundoscopy, afferent PLR); CN III/IV/VI (eye movements, ptosis, pupil); CN V (facial sensation, masseter/temporalis muscles, corneal reflex); CN VII (facial movement, taste anterior 2/3 tongue, corneal reflex efferent); CN VIII (hearing, Rinne/Weber, caloric); CN IX/X (palate, gag reflex, voice); CN XI (SCM, trapezius); CN XII (tongue -- deviation toward lesion side in LMN lesion)."),
    ("What is the cerebellopontine angle?", "The cerebellopontine angle (CPA) is a CSF-filled space between the cerebellum, pons, and petrous temporal bone. Cranial nerves VII (facial) and VIII (vestibulocochlear) traverse this space. CPA tumours -- most commonly acoustic neuromas (vestibular schwannomas, arising from Schwann cells of CN VIII's vestibular branch) -- cause unilateral hearing loss, tinnitus, disequilibrium, and later facial weakness. Microsurgery or stereotactic radiosurgery (Gamma Knife) are treatment options."),
    ("What is the internal capsule?", "The internal capsule is a dense white matter tract connecting the cortex with subcortical structures. It has anterior limb (frontopontine and thalamo-prefrontal fibres), genu (corticobulbar fibres for head and neck), and posterior limb (corticospinal fibres -- somatotopically arranged; thalamocortical fibres; corticorubral fibres). Internal capsule infarction (lacunar stroke from small vessel disease) causes contralateral pure motor hemiplegia (posterior limb) or hemianaesthesia (sensory radiation)."),
    ("What is aphasia classification?", "Aphasia (acquired language disorder from brain damage): Broca's (expressive, non-fluent, effortful speech, relatively preserved comprehension, lesion in posterior inferior frontal gyrus and insula); Wernicke's (receptive, fluent jargon, impaired comprehension, lesion in posterior superior temporal gyrus); conduction (impaired repetition, relatively preserved production and comprehension, arcuate fasciculus lesion); global (all modalities severely impaired); and anomic (word-finding difficulty, most common residual type)."),
    ("What is agnosia?", "Agnosia is failure to recognise stimuli despite intact sensory perception and intelligence. Visual object agnosia (apperceptive -- cannot form whole percept; associative -- percept formed but cannot match to memory). Prosopagnosia (cannot recognise faces). Topographagnosia (cannot navigate familiar environments). Auditory agnosia (cannot recognise non-verbal sounds or music -- amusia). Tactile agnosia (astereognosis -- cannot recognise objects by touch despite intact touch). Agnosias are caused by lesions in unimodal or multimodal association cortex."),
    ("What is apraxia?", "Apraxia is impaired ability to perform purposeful motor acts despite intact motor and sensory systems and comprehension. Ideomotor apraxia (cannot pantomime actions on command but can perform them in context -- typically left parietal lobe lesions). Ideational apraxia (cannot sequence multi-step actions -- associated with Alzheimer's). Buccofacial apraxia (impaired voluntary oral and facial movements -- associated with Broca's area lesions). Constructional apraxia (cannot draw or construct spatial arrangements -- right parietal lesion)."),
    ("What is the neural basis of reading and dyslexia?", "Reading activates a left-hemisphere network: visual word form area (VWFA, left occipitotemporal -- the 'visual word form area' or 'letterbox area') for orthographic processing; Broca's area for phonological assembly; and temporal regions for semantic access. Dyslexia involves impaired phonological processing linked to reduced activation in left temporoparietal and occipitotemporal regions, and reduced white matter (arcuate fasciculus) connectivity. Structured phonics instruction is the evidence-based intervention."),
    ("What is the neuroscience of addiction -- specific circuit changes?", "Repeated drug exposure causes: LTP at VTA-to-NAc synapses (glutamate AMPA receptor insertion); decreased D2 receptor availability in the striatum (measured by PET), reducing reward sensitivity; increased DeltaFosB in NAc and PFC; and hypofunction of the PFC-to-NAc inhibitory control pathway. These changes shift the balance from goal-directed to habitual drug-seeking, sensitise drug cue responses (via amygdala LTP), and impair cognitive control. NAc shell-to-VTA GABAergic pathways inhibit dopamine release and are potentiated by repeated drug exposure."),
    ("What is neurodegeneration and protein aggregation?", "Neurodegenerative diseases are characterised by progressive neuronal death and accumulation of misfolded proteins: Alzheimer's (amyloid-beta plaques, tau tangles); Parkinson's and Lewy body dementia (alpha-synuclein Lewy bodies); ALS and FTD (TDP-43 and FUS aggregates); Huntington's (polyglutamine-expanded huntingtin); and prion disease (PrPSc -- infectious misfolded PrP). Propagation of misfolded proteins from cell to cell (prion-like spreading) may drive disease progression along anatomically connected pathways."),
    ("What is the neurovascular unit?", "The neurovascular unit (NVU) comprises neurons, astrocytes, pericytes, endothelial cells, and the extracellular matrix working together to regulate cerebral blood flow, BBB integrity, and neural metabolism. Astrocyte endfeet contact blood vessels; pericytes regulate capillary diameter; endothelial tight junctions form the BBB. NVU dysfunction contributes to Alzheimer's (vascular contribution, amyloid angiopathy), stroke, and diabetes-related cognitive decline."),
    ("What is the significance of the Nobel Prize in neuroscience?", "Multiple Nobel Prizes have been awarded for neuroscience discoveries: 1906 (Golgi and Ramon y Cajal -- neuron doctrine); 1932 (Sherrington and Adrian -- nerve impulse physiology); 1963 (Eccles, Hodgkin, Huxley -- ion channels and action potentials); 1970 (Katz, von Euler, Axelrod -- neurotransmission); 1991 (Neher and Sakmann -- patch clamp); 2000 (Carlsson, Greengard, Kandel -- signal transduction); 2004 (Axel and Buck -- olfactory receptors); 2014 (O'Keefe, May-Britt and Edvard Moser -- place and grid cells)."),
    ("What is the squid giant axon and its contribution to neuroscience?", "The squid giant axon (up to 1 mm diameter) enabled Hodgkin and Huxley (1952) to perform voltage-clamp recordings and derive the mathematical model of the action potential -- one of the most important achievements in biology. Its large size also allowed insertion of electrodes and measurement of internal ionic composition. The squid giant axon revealed the ionic basis of electrical signalling and continues to be used for testing hypotheses about axon physiology."),
    ("What is the entorhinal cortex?", "The entorhinal cortex (EC) is a multimodal hub interfacing the hippocampus with neocortex. It contains grid cells, head direction cells, border cells, and speed cells -- components of the brain's spatial navigation system. The EC relays processed neocortical information to the hippocampus via the perforant path, and transmits hippocampal output back to the neocortex. Entorhinal cortex is the earliest site of tau pathology in Alzheimer's disease -- explaining early memory deficits."),
    ("What is the role of the insula in addiction?", "The insula is critical for the interoceptive signals that drive craving in addiction. Urge to smoke is associated with insular activity; insular lesions (stroke) caused cessation of smoking without withdrawal in heavy smokers (Naqvi et al., 2007). The insula tracks the bodily signals of drug craving (increased heart rate, sweating, tension) and translates them into the conscious urge to use. Insular targets are being explored for non-invasive neuromodulation of addiction."),
    ("What is the posterior parietal cortex?", "The posterior parietal cortex (PPC -- BA 7, 39, 40) integrates visual, somatosensory, and proprioceptive information for spatial cognition, attention, and sensorimotor transformation. The intraparietal sulcus (IPS) encodes spatial coordinates for reaching and grasping (LIP for eye, AIP for hand). The angular gyrus (BA39) supports semantic processing and mathematical cognition. Right PPC damage causes hemispatial neglect; bilateral PPC damage causes Balint's syndrome (simultanagnosia, optic ataxia, ocular apraxia)."),
    ("What is the dorsolateral prefrontal cortex function?", "The dlPFC (BA9/46) is the primary neural substrate for working memory and executive control. It maintains information over delays via persistent neuronal firing, facilitates top-down modulation of sensory cortices, and implements cognitive control (task switching, interference resolution, planning). dlPFC activity is reduced in schizophrenia (during working memory tasks -- hypofrontality), depression, and ADHD. TMS and tDCS over dlPFC modulate working memory, decision-making, and mood."),
    ("What is subplate neurons?", "Subplate neurons are the earliest-born cortical neurons forming the transient subplate zone beneath the developing cortical plate. They receive thalamic input and relay it to the overlying cortical plate before thalamocortical connections are established. They pioneer corticothalamic projections and regulate critical period timing in the visual cortex. Loss of subplate neurons disrupts cortical circuit formation and is implicated in autism, schizophrenia, and periventricular leukomalacia from premature birth."),
    ("What is cortical column?", "A cortical column (Mountcastle, 1957) is a vertical ensemble of neurons (~100 microns wide, 6 layers deep) with similar functional properties -- in S1, all neurons in a column respond to the same skin location and modality; in V1, all neurons share similar orientation preference. Columns are considered functional units of cortical processing. The minicolumn (~30 microns, ~80 neurons) is the smallest canonical circuit. Columnar organisation is most pronounced in primary sensory and motor areas."),
    ("What is the cortical layers and their connectivity?", "Cortical layers have distinct connectivity profiles: Layer I (sparse neurons, apical dendrites); Layer II/III (cortico-cortical projections, association fibres); Layer IV (thalamic input -- thickest in primary sensory cortex, absent in motor cortex); Layer V (corticospinal, corticobulbar, and corticostriatal projection neurons, including Betz cells in M1); Layer VI (corticothalamic feedback). Feedforward connections terminate in Layer IV; feedback connections in Layers I, II, and VI."),
    ("What is the claustrum?", "The claustrum is a thin, elongated structure beneath the insula with dense reciprocal connections to virtually all cortical areas. It has been proposed (Crick and Koch) as a potential consciousness integrator -- its widespread connectivity could bind information across cortical areas. Electrical stimulation of the claustrum can suppress consciousness in monkeys and in a human epilepsy patient. Its specific function remains poorly understood -- candidates include attentional salience filtering, sensory prediction, and cross-cortical synchrony."),
    ("What is the locus coeruleus?", "The locus coeruleus (LC) in the pons is the primary source of noradrenaline in the CNS. Despite containing only ~50,000 neurons in humans, LC axons project to virtually all CNS regions. LC activity regulates arousal, attention, stress responses, and cognitive performance. The LC-NE system optimises the signal-to-noise ratio in cortical processing (gain modulation). LC neurodegeneration occurs early in Alzheimer's disease (before hippocampal neurodegeneration), contributing to early cognitive and sleep disturbances."),
    ("What is the perforant path?", "The perforant path is the major input pathway to the hippocampus, originating in the entorhinal cortex (EC) Layer II to the dentate gyrus and CA3 (lateral and medial EC convey different information), and EC Layer III to CA1 and subiculum. It carries highly processed multimodal information from association cortex. Disruption of the perforant path in Alzheimer's disease (EC layer II neurodegeneration, tau pathology) accounts for early memory impairment. The perforant path is a major site of theta-modulated LTP in spatial learning."),
    ("What is the CA1 region of hippocampus?", "CA1 is the main output of the hippocampus, receiving input from CA3 (via Schaffer collaterals) and direct EC input (Layer III, via the temporoammonic path). CA1 pyramidal neurons project to the subiculum and directly back to the EC, completing the hippocampal circuit. CA1 is most vulnerable to ischaemia (selective vulnerability -- its energy demands exceed supply during even brief hypoxia). CA1 place cells form the internal map for spatial navigation."),
    ("What is the dentate gyrus?", "The dentate gyrus (DG) is the first stage of the hippocampal trisynaptic circuit, receiving perforant path input from the entorhinal cortex. Granule cells send mossy fibre projections to CA3. The DG performs pattern separation -- transforming similar input patterns into distinct output patterns -- preventing interference between similar memories. Adult neurogenesis in the DG contributes to pattern separation. DG granule cells are highly excitable and their integration is gated by inhibitory interneurons and mossy cells."),
    ("What is the cornu ammonis (CA) regions?", "CA3 receives perforant path and mossy fibre (DG) input and has extensive recurrent collaterals (Schaffer collaterals to CA1, recurrent to other CA3 neurons). CA3 recurrent connections support autoassociative memory (pattern completion -- retrieving the whole memory from partial cues, like the brain's 'auto-fill'). CA1 receives CA3 and direct EC input, integrates them, and provides the main hippocampal output. The DG-CA3-CA1 gradient of processing implements pattern separation then pattern completion."),
    ("What is myelin and its composition?", "Myelin is a multilamellar lipid-rich sheath formed by Schwann cells (PNS) or oligodendrocytes (CNS) wrapping around axons. It is 70-80% lipid (cholesterol, galactolipids including galactocerebroside and sulphatide, sphingomyelin) and 20-30% protein (MBP, PLP/DM20 in CNS; P0, PMP22 in PNS). Myelin functions as electrical insulation, increasing membrane resistance and decreasing capacitance to allow saltatory conduction. Compact myelin is periodically interrupted by cytoplasmic incisures (Schmidt-Lanterman) and paranodal regions."),
    ("What is the role of reactive astrocytes in injury?", "Following CNS injury or disease, astrocytes undergo reactive astrogliosis: morphological changes (hypertrophy, increased GFAP expression), proliferation, upregulation of cytokines and chemokines, and formation of a glial scar (with chondroitin sulphate proteoglycans -- CSPG -- that inhibit axon regeneration). Reactive astrocytes are heterogeneous: A1 subtypes (inflammatory, neurotoxic) are induced by microglia-derived signals; A2 subtypes (neuroprotective) are induced by ischaemia. Therapeutic strategies target CSPG degradation (chondroitinase ABC) to promote axon regeneration."),
    ("What is the role of NMDA receptors in learning?", "NMDA receptors (NMDARs) are the molecular coincidence detectors for Hebbian plasticity. They require simultaneous presynaptic glutamate release AND postsynaptic depolarisation (to remove the Mg2+ block) to open -- making them perfect detectors of correlated pre- and postsynaptic activity. Ca2+ influx through NMDARs activates CaMKII, triggering AMPA receptor phosphorylation, AMPA receptor insertion, and spine enlargement -- the structural basis of LTP. NMDAR antagonists (AP5, ketamine) block LTP and impair learning."),
    ("What is CaMKII?", "Calcium-calmodulin kinase II (CaMKII) is a key signalling molecule in synaptic plasticity. Ca2+ influx through NMDA receptors activates calmodulin, which activates CaMKII. CaMKII autophosphorylates (Thr286), becoming constitutively active even after Ca2+ falls -- acting as a biochemical memory switch. Activated CaMKII phosphorylates GluA1 (AMPA receptor) at Ser831, increasing channel conductance, and facilitates AMPA receptor insertion at the synapse. CaMKII inhibition blocks LTP and spatial learning."),
    ("What is synaptic tagging in neuroscience?", "Synaptic tagging and capture (Frey and Morris, 1997): weak stimulation sets a synaptic tag at the activated synapse. Protein synthesis-dependent late LTP, induced at another synapse or even another time, provides plasticity-related proteins (PRPs -- BDNF, Arc, CPEB) that are captured at tagged synapses, enabling late LTP there too. This explains how strong experiences (providing proteins) can strengthen weakly activated synapses -- suggesting a mechanism for integrating multiple experiences into stable memory."),
    ("What is the role of AMPA receptors in plasticity?", "AMPA receptors (AMPARs) are the primary mediators of fast excitatory transmission. GluA1-4 subunit combinations determine properties: GluA1-containing receptors are Ca2+-impermeable when combined with GluA2; GluA2-lacking receptors (in early LTP, addiction) are Ca2+-permeable and contribute additional plasticity signals. LTP involves CaMKII-mediated phosphorylation (GluA1-Ser831) and insertion of GluA1-containing AMPARs from perisynaptic regions into the PSD. LTD involves AMPAR endocytosis via phosphatase activation."),
    ("What is the postsynaptic density?", "The postsynaptic density (PSD) is a specialised protein scaffold at the cytoplasmic face of the postsynaptic membrane, containing: glutamate receptors (AMPAR, NMDAR); scaffold proteins (PSD-95 -- anchors NMDARs; Shank, Homer, GKAP -- structural scaffold); signalling molecules (CaMKII, Ras, MAP kinases); and cytoskeletal elements (actin). PSD-95 links NMDARs to intracellular signalling complexes. Mutations in PSD-95-interacting proteins (Shank3, SYNGAP1) cause autism and intellectual disability."),
    ("What is the role of the cerebellum in speech?", "The cerebellum coordinates the precise timing and sequencing of articulatory movements for fluent speech. Cerebellar lesions cause dysarthria -- irregular, scanning speech with imprecise articulation. The cerebellum also contributes to procedural learning in language, grammatical prediction, and inner speech. Cerebellar-PFC connectivity is disrupted in schizophrenia (cognitive dysmetria theory -- Andreasen). Cerebellar rTMS is being studied for stuttering and aphasia rehabilitation."),
    ("What is acetylcholinesterase?", "Acetylcholinesterase (AChE) rapidly degrades acetylcholine in the synaptic cleft, terminating cholinergic transmission. It is one of the fastest enzymes known (~10^4 molecules/second). AChE inhibitors (organophosphate nerve agents -- sarin, VX; insecticides -- malathion) cause SLUDE syndrome (Salivation, Lacrimation, Urination, Defecation, Emesis) from excess ACh. Therapeutic AChE inhibitors (donepezil, rivastigmine, galantamine) modestly slow cognitive decline in Alzheimer's disease by prolonging ACh action in the basal forebrain-cortex pathway."),
    ("What is glutamate excitotoxicity and treatment?", "Excitotoxicity involves NMDA receptor-mediated Ca2+ overload triggering mitochondrial dysfunction, activation of caspases, calpains, and nNOS, generating reactive oxygen species and culminating in necrosis or apoptosis. Neuroprotective strategies targeting excitotoxicity (NMDA antagonists, Ca2+ channel blockers, anti-oxidants) have largely failed in clinical trials despite efficacy in preclinical models -- partly due to the narrow therapeutic window and adverse effects of NMDA blockade. Memantine (low-affinity NMDA antagonist) is approved for moderate-severe Alzheimer's."),
    ("What is the neural basis of placebo analgesia?", "Placebo analgesia is mediated by endogenous opioid release (blocked by naloxone) and descending pain modulation from the PAG-RVM pathway. Expectation activates the PFC and ACC, which drive PAG activation and endogenous opioid release in the spinal cord dorsal horn. The cingulo-opercular network and vmPFC are involved in the psychological component of placebo response. Brain imaging predicts individual placebo responsiveness -- a potential precision medicine biomarker for pain treatment."),
    ("What is the anterior cingulate cortex and pain?", "The ACC (midcingulate cortex, cingulate zone 4) mediates the affective-motivational dimension of pain -- the suffering and unpleasantness -- distinct from S1's sensory-discriminative dimension. Anterior cingulotomy (lesioning the ACC) reduces pain suffering without affecting sensory detection. The ACC activates during empathy for others' pain, social rejection, and moral distress -- suggesting it encodes the aversiveness of any 'social pain' or threat-relevant stimulus."),
    ("What is the functional anatomy of the frontal lobe?", "The frontal lobe is divided: primary motor cortex (M1, precentral gyrus -- voluntary movement); premotor cortex (movement preparation, mirror neurons); supplementary motor area (self-initiated sequences); prefrontal cortex -- dlPFC (working memory, executive control), vlPFC (response inhibition, Broca's area), OFC (reward valuation, decision-making), ACC (conflict monitoring, error detection, pain affect), and vmPFC (emotional regulation, somatic markers, social value). Frontal lobe damage causes disinhibition, poor planning, perseveration, and personality change."),
    ("What is the role of astrocytes in metabolic support?", "Astrocytes provide metabolic support to neurons via the astrocyte-neuron lactate shuttle (ANLS -- Magistretti and Pellerin): astrocytes take up glucose, convert it to lactate (via glycolysis), and transfer lactate to neurons via MCT1/4 and MCT2 transporters, where it is oxidised for energy. Astrocytes also store glycogen (the only brain glycogen store) and mobilise it during hypoglycaemia or high demand. Glutamate uptake by astrocytes triggers increased glycolysis and lactate production, coupling local activity to energy supply."),
    ("What is the substantia innominata and basal forebrain?", "The basal forebrain (substantia innominata, nucleus basalis of Meynert, medial septum, and diagonal band of Broca) contains large cholinergic neurons projecting to the entire neocortex and hippocampus. Cholinergic tone from the basal forebrain modulates attention, memory encoding (especially the hippocampal theta rhythm), and cortical arousal. Basal forebrain cholinergic neurodegeneration occurs early and severely in Alzheimer's disease and contributes to memory and attentional deficits."),
    ("What is neuroinflammation and depression?", "Inflammatory hypotheses of depression: elevated circulating cytokines (IL-6, TNF-alpha, CRP) are found in 30-40% of depressed patients. Cytokines cross the BBB (via circumventricular organs and active transport), activate microglia, reduce serotonin availability (IDO enzyme degrades tryptophan toward kynurenine rather than serotonin), and reduce BDNF. Inflammatory subtypes of depression may respond to anti-inflammatory treatments (celecoxib, infliximab -- effective in patients with elevated CRP). Exercise reduces neuroinflammation and increases BDNF."),
    ("What is the trigeminal nerve?", "The trigeminal nerve (CN V) is the largest cranial nerve and the primary afferent for facial sensation and motor control of mastication. Three divisions: ophthalmic (V1 -- forehead, eye, nose), maxillary (V2 -- midface, upper teeth), mandibular (V3 -- jaw, lower teeth, anterior ear). Trigeminal neuralgia (severe lancinating facial pain from V2/V3 compression by blood vessels) is treated with carbamazepine (Na+ channel blockade), microvascular decompression, or stereotactic radiosurgery."),
    ("What is the facial nerve (CN VII)?", "The facial nerve (CN VII) has multiple components: motor (innervates all muscles of facial expression -- upper face has bilateral cortical supply, so unilateral UMN lesion spares forehead; LMN lesion affects entire ipsilateral face -- Bell's palsy); parasympathetic (lacrimal, submandibular, sublingual glands); special sensory (taste, anterior 2/3 tongue via chorda tympani); and general sensory (external ear). Bell's palsy (idiopathic LMN facial palsy -- likely HSV-1 reactivation) is treated with prednisolone within 72 hours."),
    ("What is the vestibulo-ocular reflex?", "The vestibulo-ocular reflex (VOR) stabilises gaze during head movement by driving eye movements of equal amplitude and opposite direction to head rotation. The three-neuron arc: vestibular hair cells -> vestibular nuclei -> extraocular muscle motor neurons. The VOR has a gain of ~1 (eye velocity equals head velocity) and operates at latencies of ~10 ms -- far faster than visual feedback. Caloric testing and head impulse test assess VOR integrity; defective VOR is a hallmark of peripheral and central vestibular disorders."),
    ("What is the role of perineuronal nets?", "Perineuronal nets (PNNs) are specialised extracellular matrix structures surrounding the cell body and proximal dendrites of specific neurons (particularly parvalbumin-positive interneurons). PNNs are composed of chondroitin sulphate proteoglycans (aggrecans, brevican), tenascins, and hyaluronan. PNN formation closes critical periods (preventing experience-dependent plasticity). Digesting PNNs with chondroitinase reopens plasticity windows, potentially enabling learning of new skills in adults and recovery from amblyopia."),
    ("What is a critical period in neuroscience?", "Critical periods are developmental windows during which the brain is maximally sensitive to environmental input for shaping neural circuit organisation. The visual cortex critical period (Hubel and Wiesel) is a canonical example: monocular deprivation during the critical period (amblyopia) shifts cortical ocular dominance toward the open eye, causing lasting visual impairment. Critical periods are opened by GABA-ergic maturation and closed by PNN formation and myelination."),
    ("What is binocular rivalry?", "When different images are presented to the two eyes simultaneously, perception alternates between the two images (binocular rivalry) rather than fusing them. It is a tool for studying perceptual awareness: during rivalry, only the dominant percept corresponds to increased neural firing in early visual cortex and decreased suppression. High-level areas (temporal cortex) may switch with perception even when low-level areas do not. Rivalry has been used to probe the neural correlates of consciousness by dissociating physical stimulation from conscious perception."),
    ("What is the phi phenomenon?", "The phi phenomenon (Wertheimer, 1912) is the perception of movement when two stationary stimuli are presented in rapid succession -- the basis of cinema. It demonstrates that motion perception is a constructive inference, not a direct sensory report. The apparent motion system involves V5/MT (motion area), which responds to apparent motion similarly to real motion. Phi is distinct from the beta movement (perception of a single object moving) and the wagon wheel illusion (illusory reversal under stroboscopic conditions)."),
    ("What is neural correlates of decision confidence?", "Decision confidence is encoded by neurons in the orbitofrontal cortex, anterior cingulate cortex, and prefrontal cortex. During perceptual decisions, confidence tracks the strength of evidence (reaction time, firing rate of evidence-accumulating neurons in LIP). Metamemory (confidence in memory accuracy) involves ventromedial PFC and hippocampal-PFC connectivity. Calibration of confidence is important for medical diagnosis, learning, and risk estimation. Overconfidence (common in novices) and underconfidence (common in experts) have distinct neural signatures."),
    ("What is the neuroscience of morality -- trolley problem?", "The trolley problem probes utilitarian vs deontological moral reasoning. The footbridge dilemma (push a large man off a bridge to save 5) activates the vmPFC, amygdala, and medial PFC (emotional, deontological -- most refuse) more than the switch dilemma (pull a lever to divert a trolley). Patients with vmPFC lesions show elevated utilitarian responses (more willing to push the man). Dual process account: System 1 (emotional, deontological) conflicts with System 2 (utilitarian calculation), with the vmPFC mediating the outcome."),
    ("What is tDCS and cognitive enhancement?", "Anodal tDCS over the dlPFC modestly improves working memory performance in healthy subjects and patients with schizophrenia. Effects are subtle (tenths of a standard deviation), highly variable across individuals, electrode placement-sensitive, and not reliably transferred to other cognitive domains. The mechanism involves membrane potential depolarisation increasing neuronal excitability (not generating action potentials). Commercial 'brain stimulators' for home use raise safety and efficacy concerns -- the field requires rigorous validation."),
    ("What is the neural basis of musical processing?", "Music engages a distributed network: auditory cortex (pitch, melody, rhythm); motor areas (beat perception, synchronisation); limbic system (emotional response -- anticipation and resolution of musical tension activates nucleus accumbens); cerebellum (timing); and language areas (lyrics). Absolute pitch involves enhanced left posterior superior temporal gyrus organisation. Music training expands motor, auditory, and somatosensory cortical representations. Congenital amusia (tone deafness) affects the right frontal-auditory connectivity."),
    ("What is the neural basis of mathematics?", "Mathematical cognition involves: the intraparietal sulcus (IPS -- numerical magnitude and arithmetic); the angular gyrus (retrieval of arithmetic facts from memory -- activated during multiplication; disrupted in dyscalculia); the prefrontal cortex (working memory, executive control in complex calculation); and the dorsal visual stream (spatial numerical cognition, number line representation). Dyscalculia is associated with IPS hypoactivation and structural differences. Arithmetic fact retrieval is disrupted by left angular gyrus lesions (Gerstmann syndrome -- agraphia, acalculia, finger agnosia, left-right confusion)."),
    ("What is the neural basis of creativity and insight?", "Insight solutions ('aha moments') are associated with sudden gamma-band (40 Hz) activity over the right anterior temporal lobe (ATL) ~300 ms before the solution is verbally reported, followed by alpha suppression. The right ATL is thought to integrate distantly related semantic associations -- enabling the remote association characteristic of insight. Increased hippocampal and posterior cingulate activity precedes insight solutions, suggesting memory retrieval and DMN involvement. EEG studies show a predictive pattern of alpha oscillations in the right temporal region that predicts who will solve a problem with insight."),
    ("What is adult stem cell therapy in neuroscience?", "Neural stem cell (NSC) therapy aims to replace lost neurons or provide trophic support in neurodegenerative diseases. Sources: ESCs, iPSCs (from patient skin cells -- avoiding immune rejection), and foetal NSCs. Challenges: directing differentiation into the correct neuron type, ensuring long-term survival and integration, avoiding tumour formation, and achieving functional connectivity. Dopaminergic neuron transplants (from foetal midbrain or iPSCs) have shown some efficacy in Parkinson's disease clinical trials. Gene therapy combined with cell transplantation may improve outcomes."),
    ("What is the neuroscience of mindfulness meditation?", "Regular mindfulness practice produces structural and functional brain changes: increased cortical thickness in the insula and sensory cortex (Lazar et al.); reduced amygdala grey matter volume and reactivity to stress (Holzel et al.); increased prefrontal regulation of the amygdala; and altered default mode network dynamics (reduced self-referential rumination, increased metacognitive awareness). MBSR reduces cortisol, inflammatory markers, and relapse of major depression (MBCT halves recurrence risk in three-episode depression)."),
    ("What is the functional role of sleep oscillations?", "Sleep oscillations serve memory consolidation: cortical slow oscillations (0.5-1 Hz) coordinate hippocampal sharp-wave ripples (80-140 Hz) and thalamic sleep spindles (12-15 Hz) in a coupled sequence. Slow oscillation upstates drive spindles, which drive ripples, creating a temporal hierarchy for transferring hippocampal memory traces to the neocortex. Stimulating slow oscillations at their endogenous frequency during sleep (tSO -- transcranial slow oscillation stimulation) enhances declarative memory consolidation."),
    ("What is dopamine in reward prediction error -- clinical implications?", "Dopamine RPE signals in the VTA and substantia nigra encode: unexpected reward (phasic increase -- excitatory); expected reward (no change); and expected reward omission (phasic decrease -- inhibitory). This signal drives associative learning (reinforcement learning) throughout the brain. In Parkinson's disease, dopamine loss impairs reward learning and motivation. In addiction, drugs of abuse hijack this system (cocaine blocks DAT; opioids disinhibit VTA dopamine neurons), causing supraphysiological dopamine bursts that overwhelm normal learning signals and progressively narrow behaviour toward drug-seeking."),
]

existing = sum(1 for _ in OUT.open()) if OUT.exists() else 0
print(f"Existing: {existing} pairs")

with OUT.open("a") as f:
    for q, a in extra:
        f.write(json.dumps({"messages": [
            {"role": "user", "content": q},
            {"role": "assistant", "content": a}
        ]}) + "\n")

total = sum(1 for _ in OUT.open())
print(f"Total: {total} pairs in upgrade_l.jsonl")
assert total >= 200, f"Only {total} -- need 200"
print("PASS: 200+ premium neuroscience pairs ready.")
