#!/usr/bin/env python3
"""gen_f_fill33.py -- final 48 pairs to reach 1004 total"""
import json, pathlib

OUT = pathlib.Path('/workspace/data_upgrades/upgrade_f.jsonl')
OUT.parent.mkdir(parents=True, exist_ok=True)

pairs = []
def p(q, a):
    pairs.append((q, a))

p("What is a red team engagement lifecycle?",
  "Red team engagement lifecycle: structured phases from planning to report; simulate sophisticated adversary; test people, process, and technology. Phase 1 -- Planning: scope agreement: what is in scope (systems, techniques, social engineering, physical?), out of scope (production databases, specific critical systems), geography, time window; rules of engagement: what deconfliction process if blue team detects? What happens if real incident during engagement? Who is the white team (knows about engagement; mediates)? Abort criteria (if tester becomes aware of real attacker); goals: specific objectives (reach domain admin, access finance data, plant persistence on CEO laptop); objectives drive all decisions; get-out-of-jail letter: authorisation document; carry at all times during physical. Phase 2 -- Reconnaissance: OSINT on target organisation; identify: technology stack, email format, key personnel, third-party vendors, physical locations, partner organisations, public IP ranges; infrastructure setup: attacker infrastructure (C2, phishing domain, VPS); configure to look legitimate; operational security: use operational accounts not traceable to testing firm. Phase 3 -- Initial Access: phishing campaign (if in scope): spear phish key personnel; pretexting calls (vishing); watering hole (compromise site target employees visit); public exploit (if internet-facing vulnerable service found); physical (if in scope): tailgating, badge cloning, evil USB drop; goal: initial foothold on single endpoint. Phase 4 -- Foothold and Persistence: install C2 implant; establish persistence (if objective includes persistence); maintain access stealthily; avoid detection by EDR and blue team. Phase 5 -- Internal Reconnaissance: network discovery: subnets, services, domain topology; Active Directory enumeration: BloodHound; trust relationships; high-value targets identified. Phase 6 -- Privilege Escalation and Lateral Movement: escalate from user to local admin to domain admin; lateral movement to targets; chain multiple lower-severity vulnerabilities; follow attack paths toward objectives. Phase 7 -- Objective Completion: demonstrate objective completion (screenshot with evidence); extract data (simulated, not real PII); plant persistence (if objective); stage full attack path documentation. Phase 8 -- Debrief and Reporting: deconfliction: reveal engagement to blue team; review: did blue team detect? What was missed? Technical report: full attack narrative; findings; IoCs generated during engagement; recommendations; executive report: business impact; Purple team debrief: red team walks blue team through each technique; blue team implements detection; retesting detection rules.")

p("What is the OWASP API Security Top 10?",
  "OWASP API Security Top 10 (2023): most critical API security risks; specific to API context. API1:2023 -- Broken Object Level Authorization (BOLA): API endpoint receives object ID in request; does not verify requestor owns object; access other users objects by changing ID; most common and impactful API vulnerability; test: enumerate all resource IDs; test with different user credentials; API2:2023 -- Broken Authentication: weak authentication mechanisms; missing authentication on sensitive endpoints; improper token handling; JWT weaknesses; brute force on auth endpoints. API3:2023 -- Broken Object Property Level Authorization: API returns more properties than needed (excessive data exposure); or allows client to change properties they should not (mass assignment); test: inspect all API responses for sensitive fields not needed by frontend; test sending extra fields in write requests. API4:2023 -- Unrestricted Resource Consumption: no rate limiting; no request size limits; no timeout; resource exhaustion through API; DoS via expensive operations; test: send many requests; send large request bodies; test expensive operations at high volume. API5:2023 -- Broken Function Level Authorization (BFLA): users accessing admin-level functions; horizontal: regular user accessing another user management functions; vertical: regular user calling admin endpoints; test: map all endpoints; test each with lower-privilege credentials. API6:2023 -- Unrestricted Access to Sensitive Business Flows: allow automation of business flows that should be limited; ticket scalping, credential stuffing, account takeover at scale; business logic without bot detection; test: automate legitimate flows; verify rate limiting and bot detection prevent abuse. API7:2023 -- Server Side Request Forgery (SSRF): API accepts URL and fetches it server-side; attacker provides internal URL (metadata service, internal APIs); test: provide 127.0.0.1, 169.254.169.254, internal hostnames in URL parameters. API8:2023 -- Security Misconfiguration: default credentials, unnecessary HTTP methods enabled, verbose error messages, CORS misconfigured (allow all origins), missing security headers, debug mode in production; test: OPTIONS request to see allowed methods; check CORS headers; check error responses. API9:2023 -- Improper Inventory Management: undocumented API versions still active (v1 retired but accessible); shadow APIs (undocumented endpoints); test: enumerate /api/v1, /api/v2, /api/v3, /api/latest, /api/beta; check Wayback Machine for old API docs. API10:2023 -- Unsafe Consumption of APIs: application consumes third-party API without validation; trusts all data from third party; injection via third-party API response; if third-party API compromised: attacker influences application; test: if application consumes external APIs: what happens if malicious data returned?")

p("What is Shodan and how do security professionals use it?",
  "Shodan: search engine for internet-connected devices; indexes banners and metadata from open ports; used by security professionals and attackers. What Shodan indexes: TCP/UDP banners: responses from open ports (HTTP headers, SSH banners, FTP banners, telnet, Modbus, SCADA protocols); screenshots: VNC, RDP, webcam images; TLS certificates: domain names from Subject Alternative Names; metadata: device type, OS, software, version, location. Shodan use cases for defenders: asset discovery: search for your own IP ranges; find exposed services you did not know about; search: net:192.168.0.0/16 (not useful for public Shodan; use for your public ranges); brand monitoring: search domain name; find subdomains you may have forgotten; find credentials in banners; vulnerability management: search for vulnerable software versions: product:Apache httpd version:2.4.49 (Log4j-affected); find Citrix, Exchange, VPN vulnerabilities before attackers; third-party risk: search partner company IP ranges; assess their exposure; ICS/SCADA discovery: Shodan prominently indexes industrial systems; Modbus devices, Siemens S7, SCADA HMIs; critical infrastructure exposure; incident response: during incident: search C2 IP in Shodan; understand what services attacker hosts; C2 infrastructure research. Shodan search filters: port: (port:22 ssh); country: (country:US); hostname: (hostname:example.com); net: (net:1.2.3.0/24); product: (product:nginx); version: (version:1.18.0); org: (org:Microsoft Corporation); before:/after: (date filters); os: (os:Windows). Shodan CLI: pip install shodan; shodan init API_KEY; shodan search port:22 product:OpenSSH; shodan host 1.2.3.4; shodan scan submit 1.2.3.0/24 (initiate scan of your own network -- requires credits). Defensive actions from Shodan: close unnecessary ports (if Shodan finds open management port: close it); update software (if Shodan reveals old version: patch); remove sensitive banners (SSH version banners reveal OS and software version); Shodan alerts: set up alerts on your IPs/domains; notify when new exposed service found; Shodan Monitor: continuous monitoring of your network assets; alert on changes. Exposure reduction: principle of minimum exposure: only expose services that must be public; VPN for management access; firewall rules: restrict by source IP; remove default banners; ensure no credentials in HTTP responses or banners.")

p("What is identity governance and administration (IGA)?",
  "IGA (Identity Governance and Administration): manage user lifecycle, access rights, and access certifications; ensure right people have right access; compliance and audit support. IGA vs IAM: IAM: authentication and authorisation (who can access what); IGA: governance layer over IAM (should they have access? Is access appropriate? Review and certify access); IGA answers: who has access to what and why? Is this access appropriate? Has access been certified recently? IGA functions: user lifecycle management: joiner (new employee): provision accounts and access based on role; mover (role change): add new access, remove old; leaver (termination): deprovision all access immediately; RBAC (Role-Based Access Control): define roles (Sales Representative, Finance Analyst); associate access entitlements with roles; assign users to roles; access request workflow: employee requests additional access; manager approval; system owner approval; access granted and logged; access certifications (recertification): periodic review of who has access; manager reviews team access; system owner reviews all users; certify or revoke; frequency: quarterly for privileged access, annual for standard; Segregation of Duties (SoD): prevent one person from having conflicting access (approver + initiator of payments); SoD policy: define conflicting access pairs; alert or block when user has both; audit reporting: who has access to system X; when was access granted; last certification date; is user still active. Products: SailPoint IdentityIQ (on-premise) and IdentityNow (SaaS): market leaders; Saviynt: strong cloud IGA; Oracle Identity Governance; Microsoft Entra ID Governance: access reviews, entitlement management, Privileged Identity Management; IBM Security Identity Manager; Omada Identity; small-medium: JumpCloud, OneLogin (Okta alternative). Integration: HR system integration (Workday, SAP SuccessFactors, BambooHR): authoritative source for employee data; joiner/mover/leaver events trigger IGA workflows; Active Directory integration: IGA manages AD group membership; ITSM integration (ServiceNow): IGA creates tickets; approval workflows through ITSM; privileged access: integration with PAM solution; IGA manages entitlement to PAM; PAM manages actual privileged credential. Compliance value: SOX: access review evidence; segregation of duties enforcement; HIPAA: access to PHI systems controlled and certified; PCI DSS: quarterly access reviews; ISO 27001: access control lifecycle; audit trail: all access grants, reviews, revocations logged with approver and date.")

p("What is network forensics?",
  "Network forensics: capture, preserve, and analyse network traffic to investigate security incidents; reconstruct attacker activities from network evidence. Evidence sources: full packet capture (PCAP): complete network traffic; most comprehensive; storage intensive; network tap or SPAN port; retrospective analysis after incident; netflow/IPFIX: connection-level metadata without payload; src IP, dst IP, port, protocol, bytes, duration; storage efficient; analysis without decryption; DNS logs: queries and responses; reveal C2 domains, data exfiltration via DNS; Zeek (Bro) logs: structured logs from traffic analysis (conn.log, http.log, ssl.log, dns.log, files.log, weird.log); proxy logs: web proxy (Squid, Bluecoat, Zscaler); URL, user agent, bytes, response code; email logs: SMTP logs, mail gateway; firewall/NAT logs: connection attempts, blocked traffic; endpoint network data: EDR network telemetry; process-to-network connection mapping. Tools: Wireshark: GUI PCAP analysis; display filters, protocol dissection, TCP stream reassembly, file extraction; tshark: command-line Wireshark; scripting; large PCAP analysis; tcpdump: capture and filter; Zeek: traffic analysis and log generation from PCAP; NetworkMiner: passive network sniffer; OS and session reconstruction; file extraction; Moloch/Arkime: large-scale PCAP storage and search; elasticsearch backend; Suricata: IDS + network monitoring; signature-based detection on network. Incident investigation workflow: acquire evidence: capture network traffic at time of incident (if real-time); retrieve stored PCAP/netflow from SIEM or network monitoring; identify suspicious activity: correlate with endpoint alerts; find malware C2 communication; identify data exfiltration; timeline reconstruction: first connection from attacker IP; subsequent lateral movement; data access; exfiltration; evidence extraction: extract files from HTTP traffic (malware downloads); decode encoded traffic; document C2 infrastructure. Specific analysis tasks: C2 identification: periodic beaconing (regular interval network connection); identify: Packet timing analysis (consistent intervals), destination (rare/new domain), User-Agent anomalies, encrypted but small regular traffic (Cobalt Strike default 60-second beacon); data exfiltration: large outbound transfers; unusual destination; unusual protocol (DNS tunneling: many small DNS queries); HTTP POST to unusual destination; email exfiltration; lateral movement: SMB connections between workstations (not normal in environment); RDP from non-admin systems; WMI/DCOM traffic to multiple hosts; account credential pass from one host to another (new logon events correlated with network connections). DFIR integration: network forensics corroborates endpoint forensics; endpoint shows process X executed; network shows process X made connection to IP Y at time Z; complete picture of attack chain.")

p("What is secure remote access and VPN security?",
  "Secure remote access: allow employees to access corporate resources from outside office; VPN, ZTNA, and secure access service edge (SASE). VPN types: site-to-site VPN: connect two office networks over internet; permanent tunnel; not user VPN; remote access VPN: individual user connects to corporate network; user experience: as if on corporate network; splits into: full tunnel (all traffic through VPN), split tunnel (only corporate traffic through VPN; internet direct). VPN protocols: IPSec: encryption and authentication at IP layer; tunnel mode: entire IP packet encrypted; transport mode: payload only; IKEv2: fast reconnect; mobile friendly; OpenVPN: open-source; TLS-based; flexible; port 1194 UDP or TCP 443; WireGuard: modern; fast; simple; cryptographically strong; growing adoption; SSL/TLS VPN: uses HTTPS (port 443); web browser or thin client; Cisco AnyConnect, Pulse Secure, GlobalProtect. VPN security vulnerabilities: credential attacks: VPN exposed to internet; brute force without rate limiting; credential stuffing; MFA bypass; CVE-based: critical vulnerabilities in VPN appliances: Pulse Secure, Fortinet, Citrix ADC, Cisco AnyConnect; nation-state exploitation of VPN vulnerabilities; example: Fortinet CVE-2022-40684 (authentication bypass); Pulse Connect Secure CVE-2021-22893; over-privileged VPN access: VPN gives access to everything; attacker with stolen credentials accesses all resources; split tunneling misconfiguration: user manipulates routing to redirect traffic. VPN hardening: MFA on VPN: all VPN connections require MFA (Duo, RSA SecurID, TOTP); hardware token strongest; patch VPN appliance: VPN CVEs actively exploited; highest priority patching; network segmentation post-VPN: VPN lands in restricted zone; lateral movement requires additional authentication; not direct access to all internal resources; logging: log all VPN connections (user, IP, time, duration); alert: new user, unusual time, new geography, concurrent sessions from different geos; certificate authentication: mutual TLS; client certificate + user credentials; split tunneling control: force DNS through VPN (prevent DNS leakage); internet traffic direct or controlled; rate limiting: limit login attempts; IP-based rate limiting; ZTNA (Zero Trust Network Access) replacing VPN: per-application access: user accesses specific application; not entire network segment; continuous verification: session reassessed continuously; context-aware: user + device + location + application; BeyondCorp model (Google); products: Zscaler Private Access, Cloudflare Access, Palo Alto Prisma Access, Cisco Duo Network Gateway.")

p("What is physical penetration testing?",
  "Physical penetration testing: assess physical security controls; attempt unauthorised physical access; complement to network and application pentesting. Why physical testing: physical access = game over; access to server room allows: direct device access, installing hardware implant, stealing drives, rebooting into live OS; social engineering via physical presence most effective attack vector; many organisations underinvest in physical security. Scope: define precisely what is in scope: which offices, what activities (tailgating, pretexting, break-in simulation?), what cannot be done (no actual locks broken, no violence, no damage); authorisation letter: carry at all times; contact for white team (person who can confirm legitimacy to security if detained). Techniques: tailgating / piggybacking: follow authorised person through secured door; hold door open appeal: most employees uncomfortable challenging; RFID cloning: Proxmark3 or Flipper Zero: clone building access RFID badge within RF range; if RFID uses older EM4100/HID Prox 125kHz (no crypto): trivially cloned; HID iCLASS, MIFARE DESFire: more secure; social engineering: pretexting: pose as IT support, HVAC technician, delivery person, fire inspector; create pretext calling ahead; uniform: matching uniforms dramatically increase access success; badge cloning + uniform: high-success combination; dumpster diving: find sensitive documents; old hard drives; credentials on paper; lock picking: pick-resistant (security pin sets): Medeco, Abloy Protec (high security); most corporate locks: standard pin tumbler; pick with standard picks or bump key; shimming: padlocks shimmed with thin metal; not all padlocks secure; dropping devices: USB drives with payloads (O.MG cable, rubber ducky); left in car park, reception area, bathroom; employee curiosity leads to plug-in. Findings: unlocked server rooms: anyone can walk in; weak RFID (125kHz cards): cloneable at distance; no visitor management: visitors not escorted; tailgating: no challenge culture; no anti-tailgating (mantrap); dumpster with sensitive documents; unattended workstations: not locked; screen visible to visitors; network drops accessible in public areas: plug in and access internal network. Remediation: anti-tailgating: culture (challenge policy), mantrap (airlock), turnstiles; RFID upgrade: replace 125kHz with encrypted credentials (HID iCLASS SE, MIFARE DESFire); document shredding: all documents; locked bins before disposal; visitor management: escorts; visitor badges that look different; clean desk policy: no sensitive documents visible; lock workstations (Win+L on leave); network port security (802.1X); CCTV coverage and monitoring.")

p("What is server-side template injection (SSTI)?",
  "Server-Side Template Injection (SSTI): inject malicious template directives; execute code in template engine context; often leads to Remote Code Execution (RCE). How template engines work: Jinja2 (Python), Twig (PHP), Freemarker (Java), Velocity (Java), Handlebars (JS), ERB (Ruby), Smarty (PHP); server uses template engine to render dynamic pages; template: Hello {{name}} where name from user input; rendered: Hello Alice. SSTI attack: if user input included unsanitised in template expression: input: {{7*7}} (Jinja2 expression); rendered: 49 (template evaluated the expression); confirms SSTI; detection: try: {{7*7}}, ${7*7}, #{7*7}, <%=7*7%>, [7*7]; if output contains 49 (or result of arithmetic): template injection; payloads are engine-specific. Engine-specific exploitation: Jinja2 (Python): {{config}} (reveal Flask config; may contain SECRET_KEY); {{''.__class__.__mro__[1].__subclasses__()}} (access Python subclasses); RCE: {{''.__class__.__mro__[1].__subclasses__()[396](command, shell=True, stdout=-1).communicate()[0].strip()}} (find subprocess.Popen at correct index); Twig (PHP): {{7*7}} = 49; {{_self.env.registerUndefinedFilterCallback(exec)}} {{_self.env.getFilter(id)}} (execute system command); Freemarker (Java): <#assign ex=objectinstantiation(Class.forName(freemarker.template.utility.Execute))>${ex(command)}; Velocity (Java): #set($x=$class.inspect(java.lang.Runtime.class).type.getRuntime())$x.exec(whoami). Wfuzz/tplmap detection: tplmap (tplmap.py): automates SSTI detection and exploitation; supports many template engines; tests payloads; exploitation payloads. Prevention: never concatenate user input into template strings: vulnerable: template = Template(Hello + user_input); safe: template = Template(Hello {{name}}); pass user data as template variable not part of template; do not use string formatting to build templates: vulnerable: template_string.format(user_data); safe: template engine escape user variables; sandboxed template execution: some template engines offer sandbox mode; limit available objects; restrict access to dangerous objects; input validation: if user input must affect template logic: strict validation; avoid template engines for user-controlled content (use different rendering approach); security testing: fuzz all input fields with template expressions: {{7*7}}, ${7*7}, #{7*7}; check if output contains 49.")

existing = sum(1 for _ in OUT.open()) if OUT.exists() else 0
print(f"Existing pairs: {existing}")
print(f"New pairs to add: {len(pairs)}")

with OUT.open("a") as f:
    for q, a in pairs:
        f.write(json.dumps({"messages": [
            {"role": "user", "content": q},
            {"role": "assistant", "content": a}
        ]}) + "\n")

total = sum(1 for _ in OUT.open())
print(f"Total upgrade_f pairs: {total}")
if total >= 1000:
    print("upgrade_f TARGET MET -- 1000+ pairs!")
else:
    print(f"Need {1000-total} more pairs")
