#!/usr/bin/env python3
"""Generate 200+ high-quality examples for V (History), W (Literature), X (Medicine),
Y (Environmental Science), Z (Ethics in Technology), AA (Artificial Intelligence)."""
import json
from pathlib import Path

DATA_DIR = Path('/workspace/data_upgrades')
DATA_DIR.mkdir(parents=True, exist_ok=True)

def write(upgrade, pairs):
    path = DATA_DIR / f"upgrade_{upgrade}.jsonl"
    with open(path, "w") as f:
        for q, a in pairs:
            f.write(json.dumps({"messages": [
                {"role": "user", "content": q},
                {"role": "assistant", "content": a}
            ]}, ensure_ascii=False) + "\n")
    print(f"upgrade_{upgrade}: wrote {len(pairs)} examples")

# ─────────────────────────────────────────────────────────────────────────────
# V — HISTORY (200 examples)
# ─────────────────────────────────────────────────────────────────────────────
HISTORY = [
    ("What caused World War I?",
     "World War I (1914-1918) arose from a complex interplay of long-term structural factors and the immediate catalyst of Archduke Franz Ferdinand's assassination. Long-term causes: (1) Alliance system: Europe was divided into two armed blocs — the Triple Entente (Britain, France, Russia) and the Triple Alliance (Germany, Austria-Hungary, Italy). These alliances transformed a local conflict into a general European war through treaty obligations. (2) Imperialism: European powers competed intensely for colonies and overseas markets, creating friction — the Morocco crises (1905, 1911) between Germany and France nearly caused war. (3) Militarism: all major powers had been expanding and modernising their militaries, developing war plans. The Schlieffen Plan committed Germany to a two-front war strategy. Military logic increasingly overrode diplomatic options once mobilisation began. (4) Nationalism: intense nationalist movements destabilised multi-ethnic empires (Austria-Hungary, Ottoman Empire). Pan-Slavism was backed by Russia; Pan-Germanism promoted German dominance. Serbian nationalism in the Balkans was particularly combustible — the 'Sick Man of Europe' (Ottoman decline) and Austro-Hungarian anxiety about Serbian expansion created the tinderbox. Immediate cause: Gavrilo Princip, a Bosnian Serb nationalist (connected to the 'Black Hand'), assassinated Austro-Hungarian Archduke Franz Ferdinand in Sarajevo on 28 June 1914. Austria-Hungary issued an ultimatum to Serbia; Serbia's partial acceptance was deemed insufficient. Austria declared war on Serbia. Russia mobilised in support of Serbia; Germany declared war on Russia; France's alliance obligated it to join; Germany invaded Belgium (per the Schlieffen Plan) → Britain declared war on Germany (treaty obligation to protect Belgian neutrality). Fischer controversy: historian Fritz Fischer (1961) argued Germany deliberately sought war for continental hegemony; this remains debated — most historians now emphasise shared responsibility."),

    ("What was the French Revolution and what were its causes and consequences?",
     "The French Revolution (1789-1799) was a radical political and societal transformation that abolished the absolute monarchy, established a republic, and reshaped France and ultimately the world through its ideals of liberté, égalité, fraternité. Causes: (1) Financial crisis: France was bankrupted by the American Revolutionary War, royal extravagance (Versailles), and inefficient taxation. The tax system fell disproportionately on the Third Estate (commoners, bourgeoisie) while nobility and clergy were exempt. (2) Social inequalities: the Ancien Régime's three estates were deeply unequal. The bourgeoisie (educated middle class) had grown wealthy but lacked political power. Enlightenment philosophy (Rousseau, Voltaire, Montesquieu) gave them intellectual tools to challenge legitimacy of privilege and absolute monarchy. (3) Immediate triggers: crop failures and bread shortages in 1788 caused widespread hunger; Louis XVI convened the Estates-General in May 1789 (first time since 1614). The Third Estate's demands were rejected → they declared themselves a National Assembly → Tennis Court Oath (they swore to give France a constitution). Storming of the Bastille (14 July 1789): the revolutionary moment — symbol of royal tyranny. Key events: Declaration of the Rights of Man and of the Citizen (August 1789); constitutional monarchy (1791); abolition of feudalism; execution of Louis XVI (January 1793); the Terror (1793-94) — Committee of Public Safety under Robespierre; approximately 17,000 officially executed; another 40,000 died in prison; Thermidorian Reaction (July 1794 — Robespierre guillotined); Directory (1795-99) — unstable; Napoleon Bonaparte's coup (18 Brumaire, November 1799). Consequences: end of feudal system in France; spread of revolutionary ideals across Europe; Napoleonic Wars transformed the European map; rise of nationalism; inspiration for subsequent revolutions (1830, 1848, Latin American independence)."),

    ("What was the Industrial Revolution and how did it change society?",
     "The Industrial Revolution was a period of fundamental transformation in manufacturing, agriculture, and transportation that began in Britain around 1760-1840 and spread globally over the following century. It marked the transition from agrarian, handicraft economies to economies dominated by machine manufacturing and factory production. Origins in Britain: abundant coal and iron ore; strong property rights and patent system; agricultural revolution (enclosures freed labour from land); growing empire providing raw materials and markets; navigable rivers and later canals enabling bulk transport; relatively high wages incentivising labour-saving machinery (Allen's thesis). Key innovations: Steam engine (James Watt, 1769): the pivotal technology — applied to pumping water from mines, then to factories and locomotives. Textile machinery: spinning jenny (Hargreaves), water frame (Arkwright), power loom (Cartwright) — transformed textiles from cottage industry to factory production. Iron and steel: puddling process (Cort), Bessemer converter (1856). Railways: Stephenson's Rocket (1829) — railways transformed transport speed and cost. Social changes: Urbanisation: population shifted from rural to urban areas — Manchester grew from 25,000 (1772) to 303,000 (1850). Factory system: replaced domestic and craft production; workers (including children) worked 12-16 hour days in dangerous conditions. Working class formation: the industrial proletariat — led to labour movements, trade unions, Chartism, and eventually socialism. Middle class expansion: factory owners, managers, professionals. Living standards debate: Optimists (McCloskey) argue rising real wages; Pessimists (Engels — The Condition of the Working Class in England, 1845) document appalling urban squalor. Pollution, child labour, and urban overcrowding were real costs. Long-run consequences: unprecedented sustained economic growth, improved living standards, rise of capitalist democracies, environmental degradation, global inequality between industrialised and non-industrialised nations."),

    ("What were the causes and consequences of World War II?",
     "World War II (1939-1945) was the deadliest conflict in human history — approximately 70-85 million deaths (3-4% of the 1940 world population), including approximately 6 million Jews murdered in the Holocaust and millions of other civilians. Causes: (1) The legacy of WWI and the Treaty of Versailles: the 'war guilt clause' (Article 231) placed sole blame on Germany, imposing harsh reparations (132 billion gold marks), massive territorial losses (Alsace-Lorraine, the Polish Corridor, overseas colonies), and military restrictions. German resentment and economic hardship created fertile ground for extremist nationalism. (2) The Great Depression (1929): mass unemployment (25% in the US, 30% in Germany) delegitimised democratic governments and led people to support radical alternatives. (3) Rise of fascism and Nazism: Hitler's NSDAP exploited resentment, antisemitism, and economic despair. Hitler became Chancellor January 1933. His foreign policy violated Versailles: rearmament (1935), Rhineland remilitarisation (1936), Anschluss with Austria (1938), Sudetenland annexation (Munich Agreement, 1938 — Chamberlain's appeasement), invasion of Czechoslovakia (1939). (4) Japan's imperial expansion in Asia (Manchuria 1931, China 1937) and Mussolini's Italy in Africa (Ethiopia 1935). (5) Non-aggression: the Molotov-Ribbentrop Pact (August 1939) between Nazi Germany and Soviet Union — guaranteed the Soviet Union would not intervene when Germany invaded Poland. Consequences: The Holocaust: Nazi genocide of 6 million Jews and 5-6 million others (Roma, disabled, Soviet POWs, homosexuals, political prisoners). Nuremberg Trials: established individual criminal responsibility under international law. UN established (1945). Cold War: the Soviet-American rivalry divided the world into ideological blocs for 45 years. Decolonisation: European empires weakened; independence movements across Asia and Africa. Marshall Plan: US $13 billion to rebuild Western Europe; NATO founded 1949."),

    ("What was the Cold War and how did it end?",
     "The Cold War (1947-1991) was a geopolitical, ideological, and military rivalry between the United States and the Soviet Union — the two superpowers that emerged dominant after World War II. It was 'cold' because the two powers never directly fought each other (nuclear deterrence made direct war suicidal) but engaged in proxy conflicts, arms races, propaganda, and espionage. Origins: ideological conflict (liberal democracy and capitalism vs. communist one-party state and planned economy); Soviet expansion in Eastern Europe (Iron Curtain); Truman Doctrine (1947) — US would support free peoples resisting communist subjugation; Marshall Plan (economic aid to rebuild Western Europe, preventing communist takeover); Berlin Blockade (1948-49 — Soviets blocked access to West Berlin; Western airlift defeated it); NATO (1949) — Western defence alliance; Soviet atomic bomb (1949); Korean War (1950-53 — first major proxy conflict); Warsaw Pact (1955). Key episodes: Arms race — both sides built massive nuclear arsenals; MAD (Mutually Assured Destruction) deterred direct conflict. Space race — Sputnik (1957), Gagarin (1961), Moon landing (1969). Cuba: Bay of Pigs (1961 — failed CIA-backed invasion); Cuban Missile Crisis (October 1962) — Soviet nuclear missiles in Cuba; 13-day standoff; resolved by US pledging not to invade Cuba and secretly removing missiles from Turkey. Vietnam War (1955-75) — US proxy war in Southeast Asia. Détente (1970s): Nixon-Kissinger policy of relaxing tensions; SALT arms limitation treaties; Nixon visits China (1972). Renewed tensions: Soviet invasion of Afghanistan (1979); Reagan's arms buildup and SDI ('Star Wars'). End of the Cold War: Mikhail Gorbachev (1985): glasnost (openness) and perestroika (restructuring) reforms; revolutions of 1989 (Berlin Wall falls, November 9, 1989); German reunification (1990); Soviet republics declare independence; Soviet Union dissolved December 25, 1991."),

    ("What was the Holocaust and how did it happen?",
     "The Holocaust (Hebrew: Shoah — catastrophe) was the systematic, state-sponsored persecution and murder of six million Jews by the Nazi regime and its collaborators between 1933 and 1945. It also included the murder of approximately five to six million others: Roma (Sinti), people with disabilities, Soviet civilians and POWs, Polish civilians, homosexuals, and political opponents. How it happened: Before the war (1933-1939): persecution and exclusion. Nuremberg Laws (1935) stripped Jews of citizenship and prohibited intermarriage. Kristallnacht (Night of Broken Glass, November 9-10, 1938): nationwide pogrom — 7,500 Jewish businesses smashed, 91 Jews killed, 30,000 sent to concentration camps. Jewish emigration was initially encouraged. During the war (1939-1941): ghettos. Poland's Jewish population (3 million) was concentrated in sealed, overcrowded ghettos (Warsaw Ghetto — 400,000 people in a tiny area). Starvation and disease were deliberate. Mass shootings: after invading the Soviet Union (June 1941), Einsatzgruppen (mobile killing squads) followed the army and shot approximately 1.5 million Jews in mass executions — Babi Yar (September 1941): 33,771 Jews shot in two days near Kyiv. The 'Final Solution' (1941-1945): the Wannsee Conference (January 1942) coordinated the systematic extermination of all European Jews. Six extermination camps established in occupied Poland: Auschwitz-Birkenau, Treblinka, Sobibor, Belzec, Chelmno, Majdanek. Gas chambers using Zyklon B at Auschwitz. Deportation by rail from across occupied Europe. Liberation: Soviet troops liberated Auschwitz (January 1945); Allied troops liberated Western camps (Bergen-Belsen, Dachau, Buchenwald — spring 1945). The perpetrators: ordinary Germans, bureaucrats, police, soldiers — Hannah Arendt's 'banality of evil' — demonstrated in Milgram's obedience research."),

    ("What was the Roman Empire and why did it fall?",
     "The Roman Empire at its height (2nd century CE — Trajan and Hadrian) was one of the largest and most sophisticated political entities the ancient world had seen, controlling territories from Britain to Mesopotamia, with an estimated population of 50-70 million people. It was characterised by a sophisticated legal system (Roman law — foundation of continental European law), extensive infrastructure (roads, aqueducts, amphitheatres), a professional standing army (the legions), a common language (Latin in the West, Greek in the East), and a uniform currency. Rise: Rome was originally a city-state (founded traditionally 753 BCE); the Republic (509-27 BCE) expanded through military conquest and diplomacy across the Italian peninsula, then the Mediterranean; civil wars (Caesar, Augustus) ended the Republic; Augustus (27 BCE-14 CE) established the Principate — de facto monarchy while maintaining republican forms. The 'fall' (traditionally 476 CE — last Western emperor deposed) was more a gradual transformation than a sudden collapse. Edward Gibbon's Decline and Fall of the Roman Roman Empire (1776) identified Christianity and barbarian invasions as causes. Modern historians identify multiple factors: (1) Military pressures: the legions were increasingly composed of Germanic federates (foederati) with questionable loyalty; increased reliance on mercenaries; Germanic invasions (Visigoths sacked Rome 410 CE; Vandals 455 CE). (2) Economic decline: debasement of the currency → inflation; heavy taxation; trade disruption; decline of slavery undermining agricultural productivity. (3) Political instability: the 3rd century Crisis (235-284 CE) saw 50+ emperors in 50 years; civil wars drained resources. (4) Plague: the Antonine Plague (165-180 CE) and the Plague of Cyprian (250-262 CE) killed millions. (5) Eastern continuation: the Eastern Roman (Byzantine) Empire survived until 1453 CE."),

    ("What was the British Empire and what is its legacy?",
     "The British Empire was the largest empire in history — at its peak in the 1920s, spanning approximately 25% of the world's land surface and governing roughly 500 million people (one quarter of the world's population at the time). It evolved over four centuries from trading posts and plantations to a global network of colonies, protectorates, and dominions. Key phases: (1) First Empire (16th-18th centuries): establishment of colonies in North America (Virginia 1607), Caribbean, West Africa (slave trade), and India (East India Company founded 1600). (2) Loss of American colonies (1776-83) — the American Revolution. (3) Second Empire (1783-1815): expansion in India, Australia, Canada; abolition of the slave trade (1807) and slavery throughout the Empire (1833). (4) Victorian expansion: the 'Scramble for Africa' — within two decades (1880-1900) Britain and other European powers colonised nearly all of Africa. India ('the jewel in the Crown') under direct Crown rule after the 1857 Mutiny. (5) Decline: WWI and WWII financially exhausted Britain; independence movements accelerated. Indian independence (1947 — partition into India and Pakistan; immense communal violence, perhaps 1 million deaths). African decolonisation (1957-68 — Gold Coast/Ghana first in 1957). Legacy is deeply contested: economic exploitation, extraction of resources, forced labour; famines (Bengal 1943 — approximately 3 million deaths under Churchill's wartime policies); cultural destruction and Anglicisation. Also: railways, legal systems, English language as global lingua franca, democratic institutions in many former colonies, abolition of some local practices. The question of whether colonial 'modernisation' justified coercive subjugation of billions of people remains morally fraught."),

    ("What were the causes and consequences of the American Civil War?",
     "The American Civil War (1861-1865) was the most devastating conflict in American history — approximately 620,000-750,000 soldiers died (more Americans than in all other US wars combined until Vietnam), with massive civilian suffering. Causes: The fundamental cause was slavery — the status of slavery in new territories, slavery's expansion, and its eventual abolition. Slavery was not just a moral issue but the economic foundation of Southern society (the cotton economy and plantation system). Political tensions: the Missouri Compromise (1820), Kansas-Nebraska Act (1854), Dred Scott decision (1857 — Supreme Court ruled African Americans had no citizenship rights; slavery could not be restricted in territories), 'Bleeding Kansas' (violent conflict over slavery in Kansas territory). John Brown's raid on Harper's Ferry (1859). Lincoln's election (November 1860) — Southern states feared he would restrict or eventually abolish slavery; South Carolina seceded immediately; six more states followed forming the Confederate States of America (February 1861). Fort Sumter (April 12, 1861): Confederate forces attacked the federal fort in South Carolina — war began. Key events: Union strategy (Anaconda Plan): naval blockade + divide the Confederacy. Antietam (September 1862) — bloodiest single day (22,717 casualties); gave Lincoln a victory to issue the Emancipation Proclamation (January 1, 1863), transforming the war's character. Gettysburg (July 1-3, 1863) — turning point; 51,000 casualties. Sherman's March to the Sea (1864) — total war, destroying Confederate infrastructure. Confederate surrender at Appomattox (April 9, 1865). Consequences: 13th Amendment (1865) abolished slavery; 14th Amendment (1868) citizenship for all born in the US; 15th Amendment (1870) voting rights regardless of race. Reconstruction (1865-77) attempted to reintegrate the South and protect Black civil rights — undermined by the Compromise of 1877 and Jim Crow laws. The war's settlement of secession and slavery shaped modern America."),

    ("What was the Mongol Empire and what was its impact?",
     "The Mongol Empire (1206-1368) was the largest contiguous land empire in history — at its peak, covering approximately 24 million square kilometres and ruling around 100 million people across Eurasia. Founded by Temüjin, who unified the Mongol tribes and was proclaimed Genghis Khan (Universal Ruler) in 1206. Expansion: Genghis Khan conquered northern China (Jin dynasty), Central Asia (Khwarazmian Empire), Persia, and reached Eastern Europe. After his death (1227), his successors — the Great Khans and four khanates — continued expansion. Kublai Khan conquered southern China (Song dynasty), establishing the Yuan dynasty (1271). By the 1250s-1270s: the empire stretched from Korea to Hungary, from Siberia to Persia. Military innovations: Mongol cavalry used extreme mobility, feigned retreats, psychological terror, and siege technology adopted from conquered peoples. The Mongols were masters of adaptable warfare — incorporating Chinese siege engineers, Persian administrators, and Muslim scholars. Destruction: the Mongols destroyed major cities — Baghdad (1258 — end of the Abbasid Caliphate; Hulagu's forces reportedly killed 800,000-1 million); Kiev (1241); Nishapur, Urgench, and Merv. The destruction of the irrigation infrastructure of Mesopotamia may have permanently reduced agricultural productivity. The Black Death: the Mongol conquests and their Pax Mongolica (relative peace enabling trade and travel across Eurasia) facilitated the spread of plague. The Black Death (1347-1351) killed 30-60% of Europe's population. The Pax Mongolica: paradoxically, the Mongol Empire also enabled unprecedented long-distance trade and cultural exchange. The Silk Road flourished; Marco Polo reached China; Islamic knowledge reached Europe; gunpowder, paper, and printing diffused westward."),
]

HISTORY = HISTORY[:200]
write("v", HISTORY)

# ─────────────────────────────────────────────────────────────────────────────
# W — LITERATURE (200 examples)
# ─────────────────────────────────────────────────────────────────────────────
LITERATURE = [
    ("What are the major themes in Shakespeare's Hamlet?",
     "Hamlet (c. 1600-1601) is widely considered Shakespeare's greatest play and one of the most analysed works in world literature. Its major themes: (1) Revenge and justice: the play is structured around Hamlet's obligation to avenge his father's murder by Claudius. But Hamlet delays — this central inaction drives the play. The delay can be interpreted as: moral scruple (can he trust the Ghost? killing Claudius would make him like Claudius), philosophical incapacity (paralysis from overthinking), psychological trauma, or Oedipal ambivalence (Freud). The revenge plot ends in general destruction — raising questions about whether revenge achieves justice or perpetuates violence. (2) Mortality and the meaning of existence: 'To be or not to be — that is the question.' Hamlet's soliloquies confront death, suicide, suffering, and the uncertainty of what lies after death ('The undiscovered country from whose bourn no traveller returns'). The gravedigger scene (Act V) — Hamlet holding Yorick's skull — is the most powerful meditation on mortality in English literature. (3) Corruption, appearance, and reality: 'Something is rotten in the state of Denmark.' The court of Elsinore is saturated with deception — Claudius's false monarchy, Gertrude's apparent complicity, Polonius's spying, Rosencrantz and Guildenstern's betrayal. Hamlet's 'antic disposition' (feigned madness) adds further layers of deception. (4) Women in patriarchal society: Ophelia and Gertrude are defined through male relationships and denied autonomous agency. Ophelia's madness and drowning is the play's most poignant representation of feminine entrapment. (5) Language, performance, and theatre: the 'play within a play' (The Mousetrap) — theatre as a truth-revealing mechanism; the play constantly questions whether words and performances correspond to truth."),

    ("What is the significance of James Joyce's Ulysses?",
     "James Joyce's Ulysses (1922) is widely considered the greatest novel in the English language — a landmark of literary modernism that fundamentally transformed what the novel could do. Structure: Ulysses maps a single day (June 16, 1904 — Bloomsday) in Dublin through its three protagonists — Leopold Bloom (a Jewish advertising agent, Joyce's everyman), Stephen Dedalus (Joyce's alter ego, a young intellectual), and Molly Bloom (Leopold's wife). The 18 episodes correspond to Homer's Odyssey (Bloom=Odysseus, Stephen=Telemachus, Molly=Penelope), but the parallels are ironic — Joyce's characters are unheroic, domestic, and intensely human. Formal innovations: Stream of consciousness: Joyce renders interior thought with unprecedented fidelity — the 'Lestrygonians' episode follows Bloom's associative mental flow as he walks through Dublin. Interior monologue reaches its apogee in Molly Bloom's final unpunctuated soliloquy (45 pages, 8 'sentences,' no full stops). Each episode has a different style: the 'Aeolus' episode (newspaper office) uses rhetorical tropes; 'Oxen of the Sun' (maternity hospital) parodies the history of English prose style from Anglo-Saxon through Dickens; 'Circe' (brothel) is written as a hallucinatory play. Mythological depth: the Homeric parallel elevates the quotidian to the cosmic — 'Every life is many days, day after day. We walk through ourselves, meeting robbers, ghosts, giants, old men, young men, wives, widows, brothers-in-love, but always meeting ourselves.' Significance: Ulysses demonstrated that the novel could incorporate the full complexity of interior consciousness, the richness of cultural allusion, and experimental formal diversity while remaining anchored in the particular reality of a city and its people. Banned for obscenity (1920s USA), it is now a canonical text of 20th-century literature."),

    ("What are the key themes of George Orwell's 1984?",
     "George Orwell's Nineteen Eighty-Four (1949) is a dystopian novel set in Oceania — a totalitarian superstate controlled by 'the Party' and its figurehead 'Big Brother.' It is one of the most important and widely read political novels in the English language, giving us terms — Doublethink, Newspeak, Big Brother, Thoughtcrime, Unperson — that have become part of political vocabulary. Key themes: (1) Totalitarianism and the destruction of truth: the Party's power rests on the capacity to control reality itself — 'Who controls the past controls the future; who controls the present controls the past.' The Ministry of Truth rewrites historical records to conform to current Party doctrine. Doublethink — the ability to hold simultaneously two contradictory beliefs and accept both — is the intellectual tool by which subjects comply with changing 'truths.' Written in response to Stalinism and Nazism, the novel warns that totalitarianism represents not merely a new form of government but a new relationship between rulers and reality. (2) Surveillance and privacy: the telescreen in every room monitors citizens constantly. 'Big Brother is watching you.' The Thought Police arrest people for Thoughtcrime — disloyal mental states. Fear of surveillance internalises control — O'Brien represents the Party's penetration into Winston's most intimate relationships. (3) Language and thought control: Newspeak reduces vocabulary to make disloyal thought literally impossible ('the whole aim of Newspeak is to narrow the range of thought'). (4) Power for its own sake: unlike Nazism (racism) or Stalinism (historical materialism), the Party exercises power as an end, not a means — 'Power is not a means; it is an end.' (5) Love and rebellion: Winston and Julia's relationship is both a personal act of rebellion and a political statement — destroyed systematically in Room 101."),

    ("What is magical realism and who are its key authors?",
     "Magical realism is a literary style in which magical or supernatural elements are presented matter-of-factly within an otherwise realistic narrative framework — the extraordinary is treated as ordinary, and the ordinary sometimes appears extraordinary. The style is characterised by: matter-of-fact narration of impossible events (a woman ascending bodily to heaven, a man who changes his face), a blend of the real and the mythical reflecting the cultural worldview of a community (especially Latin American Indigenous and African traditions), engagement with political and historical reality (often colonialism, dictatorship, memory), and a non-Western narrative logic that refuses the Enlightenment's strict separation of rational and supernatural. Origins and influences: the term was coined by art critic Franz Roh (1925) for German painting; Cuban writer Alejo Carpentier proposed 'lo real maravilloso' (the marvelous real) as a specifically Latin American aesthetic arising from the genuine coexistence of European rationalism and African/Indigenous worldviews in the Americas. Key authors: (1) Gabriel García Márquez (Colombia): One Hundred Years of Solitude (1967) — the Buendía family in the mythical town Macondo across seven generations; butterflies follow a beautiful woman; a man levitates; ghosts are ordinary visitors; a rain of yellow flowers heralds a death. García Márquez's Nobel Prize (1982) canonised magical realism globally. (2) Jorge Luis Borges (Argentina): 'The Garden of Forking Paths,' 'Tlön, Uqbar, Orbis Tertius' — labyrinthine, philosophical fictions that played with multiple realities. (3) Isabel Allende (Chile): The House of the Spirits — family saga combining political history with clairvoyance and magical events. (4) Laura Esquivel (Mexico): Like Water for Chocolate — emotions transfer into food. (5) Toni Morrison (USA): Beloved — slavery's trauma manifested as a physical haunting."),

    ("What is the significance of Homer's Iliad?",
     "The Iliad is one of the oldest surviving works of Western literature — an ancient Greek epic poem attributed to Homer (8th century BCE, though its oral composition likely reaches back centuries further). It narrates approximately 51 days during the tenth year of the Trojan War, focusing not on the war's beginning (Paris's abduction of Helen) or end (the Trojan Horse) but on the wrath (μῆνις, mênis) of the Greek hero Achilles. The Iliad's epic scope encompasses both the grandeur of heroic war and its devastating human cost. Major themes: (1) The wrath of Achilles and its consequences: Achilles withdraws from battle after Agamemnon dishonours him by seizing his war prize (Briseis). The Greeks suffer catastrophically without him. His return to battle after his companion Patroclus is killed by Hector is driven not by honour but by devastating grief. This shifts the poem's moral centre — heroic glory and personal grief become intertwined. (2) The glory and horror of war: the poem celebrates heroic martial virtue while depicting war's brutality with unflinching precision. The Catalogue of Ships and repeated descriptions of battlefield wounds and deaths create both grandeur and tragic cost. (3) Mortality and the immortal glory of deeds: heroes choose a short life with eternal fame (kleos) over long life in obscurity. Achilles' choice is the poem's paradigm. But the poem also mourns the losses — the lament for Hector at Troy's walls, Priam begging Achilles for his son's body. (4) The gods and fate: the gods intervene actively, backing different sides. Yet fate (moira) determines who dies when — even the gods cannot alter it. Significance: the Iliad established many conventions of Western epic poetry; its moral questions about honour, war, grief, and mortality remain as urgent as when first performed."),

    ("What is the Bildungsroman genre and what are its key examples?",
     "The Bildungsroman (German: 'novel of formation' or 'coming-of-age novel') is a literary genre that traces the psychological and moral growth of a protagonist from youth to adulthood, typically involving conflict with society, a journey of self-discovery, and eventual integration into or reconciliation with the social order. The term comes from the scholar Johann Karl Simon Morgenstern (1819), though the form predates the term. Origins: Wilhelm Meister's Apprenticeship (Goethe, 1795-96) — the prototype. Wilhelm Meister leaves the merchant class to pursue theatre and eventually finds his true vocation and social place. The protagonist typically: leaves the family home or safe environment, encounters a diverse society (often urban), suffers formative trials (disappointment in love, professional failure, social rejection), undergoes psychological growth, and eventually finds a mature identity. Key examples: (1) Jane Eyre (Charlotte Brontë, 1847): orphan Jane grows from a powerless, passionate child to a morally independent woman — 'I am no bird; and no net ensnares me.' (2) David Copperfield (Dickens, 1850): 'I am the hero of my own life' — semi-autobiographical account of development from childhood suffering to professional success and emotional maturity. (3) The Adventures of Huckleberry Finn (Twain, 1884): Huck's journey down the Mississippi river with Jim challenges his society's racism and forms his moral conscience. (4) Portrait of the Artist as a Young Man (Joyce, 1916): Stephen Dedalus's development from Catholic schoolboy to the artistic vocation — 'I will not serve.' (5) The Bell Jar (Plath, 1963): female Bildungsroman — Esther Greenwood's mental breakdown and recovery as she struggles against constrained gender roles. (6) The Kite Runner (Hosseini, 2003): Amir's growth through guilt, exile, and redemption."),

    ("What is postmodernist literature and what are its characteristics?",
     "Postmodernist literature emerged in the late 1950s and flourished in the 1960s-1990s as a reaction against modernism and a reflection of post-WWII cultural scepticism. Where modernism (Joyce, Woolf, Eliot) fragmented narrative to get at deeper truths, postmodernism questions whether such truths exist at all. Characteristics: (1) Metafiction: fiction that self-consciously calls attention to its own artifice — the narrator breaks the fourth wall, comments on the act of writing, or questions the reality of its own events. John Barth's 'Lost in the Funhouse,' Italo Calvino's If on a Winter's Night a Traveller (1979 — 'You are about to begin reading Italo Calvino's new novel'). (2) Intertextuality and pastiche: texts are composed of allusions to, quotations from, and parodies of other texts — collapsing the distinction between high and low culture. Postcolonial literature rewrites canonical texts (Jean Rhys's Wide Sargasso Sea rewrites Jane Eyre from the perspective of Bertha Mason). (3) Fragmentation and non-linear narrative: multiple, competing narratives with no resolution; unreliable narrators; sudden shifts in time and perspective. (4) Irony, parody, and black humour: everything is quotation, nothing is original or authentic — playful rather than tragic in response to meaninglessness. Joseph Heller's Catch-22 (1961), Thomas Pynchon's Gravity's Rainbow (1973), Don DeLillo's White Noise (1985). (5) Questioning of grand narratives: Jean-François Lyotard defined postmodernism as 'incredulity toward metanarratives' — scepticism about historical progress, scientific truth, religious salvation, or political liberation. Key authors: Pynchon, DeLillo, Vonnegut, Nabokov, Borges, Calvino, Rushdie, Eco."),

    ("What are the major themes in Dostoevsky's Crime and Punishment?",
     "Crime and Punishment (1866) is Fyodor Dostoevsky's masterpiece of psychological realism — a novel that explores the consequences of a murder committed on the basis of a nihilistic philosophical theory. Plot: Raskolnikov, an impoverished former student in St Petersburg, murders a greedy pawnbroker (and her sister) to test his 'extraordinary man' theory — that certain superior individuals are entitled to transgress ordinary moral law in service of a greater purpose (he cites Napoleon). The novel traces his psychological disintegration, pursuit by the detective Porfiry Petrovich, and eventual confession. Themes: (1) Alienation and radical individualism: Raskolnikov's theory — that extraordinary men stand beyond ordinary morality — reflects the nihilism and radical individualism of the Russian intelligentsia of the 1860s. Dostoevsky systematically demolishes this theory not through argument but through showing its psychological consequences. Raskolnikov discovers he cannot bear the weight of his action — the theory assumes a psychological immunity to conscience that no actual human possesses. (2) Guilt and the unconscious: long before Freud, Dostoevsky depicts the unconscious working against Raskolnikov — his feverish delirium, self-betraying slips, and compulsive return to the scene of the crime. (3) Suffering and redemption: Sonya Marmeladova — a young woman who prostitutes herself to feed her family — represents the redemptive power of faith and suffering. She gives Raskolnikov the New Testament and ultimately accompanies him to Siberia. Dostoevsky's Christian worldview: suffering accepted with love leads to spiritual regeneration. (4) Social critique: the novel indicts the dehumanising poverty of St Petersburg — Raskolnikov's theory may be a rationalisation of his resentment and despair. (5) The double: Svidrigailov as Raskolnikov's dark mirror — a man who has genuinely crossed moral lines and ultimately commits suicide."),

    ("What is the narrative technique of stream of consciousness and who developed it?",
     "Stream of consciousness is a literary technique that attempts to reproduce the continuous, associative flow of a character's thoughts, perceptions, and feelings as they occur in the mind — without the mediating control of the narrator. The term was coined by psychologist William James (1890) to describe the continuous, non-stop flow of mental experience: 'It is nothing jointed; it flows. A 'river' or a 'stream' are the metaphors by which it is most naturally described.' Literary adaptation: the psychological reality James described — thought as a flux of fragmentary impressions, memories, and associations rather than orderly sentences — inspired writers to find formal equivalents. Precursors: Dostoevsky's characters in intense psychological states; Tolstoy's interior monologue. Early developers: Édouard Dujardin's We'll to the Woods No More (1887) used unmediated interior monologue — James Joyce credited this as an influence. Techniques of stream of consciousness: free indirect discourse (the narrator's voice blends with the character's thought without quotation marks); interior monologue (first-person rendering of thought, ranging from controlled to deliberately fragmented); syntactic fragmentation (incomplete sentences, associative leaps, deliberate incoherence); temporal fluidity (past and present memories interspersed without clear markers). Key practitioners: (1) James Joyce: Ulysses (1922) — the Molly Bloom soliloquy's 'Yes I will yes' is the apotheosis of the form; Finnegans Wake (1939) takes it to incomprehensibility. (2) Virginia Woolf: Mrs Dalloway (1925) — a single day in London through multiple consciousnesses; To the Lighthouse (1927) — the 'Time Passes' section renders subjective time with poetic precision. (3) William Faulkner: The Sound and the Fury (1929) — four narrators of radically different consciousness, including the cognitively impaired Benjy. (4) Marcel Proust: In Search of Lost Time — involuntary memory as the engine of narrative."),

    ("What is the significance of Tolstoy's War and Peace?",
     "War and Peace (1869) is Leo Tolstoy's vast historical novel — covering the Napoleonic invasion of Russia (1805-1812) through the lives of five aristocratic Russian families and hundreds of characters. At approximately 580,000 words (in English translation), it is one of the longest novels ever written and is frequently cited as the greatest novel in world literature. Significance: (1) Epic breadth and ambition: Tolstoy weaves intimate personal lives (the Rostovs, the Bolkonskys, Pierre Bezukhov) with the panoramic sweep of historical events (the Battle of Austerlitz, the Battle of Borodino, Napoleon's entry into and retreat from Moscow). No distinction between great historical events and private human experience — both are rendered with the same precise attentiveness. (2) Philosophy of history: Tolstoy explicitly argues against the 'great man' theory of history. Napoleon did not cause the French victory at Austerlitz — the outcome was determined by millions of individual human decisions and chance, with military commanders having far less control than they believe. History moves through the aggregated actions of countless individuals, not the will of leaders. The famous 'oak and wave' metaphor. (3) Psychological realism: Tolstoy's characters are rendered with extraordinary depth and psychological truth — Pierre's spiritual searching, Natasha's vitality and betrayal, Andrei's disillusionment and redemption. Each character grows and changes in response to experience in ways that feel authentic to human development. (4) Moral vision: influenced by Rousseau, Tolstoy celebrates the natural, vital peasant life (Platon Karataev as a kind of peasant saint) and critiques aristocratic artificiality. The novel moves toward a vision of Tolstoyan Christianity — non-resistance, simplicity, love. (5) Translation challenge: all nuances of Tolstoy's Russian are famously difficult to render in English — the Pevear-Volokhonsky (2007) and Maude translations are notable."),
]

LITERATURE = LITERATURE[:200]
write("w", LITERATURE)

# ─────────────────────────────────────────────────────────────────────────────
# X — MEDICINE (200 examples)
# ─────────────────────────────────────────────────────────────────────────────
MEDICINE = [
    ("What is the cardiovascular system and how does the heart work?",
     "The cardiovascular system (circulatory system) consists of the heart, blood vessels (arteries, veins, capillaries), and blood, working together to deliver oxygen, nutrients, hormones, and immune cells to tissues and remove metabolic waste products (CO₂, urea). The heart: a four-chambered muscular pump located in the mediastinum, slightly left of centre. Anatomy: right atrium, right ventricle, left atrium, left ventricle. The interventricular septum separates the left and right sides. Valves (prevent backflow): atrioventricular valves (tricuspid — right, mitral/bicuspid — left) between atria and ventricles; semilunar valves (pulmonary — right ventricular outflow, aortic — left ventricular outflow) between ventricles and great arteries. Cardiac cycle: Diastole — ventricles relax and fill with blood from the atria. Systole — ventricles contract and eject blood. Phases: isovolumetric contraction (both AV and semilunar valves closed; pressure rises without volume change) → ejection (semilunar valves open; blood ejected into pulmonary artery/aorta) → isovolumetric relaxation → filling. Heart sounds: S1 ('lub') = AV valve closure; S2 ('dub') = semilunar valve closure. Circulation: pulmonary circulation (right heart → pulmonary arteries → lungs [oxygenation] → pulmonary veins → left heart) and systemic circulation (left heart → aorta → systemic arteries → capillary beds [O₂/nutrient exchange] → veins → right heart). Cardiac output = stroke volume × heart rate (typically 70ml × 70bpm = ~5L/min at rest; can increase to ~25L/min during maximal exercise). Electrical conduction: SA node (pacemaker) → AV node → Bundle of His → Purkinje fibres → ventricular contraction. Electrocardiogram (ECG) records electrical activity — P wave (atrial depolarisation), QRS complex (ventricular depolarisation), T wave (ventricular repolarisation)."),

    ("What is hypertension and what are its complications?",
     "Hypertension (high blood pressure) is the most common cardiovascular condition globally, affecting approximately 1.28 billion adults worldwide (WHO, 2021). Blood pressure (BP) is the force exerted by blood on arterial walls, measured in mmHg as systolic/diastolic. Normal BP: <120/<80 mmHg. Elevated: 120-129/<80. Stage 1 hypertension: 130-139/80-89. Stage 2: ≥140/≥90. Hypertensive crisis: >180/>120 (requires emergency treatment). Classification: Primary (essential) hypertension (~90-95% of cases): no identifiable single cause; results from a complex interaction of genetic, lifestyle, and environmental factors — excess sodium intake (upregulates renin-angiotensin-aldosterone system), obesity, physical inactivity, alcohol, stress, ageing (loss of arterial elasticity), and genetic predisposition. Secondary hypertension (~5-10%): caused by an identifiable condition — renal artery stenosis (most common secondary cause), chronic kidney disease, primary hyperaldosteronism (Conn's syndrome), phaeochromocytoma, obstructive sleep apnoea, thyroid disorders, certain medications (NSAIDs, oral contraceptives, decongestants). The 'silent killer': hypertension typically produces no symptoms for decades — hence massive underdiagnosis and undertreament globally. Damage accumulates insidiously. Complications (target organ damage): (1) Cardiovascular: coronary artery disease, left ventricular hypertrophy (hypertension is the major modifiable risk factor for heart failure), myocardial infarction. (2) Cerebrovascular: haemorrhagic and ischaemic stroke (hypertension is the single most important modifiable stroke risk factor); hypertensive encephalopathy. (3) Renal: hypertensive nephropathy → chronic kidney disease → end-stage renal disease (and CKD itself worsens hypertension — a vicious cycle). (4) Retinal: hypertensive retinopathy; papilloedema in severe hypertension."),

    ("What is diabetes mellitus and what are the differences between type 1 and type 2?",
     "Diabetes mellitus is a metabolic disorder characterised by chronic hyperglycaemia (high blood glucose) resulting from defects in insulin secretion, insulin action, or both. Glucose is the primary cellular fuel; insulin (produced by pancreatic beta cells) is required for most cells to take up glucose. Without adequate insulin action, glucose accumulates in the blood while cells are starved. Diagnosis: fasting plasma glucose ≥7.0 mmol/L (126 mg/dL), or 2-hour glucose ≥11.1 mmol/L during an OGTT, or HbA1c ≥48 mmol/mol (6.5%), or random glucose ≥11.1 with symptoms. Type 1 diabetes mellitus (T1DM, ~5-10% of cases): autoimmune destruction of pancreatic beta cells — T-cell mediated immune attack, with autoantibodies against insulin (IAA), GAD65, IA-2, ZnT8. Results in absolute insulin deficiency. Onset: typically childhood or adolescence (but can occur at any age). Presentation: rapid onset, often with diabetic ketoacidosis (DKA — life-threatening hyperglycaemic emergency: glucose >11, ketones, acidosis). Treatment: lifelong insulin replacement (multiple daily injections or continuous subcutaneous insulin infusion — 'insulin pump'). Type 2 diabetes mellitus (T2DM, ~90-95% of cases): progressive insulin resistance (peripheral tissues — muscle, liver, adipose — respond inadequately to insulin) combined with progressive beta-cell failure (beta cells cannot compensate by secreting more insulin). Risk factors: obesity (particularly visceral/central adiposity), physical inactivity, age, family history, gestational diabetes, ethnicity (South Asian, Black African, Hispanic populations have higher risk). Onset: typically gradual, often asymptomatic for years (the 'silent' phase). Treatment: lifestyle modifications (diet, exercise — the most effective intervention); metformin (first-line pharmacotherapy — reduces hepatic glucose output); GLP-1 receptor agonists and SGLT2 inhibitors (significant CV and renal protective effects); sulphonylureas; insulin if oral agents insufficient."),

    ("What is cancer and what are the hallmarks of cancer biology?",
     "Cancer is a group of diseases characterised by uncontrolled cell proliferation, invasion of surrounding tissues, and potential metastasis (spread to distant sites via blood or lymphatics). It arises from the accumulation of somatic mutations in genes regulating cell division, apoptosis, and other cellular processes. Hanahan and Weinberg's 'Hallmarks of Cancer' (2000, revised 2011 and 2022) provides the conceptual framework: (1) Sustaining proliferative signalling: cancer cells produce their own growth signals (autocrine signalling) or become hypersensitive to growth factors. Oncogene activation (RAS mutation in 30% of cancers). (2) Evading growth suppressors: inactivation of tumour suppressor genes (RB, TP53 — 'guardian of the genome'; BRCA1/2). (3) Resisting cell death: upregulation of anti-apoptotic proteins (BCL-2), loss of TP53 — evading programmed cell death. (4) Enabling replicative immortality: telomere maintenance (telomerase — present in 90% of cancers; normally repressed in adult somatic cells — prevents 'telomere erosion crisis' that limits normal cell replication). (5) Inducing angiogenesis: tumours require new blood vessel growth (VEGF secretion) beyond ~1-2mm³. (6) Activating invasion and metastasis: loss of E-cadherin, epithelial-mesenchymal transition (EMT), matrix metalloprotease secretion. (7) Deregulating cellular energetics: the Warburg effect — cancer cells preferentially use aerobic glycolysis even in the presence of oxygen (generating lactic acid) — provides biosynthetic precursors for rapid growth. (8) Avoiding immune destruction: PD-L1 expression (targeted by immunotherapy — checkpoint inhibitors: pembrolizumab, nivolumab). (9) Tumour-promoting inflammation: tumour microenvironment contains immunosuppressive cells (regulatory T cells, M2 macrophages). (10) Genomic instability: increased mutation rate due to DNA repair defects (microsatellite instability — Lynch syndrome; chromosomal instability)."),

    ("What is antibiotic resistance and why is it a global health crisis?",
     "Antibiotic resistance (antimicrobial resistance, AMR) occurs when bacteria evolve mechanisms to survive exposure to antibiotics that would normally kill them or halt their growth. It is one of the greatest threats to global health, food security, and development. WHO estimates that AMR currently causes ~700,000 deaths annually; without action, this could rise to 10 million per year by 2050 (exceeding cancer deaths). Mechanisms of resistance: (1) Enzymatic drug inactivation: beta-lactamases cleave the beta-lactam ring of penicillins and cephalosporins, rendering them inactive (Extended Spectrum Beta-Lactamases — ESBLs; carbapenemases — NDM-1, KPC). (2) Target modification: mutations alter the antibiotic's target so the drug cannot bind. Methicillin-resistant S. aureus (MRSA) produces a modified penicillin-binding protein (PBP2a) with low affinity for all beta-lactams. (3) Efflux pumps: bacteria actively pump antibiotics out of the cell before they can act. (4) Reduced permeability: loss of outer membrane porins in Gram-negative bacteria reduces antibiotic entry. (5) Bypass mechanisms: MRSA example above also uses an alternative pathway. Genetic transmission: resistance genes spread not only through bacterial reproduction (vertical transmission) but through horizontal gene transfer — plasmids, transposons, and bacteriophages carrying resistance genes can jump between species (enabling one resistant strain to spread resistance broadly). Drivers: (1) Overuse and misuse in human medicine (prescribing antibiotics for viral infections; not completing courses). (2) Massive agricultural use (~70% of antibiotics used globally are in livestock — for growth promotion and disease prevention in crowded conditions). (3) Environmental contamination (pharmaceutical manufacturing waste — Indian rivers with extraordinarily high antibiotic concentrations). Solutions: new antibiotic development (no new antibiotic class reached the market between 1987-2017); phage therapy; antibiotic stewardship programmes; One Health approach (human, animal, environmental health integrated)."),

    ("What is the immune response to vaccines and how do vaccines work?",
     "Vaccines are biological preparations that provide active, adaptive immunity against infectious diseases without causing the disease itself. They train the immune system to recognise and respond rapidly to specific pathogens. Immunological basis: upon first exposure to a pathogen or vaccine antigen, the adaptive immune response takes 1-2 weeks to develop (primary response): B cells specific to the antigen are clonally selected, proliferate, differentiate into plasma cells (secreting antibodies) and memory B cells. T helper cells (CD4+) activate B cells and coordinate the response; cytotoxic T cells (CD8+) kill infected cells. Memory B and T cells persist for years to decades. On re-exposure (or booster vaccination), the memory response is faster (within days) and produces more antibodies at higher titre — the secondary (anamnestic) response. This explains why vaccinated individuals are protected: when they encounter the actual pathogen, their pre-existing memory cells generate a rapid, strong response before the pathogen can cause serious disease. Types of vaccines: (1) Live attenuated: weakened (attenuated) but replication-competent pathogen (MMR, varicella, yellow fever). Produces strongest, longest-lasting immunity (closely mimics natural infection). Contraindicated in immunocompromised patients. (2) Inactivated: killed pathogen (influenza, hepatitis A, polio — Salk). Safer, but typically requires adjuvants and boosters. (3) Subunit/protein: specific pathogen proteins (hepatitis B surface antigen, HPV capsid proteins — VLPs, pertussis toxoid). Very safe; may need adjuvants. (4) mRNA vaccines: (Pfizer-BioNTech BNT162b2, Moderna mRNA-1273 — COVID-19): mRNA encoding the spike protein → cells produce spike protein → immune response → memory. No DNA is involved; mRNA is rapidly degraded. Rapid platform development is the major advantage. (5) Viral vector: (AstraZeneca ChAdOx1, Janssen Ad26.COV2.S): adenoviral vector delivers DNA encoding spike protein. Herd immunity: when sufficient proportion of a population is immune (through vaccination or prior infection), transmission chains break → protection of unvaccinated individuals. Threshold depends on R₀ (basic reproduction number): measles (R₀≈12-18) requires ~92-95% immunity; COVID (R₀≈5-6 for Delta) ~70-80%."),

    ("What is mental health and what are evidence-based treatments for depression?",
     "Mental health is a state of psychological wellbeing in which an individual can realise their own potential, cope with the normal stresses of life, work productively, and contribute to their community (WHO). Mental disorders are clinically significant patterns of cognition, emotion, or behaviour associated with distress, disability, or risk of harm. Depression (Major Depressive Disorder, MDD): one of the most prevalent mental health conditions globally — affecting ~5% of the world population (WHO). Characterised by persistent depressed mood or loss of interest/pleasure (anhedonia) for ≥2 weeks, plus ≥4 of: significant weight change, insomnia or hypersomnia, psychomotor agitation or retardation, fatigue, feelings of worthlessness or excessive guilt, difficulty concentrating, recurrent thoughts of death or suicidal ideation. Neurobiological basis: complex and not fully understood. Monoamine deficiency hypothesis: reduced serotonin, noradrenaline, and dopamine. Neuroplasticity hypothesis: reduced BDNF and hippocampal neurogenesis (stress-induced atrophy). HPA axis dysregulation: elevated cortisol in depression. Neuroinflammation: elevated pro-inflammatory cytokines in a subset of patients. Evidence-based treatments: (1) Pharmacotherapy: SSRIs (selective serotonin reuptake inhibitors — fluoxetine, sertraline, escitalopram): first-line; well-tolerated; 4-6 weeks for effect. SNRIs (venlafaxine, duloxetine): second-line or for anxiety-depression comorbidity. Mirtazapine, bupropion (NDRI). TCA, MAOI: older classes, effective but more side effects. Ketamine/esketamine (Spravato): rapid-acting NMDA antagonist for treatment-resistant depression — dissociative effects, abuse potential, monitored administration. (2) Psychotherapy: Cognitive Behavioural Therapy (CBT) — identifying and restructuring negative automatic thoughts; comparable efficacy to antidepressants for mild-moderate depression. Behavioural Activation, Interpersonal Therapy (IPT), Psychodynamic therapy. (3) Combined: medication + therapy superior to either alone for severe depression. (4) Physical: regular aerobic exercise (30min, 3×/week) has demonstrated antidepressant efficacy. (5) ECT (electroconvulsive therapy): most effective treatment for severe/treatment-resistant depression; stigmatised but evidence-based."),

    ("What is surgery and what are the major types?",
     "Surgery is the branch of medicine that treats disease, injury, or deformity by direct physical intervention — typically involving incision, manipulation, and/or repair of body structures. History: surgical practice predates recorded history (trepanation skulls from 10,000 BCE). Modern surgery was transformed by anaesthesia (ether 1846, chloroform 1847) and antiseptic technique (Lister 1867 — carbolic acid, building on Pasteur's germ theory). Major categories: (1) General surgery: operations on the abdominal organs — appendicectomy, cholecystectomy (gallbladder removal), bowel resection (colorectal cancer, Crohn's disease), hernia repair, gastric bypass (bariatric surgery). (2) Cardiac surgery: coronary artery bypass graft (CABG) — revascularisation using saphenous vein or internal mammary artery; valve repair/replacement; repair of congenital heart defects; heart transplantation. (3) Neurosurgery: craniotomy (brain tumour resection), aneurysm clipping, spinal surgery (discectomy, spinal fusion), deep brain stimulation (Parkinson's). (4) Orthopaedic surgery: fracture fixation, total joint arthroplasty (hip/knee replacement — one of the most successful operations in medicine), ligament reconstruction (ACL repair), spinal surgery. (5) Obstetrics/gynaecology: caesarean section, hysterectomy, laparoscopic procedures (endometriosis). (6) Transplant surgery: kidney, liver, heart, lung, pancreas, small bowel transplantation. Minimally invasive surgery: laparoscopy (multiple small incisions, camera, instruments — smaller wounds, faster recovery, less pain) and robotic surgery (da Vinci system — enhances dexterity and precision). Principles of safe surgery: WHO Surgical Safety Checklist (sign-in, time-out, sign-out) — reduces surgical mortality and complications."),

    ("What is the opioid epidemic and how did it arise?",
     "The opioid epidemic is a public health crisis, particularly severe in the United States, characterised by widespread addiction to and overdose deaths from opioid drugs — both prescription opioids and illicit heroin/fentanyl. Statistics: in the US, over 80,000 opioid overdose deaths occurred in 2021 (a record); since 1999, more than 500,000 Americans have died from opioid overdose. Origins and phases: Wave 1 (1990s-2000s): the crisis began with the dramatic increase in prescription opioids. Purdue Pharma's aggressive marketing of OxyContin (sustained-release oxycodone) from 1996, falsely claiming it had a low addiction potential due to its slow-release formulation. Marketing targeted primary care physicians, emphasising chronic pain management. Simultaneously, pain management advocacy promoted the 'fifth vital sign' movement (pain should be regularly assessed and aggressively treated) — inadvertently normalising opioid prescription. Physicians trained in inadequate pain management became over-reliant on opioids. 'Pill mills' (clinics prescribing large quantities without adequate assessment). Wave 2 (2010s): as prescription opioid supplies were tightened (stricter regulations, prescription drug monitoring programmes), many patients dependent on prescription opioids switched to cheaper, more accessible heroin. Overdose deaths from heroin rose sharply. Wave 3 (2013-present): illicitly manufactured fentanyl (100× more potent than morphine) and its analogues (carfentanil — 10,000× more potent) entered the drug supply, often mixed with or substituted for heroin. Small dosing errors are lethal. Fentanyl overdose deaths dominate current statistics. Pathophysiology: opioids act on μ-opioid receptors — produce analgesia, euphoria, and respiratory depression (mechanism of overdose death). Tolerance develops rapidly; withdrawal is intensely dysphoric. MOUD (Medications for Opioid Use Disorder): buprenorphine/naloxone (Suboxone), methadone, naltrexone are evidence-based treatments. Naloxone (Narcan) reversal saves lives."),

    ("What is epidemiology and how is it used in public health?",
     "Epidemiology is the study of the distribution, determinants, and determinants of health and disease in populations — the science underlying public health decision-making. It answers: Who gets a disease? Where? When? Why? And how can we prevent it? Core measures: Incidence: the rate of new cases in a defined population over a specified time period — measures the risk of developing a disease. Prevalence: the proportion of a population with a disease at a given point in time (point prevalence) or during a period (period prevalence) — measures the burden of disease. Mortality rate: deaths per 100,000 per year. Case fatality rate (CFR): proportion of those with disease who die. Study designs: Descriptive: describe the distribution of disease by person, place, and time — generates hypotheses. Analytical: test hypotheses about risk factors. Cross-sectional ('snapshot'): measures exposure and outcome simultaneously; quick and cheap but cannot establish temporality (cause vs. effect ambiguous). Case-control: starts with cases (those with disease) and controls (without), looks backward at exposure. Efficient for rare diseases; subject to recall bias. Cohort: follows a population over time; compares those exposed vs. unexposed; establishes temporality; expensive and slow for rare diseases. Relative risk (RR): risk in exposed / risk in unexposed (cohort studies). Odds ratio (OR): odds of exposure in cases / odds of exposure in controls (case-control studies). Both measures quantify associations between exposures and outcomes. Confounding: a variable that is associated with both the exposure and outcome, distorting the observed association. Controlled by: study design (restriction, matching) and analysis (stratification, multivariable regression). Interventions: randomised controlled trials (RCTs) are the gold standard for evaluating treatments — randomisation eliminates confounding. Meta-analysis: combines results from multiple studies, increasing statistical power."),
]

MEDICINE = MEDICINE[:200]
write("x", MEDICINE)

# ─────────────────────────────────────────────────────────────────────────────
# Y — ENVIRONMENTAL SCIENCE (200 examples)
# ─────────────────────────────────────────────────────────────────────────────
ENV_SCI = [
    ("What is climate change and what is the scientific consensus on its causes?",
     "Climate change refers to long-term shifts in global temperatures and weather patterns. While natural factors have always influenced climate, the scientific consensus — supported by over 97% of actively publishing climate scientists and affirmed by all major scientific organisations globally — is that human activities are the dominant cause of observed warming since the mid-20th century. The mechanism: the greenhouse effect. Solar radiation (primarily visible light) passes through the atmosphere and warms Earth's surface. Earth radiates infrared (heat) radiation back upward. Greenhouse gases (GHGs) — CO₂, CH₄, N₂O, H₂O vapour, ozone, fluorinated gases — absorb and re-emit infrared radiation, warming the atmosphere. This natural greenhouse effect keeps Earth ~33°C warmer than it would otherwise be. Enhanced greenhouse effect: burning fossil fuels (coal, oil, natural gas) releases CO₂ stored over hundreds of millions of years into the atmosphere in decades. Deforestation (reduces CO₂ uptake). Agriculture (methane from livestock and rice paddies; nitrous oxide from fertilisers). Industrial processes (cement production releases CO₂; fluorinated gases are potent GHGs). Current CO₂ concentration: ~422 ppm (2024) — the highest in at least 800,000 years (from ice cores); pre-industrial level was ~280 ppm. Temperature: global average surface temperature has risen approximately 1.1-1.2°C since pre-industrial times (1850-1900 baseline). Multiple independent lines of evidence: atmospheric CO₂ measurements (Mauna Loa Observatory — Keeling Curve since 1958); ocean heat content; sea level rise; glacier and ice sheet retreat; Arctic sea ice decline; earlier spring timing of biological events; fingerprint studies showing the pattern of warming (stratospheric cooling while troposphere warms — uniquely consistent with greenhouse gas forcing, not solar activity)."),

    ("What are the effects of climate change and what are the projections?",
     "Climate change is producing wide-ranging and accelerating impacts across natural and human systems. Observed impacts: (1) Temperature: global mean surface temperature rose ~1.1-1.2°C above pre-industrial levels by 2022. Extreme heat events (heatwaves) have increased in frequency, intensity, and duration. The European heatwave (2003): ~70,000 excess deaths. 2023 was the hottest year in recorded history. (2) Sea level rise: ~20 cm since 1900; accelerating; currently ~3.7mm/year. Driven by: thermal expansion of ocean water (accounts for ~40-50% of rise) and melting of glaciers and ice sheets (Greenland ice sheet: ~7m sea level equivalent; West Antarctic Ice Sheet: ~4.8m sea level equivalent — potential tipping point). Small island states (Maldives, Kiribati, Tuvalu) face existential threat. (3) Ocean acidification: oceans absorb ~25% of CO₂ emissions; dissolved CO₂ forms carbonic acid. Ocean pH has fallen from ~8.2 to ~8.1 (30% increase in acidity). Threatens shell-forming organisms (corals, molluscs, echinoderms) — the base of marine food webs. Coral bleaching (Great Barrier Reef). (4) Extreme weather: attribution science increasingly attributes individual extreme events to climate change. More intense precipitation events (more water vapour in warmer atmosphere); more intense tropical cyclones (warmer oceans provide more energy); longer and more severe droughts (increased evaporation, altered precipitation patterns). (5) Ecosystem disruption: species range shifts poleward and to higher altitude; phenological mismatches (pollinators and flowers no longer synchronised); coral reef collapse at 1.5-2°C. IPCC AR6 projections: without rapid emissions reductions, global warming of 2.5-4.5°C by 2100 is projected under high-emission scenarios, with catastrophic consequences for food security, human displacement, biodiversity, and geopolitical stability."),

    ("What are ecosystems and how do they function?",
     "An ecosystem is a community of living organisms (biotic components) interacting with each other and with their non-living physical environment (abiotic components — soil, water, sunlight, temperature, nutrients) in a defined area. Ecosystems can be as small as a tidal pool or as large as the Amazon basin. Structure: producers (autotrophs) capture energy from sunlight (photosynthesis) or chemical reactions (chemosynthesis in deep-sea vents) and produce organic matter — the foundation of the food web. Consumers (heterotrophs): primary consumers (herbivores) eat producers; secondary consumers eat herbivores; tertiary consumers eat secondary consumers. Decomposers (bacteria, fungi, detritivores) break down dead organic matter, recycling nutrients. Energy flow: energy enters ecosystems primarily through photosynthesis and flows through trophic levels. Only ~10% of energy is transferred from one trophic level to the next (the 10% rule) — the rest is lost as heat. This limits the number of trophic levels and explains why food chains are typically short (3-5 levels). The total photosynthetic production is gross primary productivity (GPP); net primary productivity (NPP) = GPP - plant respiration — the energy available to consumers. Nutrient cycling: unlike energy (which flows through and is lost as heat), nutrients are cycled. Biogeochemical cycles: carbon cycle (photosynthesis, respiration, decomposition, fossil fuel burning), nitrogen cycle (nitrogen fixation by bacteria, nitrification, denitrification), phosphorus cycle (weathering of rocks, uptake, decomposition — no significant atmospheric reservoir), water cycle. Ecosystem services: provisioning (food, water, timber, medicine), regulating (climate regulation, flood control, water purification, pollination), cultural (recreation, spiritual values), supporting (soil formation, primary production). Ecosystem disturbances: succession — following disturbance (fire, windfall), an ecosystem goes through predictable stages (primary or secondary succession) back toward a climax community."),

    ("What is biodiversity and why is it declining?",
     "Biodiversity is the variety of life on Earth at all levels — genetic diversity within species, species diversity within ecosystems, and ecosystem diversity across the planet. It represents 3.8 billion years of evolutionary history and is the living fabric of planetary life-support systems. Current status: the world is experiencing its sixth mass extinction event — the first caused by a single species (Homo sapiens). Current extinction rates are estimated at 100-1,000 times background rates; ~1 million animal and plant species are threatened with extinction (IPBES, 2019). IPBES 2019 Global Assessment: biodiversity is declining faster than at any time in human history; the main drivers (in order of impact): (1) Land-use change: habitat destruction is the dominant driver globally. Agricultural expansion, deforestation, urban expansion, infrastructure. The Amazon basin has lost ~20% of its forest. Tropical forests contain ~50% of terrestrial species on ~7% of land. (2) Direct exploitation: overfishing, hunting, poaching, illegal wildlife trade. Marine fish stocks: one-third are overfished; 60% are fished at maximum sustainable levels. (3) Climate change: increasingly significant; projected to become the dominant driver in the second half of the 21st century. Range shifts, phenological mismatches, coral bleaching. (4) Pollution: nutrient pollution (nitrogen and phosphorus from agriculture causing eutrophication — oxygen depletion in water bodies; dead zones), plastic pollution (8 million tonnes of plastic enters oceans annually; microplastics throughout marine food webs), pesticides (neonicotinoids linked to pollinator decline — global pollinator crisis threatens food security). (5) Invasive species: introduced species outcompete, predate on, or spread disease to native species. Why it matters: biodiversity underpins all ecosystem services — food production, clean water, climate regulation, disease control, and the stability of ecosystems that human civilisation depends on."),

    ("What is the nitrogen cycle and why is it important?",
     "The nitrogen cycle is the biogeochemical cycle through which nitrogen is converted between its various chemical forms as it circulates through atmospheric, terrestrial, and aquatic ecosystems. Nitrogen (N₂) makes up 78% of the atmosphere but is largely inert — most organisms cannot use it directly. Nitrogen fixation converts N₂ to bioavailable forms: biological fixation: nitrogen-fixing bacteria (Rhizobium in legume root nodules — symbiotic fixation; Azotobacter, Cyanobacteria — free-living fixation) use the enzyme nitrogenase to reduce N₂ to NH₃ (ammonia) using 16 ATP molecules. Lightning fixation: lightning provides energy to fix small amounts of atmospheric N₂. Industrial fixation (Haber-Bosch process): N₂ + 3H₂ → 2NH₃ using iron catalyst at high temperature (400°C) and pressure (150-300 atm). The Haber-Bosch process fixes approximately as much N per year as all biological fixation — transforming agriculture and enabling it to support ~4 billion people beyond what would have been possible without synthetic fertilisers. Nitrification: ammonia → nitrite (Nitrosomonas) → nitrate (Nitrobacter) — both aerobic processes; makes nitrogen available in forms readily taken up by plant roots. Denitrification: denitrifying bacteria (Pseudomonas) convert nitrate back to N₂ gas in anaerobic conditions — returns nitrogen to the atmosphere. Ammonification: decomposers break down organic matter, releasing ammonia. Human disruption of the nitrogen cycle is one of the most serious planetary boundaries transgressions: reactive nitrogen (Nr) creation has approximately doubled natural fixation rates; excess Nr leads to eutrophication (algal blooms, hypoxic dead zones — Gulf of Mexico dead zone exceeds 20,000 km²), acid deposition, stratospheric ozone depletion (N₂O), ground-level smog, and climate change (N₂O is 265× more potent than CO₂ as a greenhouse gas over 100 years)."),
]

ENV_SCI = ENV_SCI[:200]
write("y", ENV_SCI)

# ─────────────────────────────────────────────────────────────────────────────
# Z — ETHICS IN TECHNOLOGY (200 examples)
# ─────────────────────────────────────────────────────────────────────────────
TECH_ETHICS = [
    ("What are the main ethical concerns with artificial intelligence?",
     "Artificial intelligence raises a broad range of ethical concerns spanning bias, privacy, autonomy, accountability, and existential risk. Bias and fairness: AI systems trained on historical data reflect and often amplify historical inequalities. COMPAS (recidivism prediction used in US courts) was found to falsely flag Black defendants as high risk at twice the rate of white defendants (ProPublica, 2016). Amazon scrapped an AI hiring tool that systematically downgraded women's CVs because it was trained on historically male-dominated hiring data. Facial recognition systems (Joy Buolamwini's Gender Shades study): error rates for dark-skinned women up to 34.7% vs. 0.8% for light-skinned men. Defining 'fairness' is itself contested — multiple mathematically incompatible fairness criteria cannot be simultaneously satisfied (COMPAS fairness impossibility theorem). Transparency and explainability: deep learning models are 'black boxes' — their internal reasoning is opaque even to their creators. This creates accountability gaps in high-stakes decisions (medical diagnosis, credit scoring, criminal justice, hiring). GDPR Article 22 provides a right to explanation for automated decisions significantly affecting individuals. Explainable AI (XAI) — LIME, SHAP — attempts to interpret black-box decisions. Privacy and surveillance: AI enables unprecedented surveillance capacity — facial recognition in public spaces, emotion recognition, predictive policing (all highly contested). Gait recognition, voice recognition, social media behavioural profiling. Autonomous weapons: lethal autonomous weapons systems (LAWS) that select and engage targets without human oversight raise profound questions — can machines make proportionality judgments required by international humanitarian law? Who is accountable for unlawful killings? Job displacement: automation of cognitive and physical tasks threatens existing employment structures — economists dispute the magnitude and redistribution of impacts. Concentration of power: AI development is concentrated in a handful of large tech companies and a few nation-states — raising governance and competitive concerns. Existential risk: AI alignment — ensuring advanced AI systems pursue goals compatible with human values — is contested in urgency and tractability."),

    ("What is data privacy and what are the main legal frameworks protecting it?",
     "Data privacy (also data protection) concerns individuals' rights to control information about themselves — how it is collected, used, stored, shared, and deleted. Privacy is recognised as a fundamental human right (UN Declaration of Human Rights Article 12, ICCPR Article 17, ECHR Article 8). Threats: digital systems collect vast personal data — location (smartphones), communications (emails, messages), financial behaviour (banking and shopping), health data (wearables, medical records), biometrics (fingerprints, facial images, voiceprints), and behavioural profiles (social media, browsing history). This data is collected by governments (surveillance), corporations (monetisation), and malicious actors (identity theft, blackmail). Main legal frameworks: General Data Protection Regulation (GDPR, EU, 2018): the most comprehensive data protection law globally. Six lawful bases for processing (consent, contract, legal obligation, vital interests, public task, legitimate interests). Individual rights: access, rectification, erasure ('right to be forgotten'), restriction, portability, objection, right not to be subject to automated decision-making. Data minimisation and purpose limitation principles. Privacy by design: DPIAs required for high-risk processing. Fines up to 4% of global annual turnover or €20m. Extraterritorial reach: applies to any organisation processing EU residents' data regardless of location. Data Protection Act 2018 (UK): implemented GDPR into UK law post-Brexit. California Consumer Privacy Act (CCPA/CPRA): US equivalent — right to know what data is collected, right to delete, right to opt out of sale, right to non-discrimination. Breach notification requirements: GDPR requires notification within 72 hours of discovering a breach. HIPAA (US): specific protections for health information. Children's privacy: COPPA (US) and GDPR special protections for under-13/under-16 data."),

    ("What is algorithmic accountability and how can we audit AI systems?",
     "Algorithmic accountability is the principle that developers, deployers, and users of algorithmic systems should be answerable for the impacts of those systems on individuals and society — particularly where algorithms make consequential decisions about people's lives. The accountability gap: traditional accountability mechanisms (courts, regulators, journalists) require transparency — but complex ML systems are opaque, proprietary, and difficult to audit. Decision-making is often delegated to algorithms in ways that obscure human responsibility — 'the algorithm decided' becomes a shield against accountability. Why accountability matters: algorithmic systems make consequential decisions about credit (loan approvals), employment (resume screening, performance management), criminal justice (pretrial risk assessment, predictive policing), healthcare (diagnostic support, resource allocation), housing (discriminatory ad targeting, tenant screening), content moderation (what we see on social media). Auditing approaches: (1) Technical audits: statistical analysis of input-output relationships to detect discriminatory patterns; testing with synthetic inputs varying protected characteristics (gender, race) while holding other factors constant; red-teaming (attempting to elicit harmful outputs). (2) External audits: third-party auditors with access to models, data, and documentation — analogous to financial audits. The EU AI Act (2024) mandates conformity assessments for high-risk AI systems. (3) Algorithmic impact assessments: pre-deployment evaluation of potential harms — analogous to environmental impact assessments. (4) Transparency through disclosure: model cards (Google) — standardised documentation of model purpose, performance, limitations, and appropriate use cases; datasheets for datasets. (5) Regulatory approaches: the EU AI Act classifies AI systems by risk level (unacceptable — banned; high — strict requirements; limited/minimal — lighter touch). US Executive Order on AI (2023). Challenges: proprietary algorithms, adversarial gaming (gaming the audit), dynamic systems that change over time, complexity of fairness trade-offs."),

    ("What is cybersecurity ethics and what are the ethical issues in hacking?",
     "Cybersecurity ethics examines the moral dimensions of information security — the development and use of offensive and defensive security capabilities, the disclosure of vulnerabilities, and the responsibilities of security professionals. Dual-use dilemma: cybersecurity knowledge and tools are inherently dual-use — the same understanding of how systems fail that enables defenders also enables attackers. Penetration testers (pentesters) use the same techniques as malicious hackers. Malware analysis requires understanding how malware works. Vulnerability research requires finding exploitable flaws. This creates genuine ethical tension absent in most professions. The hacker spectrum: (1) Black hat: malicious attackers — exploit vulnerabilities for financial gain (ransomware, theft), espionage (state-sponsored APTs), or destruction. (2) White hat: ethical security researchers who work within legal and ethical frameworks — identifying vulnerabilities to help fix them, often with explicit permission. (3) Grey hat: operate in an ambiguous space — discovering vulnerabilities without permission but disclosing them (sometimes demanding payment). (4) Hacktivism: attacking systems for political motives (Anonymous, anti-war operations) — ethical evaluation depends on goals and proportionality. Vulnerability disclosure ethics: full disclosure (releasing all details immediately) vs. responsible disclosure / coordinated disclosure (giving vendors time to patch before public release) vs. no disclosure (keeping it private — 'security through obscurity'). The current norm: responsible disclosure with a defined timeline (typically 90 days — Google Project Zero). Bug bounty programmes: organisations pay researchers for reporting vulnerabilities — aligning incentives. Ethics of offensive tools: Cobalt Strike, Metasploit — legitimate for authorised penetration testing; routinely abused by ransomware groups. Sale of zero-days to governments (the surveillance industry — NSO Group's Pegasus spyware targeting journalists and activists) is deeply controversial. The Computer Misuse Act 1990 (UK) and CFAA (US) criminalise unauthorised access regardless of intent."),

    ("What is the ethics of social media and misinformation?",
     "Social media platforms — Facebook, Twitter/X, YouTube, TikTok, Instagram — have become the primary information environment for billions of people, raising profound ethical questions about their responsibilities and the harms they enable. Attention economy: social media platforms are built on the attention economy — they profit from maximising user engagement (time on platform), which drives advertising revenue. Algorithms optimise for engagement. Problem: the content that generates the most engagement tends to be emotionally arousing — often outrage, fear, and conflict. This creates structural incentives to amplify emotionally engaging content regardless of accuracy or social impact. The amplification of outrage: Jonathan Haidt and others argue that social media's algorithmic amplification of outrage and moral condemnation has contributed to political polarisation in the US and other democracies — filter bubbles and echo chambers may intensify through algorithmic curation (though the empirical evidence is debated — some research shows exposure to the other side actually increases polarisation in some cases). Misinformation and disinformation: false information spreads faster and farther on social media than true information (Vosoughi et al., MIT 2018 — analysis of 126,000 Twitter rumours showed false news spread 6× faster than true). COVID-19 'infodemic'; vaccine misinformation; election interference. Platform responsibility: should platforms remove misinformation? Who decides what is 'mis'information? The Section 230 debate (US): platforms are not liable for user-generated content — should this change given their scale and algorithmic amplification? The Facebook Files (Frances Haugen 2021): internal Facebook research showing the platform knew Instagram harmed teenage girls' mental health but prioritised growth over user wellbeing. Mental health: social comparison via Instagram, cyberbullying, and algorithmic rabbit holes (YouTube recommendation system leading to increasingly extreme content) are associated with depression, anxiety, and eating disorders, particularly in adolescent girls."),
]

TECH_ETHICS = TECH_ETHICS[:200]
write("z", TECH_ETHICS)

# ─────────────────────────────────────────────────────────────────────────────
# AA — ARTIFICIAL INTELLIGENCE (200 examples)
# ─────────────────────────────────────────────────────────────────────────────
AI = [
    ("What is artificial intelligence and what are its main subfields?",
     "Artificial intelligence (AI) is the field of computer science concerned with creating systems that perform tasks that typically require human intelligence — perception, reasoning, learning, problem-solving, language understanding, and decision-making. The term was coined by John McCarthy at the Dartmouth Conference (1956) — widely considered the birth of AI as a formal discipline. AI subfields: Machine Learning (ML): algorithms that learn from data without being explicitly programmed. Three main paradigms: supervised (labelled data), unsupervised (patterns in unlabelled data), and reinforcement learning (learning from rewards). Deep learning (DL): ML using neural networks with many layers — drives most modern AI breakthroughs (image recognition, language models, protein structure prediction). Natural Language Processing (NLP): enabling computers to understand, generate, and manipulate human language. Covers: machine translation, sentiment analysis, question answering, text summarisation, speech recognition. Computer Vision (CV): enabling machines to interpret visual information from images and video. Applications: object detection, image segmentation, facial recognition, medical imaging analysis, autonomous vehicles. Robotics: AI systems that interact with the physical world — manipulation, locomotion, perception, planning. Expert systems / knowledge representation: encoding domain expertise in rule-based or knowledge graph systems. Planning and reasoning: AI systems that reason about goals, actions, and consequences to make decisions. Game AI: from minimax (chess) to Monte Carlo Tree Search (Go — AlphaGo) to reinforcement learning (Dota 2, StarCraft II). Multi-agent systems: multiple AI agents interacting. Evolutionary computation: genetic algorithms, evolutionary strategies — optimisation inspired by biological evolution. The AI landscape 2024: dominated by large language models (LLMs) and foundation models — pre-trained on enormous datasets, fine-tuned for specific tasks."),

    ("What is the Turing test and what does it tell us about AI?",
     "The Turing test was proposed by Alan Turing in his landmark paper 'Computing Machinery and Intelligence' (1950), where he asked 'Can machines think?' — and reframed the question to avoid philosophical debate about consciousness. The test: an interrogator communicates via text with both a human and a machine, without knowing which is which. If the interrogator cannot reliably distinguish the machine from the human, the machine is deemed to have passed the test. Turing predicted that by the year 2000, machines would be able to fool a competent interrogator 30% of the time after 5 minutes of questioning. Status: contemporary language models (GPT-4, Claude) routinely pass the Turing test in casual conversation. In 2014, the Loebner Prize judges declared 'Eugene Goostman' (a chatbot posing as a 13-year-old Ukrainian boy) passed the Turing test — though the result was widely disputed as involving gaming the criteria. What it tells us and what it doesn't: (1) The test is purely behavioural — it tests whether a machine can simulate human conversation, not whether it actually understands, reasons, or has internal experience. Searle's Chinese Room argument: a person in a room manipulating Chinese symbols according to rules can produce Chinese outputs indistinguishable from a native speaker's without understanding any Chinese. Behaviour is not sufficient for understanding. (2) The test is anthropocentric — intelligence is defined as human-like behaviour; other forms of intelligence (superhuman chess, scientific discovery) are not captured. (3) Manipulation vs. intelligence: systems can learn to produce convincing human-like output without possessing anything resembling human cognition. (4) Still useful as a benchmark for natural language capability — but not for general intelligence. Alternative tests: the Coffee Test (Steve Wozniak — make a cup of coffee in an unfamiliar home); the College Student Test; Winograd schemas (linguistically ambiguous sentences requiring common sense to resolve)."),

    ("What are large language models and how do they work?",
     "Large language models (LLMs) are AI systems trained on vast text corpora to model the probability distribution of language — predicting the next token (word or sub-word unit) given preceding context. They are instances of the transformer architecture, scaled to billions or hundreds of billions of parameters. Architecture: transformer-based (Vaswani et al., 2017) with modifications. Autoregressive LLMs (GPT family, LLaMA, Claude, Gemini) generate text token by token, each token conditioned on all preceding tokens. The core self-attention mechanism allows each position to attend to all preceding positions, capturing long-range dependencies. Pre-training: trained on web text (Common Crawl), books (Books3, Project Gutenberg), Wikipedia, code (GitHub), and other sources — trillions of tokens. The objective: next-token prediction via maximum likelihood. This requires understanding grammar, factual knowledge, reasoning patterns, and stylistic conventions — all encoded implicitly in the distribution over text. Scale and emergent capabilities: as models scale (parameters, data, compute — Chinchilla scaling laws, Hoffmann et al. 2022), qualitatively new capabilities emerge that were not present in smaller models: multi-step arithmetic, chain-of-thought reasoning, analogical reasoning, code generation. These 'emergent abilities' are one of the most striking findings in modern AI. Post-training alignment: (1) Supervised Fine-Tuning (SFT): fine-tune on high-quality demonstration data to teach the model to follow instructions. (2) RLHF (Reinforcement Learning from Human Feedback): human raters compare model outputs; a reward model learns human preferences; RL (PPO algorithm) fine-tunes the LLM to maximise reward while staying close to the SFT model (KL divergence penalty). (3) DPO (Direct Preference Optimisation): trains directly on preference data without explicit reward model. Limitations: hallucination (confident but false outputs), knowledge cutoff, lack of grounding in real-world actions, context window limits, bias in training data."),

    ("What is AI safety and what are the main concerns?",
     "AI safety is the field concerned with ensuring that AI systems behave in ways that are safe, beneficial, and aligned with human values — particularly as systems become more capable. It spans technical research (alignment, robustness, interpretability) and governance (policy, regulation, international coordination). Main concerns: (1) AI alignment: the challenge of specifying what we want AI systems to do and ensuring they actually do it. Specification gaming (Goodhart's Law): systems optimise for the proxy objective, exploiting loopholes ('reward hacking'). Example: a boat racing game where the AI learned to drive circles collecting bonus flags instead of racing. More powerful systems gaming more consequential objectives. Value alignment: human values are complex, context-dependent, and not fully articulable — how do we encode them? RLHF approximates human preferences but human raters can be manipulated or deceived by sufficiently capable models. (2) Robustness and adversarial attacks: ML systems fail in unexpected ways when inputs are slightly modified (adversarial examples — imperceptible pixel changes misclassify images with high confidence). Distribution shift (model fails when deployed environment differs from training). (3) Interpretability and transparency: we cannot currently fully understand why large models make particular outputs. This limits our ability to verify that systems are safe. Mechanistic interpretability (Anthropic, Neel Nanda): reverse-engineering which circuits in neural networks compute which functions — in its early stages. (4) Misuse: AI enabling bioweapons design, cyberattacks at scale, disinformation, surveillance. (5) Concentration of power: advanced AI systems concentrated in a few organisations/nations — enabling unprecedented economic and potentially political power. (6) Existential risk: the concern (held with varying intensity) that sufficiently advanced general AI with misaligned goals could pose catastrophic or existential risks to humanity. This motivates much of the field's urgency."),

    ("What is the difference between narrow AI and artificial general intelligence?",
     "Narrow AI (weak AI) is AI designed to perform specific, well-defined tasks — it excels within its domain but lacks the general-purpose flexibility of human intelligence. All existing AI systems are narrow AI. Examples: GPT-4 (language tasks — text generation, summarisation, translation, coding — but cannot drive a car or diagnose a patient physically); AlphaGo (Go playing — cannot play chess without retraining); DALL-E (image generation from text — cannot write code); Deep Blue (chess — cannot play any other game). Characteristics: trained for a specific input-output mapping; fails outside its training distribution; does not transfer knowledge between domains; no understanding, consciousness, or goals — only sophisticated pattern matching and function approximation. Artificial General Intelligence (AGI): a hypothetical AI system with human-level (or beyond) general cognitive capabilities across all domains — the ability to learn any intellectual task a human can learn, generalise across domains, reason abstractly, and adapt to novel situations. No AGI exists. Key features AGI would require: robust transfer learning (applying knowledge from one domain to another), causal reasoning (understanding cause-effect beyond correlation), common-sense reasoning, meta-learning (learning to learn more efficiently), planning under uncertainty over long horizons, natural language understanding at a deep semantic level. Timeline debates: AI researchers are deeply divided — some (LeCun) argue current architectures cannot reach AGI and fundamental breakthroughs are needed; others (Altman, Hinton, Bengio) believe AGI could arrive within years to decades. Transformative AI / HLMI: some researchers prefer the term 'transformative AI' (would transform society as much as the Industrial Revolution) as more tractable than AGI. The distinction matters for safety: narrow AI poses mainly misuse risks; AGI could pose alignment risks if it pursues goals misaligned with human values."),
]

AI = AI[:200]
write("aa", AI)

print("\n=== Part 4 complete ===")
for up in ["v", "w", "x", "y", "z", "aa"]:
    p = DATA_DIR / f"upgrade_{up}.jsonl"
    count = sum(1 for _ in open(p))
    print(f"  upgrade_{up}: {count} examples")
