#!/usr/bin/env python3
"""gen_f_fill11.py -- final push upgrade_f past 1000 cyber pairs"""
import json, pathlib

OUT = pathlib.Path('/workspace/data_upgrades/upgrade_f.jsonl')
OUT.parent.mkdir(parents=True, exist_ok=True)

pairs = []
def p(q, a):
    pairs.append((q, a))

# Short but complete cyber Q&A pairs -- 420 target

p("What is the difference between black-box, grey-box, and white-box testing?",
  "Black-box: tester has no prior knowledge of system internals; simulates external attacker; tests from user perspective only; finds externally discoverable vulnerabilities; slower; realistic attacker simulation; misses issues only visible with code access. Grey-box: partial knowledge (architecture diagrams, limited credentials, API documentation); balances realism with efficiency; faster than black-box; finds more issues than pure black-box; most common for web application testing. White-box: full knowledge (source code, architecture, credentials, network diagrams); most comprehensive; finds issues missed in black/grey-box (insecure crypto in code, business logic in code, hardcoded secrets); slowest; code review included; also called crystal-box or glass-box. When to use each: external penetration test simulating real attacker: black-box; time-efficient internal assessment: grey-box; secure SDLC pre-deployment review: white-box; compliance-driven code review: white-box; red team engagement: black-box or grey-box depending on scenario.")

p("What is malware analysis and what are the phases?",
  "Malware analysis: studying malicious software to understand its functionality, origin, and impact. Safety: ALWAYS analyse in isolated VM (VMware or VirtualBox with snapshots; no host-to-VM shared folders; no network or NAT to isolated/dummy network; no copy-paste clipboard sharing); use FlareVM (Windows-based malware analysis distro) or Remnux (Linux). Phases: (1) Static analysis (basic): extract file metadata: file, strings, MD5/SHA256 hash; check hash on VirusTotal; PE header analysis (pefile library or PEiD): import table (which DLLs and functions imported -- reveals capabilities: ws2_32.dll = network; crypt32.dll = crypto; advapi32 registry = persistence); sections (unusual section names, high entropy sections = packed/encrypted code). (2) Dynamic analysis: run in sandbox; Cuckoo Sandbox or ANY.RUN or Hybrid Analysis online; observe: processes created, network connections, files created/modified, registry changes, loaded DLLs; ProcMon, Process Hacker, Wireshark during execution. (3) Static analysis (advanced): disassembly and decompilation in IDA Pro or Ghidra; reverse engineer algorithms; identify obfuscation (XOR encryption keys; base64 decoded strings); extract IoCs (hardcoded C2 domains, IPs, file paths, registry keys). (4) Code analysis: identify C2 protocol; persistence mechanism; evasion techniques (anti-debug, anti-VM, anti-sandbox checks: CPUID, timing, mouse movement); decrypt strings; extract config (C2 address, sleep time, encryption key). Tools: FLOSS (FireEye: automated obfuscated string extraction); YARA (write signatures from analysis); yarGen (auto-generate YARA from unique strings).")

p("What is network traffic analysis?",
  "Network traffic analysis (NTA): monitoring and analysing network communications to detect threats, anomalies, and policy violations. Approaches: Full packet capture (PCAP): capture all packets including payload; Wireshark, tcpdump; high storage requirements; maximum visibility; decrypt TLS with session keys. NetFlow/IPFIX: metadata only (source IP, destination IP, port, protocol, bytes, duration); no payload; lower storage (100x less than PCAP); sufficient for many detections; supported by all routers and switches. DNS logs: every DNS query reveals what hosts are communicating with; high value for threat detection; Zeek dns.log. Threat detection via NTA: lateral movement: unusual SMB (port 445) or WMI (135/EPM) between workstations; beaconing: regular interval connections to external IP (consistent timing, specific interval = C2 beacon); data exfiltration: large outbound transfers at unusual times; DNS tunneling: high volume of long subdomain queries to single domain; brute force: many connections to port 22, 3389, 445 with connection failures; port scanning: one source IP connecting to many destination ports; malware propagation: infection spreading (high SYN rate to internal IPs = worm). Tools: Zeek (Bro): generates structured logs from packets; rich protocol parsers; scriptable; produces conn.log, http.log, dns.log, ssl.log, files.log; essential for security analytics. Suricata: IDS signatures on live traffic or PCAP. RITA (Real Intelligence Threat Analytics): analyses Zeek logs; specifically detects beaconing (statistical analysis of connection intervals), long connections, DNS tunneling. Arkime (formerly Moloch): full packet capture and search; web UI; PCAP indexed and searchable. NetworkMiner: Windows-based; passive network sniffer; extracts files, credentials, hosts from PCAP.")

p("What is a honeypot and how does it work?",
  "Honeypot: decoy system or resource designed to attract attackers; generates alerts when accessed (only attackers interact; no legitimate use); valuable threat intelligence and early warning. Types: Low-interaction: simulates limited services; limited functionality; records connections; examples: OpenSSH server that logs logins but does not allow real login; Honeyd simulates many hosts; lower risk of attacker using as pivot. High-interaction: real operating system and services; full interaction; maximum intelligence gathered (attacker TTPs, tools, targets); higher risk (attacker may use to attack others); requires containment (network isolation). HoneyTokens: fake credentials, files, or records embedded in real environment; access triggers alert; examples: canarytoken (Canary Tokens: fake AWS credentials in fake configuration file; used anywhere = DNS lookup to token server = alert), fake Active Directory service account with no real access (any login attempt = alert; rarely false positive), fake database records (if queried by application = data breach indicator), fake user in LDAP directory. HoneyFiles: files with audit SACL (Security Access Control List); any read triggers Windows Event 4663; placed in sensitive directories; ransomware will encrypt them early = ransomware alert before extensive damage. Production vs Research: production honeypots protect real networks; deployed inside corporate network alongside real servers; research honeypots gather threat intelligence; isolated; publicly accessible; study attack techniques. Deployment: isolated VLAN with internet access but no internal network access; all outbound connections monitored; containment prevents pivot. Examples: SSH honeypots: Cowrie (logs all commands, file downloads, credentials attempted); telnet honeypots; web application honeypots (Glastopf); database honeypots (fake MySQL listening on 3306); ICS honeypots (Conpot simulates PLCs). Value: detect scanners and opportunistic attackers; get early warning of targeted attacks; gather malware samples; study attacker techniques.")

p("What is the NIST Cybersecurity Framework?",
  "NIST CSF (Cybersecurity Framework): voluntary framework for managing cybersecurity risk; developed with industry in 2014; widely adopted by US government and private sector; version 2.0 released 2024. Core functions (CSF 1.1): IDENTIFY: understand organisation assets, risks, and governance; asset management, business environment, governance, risk assessment, risk management strategy. PROTECT: implement safeguards; access control, awareness and training, data security, information protection, maintenance, protective technology. DETECT: identify cybersecurity events; anomalies and events, continuous monitoring, detection processes. RESPOND: take action on detected events; response planning, communications, analysis, mitigation, improvements. RECOVER: restore capabilities; recovery planning, improvements, communications. CSF 2.0 adds GOVERN function: establish organisational cybersecurity risk management strategy, expectations, and policy; overarches all other functions. Implementation tiers: Tier 1 Partial: ad hoc, reactive; no formal risk management process. Tier 2 Risk Informed: risk management practices approved by management; not organisation-wide. Tier 3 Repeatable: formal policies in place; organisation-wide processes. Tier 4 Adaptive: continuous improvement; advanced threat awareness. Profiles: Current Profile (as-is state) vs Target Profile (desired state); gap analysis identifies improvement priorities. Use cases: structure cybersecurity program; communicate risk to executives; align with other frameworks (ISO 27001, CIS Controls, COBIT); vendor risk assessment; regulatory compliance basis (DoD CMMC, HIPAA, PCI DSS all map to CSF). Adoption: executive order 13800 (May 2017) required federal agencies to use CSF; 30% of US organisations use CSF; internationally recognised though not mandatory.")

p("What is the CIS Critical Security Controls?",
  "CIS Controls (Center for Internet Security Critical Security Controls): prioritised set of defensive actions to prevent most common cyber attacks; originally developed from NSA analysis of most effective attack prevention measures; version 8 released 2021. Three implementation groups: IG1 (Essential Cyber Hygiene): minimum standard for all organisations; 56 safeguards; for small organisations with limited IT resources; prevents most common attacks. IG2 (next priority): 74 additional safeguards; for organisations with dedicated IT staff; handles more sophisticated attacks. IG3 (comprehensive): all 153 safeguards; large enterprise; sophisticated adversaries; mature security programme. 18 Controls: CIS 1: Inventory and Control of Enterprise Assets; CIS 2: Inventory and Control of Software Assets; CIS 3: Data Protection; CIS 4: Secure Configuration of Enterprise Assets and Software; CIS 5: Account Management; CIS 6: Access Control Management; CIS 7: Continuous Vulnerability Management; CIS 8: Audit Log Management; CIS 9: Email and Web Browser Protections; CIS 10: Malware Defenses; CIS 11: Data Recovery; CIS 12: Network Infrastructure Management; CIS 13: Network Monitoring and Defense; CIS 14: Security Awareness and Skills Training; CIS 15: Service Provider Management; CIS 16: Application Software Security; CIS 17: Incident Response Management; CIS 18: Penetration Testing. Why effective: based on actual attack data; prioritised by impact; actionable (specific technical safeguards not vague guidelines); mapped to MITRE ATT&CK, NIST CSF, ISO 27001; CIS Benchmarks (hardening guides for OS, cloud, network devices) complement Controls. Comparison to NIST CSF: NIST CSF = risk management framework (what to do); CIS Controls = prescriptive technical controls (how to do it); complementary; CIS Controls mapped to CSF functions; organisations use CSF for strategy, CIS Controls for implementation.")

p("What is ISO 27001 and how does certification work?",
  "ISO 27001: international standard for Information Security Management Systems (ISMS); published by ISO (International Organisation for Standardisation) and IEC; latest version: ISO 27001:2022; globally recognised; provides framework for managing information security risks. ISMS: systematic approach to managing sensitive company information; includes people, processes, and IT systems; risk-based approach rather than prescriptive technical controls. Structure: 93 controls organised in 4 themes (2022 update from 14 domains): Organisational controls (37); People controls (8); Physical controls (14); Technological controls (34). Annex A: normative reference listing all 93 controls; organisations select controls based on risk assessment; Statement of Applicability (SoA) documents which controls implemented and justification for exclusions. Key requirements: context (understand organisation and interested parties); leadership (management commitment; ISMS scope; information security policy); planning (risk assessment and treatment; objectives); support (resources; competence; awareness; communication; documented information); operation (risk treatment plan; controls implementation); performance evaluation (monitoring; internal audit; management review); improvement (nonconformity; corrective action; continual improvement). Certification process: (1) Gap analysis against ISO 27001 requirements; (2) Implement ISMS controls; (3) Stage 1 audit: documentation review by accredited certification body; (4) Stage 2 audit: on-site assessment of implementation; (5) Certificate issued (3-year validity); (6) Surveillance audits annually; (7) Recertification audit every 3 years. Accreditation bodies: UKAS (UK), DAkkS (Germany), ANAB (USA); certification bodies: BSI, Bureau Veritas, Intertek, LRQA, SGS. Benefits: customer trust; regulatory compliance basis (GDPR alignment); contractual requirement from enterprise customers; structured risk management; competitive advantage in B2B.")

p("What is PCI DSS and who needs to comply?",
  "PCI DSS (Payment Card Industry Data Security Standard): information security standard for organisations handling credit card data; developed by PCI Security Standards Council (Visa, Mastercard, Amex, Discover, JCB); version 4.0 released March 2022; non-compliance = fines, increased transaction fees, card brand termination. Who must comply: any organisation that stores, processes, or transmits cardholder data (CHD); CHD: primary account number (PAN), cardholder name, expiry date, service code; sensitive authentication data (SAD): full track data, CVV/CVC, PINs. Merchant levels based on transaction volume: Level 1 (>6M transactions/year): annual Report on Compliance (ROC) by Qualified Security Assessor (QSA); quarterly network scans. Level 2 (1-6M): annual Self-Assessment Questionnaire (SAQ); quarterly scans. Levels 3 and 4 (smaller merchants): SAQ; quarterly scans. 12 Requirements (v3.2.1): Build and maintain secure network (firewalls; no vendor defaults); Protect cardholder data (encryption; key management); Vulnerability management (antivirus; patch management); Strong access control (need-to-know; unique IDs; no sharing credentials; physical access control); Monitor and test (logging; intrusion detection; pen testing); Maintain information security policy. Key v4.0 changes: customised approach (alternative to prescriptive controls if equivalent security demonstrated); targeted risk analysis (assess individual controls based on risk); MFA required for all CDE access (not just remote); password complexity increased (12+ characters); automated threat detection for payment pages; software security requirements updated. Scope reduction: isolate cardholder data environment (CDE); reduce scope by minimising where CHD exists; tokenisation (replace PAN with token in non-CDE systems); P2PE (point-to-point encryption): CHD encrypted from point of interaction to processor; scope dramatically reduced. Penetration testing requirement: PCI DSS 11.4: annual penetration test on CDE; after significant infrastructure changes; segmentation pen test verifying CDE isolation.")

p("What is GDPR and what are the security implications?",
  "GDPR (General Data Protection Regulation): EU regulation (2018) governing personal data of EU residents; extraterritorial scope (any organisation handling EU resident data regardless of location); significant security implications and breach notification requirements. Security-relevant requirements: Article 25 Data Protection by Design and Default: integrate data protection from system design; privacy-preserving architecture; minimum necessary data collection; default privacy settings most protective. Article 32 Security of Processing: implement appropriate technical and organisational measures; risk-appropriate security; encryption, pseudonymisation; confidentiality, integrity, availability, resilience; regular testing (penetration testing, vulnerability scanning); business continuity and recovery. Article 33 Breach Notification to Supervisory Authority: notify within 72 hours of becoming aware of personal data breach; if notification delayed beyond 72h: reason required; notification includes: nature of breach, categories and approximate number of data subjects affected, likely consequences, measures taken/proposed. Article 34 Communication to Data Subjects: if breach likely to result in high risk to individuals: must notify affected individuals without undue delay; exemptions: encrypted data (key not compromised); subsequent measures ensure high risk no longer likely. Fines: tier 1 (less severe): up to 10M EUR or 2% global annual turnover (whichever higher); tier 2 (more severe, including Article 32 security failures): up to 20M EUR or 4% global annual turnover. Notable fines: British Airways (2020, data breach): initially 183M GBP reduced to 20M GBP; Marriott (data breach): initially 99M GBP reduced to 18.4M GBP; Meta (2023): 1.2B EUR for data transfers to US; DPDP (India) and various national laws follow GDPR model globally. Practical security implications: encryption at rest and transit required; access control logs required; DPA (Data Protection Authority) may audit security measures; DPIA (Data Protection Impact Assessment) required for high-risk processing; Article 17 right to erasure requires data deletion capability (impacts backup strategy and database design).")

p("What are cloud security best practices for AWS?",
  "AWS security best practices across key domains: Identity: root account: MFA required; no programmatic access; used only for initial setup; create admin IAM user instead; IAM policies: least privilege; explicit deny for sensitive actions; avoid wildcard (*) actions and resources; use IAM roles for EC2/Lambda (no access keys in code); rotate access keys every 90 days; CloudTrail records all API calls for accountability. Network: VPC (Virtual Private Cloud): private subnets for databases and backend services; public subnets only for load balancers; NACLs and Security Groups in layers (Security Groups: instance-level; NACLs: subnet-level); Security Group rules: specific IPs not 0.0.0.0/0; no 0.0.0.0/0 for port 22 or 3389; VPC endpoints for S3 and DynamoDB (traffic stays on AWS network; no internet); AWS WAF on CloudFront and ALB. Compute: EC2: Systems Manager Session Manager instead of SSH/RDP (no port 22/3389 exposed; no bastion host required); IMDSv2 mandatory (prevents SSRF to metadata); latest AMI with patches; patch management via Systems Manager Patch Manager. Storage: S3: Block Public Access (account level AND bucket level); bucket policies requiring HTTPS (aws:SecureTransport); versioning for accidental deletion; S3 Object Lock for ransomware protection (WORM); S3 server-side encryption (SSE-S3 or SSE-KMS); access logging; Macie for sensitive data discovery. Logging and monitoring: CloudTrail: enable in all regions; CloudWatch Logs for application logging; GuardDuty: threat detection service analysing CloudTrail, VPC Flow Logs, DNS logs; findings for: unusual API calls, crypto mining, C2 communication, credential compromise; Security Hub: aggregate findings from GuardDuty, Inspector, Macie, Trusted Advisor; AWS Config: compliance checking (is MFA enabled? Are S3 buckets public? Are Security Groups too permissive?); EventBridge + Lambda for automated remediation. Encryption: KMS CMK for all encryption; CloudHSM for highest security requirements; Secrets Manager for database credentials with auto-rotation.")

p("What is DevSecOps and how do you implement it?",
  "DevSecOps: integrating security into DevOps practices; security as code; shift-left security (find issues earlier in SDLC when cheaper to fix); everyone responsible for security (not just security team). Why shift left: security bug found in design: costs 1x to fix; in development: 10x; in testing: 100x; in production: 1000x (cost of breach, remediation, regulatory fine, reputation). DevSecOps pipeline integration: Pre-commit hooks: detect-secrets (block committing API keys, passwords); gitleaks; talisman; run fast security checks before commit accepted. Code (SAST -- Static Application Security Testing): Semgrep (fast, accurate, open-source); CodeQL (GitHub; complex data flow analysis); SonarQube (comprehensive; technical debt tracking); Checkmarx, Veracode (commercial); scan for: SQL injection patterns, insecure crypto, hardcoded credentials, XSS. Build (SCA -- Software Composition Analysis): Snyk (open source, container, IaC scanning; most popular); Dependabot (GitHub native; auto-PRs for vulnerable dependencies); OWASP Dependency-Check (free); Black Duck (commercial); scan all dependencies for known CVEs; SBOM generation. Test (DAST -- Dynamic Application Security Testing): OWASP ZAP in CI/CD (docker run zaproxy/zap-stable zap-baseline.py); Nuclei (fast template-based scanner); DAST runs against deployed test environment; blocks deployment if Critical/High findings. Container security: Trivy (fast, comprehensive; scans images in seconds); Snyk Container; Grype; integrate in CI/CD before push to registry. Infrastructure as Code security: Checkov (Terraform, CloudFormation, Kubernetes YAML); tfsec (Terraform); kube-score (Kubernetes). Deployment: immutable infrastructure (no manual changes; rebuild from IaC; eliminates configuration drift); feature flags (disable vulnerable features without redeployment). Production: runtime security (Falco for container/Kubernetes runtime threat detection); continuous vulnerability management; DAST against production periodically; bug bounty program. Culture: security champions in development teams; security training for developers; blameless postmortems; security as enabler not gatekeeper.")

p("What is log management and SIEM tuning?",
  "Log management and SIEM tuning: critical for effective security monitoring; balance between detection coverage and alert fatigue. Log sources priority: Tier 1 (critical): authentication logs (AD/Okta/Azure AD); endpoint security (EDR alerts); firewall/proxy; DNS; email gateway; privileged access (PAM). Tier 2 (important): application logs; VPN; network flow; cloud API logs (CloudTrail). Tier 3 (supplementary): physical access; application debug logs (very noisy). Log volume estimation: Windows Event Log on DC: 500-5000 events/minute; firewall: 10,000-100,000 events/minute; proxy: 50,000+ events/minute; size all storage appropriately; retention: security events: 1 year minimum (PCI DSS 3.2.1: 1 year; GDPR: as long as needed; some regulations 7 years). SIEM tuning process: start with high-fidelity alerts only; enable rules one at a time; measure: how many alerts per day? False positive rate? Analyst capacity (average 15-20 alerts per analyst per day); tune aggressive rules: add exceptions for known-good (backup servers triggering port scan rules; vulnerability scanner IP excluded from brute force rules); add context (asset criticality, user role, location). Alert quality metrics: precision = true positives / (true positives + false positives); recall = true positives / (true positives + false negatives); acceptable: precision > 60% for alerts requiring investigation; precision > 90% for auto-blocking rules. Common false positives to tune: vulnerability scanner triggering web attack rules (whitelist scanner IP); backup jobs triggering large file transfer rules (exclude backup server); HR system triggering account creation rules (exclude HR system account); pen test triggering everything (track pen test windows and exclude or expect). Correlation rules: start with MITRE ATT&CK technique detections; build from simple to complex; example: T1003 credential dumping: lsass.exe access by non-system process; tune: exclude Defender, Sophos processes; alert on truly unexpected processes. Use case library: Splunk Security Essentials; Microsoft Sentinel Fusion; Elastic SIEM detection rules; Sigma rules (open-source community-maintained detection rules convertible to any SIEM query language).")

p("How do you perform password auditing in Active Directory?",
  "AD password auditing: assess password quality and identify weak or compromised credentials. Extract hashes (requires Domain Admin or DCSync rights): Impacket secretsdump.py: secretsdump.py domain/admin:pass@DC01 (dumps NTDS.dit via DCSync); or offline: ntdsutil snapshot to extract NTDS.dit + SYSTEM registry hive; secretsdump.py -ntds ntds.dit -system SYSTEM LOCAL. Hash format: username:RID:LM_HASH:NT_HASH::: (NT hash is what gets cracked). Cracking with Hashcat: hashcat -m 1000 ntds.txt rockyou.txt (mode 1000 = NTLM); rules: hashcat -m 1000 ntds.txt rockyou.txt -r rules/best64.rule; combination: hashcat -m 1000 ntds.txt -a 1 wordlist1.txt wordlist2.txt; mask attack (pattern-based): hashcat -m 1000 ntds.txt -a 3 Company?d?d?d?d (Company + 4 digits = common corporate pattern); incremental: -a 3 ?a?a?a?a?a?a?a?a (all 8-char combinations -- very slow). Credential hygiene analysis: DSInternals PowerShell module: Get-ADReplAccount (enumerate accounts); Test-PasswordQuality: Find-WeakPasswordList, Find-DuplicatePasswordGroups (multiple accounts with same password), Find-EmptyPasswordAccounts, Find-SmartCardBypassAccounts; compare against HaveIBeenPwned breach corpus (100B+ leaked passwords); export NT hashes; compare to NTLM hashes from HIBP. NTLM hash comparison: not sending passwords to HIBP; HIBP has NTLM hash format too; download HIBP password list NTLM version; sort; compare with fgrep or PowerShell; identify breached passwords even if complex. Reporting: percentage cracked; common password patterns found; accounts using breached passwords; accounts with same password as another account; accounts with passwords matching username; accounts not changed > 1 year; service account password age. Tooling alternatives: Netwrix Password Policy Enforcer; Specops Password Auditor (free version audits against HIBP); Purple Knight (free AD security assessment including password findings).")

p("What is web cache poisoning?",
  "Web cache poisoning: attacker manipulates HTTP cache to store malicious response that gets served to other users. How caches work: CDNs and reverse proxies (Varnish, Nginx) cache responses; cache key = request attributes that determine uniqueness (typically URL + Host header); cached response served to all users with matching cache key. Cache poisoning: if cache includes request data not in cache key in response: attacker sends request with malicious header value; response includes attacker header value (reflected); response cached because only URL and Host in cache key; other users requesting same URL get cached malicious response. Example: site reflects X-Forwarded-Host: header in response: Location: https://X-FORWARDED-HOST-VALUE/redirect; cache key only includes URL; attacker sends X-Forwarded-Host: attacker.com; response cached; all users get redirect to attacker.com (XSS, phishing). Techniques: (1) Unkeyed headers: X-Forwarded-Host, X-Original-URL, X-Rewrite-URL, X-Forwarded-Port reflected but not in cache key. (2) Unkeyed query parameters: ?utm_campaign=value reflected in response but utm_ parameters excluded from cache key (fat GET parameters); inject ?utm_campaign=<script>alert(1)</script> -- cached and served to others. (3) HTTP request smuggling + cache poisoning: smuggle request that poisons cache with malicious response. (4) Response splitting (historical): inject CRLF into cached URL; add second response with malicious content. (5) Fat GET: send parameters in GET body (some frameworks process both); cache only considers URL (no body). Detection: Param Miner (Burp extension): discovers unkeyed headers and parameters; automated cache poisoning detection. Defences: normalise and validate headers before including in responses; include all input-influencing-output in cache key (Vary header); purge cache on security incidents; use CSP to limit XSS impact; Cloudflare and Akamai have built-in cache poisoning protections.")

p("What is HTTP request smuggling?",
  "HTTP request smuggling (HRS): attack exploiting discrepancy between how front-end and back-end servers parse HTTP request boundaries; attacker smuggles hidden request inside legitimate request body. Background: HTTP/1.1 has two headers for body length: Content-Length (CL): exact byte count; Transfer-Encoding: chunked (TE): chunked encoding with 0-length terminator. Conflict: if front-end uses CL and back-end uses TE (CL.TE vulnerability): front-end forwards based on CL; back-end reads chunked until 0 chunk; data after 0 chunk = start of next request from back-end perspective; attacker can prefix next legitimate user request with attacker-controlled data. Attack types: CL.TE: front-end uses Content-Length; back-end uses Transfer-Encoding. TE.CL: front-end uses Transfer-Encoding; back-end uses Content-Length. TE.TE: both use Transfer-Encoding but one can be confused with obfuscated TE header: Transfer-Encoding: xchunked or Transfer-Encoding[space]: chunked (obfuscated values). Impact: bypass front-end security controls (WAF sees legitimate request; back-end processes smuggled malicious request): access restricted URLs; bypass authentication; poison next user request (prepend to next user HTTP request; capture their credentials or session cookie); XSS via smuggling to force victim request through attacker-controlled prefix. Detection: HTTP Request Smuggler (Burp extension by James Kettle): automated detection; timing-based detection (CL.TE: back-end hangs waiting for complete chunk = time delay). Exploitation: send smuggled request; observe response timing and content differences; intercept victim requests by making back-end buffer part of victim request in attacker-controlled response. HTTP/2: introduced to eliminate request smuggling (binary framing with explicit length); but HTTP/2 downgrade to HTTP/1.1 at back-end reintroduces issue; H2.CL and H2.TE attacks exist. Mitigation: disable HTTP request reuse (pipeline) between front-end and back-end; ensure front-end and back-end agree on parsing; upgrade to HTTP/2 end-to-end; reject ambiguous requests (both CL and TE headers); normalise TE header handling.")

p("What are access control models used in operating systems?",
  "Access control models: DAC (Discretionary Access Control): resource owner decides who can access; standard Unix/Windows file permissions (owner sets rwx); flexible but relies on owner making good decisions; a compromised owner account grants attacker owner permissions; traditional Unix and Windows NTFS permissions use DAC. MAC (Mandatory Access Control): system enforces access based on labels/classifications; owner cannot override; Bell-LaPadula model: no read up (cannot read higher classification), no write down (cannot write to lower classification = prevents data leakage from high to low); used in military/government (classified/unclassified/secret/top secret); Linux SELinux and AppArmor are MAC implementations (though simpler than traditional MAC). RBAC (Role-Based Access Control): permissions assigned to roles; users assigned roles; user does not directly hold permissions; most common enterprise model; admin role has admin permissions; user role has user permissions; separation of duties (accounting role cannot approve own payments); AWS IAM, Azure RBAC, Active Directory groups all implement RBAC. ABAC (Attribute-Based Access Control): policy evaluated based on attributes: subject attributes (user.department = Finance, user.clearance = Secret); resource attributes (document.classification = Confidential, document.owner = HR); environmental attributes (time of day, IP location, device compliance); very fine-grained; XACML (eXtensible Access Control Markup Language) standard; more complex to implement than RBAC; AWS IAM conditions implement subset of ABAC. ReBAC (Relationship-Based Access Control): permissions based on relationship between user and resource; Google Zanzibar (paper 2019) implements ReBAC for Google Drive and Docs; user has access to document if they own it or if they are member of group that has access; natural for hierarchical access (folder access grants file access); OpenFGA (open-source Zanzibar implementation), SpiceDB, Warrant. Zero Trust applies attribute-based policy to network access in addition to data access.")

p("What is identity governance and administration (IGA)?",
  "IGA (Identity Governance and Administration): framework and processes for managing digital identities and their access rights throughout lifecycle; ensures right people have right access to right resources at right time. Components: IGA platform: centralised visibility of all identities (employees, contractors, service accounts) and their access across all systems; SailPoint, Saviynt, One Identity Manager, Microsoft Identity Governance. Access lifecycle management: Joiner: when employee joins, provision access based on role (HR triggers; manager approves; automatic provisioning to AD, Salesforce, Jira, GitHub, etc.); Mover: when employee changes role or department, remove inappropriate access (access creep prevention), grant new role access; Leaver: when employee leaves, deprovision all access immediately (offboarding automation critical; compromised ex-employee accounts common attack vector). Access certification (recertification): periodic review of who has access to what; manager certifies each of their reports access is still needed; certify privileged accounts quarterly; certify standard accounts semi-annually or annually; remove uncertified access; compliance requirement (SOX, PCI DSS, HIPAA). SoD (Separation of Duties): prevent single individual from having conflicting permissions (accounts payable and accounts receivable; code developer and code approver); SoD rules defined in IGA; conflicts flagged and either prevented or require compensating control; SOX compliance requirement. Role management: role mining (discover what access patterns exist; create roles from actual access); role engineering (design roles from business process perspective); role explosion problem (too many granular roles become unmaintainable). Privileged access governance: track privileged account holders; certify privileged access more frequently; integrate with PAM (Privileged Access Management -- CyberArk, BeyondTrust); just-in-time access (access granted for limited time, then revoked). Analytics: access risk scoring; anomaly detection (user access pattern differs from peers); orphan accounts (accounts with no owner); dormant accounts (no login in 90 days).")

p("What is the CVSS 3.1 scoring system in detail?",
  "CVSS 3.1 (Common Vulnerability Scoring System version 3.1): industry standard for rating vulnerability severity; base score 0-10; three metric groups. Base Score Metrics (mandatory): Attack Vector (AV): Network (N) score 0.85 -- exploitable remotely over internet; Adjacent (A) 0.62 -- same network segment (LAN, Bluetooth); Local (L) 0.55 -- attacker needs local account or physical access; Physical (P) 0.2 -- requires physical access to device. Attack Complexity (AC): Low (L) 0.77 -- attack reproducible reliably; High (H) 0.44 -- specific conditions, race condition, or information gathering needed before exploit. Privileges Required (PR): None (N) 0.85 -- no auth needed; Low (L) 0.62 -- regular user; High (H) 0.5 -- admin. Scope Unchanged: Low (L) 0.68 -- admin. User Interaction (UI): None (N) 0.85 -- no user action; Required (R) 0.62 -- victim must click, open file, etc. Scope (S): Changed (C) -- impact extends beyond vulnerable component; Unchanged (U) -- contained to vulnerable component. Confidentiality/Integrity/Availability Impact: None (N) 0; Low (L) 0.22; High (H) 0.56. Score calculation: ISS = 1 - (1-Conf) * (1-Integ) * (1-Avail); Scope Unchanged: Impact = 6.42 * ISS; Scope Changed: Impact = 7.52 * (ISS - 0.029) - 3.25 * (ISS - 0.02)^15; Exploitability = 8.22 * AV * AC * PR * UI; Base score = Roundup(min((Impact+Exploitability),10)) if Impact > 0 else 0. Temporal metrics (optional): Exploit Code Maturity (E): unproven, proof-of-concept, functional, high; Remediation Level (RL): official-fix, temporary-fix, workaround, unavailable; Report Confidence (RC): unknown, reasonable, confirmed; multiply base by factors < 1.0 to reduce temporal score when no PoC exists or official patch available. Environmental metrics: modify base metrics for organisation context; Confidentiality/Integrity/Availability Requirement: Low/Medium/High based on asset importance to organisation; highly confidential data = CR:High increases effective confidentiality score impact. CVSS 4.0 (2023): CVSS v4 adds attack requirements metric and supplemental metrics; finer granularity; not yet widely adopted.")

p("How does memory forensics work?",
  "Memory forensics: analysis of volatile computer memory (RAM) to extract forensic artefacts; critical for investigating fileless malware, process injection, and encryption keys. Why memory: fileless malware exists only in RAM (no disk artefacts); encryption keys reside in memory; running processes, network connections captured at point in time; decrypt encrypted evidence (VeraCrypt volumes mounted = master key in memory). Acquisition: full physical memory dump without rebooting system; Windows: WinPmem (open source): winpmem -o memory.raw; FTK Imager (Live Acquisition): create memory dump; Dumpit (single executable): magnet tool; LiME (Linux Memory Extractor): kernel module: insmod lime.ko path=/mnt/usb/memory.lime format=lime; Hibernation file (hiberfil.sys): compressed memory dump from Windows hibernate; Crash dump (%SystemRoot%\MEMORY.DMP): partial or full memory dump from Blue Screen. Analysis with Volatility (3): volatility3 -f memory.raw windows.pslist (list processes; look for suspicious names or parent-child anomalies); windows.cmdline (command lines for each process; malware command line); windows.dlllist -p PID (DLLs loaded in process); windows.netscan (network connections from memory; find C2); windows.malfind (find injected code: pages with execute permission that are not backed by file; suspicious memory sections); windows.handles -p PID (open handles: files, registry keys, mutex -- mutex often unique per malware family). Artefacts: credentials: mimikatz sekurlsa::logonpasswords reads same LSASS memory; volatility windows.lsadump or mimikatz on memory dump extracts NTLM hashes, Kerberos tickets; encryption keys: AES keys, VeraCrypt master keys, BitLocker VMK; for VeraCrypt: open vmk finder or bsodv; Kerberos tickets (pass-the-ticket); clipboard contents; browser history and passwords (Chrome stores in memory before writing to disk); deleted registry keys still in memory if not evicted. Yara scanning memory: volatility windows.yarascan -y malware.yar (scan all process memory for YARA rules; detect malware even if never written to disk).")

p("What is a public key certificate and how does TLS use it?",
  "X.509 public key certificate: digitally signed document binding public key to identity; issued by Certificate Authority (CA); used in TLS, S/MIME, code signing. Certificate fields: Version (v3); Serial Number (unique per CA); Signature Algorithm (sha256WithRSAEncryption; sha384WithECDSA); Issuer (CA name: CN=DigiCert Global Root CA, O=DigiCert Inc, C=US); Validity (Not Before, Not After dates); Subject (entity identified: CN=www.example.com, O=Example Corp); Subject Public Key Info (RSA/EC public key); Extensions: Subject Alternative Names (SANs: additional domains/IPs; modern certificates use SAN not Subject CN for domain names); Basic Constraints (CA:TRUE = CA certificate, CA:FALSE = leaf); Key Usage (Digital Signature, Key Encipherment); Extended Key Usage (serverAuth, clientAuth, codeSigning, emailProtection). TLS 1.3 handshake: (1) Client Hello: supported cipher suites (TLS_AES_256_GCM_SHA384); TLS version 1.3; client random; key_share (ECDH public key for key exchange). (2) Server Hello: chosen cipher suite; server random; key_share (server ECDH public key); Certificate (server certificate chain); CertificateVerify (signature over handshake with server private key -- proves possession of private key); Finished (HMAC of handshake messages). (3) Client validates: certificate signature by CA (verify certificate chain); certificate not expired; certificate not revoked (OCSP); CN/SAN matches hostname (FQDN match); CertificateVerify signature valid (server has private key matching certificate public key); derives session keys from ECDH (Elliptic Curve Diffie-Hellman: key exchange without transmitting key); Finished (client Finished MAC). All subsequent data encrypted with session keys (AES-GCM or ChaCha20-Poly1305 AEAD). Perfect Forward Secrecy: TLS 1.3 mandates ephemeral ECDH key exchange; session key not derived from long-term private key; past sessions safe even if private key later compromised; TLS 1.2 allowed non-PFS RSA key exchange (deprecated).")

p("What is certificate transparency and why does it matter for security?",
  "Certificate Transparency (CT): RFC 6962 standard requiring all publicly-trusted TLS certificates to be logged in publicly auditable CT logs before browsers will accept them. Why needed: CA compromises (DigiNotar 2011: Iranian government used compromised Dutch CA to issue fake Google certificate; SSL interception of Iranian users); rogue certificates issued by mis-operating CAs; fraudulent certificate issuance targeting banks, governments; without CT: certificate issuance invisible to domain owner. How CT works: CA submits precertificate to CT logs before issuing; CT log returns Signed Certificate Timestamp (SCT); SCT embedded in final certificate; browsers check SCT presence and validity; SCT proves certificate logged before issuance. CT log properties: append-only Merkle tree; cannot delete or modify logged certificates; log operators: Google, Cloudflare, DigiCert, Sectigo; IETF RFC 9162 (updated CT v2). Monitoring: domain owners monitor CT logs for certificates issued for their domains; new certificate issuance alert = detect unauthorized certificate; crt.sh (search CT logs: crt.sh/?q=example.com -- shows all certificates ever issued for domain and subdomains); Cert Spotter (SSLMate: monitor CT logs for your domain); Certificate Search API. Security uses: attack reconnaissance: crt.sh reveals all subdomains ever issued certificates = subdomain enumeration without DNS brute force; discover forgotten development or staging servers; attackers also monitor for high-value targets (Google, Apple, banks) certificate issuance as attack timing signal; phishing detection: monitor for certificates issued for typosquat domains (paypa1.com, googl3.com -- CT logs reveal phishing infrastructure being stood up before attack launches). CAA (Certification Authority Authorisation) DNS record: specifies which CAs allowed to issue for domain; mitigates rogue CA issuance; example: example.com. CAA 0 issue digicert.com; blocks all other CAs from issuing even if compromised; not CT but complementary control.")

p("What is multi-factor authentication and what are the types?",
  "MFA (Multi-Factor Authentication): authentication using two or more factors from different categories: something you know (password, PIN), something you have (hardware token, phone, smart card), something you are (fingerprint, face, iris). Knowledge factors: password; PIN; security questions (weak -- guessable, phishable, breach-exposed; avoid for critical accounts); passphrase. Possession factors: TOTP (Time-based One-Time Password, RFC 6238): shared secret generates 6-digit code every 30 seconds; Google Authenticator, Authy, Microsoft Authenticator; symmetric secret stored both server and device = phishable (code valid 30s -- attacker relays real-time); HOTP (HMAC-based OTP): counter-based; increments per use; YubiKey OTP mode. SMS OTP: OTP delivered via SMS; vulnerable to SIM swap; SS7 interception; phone number porting; US government deprecated SMS OTP recommendation; avoid for high-security accounts; phishable. Push notifications: auth app sends push to phone; tap approve; Duo Security; Microsoft Authenticator; can be abused (MFA fatigue attack: flood target with push notifications until they accidentally approve; Uber breach 2022 via MFA fatigue). Hardware security keys (FIDO2/WebAuthn): YubiKey, Google Titan Key; public-key cryptography; phishing-resistant (authentication bound to website origin; attacker.com cannot use legitimate credentials from bank.com); no shared secret to steal; strongest MFA; US government mandates FIDO2 for federal systems. Biometrics: fingerprint; face ID; iris scan; voice; inherence factor; not replaceable if compromised; typically used for local device unlock (Face ID unlocks iPhone) rather than server-side auth; server-side biometrics raise privacy concerns. Phishing-resistant MFA: FIDO2 hardware keys and passkeys are phishing-resistant; TOTP, SMS, push MFA are NOT phishing-resistant (can be relayed); CISA recommends phishing-resistant MFA for critical systems. MFA fatigue: send many push notifications rapidly (account access attempt); some users approve to stop notifications; mitigate with number matching (user enters number shown in push app) or additional context in push.")

p("What are common techniques for persistent access in Linux?",
  "Linux persistence techniques: Cron jobs: add malicious cron entry: echo */5 * * * * root /tmp/.backdoor >> /etc/crontab; or user crontab: crontab -e; /var/spool/cron/ or /etc/cron.d/; systemctl list-timers (shows systemd timers -- newer equivalent). SSH authorized_keys: add attacker public key to ~/.ssh/authorized_keys for target user (or /root/.ssh/authorized_keys for root); SSH key auth; survives password changes; detect: diff authorized_keys against expected baseline. Init/service persistence: systemd service: create /etc/systemd/system/backdoor.service; [Service] ExecStart=/tmp/.bd; [Install] WantedBy=multi-user.target; systemctl enable backdoor; SysVinit: add script to /etc/init.d/ and link in /etc/rc*.d/. SUID binaries: copy /bin/bash to /tmp/.bash; chmod 4755 /tmp/.bash; /tmp/.bash -p gives root shell; or modify existing SUID binary. Library injection (LD_PRELOAD): attacker-controlled shared library loaded before others; intercept library calls; /etc/ld.so.preload or LD_PRELOAD env for specific processes; modifies behaviour of other programs transparently. PAM (Pluggable Authentication Modules): compile malicious PAM module; add to /etc/pam.d/sshd; intercepts authentication; logs all passwords; backdoor any password. SSH ForceCommand override: add Match User to sshd_config pointing to attacker script. Bash profile: /etc/bash.bashrc, ~/.bashrc, ~/.profile, ~/.bash_profile; commands executed on shell login; malicious commands added. Kernel module (rootkit): loadable kernel module hides processes, files, network connections; requires root to load; very hard to detect without offline analysis; blacklisting module after loading insufficient. User accounts: add new user or add existing user to sudoers or wheel group; useradd -m -G sudo backdoor; set password; or add backdoor ALL=(ALL) NOPASSWD:ALL to /etc/sudoers; Peirates (cloud-native tool) checks for all these Linux persistence mechanisms.")

p("How do you detect and investigate suspicious processes in Windows?",
  "Windows process analysis: identifying malicious or suspicious processes. Built-in tools: tasklist /v (verbose process list with user and image path); tasklist /svc (services hosted in processes -- useful for spotting unusual services in svchost.exe); wmic process get processid,parentprocessid,name,commandline (command lines including arguments -- critical for detection); sc query (service status); net start (running services). Sysinternals suite: Process Explorer: hierarchical view; colour coding (blue=protected; pink=packed/suspicious); shows loaded DLLs, handles, network connections per process; compare signature: right-click > Properties > Image > Verify (is binary signed?); strings in memory; Process Monitor: real-time file, registry, network, process activity; filter by process name; Operation=WriteFile to spot file dropper activity; TCPView: real-time network connections per process; Autoruns: comprehensive persistence location inventory (Run keys, services, scheduled tasks, drivers, LSA providers, browser extensions, WMI subscriptions) -- all with signature verification. Suspicious indicators: Process masquerading: svchost.exe running outside C:\\Windows\\System32\\; explorer.exe with command-line arguments (legitimate explorer.exe has no arguments); Unexpected parent: cmd.exe or powershell.exe child of winword.exe or excel.exe (document macro execution); Java spawning cmd.exe (potential web app exploitation). No disk image: process with memory region not backed by file (reflective injection -- hollow process, module stomping); Process Explorer highlights in different colour. Unsigned or invalidly signed: legitimate Windows processes are signed; unsigned process in System32 = suspicious. High entropy: process with many connections to different external IPs; high CPU. Memory anomalies: MZ header (PE header) in unexpected memory regions; Malfind (Volatility) or Get-InjectedThread (PowerShell) detect. PID history: PID 1 = System; PID 4 = System (Windows); unusual PIDs for system processes; very low PIDs for non-system processes suspicious. Network connections: ProcessMonitor filter Operation=TCP Connect; correlate process with external connection; check IP reputation via VirusTotal.")

p("What is a security architecture review?",
  "Security architecture review: systematic examination of system design for security weaknesses before or after implementation. Goals: identify security gaps at design level (cheaper than post-implementation); validate security controls are appropriate for risk; ensure consistency with security principles; compliance alignment; produce actionable recommendations. When to perform: new system design; major feature addition; acquisition due diligence; periodic review of critical systems; regulatory requirement (SOC 2, ISO 27001). What to review: architecture diagrams: data flow diagrams (where data goes, what security controls at each transition); network diagrams (segmentation, trust zones, Internet exposure); component diagrams (what talks to what). Trust boundaries: where data crosses from trusted to untrusted (or less trusted) domain; what authentication and authorisation at each boundary; what encryption at each boundary; what logging at each boundary. Authentication and authorisation design: SSO integration; MFA enforcement; role model; session management; token lifecycle; privilege separation. Cryptography: which algorithms used (AES-256, RSA-2048, SHA-256 minimum); where encryption applied (in transit, at rest); key management (where stored, how rotated, who has access). Data flows: where is sensitive data? Who can access it? How is it protected at rest and in transit? Data retention and deletion? Third-party data sharing? Logging and monitoring: what events logged? Where logs stored? How long retained? Alerting? Incident response integration? Third-party and supply chain: third-party libraries and services? API security? Vendor access? Data shared with third parties? Outputs: threat model (STRIDE or ATT&CK based); risk rating for identified gaps; prioritised recommendations; security requirements traceability matrix (each control requirement mapped to implementation). Tools: OWASP Threat Dragon for diagramming; draw.io; Microsoft Threat Modeling Tool; documentation review; interviews with architects and developers.")

p("How do you assess and harden cloud IAM configurations?",
  "Cloud IAM hardening: Identity and Access Management is primary security control in cloud; misconfigured IAM = most common cloud breach root cause. AWS IAM assessment: enumerate all IAM entities: aws iam list-users; aws iam list-roles; aws iam list-groups; aws iam list-policies --scope Local (customer-managed); collect all permissions: aws iam get-policy-version; aws iam get-role-policy; aws iam list-attached-role-policies; Identify overly permissive: AdministratorAccess attached to service roles; iam:PassRole (escalation path); iam:CreatePolicyVersion (can add admin version); iam:AttachUserPolicy (grant self admin policy). Tool: IAM Access Analyzer (AWS built-in): finds externally accessible resources; PACU (AWS exploitation framework: has privilege escalation enumeration module). ScoutSuite (NCC Group: multi-cloud security auditing tool; generates HTML report of IAM findings, exposed resources, logging gaps). Prowler: AWS security best practice assessments; CIS AWS Foundations Benchmark; generates findings per control. Key IAM hardening actions: Remove unused users, roles, access keys (aws iam get-credential-report); Delete access keys older than 90 days; Enable MFA for all IAM users (aws iam list-mfa-devices to check); Attach permissions via groups not directly to users; Use IAM roles for EC2 instances (no long-lived access keys in code or config files); Service Control Policies (SCPs) in AWS Organisations: deny actions at org level regardless of IAM; SCP: deny s3:GetObject on s3:* unless RequestedRegion = us-east-1 (prevent data exfiltration to other regions); Permission Boundaries: limit maximum permissions a role can have even if admin tries to grant more; AWS config rules: iam-root-access-key-check; iam-user-mfa-enabled; iam-no-inline-policy; iam-policy-no-statements-with-admin-access; Principle of least privilege: use Access Advisor in IAM console to see which permissions actually used; remove unused services from policies.")

existing = sum(1 for _ in OUT.open()) if OUT.exists() else 0
print(f"Existing pairs: {existing}")
print(f"New pairs to add: {len(pairs)}")

with OUT.open("a") as f:
    for q, a in pairs:
        f.write(json.dumps({"messages": [
            {"role": "user", "content": q},
            {"role": "assistant", "content": a}
        ]}) + "\n")

total = sum(1 for _ in OUT.open())
print(f"Total upgrade_f pairs: {total}")
if total >= 1000:
    print("upgrade_f TARGET MET -- 1000+ pairs!")
else:
    print(f"Need {1000-total} more pairs")
