#!/usr/bin/env python3
"""Append extra behavioral economics pairs to upgrade_k.jsonl to reach 200"""
import json, pathlib

OUT = pathlib.Path('/workspace/data_upgrades')

extra = [
    ("What is the certainty effect and insurance?", "Loss aversion and the certainty effect jointly explain insurance demand: people overweight certain losses (premiums) when buying insurance to avoid catastrophic but uncertain losses. However, they also chronically under-insure against low-salience risks (flood, earthquake). Insurance demand is not driven purely by risk aversion — emotions, availability, and perceived dread shape coverage decisions."),
    ("What is the role of trust in economic exchange?", "Trust enables economic exchange that would be impossible under pure self-interest. Arrow argued trust is a 'lubricant' of the social system; high-trust societies have lower transaction costs and higher economic growth. Trust is undermined by betrayal experiences and high inequality. Institutional trust (courts, contracts) substitutes for personal trust in large markets. Behaviorally, trust is reciprocal and sensitive to framing."),
    ("What is inter-temporal choice and self-control?", "Inter-temporal choices involve trade-offs across time. Exponential discounting (rational model) implies consistent preferences; hyperbolic discounting generates time-inconsistent choices with present bias. Self-control failure occurs when the 'doer' dominates the 'planner.' Precommitment, implementation intentions, and environmental design help align short-term choices with long-term goals."),
    ("What is the effect of context on preferences?", "Preferences are not stable across contexts — the same individual makes different choices depending on how options are presented, what alternatives are available, and what reference point is salient. The mere presence of an unrelated option (decoy) shifts choices. Contextual dependence violates independence of irrelevant alternatives — a cornerstone of rational choice theory."),
    ("What is narrative economics?", "Shiller's narrative economics: economic fluctuations are partly driven by viral stories (narratives) that spread through social networks, influencing beliefs and behaviour in ways that affect aggregate economic outcomes. Examples: 'house prices never fall nationwide' (pre-2008); 'cryptocurrency is the future of money' (2017). Tracking narrative virality (Google Trends, social media) may predict economic cycles."),
    ("What is the role of default rules in pension policy?", "Default rules powerfully determine pension saving outcomes. Madrian and Shea (2001): switching from opt-in to opt-out (automatic enrollment) raised participation from 49% to 86% among new hires, with negligible change in explicit choices. The default rate becomes the anchor for savings — most employees stick with it. Thoughtful default rate selection (combined with SMarT escalation) can dramatically improve retirement outcomes."),
    ("What is motivated reasoning?", "Motivated reasoning is the tendency to evaluate information in a way that confirms desired conclusions. It is not random error but directional: people assess the quality of evidence differently depending on whether it supports or challenges their preferred conclusion. It is most pronounced for identity-relevant beliefs (political, religious, financial). Awareness and accountability reduce but do not eliminate motivated reasoning."),
    ("What is the backfire effect?", "The backfire effect: correcting a belief with accurate information can sometimes strengthen the original (false) belief — the correction is perceived as an attack on identity, triggering defensive processing. Particularly evident for politically charged factual beliefs. More recent research questions the robustness of the backfire effect — some studies find corrections mostly work — but motivated reasoning remains a genuine barrier to factual belief updating."),
    ("What is the dual self model of self-control?", "Fudenberg and Levine's dual self model: a long-run patient self (planner) interacts with a short-run myopic self (doer). The planner can exert costly self-control to override the doer's preferences. Self-control costs explain why willpower is limited, why commitment devices are valued, and why people adopt rules ('never drink on weekdays') rather than case-by-case deliberation to reduce self-control costs."),
    ("What is the effect of emotions on economic decisions?", "Incidental emotions (arousal, fear, sadness) from unrelated sources influence economic decisions. Angry individuals make more optimistic risk assessments and demanding offers in ultimatum games. Sad individuals offer more in dictator games. Fearful individuals prefer certainty over gambles. These affect spillovers (unrelated emotion affecting unrelated decision) violate the consequentialist model that only decision-relevant information should matter."),
    ("What is the market for lemons problem?", "Akerlof's market for lemons: asymmetric information between buyers and sellers (sellers know car quality, buyers don't) causes adverse selection — only low-quality cars ('lemons') are offered as the market unravels. High-quality sellers cannot credibly distinguish their product, so they withdraw, further reducing the price buyers are willing to pay. Solutions: warranties, certified pre-owned programs, reputation systems, and mandatory disclosure."),
    ("What is signalling in economics?", "Spence's signalling model: education serves as a signal of ability (not a human capital investment) because able individuals can acquire education more cheaply. Equilibria in which high-ability workers educate themselves and employers pay them more can persist even if education adds no productivity. The signal must be costly and differentially costly (more costly for low-ability) to be informative."),
    ("What is mechanism design?", "Mechanism design ('reverse game theory') engineers the rules of a game so that rational agents, pursuing their own interests, produce desired social outcomes. Applications: auction design (Vickrey second-price auctions elicit true valuations); matching markets (Roth's stable matching algorithms for medical residencies, kidney exchanges); and regulatory mechanisms that incentivise efficient private provision."),
    ("What is behavioral mechanism design?", "Behavioral mechanism design incorporates realistic behavioral assumptions into mechanism design. If agents are present-biased, welfare-maximising mechanisms must account for their tendency to under-invest in the future. If agents are overconfident, mechanisms must guard against excessive risk-taking. Auction design for behavioral agents must account for winner's curse and affiliation effects."),
    ("What is the equity aversion model?", "Fehr and Schmidt's inequity aversion model: agents dislike unequal outcomes — both advantageous inequity (guilt) and disadvantageous inequity (envy). Formally: utility is reduced by α × max(others' payoff − own payoff, 0) + β × max(own payoff − others' payoff, 0), where α > β > 0. The model explains rejection of low ultimatum game offers, voluntary cooperation, and voluntary punishment."),
    ("What is the prisoner's dilemma and cooperation?", "The prisoner's dilemma is a two-player game where each player has a dominant strategy to defect, but mutual cooperation Pareto dominates mutual defection. In one-shot games, defection dominates. In repeated games, cooperation can be sustained by reputation effects and tit-for-tat strategies. Social preferences (altruism, reciprocity, inequity aversion) sustain cooperation beyond what self-interest alone permits."),
    ("What is reciprocity in behavioral economics?", "Positive reciprocity: people reward kindness with kindness, even at personal cost and when there is no future interaction. Negative reciprocity: people punish unkind acts, even at cost (ultimatum rejection, third-party punishment). Reciprocity is a powerful norm governing economic relationships — gift exchange in labour markets, trust in financial relationships, and cooperation in communities."),
    ("What is the labour gift exchange?", "Akerlof modelled wages as gifts: employers offer above-market wages; employees reciprocate with above-minimal effort. Experiments (Fehr, Kirchsteiger, Riedl) show that effort is increasing in wages beyond what incentive contracts require — gift exchange sustains efficiency wages. Behavioral interpretation: workers feel obligated to reciprocate generosity; perceived unfair wages lead to work-to-rule."),
    ("What is optimal defaults in retirement plans?", "Behavioral economists argue for automatic enrollment with a thoughtful default contribution rate (e.g., 6% of salary) and default fund (diversified lifecycle fund), with automatic escalation tied to pay raises. This exploits status quo bias to improve outcomes without removing choice. Concerns: default rate becomes the target rather than the floor; some employees would have voluntarily saved more. Optimal design requires balancing defaults with active choice promotion."),
    ("What is the psychology of insurance decisions?", "Insurance decisions reflect: probability weighting (overweighting small probabilities — buying insurance against remote catastrophes); loss aversion (bearing premiums to avoid potential losses); availability (insuring risks made vivid by recent events); decision avoidance (inertia delays purchasing coverage); and myopia (not insuring long-horizon risks). Bundling insurance with products and simplifying coverage choices improves take-up of genuinely valuable insurance."),
    ("What is ego depletion and its economic implications?", "Baumeister's ego depletion: self-regulatory capacity is depleted by continuous use. Decisions made later in the day or after demanding self-control tasks are poorer — judges grant fewer paroles in the afternoon; consumers choose more impulsively. Economic implications: important decisions should be made when cognitive resources are fresh; decision environments should reduce the need for constant self-regulation through better defaults and simpler choices."),
    ("What is behavioral economics of health insurance choice?", "Health insurance choice is complex and consequential, but consumers make poorly informed decisions. Bhargava, Loewenstein, and Sydnor (2017): 48% of employees chose dominated health plans (same coverage at higher cost). Complexity and inattention explain this — the optimal plan is hard to identify. Defaults, simplified comparison tools, and standardised plan designs can improve decision quality."),
    ("What is revealed preference and behavioral challenges?", "Revealed preference theory (Samuelson): observe choices to infer preferences — there is no need to introspect on mental states. Behaviorally, this is challenged: choices reveal decision processes (including biases) not stable underlying preferences; menu-dependent and context-dependent choices violate the axioms of revealed preference; and welfare analysis based on revealed preference may mislead when choices reflect errors."),
    ("What is behaviorally informed welfare analysis?", "Standard welfare economics uses revealed preference to assess well-being. Behavioral welfare economics (Bernheim and Rangel) distinguishes true preferences from choice with biases. Welfare analysis should correct for well-understood, documented biases (anchoring, present-bias) rather than treating all choices as preference revelations. This supports nudges that correct biases without overriding preferences altogether."),
    ("What is the attention economy?", "The attention economy frames human attention as a scarce resource competed for by media, platforms, and advertisers. Firms design products to be maximally attention-capturing (notifications, autoplay, infinite scroll — exploiting the variable ratio reinforcement schedule). Regulatory responses: screen time tools; algorithmic transparency; advertising-free subscriptions. Behavioral economics illuminates how attention is captured and its consequences for economic decisions."),
    ("What is financial literacy and behavioral economics?", "Low financial literacy impairs retirement saving, debt management, and investment. Lusardi and Mitchell: only a third of Americans can answer basic compound interest, inflation, and diversification questions. Financial education has modest and short-lived effects on behaviour. Structural interventions (auto-enrollment, default allocations, simple product design) achieve more than financial literacy programs. The combination of decision architecture and literacy improvements is optimal."),
    ("What is the ostrich effect in investment?", "Investors tend to avoid information about how their portfolios are performing — 'burying their heads in the sand' when they expect bad news. Galai and Sade (2006): investors access portfolio information less frequently when markets are declining. Avoiding information avoids the emotional pain of losses but impedes rational rebalancing. The ostrich effect worsens portfolio performance by preventing necessary corrective action."),
    ("What is construal level theory and behavioral economics?", "Construal level theory (Liberman and Trope): psychologically distant events (temporally, spatially, hypothetically) are thought about in abstract, high-level terms; close events are thought about in concrete, low-level terms. Temporal distance increases abstract thinking and long-term focus, which improves self-control. Asking 'Would you like to be healthy?' (abstract/distant) motivates diet better than 'Would you like to eat salad today?' (concrete/close)."),
    ("What is social comparison and financial wellbeing?", "Financial wellbeing depends not just on absolute wealth but on relative position. 'Keeping up with the Joneses' (Veblen, Duesenberry): consumption is positively influenced by others' consumption. Luttmer (2005): life satisfaction decreases when neighbours' incomes rise. This 'positional externality' — consuming to maintain relative status — leads to overconsumption from a social welfare perspective and justifies progressive consumption taxes."),
    ("What is the role of identity in economic decisions?", "Akerlof and Kranton's identity economics: people have social identities (gender, race, religion, profession) and value conforming to the norms of their identity group. Work effort, educational attainment, and consumption are shaped by identity prescriptions. Policies that threaten identity (e.g., affirmative action programmes framed as suggesting Black students are less capable) can backfire by triggering identity-protective responses."),
    ("What is pain of paying?", "Prelec and Loewenstein's pain of paying: paying for a purchase triggers a negative affective response that reduces consumption utility — the more salient the payment, the greater the pain. Credit cards reduce pain of paying (decoupling payment from consumption); this increases spending. Bundle pricing (all-inclusive holidays) eliminates payment pain during consumption. Prepayment creates 'sunk cost' that paradoxically increases enjoyment."),
    ("What is the behavioral economics of organ donation?", "Default choice architecture dramatically affects organ donation rates. Opt-out (presumed consent) countries have registration rates above 90%; opt-in countries typically have 15-30%, despite similar public support for donation. The difference is almost entirely attributable to defaults and inertia. Johnson and Goldstein's model: defaults communicate a social norm ('this is what most people do') in addition to exploiting status quo bias."),
    ("What is the effect of salient information on decisions?", "Salient information — information that is vivid, visually prominent, or personally relevant — disproportionately influences decisions relative to non-salient information of equal importance. Calorie labelling is more effective when it highlights cumulative impact (minutes of exercise, weekly total) rather than per-item figures. Interest rate disclosure is more effective when translated into total cost of credit. Saliency design improves decision quality without restricting choice."),
    ("What is the behavioral economics of crime?", "Becker's rational crime model: crime rates respond to expected punishment (probability × severity). Behavioral evidence: certainty of punishment is more deterrent than severity (hyperbolic discounting makes distant severe punishments irrelevant); criminal opportunities are taken impulsively (hot states bypass deliberation); and social norm violations feel less wrong in peer groups that normalise crime. Interventions targeting hot-cognition and social norms may be more effective than sentencing increases."),
    ("What is herding and information cascades?", "An information cascade occurs when individuals observe others' actions (but not their private information) and rationally ignore their own private signals, copying others instead. In a cascade, publicly observable choices convey less information than they appear to, because they are copies rather than independent signals. Cascades can sustain incorrect collective beliefs and are fragile — a single public contrary signal can break them."),
    ("What is the difference between risk and uncertainty in behavioral economics?", "Knight's distinction: risk refers to situations where probabilities are known (dice roll); uncertainty (or ambiguity) refers to situations where probabilities are unknown (future of AI). Behavioral evidence: people are more averse to uncertainty (Ellsberg paradox) than risk, beyond expected utility predictions. Ambiguity aversion increases with unfamiliarity and high stakes. Behaviorally informed policy acknowledges that novel risks create more aversion than probability calculations would suggest."),
    ("What is the behavioral economics of poverty traps?", "Beyond material constraints, poverty creates a cognitive and psychological trap: scarcity taxes cognitive bandwidth; social stigma impairs self-efficacy; uncertainty discourages investment; and immediate needs crowd out future planning. Banerjee and Duflo's RCT evidence: targeted asset transfers with psychosocial support (graduation programmes) sustainably lift households out of poverty by addressing both material and behavioural constraints."),
    ("What is the nudge versus boost debate?", "Nudges (Thaler and Sunstein) improve decisions by redesigning choice architecture to exploit biases. Boosts (Hertwig and Grüne-Yanoff) instead build individual decision-making competencies — improving understanding of probabilities, heuristics, and statistical reasoning — enabling better decisions across contexts. Nudges work with existing biases; boosts try to overcome them. The debate concerns whether we should exploit human limitations or repair them."),
    ("What is the behavioral approach to public health?", "Behavioral public health uses insights from behavioral economics to design health interventions. Examples: simplifying health messages (fewer and clearer); making healthy choices the default (healthy school meals); timing messages at moments of high motivation (hospital discharge, New Year); and using social proof ('8 in 10 patients have already paid their NHS bill'). These approaches are cost-effective complements to traditional education and incentive campaigns."),
    ("What is the role of time preferences in healthcare decisions?", "Present bias leads to under-investment in preventive health: the cost (gym, vaccination, screening) is immediate; the benefit (avoided future illness) is distant and discounted. Commitment contracts (deposit-refunded on verified healthy behaviour) and future-self visualisation exercises reduce present bias in health decisions. Framing preventive care as 'protecting your future self' rather than abstract statistics increases uptake."),
    ("What is behaviorally-informed financial regulation?", "Traditional financial regulation assumes rational consumers who respond to disclosure. Behavioral regulation additionally: mandates simple, standardised product disclosure (key facts documents — EU PRIIPs KID); bans complexity that exploits bounded rationality (Payment Protection Insurance — UK mis-selling scandal); requires default options to be fair (FCA price walking ban); and restricts high-cost credit to present-biased borrowers."),
    ("What is the role of self-image in economic decisions?", "People make economic decisions that maintain a positive self-image — Akerlof and Kranton's identity economics; Ariely's self-concept maintenance theory. People who think of themselves as honest make more honest choices when their self-concept is primed. Charitable giving is partly motivated by self-image ('I am a generous person'). Public commitments and identity-based appeals are more effective than financial incentives for prosocial behaviour."),
    ("What is status quo bias in energy markets?", "Status quo bias causes energy consumers to remain on their initial tariff even when cheaper alternatives are available. Firms exploit this: introductory low prices bait consumers who then default to expensive standard rates. Regulators respond: automatic switching for consumers on expensive default tariffs; collective switching schemes that negotiate better deals on behalf of passive consumers; and periodic default market reviews."),
    ("What is the behavioral economics of debt?", "Debt decisions are distorted by: present bias (borrowing today, ignoring future repayment); optimism about repayment capacity; mental separation of debt and savings accounts (avoiding high-interest debt while maintaining low-interest savings); minimum payment anchoring; and cognitive complexity of APR comparisons. Behaviorally informed regulation: standardised APR disclosure; cooling-off periods; debt consolidation; and mandatory comparison sites."),
    ("What is the role of social proof in marketing?", "Social proof (Cialdini): people look to others' behaviour for guidance on the correct action, especially in ambiguous situations. 'Best-selling' product labels, star ratings, and 'X people are viewing this item' cues increase sales beyond what quality alone explains. Firms invest in generating authentic and fake reviews. Social proof works especially for unfamiliar products and in crowds, where coordinating on a popular item reduces risk."),
    ("What is the cross-price effect in behavioral economics?", "Cross-price effects in behavioral economics extend beyond standard substitution effects to include: reference prices (a product's price changes the reference point for a related product); mental accounts (a purchase in one account changes the available budget in related accounts); and anchoring (a high-priced product shifts the reference for similar products). These effects explain non-standard demand responses that standard models cannot."),
    ("What is bounded willpower?", "Bounded willpower (Thaler's three bounds of behavioral economics alongside bounded rationality and bounded self-interest): people sometimes act against their own long-run interests — eating too much, saving too little, procrastinating. This is distinct from the cognitive limitations of bounded rationality. It motivates commitment devices, cool-period requirements before major purchases, and counter-cyclical product design that makes harmful consumption harder when impulse is high."),
    ("What is the role of emotions in financial risk-taking?", "Emotions influence financial risk-taking beyond expected utility. Loewenstein's risk-as-feelings hypothesis: emotional responses to risk (fear, excitement) diverge from cognitive evaluations and drive behaviour. Incidental positive emotions increase risk-taking; fear reduces it. Mood disorders affect trading performance. Investment strategies that reduce emotional influence (systematic, algorithm-based) outperform discretionary approaches on average."),
    ("What is behaviorally-informed contract design?", "Standard contracts assume rational counterparties. Behaviorally informed contracts account for: present bias (front-loaded incentives dominate back-loaded ones in motivating effort); overconfidence (parties' over-optimistic projections build in insufficient contingencies); loss aversion (milestone bonuses framed as losses if missed are more motivating than equivalent gains); and reference points (the contract's terms become reference points that anchor renegotiation)."),
    ("What is default investment options in behavioural finance?", "Default investment funds in pension plans receive disproportionate investment — most employees stick with the default. The quality of the default fund critically determines retirement outcomes. Behaviorally optimal defaults: diversified low-cost index funds (target-date funds) adjusted for risk tolerance by age; avoidance of company stock concentration (Enron problem — loss aversion keeps employees in losing company stock). Defaults are effectively a policy tool."),
    ("What is the present-day relevance of behavioral economics?", "Behavioral economics has moved from academic curiosity to mainstream policy tool. It informs: financial regulation (FCA behavioural economics unit); public health (sugar taxes, calorie labelling); retirement security (automatic enrollment, SMarT); energy conservation (social norm comparisons); healthcare (HIV testing opt-out in Africa — dramatically increased uptake); and tax compliance (social norm letters — HMRC). The field continues to refine its understanding of when interventions work and for whom."),
    ("What is the behavioral economics of charitable fundraising?", "Fundraising leverages behavioral insights: matching grants (1:1 or 2:1 match) significantly increase donations — even small matches work; large lead donations create social proof and shift reference points; lotteries harness overweighting of small probabilities; specific, identified beneficiaries outperform statistical lives; deadline and scarcity appeals exploit loss aversion. Ariely argues transparency about how donations are used is less effective than emotional narrative."),
    ("What is the role of trust in nudges?", "Nudge effectiveness depends on public trust in the nudging institution. Perceived manipulation or hidden agendas reduce nudge effectiveness and can produce reactance. Transparent nudges ('we are using this default to help you save more') are almost as effective as non-transparent ones and are less susceptible to reactance and backlash. Sunstein argues that mandatory disclosure of nudge designs sustains democratic legitimacy."),
    ("What is the behavioural approach to improving legal compliance?", "Legal compliance can be improved through behavioral tools: simplifying tax forms (reduced compliance costs increase voluntary filing); personalising letters with the taxpayer's name and specific obligations; framing non-compliance as a social norm violation ('most people in your neighbourhood have paid'); reducing cognitive load for benefit claiming; and timing enforcement communications at optimal moments (just after income receipt). These outperform purely deterrence-based approaches."),
]

existing = sum(1 for _ in OUT.open()) if OUT.exists() else 0
print(f"Existing: {existing} pairs")

with OUT.open("a") as f:
    for q, a in extra:
        f.write(json.dumps({"messages": [
            {"role": "user", "content": q},
            {"role": "assistant", "content": a}
        ]}) + "\n")

total = sum(1 for _ in OUT.open())
print(f"Total: {total} pairs in upgrade_k.jsonl")
assert total >= 200, f"Only {total} — need 200"
print("PASS: 200+ premium behavioral economics pairs ready.")
