#!/usr/bin/env python3
"""gen_f_fill27.py -- final 100+ pairs to reach 1000+"""
import json, pathlib

OUT = pathlib.Path('/workspace/data_upgrades/upgrade_f.jsonl')
OUT.parent.mkdir(parents=True, exist_ok=True)

pairs = []
def p(q, a):
    pairs.append((q, a))

p("What is cybersecurity risk quantification?",
  "Risk quantification: express cyber risk in financial terms; enable executive decision-making; prioritise investment. Why quantify: traditional: red/amber/green heat maps (qualitative); executives cannot compare: critical risk in IT vs operational risk; cannot calculate ROI of security control investment; financial quantification: compare security investment to risk reduction in dollars; justify security budget; prioritise controls by cost-effectiveness. FAIR (Factor Analysis of Information Risk): most widely adopted quantitative framework; decomposes risk into: Loss Event Frequency (how often does threat event occur?): Threat Event Frequency (how many times does threat agent attempt?), Vulnerability (% of attempts resulting in loss event); Loss Magnitude (how much does each event cost?): Primary Loss (direct cost: recovery, notification, fines), Secondary Loss (indirect: reputation, legal, regulatory); outputs: probability distribution of annual loss; 80th percentile loss exceedance curve; FAIR analysis: structured exercise; gather data: threat intelligence, vulnerability data, control effectiveness, historical incidents; quantify each component; Monte Carlo simulation: run thousands of scenarios; produce probability distribution. Example output: ransomware risk on corporate network: 90% confidence annual loss < $2.4M; mean annual loss $800K; 10% chance of loss > $5M per year. Using quantification for decisions: control ROI: current risk $800K annual loss; MFA investment $50K; MFA reduces risk by 60% ($480K reduction); ROI = ($480K - $50K) / $50K = 860% in year 1; cyber insurance: use FAIR output to size cyber insurance policy appropriately; risk appetite: executive sets threshold: accept risks under $100K annually; mitigate risks over $1M; risk transfer above threshold. Tools: RiskLens (SaaS, FAIR-based); SAFE Security (ML-based); Axio360; spreadsheet models; Cyentia Institute (research data on breach costs). Challenges: data quality: incident data scarce; threat event frequency estimates uncertain; model is estimate not truth; ranges more honest than point estimates; starting with qualitative then quantifying top risks is pragmatic approach; common criticism: garbage in garbage out; but even rough quantification better than qualitative; forces explicit assumption documentation.")

p("What is asymmetric encryption and how is it used in security?",
  "Asymmetric encryption (public-key cryptography): two mathematically related keys; public key encrypts or verifies; private key decrypts or signs; private key never shared. How it works: key pair: generate mathematically related pair: public key (share freely) and private key (keep secret); encryption: sender encrypts with recipient public key; only recipient private key can decrypt; signature: signer signs with private key; anyone with public key can verify signature; key exchange: Diffie-Hellman: exchange public values; derive shared secret without transmitting it; algorithms: RSA: most common; based on factoring large integers; RSA-2048 minimum (RSA-4096 for 20+ year security); ECDSA (Elliptic Curve Digital Signature Algorithm): signatures; smaller keys for equivalent security; P-256, P-384, Ed25519; ECDH (Elliptic Curve Diffie-Hellman): key exchange; TLS 1.3 uses X25519 (Curve25519 ECDH). Use cases: TLS certificate and key exchange: server has RSA or ECDSA certificate (public key); TLS handshake: ECDHE for key exchange (ephemeral asymmetric key pair derives symmetric session key); certificate verifies server identity (signature by CA); SSH: server has RSA/ECDSA/Ed25519 host key; client stores public key fingerprint; prevents MITM; client authentication: client has private key; server has authorised_keys; public key authentication; code signing: binary signed with developer private key; user verifies with developer public key; ensures binary not tampered; PGP email: recipient public key encrypts; sender private key signs; GPG implements PGP; digital certificates (X.509): certificate = public key + identity + CA signature; CA signs certificate with CA private key; browsers trust CA public keys (root store); blockchain: cryptocurrency wallets are ECDSA key pairs; transaction signed with private key; network verifies with public key. Performance: asymmetric operations much slower than symmetric; RSA-2048 sign: ~1ms; AES-256 encrypt 1MB: microseconds; hybrid encryption: encrypt data with symmetric key (AES-256, fast); encrypt symmetric key with asymmetric (RSA/ECDH); recipient decrypts asymmetric wrapper; uses symmetric key to decrypt data; TLS does this: ECDHE derives symmetric session key; AES-GCM encrypts data with session key.")

p("What is a cybersecurity operations program maturity model?",
  "Cybersecurity programme maturity model: assess and improve overall security programme; not just individual controls. Common frameworks: NIST Cybersecurity Framework (CSF): not strictly a maturity model but Tiers 1-4 approximate maturity; Tier 1 (Partial): ad hoc, reactive; Tier 2 (Risk Informed): risk management practices approved but not consistently implemented; Tier 3 (Repeatable): formal policies, repeatable processes; Tier 4 (Adaptive): actively adapting; threat and technology changes incorporated. C2M2 (Cybersecurity Capability Maturity Model): US DoE; 10 domains; 4 maturity indicator levels (MIL0-MIL3); initially oil and gas sector; broader adoption. CMMI for Security: adapts CMMI software process improvement; 5 levels: Initial (ad hoc), Managed (project-level), Defined (organisation-level), Quantitatively Managed (measured), Optimising (continuous improvement). Custom programme maturity assessment: domain-based: Identity and Access Management, Vulnerability Management, Incident Response, Security Architecture, Data Protection, Governance and Risk, Third-Party Risk, Security Operations, Application Security, Physical Security; each domain: define maturity criteria per level (1-5); assess against criteria; score each domain; create spider/radar chart; identify lowest-scoring domains; prioritise improvement roadmap. Maturity assessment process: self-assessment vs external assessment; structured interview + evidence review; scoring against criteria; gap analysis; prioritised roadmap with resource requirements; executive report with business context; common maturity levels described: Level 1 (Initial/Reactive): no documented processes; reactive to incidents; no formal programme; Level 2 (Developing): basic policies exist; some processes defined; inconsistently followed; Level 3 (Defined): documented processes; consistently followed; organisation-wide; Level 4 (Managed): metrics collected; performance tracked; data-driven decisions; Level 5 (Optimising): continuous improvement; benchmarking; adaptive to new threats. Roadmap development: prioritise domains with highest risk and lowest maturity; balance quick wins (raise awareness, get executive buy-in) with strategic improvements (programme-level changes); resource requirements: headcount, tools, training, external services; timeline: 12-24 months to next maturity level typically; board reporting: maturity progress as security KPI; link to risk reduction; justify ongoing investment.")

p("How does a web application penetration test scope affect methodology?",
  "Pentest scope and methodology: scope definition determines testing approach, depth, and deliverables. Black-box testing: no prior knowledge of application; simulate external attacker with no insider knowledge; methodology: discovery first (find all endpoints, technology, functionality); automated scanning (Burp, ZAP); manual exploitation; longer reconnaissance phase; misses: internal-only vulnerabilities, server-side code issues without source access; appropriate for: external adversary simulation, testing defensive visibility, initial assessment. Grey-box testing: partial knowledge provided: user credentials (one or more roles), partial documentation, technology stack; methodology: authentication testing from provided credential points; access control testing (use provided credentials); reduced reconnaissance; more time for exploitation; most common pentest engagement type; appropriate for: authenticated user abuse scenarios, majority of web application assessments; balances realism with efficiency. White-box testing: full knowledge: source code, architecture diagrams, network diagrams, credential for all roles, documentation; methodology: code review + dynamic testing; SAST on provided source code; comprehensive authentication and authorisation testing; business logic analysis with full context; most thorough; most expensive; appropriate for: critical applications, high-security environments, pre-launch assessments, finding maximum vulnerabilities. Scope elements: in-scope: specific domains (app.example.com, api.example.com), IP ranges, mobile applications, specific functionality; out-of-scope: production customer data, specific third-party components, social engineering, physical, denial of service (must be explicit); testing environment: production vs staging; if production: extra care required; data handling: discovered credentials and PII handling procedure; exclusions: security monitoring (do you notify SOC to expect test traffic?; or test SOC detection capability without notification?). Time-based scope: fixed time engagements: 5-10 days typical for web app pentest; time allocation: reconnaissance 10-15%, automated scanning 15-20%, manual testing 50-60%, reporting 15-20%; impact: grey-box assessment more efficient (less recon time); white-box most efficient (direct to code analysis); depth vs breadth: time-limited must choose: broad shallow assessment (find common vulns across all functionality) vs narrow deep assessment (thoroughly test payment functionality); discuss with client; match business risk. Engagement letter components: scope (exact), timeline, point of contact, emergency procedure, safe harbour, deliverables, payment.")

p("What is a cyber resilience strategy?",
  "Cyber resilience: ability to withstand cyberattacks, continue operations during incidents, and recover quickly; broader than cybersecurity (which focuses on prevention). Prevention vs resilience: pure prevention focus: invest only in stopping attacks; inevitable breach eventually (no 100% prevention); no recovery capability; long disruption when breach occurs; resilience approach: accept that some attacks will succeed; invest in: detection (find attacks quickly), containment (limit blast radius), recovery (restore operations fast), continuity (keep critical operations running during incident). Business continuity planning (BCP): identify critical business processes: revenue-generating, customer-facing, legally required; rank by Maximum Tolerable Downtime (MTD): how long can this process be down before irreversible harm?; for each critical process: identify supporting IT systems; develop continuity plan; test annually. Disaster Recovery (DR): RTO (Recovery Time Objective): maximum acceptable downtime; RTO drives recovery architecture choices; RPO (Recovery Point Objective): maximum acceptable data loss (how old can restored data be?); DR strategies by RTO: backup and restore (RTO hours-days), warm standby (RTO minutes-hours), pilot light (RTO minutes), multi-site active-active (RTO seconds); backup testing: regular test restores; backup value only proven if restore works; 3-2-1 rule: 3 copies, 2 different media types, 1 offsite. Incident response capability: IR plan: documented and tested; IR retainer: pre-contracted IR firm; accelerates incident response; tabletop exercises: practise responses; cyber insurance: financial resilience; covers: IR costs, legal fees, notification costs, ransom (if decided to pay), business interruption. Resilience by design: immutable infrastructure: deploy from code; if compromised: destroy and redeploy; no manual intervention; segmentation: limit blast radius; critical systems segment isolated from general network; defence in depth: multiple controls; single control failure does not cascade; chaos engineering (Netflix approach): intentionally test failure scenarios; inject failures in production; verify system handles; identify weak resilience points. Cyber resilience metrics: MTTD (Mean Time to Detect); MTTR (Mean Time to Recover from incident); backup restore test success rate; RTO/RPO achieved in DR tests; number of incidents that degraded but did not break operations vs those that caused full outage; target: 100% of incidents managed without customer impact long-term.")

p("What is a cybersecurity career path and key skills?",
  "Cybersecurity career paths: multiple specialisations; technical and non-technical roles. Entry paths: IT support and system administration: strong foundation; understand what normal looks like; software development: developer to application security; understand code; network engineering: network to network security; know the protocols; military or law enforcement: intelligence, digital forensics. Early certifications: CompTIA Security+: broad foundation; widely accepted for entry level; vendor-neutral; CompTIA Network+: networking foundation before Security+; CompTIA CySA+ (Cybersecurity Analyst): blue team focus; CEH (Certified Ethical Hacker): red team basics; eJPT (eLearnSecurity Junior Penetration Tester): practical beginner pentest. Technical specialisations: penetration tester / red team: OSCP (Offensive Security Certified Professional): gold standard practical pentest cert; eWPT, eWPTX: web app pentest; GPEN, GWAPT (GIAC); advanced: OSED, OSEP, OSWE (Offensive Security advanced); bug bounty hunter: HackerOne, Bugcrowd; SOC analyst / blue team: GCIA (Intrusion Analyst), GCIH (Incident Handler); Microsoft SC-200 (Security Operations Analyst); threat hunter: requires EDR + SIEM expertise; ATT&CK knowledge; digital forensics and incident response (DFIR): GCFE (Forensic Examiner), GCFA (Forensic Analyst), GCFE; EnCE; cloud security: AWS Security Specialty, Azure AZ-500, GCP Professional Cloud Security Engineer; CCSP (Certified Cloud Security Professional); application security: GWEB, GWPT; CSSLP (Certified Secure Software Lifecycle Professional); OSWE; GRC (Governance Risk Compliance): CISSP (Certified Information Systems Security Professional): managerial; widely required for senior roles; CISM (Certified Information Security Manager): management focus; CRISC (Certified in Risk and Information Systems Control). Career progression: analyst -> senior analyst -> lead -> manager -> director -> CISO; technical individual contributor path: junior -> mid -> senior -> principal -> staff; management vs technical: many stay technical (principal/staff security engineer); others move to management; both valuable. Skills valued: hands-on lab practice: TryHackMe, HackTheBox, Hack The Box Pro Labs, OffSec Proving Grounds; CTF (Capture The Flag) competitions; open-source contributions (Metasploit modules, Burp extensions, YARA rules, Sigma rules); blog writing and conference talks: demonstrates expertise; builds reputation; soft skills: communication (explain technical risk to business), report writing, stakeholder management, project management.")

p("What is purple team versus red team versus blue team?",
  "Team colours in cybersecurity: specialised roles in security testing and operations. Red team: offensive; simulate real-world attackers; find vulnerabilities before adversaries do; methodologies: adversary simulation (mimic specific threat actors), goal-oriented (reach objective: domain admin, steal specific data), full-scope (physical, social engineering, digital); distinct from pentest: longer engagements, stealthier, realistic TTPs, test detection and response not just vulnerabilities; deliverable: comprehensive report on attack path, dwell time, detection gaps; personnel: ethical hackers, former offensive security researchers; tools: Cobalt Strike, Metasploit, custom implants, physical access tools. Blue team: defensive; monitor, detect, and respond to threats; functions: SIEM monitoring, alert triage, incident response, threat hunting, detection engineering, vulnerability management, security architecture; 24/7 operations; persona: defenders, SOC analysts, incident responders, detection engineers; deliverable: operational security; metrics (MTTD, MTTR, false positive rate, coverage); tools: SIEM, EDR, SOAR, vulnerability scanner, network monitoring. Purple team: collaboration between red and blue; red team executes techniques; blue team checks detection immediately; real-time feedback loop; goal: improve detection coverage against specific TTPs; not just simulation but direct improvement; adversary emulation plans (ATT&CK-based); each technique tested and detection improved on the spot; deliverable: improved detection rules, data source gaps identified, coverage heat map. Yellow team (software security): developers and security engineers; build security in; secure code, security architecture, SAST, SCA, developer security training; combines software development (yellow) with security; DevSecOps is the yellow team approach. Green team (integration): some organisations use green for security automation and SOAR engineers who bridge red (attack knowledge) and blue (defensive response) through automation; less standardised term. Practical structure: small organisations: security generalists play all roles; medium: separate red team function (or external engagement), SOC/blue team; large enterprise: dedicated red team, SOC with L1/L2/L3, detection engineering team, threat intel team, purple team exercises quarterly; very large (FAANG, financial): all teams plus dedicated adversary simulation teams, AI/ML security research, offensive security research.")

p("What is a responsible disclosure and vulnerability disclosure programme?",
  "Responsible disclosure (coordinated vulnerability disclosure): process for security researchers to report vulnerabilities to vendors; allows patch development before public disclosure. Why responsible disclosure: full immediate disclosure (no waiting): defenders have no time to patch; attackers exploit immediately after disclosure; non-disclosure (keep secret): vendor never patches; attackers independently discover; responsible disclosure balances: vendor notified first; time to patch; public disclosure after fix; benefit: researcher credited; vulnerability fixed; industry improved. Process: researcher discovers vulnerability; contacts vendor: security@company.com, HackerOne, dedicated disclosure form; shares: vulnerability details, proof of concept, affected versions, CVSS assessment; vendor acknowledges within agreed SLA (typically 3-7 days); vendor investigates; confirms validity and severity; vendor develops patch: timeline agreed (typically 90 days; Google Project Zero standard); CVE requested and reserved; patch released; coordinated public disclosure: CVE published, vendor advisory, researcher credit; credit: researcher credited in advisory and CVE; sometimes cash bounty if bug bounty programme exists. Timelines: 90 days standard (Google Project Zero): vendor has 90 days to patch; if not patched: Project Zero publishes regardless; rationale: after 90 days vendor unlikely to patch without public pressure; CERT/CC: 45 days historically; NCSC (UK): flexible; negotiation: critical infrastructure, national security implications: extended timeline negotiable; active exploitation: shorter timeline. Legal protections: safe harbour: responsible vendor explicitly states will not pursue legal action for good-faith disclosure; Computer Fraud and Abuse Act (CFAA) concerns: US law; security researchers have been prosecuted; safe harbour reduces risk; EU Directive on attacks against information systems: similar concerns; disclosure agreement: some vendors require NDA; researchers should be cautious about broad NDAs. CVE (Common Vulnerabilities and Exposures): unique identifier for each vulnerability; CVE-2024-12345; CVE Numbering Authority (CNA): vendor or organisation authorised to assign CVEs; MITRE: top-level CNA; NIST NVD: enriches CVEs with CVSS scores and additional metadata; researchers can request CVE before disclosure (pre-allocation).")

p("What is security for IoT devices?",
  "IoT security: secure Internet of Things devices; cameras, sensors, industrial equipment, medical devices, home automation. IoT security challenges: resource constraints: limited CPU, memory, battery; cannot run full OS or AV; long lifecycle: deployed 10-20 years; vendor stops supporting; no patches; poor defaults: default username/password (admin/admin); default accounts not required to change; broad attack surface: many IoT protocols (MQTT, CoAP, Zigbee, Z-Wave, BLE, LoRaWAN); lack of visibility: traditional security tools do not inventory IoT; no EDR agent; heterogeneous: thousands of device types; no standard security approach. Common IoT vulnerabilities: default credentials: Mirai botnet exploited default credentials on cameras/DVRs at massive scale; unencrypted communication: cleartext HTTP, telnet, unencrypted MQTT; no authentication between IoT device and hub; outdated firmware: no update mechanism; no patch applied for years; insecure APIs: mobile app or web interface controlling device has injection, auth bypass; physical attacks: JTAG, UART debug interfaces accessible; extract firmware; reverse engineer; modify; unencrypted firmware: extract firmware; find credentials, encryption keys, proprietary algorithms. Security controls: secure defaults: unique per-device credentials (not factory default); require password change on first use; disable unused interfaces; encryption: TLS for all communication; WPA2/WPA3 for Wi-Fi IoT; BLE with proper pairing; authentication: device authentication with certificates; mutual TLS; network segmentation: IoT devices on dedicated VLAN; no communication between IoT and corporate network; restrict internet access; firmware updates: secure update mechanism (signed firmware); automated update push; discovery and inventory: passive network scanning (fingerprinting by network behaviour); Claroty, Armis, Ordr, Nozomi (OT/IoT visibility platforms). Medical devices: FDA cybersecurity guidance: pre-market and post-market; SBOM required; coordinated vulnerability disclosure; security patching; HIPAA PHI protection. OT/ICS (overlap with IoT): Purdue model network segmentation; air-gap critical control systems; out-of-band monitoring; IEC 62443 standard. Standards: NIST SP 800-213 (IoT Cybersecurity); ETSI EN 303 645 (European IoT security standard); ENISA IoT guidelines; PSA Certified: hardware security architecture.")

p("What are common vulnerabilities in GraphQL APIs?",
  "GraphQL security vulnerabilities: query language for APIs with unique attack surface beyond REST API issues. GraphQL basics: single endpoint (/graphql); client defines exact data shape; queries (read) and mutations (write); subscriptions (real-time); schema defines types, fields, queries, mutations. Introspection: GraphQL introspection: query the schema itself; discover all types, fields, queries, mutations; query: {__schema {types {name fields {name type {name}}}}}; in development: reveals full API surface; in production: should be disabled for external consumers; disable: graphql(schema, {introspection: false}); development tool exception: graphiql playground often left enabled in production. Denial of service -- query complexity: deeply nested queries: user { friends { friends { friends { ... (20 levels deep) }}}}; N+1 queries: each friend requires separate DB query; amplification attack; protection: query depth limit (reject queries > N levels deep); query complexity limit (each field has cost; reject if total cost exceeds threshold); query timeout; rate limiting per query; persisted queries (allowlist of pre-approved queries; reject ad hoc queries). Authorization: field-level authorization missing: query user(id: 2) {adminNotes} (regular user accessing admin field); object-level: IDOR in GraphQL (change ID argument); mutation authorization: can regular user call admin mutations?; test all queries and mutations with insufficient privileges; batch mutations: GraphQL allows multiple mutations in one request; rate limiting per HTTP request insufficient; must rate limit per mutation. Injection via arguments: SQL injection in resolver arguments: getUser(name: test OR 1=1); NoSQL injection in MongoDB resolver: $where operator injection; SSRF via URL arguments: fetchURL(url: http://169.254.169.254/); inject in all string arguments; Test: GraphQL-specific tools: InQL (Burp Suite extension): introspection, query generation; GraphiQL: developer IDE for GraphQL; Altair: GraphQL client; Clairvoyance: introspection bypass (guess fields even when introspection disabled). Sensitive data in errors: GraphQL errors often verbose; reveal schema information even with introspection disabled; reveal field names from error messages; disable detailed errors in production; return generic error messages; log detailed errors server-side. Field suggestions: GraphQL returns Did you mean X? Suggestions for invalid field names; reveals valid field names even without introspection; disable suggestions in production (most frameworks have option). Batching attacks: GraphQL supports query batching (array of queries); rate limit bypass: 100 login mutations in one HTTP request = 100 password attempts; implement per-operation rate limiting not just per-HTTP request.")

existing = sum(1 for _ in OUT.open()) if OUT.exists() else 0
print(f"Existing pairs: {existing}")
print(f"New pairs to add: {len(pairs)}")

with OUT.open("a") as f:
    for q, a in pairs:
        f.write(json.dumps({"messages": [
            {"role": "user", "content": q},
            {"role": "assistant", "content": a}
        ]}) + "\n")

total = sum(1 for _ in OUT.open())
print(f"Total upgrade_f pairs: {total}")
if total >= 1000:
    print("upgrade_f TARGET MET -- 1000+ pairs!")
else:
    print(f"Need {1000-total} more pairs")
