#!/usr/bin/env python3
"""gen_p_fill.py -- add banking/finance pairs to upgrade_p.jsonl"""
import json, pathlib

OUT = pathlib.Path('/workspace/data_upgrades')
OUT.parent.mkdir(parents=True, exist_ok=True)

pairs = []
def p(q, a):
    pairs.append((q, a))

p("What is securitisation and how does it work?",
  "Securitisation: pooling illiquid assets (mortgages, auto loans, credit card receivables) and selling their cash flows as tradable securities. Process: originator (bank) creates loans; transfers pool to Special Purpose Vehicle (SPV) -- a bankruptcy-remote entity; SPV issues asset-backed securities (ABS) tranched by seniority: senior (AAA-rated, paid first, lowest yield), mezzanine, equity/first-loss (residual, highest risk/return); investors buy tranches; loan repayments flow from borrowers through SPV to investors. Benefits: banks recycle capital (remove loans from balance sheet, originate more); investors access diversified loan portfolios; price discovery for credit risk. Types: MBS (Mortgage-Backed Securities), CMBS (Commercial), ABS (auto, credit cards), CLO (Collateralised Loan Obligations -- leveraged loans), CDO (Collateralised Debt Obligations). Risk: pre-2008, CDOs squared (CDOs of CDOs) amplified risk; correlation underestimated -- when housing fell, all tranches correlated; AAA ratings proved wrong; financial crisis. Post-crisis: stricter risk retention (originator must keep 5% first-loss -- skin in the game); enhanced disclosure; simpler structures.")

p("Explain the Basel III capital requirements for banks.",
  "Basel III: international regulatory framework for bank capital, liquidity, and leverage, developed post-2008 by Basel Committee. Capital requirements: Common Equity Tier 1 (CET1) -- highest quality: ordinary shares plus retained earnings; minimum 4.5% of Risk-Weighted Assets (RWA). Tier 1 Capital: CET1 + Additional Tier 1 (AT1 -- perpetual bonds, convertible to equity at trigger); minimum 6%. Total Capital: Tier 1 + Tier 2 (subordinated debt); minimum 8%. Capital Conservation Buffer: additional 2.5% CET1; if breached, restrictions on dividends and buybacks; effective minimum CET1 = 7%. Countercyclical Buffer: 0-2.5% CET1; national regulators impose in credit boom; reduces procyclicality. G-SIB surcharge: 1-3.5% additional CET1 for Global Systemically Important Banks (JPMorgan, Citi, HSBC). Leverage Ratio: Tier 1 Capital / Total Exposure (on + off balance sheet); minimum 3%; prevents excessive balance sheet leverage regardless of RWA. Liquidity Coverage Ratio (LCR): High Quality Liquid Assets (HQLA) / Net Cash Outflows over 30 days >= 100%; ensures survival of 30-day stress. Net Stable Funding Ratio (NSFR): Available Stable Funding / Required Stable Funding >= 100%; longer-term liquidity structural requirement. Basel III fully phased in by 2025 (Basel IV further refines RWA calculation).")

p("What is the difference between market risk, credit risk, and operational risk?",
  "Bank risk categories: Credit Risk: risk that borrower defaults; largest risk for most banks; measured by Probability of Default (PD), Loss Given Default (LGD), Exposure at Default (EAD); Expected Loss = PD * LGD * EAD; capital held for Unexpected Loss (UL) -- tail scenarios; Basel IRB (Internal Ratings Based) approach allows banks to use internal models for PD/LGD. Market Risk: risk of loss from movements in market prices (interest rates, FX, equities, commodities); affects trading book; measured by VaR (Value at Risk) -- maximum loss over time horizon at confidence level (99% 10-day VaR); Stressed VaR captures tail risk; Basel FRTB (Fundamental Review of Trading Book) replaces VaR with Expected Shortfall (ES). Operational Risk: risk of loss from failed internal processes, people, systems, or external events; rogue traders (Barings Bank), cyber attacks, system outages, fraud; Basel Advanced Measurement Approach (AMA) or Standardised Approach; capital = percentage of gross income. Liquidity Risk: risk of inability to meet cash obligations; not separately capitalised under Basel but covered by LCR/NSFR. Systemic Risk: risk of failure of financial system; not a bank-level risk but addressed by macroprudential regulation (G-SIB surcharges, countercyclical buffer). Risk appetite: Board sets risk appetite statement; business lines stay within appetite; risk-adjusted return optimises within constraints.")

p("How does a credit default swap (CDS) work?",
  "CDS (Credit Default Swap): derivative providing insurance against credit event (default, bankruptcy, restructuring) of a reference entity. Structure: Protection Buyer pays periodic premium (spread, quoted in bps per year on notional); Protection Seller receives premium; if credit event occurs: seller pays buyer the difference between par and recovery value (cash settlement) or buyer delivers defaulted bonds and receives par (physical settlement). Example: $10M notional, 200bps spread = $200,000/year premium; if company defaults with 40% recovery: seller pays buyer $6M ($10M * 60% loss). CDS spread reflects credit quality: tight spreads = high credit quality; wide spreads = distressed credit; sovereign CDS for countries. Uses: hedging -- bank with large corporate loan exposure buys CDS to hedge credit risk without selling the loan (relationship preserved); speculation -- take view on credit quality without owning bonds; arbitrage -- CDS vs bond spread differences. CDS indices: CDX (North America), iTraxx (Europe) are standardised indices of 100+ CDS; liquid; used for portfolio hedging. Counterparty risk: in 2008, AIG sold enormous CDS on MBS without adequate capital; when MBS defaulted, AIG could not pay; government bailout required; post-crisis: mandatory central clearing for standardised CDS (CCP interposes between buyer and seller, eliminates counterparty risk); ISDA documentation standardises credit events.")

p("Explain interest rate risk management for banks.",
  "Interest Rate Risk in the Banking Book (IRRBB): risk that changes in interest rates adversely affect bank NII (Net Interest Income) or Economic Value of Equity (EVE). Sources: Repricing risk: assets and liabilities reprice at different times; bank with long-term fixed mortgages funded by short-term deposits suffers when rates rise (cost of funds rises, asset yield fixed). Yield curve risk: non-parallel shifts in yield curve (flattening, steepening, inversion). Basis risk: imperfect correlation between rates on different products (SOFR vs Prime rate). Optionality risk: embedded options in products (prepayment on mortgages when rates fall; early withdrawal of deposits). Measurement: NII Sensitivity: simulate parallel rate shocks (+200bps, -200bps) impact on NII over 1-2 years; short-term focus. EVE Sensitivity: present value impact of rate shocks on balance sheet; long-term focus; BCBS standard shocks include 6 scenarios (parallel up/down, steepener, flattener, short-up, short-down). Duration: measure of interest rate sensitivity; Macaulay Duration = weighted average time to receive cash flows; Modified Duration = % price change per 1% rate change; bank manages duration gap (asset duration minus liability duration). Management: hedging via interest rate swaps (fixed-to-floating or floating-to-fixed); portfolio rebalancing; natural hedging via product mix. Regulatory: BCBS IRRBB Guidelines; EBA Guidelines on IRRBB; EVE decline > 15% of Tier 1 Capital triggers supervisory concern.")

p("What is the difference between a bond yield and a bond price?",
  "Bond price and yield have inverse relationship. Bond: issuer promises to pay fixed coupon payments plus face value at maturity. Bond price: present value of all future cash flows: P = sum(Coupon/(1+r)^t) + FaceValue/(1+r)^T; where r = discount rate (yield). When yield rises: denominator in PV formula increases; price decreases. When yield falls: price rises. Yield to Maturity (YTM): internal rate of return; the yield that equates present value of all cash flows to current price; annualised return if held to maturity and coupons reinvested at same yield. Current yield: annual coupon / current price; simpler but ignores capital gain/loss. Coupon rate: fixed coupon / face value; only equals YTM when bond trades at par. Spread: yield above benchmark (Treasuries or swaps); corporate bond spread reflects credit risk, liquidity risk. Duration and convexity: Modified Duration = % price change / % yield change (negative, as price moves opposite to yield); higher duration = more interest rate sensitive; long maturity and low coupon bonds have higher duration; Convexity: second-order price sensitivity; price increases more than duration predicts when yields fall, decreases less when yields rise -- beneficial property; DV01 (Dollar Value of a Basis Point) = price change for 1bp yield change = useful for hedging.")

p("How does quantitative easing (QE) work and what are its effects?",
  "Quantitative Easing (QE): central bank creates new money to purchase financial assets (government bonds, MBS) from the open market, expanding its balance sheet. Mechanism: central bank electronically creates reserves; uses them to purchase bonds from banks; banks receive reserves instead of bonds; bond prices rise (yields fall). Effects: (1) Lower long-term interest rates: direct purchase drives down yields; reduces borrowing costs for mortgages, corporate bonds; stimulates investment and consumption. (2) Portfolio rebalancing: investors who sold bonds to central bank hold excess cash; must buy other assets (equities, real estate, corporate bonds); asset prices rise; wealth effect may increase consumer spending. (3) Currency depreciation: increased money supply and lower yields make currency less attractive; weaker currency boosts exports (supports growth), raises import prices (inflation). (4) Bank reserves: QE creates excess reserves in banking system; does not directly create money unless banks lend; bank multiplier mechanism weaker than expected in practice. (5) Inflation: primary tool post-2008 was QE + near-zero rates to avoid deflation; COVID-19 QE combined with fiscal stimulus contributed to 2021-2023 inflation surge. QT (Quantitative Tightening): reverse -- central bank reduces balance sheet by not reinvesting maturing bonds or actively selling; tightens financial conditions. Criticism: QE inflates asset prices disproportionately benefiting wealthy; transmit mechanism to real economy uncertain; central bank balance sheet hard to normalise (exit risks).")

p("Explain the role of derivatives in risk management.",
  "Derivatives: financial instruments whose value derives from underlying asset (equity, bond, commodity, currency, interest rate, credit). Risk management uses: (1) Hedging: airline buys crude oil futures to lock in fuel cost; exporter sells forward FX to lock exchange rate; reduces uncertainty about future costs and revenues. (2) Portfolio protection: pension fund buys equity put options; if market falls, puts gain value offsetting portfolio loss; costly but limits downside. (3) Interest rate management: company with floating rate debt swaps to fixed (interest rate swap) to remove uncertainty; fixed rate payer/floating rate receiver. (4) Cross-currency hedging: multinational with EUR revenues and USD expenses enters cross-currency swap; exchanges fixed USD payments for fixed EUR receipts. Types: Forwards: OTC contract to buy/sell at future date and price; customisable; counterparty risk. Futures: exchange-traded, standardised forwards; daily mark-to-market with margin; no counterparty risk (clearinghouse). Options: right (not obligation) to buy (call) or sell (put) at strike price; buyer pays premium; asymmetric payoff. Swaps: exchange of cash flows (fixed vs floating interest, one currency for another); largest OTC derivative market. Greeks (options sensitivity): Delta (price sensitivity to underlying); Gamma (delta change per underlying change); Vega (sensitivity to volatility); Theta (time decay); Rho (sensitivity to interest rate). Post-crisis regulation: mandatory central clearing (CCPs) for standardised OTC derivatives; trade reporting to repositories; increased margining requirements.")

p("What is the efficient market hypothesis and its implications?",
  "Efficient Market Hypothesis (EMH, Eugene Fama, 1970): asset prices fully reflect all available information; impossible to consistently achieve above-market returns without taking additional risk. Three forms: Weak form: prices reflect all past trading information (price history, volume); technical analysis (chart patterns, moving averages) cannot generate excess returns; empirical evidence generally supports; momentum anomaly (short-term price continuation) is evidence against. Semi-strong form: prices reflect all publicly available information (financial statements, earnings, news, economic data); fundamental analysis cannot generate excess returns; event studies show rapid price adjustment to announcements; some evidence against: value effect (cheap stocks outperform), size effect (small caps outperform), post-earnings announcement drift. Strong form: prices reflect all information including inside information; insiders cannot consistently profit; clearly violated (insider trading is profitable; why regulations against it); rejected empirically. Implications: active management underperforms after fees; passive index investing preferred; price-to-earnings ratios reflect all known information; market is best estimate of fair value; Shiller PE (CAPE): Fama-French value factor suggests EMH violated; Fama-French model adds SMB (small minus big) and HML (high minus low book-to-price) factors. Market anomalies (EMH exceptions): January effect, momentum, value premium, earnings surprise, IPO underperformance long-term. Behavioral finance (Shiller, Thaler): cognitive biases cause systematic mispricing; loss aversion, anchoring, overconfidence; markets are not always rational.")

p("How does a leveraged buyout (LBO) work?",
  "LBO (Leveraged Buyout): acquisition of a company funded primarily with debt, using target company assets and cash flows as collateral and debt repayment source. Structure: PE firm contributes 20-40% equity; rest funded by 60-80% debt (senior secured bank debt + high-yield bonds + mezzanine); post-acquisition, target company carries substantial debt. Financial model: PE firm pays 10x EBITDA (entry multiple); funds with 6x debt / 4x equity; over 5-year hold period: EBITDA grows, debt paid down, exit at 12x EBITDA; return = combination of EBITDA growth, multiple expansion, and debt paydown (financial engineering). Returns: PE targets 20-25% IRR (Internal Rate of Return) and 2-3x MOIC (Multiple of Invested Capital). Value creation levers: (1) Operational improvements: management changes, cost cuts, revenue growth, margin expansion. (2) Financial engineering: leverage amplifies equity returns; debt tax shield reduces cost of capital. (3) Multiple expansion: buy cheap (10x), sell at higher multiple (12x) due to improved business or market conditions. (4) Add-on acquisitions: buy smaller companies to bolt on, achieve synergies, expand into new markets; roll-up strategy. Characteristics of good LBO targets: stable, predictable cash flows (debt service requires consistent cash); asset-heavy (collateral); limited capex requirements; established market position; management willing to partner; not cyclical. Famous LBOs: RJR Nabisco (1989, $25bn); Toys R Us (2005, $7.5bn, ultimately bankrupted by debt load).")

p("Explain market microstructure and how electronic trading works.",
  "Market microstructure: study of how trading mechanisms affect price formation, liquidity, and transaction costs. Order types: Market order: execute immediately at best available price; guaranteed execution, uncertain price; may pay bid-ask spread. Limit order: execute only at specified price or better; uncertain execution, certain price; provides liquidity to market. Stop order: becomes market order when price reaches trigger; Stop-Limit: becomes limit order at trigger. Order Book: electronic record of all outstanding limit orders sorted by price; bid side (buy orders); ask side (sell orders); best bid and best ask = National Best Bid and Offer (NBBO). Bid-ask spread: difference between best ask and best bid; dealer/market maker profit for providing liquidity; wider spreads = less liquid; narrower = more competitive markets. Price discovery: orders arriving and matching determines fair price; fundamental value reflected through trading. High-Frequency Trading (HFT): computer algorithms executing millions of trades per second; co-located servers at exchanges for microsecond advantage; strategies: market making (continuously post bid and ask, earn spread); statistical arbitrage (exploit tiny price discrepancies between correlated instruments); latency arbitrage (faster than others to react to information). Market makers: quote continuous two-sided markets (bid and ask); earn spread; manage inventory risk; provide liquidity; designated market makers have obligations on exchanges. Dark pools: private trading venues not displaying quotes publicly; large institutional trades avoid market impact; print after execution; controversial for price discovery. Flash Crash (May 2010): algorithmic feedback loop caused Dow to drop 1000 points in minutes; circuit breakers now prevent.")

p("What is Value at Risk (VaR) and what are its limitations?",
  "VaR (Value at Risk): maximum loss expected over specified time horizon at a given confidence level. Example: 1-day 99% VaR = $1M means 99 days out of 100, daily loss will not exceed $1M; stated conversely: 1% chance of losing more than $1M in one day. Calculation methods: (1) Historical simulation: rank historical daily P&L; 99% VaR = 1st percentile of 250-day history; simple; no distributional assumptions; limited by history. (2) Parametric (Delta-Normal): assumes returns normally distributed; VaR = position size * z-score * volatility; z-score for 99% = 2.33; fast; fails when returns not normal (fat tails). (3) Monte Carlo: simulate thousands of scenarios from assumed distribution; flexible; computationally intensive. Regulatory use: Basel II and III require banks to calculate VaR for market risk capital; 10-day 99% VaR * multiplier (3+) = capital charge. Limitations: (1) Ignores tail beyond threshold: 99% VaR says nothing about magnitude of losses in the 1% tail; a $1M and a $10B loss are both just tail events. (2) Assumes normal markets: VaR historically estimated from calm periods; underestimates risk in crises (fat-tailed distributions, volatility clustering). (3) Not subadditive: Portfolio VaR can exceed sum of individual VaRs -- violates intuition that diversification reduces risk (in some methods). (4) 2008 crisis: many institutions held risks their VaR models said were safe; VaR failures led to Basel requiring Stressed VaR. Expected Shortfall (ES/CVaR): average loss given that loss exceeds VaR; captures tail magnitude; subadditive; FRTB replaced VaR with ES for trading book capital.")

p("How does quantitative asset management work?",
  "Quantitative (quant) asset management: investment decision-making using mathematical models, statistical analysis, and systematic rules rather than discretionary judgment. Factor investing: build portfolio around documented risk premia factors; Fama-French: market beta, value (HML), size (SMB); later additions: momentum (WML), quality (profitability, low investment), low volatility. Alpha generation process: (1) Hypothesis: identify predictor of returns based on theory or empirical observation. (2) Data collection: price/volume, fundamental (earnings, balance sheet), alternative (credit card data, satellite imagery, social media sentiment). (3) Backtesting: test strategy on historical data; beware overfitting (curve-fitting to past); out-of-sample testing; walk-forward analysis. (4) Signal construction: rank universe by factor (e.g., lowest P/E = highest value score); combine signals (multi-factor models). (5) Portfolio construction: mean-variance optimisation (Markowitz); risk parity; constraints (turnover, sector neutrality, factor exposure limits). (6) Execution: algorithmic execution to minimise market impact and transaction costs; VWAP/TWAP algorithms. (7) Risk management: real-time risk monitoring; factor exposure limits; stop-loss rules. Strategies: statistical arbitrage (pairs trading, mean reversion); CTA (Commodity Trading Advisors, trend following); high frequency; machine learning (NLP on earnings call transcripts, computer vision on satellite images). Challenges: factor crowding (everyone trades same factors = correlation increases; crash when all deleverage simultaneously); alpha decay (as more capital chases signal, it disappears); tail risk; data snooping bias.")

p("Explain repo markets and how they function.",
  "Repo (Repurchase Agreement): short-term collateralised borrowing; seller (cash borrower) sells securities to buyer (cash lender) and agrees to repurchase at higher price on agreed future date; difference = implied interest rate (repo rate). Mechanics: dealer borrows $100M overnight using $100M Treasury bonds as collateral; agrees to buy back tomorrow at $100,027.78 (2% annual rate * 1/360 days = ~$27.78 interest); counterparty earns 2% return on secured lending; dealer has $100M cash for one day. Haircut: lender lends less than collateral value; $100M Treasuries, 2% haircut = lender provides $98M; cushion against collateral value decline; haircut varies by collateral quality and tenor. Open repo: no fixed maturity; rolled daily; either party can terminate with notice. Term repo: fixed maturity (1 week to 1 year). Uses: (1) Dealer financing: primary dealers finance inventory of securities; buy bonds, repo them out overnight to fund purchase. (2) Short selling: investor borrows securities (reverse repo), sells short; pays repo rate plus security borrow fee. (3) Monetary policy: central bank repo operations provide/drain liquidity from banking system; Fed uses overnight repo as effective policy rate tool; Fed facility (SRF) backstops repo market stress. 2019 repo stress: short-term repo rates spiked to 10% (usually 2%); corporate tax payments + Treasury settlement drained reserves; Fed intervened. Bilateral vs Tri-party repo: bilateral: lender and borrower settle directly (custody and operations heavy). Tri-party: Bank of New York Mellon or JP Morgan acts as custodian and settlement agent; simpler operationally.")

p("What is the yield curve and what does its shape signal?",
  "Yield curve: graph of bond yields across different maturities (3-month, 1, 2, 5, 10, 30 years) for same credit quality (typically Treasuries). Normal (upward sloping): longer maturities yield more; compensation for interest rate risk (duration), inflation uncertainty, and liquidity premium over longer horizons; typical in economic expansion. Flat: short and long yields similar; transition period; uncertainty about future. Inverted: short-term yields exceed long-term; historically reliable recession predictor; 2/10 spread (10-year minus 2-year yield) inverted before every US recession since 1970; mechanism: Fed raises short rates to fight inflation; long rates fall as market prices in future rate cuts and economic slowdown; yield curve inverted in 2022-2023 at -1.1% (deepest since 1981). Humped (bell-shaped): medium-term yields highest; rare. Key spreads: 2s10s (most watched recession indicator); 3m10s (alternative recession measure); credit spread (corporate minus Treasury at same maturity = compensation for credit risk). Theories of yield curve shape: Pure Expectations Theory: long rates = expected future short rates; inverted curve means markets expect rate cuts. Liquidity Premium Theory: investors require premium for longer maturities; curve normally slopes up by ~1.5% even if rates expected flat. Market Segmentation: different investors (pension funds, money market funds) prefer specific maturities; supply/demand at each maturity drives rates independently. Practical use: swap rates (LIBOR/SOFR based) vs Treasury yields for corporate and bank pricing; mortgage rates linked to 10-year Treasury.")

p("How do central banks conduct monetary policy?",
  "Central bank monetary policy tools: (1) Policy interest rate: Fed Funds Rate (US), Bank Rate (UK), Refi Rate (ECB); set by central bank committee (FOMC, MPC, Governing Council); target rate for overnight interbank lending; transmitted to mortgage rates, corporate borrowing, savings rates; raised to fight inflation (tight money), cut to stimulate (loose money). (2) Open Market Operations (OMO): central bank buys (add reserves = looser) or sells (drain reserves = tighter) government bonds to manage short-term rates and bank reserves. (3) Reserve Requirements: fraction of deposits banks must hold as reserves (not lend out); reduced in many countries (US reduced to 0 in 2020); blunt tool, rarely adjusted. (4) Discount Window / Lender of Last Resort: banks can borrow directly from central bank at discount rate (above market rate = penalty); emergency liquidity during crises; stigma for using it. (5) Quantitative Easing (QE): purchase long-term assets to reduce long-term yields when short-term rates at zero lower bound; see QE explanation. (6) Forward Guidance: communicate future policy intentions; shape market expectations; reduce uncertainty; e.g., FOMC dot plot. (7) FX intervention: buy/sell foreign currency to influence exchange rate; rare for major currencies; common for small open economies. Transmission mechanism: policy rate change affects: short-term bank rates (immediate); long-term rates (via expectations); asset prices; exchange rate; credit availability; aggregate demand; inflation (6-18 month lag). Inflation targeting: most central banks target 2% inflation; dual mandate (Fed): price stability + maximum employment.")

p("Explain prime brokerage and its role in hedge fund operations.",
  "Prime brokerage (PB): suite of services provided by banks/broker-dealers to hedge funds, enabling complex trading strategies. Core services: (1) Securities Lending: PB lends securities to hedge fund for short selling; fund pays stock borrow fee; PB earns spread between borrow rate charged to fund and rate paid to lender; lucrative service. (2) Financing/Leverage: PB extends margin loans (secured by portfolio); hedge fund uses leverage to amplify returns; Regulation T (US) requires 50% margin for equities; PB often provides more leverage via portfolio margining. (3) Custody: hold client assets; maintain record of positions; segregation of client assets from PB balance sheet (important for insolvency protection). (4) Execution: multi-asset execution (equities, fixed income, FX, derivatives) through PB desk or third parties; best execution obligations. (5) Capital Introduction: PB connects hedge funds with institutional investors (family offices, pension funds, endowments); marketing support. (6) Technology and Reporting: portfolio risk tools, performance attribution, regulatory reporting, compliance tools. PB risk: counterparty risk for hedge fund if PB fails (Lehman Brothers 2008 -- Lehman was major PB; hedge fund assets frozen in administration for months; drove demand for multiple PBs); rehypothecation risk -- PB can reuse client collateral for own funding; limits applied post-crisis. Multi-prime: large funds use 3-5 PBs for counterparty diversification, competitive leverage rates, and operational resilience. Revenue: PB is profit centre; fees from financing, stock lending, execution; Goldman Sachs and Morgan Stanley dominate global PB.")

p("What is the difference between hedge funds and mutual funds?",
  "Hedge funds vs Mutual funds: Investor access: Mutual funds open to retail investors (SEC-registered, liquid, low minimums); Hedge funds restricted to accredited investors (net worth > $1M or income > $200K in US) or qualified purchasers ($5M+ in investments); less regulated. Structure: Mutual funds are 40 Act funds (Investment Company Act 1940) with strict requirements; Hedge funds are limited partnerships or offshore companies; general partner (fund manager) and limited partners (investors). Fees: Mutual funds: expense ratio (0.03% passive to 1%+ active); Hedge funds: 2 and 20 (2% management fee on AUM + 20% performance fee on profits above hurdle rate); some large funds 1.5 and 30; high-water mark prevents charging performance fees until previous losses recovered. Liquidity: Mutual funds: daily liquidity (sell any day); Hedge funds: lock-up period (1-2 years, then quarterly redemptions with 90-day notice); less liquid investments require long lock-ups. Strategies: Mutual funds limited to long-only (with some exceptions); Hedge funds: long-short equity, global macro, fixed income arbitrage, event-driven (M&A arbitrage, distressed), CTA (trend), credit, quant. Leverage and derivatives: mutual funds limited; hedge funds can use substantial leverage and derivatives. Transparency: Mutual funds required to disclose full portfolio quarterly; hedge funds minimal disclosure (13F filing for long equity positions only, quarterly). Returns: hedge funds historically outperformed in 2000-2010 bear markets via shorting and uncorrelated strategies; since 2010 bull market, many underperformed passive indices after fees.")

p("How is foreign exchange (FX) trading conducted?",
  "FX market: largest financial market ($7.5 trillion daily volume as of 2022); decentralised OTC market trading currency pairs. Market structure: spot FX: exchange currencies at current rate for settlement T+2 (most major pairs); FX forward: lock in exchange rate for future settlement; FX swap: simultaneously buy spot and sell forward (or vice versa); currency swap: exchange principal and interest in different currencies over longer periods; FX options: right to exchange at given rate. Market participants: banks (largest; proprietary trading, client service); central banks (FX reserves management, intervention); corporations (hedge FX exposure from international business); asset managers (investment, hedging); retail traders (small, disadvantaged by wide spreads). Major currency pairs (majors): EUR/USD (most liquid), USD/JPY, GBP/USD (cable), USD/CHF, USD/CAD, AUD/USD, NZD/USD. Pricing: bid/ask spread; pip = smallest price increment (0.0001 for most pairs, 0.01 for JPY pairs); spread for EUR/USD as tight as 0.5 pips for institutions; much wider for retail. Drivers: interest rate differentials (carry trade: borrow low-yield currency, invest in high-yield); economic data (GDP, inflation, employment); central bank statements; political risk; technical levels. EBS and Reuters: primary electronic interbank venues; also CME FX futures (standardised, exchange-traded, transparent); retail FX brokers aggregate bank prices. Carry trade: borrow JPY (low rates), invest in AUD (high rates); earns interest differential; exposed to sudden JPY appreciation (carry unwind) in risk-off episodes.")

p("What is the role of investment banks in capital markets?",
  "Investment bank (IB) functions in capital markets: (1) Equity Capital Markets (ECM): advise companies on IPOs (Initial Public Offerings) and secondary offerings; underwrite new shares (buy from issuer, sell to investors; take price risk); bookbuilding (gauge investor demand); price shares; manage stabilisation post-IPO; equity-linked products (convertible bonds). (2) Debt Capital Markets (DCM): advise on bond issuance; structure and underwrite bonds; investment grade (IG) and high yield (HY); syndicated loans; pricing based on comparable bond spreads. (3) Mergers and Acquisitions (M&A): advise buyers and sellers; valuation (DCF, LBO, trading comps, transaction comps); deal structuring; negotiation; fairness opinions; due diligence coordination; sell-side advisory (find buyer, run auction); buy-side advisory (find target, structure acquisition). (4) Syndicated Loans: arrange and underwrite large loans; syndicate portions to banks and institutional investors; leveraged loans for LBOs. (5) Restructuring: advise distressed companies or creditors on debt restructuring, Chapter 11 process, refinancing; fees based on deal value. (6) Trading and Market Making: provide secondary market liquidity for bonds, equities, FX, derivatives; position books; proprietary trading (limited post-Volcker Rule). (7) Research: sell-side research provides investment recommendations to institutional clients; supports trading relationships; research independence rules post-Spitzer settlement. Revenue: advisory fees (M&A, ECM, DCM); underwriting fees; trading revenue. Bulge brackets: Goldman Sachs, JPMorgan, Morgan Stanley, Bank of America, Citigroup.")

p("Explain the Black-Scholes option pricing model.",
  "Black-Scholes (1973): closed-form formula for pricing European options on non-dividend paying stocks. Assumptions: stock price follows geometric Brownian motion (lognormal distribution); continuous trading; no transaction costs; no dividends; constant volatility; constant risk-free rate; European exercise (only at expiry). Formula: Call price C = S*N(d1) - K*e^(-rT)*N(d2); d1 = (ln(S/K) + (r + sigma^2/2)*T) / (sigma*sqrt(T)); d2 = d1 - sigma*sqrt(T); S = stock price; K = strike; r = risk-free rate; T = time to expiry; sigma = volatility; N() = cumulative normal distribution. Interpretation: S*N(d1) = expected stock price contribution if option expires in the money; K*e^(-rT)*N(d2) = present value of expected cost; N(d2) = probability option expires in the money (risk-neutral measure). Put-Call Parity: C - P = S - K*e^(-rT); fundamental arbitrage relationship between puts and calls. Greek derivations: Delta = N(d1) for call; Gamma = N'(d1)/(S*sigma*sqrt(T)); Vega = S*N'(d1)*sqrt(T); Theta = -(S*N'(d1)*sigma)/(2*sqrt(T)) - r*K*e^(-rT)*N(d2) for call. Violations of assumptions: volatility smile/skew (implied volatility not constant across strikes -- options with lower strikes have higher IV for equities, reflecting crash risk); stochastic volatility models (Heston); jump-diffusion models (Merton); local volatility models (Dupire). Despite assumptions, Black-Scholes is the industry standard framework for quoting, hedging, and thinking about options.")

p("How do you analyse a company's financial statements for investment purposes?",
  "Financial statement analysis for equity investment: Income Statement: Revenue growth (organic vs inorganic, volume vs price); Gross margin (pricing power, cost structure); EBITDA margin (operational efficiency); Net income margin; EPS (Earnings Per Share) -- diluted; EBIT and EBITDA for comparability across capital structures. Balance Sheet: Asset quality (intangibles, goodwill -- impairment risk); Debt levels (net debt = total debt minus cash); leverage ratios (Net Debt/EBITDA typically <3x comfortable, >5x high); working capital (current ratio, quick ratio); Return on Equity (ROE = net income/equity); Return on Assets (ROA); Return on Invested Capital (ROIC = NOPAT/invested capital) -- key value creation metric. Cash Flow Statement: Operating Cash Flow (OCF) -- how much cash business generates; Capital Expenditure (maintenance vs growth capex); Free Cash Flow (FCF = OCF - capex) -- what is available for dividends, buybacks, debt repayment; FCF yield (FCF/market cap) vs earnings yield comparison. Valuation multiples: P/E (price to earnings); EV/EBITDA (enterprise value to EBITDA -- most used, capital structure neutral); P/S (price to sales -- for unprofitable companies); EV/Revenue; P/B (price to book -- banks). DCF: project FCF 5-10 years; terminal value (Gordon Growth or exit multiple); discount at WACC; sensitivity analysis on growth and discount rate. Quality red flags: revenue recognition anomalies; accounts receivable growing faster than revenue; increasing days sales outstanding; goodwill impairments; related party transactions; auditor changes; declining CFO vs net income (accruals building up).")

p("What is algorithmic trading and what strategies does it use?",
  "Algorithmic trading: use of computer programs to execute trades based on pre-defined rules, often at speeds and frequencies impossible for humans. Execution algorithms (minimise market impact): VWAP (Volume Weighted Average Price): spread order throughout day proportional to historical volume pattern; minimise deviation from day's VWAP; used by institutional investors for large orders. TWAP (Time Weighted Average Price): execute equal portions over time; simpler; ignores volume. Implementation Shortfall (IS): minimise difference between paper portfolio and executed portfolio; trades off market impact vs timing risk; dynamically adjusts. POV (Percentage of Volume): participate at X% of market volume until order complete. Alpha strategies (generate returns): Statistical Arbitrage: exploit temporary price divergences between correlated instruments; pairs trading (long-short correlated stocks); mean reversion; market neutral. Market Making: quote bid and ask; earn spread; manage inventory risk; update quotes with market moves; dominant HFT strategy. Momentum: buy recent winners, short recent losers; short holding period (seconds to days for HFT; days to months for systematic). Trend Following (CTA): buy assets in uptrend, short downtrend; longer timeframe; commodities, FX, rates. Mean Reversion: assets revert to historical mean; relative value arbitrage. HFT technical: co-location (servers at exchange); direct market data feeds (faster than consolidated tape); FPGA hardware for microsecond latency; order types (IOC, FOK); market microstructure knowledge.")

existing = sum(1 for _ in OUT.open()) if OUT.exists() else 0
print(f"Existing pairs: {existing}")
print(f"New pairs to add: {len(pairs)}")

with OUT.open("a") as f:
    for q, a in pairs:
        f.write(json.dumps({"messages": [
            {"role": "user", "content": q},
            {"role": "assistant", "content": a}
        ]}) + "\n")

total = sum(1 for _ in OUT.open())
print(f"Total upgrade_p pairs: {total}")
print("upgrade_p DONE")
