#!/usr/bin/env python3
"""Append 50 extra premium math pairs to upgrade_h.jsonl to reach 200"""
import json, pathlib

OUT = pathlib.Path('/workspace/data_upgrades')

extra = [
    ("What is the epsilon-delta definition of a limit?", "lim f(x)=L as x->a means: for every epsilon>0 there exists delta>0 such that 0<|x-a|<delta implies |f(x)-L|<epsilon. The quantifier ordering is critical: epsilon is the challenge, delta is the response. This rigorous definition replaced intuitive notions of infinitesimals."),
    ("What is L'Hopital's rule?", "If lim f(x)=lim g(x)=0 (or both infinite), then lim f(x)/g(x) = lim f'(x)/g'(x), provided the latter limit exists. It resolves indeterminate forms 0/0 and infinity/infinity. Proved using the generalised mean value theorem."),
    ("What is the squeeze theorem?", "If g(x)<=f(x)<=h(x) near a and lim g(x)=lim h(x)=L, then lim f(x)=L. Used to prove lim_{x->0} sin(x)/x=1 by squeezing between cos(x) and 1. The fundamental tool for establishing limits by bounding."),
    ("What is the chain rule?", "If g is differentiable at x and f is differentiable at g(x), then (f composed with g)'(x)=f'(g(x))*g'(x). In Leibniz notation dy/dx=(dy/du)*(du/dx). Generalises to multivariate settings as the Jacobian chain rule."),
    ("What is integration by parts?", "Integral of u dv = u*v - integral of v du. Derived from the product rule. Used when a product's antiderivative is unknown: integral of x*e^x dx = x*e^x - e^x + C. The LIATE rule guides choice of u."),
    ("What is a partial derivative?", "The partial derivative of f with respect to x_i is the derivative holding all other variables fixed. The gradient vector of partial derivatives points in the direction of steepest ascent. The Hessian matrix of second partials describes local curvature."),
    ("What is Green's theorem?", "The line integral around a closed curve C of (P dx + Q dy) equals the double integral over the enclosed region D of (dQ/dx - dP/dy) dA. It relates line integrals around closed curves to double integrals — a 2D case of Stokes' theorem."),
    ("What is the divergence theorem?", "The flux of a vector field F through a closed surface S equals the triple integral of div(F) over the enclosed volume V. It relates volume sources to surface flux and is fundamental in electromagnetism and fluid mechanics."),
    ("What is uniform convergence?", "A sequence of functions f_n converges uniformly to f on E if the supremum of |f_n(x)-f(x)| over E goes to zero. Uniform convergence preserves continuity and allows interchange of limit with integral. Weierstrass M-test: if |f_n(x)|<=M_n and sum M_n converges, then sum f_n converges uniformly."),
    ("What is a Taylor series convergence condition?", "The Taylor series of f at a converges to f(x) when the remainder R_n(x)->0. Analytic functions equal their Taylor series everywhere. e^x, sin(x), cos(x) are analytic on all of R. The function e^(-1/x^2) at x=0 has all derivatives zero yet is not identically zero — an example of non-analyticity."),
    ("What is the ratio test?", "For sum a_n, let L=lim |a_{n+1}/a_n|. If L<1, the series converges absolutely; if L>1, diverges; if L=1, inconclusive. Effective for series with factorials or exponentials. Derived from comparison with a geometric series."),
    ("What is absolute versus conditional convergence?", "A series converges absolutely if the sum of absolute values converges. Absolute convergence implies convergence; the converse is false. The alternating harmonic series converges conditionally. By Riemann's rearrangement theorem, conditionally convergent series can be rearranged to converge to any value."),
    ("What is a Cauchy sequence?", "A sequence is Cauchy if the distance between terms becomes arbitrarily small: for every epsilon>0 there exists N such that m,n>N implies d(x_m,x_n)<epsilon. In complete spaces, every Cauchy sequence converges. In Q, sequences approximating sqrt(2) are Cauchy but have no limit in Q."),
    ("What is the Jordan curve theorem?", "Every simple closed curve (homeomorphic to the circle) in the plane divides it into exactly two regions: a bounded interior and an unbounded exterior. Intuitively obvious but technically subtle — the curve could be wildly fractal. Proved using algebraic topology."),
    ("What is Poincare duality?", "For a compact oriented n-manifold M without boundary, H^k(M) is isomorphic to H_{n-k}(M). It pairs cohomology and homology via the cap product with the fundamental class. For a compact surface of genus g: H^1 has rank 2g, equal to H_1."),
    ("What is the Borsuk-Ulam theorem?", "For any continuous map f from the n-sphere to R^n, there exists a point x such that f(x)=f(-x). Corollary (ham sandwich theorem): any n measurable sets in R^n can be bisected simultaneously by a single hyperplane. It has numerous combinatorial applications."),
    ("What is Brouwer's fixed point theorem?", "Any continuous map of a compact convex set in R^n to itself has a fixed point. Proved using homology (the boundary sphere has non-trivial homology). Used to prove Nash equilibrium existence and equilibrium in economic models."),
    ("What is de Rham cohomology?", "De Rham cohomology H^k_dR(M) is the quotient of closed k-forms by exact k-forms (ker d / im d). By de Rham's theorem it is isomorphic to singular cohomology with real coefficients. Poincare lemma: every closed form on a contractible domain is exact."),
    ("What is a tensor?", "A tensor is a multilinear map from products of vector spaces and their duals to scalars. A (p,q)-tensor has p contravariant and q covariant indices and transforms accordingly under change of basis. Tensors generalise vectors (1,0) and covectors (0,1) to arbitrary rank."),
    ("What is the exterior algebra?", "The exterior algebra of V has the relation v wedge v=0 (so u wedge v = -v wedge u). The k-th exterior power has dimension C(n,k). Differential k-forms are sections of the k-th exterior power of the cotangent bundle — the natural objects to integrate over k-dimensional manifolds."),
    ("What is a fibre bundle?", "A fibre bundle (E,B,pi,F) has total space E, base B, projection pi:E->B, and fibre F over each point. Locally E looks like B cross F. Vector bundles have vector space fibres; principal bundles have structure group G. Connections encode parallel transport and curvature."),
    ("What is characteristic class theory?", "Characteristic classes (Chern, Pontryagin, Stiefel-Whitney) are cohomology classes of a vector bundle measuring its twisting. Chern classes live in even-degree cohomology for complex bundles. They are obstructions to global sections and are used in the Atiyah-Singer index theorem."),
    ("What is an exact sequence?", "A sequence A->B->C is exact at B if the image of A->B equals the kernel of B->C. Long exact sequences in homology arise from short exact sequences of chain complexes. The snake lemma, five lemma, and horseshoe lemma are key tools in homological algebra."),
    ("What is homological algebra?", "Homological algebra studies chain complexes and their homology. Derived functors (Tor, Ext) measure the failure of functors to be exact. Projective resolutions compute Tor; injective resolutions compute Ext. Spectral sequences systematically compute homology from filtrations."),
    ("What is model theory?", "Model theory studies mathematical structures and the first-order sentences they satisfy. Godel's completeness theorem: every consistent first-order theory has a model. Compactness: if every finite subset has a model, so does the whole theory. Lowenheim-Skolem: theories with infinite models have models of every infinite cardinality."),
    ("What is a Turing machine?", "A Turing machine has a read-write head on an infinite tape, a finite set of states, and transition rules. Turing-computable functions exactly match those computable by any reasonable model of computation (Church-Turing thesis). Turing machines decide decidable languages and semi-decide recognisable ones."),
    ("What is computational complexity?", "Complexity theory classifies problems by resources needed. Hierarchy: L subset NL subset P subset NP subset PSPACE subset EXPTIME. SAT is NP-complete (Cook-Levin); QBF is PSPACE-complete. The P vs NP question asks whether efficient solution follows from efficient verification."),
    ("What is an error-correcting code?", "A linear code over F_q forms an [n,k,d] code: length n, dimension k, minimum distance d — can correct floor((d-1)/2) errors. Reed-Solomon, Hamming, and LDPC codes are standard. The Singleton bound limits d<=n-k+1; codes achieving it are called MDS codes."),
    ("What is the probabilistic method?", "The probabilistic method (Erdos) proves existence of combinatorial objects by showing a random construction succeeds with positive probability. It proves R(k,k)>2^(k/2) and constructs expander graphs. No explicit construction is needed — existence is enough."),
    ("What is Szemeredi's regularity lemma?", "Every large enough graph can be partitioned into a bounded number of roughly equal parts such that edges between most pairs behave like random bipartite graphs. A cornerstone of extremal combinatorics with applications to arithmetic progressions in dense sets."),
    ("What is the Green-Tao theorem?", "Green and Tao (2004) proved that the primes contain arbitrarily long arithmetic progressions. The proof uses Gowers uniformity norms, a relative Szemeredi theorem, and deep analytic number theory. It resolved a long-standing conjecture and opened the field of additive combinatorics."),
    ("What is random matrix theory?", "Random matrix theory studies eigenvalue distributions of large random matrices. Wigner's semicircle law: the empirical spectral distribution of a real symmetric random matrix converges to the semicircle distribution. GUE universality connects eigenvalue statistics to quantum chaos and Riemann zeta function zeros."),
    ("What is a CW complex?", "A CW complex is built by attaching cells of increasing dimension: 0-cells (points), 1-cells (intervals), 2-cells (disks), etc. Most spaces of interest are CW complexes. Cellular homology computes homology from the CW structure efficiently using the cellular chain complex."),
    ("What is a spectral sequence?", "A spectral sequence is a sequence of bigraded modules with differentials converging to a target (co)homology. Starting typically from E_2 (Serre spectral sequence: E_2 = H*(B; H*(F))) and converging to H*(E) for a fibration F->E->B. It computes homology of complex spaces systematically."),
    ("What is a sheaf?", "A sheaf on a topological space assigns data (groups, rings) to open sets with restriction maps satisfying a gluing axiom: data agreeing on overlaps glues to a unique global section. Sheaf cohomology measures obstructions to globalising local data and is central in algebraic geometry."),
    ("What is a derived category?", "The derived category of an abelian category inverts quasi-isomorphisms (chain maps inducing isomorphisms on homology). It provides the right framework for derived functors, homological algebra, and is the language of modern algebraic geometry and representation theory."),
    ("What is symplectic geometry?", "Symplectic geometry studies manifolds with a closed non-degenerate 2-form omega. Hamilton's equations follow from the symplectic structure. Liouville's theorem states Hamiltonian flows preserve phase space volume. The Arnold conjecture on fixed points of Hamiltonian diffeomorphisms drove much of modern symplectic topology."),
    ("What is Nash's embedding theorem?", "Every smooth Riemannian manifold can be isometrically embedded into some Euclidean space R^N. Nash's original proof (1956) was a landmark of hard analysis, using iteration techniques later systematised as the Nash-Moser implicit function theorem."),
    ("What is an abelian category?", "An abelian category is an additive category where every morphism has a kernel and cokernel, every mono is a kernel, and every epi is a cokernel. Examples: abelian groups, modules over a ring, sheaves. The natural setting for homological algebra and derived functors."),
    ("What is the Navier-Stokes Millennium Problem?", "Whether smooth solutions to the 3D Navier-Stokes equations (modelling viscous fluid flow) exist globally from smooth initial data is one of the seven Clay Millennium Prize Problems. 2D existence and uniqueness is established; the 3D case remains one of the deepest open problems in analysis."),
    ("What is percolation theory?", "Percolation theory studies random subgraphs where each bond is present with probability p. There is a critical probability p_c above which an infinite connected component exists almost surely. The phase transition and critical behaviour are studied using renormalisation group methods."),
    ("What is K-theory in mathematics?", "K-theory assigns groups K_n(X) to topological spaces or rings, encoding information about vector bundles (topological K-theory, Atiyah-Hirzebruch) or projective modules (algebraic K-theory, Quillen). It connects analysis (index theorem), topology, and number theory."),
    ("What is motivic cohomology?", "Motivic cohomology is a universal cohomology theory designed to underlie all Weil cohomology theories. Voevodsky's construction proved the Milnor conjecture and Bloch-Kato conjecture using motives, winning him the 2002 Fields Medal. Motives are the universal cohomological shadow of algebraic varieties."),
    ("What is etale cohomology?", "Etale cohomology provides cohomology groups for algebraic varieties over arbitrary fields. For varieties over finite fields F_q, it provides l-adic cohomology with a Frobenius action whose eigenvalues encode point counts over finite field extensions — key to Deligne's proof of the Weil conjectures."),
    ("What is a number field?", "A number field K is a finite extension of Q. Its ring of integers consists of elements satisfying monic integer polynomials. Ideals in the ring of integers factor uniquely into prime ideals (though elements may not). The class group measures the failure of unique factorisation."),
    ("What is the Langlands correspondence?", "The Langlands correspondence predicts a bijection between n-dimensional Galois representations and automorphic representations of GL(n), matching L-functions on both sides. Partially proved (Wiles for elliptic curves, Lafforgue for function fields). The grand unified theory of number theory."),
    ("What is second-order logic?", "Second-order logic allows quantification over predicates and functions. More expressive than first-order: it can characterise N up to isomorphism. But it lacks completeness and compactness — there is no recursively enumerable complete axiomatisation of second-order logical validity."),
    ("What is constructive mathematics?", "Constructive mathematics requires that proofs of existential statements exhibit explicit witnesses. Brouwer's intuitionism rejects excluded middle. Martin-Lof type theory provides a rigorous foundation where proofs are programs and propositions are types (Curry-Howard correspondence)."),
    ("What is the Poisson summation formula?", "For a Schwartz function f, sum_{n in Z} f(n) = sum_{n in Z} f_hat(n) where f_hat is the Fourier transform. It connects a sum over a lattice to a sum over the dual lattice. Central in analytic number theory (theta functions, L-functions) and signal processing (sampling theorem)."),
    ("What is the Riemann-Roch theorem?", "For a compact Riemann surface of genus g and a divisor D: dim H^0(D) - dim H^0(K-D) = deg(D) - g + 1, where K is the canonical divisor. It computes the dimension of spaces of meromorphic functions with prescribed poles. The Grothendieck-Riemann-Roch theorem extends this to algebraic varieties."),
    ("What is the abc conjecture?", "For coprime positive integers a,b,c with a+b=c, the conjecture states that c is bounded by a power of the radical (product of distinct prime factors) of abc: for every epsilon>0, c < rad(abc)^(1+epsilon) for all but finitely many triples. Mochizuki claimed a proof in 2012, still contested."),
]

# Read existing pairs count
existing = sum(1 for _ in OUT.open()) if OUT.exists() else 0
print(f"Existing pairs: {existing}")

with OUT.open("a") as f:
    for q, a in extra:
        f.write(json.dumps({"messages": [
            {"role": "user", "content": q},
            {"role": "assistant", "content": a}
        ]}) + "\n")

total = sum(1 for _ in OUT.open())
print(f"Total after append: {total} pairs in upgrade_h.jsonl")
assert total >= 200, f"Only {total} — need 200"
print("PASS: 200+ premium mathematics pairs ready.")
