#!/usr/bin/env python3
"""gen_f_fill28.py -- final batch to cross 1000 upgrade_f pairs"""
import json, pathlib

OUT = pathlib.Path('/workspace/data_upgrades/upgrade_f.jsonl')
OUT.parent.mkdir(parents=True, exist_ok=True)

pairs = []
def p(q, a):
    pairs.append((q, a))

p("What is port scanning and service enumeration?",
  "Port scanning: discover open network ports and services on target; foundation of network reconnaissance. TCP scanning: SYN scan (half-open, stealth): nmap -sS TARGET; send SYN; receive SYN-ACK = open, RST = closed, no response = filtered; no full connection; less likely logged than connect scan; requires root; Connect scan: full TCP three-way handshake; no root required; more reliably detected; UDP scan: nmap -sU TARGET; UDP ports (DNS 53, SNMP 161, DHCP 67/68, NTP 123, TFTP 69, NetBIOS 137, RADIUS 1812); slower (no handshake; timeout-based); service enumeration: version detection: nmap -sV TARGET (probe open ports; identify service and version); banner grabbing: nc -nv TARGET 22 (connect; read service banner; reveals: OpenSSH 8.2p1 Ubuntu). Nmap command examples: nmap -sV -p- --min-rate 5000 TARGET (all 65535 ports, fast, version detection); nmap -A TARGET (aggressive: OS detection, version, script scan, traceroute); nmap -sC TARGET (default script scan); nmap -p 80,443,8080,8443 TARGET (specific ports); nmap -iL targets.txt (scan list from file); nmap -oA output TARGET (save results in all formats: .nmap, .xml, .gnmap). NSE (Nmap Scripting Engine): nmap --script vuln TARGET (vulnerability scanning); nmap --script http-enum TARGET (web directory enumeration); nmap --script smb-enum-shares TARGET (enumerate SMB shares); nmap --script banner TARGET (grab banners from all open ports). Masscan: fastest port scanner; 10M packets/second; masscan -p0-65535 TARGET --rate=100000; use for quick discovery before detailed nmap; combine: masscan to find open ports, nmap for version and scripts. Service-specific enumeration: FTP (21): anonymous login (ftp TARGET; anonymous); list files; SMTP (25): VRFY/EXPN (user enumeration on some mail servers); telnet TARGET 25; VRFY admin; SMB (445): nmap --script smb-enum-shares,smb-enum-users TARGET; smbclient -L //TARGET -N (null session); HTTP (80/443): web application; gobuster for directories; detect CMS; SNMP (161): snmpwalk -v 2c -c public TARGET (community string enumeration); reveals: system info, network interfaces, running processes, installed software; common community string: public, private, community; LDAP (389/636): ldapsearch -x -H ldap://TARGET -s base namingContexts (anonymous LDAP query). Evasion: slow scanning: nmap -T1 or -T2; decoys: nmap -D RND:5 TARGET; fragment packets: nmap -f TARGET; randomise port order: nmap --randomize-hosts TARGET.")

p("What is XSS via file uploads?",
  "XSS via file uploads: inject malicious JavaScript through file upload functionality; bypass normal XSS input filtering; achieve stored XSS or client-side execution. Attack types: SVG XSS: SVG files are XML; can contain JavaScript; upload SVG file with embedded script: <?xml version=1.0 standalone=no?><!DOCTYPE svg PUBLIC -//W3C//DTD SVG 1.1//EN http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd><svg xmlns=http://www.w3.org/2000/svg width=200 height=200><script type=text/javascript>alert(XSS)</script></svg>; if server serves uploaded SVG with Content-Type: image/svg+xml: browser renders as SVG and executes JavaScript; impact: if served from same origin: full XSS; access cookies, localStorage, DOM; HTML file upload: upload .html file with XSS payload; if served from same origin: full XSS; EXIF metadata XSS: metadata in JPEG files; if application displays EXIF data without sanitisation: XSS possible (limited; requires EXIF display); polyglot files: file that is valid as multiple formats; JPEG+JavaScript: file starts with JPEG magic bytes (FFD8FF); also valid JavaScript (content after JPEG header); serve as Content-Type: text/javascript; script src to polyglot file; PDF XSS: PDF files can contain JavaScript (PDF JavaScript); if displayed in browser PDF renderer: executes; older browsers more susceptible; modern browsers sandboxed. Why file upload XSS bypasses filters: normal XSS filtering focuses on HTML form inputs; file upload less scrutinised; server may not inspect file content for scripts; file type validation may pass SVG as image; Content-Type from upload may be trusted without verification. Exploitation: upload SVG; share link; victim clicks link; browser renders SVG; JavaScript executes in origin context; cookie theft: document.cookie; localStorage theft: localStorage.getItem(token); CSRF token theft; key logging. Mitigation: serve uploaded files from separate domain (uploads.cdn.example.com): XSS limited to CDN domain, cannot access main app cookies or localStorage; Content-Type validation: serve uploaded files with correct content type (image/jpeg, image/png) regardless of file content; never serve as text/html; SVG: if SVG upload allowed: sanitise SVG (remove script tags and event handlers) -- DOMPurify sanitises SVG; or serve as Content-Disposition: attachment (download instead of display); CSP: frame-src restrictions limit where content can be embedded; File validation: reject SVG if not needed; magic bytes check; re-encode images (strips SVG/JavaScript from JPEG by re-encoding through image library).")

p("What is Active Directory certificate services (AD CS) and its security risks?",
  "AD CS (Active Directory Certificate Services): Microsoft PKI implementation; issues certificates for users, computers, and services; significant attack surface in many environments. AD CS components: Certificate Authority (CA): root CA or subordinate CA; issues certificates; Windows Certificate Authority; Certificate Templates: define what certificates CA will issue; what attributes; who can request; Web Enrollment (certsrv): IIS-based certificate request interface; OCSP Responder: certificate revocation status; Network Device Enrollment Service (NDES): SCEP for network devices. Security vulnerabilities (ESC classes from SpecterOps research): ESC1 -- Misconfigured certificate templates: template allows requestor to specify arbitrary Subject Alternative Name (SAN); SAN can be domain admin UPN or email; request certificate for admin@corp.com; authenticate as domain admin with issued cert; ESC2 -- Misconfigured certificate templates (Any Purpose EKU or no EKU): certificate can be used for any purpose; includes client authentication; request cert; use for domain auth; ESC3 -- Misconfigured enrollment agent templates: enrollment agent cert allows requesting certs on behalf of any user; chain to admin auth; ESC4 -- Vulnerable certificate template access control: low-privileged user can modify template settings; modify to ESC1; ESC5 -- Vulnerable PKI object access control: DACL on CA object, CA server, RPC/DCOM interface; ESC6 -- EDITF_ATTRIBUTESUBJECTALTNAME2 flag: CA configured to include SAN from certificate request even if not specified in template; any template request can specify SAN; ESC7 -- Vulnerable CA access control: user has ManageCA or ManageCertificates; can issue pending/failed certificates; ESC8 -- NTLM relay to AD CS HTTP endpoints: web enrollment does not require authentication; NTLM relay to certsrv; obtain certificate for relayed machine account; authenticate as domain controller; NTLM relay attack: PetitPotam coerces DC to authenticate to attacker; attacker relays to certsrv; gets DC certificate; DCSync. Tools: Certify (SharpCollection): enumerate misconfigured templates; request certificates; Certipy (Python): enumerate and exploit ESC attacks; BloodHound: 5.0+ includes AD CS nodes and edges; shows certificate-based attack paths. Remediation: audit certificate templates: restrict who can request; disable SANs unless required; remove write access from non-admins; PKINIT restrictions; Require CA manager approval for sensitive templates; NTLM relay: enforce HTTPS + EPA (Extended Protection for Authentication) on AD CS web enrollment; disable HTTP enrollment if not needed.")

p("How do you perform cloud penetration testing on AWS?",
  "AWS penetration testing: assess Amazon Web Services environment; identity, configuration, services, and data security. Permission to test: AWS Acceptable Use Policy: no need to request permission for penetration testing of own account; prohibited without permission: DDoS attacks on AWS infrastructure, port flooding, protocol flooding; rules of engagement: document scope; test only authorised accounts; no attacking AWS shared infrastructure. Reconnaissance: credential discovery: AWS credentials in source code, S3 public buckets, instance metadata, EC2 user data; tools: truffleHog, git-secrets, detect-secrets; S3 public bucket enumeration: aws s3 ls --no-sign-request s3://bucket-name (anonymous access); bucket name guessing: company-name, company-name-backup, company-name-logs; cloud_enum (automated bucket/storage enumeration); network discovery: nmap scanning of EC2 instances; AWS metadata for instance topology; account enumeration: error message differences for valid vs invalid account IDs (some services reveal account ID); IAM enumeration: if credentials obtained; Principal Mapper (PMapper): IAM permission analysis; identify privilege escalation paths; aws iam list-users, list-roles, list-policies; Pacu: AWS exploitation framework; modular; reconnaissance and exploitation. IAM privilege escalation: if initial access with limited IAM credentials; PMapper: automatically identifies escalation paths; common paths: CreateRole + AttachRolePolicy (create role with admin; assume it); PassRole + CreateFunction (pass privileged role to Lambda function; invoke function); CloudFormation stack with role; AttachUserPolicy; CreateLoginProfile; SetDefaultPolicyVersion; UpdateAssumeRolePolicy; Exploit: create admin role and assume it; PMapper: python3 -m principalmapper --profile TARGET graph create; python3 -m principalmapper --profile TARGET analysis --privesc. Service exploitation: SSRF to IMDS: EC2 applications with SSRF can reach 169.254.169.254; retrieve instance role credentials; exploit S3: misconfigured bucket policies; public objects; bucket ACLs; lambda exploitation: environment variable secrets; injection via event sources; RDS: public accessibility; default credentials; ECS/EKS: container escape; overprivileged task roles; API Gateway: authentication bypass; injection. Post-exploitation in AWS: CloudTrail evasion (delete events if permissions allow); persistence (IAM user, access key, role backdoor); data exfiltration (S3 sync); privilege escalation to OrganizationAccountAccessRole (cross-account admin). Tools: Pacu (AWS exploitation); ScoutSuite (multi-cloud security audit); CloudMapper (AWS account visualisation); cloudsplaining (IAM policy analysis); Prowler (security assessment); ROADtools (Entra ID equivalent); CloudFox (privilege escalation paths).")

p("What is broken authentication in web applications?",
  "Broken authentication: weaknesses in authentication implementation; allow attackers to compromise credentials, session tokens, or bypass authentication. Common broken authentication vulnerabilities: weak passwords accepted: no minimum length, no complexity, common passwords allowed (admin, password123); no protection against credential stuffing (list of breached username/password combos tested against site); account enumeration: login error reveals different message for valid vs invalid username: username not found (reveals username does not exist) vs incorrect password (reveals username exists); test: different response time, response body, status code between valid and invalid username; fix: identical error for both (invalid credentials); brute force: no rate limiting on login endpoint; lockout not implemented; CAPTCHA absent; credential stuffing: billions of breached credentials available; attackers test against new site; requires: rate limiting, MFA, anomaly detection (many different source IPs). Insecure forgot password: reset token in URL (logged by proxies and browsers); token not expired after use; token not time-limited (valid for days); token predictable (sequential, time-based); token sent over insecure channel; user enumeration via forgot password (reveals if email registered); exploit: request reset for victim; intercept token from URL or predict; reset password; gain access. Default credentials: admin/admin, admin/password, guest/guest; devices, applications, cloud services with default credentials; test: admin panels, development ports, API test interfaces; tools: SecLists default credentials list; DefaultCreds-Cheat-Sheet. Session fixation: attacker sets victim session ID (via URL or cookie injection); victim logs in; session ID elevated to authenticated; attacker uses same ID; fix: generate new session ID on login. Weak session tokens: sequential (predict next token); base64 encoded user ID (decode and modify); short (brute forceable); time-based (predictable); test: intercept session token; decode (base64, JWT without validation, URL decode); try to predict or manipulate; tools: Burp Sequencer: analyse session token randomness; statistical test; Hackvertor (Burp extension): decode and modify tokens. Broken logout: logout does not invalidate server-side session; cookie cleared client-side but session still valid on server; exploit: capture session token before logout; reuse after logout; fix: delete server-side session on logout; for JWTs: token blocklist or short expiry.")

p("What is the PTES (Penetration Testing Execution Standard)?",
  "PTES (Penetration Testing Execution Standard): comprehensive methodology defining phases, tools, and deliverables for penetration tests; industry reference. Seven phases: (1) Pre-engagement Interactions: scope definition; rules of engagement; emergency contact procedures; legal authorisation; NDA; payment terms; timeline; deliverable format; goals and success criteria. (2) Intelligence Gathering: OSINT; technical, organisation, and people reconnaissance; passive and active methods; tools: theHarvester, Maltego, Recon-ng, Shodan; deliverable: target profile; attack surface map. (3) Threat Modelling: identify highest-priority targets; threat actors relevant to organisation; attack vectors most likely to be exploited; map to scope and intelligence gathered; create attack plan focusing on highest-risk areas. (4) Vulnerability Analysis: active scanning: Nessus, OpenVAS; web scanning: Burp Suite, Nikto, OWASP ZAP; manual analysis; network scanning: nmap; service enumeration; identify vulnerabilities in discovered services and applications. (5) Exploitation: exploit identified vulnerabilities; gain access; demonstrate impact; evidence collection; tools: Metasploit, Burp Suite, custom exploits, Impacket, CME; escalate privileges; document each step. (6) Post Exploitation: maintain access; explore network; privilege escalation; lateral movement; data collection (evidence of what could be reached); assess business impact; cleanup (remove tools, artefacts -- restore to pre-test state except as agreed). (7) Reporting: executive summary; technical findings; attack narrative; evidence (screenshots, command output); risk ratings; remediation recommendations; retesting suggestions; appendices (tool output, references). PTES vs OWASP Testing Guide: PTES: general penetration testing (network, application, social engineering); OWASP Testing Guide: web application specific; very detailed web vulnerability testing methodology; complement each other; use OWASP Testing Guide for web portion of PTES. Why PTES matters: provides client expectations framework; testers follow consistent methodology; comparable engagements; reduces scope ambiguity; quality assurance. Scope document based on PTES: both tester and client sign; explicitly lists: in-scope, out-of-scope, permitted techniques, prohibited techniques, timeline, contacts, reporting requirements.")

p("What is threat actor attribution in cyber threat intelligence?",
  "Threat actor attribution: identify who is responsible for a cyberattack; extremely difficult; high confidence rare; significant implications. Attribution challenges: attacker deception: use other actors tools and TTPs to mislead (false flag); route through multiple countries; use rented infrastructure; shared infrastructure: multiple actors use same bulletproof hosting, same C2 framework (Cobalt Strike, Metasploit); common tools provide plausible deniability; evidence destruction: attackers clean traces; delete logs; attribution evidence: technical indicators: malware code similarities (unique coding patterns, reused code, compiler artefacts), infrastructure overlap (IP addresses, domains reused across campaigns), TTPs overlap (same techniques, same order), language/cultural artefacts in malware (encoding, comments, error messages), timestamps (compile time, activity time suggests timezone), certificate details. Attribution levels: low confidence: technical overlap only (another actor could have same tool); medium confidence: multiple technical indicators consistent with known actor; high confidence: signals intelligence (SIGINT), human intelligence (HUMINT), technical plus intelligence community corroboration; near-certain: nation-state intelligence assessment; criminal indictment (NSA/FBI joint attribution with evidence disclosed in court). Named threat actors: APT (Advanced Persistent Threat) groups: APT1 (China, Comment Crew), APT28 (Russia, Fancy Bear/Cozy Bear = SVR), APT29 (Russia, Midnight Blizzard), APT38 (North Korea, Lazarus financial theft), APT41 (China, Winnti, dual espionage and financial), TA505 (criminal, ransomware); naming conventions: CrowdStrike (Bears = Russia, Pandas = China, Kittens = Iran, Chollima = North Korea); Microsoft (Volt Typhoon, Midnight Blizzard, Scattered Spider). Why attribution matters (and does not): strategic value: policy response, diplomatic pressure, sanctions, indictments, offensive cyber operations; tactical value: predict next campaigns, understand actor motivation (financial, espionage, disruption), tailor defences to known actor TTPs; operational value: detect infrastructure reuse, share intelligence about same actor across victims; warning: over-reliance on attribution: actors change tools and TTPs; false attribution misdirects response; focus on TTP-based defence regardless of actor (mitigate MITRE ATT&CK techniques; any actor using them is covered).")

p("What is security validation and breach attack simulation?",
  "BAS (Breach and Attack Simulation): continuously simulate attacks against real production environment; validate controls work as expected; find gaps before real attackers. Why BAS: security teams assume controls work; BAS proves they do (or do not); changes happen constantly (new firewall rules, WAF rule changes, SIEM tuning); controls may drift from known-good state; BAS detects drift; frequency: automated BAS runs 24/7 or daily; penetration test: annual or quarterly; gap between tests is risk window. How BAS works: BAS platform: agents deployed in production environment; agent simulates attack behaviours safely (no actual damage); traffic generated matches real attack patterns; results: which attacks were blocked, detected, or missed; coverage: antivirus bypass simulation (known malware samples; check EDR/AV blocks), email simulation (phishing email delivery; check email gateway blocks), web attack simulation (attack agent sending HTTP attacks to WAF; check WAF blocks), network simulation (lateral movement simulation; check network controls), exfiltration simulation (data exfiltration attempts; check DLP and egress controls). BAS vs penetration testing: penetration testing: human-driven; creative; finds unknown vulnerabilities; quarterly or annual; BAS: automated; known attack library; validates controls against known attacks; continuous; complement not replace each other. Specific validation capabilities: EDR validation: run known malware sample; verify EDR quarantines; MITRE ATT&CK technique execution: execute atomic tests; verify SIEM alerts; email gateway: send phishing simulation; verify gateway catches; WAF: send OWASP Top 10 payloads; verify WAF blocks; lateral movement: simulate PsExec, WMI movement; verify network detection. Products: SafeBreach: comprehensive; 10,000+ attack playbooks; Cymulate: enterprise BAS; MITRE ATT&CK mapped; AttackIQ: ATT&CK-aligned; purple team integration; Picus Security: threat exposure management; CISA recommended BAS practices; open-source: Atomic Red Team (manual BAS); Caldera (MITRE, automated ATT&CK emulation). Reporting: control effectiveness score (% of attacks blocked + detected); comparison to previous period (is coverage improving?); ATT&CK coverage heat map; prioritised gaps for remediation; compare to industry benchmark.")

p("What are common application layer DDoS attack patterns?",
  "Application layer DDoS (Layer 7 DDoS): target application resources not bandwidth; more sophisticated; harder to distinguish from legitimate traffic. Why layer 7 effective: small volume can exhaust application resources; each request: DB query, compute, API call; attacker sends slow/moderate request volume; each request expensive server-side; 10,000 legitimate req/sec sustainable; 1,000 crafted req/sec to expensive endpoint: server exhaustion. Attack types: HTTP flood: high volume HTTP GET or POST requests; volumetric but targeting application (not just network bandwidth); simple mitigation: rate limit per IP; sophisticated: distributed botnet with many IPs; rate limit per session or browser fingerprint; slow HTTP attacks: Slowloris: open many HTTP connections; send headers extremely slowly; server waiting for complete request; consumes connection slots; servers have limited concurrent connections; mitigation: connection timeout; limit connections per IP; RUDY (R-U-Dead-Yet): POST request with huge Content-Length; send body one byte per minute; server waits for complete body; HTTP range attack: Range: bytes=0-1 requests; server processes many overlapping ranges; expensive server-side computation; Cache busting: add random query parameter (search?q=keyword&rand=12345); CDN cache miss every request; all requests reach origin; overwhelm origin server behind CDN; login endpoint targeting: authentication endpoints computationally expensive (bcrypt); focus flood on login; server cannot process other requests; search endpoint targeting: complex database queries; attacker triggers expensive searches. Mitigation: rate limiting per IP and per session; JS challenge (client-side JavaScript execution proves legitimate browser vs bot); CAPTCHA for suspicious traffic; device fingerprinting (TLS fingerprint, HTTP/2 fingerprint, browser characteristics); geographic blocking (if attack concentrated in specific region); CDN / DDoS scrubbing (Cloudflare, Akamai, Radware, AWS Shield Advanced): absorb L7 attacks at edge; detect and mitigate application layer attacks; autoscaling: additional capacity during attack (buy time; not solution since cost may be unsustainable); IP reputation: block known bad actor IPs; challenge unknown IPs; WAF rules targeting specific attack patterns; circuit breaker: application-level: if error rate exceeds threshold: return cached or simplified response; shed load gracefully. Cloudflare application layer DDoS: 40M+ requests/second blocked during largest documented L7 attack (2022).")

p("What is security control assurance?",
  "Security control assurance: verify controls work as intended; not just that they exist. Why assurance matters: compliance checkbox: control documented as present; actual effectiveness not verified; example: SIEM alerting rule exists on paper; never tested; attacker uses technique covered by rule; alert never fires; assurance: control exists AND works as intended. Assurance methods: technical testing: penetration testing validates controls prevent/detect attacks; red team exercises test detection and response controls; BAS (Breach and Attack Simulation): continuous automated control validation; vulnerability scanning: confirms patches applied; configuration review: confirms hardening settings applied; Control effectiveness testing: SIEM alert test: generate test event matching alert rule; confirm alert fires within expected time; EDR test: run known malicious sample; confirm quarantine action occurs; backup restore test: restore from backup; verify data integrity and completeness; MFA test: attempt login without second factor; confirm blocked; firewall rule test: attempt to make connection blocked by policy; confirm blocked; log completeness test: generate specific events; verify all appear in SIEM; alert timing test: measure how long from event to alert (MTTD from control perspective). Continuous control monitoring: automated tools check control status continuously; GRC platform (ServiceNow GRC, RSA Archer, MetricStream) with automated evidence collection; security ratings (SecurityScorecard, BitSight): external view of control effectiveness; Tenable.sc / Qualys: continuous vulnerability assessment (patch control); CSPM: continuous cloud configuration compliance check; SOAR playbooks trigger control tests on schedule. Assurance reporting: control health dashboard: all controls with current status; passing (green), failing (red), degraded (amber); trend: is control health improving?; exceptions: controls that have failed assurance; risk acceptance or remediation plan; audit evidence: control test results stored; available for auditors; third-party assurance: SOC 2 Type II: auditor tests controls over 6-12 month period; not just point-in-time; ISO 27001 surveillance audit: annual check controls still operating; penetration test report: independent evidence of control effectiveness (or failure). NIST SP 800-53A: assessment procedures for each control in NIST 800-53; defines how to assess each control (examine, interview, test); provides structured assessment methodology.")

existing = sum(1 for _ in OUT.open()) if OUT.exists() else 0
print(f"Existing pairs: {existing}")
print(f"New pairs to add: {len(pairs)}")

with OUT.open("a") as f:
    for q, a in pairs:
        f.write(json.dumps({"messages": [
            {"role": "user", "content": q},
            {"role": "assistant", "content": a}
        ]}) + "\n")

total = sum(1 for _ in OUT.open())
print(f"Total upgrade_f pairs: {total}")
if total >= 1000:
    print("upgrade_f TARGET MET -- 1000+ pairs!")
else:
    print(f"Need {1000-total} more pairs")
